### ISSUE TITLE
Search: doesn't return any results

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1000]
Version: 3.2.8 beta
URL: 
https://www.beta.patricbrc.org/view/FeatureList/?keyword(%22fig%7C573.3197.peg.4497%22)
User ID: KPNs_4_Houston

fig|573.3197.peg.4497

To clarify, the search does not work when you have "all types" selected in 
the drop down, but it does when you ask for the specific type, which is 
strange.

<img width="1374" alt="screen shot 2016-10-07 at 9 31 51 am" src="https://cloud.githubusercontent.com/assets/1236463/19193750/ec28f51a-8c70-11e6-8816-2b29e82998a5.png">

<img width="678" alt="screen shot 2016-10-07 at 9 32 26 am" src="https://cloud.githubusercontent.com/assets/1236463/19193765/fbf62170-8c70-11e6-9424-e3e168cc6890.png">

**Comment by dmachi** [comment]
This works on alpha now, please verify.

**Comment by dmachi** [comment]
This works on alpha now, please verify.

**Comment by mshukla1** [comment]
fixed, verified on alpha.
