### ISSUE TITLE
Search: top search results unexpected

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1001]
I searched for Brucella and top genome and specialty genes are NOT Brucella. 

If I run the same search on public site and in solr I get the correct results at the top. 

We need to have match the search logic, scoring and sorting to that on the public site. 

<img width="1437" alt="screen shot 2016-10-07 at 9 24 07 am" src="https://cloud.githubusercontent.com/assets/1236463/19193846/5880051e-8c71-11e6-8c2b-858d254c4dfb.png">

<img width="533" alt="screen shot 2016-10-07 at 9 28 48 am" src="https://cloud.githubusercontent.com/assets/1236463/19193859/61b6444a-8c71-11e6-9a9e-44d571b2c935.png">

**Comment by dmachi** [comment]
This has already been fixed on alpha and appears to match what is in production.  Please verify.
