### ISSUE TITLE
Search: can't search for private genomes

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1002]
Version: 3.2.8 beta
URL: https://www.beta.patricbrc.org/search/?keyword(%22573.3197%22)
User ID: KPNs_4_Houston

I have a private genome, "573.3197". When I search for "573.3197" It is 
not found.

**Comment by mshukla1** [comment]
The issue was submitted by Jim. 

I tried to search for my private genomes, and they all returned 0 results in the global search. 

<img width="1154" alt="screen shot 2016-10-07 at 9 47 11 am" src="https://cloud.githubusercontent.com/assets/1236463/19194443/32c22ca6-8c73-11e6-9a08-3f30f638423e.png">

<img width="505" alt="screen shot 2016-10-07 at 9 47 20 am" src="https://cloud.githubusercontent.com/assets/1236463/19194452/3af0a416-8c73-11e6-9b7e-c856706e16fc.png">

**Comment by dmachi** [comment]
Fixed on alpha

**Comment by mshukla1** [comment]
fixed. verified on alpha.
