### ISSUE TITLE
Data: don't mark user genome as complete

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1003]
Version: 3.2.8 beta
URL: 
https://www.beta.patricbrc.org/view/Taxonomy/573?and(eq(public,%22true%22),eq(genome_status,%22Complete%22))#view_tab=proteinFamilies
User ID: KPNs_4_Houston

A user's genome should not be considered "complete" unless dictated by the 
user. I submitted a bunch of plasmids that were considered "complete" 
because they had a single contig.

**Comment by hyoo** [comment]
is it done?

**Comment by mshukla1** [comment]
Updated the script. Will be deployed soon.

**Comment by hyoo** [comment]
@mshukla1 is this deployed?
