### ISSUE TITLE
Feature table: can't download data for private genome

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1004]
Version: 3.2.8 beta
URL: 
https://www.beta.patricbrc.org/view/GenomeList/?keyword(%22573.3197%22)#view_tab=features
User ID: KPNs_4_Houston

The download icon in the top left of the features tab for a genome is not 
working. I can't download in any format from this. I am working on a 
private genome now.

Can't download data using the action bar on the right either!!!

**Comment by dmachi** [comment]
Fixed.  Will be on alpha soon.

**Comment by mshukla1** [comment]
Working on alpha.
