### ISSUE TITLE
Login: takes a while to load

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1005]
Version: 3.2.8 beta
URL: 
https://www.beta.patricbrc.org/view/FeatureList/?keyword(%22fig%7C573.3197.peg.1%22)#view_tab=features
User ID: KPNs_4_Houston

the login window is taking 3-4 seconds to load

**Comment by JoshuaVSherman** [comment]
link to pull request
https://github.com/PATRIC3/p3_web/pull/662

**Comment by hyoo** [comment]
#1763
