### ISSUE TITLE
Tables: remove columns 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1007]
Version: 3.2.9 beta
URL: 
https://www.beta.patricbrc.org/view/GenomeList/?keyword(KPN1954ec)#view_tab=features
User ID: KPNs_4_Houston

I kind of wish that the headers on the tables had little Xs so that I could 
just blow away the columns that aren't useful to me.

**Comment by dmachi** [comment]
This won't happen any time soon as it will require the underlying grid to be modified.  Additionally, while this is a nice to have feature, most of the tables are too cramped and the little X will be hard to get positioned in the column headers in the space available.

**Comment by mshukla1** [comment]
I agree with your assessment, Dustin. I think making show/hide columns more noticeable, would suffice.

**Comment by hyoo** [comment]
closing per discussion.
