### ISSUE TITLE
Table downloads: organize columns

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1008]
The order of the columns in the downloaded files (genome and feature) seems random, which makes it very hard to read / understand / parse! 

We need to organize/oder columns to make them easier to understand and more usable to the users.

Also need to make sure that the columns are consistent in text, csv and excel files.

-Maulik

**Comment by hyoo** [comment]
we needs some configuration on data-api level. I will work on this.

**Comment by hyoo** [comment]
duplicate #1222

**Comment by mshukla1** [comment]
fixed. verified on beta.
