### ISSUE TITLE
PFS: showing genomes not in current scope

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1009]
I was looking at PG fams for a single private genome. 
Mycobacterium vaccae test 123

Then, I changed it to PLfams and it sudden;t started showing data for several Ecoli genomes!!!

<img width="1123" alt="screen shot 2016-10-07 at 2 18 32 pm" src="https://cloud.githubusercontent.com/assets/1236463/19202681/3fcb6ef0-8c99-11e6-8a48-6eca5ef375a9.png">

**Comment by hyoo** [comment]
I cannot reproduce with my private genome. I am annotating one more genome and will try to reproduce this issue. However, did you ever opened another window and used protein family tab? I guess this shouldn't matter, but just in case.

**Comment by mshukla1** [comment]
I can't reproduce it either!
