### ISSUE TITLE
data issue or website issue - I haven't figured it out yet

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#101]
if you start at genome list of Mtb complex 
http://www.beta.patricbrc.org/portal/portal/patric/Taxon?cType=taxon&cId=77643
click on genome list and filter by keyword tb-arc bovis, you'll get 9 genomes which is what I expected (and the same as the production website)

if you start at genome list of M. bovis
http://www.beta.patricbrc.org/portal/portal/patric/GenomeList?cType=taxon&cId=1765&dataSource=&displayMode=&pk=&kw=
and filter on tb-arc, you'll get 3 genomes - which is NOT what I expected (and NOT the same as the production website)

I don't know if this has to do w/ some sort of reclassifications (I also sent mail to Maulik about a Clostridium difference, with fewer genomes in the beta release than the production release) or if it's a bug in the data or if it's a bug in the website (probably not the latter, but what do I know)

**Comment by mshukla1** [comment]
This is because 6 of the bovis genomes have been renamed / reclassified by ncbi as tuberculosis now. For the same taxon id, they changed the species name. Hence, even though they are still named bovis, they are not available under bovis.
