### ISSUE TITLE
Removed file from uploads, but name remains-beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1010]
Its not a big deal, but it will be a bit confusing to users.  I was uploading the contig files one at a time.  So I had completed one annotation submission, then reset the page to start the second.  When I went to upload the new contigs, the old file was there.  I clicked on the X to remove it, and while the X disappeared, the name remained.  It was a bit confusing. 
<img width="706" alt="screen shot 2016-10-08 at 1 24 25 pm" src="https://cloud.githubusercontent.com/assets/11475316/19214868/c6e2e414-8d5b-11e6-943d-de287e0e745e.png">

It did go away after I uploaded the second file, but it would be best if the name disappeared after I clicked the X.

**Comment by hyoo** [comment]
verified.
