### ISSUE TITLE
Not again!!!!!  Genes in feature table for genome not in order!!

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1011]
I REALLY hate this.  When you are looking at a genome, and click on the feature table, the first gene you see should be the first gene in the genome!  We fixed this on production, but I see that its back to being scrambled on beta.  PLEASE FIX THIS!
<img width="1035" alt="screen shot 2016-10-08 at 1 55 30 pm" src="https://cloud.githubusercontent.com/assets/11475316/19215020/e03a3058-8d5f-11e6-9965-7fd57b6794b5.png">

**Comment by hyoo** [comment]
https://github.com/PATRIC3/p3_web/commit/bb676024aed3e6034a1c40ee2b28a49d3ef8cd90

this patch reverted sorting fix.

**Comment by dmachi** [comment]
Yes, this was known to be incorrect when not coming in from a search.  However, there isn't currently a mechanism to override the default search via link, but will be needed for this task.

**Comment by dmachi** [comment]
Reverted the default sort for feature grid.  Added defaultSort hashparam to override the default sorting order.  Modified search links to use defaultScore=-score. Will be on alpha soon.

**Comment by mshukla1** [comment]
Verified. By default when the feature table is loaded for a genome, it sorts feature by location. 

However, once sort order is changed, it is hard to go back to default. Harry is going to work on that.
