### ISSUE TITLE
Global search not able to find gene in privately annotated genome in beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1013]
Results in beta:
<img width="1181" alt="screen shot 2016-10-10 at 7 35 48 am" src="https://cloud.githubusercontent.com/assets/11475316/19236304/a2637f08-8ec4-11e6-8735-23fdd00e3ee4.png">

Results in alpha:
<img width="565" alt="screen shot 2016-10-10 at 8 36 47 am" src="https://cloud.githubusercontent.com/assets/11475316/19236318/bbcbace0-8ec4-11e6-9095-ef9697f0ed7c.png">

**Comment by dmachi** [comment]
This was fixed late last week and pushed to alpha, but has not yet been pushed to beta.

**Comment by mshukla1** [comment]
Fixed, verified on alpha.
