### ISSUE TITLE
Jobs view doesn't load when going directly to page-alpha

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#1014]
I think this is a relatively new issue since it's not an issue on beta.

1) Go directly to https://www.alpha.patricbrc.org/job/ (or go there and reload page) and my jobs list doesn't show up.  I noticed the list will show up after sorting.

![image](https://cloud.githubusercontent.com/assets/1194246/19243394/239e6520-8edd-11e6-8fd9-395c20d0140b.png)

**Comment by dmachi** [comment]
My updates last week caused this as they aren’t complete yet.  The updates i committed last week address some of the performance issues with the Jobs Grid, but also cause this issue.  Will take a look when i can.

**Comment by dmachi** [comment]
Fixed.
