### ISSUE TITLE
Disappointing experience waiting for genome groups to load protein familes

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1018]
Had 3 groups that had approx. 150 genomes.  It never loaded.  Heart broken.

**Comment by ARWattam** [comment]
<img width="982" alt="screen shot 2016-10-10 at 3 25 51 pm" src="https://cloud.githubusercontent.com/assets/11475316/19248416/ebe4a484-8efd-11e6-87c4-311e6546213c.png">
This is what the page looked like after 5 minutes to load the groups to a genome list.

**Comment by ARWattam** [comment]
This is what the group protein family page looked like after 15 minutes.  Sigh.  Workshop looking not so great....
<img width="1238" alt="screen shot 2016-10-10 at 3 27 04 pm" src="https://cloud.githubusercontent.com/assets/11475316/19248461/1e75920a-8efe-11e6-9b9b-667c70a90bae.png">

**Comment by dmachi** [comment]
This has been fixed locally, will be up on alpha/beta soon

**Comment by mshukla1** [comment]
selected a group with 237 genomes, it loaded in about 4 minutes. 

We should see if we can improve the performance. However, it is not broken any more.
