### ISSUE TITLE
workspace genome collection date formatting issue?

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#102]
for many genomes, the collection date (at least as displayed on the website in the genome list, either production or beta) is only a year (has to do w/ HIPAA).   For example Mycobacterium bovis B2 7505, collection date is 2006, but if I add that genome to my workspace and look at the collection date as part of a genome group it says 12/31/05

**Comment by dmachi** [comment]
Harry fixed this issue when fixing genome metadata.
