### ISSUE TITLE
PFS: Move filter buttons up on protein family sorter?-beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1021]
Users might not realize that they have to hit the filter button after entering text in.    Just by hitting return, they might think that they are going to be able to do it, and find that nothing happens.  They have to scroll down to see that there is a filter button.  If it was was above the text box, then they could see that button.
<img width="518" alt="screen shot 2016-10-10 at 3 32 15 pm" src="https://cloud.githubusercontent.com/assets/11475316/19248600/12afb80a-8eff-11e6-93e2-c3526040ab4b.png">

**Comment by mshukla1** [comment]
Harry tried to reduce the number of genomes displayed and changed the family selection to dropdown to reduce size. 

However, the filter button is still below the fold and may not be visible to user without scrolling. We need to revisit this after the florida workshop. 

It would be good if we can make the button float at the bottom right corner of layer.

**Comment by mshukla1** [comment]
#996 duplicate.
