### ISSUE TITLE
Genome Overview: in host name pie chart, some number doesn't match with genome list

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1023]
Example: https://www.beta.patricbrc.org/view/Taxonomy/780#view_tab=overview
The pie slice for "Tick" indicates 3 genome, but the genome list shows 25.
<img width="1000" alt="screen shot 2016-10-10 at 3 37 26 pm" src="https://cloud.githubusercontent.com/assets/6361802/19248685/7cc6a564-8eff-11e6-91db-293d46644315.png">

<img width="1280" alt="screen shot 2016-10-10 at 3 32 04 pm" src="https://cloud.githubusercontent.com/assets/6361802/19248650/5c4a169a-8eff-11e6-96c7-562995139b19.png">

**Comment by hyoo** [comment]
because you have several tick variations.

**Comment by chmao1** [comment]
But the two numbers need to be the same

**Comment by chmao1** [comment]
If you click on the pie chart which indicates 3 genomes, then the resulting genome list should show only 3 genome, not 25.

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/28537515-c688217a-7070-11e7-9033-41d578338122.png)

Actually, this is what we designed for partial matching and there is no way to restrict to the exact match.
