### ISSUE TITLE
"Copy" button in Create/Add to Group popup box should be labeled "Add"

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1024]
The popup box says Add Genome to Group, but the button choices are "Cancel" and "Copy." It is a bit confusing.

**Comment by dmachi** [comment]
Fixed and will be on alpha soon.

**Comment by mshukla1** [comment]
changed to copy to "add". However, the pop up window title still says, "Copy selection to group".

I think we need to systematically go over all add to group widgets and make the language consistent.

**Comment by mshukla1** [comment]
@dawenx Can you change the window title from "Copy Selection to Group" to "Add selected items to group" ?

This should apply to all genome and feature group creation pop ups. 

<img width="418" alt="screen shot 2017-09-17 at 12 44 46 pm" src="https://user-images.githubusercontent.com/1236463/30523408-7275c9aa-9ba6-11e7-8b49-8686f3702273.png">

**Comment by dawenx** [comment]
I will work on that. Hovering on "Group" button shows "Copy selection to a new or existing group", I would assume we want to change "Copy" to "Add" as well.

**Comment by dawenx** [comment]
![for_issue_1024](https://user-images.githubusercontent.com/26723038/30544928-1efcdba0-9c56-11e7-9d34-f418271ef25a.png)

**Comment by mshukla1** [comment]
Yes, it would be good to have consistent language everywhere!

**Comment by dawenx** [comment]
I went through all files and made sure all hover and popup title are consistent. PR submitted.

**Comment by mshukla1** [comment]
Thanks, Dawen.
