### ISSUE TITLE
PFS tool: submission form text

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1025]
selecting multiple genome groups to compare. 

when the name is long, the text wraps around and overlaps with the next group. 

![screen shot 2016-10-10 at 2 38 05 pm](https://cloud.githubusercontent.com/assets/1236463/19248747/5c0b6c7c-8ef7-11e6-82f8-401d5b134814.png)

**Comment by hyoo** [comment]
verified.
