### ISSUE TITLE
PFS: Identifiers over the three columns in protein family sorter are missing

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1026]
Only the long time PATRIC user will know that the first column means Present, the second is Absent, and the third is Mixed.
<img width="310" alt="screen shot 2016-10-10 at 3 42 42 pm" src="https://cloud.githubusercontent.com/assets/11475316/19248865/6fa9d1f2-8f00-11e6-99d8-d2b0a1f6ccf7.png">

**Comment by mshukla1** [comment]
Column headings are added. 

However, I think they take up too much space and look verbose. We should try to come up with intuitive icons for include/exclude/dont care or use P/A/E or +/x/- add column heading with mouseover.

**Comment by mshukla1** [comment]
This has been addressed. Closing the ticket. 

<img width="303" alt="screen shot 2017-09-17 at 12 51 05 pm" src="https://user-images.githubusercontent.com/1236463/30523447-ebfdc610-9ba6-11e7-999a-8d06a9f83415.png">
