### ISSUE TITLE
Feature list header should not display all the ids

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1028]
I hope the query condition to be one line and make expandable.
<img width="1696" alt="screen shot 2016-10-10 at 2 46 20 pm" src="https://cloud.githubusercontent.com/assets/1236467/19248929/69223110-8ef8-11e6-84ec-3af93ccfe0ea.png">

**Comment by hyoo** [comment]
this blocks content panel. cannot go further.

**Comment by dmachi** [comment]
I'm not sure why it wrapped around like this on your screen, it normally just does horizontal scrolling.  However, I've updated FeatureList to use the QueryToEnglish function which avoids this problem.

It now does something like:

FEATURE ID IS PATRIC.325775.3.CP007541.CDS.275009.276094.fwd OR PATRIC.325775.3.CP007541.CDS.274635.274895.fwd ... 43 more ... ( 45 Genome Features )

**Comment by dmachi** [comment]
Will push this change to alpha soon.

**Comment by mshukla1** [comment]
verified on beta.
