### ISSUE TITLE
Job submission forms: genome groups should be listed most recent first

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1029]
In the selection panel, genome groups should be listed most recent first. 

-Maulik

![screen shot 2016-10-10 at 2 47 49 pm](https://cloud.githubusercontent.com/assets/1236463/19248958/8ac62fc4-8ef8-11e6-8046-e6ebc1d64763.png)

**Comment by hyoo** [comment]
This is fixed on beta. However, per discussion during the Florida workshop, we need both options for sorting. This will be another ticket. I am closing this one.
