### ISSUE TITLE
genome metadata in workspace (sorry if this is a dup)

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#103]
sorry if this is a dup - but I did a quick scan and didn't see it anywhere
for genome groups in my beta workspace, it doesn't allow me to hide/show the entire list of genome metadata items

**Comment by dmachi** [comment]
Harry, can you setup the correct set of columns in https://github.com/dmachi/p3-web/blob/master/public/js/p3/widget/GenomeGrid.js   If something needs a formatter, the formatting functinos are in https://github.com/dmachi/p3-web/blob/master/public/js/p3/widget/formatter.js

The Feature grid columns are currently defined in https://github.com/dmachi/p3-web/blob/master/public/js/p3/widget/viewer/FeatureList.js

**Comment by dmachi** [comment]
Verified harry's fix.
