### ISSUE TITLE
not able to create a group from the heatmap selection

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1031]
https://www.beta.patricbrc.org/view/GenomeList/?in(genome_id,(1136217.3,1136218.3,562.7825,562.7197,562.10905,562.10904,1048254.4,1038927.9,1068614.3,1068615.3,1068616.3,1068617.3,1068618.3,1068619.3,1068620.3,1068621.3,1068623.3,1068624.3,1068622.3,562.8470,562.8471,562.7928,562.7171,562.7173,562.7175,562.7170,562.9825,562.7165,562.7012,562.7038,562.7168,562.8453,1090928.3,1090927.4,562.10847,1042804.3,1038927.6,1038927.7,1038927.8,1446497.3,1446507.3,1446590.3,562.5742,1151243.3,1335303.3,1335304.3,562.5741,562.7434,562.10844,1133852.3,1048765.4,1133853.3,1134782.3,1240758.3,1240759.3,1240760.3,1240761.3,1240762.3,1240763.3,1240764.3,1240765.3,1240766.3,1240767.3,1240768.3,1240769.3,1240770.3,1240771.3,1240772.3,1240773.3,1240774.3,1240775.3,1240776.3,1240777.3,1240778.3,1240779.3,1048265.3,1048266.3,562.7176,562.9029,562.7174,562.9028,562.7172,562.9037,562.9042,562.9041,562.9039,562.9040,562.9036,562.9031,562.9035,562.9033,562.9032,562.9034,562.10839,562.10838,562.10837,562.10835,562.10834,562.10836,1038844.18,1040638.5,1038927.5,1038927.4,1048256.3,1048254.3,1038927.9,1048334.3))#view_tab=proteinFamilies

**Comment by mshukla1** [comment]
fixed on beta.
