### ISSUE TITLE
PFS: Need to download family with members

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1032]
Where's the download button?
<img width="1432" alt="screen shot 2016-10-10 at 3 48 52 pm" src="https://cloud.githubusercontent.com/assets/11475316/19249006/2437be22-8f01-11e6-862d-758081d13b51.png">

**Comment by hyoo** [comment]
do you want to download family info? data as see in the grid? just for checking.

**Comment by ARWattam** [comment]
Generally, we can download the list of protein families, or with the more advanced version, download the protein families and all their members.

----- Original Message -----

**Comment by hyoo** [comment]
reopen for verification

**Comment by mshukla1** [comment]
Download for the entire table has been added. However, it doesn't support downloading family with members yet. Need it add it later.

**Comment by hyoo** [comment]
Downloading family member in legacy is working only with limited number of families. There are some tickets reporting this issue. Given that, currently we have a work around. you can select multiple families and click members button, then you have all the participating feature list with family info. Absolutely, you can download from there. Can this replace the downloading members?

**Comment by mshukla1** [comment]
Addressed as mentioned in earlier comments.
