### ISSUE TITLE
Blast output

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1033]
I just blasted the K-12 16S gene against itself.  I end up with 5 or 6 HSPs representing hits to  the 16S genes in this genome but there is no way to tell which contig they are on.  Probably not a problem for K-12, but its  a huge problem for other genomes.   Also, the alignment view is good, but the list output is also necessary for getting a fast idea of what was matched.  For instance I am attaching a list output from the seed.

<img width="1110" alt="screen shot 2016-10-10 at 2 46 33 pm 1" src="https://cloud.githubusercontent.com/assets/7661533/19248927/67661b84-8ef8-11e6-8cdc-662518e4df98.png">

<img width="316" alt="screen shot 2016-10-10 at 2 49 50 pm" src="https://cloud.githubusercontent.com/assets/7661533/19249018/d5e58c66-8ef8-11e6-929b-e9f8f799e08f.png">

Also to clarify, in this case, I had one result because I went against one genome, but I should have had a table row for each HSP.

**Comment by mshukla1** [comment]
contig accession and descriptions have been added in the resulttable. verified on beta.
