### ISSUE TITLE
BLAST: search for RNA coding genes

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1035]
I should be able to blast against all genomic features, especially RNA genes.

<img width="729" alt="screen shot 2016-10-10 at 2 51 41 pm" src="https://cloud.githubusercontent.com/assets/7661533/19249060/1454e73a-8ef9-11e6-98d5-7dc6d843fb3f.png">

**Comment by dmachi** [comment]
Rebecca says (and so its REALLY IMPORTANT) that when you take a rRNA gene and blast it against genes and proteins, BLAST should return the rRNA genes, but it did not!  Its clear that the BLAST database only has protein coding genes, and not RNA genes.  MUST BE FIXED BEFORE VALERIE TRIES IT!!!!

**Comment by olsonanl** [comment]
@mshukla1 the blast databases used are GENOME.PATRIC.ffn  which appear to have only pegs. I'm assuming we'll need to regenerate those with all features included.

**Comment by mshukla1** [comment]
We do not include RNAs in the ffn files, they are kept separately in frn files. I am creating BLAST databases for all frn files, so that they can be used in the same way as ffn files.

**Comment by olsonanl** [comment]
Does that include all non-peg features or just the RNAs?

**Comment by mshukla1** [comment]
RNA BLAST is working now. We have frn databases created for individual genomes and we also have specialized blast database for 16s RNAs. 

I have tested them both on beta and they are working. 

-Maulik
