### ISSUE TITLE
Pathway page empty

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1037]
Tried to access Glycolosis/Gluconeogenisis pathway 00010, but got empty pathway page when I clicked on the <Map> button.

![screen shot 2016-10-10 at 3 55 35 pm](https://cloud.githubusercontent.com/assets/3188570/19249226/61aca532-8f02-11e6-8a5b-647868ab9eed.png)

**Comment by mshukla1** [comment]
seems to be fixed now on beta.
