### ISSUE TITLE
<Print> button on pathway map page does nothing?

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1039]
I clicked it, but nothing seemed to happen.

https://www.beta.patricbrc.org/view/PathwayMap/annotation=PATRIC&genome_ids=441771.6,502347.3,1432557.3,585054.5,1115512.3,1115515.3,556266.3&pathway_id=00010

![screen shot 2016-10-10 at 4 08 35 pm](https://cloud.githubusercontent.com/assets/3188570/19249510/f6a29f06-8f03-11e6-8e14-20acf069cb7d.png)

**Comment by hyoo** [comment]
Not implemented yet. Do we really need this? just for checking.
