### ISSUE TITLE
Annotation app overrides my name

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#104]
If I give the annotation app a tax ID and a scientific name, it overrides my name with the one mapped by the tax id. I should be able to define the name used. For example, in this job I gave it some random name and a random taxid, and it gave me the name corresponding to the random taxid. 

$VAR2 = {
          'scientific_name' => 'uncultured type I methanotroph T1-06',
          'contigs' => '/olson@patricbrc.org/home/buchnera.fa',
          'domain' => 'Bacteria',
          'output_file' => 'buch3',
          'tax_id' => '105967',
          'output_path' => '/olson@patricbrc.org/home/out1',
          'code' => '11'
        };

**Comment by aswarren** [comment]
A patch for this has been committed.
