### ISSUE TITLE
BLAST result: cannot select all results.

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1041]
I am currently in safari.  When I check the select all check box in the top left, I get dark blue highlighting of the first few rows, and not check boxes. When I select again, the first few get checked (even though the top checkbox is now unchecked).  It is currently impossible to check all.

<img width="1248" alt="screen shot 2016-10-10 at 3 18 19 pm" src="https://cloud.githubusercontent.com/assets/7661533/19249780/ce60c68c-8efc-11e6-8cda-a715cdbcf1ea.png">

<img width="1267" alt="screen shot 2016-10-10 at 3 13 57 pm" src="https://cloud.githubusercontent.com/assets/7661533/19249726/8e60f214-8efc-11e6-8a46-1fdbbd4c9db2.png">

**Comment by hyoo** [comment]
This could be possible when the results are not distinct. Would you give me a query so that I can reproduce it?

**Comment by mshukla1** [comment]
@hyoo try the folloing query against ref.fna. select all is not working in safari and in chrome.

>fig|511145.12.peg.3032|b2938|VBIEscCol129921_3032| Biosynthetic arginine decarboxylase (EC 4.1.1.19) [Escherichia coli str. K-12 substr. MG1655 | 511145.12]
atgagctcccaggaagccagcaagatgctgcgtacttacaatattgcctggtggggcaat
aactactatgacgttaacgagctgggccacattagcgtgtgcccggacccggacgtcccg
gaagctcgcgtcgatctcgcgcagttagtgaaaactcgtgaagcacagggccagcgtctg
cctgcactgttctgtttcccacagatcctgcagcaccgtttgcgttccattaacgccgcg
ttcaaacgtgcgagggaatcctacggctataacggcgattacttccttgtttatccgatc
aaagttaaccagcaccgccgcgtgattgagtccctgattcattcgggcgaaccgctgggt
ctggaagccggttccaaagccgagttgatggcagtactggcacatgctggcatgacccgt
agcgtcatcgtctgcaacggttataaagaccgcgaatatatccgcctggcattaattggc
gagaagatggggcacaaggtctatctggtcattgagaagatgtcagaaatcgccattgtg
ctggatgaagcagaacgtctgaatgtcgttcctcgtctgggcgtgcgtgcacgtctggct
tcgcagggttcgggtaaatggcagtcctccggcggggaaaaatcgaagttcggcctggct
gcgactcaggtactgcaactggttgaaaccctgcgtgaagccgggcgtctcgacagcctg
caactactgcacttccacctcggttcgcagatggcgaatattcgcgatatcgcgacaggc
gttcgtgaatccgcgcgtttctatgtggaactgcacaagctgggcgtcaatattcagtgc
ttcgacgtcggcggcggtctgggcgtggattatgaaggtactcgttcgcagtccgactgt
tcggtgaactacggcctcaatgaatacgccaacaacattatctgggcgattggcgatgcg
tgtgaagaaaacggtctgccgcatccgacggtaatcaccgaatcgggtcgtgcggtgact
gcgcatcacaccgtgctggtgtctaatatcatcggcgtggaacgtaacgaatacacggtg
ccgaccgcgcctgcagaagatgcgccgcgcgcgctgcaaagcatgtgggaaacctggcag
gagatgcacgaaccgggaactcgccgttctctgcgtgaatggttacacgacagtcagatg
gatctgcacgacattcatatcggctactcttccggcatctttagcctgcaagaacgtgca
tgggctgagcagctttatttgagcatgtgccatgaagtgcaaaagcagctggatccgcaa
aaccgtgctcatcgtccgattatcgacgagctgcaggaacgtatggcggacaaaatgtac
gtcaacttctcgctgttccagtcgatgccggacgcatgggggatcgaccagttgttcccg
gttctgccgctggaagggctggatcaagtgccggaacgtcgcgctgtgctgctggatatt
acctgtgactctgacggtgctatcgaccactatattgatggtgacggtattgccacgaca
atgccaatgccggagtacgatccagagaatccgccgatgctcggtttctttatggtcggc
gcatatcaggagatcctcggcaacatgcacaacctgttcggtgataccgaagcggttgac
gtgttcgtcttccctgacggtagcgtagaagtagaactgtctgacgaaggcgataccgtg
gcggacatgctgcaatatgtacagctcgatccgaaaacgctgttaacccagttccgcgat
caagtgaagaaaaccgatcttgatgctgaactgcaacaacagttccttgaagagttcgag
gcaggtttgtacggttatacttatcttgaagatgagtaa
