### ISSUE TITLE
Virulence Gene curation page is not implemented in Beta

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1042]
The virulence gene annotation pages for VFs that were curated in PATRIC are missing in beta.
Here is an example from the production site:
https://www.patricbrc.org/portal/portal/patric/SpecialtyGeneEvidence?source=PATRIC_VF&sourceId=STM474_0039

**Comment by chmao1** [comment]
This is implemented and will be available in the next build.

**Comment by mshukla1** [comment]
Page added. Verified on alpha.
