### ISSUE TITLE
Pathway list timed out from genome group

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1045]
Only 88 genomes, and PATRIC bailed on me....
<img width="1313" alt="screen shot 2016-10-10 at 4 22 40 pm" src="https://cloud.githubusercontent.com/assets/11475316/19249917/de98eabc-8f05-11e6-9284-31ece7d34098.png">

**Comment by ARWattam** [comment]
Hmmm....but then after I went back on page and loaded it again..it seemed to work.
<img width="1176" alt="screen shot 2016-10-10 at 4 24 04 pm" src="https://cloud.githubusercontent.com/assets/11475316/19249960/0ace00a4-8f06-11e6-9c9b-a0ce94656ad8.png">

**Comment by dmachi** [comment]
I think this is essentially  a duplicate of #1048

**Comment by hyoo** [comment]
I tested with 121 genomes and works.
