### ISSUE TITLE
Pathways page of "Top 

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1047]
List of pathways for a genome takes a long time to load

https://www.beta.patricbrc.org/view/Genome/83332.12#view_tab=pathways

**Comment by hyoo** [comment]
@dmachi This is the one I mentioned earlier that I want you to look at, but later commented it was working. However, I cannot load this page again. Don't know what is going on.

**Comment by dmachi** [comment]
I think something it is trying to load before it has a search or list of ids from the overall view.  If you remove the patric filter it works (and it works when you add it back).

**Comment by hyoo** [comment]
reopen for verification

**Comment by mshukla1** [comment]
fixed. verified on alpha.
