### ISSUE TITLE
Blast

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1049]
If you do a blast, and then you hit "edit and resubmit" to rerun the blast, it carries over the previous page and concatenates it to the bottom of the page. 

![image](https://cloud.githubusercontent.com/assets/7661533/19250096/460e3c54-8efe-11e6-9713-727b0de63afa.png)

**Comment by hyoo** [comment]
Yes. Actually, the original submit form was hidden and re-opened when you clicked the "edit and resubmit"

**Comment by hyoo** [comment]
I don't think this is a bug or fixable item.
