### ISSUE TITLE
user uploads files of unspecified type and gets confused

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#105]
On Mar 24, 2015, at 12:08 PM, Thomas Brettin brettin@anl.gov wrote:

I uploaded two fastq files for assembly. I didn’t set the type for one of them. It appears that the only way I can proceed is to re-upload the second file with the type properly set.

I tried entering the name of the file by hand.

I tried selecting the file after selecting “Show files with an unspecified type”, but the selection was not accepted.

This will happen, multiple times, particularly since there is no indication that a type is required. When I choose to upload the second fastq file with no type selected, the uploader went merrily along its job. 

I see a couple options.

1) don’t let me upload something of unspecified type, without having to click a ‘yes, i really want to do this and understand that i won’t be able to use it as input to a service” button.
2) let me change the type from within the GUI.
3) let me pass files of unspecified type to services.

(I favor option 1, with option 2 enabled later, and dislike option 3 altogether)

On Mar 24, 2015, at 1:17 PM, Christopher Henry chrisshenry@gmail.com wrote:

To the API DOES allow you to alter the type on an existing object.

typedef structure {
    list<tuple<FullObjectPath,UserMetadata,ObjectType,Timestamp creation_time>> objects;
    bool autometadata;
    bool adminmode;
} update_metadata_params;
funcdef update_metadata(update_metadata_params input) returns (list<ObjectMeta> output) authentication required;

If you specify “ObjectType” in the “objects” argument, you will respecify the type. 

But we probably should offer a UI capacity to run this function? Is that what you’re looking for?

**Comment by dmachi** [comment]
Sorry, I didn't notice this email earlier.  It is currently subtle, but you can edit the type of things that a user would have uploaded.  When you select the item in the workspace and look in the detail panel on the right, the type property is clickable and will let you change the type of object a particular item is set to.  All that said, I'm generally in favor of #1 too, though not everyone agrees.

**Comment by mshukla1** [comment]
I uploaded fna file as unspecified. When I click on the file, I see the following: 
![screen shot 2015-06-10 at 11 36 39 pm](https://cloud.githubusercontent.com/assets/1236463/8099344/a8d9405a-0fc9-11e5-8d7e-d66e22653e46.png)

**Comment by mshukla1** [comment]
UI now allows you to view metadata for unspecified file and change file type.
