### ISSUE TITLE
Why is there a pathway icon in the green bar when the pathway table list is loaded?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1050]
I don't know what's supposed to happen when you click the pathway icon in the green bar
<img width="1180" alt="screen shot 2016-10-10 at 4 27 01 pm" src="https://cloud.githubusercontent.com/assets/11475316/19250097/a902b0c6-8f06-11e6-822f-972f8dd4e02b.png">

I did click on it, but nothing ever returned.
<img width="1289" alt="screen shot 2016-10-10 at 4 29 11 pm" src="https://cloud.githubusercontent.com/assets/11475316/19250121/be455d08-8f06-11e6-9723-1f1ff49ccdc7.png">

**Comment by hyoo** [comment]
The button was for Pathway Summary (aka Pathway enrichment).

**Comment by mshukla1** [comment]
fixed on beta.
