### ISSUE TITLE
Can't get to gene page from Genes list in Pathways

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1051]
There is no View button, or equivalent, that I can find.

https://www.beta.patricbrc.org/view/Genome/83332.12#view_tab=pathways

![screen shot 2016-10-10 at 4 29 30 pm](https://cloud.githubusercontent.com/assets/3188570/19250135/cc7965f4-8f06-11e6-98c5-6d05ec63c2ea.png)

**Comment by hyoo** [comment]
From this grid, you would expect to see pathway map and "MAP" button is there. 
Please tell us if you expected something else.

I guess we can add "Feature" button only in the genes sub-tab.

**Comment by rkenyon** [comment]
In the production site, in the genes sub-tab you can click on a gene in the list and go to the corresponding gene page.  Its not possible from the Beta site.  This is one of the specific steps in Rebecca's Pathways tutorial - otherwise I probably would not have noticed it.

Anywhere we have a list of genes you should be able select one of the genes and go to its gene page.

![screen shot 2016-10-11 at 9 46 45 am](https://cloud.githubusercontent.com/assets/3188570/19272769/d2141824-8f97-11e6-9abf-0a889e9a83be.png)

**Comment by hyoo** [comment]
Got it. Will add feature button on the selection action panel, which will resolve this issue.

**Comment by hyoo** [comment]
fixed and will be available on alpha soon.

**Comment by mshukla1** [comment]
link to the feature overview page added in the action bar. verified on beta.
