### ISSUE TITLE
ID Mapping to Gene ID returns nothing

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1053]
I selected a list of genes:
<img width="1172" alt="screen shot 2016-10-10 at 4 34 13 pm" src="https://cloud.githubusercontent.com/assets/11475316/19250263/82b9bf94-8f07-11e6-9de9-ade3dcbeb1c7.png">
Chose ID Mapping, and then selected Gene ID under RefSeq identifiers:
<img width="500" alt="screen shot 2016-10-10 at 4 34 22 pm" src="https://cloud.githubusercontent.com/assets/11475316/19250290/a85ddbb8-8f07-11e6-828a-4c02592848f6.png">
The results page says it returned 45 results, but the column for Gene is empty.
<img width="1182" alt="screen shot 2016-10-10 at 4 33 54 pm" src="https://cloud.githubusercontent.com/assets/11475316/19250340/c2cfc9a2-8f07-11e6-87ac-ab857654b549.png">

**Comment by mshukla1** [comment]
I believe the "Gene" here refers to the gene symbol, which is default in all feature-ish tables.

I think the problem is that Gene ID (or whatever ID type was selected) is not displayed as a column in the ID Mapping result table.

**Comment by ARWattam** [comment]
The Gene column was not there before I did the ID mapping.

----- Original Message -----

**Comment by mshukla1** [comment]
aah, I see that now.

**Comment by hyoo** [comment]
fixed and will be available soon. thanks for catching it.
