### ISSUE TITLE
Where are the check boxes allowing me to select things in the ID Mapping return page?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1054]
No little check boxes....sad....
<img width="1182" alt="screen shot 2016-10-10 at 4 33 54 pm" src="https://cloud.githubusercontent.com/assets/11475316/19250371/df2e567c-8f07-11e6-8f17-18615586a5b0.png">

**Comment by aswarren** [comment]
Checkboxes have been turned on but given the idx model in IDMappingMemoryStore.js I can't figure out how to make select all work.  setting allowSelectAll: false in IDMappingGrid for now.
https://github.com/PATRIC3/p3_web/commit/b89fcfee8b7cfb15dfd3df7a374c5dd4acb3fe71

**Comment by aswarren** [comment]
Fixed in https://github.com/PATRIC3/p3_web/pull/294/commits/93e96c85bd0d4c16a3fc32193cefb364ddddd111
