### ISSUE TITLE
Excel download from Pathway heatmap opens txt file

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1056]
I purposely selected excel to see the heat map data, but it returned a txt file.
<img width="595" alt="screen shot 2016-10-10 at 4 42 42 pm" src="https://cloud.githubusercontent.com/assets/11475316/19250525/b846ceda-8f08-11e6-8467-69699f89c7c8.png">

**Comment by hyoo** [comment]
currently removed excel download option, because this case is pushing data from web browser instead of from api. You can use excel to read csv file format.
