### ISSUE TITLE
BLAST against genome group

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1057]
Fails for me with the following error.  My group is in the KPNs_4_Houston login under bad_ec.

![image](https://cloud.githubusercontent.com/assets/7661533/19250571/9aa670c2-8f00-11e6-96af-ceb9c0b3124d.png)

Here is a failure when I blast against a group with only public genomes:
![image](https://cloud.githubusercontent.com/assets/7661533/19250651/2173fa20-8f01-11e6-8c93-2cb73c037d35.png)

**Comment by hyoo** [comment]
seems like two issues.
1. genome id 573.5710 is a public genome. Need to check whether we have indexes for all genomes. - assign Maulik here.
2. genome id 83333.144 is a private. need to wait until we have the capability. - assign Bob here.
