### ISSUE TITLE
Genome Browser: make patric and refseq default tracks

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1060]
currently, only PATRIC annotations are shown as default. I think we should add refseq features as well, so that users are aware of them and can make comparisons. 

-Maulik

**Comment by dmachi** [comment]
The tracks are in the list by default, so people should be able to see them.  Enabling them all just so they are seen just make the browser loading slower.

**Comment by dmachi** [comment]
Fixed.  On alpha soon.
