### ISSUE TITLE
Genome browser: show feature + 3000bp flanks

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1061]
feature level page -> genome browser -> it shows only feature, no flanking region. 

It should show features + 3000bp regions on either side to show the context. 

-Maulik

![screen shot 2016-10-10 at 3 57 45 pm](https://cloud.githubusercontent.com/assets/1236463/19250930/73f4a7ee-8f02-11e6-8497-45e1c4a04c9b.png)

**Comment by aswarren** [comment]
Fixed at least from the feature view Genome Browser tab. If there are other ways to get there they will have to be modified as well.
