### ISSUE TITLE
MSA: breaks when loading PATRIC and refseq features

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1063]
https://www.beta.patricbrc.org/view/FeatureList/?and(keyword(Escherichia),keyword(coli),keyword(O104),keyword(Shiga),keyword(toxin),keyword(A))#view_tab=features&filter=eq(feature_type,%22CDS%22)

Select all -> run MSA. It breaks. 

If I select only PATRIC features, it works. 

IF I select only refseq features, it never loads. 

![screen shot 2016-10-10 at 4 13 08 pm](https://cloud.githubusercontent.com/assets/1236463/19251505/32bc63a4-8f05-11e6-98f7-ccce06b58d52.png)

**Comment by aswarren** [comment]
Fixed via
https://github.com/PATRIC3/p3_api/commit/7d18af0dae5c75dbe181aee19f3280371ce43e48
https://github.com/PATRIC3/p3_web/commit/b4e7cb85e13b714ade141b1b093e4bfdcf362ae0
https://github.com/PATRIC3/p3_api/pull/23/commits/fbea53ad020377626f4d32a8997dca73afbf568e
