### ISSUE TITLE
Workspace seems to be down

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1064]
Clicked on it from the Workspace tab and saw this
<img width="1120" alt="screen shot 2016-10-11 at 6 55 15 am" src="https://cloud.githubusercontent.com/assets/11475316/19267990/cd1c360c-8f7f-11e6-8d1f-85f067943c63.png">

**Comment by ARWattam** [comment]
It just shows up when I go to Your Workspace. When I go to Genome Groups, they load but maintain the error message:
<img width="1120" alt="screen shot 2016-10-11 at 6 57 43 am" src="https://cloud.githubusercontent.com/assets/11475316/19268049/1c79156c-8f80-11e6-879c-19b93e8a63b4.png">

**Comment by dmachi** [comment]
Workspaces are currently up.  I'm not sure what happened here, but it appears to be working now and others have verified.
