### ISSUE TITLE
Blast search

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1066]
I would like to be able to add genomes by their identifiers because the genome lookup is so painful.

![image](https://cloud.githubusercontent.com/assets/7661533/19272280/97a60062-8f8d-11e6-834d-22e206eb95f4.png)

**Comment by jimdavis1** [comment]
Actually this issue is critical, since more than one genome can have the same strain name.

**Comment by hyoo** [comment]
this is fixed and available on production.
