### ISSUE TITLE
Feature Overview: the links to the source ids are missing in the Special Properties table 

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1068]
<img width="999" alt="screen shot 2016-10-11 at 3 42 28 pm" src="https://cloud.githubusercontent.com/assets/6361802/19285826/85a13ac6-8fc9-11e6-9d23-e7872ae498fe.png">

**Comment by chmao1** [comment]
Both the source and source id links are added in the Special Properties table and will be available in the next build.

**Comment by mshukla1** [comment]
links added. verified on alpha.
