### ISSUE TITLE
In feature view, the last element of the breadcrumb should be the genome, not the species.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1072]
![screen shot 2016-10-13 at 3 46 38 pm](https://cloud.githubusercontent.com/assets/11475316/19325201/fff33d6e-9092-11e6-9b2e-c489449a523d.png)

**Comment by mshukla1** [comment]
Agree. Genome should be added to the breadcrumb, similar to that on the public site.

**Comment by hyoo** [comment]
this is fixed and available on production.

https://www.patricbrc.org/view/Feature/PATRIC.83332.12.NC_000962.CDS.2726806.2727339.fwd#view_tab=overview
