### ISSUE TITLE
BLAST on specialty genes DB

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1073]
Since we already have NRs for the specialty genes databases, it should be trivial to enable a user to have the option to search against them as well.  

![image](https://cloud.githubusercontent.com/assets/7661533/19351822/e576cb64-9122-11e6-9062-decbcd4dcd98.png)

**Comment by hyoo** [comment]
we have this in plan. DB is not ready yet, but you should be able to see the option when you choose blastx with nucleotide sequence or blastp with protein sequence.

Maulik, please let us know when the DB is available.

**Comment by mshukla1** [comment]
Database is available now and spgene blast is working. The results require some formatting though, which is covered under a different ticket. so closing this one. 

#1325
