### ISSUE TITLE
Need to sort genome group list on alphabetical order

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1074]
Can the list of genome groups be alphabetized?

![image](https://cloud.githubusercontent.com/assets/7661533/19353311/8114c86e-9128-11e6-82f0-0db88a381866.png)

**Comment by hyoo** [comment]
I also prefer alphabetical order in genome groups, but maybe we can expand this UI component in which user can choose the order.

**Comment by mshukla1** [comment]
You can already click on folder icon to get group listing and sort them alphabetically or by date.

For now, I think we just need to decide what is more useful in the drop down, alphabetical or most recent? 

My preference is alphabetical. 

-Maulik

**Comment by mshukla1** [comment]
I like the current solution. Display top N most recent groups in the drop down, assuming that user are likely to select most recent groups. You have the folder selection icon next to it to see the complete listing of the group and sort them alphabetically or by date.
