### ISSUE TITLE
global search and features list doesn't filter after selection

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1075]
Search dnaK in global search -> clicked "Genomic Features: 218947" -> choose two features -> feature list button -> it updated header but still seeing 127891 features in the grid (I guess this is due to the CDS PATRIC filter, it was 218947) and header count is still wrong (554384256).

**Comment by dmachi** [comment]
I've fixed the problem with the header count not updating.  However there is still a discrepency I can't explain. The search page says:  Genome Features (218973)  When you go to the feature list the total count shows Features: dnak ( 219452 Genome Features ) (with CDS and PATRIC filtering, 127917).  I'm not yet sure why there is this discrepancy for the dnaK search.

**Comment by dmachi** [comment]
Will be up on alpha soon.

**Comment by mshukla1** [comment]
I found the source of discrepancy. 

I think the mail search shows only refseq and patric features (excludes BRC1 features). 

However, the table counts all three for the bottom count. 

We should make it consistent to avoid any confusion from users. 

<img width="756" alt="screen shot 2016-10-17 at 9 43 51 pm" src="https://cloud.githubusercontent.com/assets/1236463/19462525/0729c386-94b3-11e6-8eaf-b9e3eb96e91d.png">

<img width="1044" alt="screen shot 2016-10-17 at 9 43 39 pm" src="https://cloud.githubusercontent.com/assets/1236463/19462528/0bcd4958-94b3-11e6-8103-5c52447b3353.png">

**Comment by dmachi** [comment]
Can't we just delete these annotations and avoid this problem?

**Comment by mshukla1** [comment]
BRC1 annotations have been removed.
