### ISSUE TITLE
Filter up and down arrows missing from Transcriptomics left filter on Table View

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1076]
https://www.beta.patricbrc.org/view/Taxonomy/629#view_tab=transcriptomics

![screen shot 2016-10-13 at 10 59 10 am](https://cloud.githubusercontent.com/assets/3188570/19354422/a5f7f794-9134-11e6-8288-0d03cfd287f1.png)

**Comment by hyoo** [comment]
There is a mouse over. it is technically difficult to change headers in dgrid library. I can add extra table with description as we have in protein families tab. but Maulik doesn't like it. We may need a better way to describe it.

**Comment by hyoo** [comment]
I added same icons on top of the grid. will be available soon.

**Comment by mshukla1** [comment]
Harry, this is fine for now. 

However, we need to revisit and improve the filter styling and layout on transcriptomics and protein family pages. 

-Maulik
