### ISSUE TITLE
sequence tab and contig download should not have "protein fasta" option

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1078]
Download button in the selection action bar is not working but it works on features & genomes tab.

![image](https://cloud.githubusercontent.com/assets/1236467/19354514/91ab994c-912c-11e6-89dc-83ad0d910fef.png)

**Comment by hyoo** [comment]
duplicate #945

**Comment by mshukla1** [comment]
sequence tab and contig download should not have "protein fasta" option. please remove it. 

<img width="1440" alt="screen shot 2016-10-17 at 9 24 29 pm" src="https://cloud.githubusercontent.com/assets/1236463/19462156/3f65fc72-94b0-11e6-9cf1-849e02e48b22.png">

**Comment by hyoo** [comment]
Technically, this should be a new ticket. but I am changing title and will leave this one open.
