### ISSUE TITLE
Circular Viewer not available for some genomes

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#1079]
Genome Browser comes up OK for this genome, but not the Circular Viewer:  
Streptococcus pneumoniae INV104  (869269.3)

**Comment by dmachi** [comment]
Hmm, i'm not seeing this problem.  This is what the circular viewer is looking like here.  What was the behavior...did the circular viewer not load at all or did it just stall loading the tracks?

![streptococcus pneumoniae inv104 genome circular viewer 2016-10-13 11-16-36](https://cloud.githubusercontent.com/assets/190574/19354955/9078cc98-9136-11e6-8877-6eb69ce21c74.png)

**Comment by mshukla1** [comment]
I am not seeing the problem either. 

Closing the ticket.
