### ISSUE TITLE
Clicking on strain column header in Transcriptomics causes all data to disappear

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1080]
Escherichia-Transcriptomics-click on Strain and all data leaves...
<img width="1120" alt="screen shot 2016-10-13 at 11 10 53 am" src="https://cloud.githubusercontent.com/assets/11475316/19354760/e0470bc8-9135-11e6-8c73-cce430936866.png">

**Comment by dmachi** [comment]
SOLR doesn't allow us to sort on multivalued fields.  Sorting for this column will need to be disabled.

**Comment by dmachi** [comment]
Fixed locally, on alpha soon.

**Comment by mshukla1** [comment]
Fixed. Verified on beta.
