### ISSUE TITLE
Arrows and text filters missing on experiment table list

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1082]
the arrows over the circles (indicating up or down regulated) are missing.  There should be a text box that allows users to search for specific genes.
<img width="822" alt="screen shot 2016-10-13 at 11 16 23 am" src="https://cloud.githubusercontent.com/assets/11475316/19355112/16e57b46-9137-11e6-8945-64a3e194f3ce.png">

**Comment by ARWattam** [comment]
Here is the filtering ability currently on production:
<img width="295" alt="screen shot 2016-10-13 at 11 48 07 am" src="https://cloud.githubusercontent.com/assets/11475316/19356186/f89d3c6a-913a-11e6-8b5c-fe69b24ee033.png">

**Comment by mshukla1** [comment]
fixed. verified on alpha.
