### ISSUE TITLE
invisible ORF

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#1083]
Bob's new Compare Regions display in PATRIC refuses to show this particular feature for some reason:  fig|869269.3.peg.7, while ORFs upstream and downstream of it are nicely shown -

https://www.beta.patricbrc.org/view/Feature/PATRIC.869269.3.FQ312030.CDS.4941.8450.fwd#view_tab=overview

Note that the same feature is displayed properly in regular PATRIC (not beta) Compare Region --

https://www.patricbrc.org/portal/portal/patric/CompareRegionViewer?cType=feature&cId=PATRIC.869269.3.FQ312030.CDS.4941.8450.fwd&tracks=CR0%2CCR2%2CCR3%2CCR4%2CCR5&regions=5&window=10000&loc=fig%7C869269.3.peg.7%3A1..10000&highlight=

**Comment by olsonanl** [comment]
It shows up for me:

http://p3.theseed.org/qa/compare_regions/fig|869269.3.peg.7

you need to be patient (the machine the compare regions is running on is also the machine I have the application that's doing pattyfam calling for the test data and that's using up nearly all available memory)
![screen shot 2016-10-13 at 11 53 37 am](https://cloud.githubusercontent.com/assets/2152226/19358488/b82faea0-913b-11e6-9b7d-8271f0ce3984.png)

**Comment by mshukla1** [comment]
Bob, from your comment above, it seems this is not a real problem, right? 

If so, please close the ticket.
