### ISSUE TITLE
Selections don't stick

### ISSUE THREAD

**Issue by vvons** [PATRIC3/patric3_website#1085]
Selections made in a previous window do not stick when using the back button. It's sometimes very painful, if the selection of lets say genomes took a long time then you do something and then you would like to go back and do something else. That selection is lost. I understand that I could have created and saved a group, but sometimes one is trying things out and creating groups all the time isn't what one wants.

**Comment by dmachi** [comment]
Understood.  Its not going to be possible to simply avoid this.  However, I do have a plan to allow a kind of ephemeral group that would avoid this and at the same time allow creation of more complex selections across the site, but that isn't currently implemented.

**Comment by dawenx** [comment]
Assuming the back button is not the one provided by the browser, in stead, it's at the bottom of the page to navigate to previous set of the results, then this issue has been solved. (See "Grid general: Cannot select across pages", #1719)

**Comment by mshukla1** [comment]
#2073 duplicate
