### ISSUE TITLE
BLAST

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1086]
I have a genome group. I wish to know how many of this antibiotic resistance gene are in the group at a given blast threshold.  I currently can't ask that question because I can only search for a certain number of hits. 

![image](https://cloud.githubusercontent.com/assets/7661533/19355740/0852da02-9131-11e6-901f-a192e44ad118.png)

**Comment by jimdavis1** [comment]
Apropos of this comment, after your results are returned, you don't know how many there are in the table.  If you click the select all box, it says how many there are (I think). 

![image](https://cloud.githubusercontent.com/assets/7661533/19355892/9053c358-9131-11e6-9695-17b7c536b1c5.png)

![image](https://cloud.githubusercontent.com/assets/7661533/19355988/e095d2d4-9131-11e6-8cf2-67717a26c48a.png)

It is very slow to scroll to the bottom of the list, so i think we need something like this:

![image](https://cloud.githubusercontent.com/assets/7661533/19356068/21338ea8-9132-11e6-942d-8e5bbb572541.png)

**Comment by hyoo** [comment]
now we're using page grid, as you described above.

**Comment by mshukla1** [comment]
number of results and paging has been added. verified on beta.
