### ISSUE TITLE
Not able to deploy initial filter of experiments on beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1087]
An important function in the transcriptomics tab is the ability to filter down on experiments.  We often show filtering on hypoxia for Mycobaterium.  The filter on production looks like this:
<img width="433" alt="screen shot 2016-10-13 at 11 53 30 am" src="https://cloud.githubusercontent.com/assets/11475316/19356429/d6febcb8-913b-11e6-9411-1dd53874a171.png">

I can't figure out how to do it on beta except by painfully entering the text in.  I liked the way it used to be....
<img width="1434" alt="screen shot 2016-10-13 at 11 54 58 am" src="https://cloud.githubusercontent.com/assets/11475316/19356573/4389a730-913c-11e6-81f5-f27a60490e3d.png">

**Comment by ARWattam** [comment]
I click on the filter in the upper right, but nothing happens until I select something...I guess that I could select EVERYTHING...oops.  When I try that, nothing happens.
<img width="1431" alt="screen shot 2016-10-13 at 11 58 40 am" src="https://cloud.githubusercontent.com/assets/11475316/19356627/73458d7c-913c-11e6-8ef9-40a1068ede48.png">

**Comment by dmachi** [comment]
This is a regression somewhere.  Filter panel should show you the filters you want.  Will have to track it down.

**Comment by mshukla1** [comment]
Dustin, I believe This is critical for transcriptomics usecases. Can you fix this before the workshop Tomorrow? 

-Maulik

**Comment by hyoo** [comment]
actually, filter IS there. you should be able to see it when you drag the border line. The filter button does not open the filter panel, though. Let me check whether I can quickly fix.

![image](https://cloud.githubusercontent.com/assets/1236467/19473855/440e702e-94fb-11e6-92d4-cb270b9331b2.png)

**Comment by hyoo** [comment]
fixed locally. I will deploy soon.
