### ISSUE TITLE
Proteome comparison should flag missing comparison genome

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1088]
The proteome comparison app lets one submit a comparison job without having selected a comparison genome - it should disallow that case since it will eventually mysteriously crash.

**Comment by chmao1** [comment]
Fixed and will be available in the next build.

**Comment by mshukla1** [comment]
Checked on beta. The app now shows an error if reference genome is not selected. 
"Error Submitting Job. Please check the submission form."

This is better than before. However, I think it will be more useful to the user if either
- error message is more explicit saying which field is missing or has error 
- or, showing a red flag next to the filed that is missing value

**Comment by chmao1** [comment]
I'll revise the error message. Showing a red flag next to the field won't apply for the reference genome section, because all three fields are optional. The restriction is that ONE of the three fields is required to be filled.

**Comment by mshukla1** [comment]
I understand. Just making it explicit in the error message would be fine.

**Comment by chmao1** [comment]
Revised the message and will be in the next build.
