### ISSUE TITLE
region viewer on feature landing page.

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1090]
It would be nice if I could interact with this rendering of the genomic region, like walking and zooming in and out.  I don't know if the plan is to replace it with compare regions...

![image](https://cloud.githubusercontent.com/assets/7661533/19358498/c5941f36-913b-11e6-92e6-1a83d14b8c54.png)

**Comment by hyoo** [comment]
genome browser already have all the functionality you described. This was meant to be a quick view.

**Comment by mshukla1** [comment]
Jim, this cartoon is meant to provide only a quick overview of the gene neighborhood and allow one to click on the neighboring gene and jump to corresponding gene page. 

We do have full genome browser on a separate tab that provide all interactive features. 

-Maulik
