### ISSUE TITLE
the genome browser needs the annotation in the mouse-over

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1093]
![image](https://cloud.githubusercontent.com/assets/7661533/19400266/0aed950a-921b-11e6-9e6e-68100e7d97bd.png)

**Comment by mshukla1** [comment]
I like the new mouseover, the id and function display is now consistent with the information the header for the gene overview page. 

However, the coordinates are not displayed correctly. It is missing start and strand. 

<img width="460" alt="screen shot 2016-10-29 at 5 34 06 am" src="https://cloud.githubusercontent.com/assets/1236463/19828940/7ce20d74-9d99-11e6-9110-398ca54ee10d.png">

**Comment by aswarren** [comment]
double fixed
