### ISSUE TITLE
BLAST bug

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1094]
I tried to blast a k-mer against a genome group made from the public S. pneumoniae genomes.

![image](https://cloud.githubusercontent.com/assets/7661533/19400912/0b07e3d0-921e-11e6-976c-c79146c3bd42.png)

**Comment by olsonanl** [comment]
Hm. Hitting command line length limits with large sets of genomes. will need to figure out how/if to deal with that.

**Comment by olsonanl** [comment]
Fixed in https://github.com/olsonanl/homology_service/commit/74592e2c5b7de11cc7c1219d1e12b210a6a9cd55
