### ISSUE TITLE
genome browser suggestions.

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1096]
It would also be good if the patric annotation box didn't obscure the peg.

If there is no reference sequence, that track should go away.

Also it is killing me to click on a gene and scroll all the way to the bottom of the box to get the annotation.

The mouseover of the peg gets cut off because it renders too far to the right (see bottom image).  This happens in the seed too.

![image](https://cloud.githubusercontent.com/assets/7661533/19401230/bd6617bc-921f-11e6-86b4-7c672356408e.png)

![image](https://cloud.githubusercontent.com/assets/7661533/19401293/1d9a0116-9220-11e6-8f3e-28f7434b356b.png)

**Comment by mshukla1** [comment]
We have show / hide track labels button now at the top, which allows you to hide the track labels and see the features at the end. 

<img width="287" alt="screen shot 2017-12-07 at 7 56 54 am" src="https://user-images.githubusercontent.com/1236463/33718801-512bcef8-db24-11e7-8259-86fe16d61f78.png">

<img width="1440" alt="screen shot 2017-12-07 at 7 56 37 am" src="https://user-images.githubusercontent.com/1236463/33718808-57457c44-db24-11e7-8ab0-f97498d0ef41.png">
