### ISSUE TITLE
issues sorting items in Experiments in Workspace - and resulting incorrect metadata for selected item?

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#110]
Committing the cardinal sin by entering probably more than 1 problem here.
1) If I sort the experiments in my workspace by title and then select one of the experiments, the table immediately unsorts itself (back to the original order, I think, although I'm not sure what the original order is ordered by)
2) After the "unsort" happens, I think what is happening is that the selection shading is still on the same numerical position as it was when I clicked on the sorted version, and so the metadata matches the item I intended to select but it doesn't match the item that is highlighted as selected in the table.   See screenshot.    I have seen this mismatch in highlighted item and metadata several times.   I THINK this is probably how it happened each time, but I won't swear to that.
![wrong description](https://cloud.githubusercontent.com/assets/1243115/6818944/75c8f8d0-d28f-11e4-995c-99f6337053df.png)

**Comment by mshukla1** [comment]
resolved.
