### ISSUE TITLE
PFS: Major problem-choosing one genome group in Protein Family Sorter and it loads a different one

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1100]
So I choose Brucella
<img width="159" alt="screen shot 2016-10-16 at 10 49 24 am" src="https://cloud.githubusercontent.com/assets/11475316/19418330/bc6e8ad0-938f-11e6-9874-114d65bc9e35.png">
 Hit Submit and I could see Brucella in the background:
<img width="1440" alt="screen shot 2016-10-16 at 10 49 38 am" src="https://cloud.githubusercontent.com/assets/11475316/19418334/ce43b348-938f-11e6-91fe-2664b75009ea.png">
Then I could see that it says Escherichia in the background (I had loaded Escherichia earlier this morning):
<img width="1440" alt="screen shot 2016-10-16 at 10 49 41 am" src="https://cloud.githubusercontent.com/assets/11475316/19418339/e3abe688-938f-11e6-8357-6bd269ca4b94.png">
When it finally completes, its Escherichia and not Brucella:
<img width="1103" alt="screen shot 2016-10-16 at 10 59 23 am" src="https://cloud.githubusercontent.com/assets/11475316/19418341/f0d10604-938f-11e6-9ae7-9d3282bf429e.png">

**Comment by ARWattam** [comment]
Hmm...first screen shot didn't load...here's me choosing a brucella group I had created
<img width="905" alt="screen shot 2016-10-16 at 10 49 31 am" src="https://cloud.githubusercontent.com/assets/11475316/19418350/12bd093e-9390-11e6-9fee-23ae667b6bc7.png">

**Comment by mshukla1** [comment]
This has happened to me once before. However, I could never reproduce it
and show it to Harry. Few questions to help understand the issue: 

Did you click anything when the protein families where trying to load? 

Or, Did you have any other tab with E coli families open in parallel? 

Or, did you try to load E coli genomes before you try to load Brucella? 

Can you reproduce it?

**Comment by hyoo** [comment]
available on alpha.

**Comment by mshukla1** [comment]
I am still seeing this problem on alpha. 

Went to PFS tool, selected brucella group, got the right families. 

Then, went back and selected an ecoli group, got the right families, but the genome list on left still shows brucella genomes from previous group. 

<img width="982" alt="screen shot 2016-10-26 at 11 55 31 am" src="https://cloud.githubusercontent.com/assets/1236463/19735927/23629dfe-9b73-11e6-8a5f-9e98905c5ef0.png">

**Comment by mshukla1** [comment]
Fixed. Verified in beta.
