### ISSUE TITLE
PFS: Anchoring does not appear to be working-beta Protein Family Sorter

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1101]
40 genomes from Brucella...loaded on production:
<img width="1435" alt="screen shot 2016-10-16 at 12 33 57 pm" src="https://cloud.githubusercontent.com/assets/11475316/19418968/de244630-939c-11e6-8dde-9f2f8d8c331d.png">

Never loaded on beta...same group, same genome as anchor:
<img width="1329" alt="screen shot 2016-10-16 at 12 24 33 pm" src="https://cloud.githubusercontent.com/assets/11475316/19418973/00b5608a-939d-11e6-94a6-a537e0a2e3e1.png">

**Comment by mshukla1** [comment]
It worked for me fine for a genome group of 55 complete Brucella genomes using local families. 
Anchoring worked in just couple of seconds. 

My feeling is that it could be a temporary performance glitch, not a systematic problem. Can you try 
again and verify? 

-Maulik
