### ISSUE TITLE
Persisting box-beta on comparative pathway heatmap

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1103]
I can see the opening of one of the drop down boxes at the upper left of the heatmap.  It doesn't go away until kill the page.
<img width="323" alt="screen shot 2016-10-16 at 5 36 33 pm" src="https://cloud.githubusercontent.com/assets/11475316/19421121/4676d340-93c7-11e6-912d-100ab98d808f.png">

**Comment by hyoo** [comment]
for verification

**Comment by mshukla1** [comment]
fixed. verified on alpha.
