### ISSUE TITLE
PFS: keyword filter is kept in the box when I switch taxon

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1105]
I am in borrelia PFS -> applied keyword filter. 

Then I went to bartonella -> PF tab. They previous keyword is still displayed in the box, which 
should be cleared when I change context.

**Comment by hyoo** [comment]
I have a fix locally. will deploy soon.

**Comment by mshukla1** [comment]
fixed, verified on alpha.
