### ISSUE TITLE
Top nav: add link to private genomes

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1106]
Need to add direct link to private genomes under data or workspace menu in the top navigation bar. 

Currently, it requires three click to see all my private genomes: 
all bacteria -> genome list -> filter public=false

-Maulik

**Comment by dmachi** [comment]
Added "Private Genomes" link underneath Data->Genomes.  This will currently show all private genomes you have access to (In the future, with sharing, we may want to make this more specific...private genomes of which you are the owner).  

Will be on alpha soon.

**Comment by hyoo** [comment]
verified
