### ISSUE TITLE
Circular viewer: help tool tips are sticky and annoying 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1108]
The help tool tips for the custom track and upload your own data are useful. However, they keep appearing when I trying to actually use those options and are hard to get rid of, which makes it difficult to access the options and buttons in that area. It is annoying. 

Suggestion: add a question mark or help icon at the right most edge of the section title with mouseover, instead of enabling mouseover on the entire section title. 

-Maulik

**Comment by chmao1** [comment]
Fixed and will be available in the next build.

**Comment by mshukla1** [comment]
Fixed. verified on beta.
