### ISSUE TITLE
circular viewer: sort contigs and features 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1109]
When showing multiple contigs / replicons, sort them by accession number. Currently, they seem to be in random order. 

Similarly, the features should also be sorted by accession + start, to provide a clear overview of their relative positions on the genome. 

https://www.beta.patricbrc.org/view/Genome/1194972.3#view_tab=circular

-Maulik

<img width="1188" alt="screen shot 2016-10-17 at 5 33 52 pm" src="https://cloud.githubusercontent.com/assets/1236463/19458184/28630544-9490-11e6-9956-aead0db2ffdb.png">

**Comment by chmao1** [comment]
Fixed and will be in the next build.

**Comment by mshukla1** [comment]
Looks good. Verified on beta.
