### ISSUE TITLE
BLAST: folder selection shows workspaces that are not mine!! 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1110]
I am logged in as mshukla. 

When I go to protein family and other tools, I see folders in my workspace home. 

However, when I go to BLAST, I am seeing other weird workspaces that, for all I can say, are not mine! Looks like these are the workspaces created to test publish/clone/share workspace features. 

<img width="793" alt="screen shot 2016-10-17 at 9 15 36 pm" src="https://cloud.githubusercontent.com/assets/1236463/19462030/491f2910-94af-11e6-99e4-ef90d1863dc7.png">

<img width="883" alt="screen shot 2016-10-17 at 9 13 51 pm" src="https://cloud.githubusercontent.com/assets/1236463/19462035/5245d7fa-94af-11e6-86f3-97e3d0f7b9a5.png">

**Comment by hyoo** [comment]
I have fixed and and available on alpha.
