### ISSUE TITLE
Contact us is missing from bottom of beta page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1111]
Oops!  We don't have the email link anymore
<img width="1123" alt="screen shot 2016-10-18 at 9 58 05 am" src="https://cloud.githubusercontent.com/assets/11475316/19480726/77de99d8-9519-11e6-9382-ca539815ad59.png">

**Comment by dmachi** [comment]
They had me get rid of it in favor of the Provide feedback link (instead of having both).

**Comment by ARWattam** [comment]
But I don't even see that!  All that's there is the address, how to cite, and the funding statement

**Comment by dmachi** [comment]
It is in the help menu.

**Comment by mshukla1** [comment]
I wonder if we need provide different flavors of the same link in different contexts to make it more intuitive to the users, i.e. report problem, provide feedback, contact us, etc. 

-Maulik

**Comment by mshukla1** [comment]
@rkenyon what do you think? 

Is "Provide Feedback" in the top menu enough or do we need additional link at the bottom of the page and on about patric page? 

Close the ticket if you think additional links are not needed.

**Comment by rkenyon** [comment]
Now in Help Menu.  Closing ticket.
