### ISSUE TITLE
login window needs form validation

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1112]
a user was not able to login and he did not noticed he didn't provided a username. It might be better to have a specific feedback what went wrong.

**Comment by mshukla1** [comment]
@dmachi

can we add js check for and flag the field if no value provided for user name or password? 

Please make the change and close the ticket.

**Comment by dmachi** [comment]
Will take care of this in the upcoming p3-user changes.

**Comment by JoshuaVSherman** [comment]
link to pull request
https://github.com/PATRIC3/p3_web/pull/662

**Comment by hyoo** [comment]
#1763
