### ISSUE TITLE
Global search: yggs mg1655, all top features are refseq

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1113]
It should be showing PATRIC features at the top, instead. 

<img width="802" alt="screen shot 2016-10-18 at 1 25 50 pm" src="https://cloud.githubusercontent.com/assets/1236463/19488790/729c8cba-9536-11e6-8b68-4ce1c3f9c613.png">

**Comment by chmao1** [comment]
Fixed and made a pull request.

**Comment by chmao1** [comment]
Verified on alpha.
