### ISSUE TITLE
Gene View: tabs are shown for refseq features

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1114]
when gene overview page is opened for a refseq gene which has identical patric gene, overview correctly shows information. However, other tabs are still displayed for original refseq features, hence no transcriptomics data is displayed. 

https://www.beta.patricbrc.org/view/Feature/RefSeq.511145.12.NC_000913.CDS.3093120.3093824.fwd#view_tab=overview

if I go to equivalent PATRIC feature, I do see transcriptomics data. 

https://www.beta.patricbrc.org/view/Feature/PATRIC.511145.12.NC_000913.CDS.3093120.3093824.fwd#view_tab=transcriptomics

**Comment by mshukla1** [comment]
Here is another example with similar issue: 

fig|83332.12.peg.2721 | Rv2429 | ahpD | Alkylhydroperoxidase protein D

Transcriptomics data is shown for this gene on the public site. Note that I am loading the gene overview page with a refseq feature id. But, when I go to transcriptomics and correlated genes tab, they are shown for equivalent patric features, which is what is expected. 

https://www.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=RefSeq.83332.12.NC_000962.CDS.2726806.2727339.fwd

https://www.patricbrc.org/portal/portal/patric/TranscriptomicsGeneExp?cType=feature&cId=PATRIC.83332.12.NC_000962.CDS.2726806.2727339.fwd&sampleId=&colId=&log_ratio=&zscore=

However, no transcriptomics data is shown for this gene, with refseq or patric feature id. 

https://www.beta.patricbrc.org/view/Feature/RefSeq.83332.12.NC_000962.CDS.2726806.2727339.fwd#view_tab=transcriptomics

https://www.beta.patricbrc.org/view/Feature/PATRIC.83332.12.NC_000962.CDS.2726806.2727339.fwd#view_tab=transcriptomics

-Maulik

**Comment by hyoo** [comment]
refseq_locus_tag was stored with key named 'refseq_locus_tag' or 'exp_locus_tag'. added missing case.

**Comment by hyoo** [comment]
reopen for verification.

**Comment by mshukla1** [comment]
Fixed. Verified on beta.
