### ISSUE TITLE
Genome Browser: display PATRIC ids and refseq locus tags as default labels

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1116]
provide gene names and function in mouseover. 

Right now, it shows gene names or protein ids  or patric ids using some logic, which is very confusing to the users. 

<img width="1264" alt="screen shot 2016-10-18 at 1 53 05 pm" src="https://cloud.githubusercontent.com/assets/1236463/19489819/c72a8a94-953a-11e6-8c3d-ccab5a85cf04.png">

-Maulik

**Comment by aswarren** [comment]
Duplicate of #1098
