### ISSUE TITLE
Assembly: reset doesn't clear selected libraries

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1119]
Submitted a job. Hit reset button to submit next job. It cleared all fields, except selected libraries. 

Also, after hitting reset button:
- Reset button should be greyed out 
- job has been queued message should go away. 

-Maulik

<img width="795" alt="screen shot 2016-10-18 at 2 12 30 pm" src="https://cloud.githubusercontent.com/assets/1236463/19490423/20ad239a-953d-11e6-9a8c-b3889551a0f2.png">

**Comment by aswarren** [comment]
Selected Libraries clear Fixed in https://github.com/PATRIC3/p3_web/pull/301
Resetting submit msg and Reset button still needs some work.

**Comment by aswarren** [comment]
Submission message clearing fixed. The reset button being always active is not really a problem and would take some effort to change.
