### ISSUE TITLE
Viewing Gene List from an Experiment Sample gets spinny wheel forever, no gene list

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#112]

**Comment by dmachi** [comment]
This is fixed and in beta.

**Comment by hyoo** [comment]
This is fixed from Experiment folder, but not fixed when you launch gene list from "Experiment Group". See below url,

https://www.patricbrc.org/portal/portal/patric/TranscriptomicsGene?cType=taxon&cId=131567&dm=result&log_ratio=&zscore=&expId=ff16aa94-3705-46e4-8044-dab6fc410020&sampleId=&wsExperimentId=&wsSampleId=

**Comment by dmachi** [comment]
Fixed and pushed to production.
