### ISSUE TITLE
top nav requires sync up with user.beta.patricbrc.org

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1120]
in a sub-domain (user.beta.patricbrc.org), it is not synchronized to www.beta.patricbrc.org.

Do we need to manually sync up every time?

![image](https://cloud.githubusercontent.com/assets/1236467/19491451/0043300a-9541-11e6-9f4b-bdd925e82196.png)

**Comment by dmachi** [comment]
Updated on alpha, haven't updated on beta yet.  Currently they both need to be kept in sync as they are changed.  We can work out something to make that smoother in the future.
