### ISSUE TITLE
action button location needs some consistency

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1121]
sometimes "OK" and "Cancel" 
sometimes "Cancel" and "Ok"

<img width="1008" alt="screen shot 2016-10-18 at 2 56 37 pm" src="https://cloud.githubusercontent.com/assets/1236467/19492133/7a8c768a-9543-11e6-9827-bf4e079af821.png">

<img width="629" alt="screen shot 2016-10-18 at 2 57 51 pm" src="https://cloud.githubusercontent.com/assets/1236467/19492137/7d9d999e-9543-11e6-9590-e07a231ef7a4.png">

**Comment by nconrad** [comment]
yeah, i noticed this and fixed it in PR patric3/p3_web#234

**Comment by nconrad** [comment]
Something else I noticed was that the enter key will cancel the delete prompt.  I personally think enter should confirm the delete?

**Comment by dmachi** [comment]
I don’t really care too much, but I think the general UI principle in this case is that something destructive (delete) shouldn’t be accidentally selected (so enter defaults to cancel).

**Comment by mshukla1** [comment]
fixed. verified on beta.
