### ISSUE TITLE
Workspace: change file type

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1122]
It is not obvious to the users how they can change file type for a selected file. We need a visual clue. 

-Maulik

<img width="352" alt="screen shot 2016-10-18 at 3 03 09 pm" src="https://cloud.githubusercontent.com/assets/1236463/19492280/043e7342-9544-11e6-818d-1fe03e17367d.png">

**Comment by nconrad** [comment]
I can take this one, if you want.

**Comment by dmachi** [comment]
Yes, I think he was supposed to assign it to you but he is just too used to assigning me tickets :P

**Comment by mshukla1** [comment]
Verified on beta.
