### ISSUE TITLE
Job submission form: filter/highlight ref/rep genomes

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1125]
Proteome comparison tool. User wanted to use E coli MG1655 reference genome. The problem is that there are >10 MG1655 genomes and user cant tell which one if reference. 

Solution: 
- Provide a filter for reference/representative genomes, similar to public/private.
- highlight reference/representative genomes by making them bold. 
- also, allow users to search for genomes using genome id

**Comment by aswarren** [comment]
Duplicate of #845 and #849
