### ISSUE TITLE
jobs page not showing

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1126]
I had a PATRIC page up with blast results and tried to click on the workspaces -> Your Jobs link in the bar and nothing happened. Error console had the following.

[Error] Failed to load resource: the server responded with a status of 404 (Not Found)  https://www.beta.patricbrc.org/js/3.2.26/p3/widget/JobManager.js
(JobManager.js, line 0)
[Error] Error: xhrFailed
    getText (dojo.js:19:143)
    ma (dojo.js:36:358)
    b (dojo.js:15:297)
    (anonymous function) (dojo.js:24:165)
    fa (dojo.js:33)
    ja (dojo.js:24:152)
    La (dojo.js:24:500)
    s (dojo.js:15:479)
    getConstructor
    _doNavigation
    navigate
    (anonymous function)
    fireRoute
    _handlePathChange
    go
    (anonymous function)
    (anonymous function) (dojo.js:87:141)

**Comment by dmachi** [comment]
I think there was a build problem and it looks like you are still on an old version, so I guess the page you launched from hasn’t been reloaded in a day or so (the current version is 3.2.30).

**Comment by mshukla1** [comment]
@olsonanl , can you reproduce the problem or should it be closed?

**Comment by olsonanl** [comment]
It comes up properly today.

**Comment by dmachi** [comment]
There are still known bugs on the jobs page.  For example, if you go to the jobs page and hit reload, it will be empty.  If you go to the jobs page from any other page after the Job Status indicator has been populated, it works.  Of course, this is on the list of things to get fixed and I believe there is a ticket for it.

Dustin
