### ISSUE TITLE
Proteome Comparison Tool

### ISSUE THREAD

**Issue by dmachi** [PATRIC3/patric3_website#1127]
After submitting a job to proteome comparison, a user clicked the reset button.  After this an additional submission to the tool generated an error (and still showed the success of the previous submission).

**Comment by chmao1** [comment]
Could you provide an example to reproduce this problem?

**Comment by chmao1** [comment]
Fixed and made a pull request.

**Comment by mshukla1** [comment]
Fixed, verified on beta.
