### ISSUE TITLE
services submission pages

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1130]
add a link to tutorials and sample data set so that users can refer it.

**Comment by mshukla1** [comment]
Most tools and pages on the public site has one line description of the tool / functionality and then link to the FAQs / tutorial. We need to add them for all services/tools/pages on the beta site as well. 

For example, below is the message on the ID Mapping tool in the production site: 

"The ID Mapping Tool enables researchers to locate synonymous identifiers across multiple-source databases. For further explanation, please see ID Mapping Tool User Guide."

**Comment by dawenx** [comment]
@hyoo can we close this ticket now?

**Comment by hyoo** [comment]
I would like to add some intro line at top. I will take care of them.

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/33857552-c85347c0-de91-11e7-8a4d-e88fccc1e7bc.png)

Now, all service submission pages have a description and links to user guide and tutorial.
