### ISSUE TITLE
column selector plus icon too small

### ISSUE THREAD

**Issue by dmachi** [PATRIC3/patric3_website#1131]
Reports from the workshop that the column selector icon in dgrid is too small to notice.

**Comment by mshukla1** [comment]
I am not sure if we still consider this an issue. Should check with Rebecca. 

If yes, my suggestion is that we add a big icon above the table for column selection / customization (next to filter and apply icons), in addition to the current + icon in the last column. We have space and it will make it more obvious. 

-Maulik

<img width="1117" alt="screen shot 2017-09-17 at 1 08 43 pm" src="https://user-images.githubusercontent.com/1236463/30523595-a362f97c-9ba9-11e7-88b8-90e93f98afb6.png">

**Comment by chmao1** [comment]
Fixed and will be available in the next build.

**Comment by chmao1** [comment]
Verified on alpha.
