### ISSUE TITLE
proteome comparison links should open in new tab

### ISSUE THREAD

**Issue by dmachi** [PATRIC3/patric3_website#1133]

**Comment by mshukla1** [comment]
@maovt, please reassign it to Fangfang, if it needs to be fixed from the service side. 

-Maulik

**Comment by levinas** [comment]
Can you clarify which link this is referring to?

**Comment by chmao1** [comment]
Fangfang, 

I think that it's referring to the links for the features in the circular image. This requires server side fix in circos.html - adding "target='_blank'" in the link construction. 

Chunhong

**Comment by levinas** [comment]
Fixed in PR: https://github.com/TheSEED/app_service/pull/58

**Comment by hyoo** [comment]
confirmed on production
