### ISSUE TITLE
Proteome Comparison - change blast options?

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1134]
a user in Florida workshop asked whether he can use cblast or tblast because he works on phages and blastp doesn't work for his work.

I guess we can review the pipeline and see what we can provide as advanced options.

**Comment by mshukla1** [comment]
@levinas , what do you think? Is this a reasonable request? 

I am thinking the current proteome comparison tool is designed for a very specific use case. 
We can provide separate set of tools later for doing phage or plasmid analysis. 

-Maulik

**Comment by levinas** [comment]
@mshukla1 Is cblast for structural search? I agree; these may not be proteome comparison per se. They could be supported in a blast tool suite.

**Comment by mshukla1** [comment]
@levinas, yes, it looks like cblast is for structure comparison. I agree that we can make it available as part of BLAST and allow search against MMDB in future. 

Closing the ticket.
