### ISSUE TITLE
needs some consistency between view pages and workspace

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1135]
1. green bar on workspace is narrower
2. view pages calls the first button "Hide" but workspace calls it "Detail"

![image](https://cloud.githubusercontent.com/assets/1236467/19521719/b07665ea-95e2-11e6-9419-1e27411d08d5.png)

![image](https://cloud.githubusercontent.com/assets/1236467/19521729/c1321014-95e2-11e6-8220-d9febcc042c5.png)

**Comment by mshukla1** [comment]
@nconrad , job list page still calls it detail. Please change that as well. 

<img width="1032" alt="screen shot 2016-10-26 at 1 42 04 pm" src="https://cloud.githubusercontent.com/assets/1236463/19739834/154e5f78-9b82-11e6-85b3-f5267aa58433.png">
