### ISSUE TITLE
beta std err and std out retrieval

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#1136]
It looks like requests for stderr/stdout only displays on production and not beta.

For example:

GET /services/app_service/task_info/033913d4-47c3-4519-9c3c-33dd716148cc/stderr HTTP/1.1
Host: p3.theseed.org
Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Origin: https://www.patricbrc.org

![image](https://cloud.githubusercontent.com/assets/229173/19521774/f8009e08-95e2-11e6-8e6d-121dac219196.png)

![image](https://cloud.githubusercontent.com/assets/229173/19521801/0def55d8-95e3-11e6-8c44-024dd7fc0b14.png)

Also, there is no longer a view of std out content?

**Comment by hyoo** [comment]
@nconrad I guess we already fixed this issue. Please reopen if not. I am pretty sure.
