### ISSUE TITLE
Proteome comparison: make it interactive

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1138]
We need to make proteome comparison results more interactive. 

Need complementary tabular, circular and heatmap viewers with filter options, similar to protein family sorter. 

Circular viewer: 
- Use new circular viewer to show the results, instead of circos. 
- mouseover tooltip to show basic feature information, id, locus tag, gene name, function
- linkout to the genome overview page

Tabular view: 
- dojo grid or new table viewer, similar to one in seed / rast. 

Heatmap viewer: 
- reuse protein family heatmap

**Comment by chmao1** [comment]
This requires significant re-implemention of both front UI and backend server programs.

**Comment by mshukla1** [comment]
I agree, this is major redesign of the existing tool, perhaps for PATRIC4. 

I am going to close this ticket.
