### ISSUE TITLE
Display workspace folder when uploading

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#114]
If I have two files named the same, but in different workspace locations, I will not know which file I am using. Displaying the workspace location would be helpful.

![screen shot 2015-03-25 at 10 09 34 am](https://cloud.githubusercontent.com/assets/991769/6826344/30a435e2-d2d7-11e4-8c71-632fa57cd678.png)

**Comment by dmachi** [comment]
You are always choosing from a single workspace folder which defaults to the last folder you visited or ~.  However, we should make this dialog show what folder you are currently in to make it clearer.

**Comment by dmachi** [comment]
Will now show current folder in the workspace object selector.  Will push to beta shortly
