### ISSUE TITLE
assembly failure during workshop: "Error: Invalid assembly ID: auto"

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1148]
## PATRIC created PATRIC-570:

```
        Summary: [beta] Job failure in workshop: velvet-spades failed
            Key: PATRIC-570
            URL: https://jira.cels.anl.gov/browse/PATRIC-570
        Project: PATRIC
     Issue Type: Bug
       Reporter: PATRIC
       Assignee: Rebecca Wattam
```

Version: 3.2.30 beta
URL: https://www.beta.patricbrc.org/job/
User ID: C1988LERMA

Hello,
This job did not work:
d1e05f53-d415-43c6-82e1-697174402b83
Thank you for your help

GET WS => /scratch/tmp/eKxkoPYTek 609_1.velvet_contigs.fa /C1988LERMA@patricbrc.org/home/609_1.velvet_contigs.fa
GET WS => /scratch/tmp/eKxkoPYTek 609_2.spades_contigs.fasta /C1988LERMA@patricbrc.org/home/609_2.spades_contigs.fasta
\@submit_cmd = $VAR1 = [
          'ar-run',
          '-r',
          'auto',
          '--pair',
          '/scratch/tmp/eKxkoPYTek/609_1.velvet_contigs.fa',
          '/scratch/tmp/eKxkoPYTek/609_2.spades_contigs.fasta',
          'platform=infer',
          'read_orientation_outward=false',
          'interleaved=false'
        ];
Running ar-run -r auto --pair /scratch/tmp/eKxkoPYTek/609_1.velvet_contigs.fa /scratch/tmp/eKxkoPYTek/609_2.spades_contigs.fasta platform=infer read_orientation_outward=false interleaved=false
Submission returns
Job ID: 3

Submitted job 3, waiting for results
+--------+---------+--------------------+----------+-------------+
| Job ID | Data ID |       Status       | Run time | Description |
+--------+---------+--------------------+----------+-------------+
|   1    |    1    |      Complete      | 0:06:47  |     None    |
|   2    |    2    | Stage 1/6: bhammer | 0:19:30  |     None    |
|   3    |    3    |   Data transfer    |          |     None    |
+--------+---------+--------------------+----------+-------------+

Running pull: ar-get -w -p -j 3 | ar-filter -l 300 -c 5
Error: Invalid assembly ID: auto

Error retrieving results from job 3

**Comment by levinas** [comment]
Contigs, not reads, were used as input to this job, and that caused the failure.

```
'/scratch/tmp/eKxkoPYTek/609_1.velvet_contigs.fa',
'/scratch/tmp/eKxkoPYTek/609_2.spades_contigs.fasta',
```

**Comment by mshukla1** [comment]
@levinas, Should there be better validation of the input files before the job is run, or a more clear error message for the user?

**Comment by rkenyon** [comment]
Outdated
