### ISSUE TITLE
Job page not refreshing when selecting Jobs

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#115]
1. an assembly job is launched.
2. the jobs counter shows the job is running.

![screen shot 2015-03-25 at 10 13 25 am](https://cloud.githubusercontent.com/assets/991769/6826437/daf2f3c6-d2d7-11e4-8d9e-c30e1a20d542.png)

3. the user clicks on the Job counter.
4. the user is taken to what appears to be an old, cached version of the jobs page

![screen shot 2015-03-25 at 10 13 52 am](https://cloud.githubusercontent.com/assets/991769/6826459/fe148298-d2d7-11e4-992e-f91e52ecad99.png)

4. the user manually refreshes the jobs page to see the correct information.

![screen shot 2015-03-25 at 10 14 08 am](https://cloud.githubusercontent.com/assets/991769/6826467/0b7c9628-d2d8-11e4-899b-07ed92bedea2.png)

5. the jobs page does not refresh automatically thereafter.

**Comment by brettin** [comment]
The browser is safari 7.1.3

**Comment by dmachi** [comment]
Fixed.
