### ISSUE TITLE
blast page gets stuck dropdown

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1152]
![screen shot 2016-10-19 at 1 06 11 pm](https://cloud.githubusercontent.com/assets/2152226/19531305/d4c87d38-95fc-11e6-8382-20c847565b4c.png)

**Comment by hyoo** [comment]
this is a dojo rendering but. I have no idea how to fix. 

@dmachi do you have any idea?

**Comment by mshukla1** [comment]
I am not able to reproduce this after trying for several times. So, IMHO, it is not critical at least.

Please respond if anyone still sees the problem.

**Comment by hyoo** [comment]
resolved.  #1368
