### ISSUE TITLE
Improving heatmap clustering

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1154]
if protein family is driven by taxon, it is easily over 100 genomes and 10,000 families, which never loads. I wish I can
1. change cluster program to multi-cpu version
2. move it to app service like BLAST.

**Comment by olsonanl** [comment]
We need to profile exactly where the time is going.

**Comment by dmachi** [comment]
Yes, we did some profiling of this previously and I think we discussed in another ticket ( #673 ).  Essentially the cluster program being run is a single cpu binary, and for larger data sets can easily take > 40 minutes to complete.

**Comment by olsonanl** [comment]
Is the clustering always invoked, or do the initial unclustered families never load?

**Comment by dmachi** [comment]
The initial unclustered ones load.  The error here is when they click the “cluster” button in the heat map.

**Comment by dmachi** [comment]
This is the clustering program we are using.  Harry said we could probably find another clustering program to use.

http://bonsai.hgc.jp/~mdehoon/software/cluster/cluster3.pdf

**Comment by mshukla1** [comment]
I think the broader point here is that we should not be running compute intensive programs (i.e. BLAST, clustering, MSA) on the web server as they often hog the resources (specially when running in workshop settings) and often slow down other parts of the website as well. 

-M

**Comment by olsonanl** [comment]
can someone comment on how the clustering software is invoked? (What precisely is being clustered)

**Comment by hyoo** [comment]
transcriptomics expression data (per feature per comparison) or protein families count (how many times a protein family was counted per genome).

**Comment by olsonanl** [comment]
This is ancient.
