### ISSUE TITLE
feature level transcriptomics tab

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1157]
1. it is missing total number of comparisons.
2. filter works only after clicking twice. 

https://www.patricbrc.org/portal/portal/patric/TranscriptomicsGeneExp?cType=feature&cId=PATRIC.83332.12.NC_000962.CDS.1010313.1011734.fwd&sampleId=&colId=&log_ratio=&zscore=

https://www.beta.patricbrc.org/view/Feature/PATRIC.83332.12.NC_000962.CDS.1010313.1011734.fwd#view_tab=transcriptomics

![image](https://cloud.githubusercontent.com/assets/1236467/19534915/c1ed42ae-9613-11e6-8f1f-6e78851b0d06.png)

![image](https://cloud.githubusercontent.com/assets/1236467/19534927/cb9507ce-9613-11e6-9208-1f66ce55cf5b.png)

**Comment by chmao1** [comment]
The total count is at the table tab.

**Comment by chmao1** [comment]
The filter should work after clicking once now. The fix will be available in the next build.

**Comment by mshukla1** [comment]
fixed. verified on alpha.
