### ISSUE TITLE
Feature overview: gene neighborhood cartoon

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1161]
The selected gene is not displayed in red in the cartoon!!!

https://www.beta.patricbrc.org/view/Feature/RefSeq.265668.3.BBMI01000072.CDS.27779.28135.rev

<img width="1338" alt="screen shot 2016-10-24 at 4 44 13 pm" src="https://cloud.githubusercontent.com/assets/1236463/19665374/4c79076a-9a0a-11e6-982d-f44cd849eee8.png">

**Comment by hyoo** [comment]
reopen for verification

**Comment by mshukla1** [comment]
fixed. verified in beta.
