### ISSUE TITLE
PFS: Weird error on Protein Family Sorter

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1162]
Looking at a special group of Lactobacillus genomes from a paper.  This is the first time I have ever seen this type of error:
<img width="1433" alt="screen shot 2016-10-24 at 6 50 11 pm" src="https://cloud.githubusercontent.com/assets/11475316/19666824/d6a48990-9a1a-11e6-86e9-75e3ca140735.png">

**Comment by hyoo** [comment]
I think this can be related to #1100. please check on alpha.

**Comment by hyoo** [comment]
and please let us know how we can reproduce it.

**Comment by hyoo** [comment]
i guess this is related to the session issue address by other ticket.

**Comment by mshukla1** [comment]
@hyoo, this is not related to session. You get columns undefined or empty message when the filers result in zero features in the table. Here is how you can reproduce it. 

Go to: 
https://www.beta.patricbrc.org/view/TranscriptomicsExperiment/?eq(eid,(431625))

Filters: log ratio = 1 z score = 2 and down in the first condition. 

<img width="999" alt="screen shot 2016-11-15 at 3 23 39 am" src="https://cloud.githubusercontent.com/assets/1236463/20300145/5e3f920e-aae3-11e6-96a6-c31c15d24d12.png">

**Comment by mshukla1** [comment]
I think the solution can be either just the empty heatmap, or a better message saying 
"No results to display".  

-Maulik

**Comment by hyoo** [comment]
That message is controlled by flash (heatmap implementation).

**Comment by mshukla1** [comment]
OK, so there is nothing we can do about this as long as we are using flash. closing it.
