### ISSUE TITLE
Unable to do any of the green bar functions from feature group in beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1164]
I created a feature group, went into my workspace and loaded it, and then tried to do a msa....nothing.  ID Mapping....nothing.  Get sequence....nothing.  Pathway....nothing.  What's going on?

**Comment by mshukla1** [comment]
here is how to reproduce the problem: 
go to feature group list in the workspace -> double lick on on of the groups -> go to member list -> select few -> try actions using side bar. 

I think we need to deprecate this page. Instead, when double clicked on the group name, it should go to the new feature list view. Then, we also need to add button for removing selected members. 

-Maulik

**Comment by dmachi** [comment]
Agree, this should be a workspace task.

**Comment by hyoo** [comment]
I think the member page is no longer reachable.

**Comment by dmachi** [comment]
Yes, I removed this as requested.  The GenomeGroup View  page needs a remove from group button still.

**Comment by mshukla1** [comment]
@hyoo @dmachi 

Are you planning to add "remove from group" button on the genome and feature group view page? 
I think this is critical, Rebecca has submitted multiple tickets for that.

**Comment by dmachi** [comment]
I will try to fix this today.

**Comment by hyoo** [comment]
@dmachi 
you may need to import this module.

![image](https://cloud.githubusercontent.com/assets/1236467/20815393/566e7f74-b7e3-11e6-8186-4fb6784a3ee7.png)

**Comment by hyoo** [comment]
well, I think this is not implemented for feature group. So I am punting back.

it works after I import the module, but I noticed that page header count is not updated. need to address this issue as well.

**Comment by dmachi** [comment]
ok, i’ve just committed the change for when.  You are right, I only did this for GenomeGroup. Will do the same thing for FeatureGroup.  Will check out the page header count.

**Comment by dmachi** [comment]
I've fixed this for Feature Group.   There is currently no mechanism to trigger refreshing the page header count when items are deleted.  I will look into that tomorrow.

**Comment by dmachi** [comment]
Fixed the header count for feature group and genome group.  Will be on alpha soon.

**Comment by hyoo** [comment]
verified.
