### ISSUE TITLE
All locus tags except PATRIC

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1165]
When doing a search, a couple of locus tags return, but not the PATRIC one.  We have the old VBI one and not the RASTtk one?  Is there a reason for this?
<img width="835" alt="screen shot 2016-10-25 at 1 55 10 pm" src="https://cloud.githubusercontent.com/assets/11475316/19697813/ec47794c-9aba-11e6-961a-4481b501fca4.png">

**Comment by mshukla1** [comment]
no reason, just oversight. PATRIC ids should be displayed when available.

**Comment by dmachi** [comment]
Not sure what you mean here.  Are there search results that are missing or is the format of the 2 results incorrect?

**Comment by mshukla1** [comment]
The format of the displayed results, need to display patric_id for patric feature.

Change: 
PATRIC | CDS | b2965 | VBIEscCol129921_3061

to:
PATRIC | CDS | fig|511145.12.peg.3061 | b2965 | VBIEscCol129921_3061

**Comment by dmachi** [comment]
Fixed. Will be on alpha soon.

**Comment by mshukla1** [comment]
@dmachi, I don't see it on alpha yet. Has it been deployed?

**Comment by mshukla1** [comment]
fixed. verified on alpha.
