### ISSUE TITLE
BLAST bug

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1166]
This search is hanging and gives the user no indication that it failed. 

![image](https://cloud.githubusercontent.com/assets/7661533/19701928/201e222c-9ac3-11e6-82f8-9952fe9bc8ab.png)

**Comment by olsonanl** [comment]
Hm, I tried answering this by email but it never showed up here. anyway, when I looked there were a couple blast jobs that had been running for 6 minutes, and then finished up.

**Comment by olsonanl** [comment]
oh that’s against all the rep proteins. I do see a couple blast runs still going against that database. It just may take a long time to run these.

I’ll ask my usual question - what are you looking for in particular from running blast?

—bob

On Oct 25, 2016, at 2:56 PM, jimdavis1 <notifications@github.com<mailto:notifications@github.com>> wrote:

This search is hanging and gives the user no indication that it failed.

[image]https://cloud.githubusercontent.com/assets/7661533/19701928/201e222c-9ac3-11e6-82f8-9952fe9bc8ab.png

**Comment by olsonanl** [comment]
what were you searching against?

On Oct 25, 2016, at 2:56 PM, jimdavis1 <notifications@github.com<mailto:notifications@github.com>> wrote:

This search is hanging and gives the user no indication that it failed.

[image]https://cloud.githubusercontent.com/assets/7661533/19701928/201e222c-9ac3-11e6-82f8-9952fe9bc8ab.png

**Comment by hyoo** [comment]
you should have the loading mask when it is running and will have a dialog when the blast is failed.

**Comment by mshukla1** [comment]
fixed. verified on beta.
