### ISSUE TITLE
BLAST: Right panel delay in showing correct information

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1167]
I did BLAST once, then did edit and resubmit with a new protein.  When I select the gene I want to see, I noticed that the information to the right of the green band shows the old gene from the former blast, not the recent one.
<img width="1432" alt="screen shot 2016-10-25 at 4 46 05 pm" src="https://cloud.githubusercontent.com/assets/11475316/19703703/c64208bc-9ad2-11e6-8df6-c87afd8054ba.png">

**Comment by mshukla1** [comment]
I tried it multiple times on beta Today and could not reproduce the problem. 

@ARWattam, can you please try it again and see if the problem persists? If so, provoide more details on which blast options you tried.

**Comment by mshukla1** [comment]
Can't reproduce.
