### ISSUE TITLE
Can we link to raw reads at SRA?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1168]
I was just answering a user request and showed them how to find the reads for a particular genome at SRA.  Is there any direct link between reads and the assembly?  I'm wondering if we could provide a hyperlink to the reads at SRA from the genome landing page.

**Comment by mshukla1** [comment]
I know we added those links for the genomes we assembled from SRA. 

I will check if we can add them for other genomes as well. 

-Maulik

**Comment by mshukla1** [comment]
I have added SRA accessions for ~47,000 genomes in solr, all the public genomes that can be mapped reliably to corresponding SRA accessions as of now. 

@hyoo, some of the genomes have multiple SRA accessions, separated by ",", which breaks the link to NCBI. You will need to replace "," with " OR " to make the linkout work. 

Below is an example: 

https://www.patricbrc.org/view/Genome/1742972.4

https://www.ncbi.nlm.nih.gov/sra/?term=ERR1149361+OR+ERR1149362+OR+ERR1149363+OR+ERR1149364
