### ISSUE TITLE
Selecting taxonomy name in annotation service a bit finicky

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1169]
I have tried to do four different Corynebacterium pseudotuberculosis jobs this morning  When typing out "pseudotuberculosis", Yersinia pseudotuberculosis appeared as the top his, with Corynebacterium pseudotuberculosis as the second.  I carefully selected the Corynebacterium species four times, but each time it autofilled Yersinia pseudotuberculosis.  Then I entered both the genus and species name.  The first time it worked, then when submitting another genome, the taxonomy id did not autofill.  A bit frustrating.
<img width="560" alt="screen shot 2016-10-26 at 7 53 24 am" src="https://cloud.githubusercontent.com/assets/11475316/19725091/b3d16856-9b51-11e6-99f0-f3f97f839968.png">

**Comment by mshukla1** [comment]
@ARWattam, I am not able to reproduce the problem. Can you?

**Comment by hyoo** [comment]
I cannot reproduce either. Please reopen if it exists.

**Comment by ARWattam** [comment]
I now always look up the taxon id at NCBI and enter that.  The name is just too unstable.  Just try trying to do an annotation for Brucella.  It doesn't matter how many times I select Brucella, it chooses Brucellacea....which is VERY different!  Now I just enter 234 into the Taxon ID number, and it autofills what I want.
