### ISSUE TITLE
Delay in showing annotation jobs have been submitted

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1170]
This morning I submitted 4 annotation jobs over the course of 5-8 minutes.  The jobs tracking page does not reflect the submission.  Why is there a delay this long?
<img width="986" alt="screen shot 2016-10-26 at 7 57 38 am" src="https://cloud.githubusercontent.com/assets/11475316/19725205/41088bd2-9b52-11e6-8181-b1c72b048043.png">

**Comment by ARWattam** [comment]
They appeared as completed before they ever appeared in the job tracker.
<img width="1149" alt="screen shot 2016-10-26 at 8 03 04 am" src="https://cloud.githubusercontent.com/assets/11475316/19725282/b469f598-9b52-11e6-9656-b2fb8fb4a8a5.png">

**Comment by olsonanl** [comment]
Did the job window come up quickly for you or was there a delay? Wondering if it is related to the problem with rendering that page when there is a large number of jobs.

If the job page is pulling jobs incrementally, we might have an issue with sort ordering and the new jobs not coming up in initial retrieves when they don't yet have a start or completion time. I'll take a look at that possibility today.

**Comment by ARWattam** [comment]
I opened the jobs window pretty easily, and then clicked on the Started column.  They weren't showing up in the queue.  I've seen this before.

----- Original Message -----

**Comment by mshukla1** [comment]
@nconrad, see if you can fix this.

**Comment by nconrad** [comment]
This issue doesn't seem easy to replicate.  It sounds like this could have even been when @ARWattam 's polling was getting blocked by ANL, @olsonanl ?   I wonder if we will have that issue again with the 5 second timeout polling.  Polling will be more often, but payload is only a couple hundred bytes.
