### ISSUE TITLE
Toolbar version of ID Mapping: result header and target id label

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1171]
Selected first 5 features from H37Rv genomes and ran ID mapping with KEGG as target.  

https://www.beta.patricbrc.org/view/Genome/83332.12#view_tab=features

Two issues: 
1. The says "Out of 5 features selected, 16 found in KEGG" because of one to many mappings. This is misleading. It should say something like: Out of 5 feature selected, 3 are mapped to 16 kegg ids. 
2. The IDs mapped to are displayed under column heading "Target". We should make the column heading more specific to say what ID type it is. 

<img width="1116" alt="screen shot 2016-10-26 at 3 43 20 pm" src="https://cloud.githubusercontent.com/assets/1236463/19744503/6e55d0fe-9b93-11e6-8551-81a918731a63.png">

**Comment by JoshuaVSherman** [comment]
* The results page generated after using the action bar version of ID mapper should be the same one that is displayed after using the standalone version of ID mapper

**Comment by JoshuaVSherman** [comment]
@dmachi getting an **undefined** are mapped; output from Action Bar ID mapper query does not include # that were mapped, need help with that please

**Comment by JoshuaVSherman** [comment]
https://github.com/JoshuaVSherman/p3_web/blob/9a9ea7bd30085b0807d49a6b922695292843498d/public/js/p3/widget/viewer/IDMapping.js

line 38

**Comment by JoshuaVSherman** [comment]
https://github.com/PATRIC3/p3_web/pull/706
