### ISSUE TITLE
Genome data type page issues

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1173]
At the top there's a spurious line "Data"

Also in the genome status chart it lists 0% for plasmid genomes; seems we shouldn't list it if we don't have any.

**Comment by mshukla1** [comment]
There are only 6 plasmid only genomes, hence, when rounded, they become 0. I am thinking, we should just remove those 6 plasmid only genomes from the database to avoid any confusion. 

<img width="986" alt="screen shot 2016-10-27 at 10 04 45 am" src="https://cloud.githubusercontent.com/assets/1236463/19772818/07068a98-9c2d-11e6-9f43-3761eba67a0c.png">

**Comment by mshukla1** [comment]
Harry explained to me that "Data" was added near Florida workshop as breadcrumb. 

@nconrad, can you go over all data landing pages and add breadcrumb in style that is consistent with the rest of the site?
