### ISSUE TITLE
DLP: Genome data type page - top 5 host graphic

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1174]
There isn't a legend saying what the hosts are; it's not entirely obvious that you need to mouse over it to see the host name

**Comment by mshukla1** [comment]
https://www.beta.patricbrc.org/view/DataType/Genomes

<img width="383" alt="screen shot 2016-10-27 at 10 03 04 am" src="https://cloud.githubusercontent.com/assets/1236463/19772704/a0af79d0-9c2c-11e6-9177-36fd0e51abcb.png">

**Comment by hyoo** [comment]
wasn't it better than 

![image](https://cloud.githubusercontent.com/assets/1236467/19984517/c4daa34c-a1dc-11e6-925c-8c4e53216521.png)

https://www.patricbrc.org/portal/portal/patric/Genomes

just kidding. I will fix label.

**Comment by hyoo** [comment]
here are changes.
- for top 5 bacterial hosts, I changed label to include host name.
- for top 5 isolation countries, I added country flag back.

![image](https://cloud.githubusercontent.com/assets/1236467/20012820/ce45e41c-a27e-11e6-9a42-23c87c5b694e.png)

![image](https://cloud.githubusercontent.com/assets/1236467/20012832/d7502202-a27e-11e6-9a4a-007f4feab47f.png)

**Comment by mshukla1** [comment]
Thanks, Harry. Looks better. 

If future, if we run out of flags, I would not mind having just the labels.
