### ISSUE TITLE
The drop down selection for workspace needs to be alphabetized.

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1175]
This is impossible to navigate:

![image](https://cloud.githubusercontent.com/assets/7661533/19772652/834bd884-9c2c-11e6-926b-aa6f5ffb0cc4.png)

![image](https://cloud.githubusercontent.com/assets/7661533/19772562/412cc986-9c2c-11e6-8afc-e926049e064a.png)

![image](https://cloud.githubusercontent.com/assets/7661533/19772597/5d581dcc-9c2c-11e6-8411-aaa3925921a2.png)

![image](https://cloud.githubusercontent.com/assets/7661533/19772616/6848fae4-9c2c-11e6-81c7-d7a1ab4843bc.png)

![image](https://cloud.githubusercontent.com/assets/7661533/19772629/705d62e2-9c2c-11e6-9ccc-0687bfbc98e2.png)

**Comment by dmachi** [comment]
I agree with you on the alphabetizing.  However, I will note that you have two other options as well.  1) You can type in that box to filter down to what you want or 2) you can click on the folder icon to the right and browse to what you are looking for.

**Comment by JoshuaVSherman** [comment]
https://github.com/PATRIC3/p3_web/pull/706

**Comment by JoshuaVSherman** [comment]
https://github.com/PATRIC3/p3_web/pull/713

**Comment by JoshuaVSherman** [comment]
@olsonanl request for decision on this ticket, my fix set the dropdown alphabetical
I can revert that and it would again be most recent
I could setup a sort by and you would pick either (alphabetical or chronological)
I can default it to chronological or alphabetical
please let me know, thanks
