### ISSUE TITLE
genome data page - weird back button behavior

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1176]
If I click on a genome name in the "Select genomes" section I have to click the back button _twice_ to get back to that page.

The use of "select" there is a little unclear; at first read I read it as a verb

**Comment by mshukla1** [comment]
Select is used as an adjective here, as in interesting / useful / carefully chosen / popular genomes.
After lot of deliberations while designing the page we settled on "select",  so we don't hurt anyone's feelings!! ;)

Clicking the back button twice is an issue and I have seen it in other places as well.

**Comment by dmachi** [comment]
I assume this is referring to Genome Landing pages.  This actually looks to be a bad link.  All of the genomes are linking to things like: https://www.beta.patricbrc.org/view/Genome/83332.12#genome-tab1

I have no idea what that #genome-tab1 is referring to as there is no such thing in the Genome View.  When you link to this there is essentially a redirect and that is why it takes two clicks to get back (you can see the url change each time).
