### ISSUE TITLE
DLP: genomic features page - bad english

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1178]
PATRIC supports genome annotations from multiple sources, including:

Original annotations from GenBank / RefSeq
Consistent annotation across all bacterial genomes using RAST

The second item isn't a source, it's a methodology for creating the genomes

**Comment by mshukla1** [comment]
Methodology / algorithm / tool can be a source of annotations / predictions, it doesn't have to be a database resource always, no? 

Would the following be more appropriate?...or, pls suggest the sentence you like to see. 

Consistent annotation across all bacterial genomes using PATRIC annotation pipeline

**Comment by mshukla1** [comment]
fixed on alpha.
