### ISSUE TITLE
DLP: genome features page - markup overwrite

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1180]
https://www.beta.patricbrc.org/view/DataType/GenomicFeatures

when you hover on a genome name in the select list, an arrowhead overlays the text. see image.

<img width="987" alt="screen shot 2016-10-27 at 10 07 09 am" src="https://cloud.githubusercontent.com/assets/2152226/19772961/6c0a01fe-9c2d-11e6-9ba9-02fe69f44eb3.png">

**Comment by hyoo** [comment]
https://github.com/hyoo/p3_web/commit/850ab353a2d6995abbd19f33e7da2e64f51ce4e2
