### ISSUE TITLE
Unattractive rendering in proteome comparison

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1181]
Notice the contig numbers in the top left:
![image](https://cloud.githubusercontent.com/assets/7661533/19773160/1f69565a-9c2e-11e6-98c8-aa702d659987.png)

Now if i zoom in as far as I can with the browser, it never resolves itself.  

BTW, this also brings up the old gripe that if we don't have a way to zoom into the diagram, then there is no point having the links to the protein page.

![image](https://cloud.githubusercontent.com/assets/7661533/19773182/2b5b950e-9c2e-11e6-8af9-2a745c6824b0.png)

Also look at the numbers in dark lettering.  What does 0.0, 0.1, 0.2 etc. mean?  How can all of the smaller contigs be 0.0?

![image](https://cloud.githubusercontent.com/assets/7661533/19773307/a72edc72-9c2e-11e6-85db-2685d342bba0.png)

**Comment by mshukla1** [comment]
The outer most track shows contigs for the reference genome. This is useful in some cases to distinguish between two chromosomes or chromosomes and plasmids. However, If you select a crappy reference with hundreds of contigs, it is going to mess up the display. 

Possible solutions: 
- Advise users to select high quality genomes as reference. 
- Highlight reference/complete genomes in the genome selector to make it easier to find them.
- Or, in worst case, remove the outer contig track to provide better view

your preference?

**Comment by chmao1** [comment]
The fix is needed from the server side.

**Comment by levinas** [comment]
The outer most track contains information about the size/scale of the contigs. This rendering is a fitting reminder of a bad reference choice. I would recommend no fix for now.
