### ISSUE TITLE
DLP: genomic features data type page - families

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1182]
https://www.beta.patricbrc.org/view/DataType/GenomicFeatures also doesn't have pattyfam information

**Comment by mshukla1** [comment]
Agree, PLFam and PGFam summaries should be included. 

<img width="976" alt="screen shot 2016-10-27 at 10 22 52 am" src="https://cloud.githubusercontent.com/assets/1236463/19773503/67f07ab0-9c2f-11e6-9cd3-8418f61c0d92.png">

**Comment by mshukla1** [comment]
fixed. verified on alpha.
