### ISSUE TITLE
"Gene Page Transcriptomics"

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1183]
If I click on this thing on the home page:

![image](https://cloud.githubusercontent.com/assets/7661533/19773571/b235f92e-9c2f-11e6-9bf8-75b396c02045.png)

It puts me on a "Feature View" page for Mycobacterium tuberculosis "universal stress protein family" instead of some entry page for transcriptomic analysis.  Its totally disorienting.

![image](https://cloud.githubusercontent.com/assets/7661533/19773612/e7546546-9c2f-11e6-9052-c786d3392382.png)

Also, we probably don't need the vertical bars for "Log Ratio" and "Z-score":
![image](https://cloud.githubusercontent.com/assets/7661533/19773729/47d344a0-9c30-11e6-84bf-1ee25d0e68a3.png)

**Comment by mshukla1** [comment]
Agree. Both genome metadata and gene level transcriptomics are confusing and should be replaced with other services, such as Proteome comparison, RNA-Seq, Differential expression, or variation analysis. 

-Maulik

**Comment by mshukla1** [comment]
With the new home page, this widgets are no longer there. Obsolete.
