### ISSUE TITLE
specialty genes columns centered not justified

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1185]
From specialty gene data landing page: https://www.patricbrc.org/portal/portal/patric/SpecialtyGeneSource?source=PATRIC_VF&kw=

Click on PATRIC_VF

This looks jarring

https://www.patricbrc.org/portal/portal/patric/SpecialtyGeneSource?source=PATRIC_VF&kw=

**Comment by mshukla1** [comment]
Two issues:
- we need special page for the PATRIC_VFs on the beta site. 
- Then, Link on the DLP should go to the page above, not the page on the production site.

**Comment by chmao1** [comment]
The page for the PATRIC_VFs  is implemented and will be available in the next build

**Comment by mshukla1** [comment]
@maovt, I can not find the page on alpha. Can you please provide the link?

**Comment by mshukla1** [comment]
Ok, I think I found the list of manually curated PATRIC_VFs. 

@hyoo, please updated the PATRIC_VF link on the specialty gene DLP to the one below: 

https://www.alpha.patricbrc.org/view/SpecialtyGeneList/?keyword(*)#view_tab=specialtyGenes&filter=and(eq(source,PATRIC_VF),eq(evidence,Literature))

**Comment by hyoo** [comment]
PATRIC_VF link is updated on alpha.

**Comment by mshukla1** [comment]
Verified on alpha.
