### ISSUE TITLE
DLP: workflow graphics for features / specialty genes

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1186]
The graphics for "How Do We Process and Clean Up Our Data?" and "How Do We Curate, Integrate, and Map Specialty Genes?" are the same which seems a little odd

**Comment by mshukla1** [comment]
yeah, because they both refer to the same genome annotation workflow. 

Do you see anything conceptually wrong with either of them? 

We could add more details on the latter if we want to.
