### ISSUE TITLE
DLP: pathways view from genomic features data page doesn't work

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1187]
go to https://www.beta.patricbrc.org/view/DataType/GenomicFeatures

highlight Mtb 

click on "Pathway" under "Explore genomic features in"

I get sent to https://www.beta.patricbrc.org/view/Genome/83332.12#view_tab=pathways which shows 0 of 0 pathways and an error on the console

[Error] Error: This deferred has already been resolved
    d (dojo.js:121:173)
    callback (dojo.js:123)
    (anonymous function)
    (anonymous function) (dojo.js:57:507)

**Comment by olsonanl** [comment]
The pathway links don't work from here either

https://www.beta.patricbrc.org/view/DataType/Pathways

**Comment by mshukla1** [comment]
The pathway link needs to be changed to the following form. 

https://www.beta.patricbrc.org/view/Genome/198215.6#view_tab=pathways&filter=eq(annotation,PATRIC)

**Comment by mshukla1** [comment]
#922

**Comment by mshukla1** [comment]
#904

**Comment by hyoo** [comment]
this was due to #1047

**Comment by mshukla1** [comment]
fixed. verified on alpha.
