### ISSUE TITLE
Transcriptomics: Keep getting an error when trying to load genes from experiment list

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1188]
This doesn't happen every time, but it has been happening EVERY OTHER time.  I have three conditiions that I want to compare (ampicillan, kanmycin and stationary).  I select all the conditions individually, and then click the genes button.  Half of the time nothing loads, and I see this error:
<img width="1432" alt="screen shot 2016-10-27 at 11 38 18 am" src="https://cloud.githubusercontent.com/assets/11475316/19774170/23577f7e-9c3a-11e6-9fa1-9c0a0c8d0378.png">

**Comment by mshukla1** [comment]
Private experiment dataset -> Sangurdeker dataset -> select few conditions -> load gene list

I think the problem is that the dataset is very large, which results in a delay in loading the data. 

This should be addressed when Harry migrates the private data logic to data API. 

-Maulik

**Comment by hyoo** [comment]
I guess I have fixed this issue. please try later today.

**Comment by mshukla1** [comment]
Checked on alpha. This seems to be resolved now. 

@ARWattam, please try it again and reopen the ticket if you still see the problem.
