### ISSUE TITLE
DLP: Genomic feature page - select genomes missing pattyfams

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1190]
Patric fams missing from select genomes list of attributes

<img width="969" alt="screen shot 2016-10-27 at 10 41 56 am" src="https://cloud.githubusercontent.com/assets/2152226/19774237/0a3d8054-9c32-11e6-9cc0-fdba5ba20f3e.png">

**Comment by hyoo** [comment]
#1182 duplicates

**Comment by mshukla1** [comment]
fixed. verified on alpha. 

<img width="974" alt="screen shot 2016-11-07 at 10 08 13 am" src="https://cloud.githubusercontent.com/assets/1236463/20064994/25d4e188-a4d2-11e6-94f5-32c6a1e4073a.png">
