### ISSUE TITLE
DLP: protein families data type page missing patric fams

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1191]
patric families entirely missing from https://www.beta.patricbrc.org/view/DataType/ProteinFamilies

**Comment by mshukla1** [comment]
We need to: 
- Add PL and PG fam to the description (Maulik)
- Update process diagram (Maulik)

**Comment by hyoo** [comment]
chart data is updated using PLfam. available on alpha.

**Comment by hyoo** [comment]
We still need other updates.

**Comment by hyoo** [comment]
@mshukla1 we need your input.

**Comment by mshukla1** [comment]
I have added descriptions for all three types of protein families.
