### ISSUE TITLE
Transcriptomics: featured experiment shows no features

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1193]
https://www.beta.patricbrc.org/view/DataType/Transcriptomics

click on Transcriptional profiles of Campylobacter jejuni NCTC 11168 to 0.125mg/L erythromycin treatment
click on Comparisons tab
select the one row, click on Genes

we see a page that says Loading briefly, and "1-1 of 0 results"
<img width="1291" alt="screen shot 2016-10-27 at 10 54 57 am" src="https://cloud.githubusercontent.com/assets/2152226/19774774/d49e4a8a-9c33-11e6-8f96-f6df9284d1b6.png">

**Comment by mshukla1** [comment]
The results loaded for me after few seconds. We need spinning wheel icon while browser waits for the data. 

-Maulik

<img width="1059" alt="screen shot 2016-10-27 at 3 08 01 pm" src="https://cloud.githubusercontent.com/assets/1236463/19783332/2ff6aaa8-9c57-11e6-9031-ec89cdf030fc.png">

**Comment by hyoo** [comment]
spinning wheel is added.
https://github.com/hyoo/p3_web/commit/2e3d828cfb85593731b3f50619dc2d12067cb350

will be available on alpha soon.

**Comment by mshukla1** [comment]
fixed. verified on alpha.
