### ISSUE TITLE
Home page: terminology mismatch 

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1194]
If you click on "Experiments" under Browse Data on the home page, it takes you to a page called Transcriptomics

**Comment by mshukla1** [comment]
Action: Change experiments to Transcriptomics. This will make it consistent with tabs, DLPs, and top menu. 

<img width="655" alt="screen shot 2016-10-27 at 3 04 40 pm" src="https://cloud.githubusercontent.com/assets/1236463/19783250/d1b3e046-9c56-11e6-822e-404a50ec7d0b.png">

**Comment by hyoo** [comment]
will be available on alpha soon.

**Comment by hyoo** [comment]
reopen to be confirmed.

**Comment by mshukla1** [comment]
@hyoo, thanks for changing the label. However, it has messed up the layout. Transcriptomics is now displayed on a second line. Can you fix it please? 

<img width="669" alt="screen shot 2016-10-29 at 5 09 30 am" src="https://cloud.githubusercontent.com/assets/1236463/19828810/0ca608f6-9d96-11e6-8dc7-a01059f30f38.png">

**Comment by mshukla1** [comment]
fixed. verified on alpha.
