### ISSUE TITLE
facebook is out of date

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1196]
Latest FB post was from May ... apparently folks can't upload pictures

**Comment by mshukla1** [comment]
@rkenyon, need to decide if we want to actively use/update PATRIC facebook account.  

If so, we could post the following: 
- links to data and software release
- advertise workshops / post workshop pictures
- highlight PATRIC related talks, presentations, papers, etc.

**Comment by mshukla1** [comment]
not anymore...as we know Rebecca is all over it now! :)
