### ISSUE TITLE
Taxon overview: Recent pubmed articles

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1197]
Some how I ended up on the landing page for "Bacteria".  this has the pane with recent pubmed articles.  I doubt this is useful for all bacteria.  I think that we should talk about when this should be displayed so that it isn't just taking up space.  

![image](https://cloud.githubusercontent.com/assets/7661533/19775064/c8456b50-9c34-11e6-984f-b18ae4b18780.png)

**Comment by mshukla1** [comment]
It may not be useful for all bacteria, however, it would be for almost any taxon level below it. 

If we selectively hide it for all bacteria, do you have any suggestions on other useful information that can go on the overview page? 

-Maulik

**Comment by mshukla1** [comment]
I am suggesting that we keep it as it is for the sake of consistency across all taxon landing pages.
