### ISSUE TITLE
Can't create new folder to put my annotated genome into

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#120]
I could create a folder, but couldn't name it.  Nor could I put my genome into an unnamed folder.  I had to put it into Genomes with all my other ones.

**Comment by dmachi** [comment]
I see this problem.  I assume you mean creating a folder from within the "Choose or upload a workspace object" dialog.  Creating a folder from the normal workspace is working fine for me.  

When you say put your genome into an unnamed folder, do you mean it wouldn't let you choose the above folder when you were doing annotation or assembly?  Or do you mean you could only create genome groups in the genome groups folder?

Dustin

**Comment by ARWattam** [comment]
Its when I was trying to put it into a folder for download.  And its when I had uploaded contigs for annotation.

Rebecca

----- Original Message -----

**Comment by dmachi** [comment]
Fixed and pushed to production.
