### ISSUE TITLE
Transcriptomics gene list: refseq locus tags are not displayed 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1200]
I am looking at my private transcriptomics dataset. For the same dataset, refseq locus tags are displayed in the gene list on the production site, but they are not displayed on the alpha site. 

<img width="1007" alt="screen shot 2016-10-29 at 4 50 23 am" src="https://cloud.githubusercontent.com/assets/1236463/19828723/72747b98-9d93-11e6-80de-c627a4178831.png">

<img width="1119" alt="screen shot 2016-10-29 at 4 52 18 am" src="https://cloud.githubusercontent.com/assets/1236463/19828725/7f604706-9d93-11e6-9bd3-7e49313d10ce.png">

**Comment by mshukla1** [comment]
Note that the problem seems to be only with private data. When I look at a public experiment, refseq loacus tags are displayed fine.

**Comment by hyoo** [comment]
deployed on alpha.

**Comment by mshukla1** [comment]
verified on alpha.
