### ISSUE TITLE
feature overview, small issue

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1203]
I am finding myself doing the math in my head to figure out how long these proteins are.  Can we have one more line for length in aa or nt?  length in nt is probably better since other features can be listed as well.

![image](https://cloud.githubusercontent.com/assets/7661533/19892502/3263bc12-a013-11e6-9846-045fbcab819a.png)

**Comment by hyoo** [comment]
reopen for verification
