### ISSUE TITLE
Filters are missing

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1210]
I searched for the following pattyfam, now I want to reduce it to a set of reference genomes, or complete genomes, or whatever:

![image](https://cloud.githubusercontent.com/assets/7661533/19907242/f25419d0-a04b-11e6-8597-a0b6cd741711.png)

**Comment by mshukla1** [comment]
The genome metadata is not available at the feature level, hence, those filters are not available.

For now, the way to do it would be to start top down, i.e. start with the genomes you are interested in as defined scope, and then search for the genes/families you are interested in. 

Prividing direct filters to allow users to find family members from ref/rep complete/wgs genomes would be major enhancement.

-Maulik

**Comment by mshukla1** [comment]
Given users may want to filter features by any of the genome metadata attributes, i.e. complete/wgs, reference/representative, amr resistance/susceptible etc, the way to do it is to first search for the genomes you are interested in and set the as your scope (or save them as group) and then search within those genomes for features of interest.

**Comment by rkenyon** [comment]
Jim triage comment: Low/no action.  Not sure if anything should be done about this one.  The issue is that if you start analyzing genomes based on a feature or pattyfam search, it is hard to pear down the list of output to a set of rational genomes..
