### ISSUE TITLE
MSA not working from feature group

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1212]
I selected my genes from the feature group and clicked MSA, and nothing happened.  I opened the developer tools so you could see the error message
<img width="1435" alt="screen shot 2016-11-03 at 9 40 27 am" src="https://cloud.githubusercontent.com/assets/11475316/19968151/bc0f23e2-a1a9-11e6-90b7-03ad95a08cee.png">

And here is the specific error message:

2url-change-tracker.js:73Uncaught TypeError: Failed to execute 'replaceState' on 'History': 2 arguments required, but only 1 present.
3https://www.beta.patricbrc.org/portal/portal/patric/FIGfam/FIGfamWindow?action=b&cacheability=PAGE Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by ARWattam** [comment]
I was working with some specific collaborators trying to get the msa...I wasn't watching a video or anything as you might assume from the screen shot.

**Comment by aswarren** [comment]
Tested from the speA feature group and it works
