### ISSUE TITLE
Genome browser annoyance

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1214]
I'm working in safari, and I have to resize the window to see any region to the right.  scrolling and the right arrow button will not show anything after (in this case 45,000).
![image](https://cloud.githubusercontent.com/assets/7661533/19972156/34116dd2-a1af-11e6-9ad7-640c7146e1a4.png)

Here is what it looks like after I resize the window, you can see that I missed about 1KB of genes.
![image](https://cloud.githubusercontent.com/assets/7661533/19972209/473f8aec-a1af-11e6-915a-65e4bdc11e86.png)

**Comment by dmachi** [comment]
I think andrew fixed this yesterday, not sure if it has made it onto beta yet.

**Comment by aswarren** [comment]
Indeed fixed as far as I know. I think Jim's example is a private genome so couldn't test on it explicitly.
