### ISSUE TITLE
BLAST: bug in blast

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1215]
I just did a blast of a protein against a large genome group and i cannot see how many hits  (hsps) there were. All I get is a table and I don't know offhand how many entries are in the table.  Is this all the HSPs? Is it some fraction of them????  If you are going to limit the output, you need a statement saying output limited to n/n hsps.

![image](https://cloud.githubusercontent.com/assets/7661533/19972695/e8660de6-a1b0-11e6-97d4-28adc6a1429a.png)

**Comment by hyoo** [comment]
will be available on alpha soon.

**Comment by mshukla1** [comment]
fixed. verified on beta.
