### ISSUE TITLE
genome table download

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1216]
It took me 10 minutes to figure out that the 9th field of a download genome table is the organism name and the 27 field is the genome identifier.  There is a ton of superfluous information before that.   I think it should be like "patric id" "genbank accession", "genome name"... ... ... in the order of things that are most useful and most human-readable.  The sequencing platform and where it was sequenced etc. should come later.

**Comment by mshukla1** [comment]
#1222
