### ISSUE TITLE
BLAST: Check boxes don't seem to be working when creating a feature group

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1217]
I did a Blast  and carefully selected 40 features out of the total 50 from the results and created a feature group.  When I went to that feature group in my workspace, I found all 50 there, not the group that I had specifically selected

**Comment by hyoo** [comment]
will be available on alpha soon.

**Comment by mshukla1** [comment]
Fixed. Verified on beta.
