### ISSUE TITLE
Why do some tables have check boxes, and some don't?  Shouldn't they all have them?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1218]
Blast results have check boxes:
<img width="1155" alt="screen shot 2016-11-03 at 1 52 25 pm" src="https://cloud.githubusercontent.com/assets/11475316/19978349/0614a66a-a1cd-11e6-8297-c4f628e5a1c4.png">

Workspace feature groups don't:
<img width="1101" alt="screen shot 2016-11-03 at 1 53 38 pm" src="https://cloud.githubusercontent.com/assets/11475316/19978364/157b03ba-a1cd-11e6-938e-4e797a3dce30.png">

**Comment by mshukla1** [comment]
There are multiple tables without checkboxes. Everyone, please address it in your respective pages.

**Comment by hyoo** [comment]
protein families tab and transcriptomics genes. this has been ticked multiple times.

**Comment by dmachi** [comment]
Yes, and it isn’t a matter of just enabling the checkboxes.  We know we want to add these, but it will take some effort on some of these tables due to how they are generated and the underlying store.

**Comment by mshukla1** [comment]
Is it the case that it is easy to add checkboxes when the table shows primary entities, 
i.e. features and genomes. But, it is harder to add check boxes when the table shows 
protein families and pathways, that require additional query to get corresponding 
genome/feature ids?

**Comment by dmachi** [comment]
The problem is that for in-memory stores (client side generated stores that don’t have a 1-1 match with a backend data source), there seems to be an issue with the underlying store matching up with the checkbox selector plugin.

Dustin

**Comment by hyoo** [comment]
will be available on alpha soon.

**Comment by mshukla1** [comment]
it seems all tables have checkboxes now. verified on beta.
