### ISSUE TITLE
PATRIC not showing strain name

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1219]
I’m finding some errors in the metadata sheet from the last round.  A couple of times I’ve seen that the strain isn’t listed in the data you sent.  For instance, the GenBank Accession goes to Leptospira inadai serovar Lyme strain M34/99 and in PATRIC its listed as Leptospira inadai serovar Lyme.  We are missing the strains in some instances.

Genome ID: 293084.5
GenBank Accession: MCRM00000000

**Comment by mshukla1** [comment]
Updating genome names for 1635 genomes in total to include strain names, including the one reported here.
