### ISSUE TITLE
Is it possible to add locus tag to BLAST results?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1220]
It currently is not in the drop down box for adding a column.
<img width="1154" alt="screen shot 2016-11-03 at 2 39 32 pm" src="https://cloud.githubusercontent.com/assets/11475316/19980176/73e90342-a1d3-11e6-885a-e0e8ae25be20.png">

**Comment by mshukla1** [comment]
@hyoo, I think we should be able to display refseq locus tags as they are part of the fasta def lines. Please check if they are available from the service.

**Comment by hyoo** [comment]
we already bind the blast result to genome feature to provide selector actions. so any field in genome feature can be available on this grid.

**Comment by hyoo** [comment]
available on alpha and beta.

**Comment by mshukla1** [comment]
BLAST now shows all useful fields,  genome id, genome name, patric id, refseq locus tag, gene name and product. 

Verified on beta.
