### ISSUE TITLE
Genome table file download

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1222]
Woah, each time you download a genome table the fields change!  

The first image is the list of  representative and reference genomes.  It starts with sequencing depth: 
![image](https://cloud.githubusercontent.com/assets/7661533/19982104/b2911aea-a1d2-11e6-9657-afd9f2233556.png)

The second image is representative genomes only and starts with plasmids

![image](https://cloud.githubusercontent.com/assets/7661533/19982123/cff4b2ea-a1d2-11e6-86b7-e8045ef4054f.png)

This is a huge pain.

**Comment by mshukla1** [comment]
This is applicable to ALL table downloads. We need properly arrange all columns in ALL table downloads throughout the site. Without that, the downloaded files look like garbage!!!

**Comment by dmachi** [comment]
There was code in here to do this already, but we were encountering a bug where that code was being skipped in the case of a streamed download.  That has been fixed and will be pushed to alpha soon.  However, I need some help for the rest of this ticket.

There is a middleware function that defines what the default fields (and order) are for both genome and genome_feature data types.  I need the same list for the rest of the data types.  Keep in mind that if a query specifically includes a field list  ( select() in rql or &fl= in solr ), that will be used for both the field selection and order of data in the download files.  However, the cases we have been talking about are the default case where no specific field list is given to the api.  

The definitions can be seen here: https://github.com/PATRIC3/p3_api/blob/master/middleware/ExtractCustomFields.js#L14-L37

Please add additional data types/fieldSelections to this function or give me a list for the other data types and then I can add them.

**Comment by dmachi** [comment]
@hyoo is going to update the field definitions.

**Comment by hyoo** [comment]
we have added column definitions for
- genome
- feature
- sequence
- transcriptomics experiments
- transcriptomics comparisons
- specialty genes

and also added client level grid download for all three sub-tabs in pathways.

**Comment by mshukla1** [comment]
Checked downloads from all the pages listed above and they now seems well formatted and as expected.
