### ISSUE TITLE
When you edit and resubmit BLAST, the results return pre-checked!

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1223]
How convenient...well, not really.  I used the "Edit and Resubmit" option.  I have reported previously that the page loads funny.  This time the results returned with them already selected.
<img width="1155" alt="screen shot 2016-11-03 at 4 27 57 pm" src="https://cloud.githubusercontent.com/assets/11475316/19984030/dcecd6a2-a1e2-11e6-8af1-d4687450607e.png">

**Comment by ARWattam** [comment]
And when it comes pre-selected, I have no options in the magic green bar.  :(  It wasted my BLAST! :(
<img width="1166" alt="screen shot 2016-11-03 at 4 32 12 pm" src="https://cloud.githubusercontent.com/assets/11475316/19984088/2e12a926-a1e3-11e6-91f9-8d8c1596b125.png">

**Comment by hyoo** [comment]
reopen for verification

**Comment by mshukla1** [comment]
edit and resubmit has been fixed. verified on beta.
