### ISSUE TITLE
Good to show columns for conditions transcriptomics to see which conditions the genes had altered expression

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1224]
USER Request
Using the Expression Import Service: We can see only in how many conditions 
certain gene is up or down regulated. We could have columns for each 
condition, so we know exactly in which conditions the gene had altered 
expression.

**Comment by mshukla1** [comment]
In the current design, the tabular view is is meant to provide the summary of expression and the heatmap is meant to provide detail view showing expression of each gene in each condition. I don't think we need to change anything there. 

However, We need to add ability to download the entire gene list  as an excel file with expression values, which is already covered by another ticket. #1225 

Closing the ticket as redundant.
