### ISSUE TITLE
Inability to download table from differential expression results

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1225]
User report from UF workshop
I was not able to download this table displaying the differential 
expression (DE) results (not as text nor as csv files). And I would like to 
do it for the more than 4,000 E. coli genes. But even selecting the first 
200 displayed genes I was not able to download.

**Comment by mshukla1** [comment]
@hyoo we don't have the buttons at the top for downloading the entire table without making selection. We need it for downloading the table as txt and excel and also for downloading entire table as gene matrix with expression values.

**Comment by hyoo** [comment]
for verification

**Comment by mshukla1** [comment]
@hyoo, I don't see download button for the entire table on alpha!

**Comment by hyoo** [comment]
same as protein family download. right above the main grid.
![image](https://cloud.githubusercontent.com/assets/1236467/20316334/0629e0bc-ab27-11e6-95f2-33e32c608048.png)

**Comment by mshukla1** [comment]
fixed. verified on alpha.
