### ISSUE TITLE
Downloadable heatmap image

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1228]
User request:

We frequently get this request for a downloadable image of the heatmap so users can put them into publicatons

**Comment by hyoo** [comment]
you can always capture your screen. as far as I remember, downloading flash heatmap has been discussed from the beginning of the PATRIC2, since it can goes up to take 10ish GB. The screen capture is the easiest way people can do with their current technology.

**Comment by ARWattam** [comment]
If its the whole genome, you can't compress it enough to take a screenshot of the whole thing.

----- Original Message -----

**Comment by mshukla1** [comment]
Harry, I am thinking this should be considered as one of the desired features 
when we select next heat map technology, i.e. HTML5 or javascript version of 
heat map. Hence, I have marked it as enhancement. 

No action is expected with the current implementation. 

-Maulik

**Comment by mshukla1** [comment]
@nconrad Can the new heatmap support export as high quality image?

**Comment by nconrad** [comment]
There may be some options for .png, but since it's WebGL, I'd have to figure create some solution for svg.  I'll see what's possible.

**Comment by nconrad** [comment]
It's probably not perfect, but there is an SVG download button with the new viewer, so I'm going to close this.
