### ISSUE TITLE
GenBank ID number we have not found in Genbank.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1231]
Genome Id is 	284037.4
GenBank Accessions we list: MDFG00000000KV757140,KV757141,KV757142,KV757143,KV757144,KV757145
When I searched for MDFG00000000KV757140 at GenBank, it didn't return anything
When I clicked the hyperlink at PATRIC, it also didn't return for that accession number
<img width="747" alt="screen shot 2016-11-05 at 8 57 55 am" src="https://cloud.githubusercontent.com/assets/11475316/20030195/60e964ee-a336-11e6-8332-95de95ea4255.png">

**Comment by mshukla1** [comment]
The accessions are combination of WGS master record and bunch of assembled plasmids. There is a comma missing between MDFG00000000 and KV757140 (MDFG00000000KV757140). I will correct the data. 

-Maulik

**Comment by mshukla1** [comment]
Fixed 81 genomes with such fused accession in solr.
