### ISSUE TITLE
Another genome missing strain name

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1232]
Genome id is 336810.23
Name in PATRIC is Candidatus Sulcia muelleri
GenBank accession is CP016223
Name at GenBank is Candidatus Sulcia muelleri strain NC
Could the name be coming from the organism tag?
<img width="752" alt="screen shot 2016-11-05 at 9 19 59 am" src="https://cloud.githubusercontent.com/assets/11475316/20030324/1855fb7c-a339-11e6-86e2-d5f1fbf2313f.png">

**Comment by mshukla1** [comment]
Updating genome names for 1635 genomes in total to include strain names, including the genome reported here.
