### ISSUE TITLE
335 Genome IDs that are missing strains in PATRIC, and with strain names at GenBank -

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1233]
Genome IDs that are missing strains that are present at GenBank.  This is just for the last release.  I think we need to go in and check the rest of the genomes in the database
135461.32
135461.24
135461.25
135461.27
135461.33
302912.6
1682.27
1682.29
1679.14
1679.20
1679.24
1679.22
1679.21
1679.23
32019.24
1507806.16
1507806.17
1507806.21
1507806.12
1507806.10
1507806.6
1507806.8
1507806.19
1507806.18
1507806.14
1507806.25
1507806.24
1507806.29
1507806.30
1507806.31
1507806.28
1507806.26
1507806.27
32020.6
32020.10
32020.9
32020.7
32020.12
32020.11
32022.219
32022.220
252393.12
132144.8
132144.9
132144.10
336810.23
1427364.7
189385.10
155515.4
155515.6
505345.6
505345.8
505345.7
1463164.10
1463164.9
66976.18
66976.17
59736.7
293084.5
211880.10
766041.3
202462.4
85581.13
85581.15
38294.24
286156.4
386.135
59201.240
59201.238
59201.237
59201.242
59201.301
59201.302
59201.300
59201.303
59201.299
59201.252
59201.256
59201.261
59201.258
59201.257
59201.259
59201.255
59201.254
59201.265
59201.264
59201.262
59201.263
59201.260
59201.277
59201.281
59201.279
59201.280
59201.282
59201.283
59201.278
59201.251
59201.253
59201.266
59201.267
59201.273
59201.275
59201.270
59201.274
59201.268
59201.272
59201.271
59201.276
59201.284
59201.287
59201.286
59201.285
59201.290
59201.289
59201.288
59201.269
59201.297
59201.291
59201.294
59201.295
59201.293
59201.296
59201.292
59201.298
149539.468
149539.462
149539.461
149539.465
149539.464
149539.460
149539.466
149539.463
149539.467
149539.451
149539.449
149539.450
149539.457
149539.453
149539.459
149539.452
149539.458
149539.455
149539.456
149539.454
611.105
611.108
611.112
611.114
611.116
611.111
611.121
611.122
611.123
611.125
611.129
611.128
611.127
611.126
611.119
611.120
611.124
595.54
595.55
70803.6
115981.41
115981.42
1173869.3
596.23
596.24
600.12
600.14
90371.1913
90371.1914
90371.1921
90371.1922
90371.1923
712528.4
1884263.3
46170.232
46170.233
46170.238
46170.249
46170.240
46170.239
46170.241
46170.246
46170.248
46170.244
46170.247
46170.245
46170.243
46170.242
119602.67
119602.65
119602.74
119602.75
119602.78
119602.72
119602.69
119602.77
119602.76
119602.73
53354.9
161.18
161.19
161.20
161.17
161.16
161.15
161.37
161.30
161.31
161.28
161.29
161.36
161.33
161.35
161.24
161.34
161.27
161.26
161.22
161.25
161.23
161.21
152263.8
227946.17
227946.18
227946.16
134875.17
134875.15
134875.16
487909.12
487909.15
487909.16
1348101.3
1348101.4
1835721.3
905011.3
162156.4
162156.5
162156.3
162156.7
765821.5
765821.7
765821.8
765821.3
765821.10
765821.12
765821.6
765821.14
765821.13
765821.15
1193532.3
1193532.4
59620.11
59620.6
59620.4
59620.7
59620.19
59620.39
59620.13
59620.22
59620.24
59620.30
59620.26
59620.32
59620.34
59620.36
59620.38
59620.49
59620.44
59620.46
59620.40
59620.55
59620.58
59620.41
59620.43
59620.42
59620.57
59620.50
59620.52
59620.53
59620.51
59620.48
59620.45
59620.47
59620.60
59620.54
59620.56
59620.59
165190.3
458253.5
458253.6
286138.4
165185.7
165185.6
165185.9
165185.4
165185.3
165185.5
165185.10
165185.11
259315.3
259315.5
1193534.3
1193534.6
1193534.5
1193534.7
1193534.8
446043.3
165188.4
876091.4
876091.3
512314.3
512314.4
165186.13
165186.17
165186.16
165186.18
165186.21
165186.3
165186.5
165186.4
165186.8
165186.12
165186.19
165186.25
165186.24
165186.23
165186.22
165186.26
165186.27
165186.28
165186.29

**Comment by mshukla1** [comment]
Updating genome names for 1635 genomes in total to include strain names. The list also includes 335 genomes reported here. 

-Maulik
