### ISSUE TITLE
ARDB and CARD

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1236]
Here is an example of the links that are provided to a CARD match.  Both links just take you back to the card front page, they don't actually take you to the entry in card, which is not very helpful.  

Its most particularly annoying in this case because both links take you to the CARD home page.

![image](https://cloud.githubusercontent.com/assets/7661533/20102923/7f836194-a58d-11e6-8184-f89ac1f251fd.png)

**Comment by chmao1** [comment]
Fixed to use CARD ID in the source ID column. However, we currently can’’t create links for CARD IDs. The new links will be provided when they're available. This fix will be included in the next build. @mshukla1 @jimdavis1
