### ISSUE TITLE
BLAST bugs

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1237]
1. The "genome" and "feature" buttons lead you astray when you blast against contigs.  Genome just sends you to the landing page for that genome, which is worthless.  If anything, the genome link should really take you to the region on the genome in the genome browser, but it doesn't.

2. If you click on one of these buttons, you cannot get back to your blast job.  It is lost and you have to re-blast.

![image](https://cloud.githubusercontent.com/assets/7661533/20104017/e333448a-a591-11e6-96c4-a2b37694055c.png)

**Comment by hyoo** [comment]
if you are looking for a region, you should use features. the green bar and buttons are working based upon items you choose. in this case, you searched for "contig" and all the actions are those available for a genome sequence.

**Comment by hyoo** [comment]
reopen for verification.
1.  I have added "genome browser" button so that users can see the hit in the genome context.
2. all the action buttons will open a new tab/window.

**Comment by mshukla1** [comment]
Verified fixes on beta. 

@hyoo, the genome browser link currently doesn't show PATRIC or RefSeq features in the selected region. Can you enable those tracks in the link?

**Comment by hyoo** [comment]
no it shows by default.

![image](https://cloud.githubusercontent.com/assets/1236467/21398462/ffa3a400-c76c-11e6-9aa6-641f67f18653.png)

this is my private genome, so this is showing only PATRIC annotations.
