### ISSUE TITLE
Information panel for parameters in Variant Service could be more informative

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1239]
Working on the new tutorial...we need to put more text in here that describes the aligners and the snp callers.
<img width="659" alt="screen shot 2016-11-08 at 10 16 50 am" src="https://cloud.githubusercontent.com/assets/11475316/20104628/b0cb598c-a59c-11e6-984e-953535c393d8.png">

**Comment by aswarren** [comment]
Including @levinas . Got a piece of information from him the other day concerning bwa-mem-strict but still need any info he is interested in including on how the other options are run.
Specifically: 
      "enum": [
        "BWA-mem",
        "BWA-mem-strict",
        "Bowtie2",
        "MOSAIK",
        "LAST"
      ]
and 
      "enum": [
        "FreeBayes",
        "SAMtools"
      ]

**Comment by levinas** [comment]
Updated helper text in https://github.com/dmachi/p3-web/pull/56
