### ISSUE TITLE
Thumbnails in Data Landing Pages Tutorials section go to wrong URLs.

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#124]
For example, on the Genomes Data Landing Page, in the Tutorials section, the PATRIC Data Organization Overview link goes to the correct URL, but the thumbnail beside it goes back to the Genomes DLP.  As far as I checked, all of the Tutorial thumbnail links have this problem.

**Comment by hyoo** [comment]
fixed
