### ISSUE TITLE
Error submitting variant service job.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1240]
Why does this always happne when I'm making tutorials???
Error Submitting Job
submit failed: Can't connect to redwood.mcs.anl.gov:7080 (Connection refused) LWP::Protocol::http::Socket: connect: Connection refused at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/LWP/Protocol/http.pm line 49. { "info" : { "priority" : 2, "userattr" : { "parameters" : "{\n \"single_end_libs\" : [\n {\n \"read\" : \"/ARWattam@patricbrc.org/home/SRR396518.fastq.gz\"\n },\n {\n \"read\" : \"/ARWattam@patricbrc.org/home/SRR396519.fastq.gz\"\n },\n {\n \"read\" : \"/ARWattam@patricbrc.org/home/SRR396520.fastq.gz\"\n },\n {\n \"read\" : \"/ARWattam@patricbrc.org/home/SRR396521.fastq.gz\"\n }\n ],\n \"output_file\" : \"MG1655 vs SRR39651X\",\n \"mapper\" : \"BWA-mem\",\n \"output_path\" : \"/ARWattam@patricbrc.org/home/Variation\",\n \"caller\" : \"FreeBayes\",\n \"reference_genome_id\" : \"511145.12\"\n}\n", "workspace" : null, "app_id" : "Variation", "task_file_id" : "87bb5e6c-3433-4d25-8342-46d623d7a63d" }, "clientgroups" : "AppService-p3.theseed.org", "project" : "AppService", "user" : "ARWattam@patricbrc.org", "name" : "Variation", "pipeline" : "AppService" }, "tasks" : [ { "userattr" : {}, "outputs" : { "awe_stderr.txt" : { "name" : "awe_stderr.txt", "node" : "-", "host" : "http://p3.theseed.org/services/shock_api" }, "awe_stdout.txt" : { "name" : "awe_stdout.txt", "node" : "-", "host" : "http://p3.theseed.org/services/shock_api" } }, "dependsOn" : [], "cmd" : { "name" : "App-Variation", "args" : "https://p3.theseed.org/services/app_service/task_info @app @params", "description" : "App-Variation", "environ" : { "private" : "taskid" : "0", "inputs" : { "params" : { "name" : "params", "node" : "f67e7400-2f05-41e6-bb8b-25ea8daac6d3", "host" : "http://p3.theseed.org/services/shock_api" }, "app" : { "name" : "app", "node" : "d6c422ac-0bdb-40d3-8075-9115d52e1953", "host" : "http://p3.theseed.org/services/shock_api" } }, "partinfo" : {}, "skip" : 0, "totalwork" : 1 } ] }

**Comment by mshukla1** [comment]
Awe crashed. Service worked fine after Bob restarted the server. 

-Maulik
