### ISSUE TITLE
After clicking Reset, reads still loaded in variant service

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1241]
Reset only appears to work on parameters.  Is that by design?
<img width="813" alt="screen shot 2016-11-08 at 12 26 09 pm" src="https://cloud.githubusercontent.com/assets/11475316/20109572/a61ebc42-a5ae-11e6-9eaa-f4692b801bfe.png">

**Comment by aswarren** [comment]
Fixed in https://github.com/PATRIC3/p3_web/pull/301
