### ISSUE TITLE
Multiple pegs highlighted in feature cartoon

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1242]
See https://www.beta.patricbrc.org/view/Feature/fig%7C1115819.3.peg.1366

There are two features highlighted in red on the context cartoon

![screen shot 2016-11-08 at 11 57 35 am](https://cloud.githubusercontent.com/assets/2152226/20110588/9a856524-a5aa-11e6-8044-90fa27a80eaf.png)

**Comment by hyoo** [comment]
for verification
