### ISSUE TITLE
Why can I load the same file multiple times into the variation service?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1243]
<img width="662" alt="screen shot 2016-11-08 at 4 42 02 pm" src="https://cloud.githubusercontent.com/assets/11475316/20118420/5cef7556-a5d2-11e6-9931-ee2b556dc9d5.png">

**Comment by aswarren** [comment]
Fixed in https://github.com/PATRIC3/p3_web/pull/301
