### ISSUE TITLE
MSA viewer not matching the right sequence in the MSA and tree

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1249]
Look at this alignment of arginase.  According to the tree and the line up of the sequence in the msa, B. melitensis abortus 2308 should start with MGNLAP:
<img width="1345" alt="screen shot 2016-11-14 at 4 46 36 pm" src="https://cloud.githubusercontent.com/assets/11475316/20284255/63cee7f0-aa8a-11e6-91be-b3315f91f634.png">

When you look at the actual sequence for this gene, it actually begins with MHCKILG:
<img width="1077" alt="screen shot 2016-11-14 at 4 47 21 pm" src="https://cloud.githubusercontent.com/assets/11475316/20284297/80209ab6-aa8a-11e6-9645-0ab25c42ee7d.png">

**Comment by aswarren** [comment]
https://www.beta.patricbrc.org/view/MSA/?in(feature_id,(PATRIC.575591.3.NZ_GG703762.CDS.432658.433578.fwd,PATRIC.430066.4.NC_010740.CDS.335512.336432.fwd,PATRIC.262698.4.NC_006933.CDS.335453.336373.fwd,PATRIC.520450.3.NZ_DS999911.CDS.432735.433523.fwd,PATRIC.520451.3.NZ_DS999893.CDS.935697.936485.rev,PATRIC.520452.3.NZ_DS999881.CDS.431099.432019.fwd,PATRIC.520453.4.NZ_GG774528.CDS.223169.223957.fwd,PATRIC.520454.3.NZ_DS999869.CDS.220731.221651.fwd,PATRIC.520455.3.NZ_EQ999630.CDS.220856.221776.fwd,PATRIC.641140.3.NZ_ACOR01000007.CDS.335482.336402.fwd,PATRIC.483179.4.NC_010104.CDS.880033.880953.rev,PATRIC.520457.3.NZ_EQ999619.CDS.982784.983704.rev,PATRIC.520460.3.NZ_DS999686.CDS.971176.972096.rev,PATRIC.520458.3.NZ_EQ999599.CDS.222985.223905.fwd,PATRIC.520459.3.NZ_DS999669.CDS.970874.971794.rev,PATRIC.595497.3.NZ_ACJD01000007.CDS.349763.350671.rev,PATRIC.470735.4.NZ_ADEZ01000040.CDS.47485.48405.rev,PATRIC.546272.3.NC_012442.CDS.859948.860868.rev,PATRIC.359391.4.NC_007624.CDS.335522.336442.fwd,PATRIC.224914.11.NC_003318.CDS.416697.417617.fwd,PATRIC.224914.16.NZ_GG703779.CDS.949637.950425.rev,PATRIC.520464.3.NZ_EQ999555.CDS.949336.950256.rev,PATRIC.520465.3.NZ_ACEM01000009.CDS.93800.94720.fwd,PATRIC.520466.3.NZ_EQ999588.CDS.220437.221357.fwd,PATRIC.568815.3.NC_013118.CDS.881858.882778.rev,PATRIC.520456.3.NZ_EQ999575.CDS.221226.222146.fwd,PATRIC.444178.3.NC_009504.CDS.882398.883318.rev,PATRIC.520461.3.NZ_DS999849.CDS.218106.219026.fwd,PATRIC.520463.3.NZ_DS999750.CDS.221316.222236.fwd,PATRIC.520462.3.NZ_EQ999534.CDS.217859.218779.fwd,PATRIC.520449.3.NZ_DS999659.CDS.362210.363130.fwd,PATRIC.693750.4.NZ_ADFA01000079.CDS.24836.25756.fwd,PATRIC.437701.3.NZ_GG663472.CDS.999739.1000647.rev,PATRIC.693748.4.NZ_ADFB01000055.CDS.43911.44831.rev,PATRIC.520448.3.NZ_GG770511.CDS.982990.983910.rev,PATRIC.204722.5.NC_004311.CDS.880732.881652.rev,PATRIC.470137.4.NC_010167.CDS.868354.869142.rev,PATRIC.520487.3.NZ_DS999731.CDS.963330.964118.rev,PATRIC.520488.3.NZ_GG703794.CDS.221071.221991.fwd,PATRIC.520489.3.NZ_DS999712.CDS.954962.955882.rev))
