### ISSUE TITLE
MGRAST page in PATRIC is dead link

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#125]
https://www.patricbrc.org/portal/portal/patric/MGRAST gives a missing page error

**Comment by dmachi** [comment]
The way this iframe is created, it uses 

<iframe id="iframe_rast" src="//metagenomics.nmpdr.org/" height="500" title="MG-RAST Service" seamless="" style="height: 536px;"></iframe>

In this case, that makes the link go to https://metagenomics.nmpdr.org/  which does not exist.  Only http://metagenomics.nmpdr.org exists. This probably won't be embeddable in this way any more.

**Comment by hyoo** [comment]
This works on safari. But I also have a problem on chrome.
IF we don't like iframe idea, we can directly link to their page. And we may want to rephrase the description above the iframe, which is "PATRIC includes a collaboration with the University of Chicago to provide a meta genome annotation service using the MG-RAST system."

**Comment by hyoo** [comment]
We decided to change to a direct link (http://metagenomics.nmpdr.org/, not https!!).
Harry will change JBoss link, Dustin will change p3-web side, Ron will change in wordpress.

**Comment by hyoo** [comment]
I have fixed the JBoss link and committed to jboss_patric repo.

**Comment by rkenyon** [comment]
I have also updated the link in the Tools page in Wordpress.

Ron Kenyon
PATRIC Project Manager, patricbrc.org
Project Management Director
Virginia Bioinformatics Institute, Virginia Tech
Ph: 540-231-7470

**Comment by dmachi** [comment]
Updated the p3-web side.

**Comment by brettin** [comment]
I wonder if the link should be metagenomics.anl. gov

**Comment by hyoo** [comment]
Yes, indeed I notice the new url after redirection. I made a link to metagenomics. <http://metagenomics.nl/>anl.gov. and Dustin will change so. 

Harry
