### ISSUE TITLE
Persistant pop-up

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1250]
I've been going back and forth to one of my feature groups, and after a couple of times the pop-up window just keeps sticking around through several iterations.  A tad annoying.
<img width="1386" alt="screen shot 2016-11-14 at 5 35 37 pm" src="https://cloud.githubusercontent.com/assets/11475316/20285611/e191567c-aa90-11e6-81eb-c9e2d42389f4.png">

**Comment by ARWattam** [comment]
Notice that the pop-up is not even for the genome that the page is on.

**Comment by mshukla1** [comment]
@ARWattam, this might be browser freeze on your side. I am not able to reproduce it on alpha or beta.
