### ISSUE TITLE
Why isn't the strain name appearing in the breadcrumb.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1251]
I had to search down the page to find that I was on the abortus Tulya strain.  It should be in the breadcrumb.
<img width="846" alt="screen shot 2016-11-14 at 5 37 39 pm" src="https://cloud.githubusercontent.com/assets/11475316/20285670/29a72d74-aa91-11e6-9248-21dee4a30d51.png">

**Comment by mshukla1** [comment]
Agree, for feature level pages, genome name should be part of the breadcrumb, like on the production site. 

<img width="594" alt="screen shot 2016-11-15 at 11 45 18 am" src="https://cloud.githubusercontent.com/assets/1236463/20316815/26e3ff7a-ab29-11e6-8428-85f85829eddf.png">

**Comment by dmachi** [comment]
I don’t mind having this ticket assigned to me, but i have 50+ tickets for november and this issue doesn’t require any special knowledge that I have to complete. I think you should only assign tickets to a particular person when that person is going to be needed to resolve the ticket.

**Comment by chmao1** [comment]
Fixed and made a pull request.
