### ISSUE TITLE
Ability to remove features from Feature Group seems to be missing

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1254]
Rats!  Things seem to disappear right when I need them!
<img width="1183" alt="screen shot 2016-11-15 at 7 12 18 am" src="https://cloud.githubusercontent.com/assets/11475316/20305327/fea6abc8-ab02-11e6-9d18-ca046a9340ba.png">

**Comment by hyoo** [comment]
this is fixed on production long time age.

**Comment by ARWattam** [comment]
How come when I select more than 2 in my feature group, the remove button disappears in the green bar?
