### ISSUE TITLE
Download from feature group returns nothing

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1255]
I can't remember if this was supposed to be fixed, is a new issue, or what but here goes.  I went to workspace and found the feature group I was interested in. Check boxes appear to be missing, btw.  I selected them all and hit download, chose txt, and got el zippo!
<img width="643" alt="screen shot 2016-11-15 at 7 22 46 am" src="https://cloud.githubusercontent.com/assets/11475316/20305647/8cbdc58a-ab04-11e6-811b-f3c934d8ea0b.png">
<img width="1440" alt="screen shot 2016-11-15 at 7 22 57 am" src="https://cloud.githubusercontent.com/assets/11475316/20305652/93829fb2-ab04-11e6-979e-8707381e3db4.png">

**Comment by mshukla1** [comment]
#1164

**Comment by nconrad** [comment]
I'm making this "fixed" since the download button in the green action bar should work now.
