### ISSUE TITLE
Download from feature group not working on Production, either.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1256]
selected features:
<img width="1231" alt="screen shot 2016-11-15 at 7 27 24 am" src="https://cloud.githubusercontent.com/assets/11475316/20305753/0fad0244-ab05-11e6-8bd3-534e2ca8c788.png">

and the corresponding download:
<img width="639" alt="screen shot 2016-11-15 at 7 27 53 am" src="https://cloud.githubusercontent.com/assets/11475316/20305759/194afed2-ab05-11e6-8294-40336c363067.png">

**Comment by mshukla1** [comment]
Need to get rid of the old genome and feature group pages implemented in the workspace and, instead, link to the new genome and feature list views. 

#1164

**Comment by ARWattam** [comment]
Confirmed that it works on production
