### ISSUE TITLE
Click on what I think is finished annotation job and get....?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#126]
I can't figure out what I'm getting, but its not the nice list of folders that I expected.  See attached screenshot.
![screen shot 2015-03-27 at 7 00 23 am](https://cloud.githubusercontent.com/assets/11475316/6866476/0e7c5732-d44f-11e4-9121-60e33c6ead5e.png)

**Comment by aswarren** [comment]
@ARWattam Can you confirm that this is actually a genome you uploaded and not the result of an assembly job? I presume its not the result of annotation job since annotation jobs don't produce fasta files.

**Comment by ARWattam** [comment]
Yes, it is indeed an annotation and not an assembly.

Rebecca

----- Original Message -----

**Comment by aswarren** [comment]
A fix for this has been committed.
