### ISSUE TITLE
Not able to see genome IDs in BLAST drop down

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1261]
This limits choosing the genome that I want.   
![screen shot 2016-11-15 at 2 05 03 pm](https://cloud.githubusercontent.com/assets/11475316/20320281/580d1346-ab3f-11e6-956b-214547636fce.png)

**Comment by hyoo** [comment]
firefox
![image](https://cloud.githubusercontent.com/assets/1236467/20458728/18fe89a6-ae72-11e6-9be5-2f42e9a07a8b.png)

chrome
![image](https://cloud.githubusercontent.com/assets/1236467/20458731/28ea5d68-ae72-11e6-9348-64ceaf37475e.png)

safari
![image](https://cloud.githubusercontent.com/assets/1236467/20458734/4e1b6f82-ae72-11e6-99cc-ab10a4d5755d.png)

**Comment by mshukla1** [comment]
genome ids are now visible even for genomes with long names. verified on beta.
