### ISSUE TITLE
Using genome ID to select genome in BLAST doesn't work.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1262]
As I couldn't scroll over to see the genome ID to select my genome of interest, I tired using the genome ID in the Blast genome text box.  It says that is not valid.
<img width="836" alt="screen shot 2016-11-15 at 2 28 01 pm" src="https://cloud.githubusercontent.com/assets/11475316/20320412/c0b06cea-ab3f-11e6-8c03-9559195eb790.png">

**Comment by hyoo** [comment]
duplicate #849 
fixed in PATRIC3/p3_web#344

**Comment by ARWattam** [comment]
Confirmed that it works on production
