### ISSUE TITLE
implement facets for PATRIC_VF page

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1263]
![image](https://cloud.githubusercontent.com/assets/1236467/20321631/c126bd72-ab3b-11e6-95c5-01b891f977ec.png)

JBoss version has specialized facets for this page. In current implementation, we don't have an option to create facets outside the page scope, but we need to extend it so that we can implement those.

![image](https://cloud.githubusercontent.com/assets/1236467/20321655/d5ae820c-ab3b-11e6-8e4c-aa10b85767d5.png)

**Comment by chmao1** [comment]
Implemented and will be available in the next build.

**Comment by hyoo** [comment]
![image](https://cloud.githubusercontent.com/assets/1236467/25008805/669ae1b2-202a-11e7-9e8b-3a0d776243c6.png)

https://www.patricbrc.org/view/SpecialtyVFGeneList/?keyword(*)&eq(source,PATRIC_VF)

Yes, it works.
