### ISSUE TITLE
Feature group creation. BLAST and elsewhere

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#1265]
When a selection of features is made it should be possible to create a group of Genomes or Features.
For a working example see MSA group creation.
In SelectionToGroup.js there is a selectType: false parameter that can be enabled in appropriate places As part of this dedup logic needs to be added to WorkspaceManager.js The addToGroup function already has some but createGroup does not.

**Comment by hyoo** [comment]
This is not a BLAST UI issue. Rather, as you mentioned, a generic AddToGroup widget issue. We used to have an option saying "create genome group" in old widget (JBoss).

**Comment by mshukla1** [comment]
We should apply this to the feature group creation widget in general. 

<img width="1122" alt="screen shot 2017-09-17 at 1 42 44 pm" src="https://user-images.githubusercontent.com/1236463/30523827-22fc0468-9bae-11e7-8626-0d33956d0f59.png">

**Comment by dawenx** [comment]
OK, I will start to work on this.

**Comment by dawenx** [comment]
@aswarren it looks like group creation is not working on MSA when I chose to create a genome group: well, the group was created (see screenshot 1), but when i tried to view it from workspace, it does not have valid data (see screenshot 2). can you take a look? thanks!
![issue_1265_1](https://user-images.githubusercontent.com/26723038/31027565-98c67480-a518-11e7-9de8-515c00183a05.png)
![issue_1265_2](https://user-images.githubusercontent.com/26723038/31027569-9de2fd76-a518-11e7-98ec-b4e0d034fa82.png)

**Comment by dawenx** [comment]
i created a separate issue to address some general issues in group creation. this issue only handles its original request: allow selection of group type when handling feature list.

**Comment by dawenx** [comment]
@mshukla1 i have enabled genome group creation from feature selection in Feature tab, IDMapping result, interaction tab, pathway summary tab and protein families tab.

I did not make change in Transcriptomics Gene Heatmap case because feature group creation is not working, and i opened issue #1741.

**Comment by mshukla1** [comment]
Thanks, Dawen. I will test it once it is on alpha. 

-Maulik

**Comment by dawenx** [comment]
@mshukla1 fyi, it's on alpha now.
