### ISSUE TITLE
Download specific data from genome groups

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1266]
In production, I can go to the data download tool and get my fasta files to build a tree:
<img width="1427" alt="screen shot 2016-11-15 at 4 51 31 pm" src="https://cloud.githubusercontent.com/assets/11475316/20325752/ebcfb5fc-ab53-11e6-84c7-df396c8fb1dc.png">

On beta, I can't figure out how to do it from the groups page.  I think that this is pretty important to maintain.
<img width="1440" alt="screen shot 2016-11-15 at 4 50 34 pm" src="https://cloud.githubusercontent.com/assets/11475316/20325787/0cb01a28-ab54-11e6-997f-bb10af6ca8b7.png">

**Comment by dmachi** [comment]
It should be under the More Options in the download button you selected.

**Comment by ARWattam** [comment]
Thank you!  I knew I had seen it before, but couldn't remember how to get there.

----- Original Message -----

**Comment by mshukla1** [comment]
I believe there is no follow up action here, so closing it. 

Feel free to reopen if anyone disagrees.
