### ISSUE TITLE
Off by one error. Proteins are being truncated! Bad bug! occurrs browser and overview

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1267]
Note the missing leucine.
beta
>fig|1313.6068.peg.662|ERS013935_00622|   Chloramphenicol acetyltransferase (EC 2.3.1.28)   [Streptococcus pneumoniae strain spnIC28 | 1313.6068]
MNFNKIDLDNWKRKEIFNHYLNQQTTFSITTEIDISVLYRNIKQEGYKFYPAFIFLVTRV
INSNTAFRTGYNSDGELGYWDKLEPLYTIFDGVSKTFSGIWTPVKNDFKEFYDLYLSDVE
KYNGSGKLFPKTPIPENAFSLSIIPWTSFTGFNLNINNNSNYLLPIITAGKFINKGNSIY
LPLSLQVHHSVCDGYHAGLFMNSIQELSDRPNDWL

Production site:
>fig|1313.6068.peg.662|ERS013935_00622|   Chloramphenicol acetyltransferase (EC 2.3.1.28)   [Streptococcus pneumoniae strain spnIC28 | 1313.6068]
MNFNKIDLDNWKRKEIFNHYLNQQTTFSITTEIDISVLYRNIKQEGYKFYPAFIFLVTRV
INSNTAFRTGYNSDGELGYWDKLEPLYTIFDGVSKTFSGIWTPVKNDFKEFYDLYLSDVE
KYNGSGKLFPKTPIPENAFSLSIIPWTSFTGFNLNINNNSNYLLPIITAGKFINKGNSIY
LPLSLQVHHSVCDGYHAGLFMNSIQELSDRPNDWLL

**Comment by aswarren** [comment]
This is now fixed. We should have unit tests for these kinds of things.
