### ISSUE TITLE
Genome browser has a hard time getting to sequence level on beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1268]
I can look at the same gene on production and beta, but beta has a hard time getting to the sequence level.  Not so on production.
<img width="1438" alt="screen shot 2016-11-15 at 9 09 15 pm" src="https://cloud.githubusercontent.com/assets/11475316/20332141/f26d25f6-ab77-11e6-892c-35a6499073f4.png">

**Comment by aswarren** [comment]
Links are helpful. Please include links in your bugs where possible.
This is not a bug. Just tested it from home beta about 10x faster.

production: https://www.patricbrc.org/portal/portal/patric/GenomeBrowser?cType=feature&cId=PATRIC.520489.3.NZ_DS999712.CDS.412216.412713.fwd&loc=NZ_DS999712%3A412199..412731&tracks=DNA%2CPATRICGenes%2CRefSeqGenes&highlight=

beta: https://www.beta.patricbrc.org/view/Feature/RefSeq.520489.3.NZ_DS999712.misc_feature.411320.412713.fwd#view_tab=genomeBrowser
