### ISSUE TITLE
Why doesn't the PATRIC ID occur in the search results

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1269]
So I searched on fig|520489.3.peg.113 , and when I see the hits that are returned, I see a lot of locus tags, but not the PATRIC one.  Makes it a bit difficult to see which gene matches my search query.
<img width="860" alt="screen shot 2016-11-15 at 9 11 34 pm" src="https://cloud.githubusercontent.com/assets/11475316/20332223/56473058-ab78-11e6-82c5-47c044da4863.png">

**Comment by mshukla1** [comment]
This has been fixed already and deployed on alpha. 

<img width="815" alt="screen shot 2016-11-17 at 9 47 57 pm" src="https://cloud.githubusercontent.com/assets/1236463/20418030/8dcca088-ad0f-11e6-9549-8ec0c76ef2f0.png">
