### ISSUE TITLE
RefSeq locus tags go to empty RefSeq pages

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1270]
Searching for BCETI_6000640 ...the page at PATRIC where I clicked on the RefSeq link:
<img width="869" alt="screen shot 2016-11-16 at 7 28 48 am" src="https://cloud.githubusercontent.com/assets/11475316/20347311/7937801c-abce-11e6-9af7-ee4b5aa33878.png">

And this is what it takes me to....
<img width="1426" alt="screen shot 2016-11-16 at 7 27 35 am" src="https://cloud.githubusercontent.com/assets/11475316/20347322/83715026-abce-11e6-84a3-d377cfe1d1d5.png">

**Comment by chmao1** [comment]
Fixed and will be available in the next build.
