### ISSUE TITLE
Where are the prediction and the kmer identifying resistance and susceptiblity on the annotated genomes?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1271]
A user has been asking about this.  Where do we show this on the genome page?

**Comment by mshukla1** [comment]
Classifier predicted regions / kmers are displayed on the genome overview page under genomic features, and also accessible from feature table and genome browser. 

The predicted AMR phenotypes are not shown on the genome overview pages yet. 

<img width="594" alt="screen shot 2016-11-17 at 9 45 05 pm" src="https://cloud.githubusercontent.com/assets/1236463/20418002/4c8f2ba4-ad0f-11e6-83ba-99871d8625dc.png">

**Comment by mshukla1** [comment]
Both predicted AMR phenotypes and kmer regions are now available from the genome overview page.
