### ISSUE TITLE
AMR data isn't rendering

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1272]
AMR data isn't rendering on the genome landing page and this genome should have it.

![image](https://cloud.githubusercontent.com/assets/7661533/20358956/7ec965de-abf3-11e6-91a8-f762010deaed.png)

**Comment by hyoo** [comment]
oh, there is an error on the genome page. I will fix it soon.

**Comment by hyoo** [comment]
will be available on alpha soon.
