### ISSUE TITLE
Clustering on PFS heatmap-if its not working, lets remove it

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1275]
Are there any plans for this to work before the release?  It still is not working and I think we should take down the option if we're not going to fix it.  The circle just keeps rotating and never returns anything, tying up the site.
<img width="1411" alt="screen shot 2016-11-16 at 3 49 43 pm" src="https://cloud.githubusercontent.com/assets/11475316/20365273/5b83033e-ac14-11e6-8a3e-2c7988cef2fa.png">

**Comment by mshukla1** [comment]
I tried clustering several times, with 18, 36 and 61 brucella genomes and clustering worked every time in less than a minute. 

<img width="1268" alt="screen shot 2016-11-17 at 7 01 58 pm" src="https://cloud.githubusercontent.com/assets/1236463/20414625/f1d451e6-acf8-11e6-93b0-8de8b01f4340.png">

<img width="1273" alt="screen shot 2016-11-17 at 7 05 33 pm" src="https://cloud.githubusercontent.com/assets/1236463/20414626/f45420b8-acf8-11e6-8458-85b8e1118191.png">

**Comment by mshukla1** [comment]
worked with 126 brucella genomes! 

<img width="1440" alt="screen shot 2016-11-17 at 9 31 37 pm" src="https://cloud.githubusercontent.com/assets/1236463/20417749/46331952-ad0d-11e6-8ca8-8506b805f096.png">

**Comment by ARWattam** [comment]
Just tried it with 55 Brucella genomes and then with 14 Lactobacillus genomes that had 16,000+ protein families.  I'm not sure what happened the last few times I tried it (including Wednesday), but this time it worked flawlessly.  I consider this ticket closed....but I don't know how to do it so somebody else has to.

----- Original Message -----
