### ISSUE TITLE
Genomes in drop down box for PFS heatmap...how is the order determined?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1276]
On production, the genomes in the anchor option are listed in alphabetical order:
<img width="749" alt="screen shot 2016-11-16 at 3 54 22 pm" src="https://cloud.githubusercontent.com/assets/11475316/20365482/099be706-ac15-11e6-9d48-79ee2b3c9249.png">

No sure what determines the order in beta, but it should be alphabetical.  That will make it easier to find genomes in big groups.
<img width="382" alt="screen shot 2016-11-16 at 3 50 36 pm" src="https://cloud.githubusercontent.com/assets/11475316/20365514/297c9890-ac15-11e6-9bb8-e7147dcf05ac.png">

**Comment by mshukla1** [comment]
Now this is a real problem! :)

**Comment by hyoo** [comment]
will be available on 3.2.52
