### ISSUE TITLE
Protein Families at genome page not loading

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1277]
Looking at this genome:
Lactobacillus casei ATCC 334

Clicked on Protein Families, and it never loaded.
<img width="1432" alt="screen shot 2016-11-16 at 4 05 21 pm" src="https://cloud.githubusercontent.com/assets/11475316/20365859/9ebc1210-ac16-11e6-818c-8dbca5b9e687.png">
The developer code said, "Failed to load resource: the server responded with a status of 502 (Bad Gateway)"

**Comment by mshukla1** [comment]
Again, I can't reproduce the problem. 

@ARWattam, Something is not right. Several of the problems you reported, I can't reproduce them. Some of them were already fixed couple of weeks ago. We need to figure out why this is happening to [only] you!! Are you on a time travel or something?? ;)
