### ISSUE TITLE
Genomes not showing strain still a problem

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1282]
You can see that this genome ends with Dublin as the serovar.  The strain is SC50
<img width="1055" alt="screen shot 2016-11-17 at 2 03 11 pm" src="https://cloud.githubusercontent.com/assets/11475316/20403414/bee46d90-acce-11e6-8235-2160f362987c.png">

**Comment by ARWattam** [comment]
And I'm seeing A LOT of Salmonella genomes that are missing the strains, when I KNOW that they actually exist.  
<img width="1184" alt="screen shot 2016-11-17 at 2 05 54 pm" src="https://cloud.githubusercontent.com/assets/11475316/20403505/0db6b784-accf-11e6-9e1b-4730e8fb5db5.png">

**Comment by mshukla1** [comment]
#1233 
#1232 
#1219

**Comment by mshukla1** [comment]
#1233

**Comment by dmachi** [comment]
This is a bug in production (or in the data depending on how you look at it), not on the new site.  

https://www.beta.patricbrc.org/view/Taxonomy/590?keyword(Dublin)#view_tab=genomes&filter=false

The genome name column here has the strain names.

**Comment by mshukla1** [comment]
Dustin, check the labels and assignment if you are in github first before you chase in issue, 
it may save you some time. 

If I have assigned Data label and to me, it means it is not a UI problem. 

-Maulik

**Comment by mshukla1** [comment]
Updating genome names for 1635 genomes in total to include strain names. The list also includes 335 genomes reported here.
