### ISSUE TITLE
PFS: anchor shows different genomes

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1283]
I first loaded PFS for Lactobacillus. Then, I went to Brucella. When I try to use anchor in the heatmap, it still shows lactobacillus genomes from previous session. 

<img width="1259" alt="screen shot 2016-11-17 at 6 48 06 pm" src="https://cloud.githubusercontent.com/assets/1236463/20414396/cc3158f4-acf7-11e6-8ba9-65c4d988cf11.png">

**Comment by hyoo** [comment]
ah.. yes, this is a bug. the panel is built first time and did not reload. will fix it soon.

**Comment by hyoo** [comment]
will be available on 3.2.52
