### ISSUE TITLE
classifier predicted region does not display antibiotic or rank

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1284]
This no informative value if the antibiotic and rank are not displayed.  Both should exist in the gto file.

![image](https://cloud.githubusercontent.com/assets/7661533/20433220/56abcf3a-ad68-11e6-99b2-b1b147dae359.png)

**Comment by mshukla1** [comment]
do we have those in the genome object?

**Comment by dmachi** [comment]
This is the same feature summary we use everywhere (there is a standard formatter for each data type).  So if we have what you are asking for as part of this data type (genome_feature), then we can add it pretty easily.  I don’t know if that is the case or not.

**Comment by jimdavis1** [comment]
They are in the GTO.

**Comment by hyoo** [comment]
This requires web & data api deployment. Code changes are in repo. This will be deployed on production before the July release.

**Comment by mshukla1** [comment]
Harry, this is important for Jim and I like to review the UI functionality with him and make sure it meets his expectations before we close the ticket.

-Maulik

**Comment by hyoo** [comment]
Genome level

https://alpha.patricbrc.org/view/Genome/1313.15743#view_tab=features&filter=and(eq(feature_type,%22classifier_predicted_region%22),or(eq(annotation,%22PATRIC%22)))

![image](https://user-images.githubusercontent.com/1236467/43011136-362925b6-8c08-11e8-9324-ed0b32d3eba0.png)

Feature level

https://alpha.patricbrc.org/view/Feature/PATRIC.1313.15743.CLVQ01000001.classifier_predicted_region.4235.4251.fwd#view_tab=overview

![image](https://user-images.githubusercontent.com/1236467/43011177-502294b6-8c08-11e8-90a1-a64edae50688.png)

**Comment by rkenyon** [comment]
I was able to see these as well.  Used Harry's examples though because I couldn't find genomes or features with values for this.
