### ISSUE TITLE
Error output not appearing in beta site

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1285]
for the attached job view for 6159eb0f-3c17-4d0f-ab0e-54aabb2f5fd9 the error output is empty in beta. It is valid in production site. I also can no longer double-click on the red dot to see the larger error dialog window like we could with production.

![screen shot 2016-11-18 at 10 23 35 am](https://cloud.githubusercontent.com/assets/2152226/20437306/16dd03a4-ad79-11e6-94eb-6896afe12da0.png)

**Comment by hyoo** [comment]
I believe this has been fixed and deployed. #1386
