### ISSUE TITLE
All the genomes not appearing in the transcriptome filter

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1287]
I can see that the Erdman strain is in the list of conditions, but when I look at the strain filter I am not able to see it.  The only ones I can see are M. smegmatis Mc21511, M. tuberculosis H37Rv and CDC 1511

https://www.beta.patricbrc.org/view/TranscriptomicsExperiment/?in(eid,(213140,231764,248682,264531,267161,267915,268478,305749,322785,326845,332843,333076,333319,341836,342459,343250,343910,348636,351269,354496,356112,358083,1070015))

<img width="924" alt="screen shot 2016-11-18 at 3 02 40 pm" src="https://cloud.githubusercontent.com/assets/11475316/20444767/64ade2d4-ada0-11e6-8956-a39b256ecb89.png">

**Comment by hyoo** [comment]
Erdman strains are coming from experiment comparison meta data, which may or may not related to the actual genes. that genome list is populated from the expression value.

**Comment by mshukla1** [comment]
Erdman is the strain used in the experiment here. However, data is mapped to the genomes based on the definition of the corresponding microarray platform. In this case, Erdman is not one of the platform strains, hence data is not mapped to Erdman genome and it is not shown in the dropdown below. 

This may be confusing, but it is one of the artifacts of dealing with the microarray data. We have discussed this while developing transcriptomics functionality. 

-Maulik
