### ISSUE TITLE
data api is not accessible 

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#129]
For example, from a feature page,

https://www.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=RefSeq.83332.12.NC_000962.CDS.2726806.2727339.fwd

protein interactions are not shown because the following query was failed.

http://polyomic.patricbrc.org/pig/?descendants((2,33208))&between()&keyword(PATRIC.83332.12.NC_000962.CDS.2726806.2727339.fwd)&eq(is_hpi,Y)&facet((sort,+rownum))&limit(0,0)

**Comment by dmachi** [comment]
I've proxied the old polyomic api in on alpha at /oldapi/ until the new data api is completed and usable for this. Once PIG is updated and tested, I can add the same proxying in for production

**Comment by hyoo** [comment]
This works now at 
https://www.alpha.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=RefSeq.83332.12.NC_000962.CDS.2726806.2727339.fwd

Please setup on the beta/prod so that this issue can be addressed in next release.
