### ISSUE TITLE
feature page with multiple badness

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1295]
https://www.beta.patricbrc.org/view/Feature/RefSeq.9823.5.NC_010448.mRNA.58158519.58185391.rev

it has a number of issues; bare "loading...", overwrite on identifier, no sequence available

**Comment by hyoo** [comment]
I added "Note: There is no corresponding PATRIC feature."

**Comment by hyoo** [comment]
https://www.patricbrc.org/view/Feature/RefSeq.9823.5.NC_010448.mRNA.58158519.58185391.rev

- handle long feature id
- handle Gene viewer when the data is not available. currently it says "Loading..." and do nothing.

**Comment by hyoo** [comment]
- removed loading message when there is no record to display
- added overflow css on DataItemHeader div

![image](https://cloud.githubusercontent.com/assets/1236467/25499260/71ff07e6-2b50-11e7-94ba-36c0bef3452d.png)
