### ISSUE TITLE
gene landing page is atypical

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1296]
Note the "Add to Group" link in the top right.  Shouldn't this be on a green bar like all the other pages?   The green bar would be a waste of space, but it might be nice to make the button have a green background just for consistency. 

![image](https://cloud.githubusercontent.com/assets/7661533/20531703/28d1a64c-b09d-11e6-858b-c7a239655747.png)

**Comment by dmachi** [comment]
The green bar is for actions that apply to a selection.  On this page there is no active selection, so this is more like the buttons above a table that apply to the whole table.  So IMHO this is the correct icon.
