### ISSUE TITLE
Unable to add genome to an existing group

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1297]
I've been trying to add some new genomes to an existing group, and a pop-up comes up that says that 0 genomes got added.
<img width="1440" alt="screen shot 2016-11-23 at 9 25 32 pm" src="https://cloud.githubusercontent.com/assets/11475316/20584718/8585240a-b1c3-11e6-8c28-8bde4cd68895.png">

I've tried several times, but I can't seem to add anything

**Comment by hyoo** [comment]
Make sure that genome is not in the group already

**Comment by ARWattam** [comment]
Its not part of the original group.  

Also, it looks like its only happening from the genome landing page.  When I do it from a list in TAxonomy, it adds just fine.

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/28538071-8f17e5fc-7072-11e7-8e72-0a9282ac3597.png)

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/28538133-c877ca1a-7072-11e7-8f7a-021042219101.png)

I cannot reproduce this problem.

The only way i can do is adding the same genome in second time.

![image](https://user-images.githubusercontent.com/1236467/28538184-fc8652ea-7072-11e7-8816-051e31b12516.png)

Whenever i tried with new genome, it worked.

**Comment by hyoo** [comment]
please reopen if you can reproduce this problem.
