### ISSUE TITLE
Cannot remove genome from created group on beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1298]
I have a group, go to group view, go to genomes and select the genome I want to remove, but that is not an option on the mystical green band.
<img width="1166" alt="screen shot 2016-11-24 at 9 19 16 am" src="https://cloud.githubusercontent.com/assets/11475316/20601561/403257f6-b227-11e6-81df-43d820e663cb.png">

https://www.beta.patricbrc.org/view/GenomeGroup/ARWattam@patricbrc.org/home/Genome%20Groups/Boyle%20Brucella#view_tab=genomes

I will have to do it in production...sigh...sad.....

**Comment by hyoo** [comment]
this is already done in production.
