### ISSUE TITLE
Jobs page doesnt update when the job status updates

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1300]
Notice the first job is displayed as queued, but the jobs thingy in the bottom right shows that it's in progress:

![image](https://cloud.githubusercontent.com/assets/7661533/20675235/36854600-b551-11e6-9efa-caddcdd0f7c3.png)

So then I hit refresh and I get this. I'm in safari.  So then I clicked on the jobs thingy in the bottom right, but it's no longer a link when the page is blank like this.  If I click a tab, and then click the jobs thing, I can see the jobs page again and this time it's refreshed.

![image](https://cloud.githubusercontent.com/assets/7661533/20675260/4b7caf30-b551-11e6-8d2a-587057930728.png)

**Comment by dmachi** [comment]
Duplicate and Fixed.
