### ISSUE TITLE
Annotation service download formats

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1301]
I am really surprised that nobody has asked us for a fasta file of just RNAs or protein encoding genes.  Neither is available for download.  Somebody who can't program, won't be able to get this  on their own.  BTW, I think RAST offers these.

![image](https://cloud.githubusercontent.com/assets/7661533/20675638/a0cf2660-b552-11e6-9210-eac249e5ab44.png)

**Comment by dmachi** [comment]
These are just the files in your workspace that the annotation service generates.  It seems like a waste of space to generate every possible type of file that a user may want to have in the future given that the purpose of these files if for importing into the database.  I think you could get to this by going to the features for this genome (Features tab of the Genome View), filtering to what you want, select all, then download as FASTA.  I could be wrong, but thats how I’d go about it.

**Comment by mshukla1** [comment]
I agree, once the genomes are indexed there are other ways of downloading the subset of features and corresponding sequences using search and filter, if user wishes.
