### ISSUE TITLE
Download links in Annotation service don't work in safari

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1302]
I'm trying to download my genome and can't do it. I had to quit safari and use firefox.

![image](https://cloud.githubusercontent.com/assets/7661533/20675727/e8a76614-b552-11e6-8d0f-709c3dc41a33.png)

**Comment by hyoo** [comment]
I noticed this one. from at some point, click does not work on chrome as well. firefox works, though.

**Comment by hyoo** [comment]
i think #1159 is related this issue. 
@nconrad would you take a look?

**Comment by nconrad** [comment]
That's right. I've reported this before, but I don't think there was a detailed plan to get it fixed.   see https://github.com/PATRIC3/patric3_website/issues/1159

**Comment by dmachi** [comment]
These download links are getting replaced in the JobViewer modifications that Zane is working on.  I would let it go for now until that is completed.

**Comment by zreyn** [comment]
Closing this in favor of the related issue:
https://github.com/PATRIC3/patric3_website/issues/1159
