### ISSUE TITLE
File names following download from annotation service

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1303]
I just downloaded my genome and opened it with text wrangler.  Somehow it got called: Escherichia-5.  Why can't we call it what it is actually named on the website?  I'm doing an analysis of Sakai vs EDL933, now I have a file called Escherichia-5 and a file called Escherichia(1).  I have no idea why they got the names they were given.

![image](https://cloud.githubusercontent.com/assets/7661533/20675820/4727ab68-b553-11e6-8423-635aa8ee6f71.png)

![image](https://cloud.githubusercontent.com/assets/7661533/20675813/390222c0-b553-11e6-8c66-ce9795a4a067.png)

**Comment by mshukla1** [comment]
Are you referring to the name of the downloaded file? It may very depending on where you 
downloaded it from. 

Did you download it from workspace or genome or taxon level taxon feature list? 

Which file format did you download?….it looks like ffn from the feature table!

**Comment by jimdavis1** [comment]
I downloaded the contig fasta file from the job directory in my workspace.  By the way, if you download the excel file, it doesn't even have a .xls extension.

**Comment by jimdavis1** [comment]
Here is an example, I click on the .xls file and it shows up in my downloads as Escherichia(2) and klobbers the previous thing called Escherichia(2). No xls file extension. These should be named as they appear on the website.


![image](https://cloud.githubusercontent.com/assets/7661533/20677290/36a13a70-b558-11e6-930e-55a5fd18e479.png)

**Comment by mshukla1** [comment]
This issue has been resolved. I downloaded files and they were saved with correct file names and extensions.
