### ISSUE TITLE
Search for  box in BLAST...are we adding anything else?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1304]
We have this option on blast, but it only as one selection.  Are we adding anything else?  If not, I would get rid of it.
<img width="756" alt="screen shot 2016-11-28 at 2 15 26 pm" src="https://cloud.githubusercontent.com/assets/11475316/20682261/4b7f421c-b575-11e6-9ff3-37ae71c8d1f9.png">

**Comment by hyoo** [comment]
based upon program & database combination, it shows available options. it could have "contigs" in this one.
