### ISSUE TITLE
BLAST results sometimes linger when editing/resubmitting new job

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1305]
BLAST has been behaving well, but I noticed that the former BLAST results are hanging at the bottom of the page after I hit the edit/resubmit button.

https://www.beta.patricbrc.org/app/BLAST

<img width="1427" alt="screen shot 2016-11-28 at 2 24 57 pm" src="https://cloud.githubusercontent.com/assets/11475316/20682597/9db75ca8-b576-11e6-848b-ca082db2a993.png">

**Comment by hyoo** [comment]
I intentionally left it because user may want to open the form and review their parameters while they are viewing the BLAST results.

**Comment by hyoo** [comment]
please reopen if you think otherwise.
