### ISSUE TITLE
BLAST against genome contigs not returning results

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1307]
Even when I choose a single genome, nothing happens.  I used the following sequence and chose BLAST against genome contigs, and I chose Brucella melitensis biovar abortus 2308.  No results ever returned.  When I do BLASTP with the same sequence (amino acids, though), that returns results.
>fig|511145.12.peg.3032|b2938|VBIEscCol129921_3032|   Biosynthetic arginine decarboxylase (EC 4.1.1.19)   [Escherichia coli str. K-12 substr. MG1655 | 511145.12]
atgagctcccaggaagccagcaagatgctgcgtacttacaatattgcctggtggggcaat
aactactatgacgttaacgagctgggccacattagcgtgtgcccggacccggacgtcccg
gaagctcgcgtcgatctcgcgcagttagtgaaaactcgtgaagcacagggccagcgtctg
cctgcactgttctgtttcccacagatcctgcagcaccgtttgcgttccattaacgccgcg
ttcaaacgtgcgagggaatcctacggctataacggcgattacttccttgtttatccgatc
aaagttaaccagcaccgccgcgtgattgagtccctgattcattcgggcgaaccgctgggt
ctggaagccggttccaaagccgagttgatggcagtactggcacatgctggcatgacccgt
agcgtcatcgtctgcaacggttataaagaccgcgaatatatccgcctggcattaattggc
gagaagatggggcacaaggtctatctggtcattgagaagatgtcagaaatcgccattgtg
ctggatgaagcagaacgtctgaatgtcgttcctcgtctgggcgtgcgtgcacgtctggct
tcgcagggttcgggtaaatggcagtcctccggcggggaaaaatcgaagttcggcctggct
gcgactcaggtactgcaactggttgaaaccctgcgtgaagccgggcgtctcgacagcctg
caactactgcacttccacctcggttcgcagatggcgaatattcgcgatatcgcgacaggc
gttcgtgaatccgcgcgtttctatgtggaactgcacaagctgggcgtcaatattcagtgc
ttcgacgtcggcggcggtctgggcgtggattatgaaggtactcgttcgcagtccgactgt
tcggtgaactacggcctcaatgaatacgccaacaacattatctgggcgattggcgatgcg
tgtgaagaaaacggtctgccgcatccgacggtaatcaccgaatcgggtcgtgcggtgact
gcgcatcacaccgtgctggtgtctaatatcatcggcgtggaacgtaacgaatacacggtg
ccgaccgcgcctgcagaagatgcgccgcgcgcgctgcaaagcatgtgggaaacctggcag
gagatgcacgaaccgggaactcgccgttctctgcgtgaatggttacacgacagtcagatg
gatctgcacgacattcatatcggctactcttccggcatctttagcctgcaagaacgtgca
tgggctgagcagctttatttgagcatgtgccatgaagtgcaaaagcagctggatccgcaa
aaccgtgctcatcgtccgattatcgacgagctgcaggaacgtatggcggacaaaatgtac
gtcaacttctcgctgttccagtcgatgccggacgcatgggggatcgaccagttgttcccg
gttctgccgctggaagggctggatcaagtgccggaacgtcgcgctgtgctgctggatatt
acctgtgactctgacggtgctatcgaccactatattgatggtgacggtattgccacgaca
atgccaatgccggagtacgatccagagaatccgccgatgctcggtttctttatggtcggc
gcatatcaggagatcctcggcaacatgcacaacctgttcggtgataccgaagcggttgac
gtgttcgtcttccctgacggtagcgtagaagtagaactgtctgacgaaggcgataccgtg
gcggacatgctgcaatatgtacagctcgatccgaaaacgctgttaacccagttccgcgat
caagtgaagaaaaccgatcttgatgctgaactgcaacaacagttccttgaagagttcgag
gcaggtttgtacggttatacttatcttgaagatgagtaa

<img width="682" alt="screen shot 2016-11-29 at 9 01 31 am" src="https://cloud.githubusercontent.com/assets/11475316/20712575/9b3b1004-b612-11e6-93f3-c9d9ca7f3077.png">

**Comment by ARWattam** [comment]
Here are the results when I do BLASTP with the amino acid version of the same sequence.
<img width="1144" alt="screen shot 2016-11-29 at 9 03 01 am" src="https://cloud.githubusercontent.com/assets/11475316/20712584/bafdfc9e-b612-11e6-8a00-d0b7c52680b8.png">

**Comment by mshukla1** [comment]
I tried
- BLASTN against reference genomes, it worked. 
- BLASTN against E coli  MG1655, it worked. 
- tblastx against B 2308, it worked. 

=> BLASTN against B 2308 didn't return any results, because there are no significant hits at DNA level.
