### ISSUE TITLE
BLAST result -  MSA in action bar

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1310]
The current blast result table only provide the subject list, not the original query sequence. It would be more useful if the MSA includes the original query sequence, so that the subjects can be compared to the query sequence.

**Comment by mshukla1** [comment]
we show pair-wise blast alignments of the query and subject, list NCBI blast. 

The selection and actions from the BLAST results are mostly done using the same mechanisms as any other feature table on the site. Given that the selection tools and MSA pass feature ids and pull related data from the database, I don't think we can support adding query sequence to MSA without requiring major changes. 

-Maulik

**Comment by hyoo** [comment]
The query sequence can be either a PATRIC feature or random sequence. So, I don't think we can support this functionality. Please repoen if you think otherwise.
