### ISSUE TITLE
Protein Family Sorter and Comparative Pathway Services help have wrong help text

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1311]
Looks like it was stubbed from the Assembly Service, but not updated.

https://www.beta.patricbrc.org/app/ComparativePathway
https://www.beta.patricbrc.org/app/ProteinFamily

![screen shot 2016-11-29 at 11 43 13 am](https://cloud.githubusercontent.com/assets/3188570/20719180/2ce2abe6-b629-11e6-9fd9-5b0b5663c84b.png)

**Comment by hyoo** [comment]
I cleaned up old text and added some placeholder. 

please add more info as needed.

https://github.com/PATRIC3/p3_web/blob/master/public/js/p3/widget/app/help/ComparativePathwayHelp.html

https://github.com/PATRIC3/p3_web/blob/master/public/js/p3/widget/app/help/ProteinFamilyHelp.html

**Comment by hyoo** [comment]
I have update protein family help doc, and removed unneccesary icons from comparative pathway
