### ISSUE TITLE
Check All filter on Transcriptomics gene table view "uncheck" feature does not work

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1312]
You can click the top checkbox to select all, but clicking it again (to uncheck all) does nothing.

https://www.beta.patricbrc.org/view/TranscriptomicsExperiment/?eq(eid,(233094))

![screen shot 2016-11-29 at 1 18 43 pm](https://cloud.githubusercontent.com/assets/3188570/20722905/649843ea-b636-11e6-9abd-58c30db38256.png)

**Comment by hyoo** [comment]
you cannot unselect all. this is not a selection of rows (comparisons), but selecting different condition of comparisons, ie up-regulated, down-regulated, or both.
