### ISSUE TITLE
Text box filter not working on Protein Family Sorter

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1316]
I am comparing three groups and one private genome, selected PLFams, and there are 16650 PLFams.  I put iron in the text box and click filter...the same 16650.
<img width="1419" alt="screen shot 2016-11-29 at 2 18 07 pm" src="https://cloud.githubusercontent.com/assets/11475316/20725176/f919fce0-b63e-11e6-959f-f351b70e94aa.png">

**Comment by mshukla1** [comment]
Keyword search seems to be working on alpha. Please try again and reopen the ticket if you still see the problem.
