### ISSUE TITLE
Proteome Comparison result -  the numbers for list of genomes are not displayed.

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1317]
The ordered numbers for the list of tracks (List of tracks, from outside to inside:) are not displayed in beta.

This is from beta
![image](https://cloud.githubusercontent.com/assets/6361802/20725106/d029007e-b63e-11e6-8aef-311dc7bb794d.png)

This is from the current production
![image](https://cloud.githubusercontent.com/assets/6361802/20725202/13f08106-b63f-11e6-9337-f7673c45aa33.png)

**Comment by chmao1** [comment]
@levinas Fangfang, could you check the script that generates the html file from the server side?

**Comment by levinas** [comment]
I guess this is a css problem. I'm using the standard HTML ol tag:
http://www.w3schools.com/tags/att_ol_type.asp

```
</br>List of tracks, from outside to inside:</br>
<ol type="1">
  <li>genome 1</li>
  <li>genome 2</li>
  ...
</ol>
```

**Comment by chmao1** [comment]
Fixed the css problem and will be available in the next build.

**Comment by chmao1** [comment]
Tested and passed.
