### ISSUE TITLE
What if we added the name of the genome group as one of the columns in the PFS filter?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1319]
That way, people would be able to see which genomes came from specific groups.  If it wasn't part of a group, it would be blank.  I think that this would be a significant improvement to the tool

**Comment by hyoo** [comment]
I understand the need. However, the current structure retrieves all the gnome ids from the genome groups and pass the "list of genome ids" to the protein family widget. That's how it could work with taxonomy, genome list, and genome pages. 

So, the genome ID and genome group association info will be lost before it hits the filter grid, which is the reason we could not implement at the previous request. This requires architectural consideration and I don't think we can deliver it before the Nov release.

**Comment by hyoo** [comment]
This is a duplicate.
#1030
