### ISSUE TITLE
Feature View: feature view page remains at loading status on Firefox

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1320]
Here is an example (using fid id): https://www.beta.patricbrc.org/view/Feature/fig|1457189.3.peg.432
On Firebox, the page never loaded the detail.
![image](https://cloud.githubusercontent.com/assets/6361802/20725476/f0bcaf24-b63f-11e6-81cf-434505939d14.png)

This is fine using Chrome.

**Comment by hyoo** [comment]
this link has to be url encoded.

https://www.beta.patricbrc.org/view/Feature/fig%7C1457189.3.peg.432

**Comment by chmao1** [comment]
The link is from the proteome comparison result page. I'll close this one and issue a new one for proteome comparison bug.
