### ISSUE TITLE
BLAST result -  did not return result when using a NT sequence and plasmid contigs proteins datasbase

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1321]
After a couple of hours, still no results
![image](https://cloud.githubusercontent.com/assets/6361802/20725569/480d70c4-b640-11e6-8011-69e4f5718461.png)

**Comment by hyoo** [comment]
we don't have plasmid db yet.

**Comment by chmao1** [comment]
@hyoo Any other databases are not available?
I tested several other databases, and the results have not yet been returned. Not sure which ones were not available.

**Comment by hyoo** [comment]
plasmid and transcriptomics are not available yet.

**Comment by mshukla1** [comment]
plasmid.fna database has been added. this is working now on beta.
