### ISSUE TITLE
Anchoring a genome appears to be failing on beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1322]
As in the workshops, comparing 3 groups and one private genome.  Load heatmap, select anchor a genome.  Anchoring did not work, and I got a pop up message that a plugin (shockwave flash) is not responding.
<img width="1440" alt="screen shot 2016-11-29 at 2 32 57 pm" src="https://cloud.githubusercontent.com/assets/11475316/20725777/f41f2ace-b640-11e6-9a67-e8fab025b057.png">

**Comment by hyoo** [comment]
flash player in the browser crashed. not related to anchoring function.
