### ISSUE TITLE
Proteome Comparison: links for the features in the circular graph

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1323]
The links for the features in circular graph do not work on firefox. For example:
https://www.beta.patricbrc.org/view/Feature/fig|1457189.3.peg.432
The link has to be url encoded: https://www.beta.patricbrc.org/view/Feature/fig%7C1457189.3.peg.432

Please make the correction on the server side for generating the html file.

**Comment by levinas** [comment]
Fixed in PR:
https://github.com/TheSEED/app_service/pull/58

**Comment by hyoo** [comment]
I am flagging "fixed" per Fangfang's comment. @maovt please verify and close it

**Comment by levinas** [comment]
It's not deployed yet until Bob @olsonanl is back.

**Comment by olsonanl** [comment]
This is merged & deployed now.

________________________________

**Comment by chmao1** [comment]
Tested and found that a client side fix was still required to handle the url change (for fig id) in Firefox. I fixed the client side code and made a pull request. @hyoo please include this change in the next beta build.

**Comment by levinas** [comment]
Thanks Bob.

**Comment by chmao1** [comment]
Tested on beta and it works now.
