### ISSUE TITLE
BLAST: Specialty Gene BLAST results

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1325]
specialty gene blast shows empty cells,

![image](https://cloud.githubusercontent.com/assets/1236467/20727900/dcd54f10-b640-11e6-9bd6-b0a1c85830bb.png)

because it does not return feature_id. need to address before the release.

![image](https://cloud.githubusercontent.com/assets/1236467/20727905/e773f156-b640-11e6-9c8b-d32765251a45.png)

**Comment by mshukla1** [comment]
@hyoo Please let me know if this can be fixed in short time. 

If it can not be fixed quickly, I recommend that we hide specialty gene blast from the options for now. We can add them back later after the November release. 

-Maulik

**Comment by hyoo** [comment]
this is fixed and available on beta.
