### ISSUE TITLE
A list of features...why doesn't mystical green band show Pathway?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1326]
This has me scratching my head.  Shouldn't Pathway be an option when all these features are selected?  I did the usual workflow for the tutorial on the new E. coli, selected a bunch of genes, got the features and selected them all.  Pathway should be one of the options, right?  Why is this ephemeral?
<img width="1167" alt="screen shot 2016-11-29 at 4 24 04 pm" src="https://cloud.githubusercontent.com/assets/11475316/20729535/6b4483a6-b650-11e6-8576-d9bf34185355.png">

**Comment by hyoo** [comment]
Pathway enrichment icon is available but limited to 200 features. We can increase the limit if necessary. What would be the realistic number for type of analysis?

**Comment by hyoo** [comment]
I don't know why, but it seems like I misunderstood your issue. Please give a number so that I can increase the limit.

**Comment by ARWattam** [comment]
What do we have to consider...if we said 1000 would it be too slow?  2000?
I think that it is a trade-off between speed of loading and max number that
can be shown.

**Comment by olsonanl** [comment]
What is the complexity of this computation?

**Comment by hyoo** [comment]
it's just a couple of sub queries and computation is not complex. I tested with 5000 features and worked well. Is it enough or more is better?

**Comment by ARWattam** [comment]
Lets go with 5000 and see if we get reports from people wanting more.  How
does that sound?

Rebecca

**Comment by hyoo** [comment]
Sounds good. Will deploy with April release.
