### ISSUE TITLE
job list disappears when I refresh the page 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1327]
If I go to the job list from the top navigation bar, no jobs are displayed. 

When I click on the notification area at the bottom, the job list loads fine. 

However, if I refresh the page, jobs disappear again. 

Now if I click on the job summary at the bottom, it doesn't sho the jobs. 

The only way I would make it work again is to go to some other page, home page, and then click on the job number at the bottom again. 

-Maulik

**Comment by mshukla1** [comment]
@dmachi, Neal is not available this week, can you look into this?

**Comment by dmachi** [comment]
This has existed for at least 2 months this way. Duplicate of #1014.  Will take a look

**Comment by dmachi** [comment]
Fixed. Will be on alpha soon.

**Comment by hyoo** [comment]
verified.
