### ISSUE TITLE
Uploading failed of contigs for Benchmark Contigs in Assembly

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1329]
I've taking Assembly through its steps, and wanted to test using the Benchmark contigs.  Downloaded a .fna file from PATRIC, and tried uploading.  It never worked.
<img width="688" alt="screen shot 2016-11-30 at 2 32 48 pm" src="https://cloud.githubusercontent.com/assets/11475316/20768029/6620caa0-b70a-11e6-8a5d-7d362d34e52a.png">

**Comment by mshukla1** [comment]
Looks like this is very old ticket and the issue has been fixed. 

I tried to upload and use benchmark contigs myself and it worked.
