### ISSUE TITLE
The 'Update Profile' button does not work

### ISSUE THREAD

**Issue by sebhtml** [PATRIC3/patric3_website#133]
Hello,

Steps
====

1. Go to http://patricbrc.org/
2. Log in
3. Click "My Account"
4. Fill the text fields
5. Clock the 'Update Profile' button

Expected result
=============

I expected my profile to be updated.

Actual result
==========

Nothing is happening.

Troubleshooting
=============

The console shows:

Submit Vals:  Object {first_name: "Sebastien", last_name: "Boisvert", email: "boisvert@anl.gov", affiliation: "foo", organisms: "bar"…}affiliation: "foo"email: "boisvert@anl.gov"first_name: "Sebastien"id: "sebhtml"interests: "yes"last_name: "Boisvert"organisms: "bar"__proto__: Object 

The source code file is:

/js/release/p3/widget/UserProfileEditor.js

There is a return statement at line 38 which explains the issue.

**Comment by dmachi** [comment]
Thanks Sebastien.  Debugging block made it through.  I'll get it fixed.

**Comment by sebhtml** [comment]
What is a "Debugging block" ?

**Comment by dmachi** [comment]
I just meant while I was working on it, i had put that return so I could see the console message without actually sending the post.

**Comment by sebhtml** [comment]
got it.

**Comment by dmachi** [comment]
Fixed in beta, will be in next release to production

**Comment by sebhtml** [comment]
Awesome !
