### ISSUE TITLE
Unable to get to genome landing page from job details-annotation

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1331]
I annotated a genome.  Went to Jobs, clicked on View icon, went to landing page for the annotation job.  Clicked on the View icon (the eye) and...nothing happened.  Here's the url
https://www.beta.patricbrc.org/workspace/ARWattam@patricbrc.org/home/Annnotations/Escherichia%20coli%20MRSN_test_kiki

I opened the developer view and took a screenshot.  Here's what it said once it started returning errors:

Q:  ?eq(taxon_id,562)&select(taxon_id,taxon_name,lineage_names)&sort(+taxon_id)
2https://p3.theseed.org/services/Workspace Failed to load resource: the server responded with a status of 500 (Internal Server Error)
https://p3.theseed.org/services/app_service Failed to load resource: net::ERR_INTERNET_DISCONNECTED
JobsGrid.js:221 STARTUP REFRESH
JobsGrid.js:199 dgrid-select:  Event
JobManager.js:130 rownum:  257c0811-9c43-4101-9ebf-39b240798c1b
JobManager.js:131 Row:  Object
JobManager.js:137 selection:  Array[1]
JobManager.js:97 SEL:  Object
GenomeAnnotation.js:45 job result viewer data:  Object
GenomeAnnotation.js:52 got objects:  Array[20]
GenomeAnnotation.js:31 GENOME OBJECT:  Object
GenomeAnnotation.js:33 Id:  undefined
GenomeAnnotation.js:41 Uncaught Error: Missing ID(…)
GenomeAnnotation.js:31 GENOME OBJECT:  Object
GenomeAnnotation.js:33 Id:  undefined
GenomeAnnotation.js:41 Uncaught Error: Missing ID(…)
GenomeAnnotation.js:31 GENOME OBJECT:  Object
GenomeAnnotation.js:33 Id:  undefined
GenomeAnnotation.js:41 Uncaught Error: Missing ID(…)
GenomeAnnotation.js:31 GENOME OBJECT:  Object
GenomeAnnotation.js:33 Id:  undefined
GenomeAnnotation.js:41 Uncaught Error: Missing ID(…)
GenomeAnnotation.js:31 GENOME OBJECT:  Object
GenomeAnnotation.js:33 Id:  undefined
GenomeAnnotation.js:41 Uncaught Error: Missing ID(…)

<img width="1440" alt="screen shot 2016-11-30 at 4 33 37 pm" src="https://cloud.githubusercontent.com/assets/11475316/20772344/1e7d5716-b71b-11e6-81f1-73eb4cc03d6c.png">

**Comment by hyoo** [comment]
#1334

**Comment by hyoo** [comment]
i am closing since this is a duplicate
