### ISSUE TITLE
None of the links from icons at top of Annotation result page are working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1334]
When trying to examine results from my private genome annotation job, I clicked on the Blue eye, the CDC and the Browser icon.  None of them went anywherel
<img width="1089" alt="screen shot 2016-12-01 at 9 02 56 am" src="https://cloud.githubusercontent.com/assets/11475316/20796716/755a3902-b7a5-11e6-915c-977c1ebdd8ff.png">

**Comment by mshukla1** [comment]
I see that the genome got indexed in the database at 2016-11-30T20:50:34.985Z, few hours after the job finishes. So the link should have worked if you tried them Yesterday. 

Can you try again and tell if you still see the problem?
