### ISSUE TITLE
Weird behavior on Jobs page...reloading says no results available.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1335]
This will have three screenshots.  As reported earlier, when I first go to the page, I see that some of my jobs that are completed are listed in progress (I know the assembly jobs in the screenshot  are completed because I submitted them for annotation):
<img width="1142" alt="screen shot 2016-12-01 at 9 13 24 am" src="https://cloud.githubusercontent.com/assets/11475316/20796926/abe8ef80-b7a6-11e6-9c3d-6049106c5f4a.png">

When I reload the page, it says I have no results:
<img width="1250" alt="screen shot 2016-12-01 at 9 12 58 am" src="https://cloud.githubusercontent.com/assets/11475316/20796935/b9345ea4-b7a6-11e6-81c3-bd22800c4e07.png">

But if I click on the homepage, and then go to the jobs page, I see an accurate portrayal of the progress of my jobs:
<img width="1138" alt="screen shot 2016-12-01 at 9 13 11 am" src="https://cloud.githubusercontent.com/assets/11475316/20796965/d14d15e4-b7a6-11e6-8a5e-8fe4d3b021cc.png">

**Comment by dmachi** [comment]
Duplicate
