### ISSUE TITLE
BLAST - failed when using a nucleotide sequence and tblastx

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1336]
Couldn't get any tblastx results back. Got the following error:
"We were not able to complete your BLAST request. Please let us know with detail message below."

![image](https://cloud.githubusercontent.com/assets/6361802/20799054/05f077ac-b7af-11e6-8380-091ea5dbc759.png)

**Comment by chmao1** [comment]
This happened when "Reference or Representative Genomes (ffn)" or  "Reference or Representative Genome features (fna)" was used.

**Comment by chmao1** [comment]
Here is the nt sequence used:
>fig|83332.12.peg.3|Rv0003|VBIMycTub87468_0003| DNA recombination and repair protein RecF [Mycobacterium tuberculosis H37Rv | 83332.12] gtgtacgtccgtcatttggggctgcgtgacttccggtcctgggcatgtgtagatctggaa ttgcatccagggcggacggtttttgttgggcctaacggttatggtaagacgaatcttatt gaggcactgtggtattcgacgacgttaggttcgcaccgcgttagcgccgatttgccgttg atccgggtaggtaccgatcgtgcggtgatctccacgatcgtggtgaacgacggtagagaa tgtgccgtcgacctcgagatcgccacggggcgagtcaacaaagcgcgattgaatcgatca tcggtccgaagtacacgtgatgtggtcggagtgcttcgagctgtgttgtttgcccctgag gatctggggttggttcgtggggatcccgctgaccggcggcgctatctggatgatctggcg atcgtgcgtaggcctgcgatcgctgcggtacgagccgaatatgagagggtgttgcgccag cggacggcgttattgaagtccgtacctggagcacggtatcggggtgaccggggtgtgttt gacactcttgaggtatgggacagtcgtttggcggagcacggggctgaactggtggccgcc cgcatcgatttggtcaaccagttggcaccggaagtgaagaaggcataccagctgttggcg ccggaatcgcgatcggcgtctatcggttatcgggccagcatggatgtaaccggtcccagc gagcagtcagatatcgatcggcaattgttagcagctcggctgttggcggcgctggcggcc cgtcgggatgccgaactcgagcgtggggtttgtctagttggtccgcaccgtgacgaccta atactgcgactaggcgatcaacccgcgaaaggatttgctagccatggggaggcgtggtcg ttggcggtggcactgcggttggcggcctatcaactgttacgcgttgatggtggtgagccg gtgttgttgctcgacgacgtgttcgccgaactggatgtcatgcgccgtcgagcgttggcg acggcggccgagtccgccgaacaggtgttggtgactgccgcggtgctcgaggatattccc gccggctgggacgccaggcgggtgcacatcgatgtgcgtgccgatgacaccggatcgatg
tcggtggttctgccatga

**Comment by chmao1** [comment]
Here is the error from inspect:
![image](https://cloud.githubusercontent.com/assets/6361802/20800773/a1b80b46-b7b4-11e6-8d91-e404a33cca33.png)

**Comment by hyoo** [comment]
this was timed out. I am displaying message and now hiding result grid so that users can see the message clearly.
