### ISSUE TITLE
BLAST - failed when using an aa sequence, blastp and specialty gene reference proteins

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1337]
The blast result didn't returned after long time (hours) when using an aa sequence, blastp and specialty gene reference proteins.

**Comment by chmao1** [comment]
This is the sequence used:

>fig|83332.12.peg.3|Rv0003|VBIMycTub87468_0003|   DNA recombination and repair protein RecF   [Mycobacterium tuberculosis H37Rv | 83332.12]
MYVRHLGLRDFRSWACVDLELHPGRTVFVGPNGYGKTNLIEALWYSTTLGSHRVSADLPL
IRVGTDRAVISTIVVNDGRECAVDLEIATGRVNKARLNRSSVRSTRDVVGVLRAVLFAPE
DLGLVRGDPADRRRYLDDLAIVRRPAIAAVRAEYERVLRQRTALLKSVPGARYRGDRGVF
DTLEVWDSRLAEHGAELVAARIDLVNQLAPEVKKAYQLLAPESRSASIGYRASMDVTGPS
EQSDIDRQLLAARLLAALAARRDAELERGVCLVGPHRDDLILRLGDQPAKGFASHGEAWS
LAVALRLAAYQLLRVDGGEPVLLLDDVFAELDVMRRRALATAAESAEQVLVTAAVLEDIP
AGWDARRVHIDVRADDTGSMSVVLP

**Comment by hyoo** [comment]
will be available on alpha soon.
