### ISSUE TITLE
BLAST - failed when using a nt sequence, blastx and specialty gene reference proteins

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1338]
BLAST result didn't return when using a nt sequence, blastx and specialty gene reference proteins.

**Comment by chmao1** [comment]
This is the seqeunce used for testing:
>fig|1349754.4.peg.2470|   ABC transporter, permease protein   [Bacillus simplex NBRC 15720 | 1349754.4]
atggagcccatcagaagttatgctagtcaagaaatagaacaggaaacgaatcctattgag
ccgcaaaaggaacctaaaatcaagaaaaggaaagtctgggtgccgggattactcctttta
acgccgattctacttttcatatttggtttcttcgtcataccgatgttatacattttatat
ttaagcttcatatcaacagataatcttgggggagcggatgcagtttatagcctaaaaaat
tatacacaattattttccgatagctattacttatcttctttatggctgacagtgaaaatc
agtttatattcggtcttggttgctttatttcttggatatccggtagctttaacgatggcc
aaaagttcagcgcggatcagagggtatatcactctcttgatcgtgtcaccactcttggta
agtatagttgtccgtaattttggctggtacctattactattgcctaacggaacgattaat
caaaccttgatggcactcggcataatagatgcaccattgaaactattgttttcggaaatc
ggagttgtaattgggctatccaatgcatatcttcctttcatgatcttatccatcgttgcg
agtctttataatattgatccttctctggataaggcaggagcaatacttggggcaagccca
ttcagaaggttcttttccattacattgccgctaagcatccctggtatcgtatctggctgc
atactagtattcagtttgtcaatgagtgcttatgttacgcctgcgctaatgggtggagcc
aatgtaccagtgatgccagttgtcatctatgatcaaataaataacctgctgcactggact
ttcggatctgctctttcttatattctattagcaaccactgtcatatctgtagccgttttt
acaagagtgtttgaaaaagggaaattcaaggaggtattccgatga

**Comment by hyoo** [comment]
will be available on alpha soon.

**Comment by chmao1** [comment]
tested on beta and passed.
