### ISSUE TITLE
Determining status of job

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#134]
I can see that the job is in progress, but it doesn't tell me WHAT job is in progress.  RAST has a nice interface that allows you to see the status of all the jobs you have submitted.  I imagine that the power user will have a lot of jobs, and won't want to go searching for things.

**Comment by dmachi** [comment]
Click on the thing that says "Jobs" at the bottom and it will bring you to a full list.

From that full list you can double click on a completed row to go to the results or if its a failed job it will give you some information about why it failed (though not necessarily user friendly information about why it failed).

Dustin

**Comment by ARWattam** [comment]
Got it!  I was clicking on the numbers and not the word.  Thanks!

----- Original Message -----
