### ISSUE TITLE
Unable to open Comparative Pathway tool

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1345]
I keep clicking on it from services, but it is not opening the landing page for the tool.  Its not doing anything.
<img width="402" alt="screen shot 2016-12-01 at 9 26 06 pm" src="https://cloud.githubusercontent.com/assets/11475316/20820930/eb329b76-b80c-11e6-9f13-6e20026fa5ec.png">

**Comment by dmachi** [comment]
I’m not seeing any problems with this on beta.  Can you tell if the url changed after you clicked on it (it should end up at https://www.beta.patricbrc.org/app/ComparativePathway <https://www.beta.patricbrc.org/app/ComparativePathway> )?

**Comment by ARWattam** [comment]
Gave up and went to bed, but checked the url in the morning and it was very strange.  It was stuck where it was..even with checking the Pathway Comparison box many times.  So I went to the home page, and then it seemed to reboot it.  Working now.

----- Original Message -----

**Comment by mshukla1** [comment]
closing it.
