### ISSUE TITLE
Drop down list showing folders to place job in Proteome Comparison not consistent

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1347]
Twice this morning it showed an abbreviated list, and did not show Proteome Comparison-my standard folder.  Only once has it shown it, and that was the second time.  Also, the list could be alphabetical...would make things easier to find for clutterers like myself.
<img width="371" alt="screen shot 2016-12-02 at 7 39 44 am" src="https://cloud.githubusercontent.com/assets/11475316/20834325/be350cd4-b862-11e6-83ae-3114f43f1504.png">

**Comment by mshukla1** [comment]
I agree, it should be make alphabetical. 

However, you know that you can click on the folder icon next, which gives you directory listing that can be sorted/reverse sorted alphabetically or by chronology, right?

**Comment by chmao1** [comment]
@ARWattam and @mshukla1 please review this and close the issue if this is no longer required.

**Comment by chmao1** [comment]
Closing this issue for now. Please reopen if this is still an issue.
