### ISSUE TITLE
Wrong info box when submitting Proteome Comparison

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1348]
When I submit a job, the green pop-up box says Genome Comparison.  It should say Proteome.
<img width="381" alt="screen shot 2016-12-02 at 7 44 39 am" src="https://cloud.githubusercontent.com/assets/11475316/20834420/4d7f1bd2-b863-11e6-90bd-afe0d9ab833f.png">

**Comment by chmao1** [comment]
Fixed and will be available in the next build.
