### ISSUE TITLE
Comparative Pathway tool- choose RefSeq and it returns PATRIC

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1349]
When users take the effort to select RefSeq as their annotation choice:
<img width="762" alt="screen shot 2016-12-02 at 8 14 17 am" src="https://cloud.githubusercontent.com/assets/11475316/20835231/737bee10-b867-11e6-8633-c177642d67fc.png">

Why does the table return PATRIC results?
<img width="1115" alt="screen shot 2016-12-02 at 8 14 29 am" src="https://cloud.githubusercontent.com/assets/11475316/20835248/80df2658-b867-11e6-9030-8d83f6cb3174.png">

**Comment by ARWattam** [comment]
And when they engage the filter on the table, RefSeq isn't even there.  Sad....
<img width="1120" alt="screen shot 2016-12-02 at 8 16 26 am" src="https://cloud.githubusercontent.com/assets/11475316/20835281/b16ad52e-b867-11e6-88d3-c3c283ecbb7c.png">

**Comment by ARWattam** [comment]
Its the same when I select all for that particular group.  However, I went back to my old pal, Brucella, and when I select All on that, RefSeq appeared.  Is it because some of the genomes in the previous selection don't have RefSeq annotation?  Does that prevent any summary of the information across all the other genomes?  And how would a user know this?

<img width="816" alt="screen shot 2016-12-02 at 8 18 12 am" src="https://cloud.githubusercontent.com/assets/11475316/20835382/4fc95aa6-b868-11e6-9e84-5b3d16a5c6bd.png">


<img width="1121" alt="screen shot 2016-12-02 at 8 18 24 am" src="https://cloud.githubusercontent.com/assets/11475316/20835392/5963e964-b868-11e6-8003-5366262fe0b4.png">

**Comment by mshukla1** [comment]
Annotation selection should not be there in pathway comparison because there is no 
guarantee that select genomes with have pathways in refseq annotations, or that 
select genomes will even have refseq annotations. 

@hyoo please REMOVE annotation selection from the parameters box.

**Comment by ARWattam** [comment]
Oh No!  Does that mean I will have to change that damn tutorial AGAIN???  NOOOOOOOOO!!!!!!

**Comment by mshukla1** [comment]
I think it is better to change UI and tutorial than confuse users, no?
