### ISSUE TITLE
New genome group not showing up in Protein Family sorter tool

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#135]
I just made a new group of all the complete Mycobacterium genomes.  I can see them in my workspace, but when I open up the Protein Family Sorter, that group is not present.  It only shows the groups I created previously.

**Comment by hyoo** [comment]
I cannot reproduce this problem. I have created one group with 20 genomes and confirmed in the workspace UI and moved to Protein Family Sorter in Tool menu. The new group showed up immediately.

**Comment by hyoo** [comment]
same as #136
