### ISSUE TITLE
Weird hang on of BLAST results table continues

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1354]
The second time I hit the Edit and resubmit button, the BLAST results came with it.
<img width="1440" alt="screen shot 2016-12-02 at 10 07 04 am" src="https://cloud.githubusercontent.com/assets/11475316/20838704/b4d7174e-b877-11e6-9053-f82dbb7a66ed.png">

I don't know if it helps, but here is the screenshot from the developer view
<img width="1429" alt="screen shot 2016-12-02 at 10 12 32 am" src="https://cloud.githubusercontent.com/assets/11475316/20838752/ebf17e5e-b877-11e6-917e-e5c59156a5b0.png">

**Comment by hyoo** [comment]
I don't know how to reproduce this issue. if it persists, please reopen this ticket with detail process and sequences.
