### ISSUE TITLE
Gene tree shows correct locus tags, but organism name is not correct

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1357]
I noticed that the MSA and the gene tree line up correctly when the locus tags are displayed, but not when the organism names are displayed.  

In the screenshot, the shortened gene is actually Brucella sp. F5/99, but B. suis 1330
<img width="1106" alt="screen shot 2016-12-02 at 9 51 17 pm" src="https://cloud.githubusercontent.com/assets/11475316/20856307/c7b46bc0-b8d9-11e6-8382-228429f9d281.png">

When looking at the locus tags, the shortened one is correctly lined up with the Brucella sp F5/99 gene.
<img width="1263" alt="screen shot 2016-12-02 at 9 54 33 pm" src="https://cloud.githubusercontent.com/assets/11475316/20856316/f0f23aa8-b8d9-11e6-9dff-9c8eb8485e79.png">

I was aligning members of PLF_234_00000374

**Comment by aswarren** [comment]
@ARWattam After careful analysis I don't believe this is a bug. A sequence can be shorter but have gaps in the back OR the front of the alignment. I checked the sequences in question and they match to the AA record from the feature table. If you recreate the alignment check the front AND back of Brucella sp. F5/99 and B. suis 1330
