### ISSUE TITLE
Cannot BLAST with a large genome group

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1358]
I have a genome group with ~1000 genomes in it.  When I blast against this group I never have any idea if the blast will work, or how long it might take.  How long should I stare at the spinning circle before I give up?  Why is NCBI so fast and we are so slow?

**Comment by olsonanl** [comment]
@hyoo did we figure out the problem yet with blasting against genome groups / genera ? This sounds similar.

**Comment by hyoo** [comment]
I was able to blast against a genome group that has ~1200 genomes.

**Comment by hyoo** [comment]
i tested with 1200 genomes and it works.

**Comment by olsonanl** [comment]
I think this was related to a bug somewhere along the line - buggy/failed requests have a tendency of showing up as never-ending spinning (which should get a systematic fix btw).
