### ISSUE TITLE
Tutorial: private genome

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1361]
Tutorial => workshop guide: private genome
https://www.beta.patricbrc.org/public/pdfs/Workshop-Private-Genome.pdf

Now that we are providing a direct link to the list of private genomes from the top navigation bar, I imagine that to be one of the easiest way for users to explore their private genomes. We need describe this option in the tutorial. 

-Maulik

<img width="320" alt="screen shot 2016-12-06 at 6 11 46 am" src="https://cloud.githubusercontent.com/assets/1236463/20925229/469b7a84-bb7b-11e6-954c-8dcaabdf5b34.png">

**Comment by rkenyon** [comment]
Done: 
https://docs.patricbrc.org/user_guides/workspaces/private_genomes.html
Also created Jobs User Guide:
https://docs.patricbrc.org/user_guides/workspaces/jobs.html
