### ISSUE TITLE
trouble loading pathway summary for private genome

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1362]
I went to one of my private gnomes, feature table, searched for "glycolysis", and found all the features mapped to glycolysis pathway. 

Next, I selected those features and clicked on pathway summary in action bar. I get endless spinning wheel and results never load. 

I tried the same with several other genes with EC numbers, never worked. 

I tried another private genome, still didn't work. 

Given this happens for private genome, I can't share the URL. But, I can show it in person, if needed.

**Comment by mshukla1** [comment]
BTW, pathway summary doesn't work from pathway tab as well, for private genomes.

**Comment by hyoo** [comment]
this could be related to the cert error. please wait until we resolve the issue and try again.
