### ISSUE TITLE
The AMR data on the website do not match the AMR data on the FTP site. 

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1364]
There are (at least) 340 K. pneumoniae genomes with an SIR determination on the FTP site (predating the november release).  Only 288 show up on the beta site.  Most of the missing ones are coming from the DeLeo publication that we assembled ourselves.  Oh, and now I've noticed that they exist in the downloads you don't filter for amr panel or any of the things in the attached image, so something must have gone wrong on the import into solr.

Also, as an aside, when you download this selection it gives you 9 Enterobacter genomes.

[TableS4_KPN_matrix.xlsx](https://github.com/PATRIC3/patric3_website/files/633981/TableS4_KPN_matrix.xlsx)

![image](https://cloud.githubusercontent.com/assets/7661533/20927512/9351a0e0-bb87-11e6-808a-66a03d3c0aaa.png)

**Comment by mshukla1** [comment]
I have updated the data in the database. The numbers should be comparable now. 

-Maulik

**Comment by jimdavis1** [comment]
How long should this take?  I am not seeing the update on beta yet.

**Comment by mshukla1** [comment]
It is updated already.

**Comment by hyoo** [comment]
https://www.beta.patricbrc.org/view/Taxonomy/573#view_tab=genomes

![image](https://cloud.githubusercontent.com/assets/1236467/20933222/096e0a1a-bb9d-11e6-8eff-1a512d777c25.png)


I am seeing 355 genomes now.
