### ISSUE TITLE
genome metadata needs cleanup

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1365]
![image](https://cloud.githubusercontent.com/assets/1236467/20931873/3dfc9774-bb98-11e6-90f6-c40be709722f.png)

I was about to regenerate data landing page cache, but I stopped because this may mess up the chart.

1. remove undefined in disease
2. merge None and none in disease
3. Merge Human, Homo sapiens and Homo sapiens in host name
4. remove or rename "not applicable" in host name
5. Merge "Non-susceptible" and "Nonsusceptible" in Antimicrobial Resistance

**Comment by mshukla1** [comment]
ok, I will run the clean up this morning.

**Comment by hyoo** [comment]
This is not done yet. removing Obsolete tag.

**Comment by mshukla1** [comment]
Fixed.
