### ISSUE TITLE
Filtering on Transcriptomic gene list using keyword text box returns results for all bacteria

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1366]
I was looking at a particular experiment for E. coli MG1655 from my private workspace.  I had clustered the heatmap, selected genes of interest that were up-regulated.  A new tab opened, showing that I had selected 267 genes.  That's too many to get pathway results, so I wanted to filter on all genes that had an EC number.  I entered EC in the text box and hit return.  What the table returned was not a subset of the Escherichia coli MG1655 genes I had been looking at, but all genes in PATRIC.
<img width="1081" alt="screen shot 2016-12-06 at 3 41 06 pm" src="https://cloud.githubusercontent.com/assets/11475316/20942794/ec6dee52-bbca-11e6-9a22-d1ffbc58b5fb.png">

**Comment by hyoo** [comment]
@ARWattam I think this is a bug already fixed. I cannot reproduce this bug. Please reopen if it still exists.
