### ISSUE TITLE
Error loading Variant service tutorial on production

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1367]
Here's what it looks like at this location:
https://www.patricbrc.org/public/pdfs/Workshop-Variation-Service.v3.pdf
<img width="1348" alt="screen shot 2016-12-06 at 4 45 01 pm" src="https://cloud.githubusercontent.com/assets/11475316/20944967/74d292ea-bbd3-11e6-9b92-d59a2d355c25.png">

All other tutorials loaded fine

**Comment by dmachi** [comment]
That link is incorrect.  It should be https://www.patricbrc.org/public/pdfs/Workshop-Variation-Service.pdf <https://www.patricbrc.org/public/pdfs/Workshop-Variation-Service.pdf>

**Comment by hyoo** [comment]
Ron asked me to remove .v3 in the file name and I changed accordingly, but i didn't noticed actually there are two links to change. fixed and will be available on production soon.

**Comment by ARWattam** [comment]
I had sent aversion without v3 in title. I'll send again when I get home

**Comment by hyoo** [comment]
if you want to change the tutorial, please update the Box folder.

**Comment by ARWattam** [comment]
The one in Box is the one without v3 in it.  That should have been the one loaded.

----- Original Message -----
