### ISSUE TITLE
Genome group created from heatmap does not get saved

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#137]
This breaks Rebecca's AMR tutorial:

Use organisms menu to go to Brucella
Click on protein family sorter
Type dnak into search box
Show heat map view
Click on Chaperon protein DnaK column head
Click on add proteins to group 
Wait a long time - popup never seems to show up
When it does, select create a new group and name it
Choose save as genome group
Save to workspace

Then go to the workspace
Click in genome groups
And the new group is not there

**Comment by hyoo** [comment]
This was due to the data api call. I have fixed it and available on alpha now. This will be deployed with Release 1.1 on Friday.
