### ISSUE TITLE
Workspace: which timezone should we use?

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1370]
I just uploaded this file at 10:55AM.  Note the date as being 4:50, I think this is like greenwich time, but it's weird.

![image](https://cloud.githubusercontent.com/assets/7661533/21081617/6b4d104a-bf90-11e6-85f9-893e085632e5.png)

**Comment by hyoo** [comment]
@olsonanl Is this Shock server time?

**Comment by olsonanl** [comment]
The data in the workspace looks like this:
```
{
  "_id": ObjectId("584ebbb8fc65213abb4a8903"),
  "autometadata": {

  },
  "creation_date": "2016-12-12T15:01:12",
  "folder": NumberLong(0),
  "metadata": {

  },
  "name": "MRSN388634.fa",
  "owner": "jimdavis@patricbrc.org",
  "path": "",
  "shock": NumberLong(1),
  "shocknode": "https://p3.theseed.org/services/shock_api/node/1f8ed998-cbfd-4d8d-b946-496be14542cd",
  "size": NumberLong(5305619),
  "type": "contigs",
  "uuid": "D257942C-C07B-11E6-B1AB-A7D4682E0674",
  "workspace_uuid": "79D4B6A4-D3D3-11E4-91B6-D1F6682E0674"
}
```

The date appears to be an ISO8601  datetime, with no designated time zone.

The corresponding Shock node has this (looking at the underlying mongo record)

```
  "created_on": new Date(1481554856728),
  "last_modified": new Date(1481554857358),
```

which appears to be epoch time in ms; converting created_on:

```
GMT: Mon, 12 Dec 2016 15:00:56.728 GMT
Your time zone: 12/12/2016, 9:00:56 AM GMT-6:00
```

and last_modified:

```
GMT: Mon, 12 Dec 2016 15:00:57.358 GMT
Your time zone: 12/12/2016, 9:00:57 AM GMT-6:00
```

so there is some slop there ... 

All of that said; I just uploaded files both at the command line and through the GUI and the creation times appear to mesh properly.

**Comment by olsonanl** [comment]
This is fixed by ensuring workspace service returns timestamps with a timezone indicator (Z) attached, and with times forced into UTC.

Times within Shock correctly have a time zone.

NB Safari javascript does not properly parse valid ISO8601 times of the form 2017-10-31T16:16:37+0000
