### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1372]
The "sequences" tab is worthless if you cant trace back the original sequence ids from the contigs file.  I have no idea what "562.13195.con.0001" is relative to what I gave the annotation service.

![image](https://cloud.githubusercontent.com/assets/7661533/21082064/ef46166e-bf98-11e6-9535-c0d69c0fec07.png)

**Comment by mshukla1** [comment]
Original sequence ids are now saved as part of the sequence description. Resolved. 

<img width="1007" alt="screen shot 2018-07-12 at 3 46 11 pm" src="https://user-images.githubusercontent.com/1236463/42658378-bf97c312-85ea-11e8-8fd5-30e9c78236f1.png">
