### ISSUE TITLE
PFS: takes longer for private genome

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1373]
I'm getting the pinwheel of death when I click on the protein families page for my annotated genome:

It ended up loading when I clicked on another tab and then clicked back.

![image](https://cloud.githubusercontent.com/assets/7661533/21082095/a322b214-bf99-11e6-9efd-c5b19256b1f6.png)

**Comment by hyoo** [comment]
I tried with my private genomes, but cannot reproduce this problem. please reopen if this persists
