### ISSUE TITLE
bookmark on taxon?

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1375]
![image](https://cloud.githubusercontent.com/assets/1236467/21105639/90085adc-c050-11e6-9747-8f1867642255.png)

It would be useful if user can bookmark a taxon and that goes below the genus list, as making a shortcut.

**Comment by mshukla1** [comment]
Users can use web browser bookmark for saving the taxon links, hence I don't think there is much added value in this. 

If we have a way to create custom home page or dash board like iGoogle, that would be more useful.
