### ISSUE TITLE
cannot access to workspace 

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1377]
<img width="845" alt="win-chrome-workspace" src="https://cloud.githubusercontent.com/assets/1236467/21110857/90083dcc-c064-11e6-8001-c489bee4bcde.png">

I was testing on the windows chrome, I don't see my workspaces. This is a fresh install of windows & chrome.

<img width="1213" alt="win-chrome-workspace-console" src="https://cloud.githubusercontent.com/assets/1236467/21111000/2b0be2ba-c065-11e6-9363-3a7e408ee305.png">

**Comment by hyoo** [comment]
This happens on all the browsers in Windows 10, but it works on Chrome & firefox on Windows 7.

![image](https://cloud.githubusercontent.com/assets/1236467/21127244/1bc0f2d0-c0b7-11e6-8eb9-3315b4cab2c7.png)

I am wondering whether this is related to the content-type we are using ("application/jsonrpc+json" or "application/json-rpc") since,

![image](https://cloud.githubusercontent.com/assets/1236467/21127271/47984e1c-c0b7-11e6-891a-cfe0e5d4a8b2.png)


https://developer.mozilla.org/en/docs/Web/HTTP/Access_control_CORS

**Comment by hyoo** [comment]
this disappeared after updating windows. Internet Explorer Edge still showing problem but at least Chrome and Firefox are working.

**Comment by olsonanl** [comment]
Concur. My win10 VM shows edge not working due to CORS issues but chrome works properly.
