### ISSUE TITLE
Enhancement to proteome comparison tool

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1380]
A user would like protein family ids in the table output of the proteome comparison tool.  I think that seemed like a nice idea.

**Comment by rkenyon** [comment]
Jim triage comment: Medium.  This would be a nice enhancement.

**Comment by chmao1** [comment]
@jimdavis1 Do you mean that we need to add the PATRIC local and global family id columns to the ref_genome section in the result file?

**Comment by chmao1** [comment]
Based on the discussion with Rebecca, PATRIC local and global family id columns were added for the reference genome. These are not added for the comparison genomes to avoid making the table too big.

**Comment by mshukla1** [comment]
Awesome, thanks.
