### ISSUE TITLE
Workshop test datasets on FTP

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1382]
Bundle up all relevant test input and output datasets for the workshop as a single zip file. 

We had one for the ANL worksop, but it was too big, ~5gb. We need one with smaller size. 

-Maulik

**Comment by hyoo** [comment]
might be better to do before the upcoming workshops, GLBIO (May 15), ASM (June1-5)

**Comment by hyoo** [comment]
We add public PATRIC workspace sharing so that attendee does require to download from ftp. so closing this ticket.
