### ISSUE TITLE
Error reporting for the failed jobs

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1386]
the error output dropdown seems flaky. Often, it is empty when we know there is error output on the backend service.

**Comment by olsonanl** [comment]
More than flaky - I don't think I've ever seen valid error output in the new production site

**Comment by olsonanl** [comment]
This is a dup of #1378 but I can't seem to mark it so.

**Comment by mshukla1** [comment]
I know, I copied it verbatim from the  skype thread during the workshop! :)

I think this need to be fixed ASAP.

**Comment by olsonanl** [comment]
one or the other of these issues should be closed as a duplicate. #1378

**Comment by hyoo** [comment]
this is fixed by the 2017 March release.
