### ISSUE TITLE
Put CLI Tutorials on the PATRIC site

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1391]
Add a link to PATRIC command-line tools: 

https://github.com/PATRIC3/PATRIC-distribution/releases

Also, make CLI tutorials available from the PATRIC website. 

https://github.com/PATRIC3/PATRIC-distribution/tree/master/Tutorials

Currently, they are available only on SEED site: 
http://tutorial.theseed.org/PATRIC-Tutorials/

-Maulik

**Comment by hyoo** [comment]
working on pdf version and will add to the tutorial page.

**Comment by hyoo** [comment]
available on alpha. will be deployed by July release.
