### ISSUE TITLE
Inconsistency in feature count in pathway map and final data from heatmap

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1394]
Here's where I was working on L. casei:
https://www.patricbrc.org/view/PathwayMap/?annotation=PATRIC&pathway_id=00030&feature_id=PATRIC.1051651.3.AFYK01000061.CDS.19280.20152.rev,PATRIC.1051651.3.AFYK01000061.CDS.15401.16024.rev,PATRIC.1051651.3.AFYK01000061.CDS.18365.19258.rev&genome_ids=1051651.3

I noticed on the pathway map that this genome had 9 features with an EC number of 4.1.2.13:
<img width="1440" alt="screen shot 2016-12-22 at 2 49 29 am" src="https://cloud.githubusercontent.com/assets/11475316/21403936/7d7646c4-c7f1-11e6-8e6a-21fdfc06bbe7.png">
 
So I went to the heatmap and clicked on the cell and then clicked "Show Proteins".  It returned 5:
<img width="1438" alt="screen shot 2016-12-22 at 2 52 53 am" src="https://cloud.githubusercontent.com/assets/11475316/21404009/c84d0e30-c7f1-11e6-9033-dd8b867e053b.png">

However, when I clicked on the row header, it returned 9:
<img width="1439" alt="screen shot 2016-12-22 at 2 53 53 am" src="https://cloud.githubusercontent.com/assets/11475316/21404037/e9d685d6-c7f1-11e6-91c8-a2501081c988.png">

**Comment by hyoo** [comment]
oh,, this is a bug, thanks for reporting. i will fix it

**Comment by hyoo** [comment]
fixed and available on production.
