### ISSUE TITLE
The issue of changing the protein families from default (PG) to PLFams still problematic

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1395]
Several times I have changed to PLFams on Protein family page at taxon level (working on Lactobacillus casei).  I change from the default, which is PGFams, to PLFams.  The spinning wheel comes up, and although on the filter it says PLFams, in the table they are still PGFams.

**Comment by hyoo** [comment]
Rebecca, I am trying to reproduce this problem, but was not successful so far.

In my case, once the spinning wheel comes up, the main grid changes to "Loading..." and changed to pgfam or plfam accordingly. 

Does it happen to you or you see a little bit different behavior? I am using chrome (55.0).


https://www.patricbrc.org/view/Taxonomy/1582#view_tab=proteinFamilies

![image](https://cloud.githubusercontent.com/assets/1236467/21405658/ea8e6f44-c78c-11e6-988c-df5cb417bd82.png)

**Comment by hyoo** [comment]
#1393

**Comment by ARWattam** [comment]
Hmm!  When I followed your link it worked fine.  I will keep an eye on it today and see what happens in the workshop.  they have us in a computer room with windows machines.  All have chrome installed, but I don't know the version.

Fingers crossed that this goes well!

----- Original Message -----

**Comment by hyoo** [comment]
here is an instruction for updating chrome. you can ask participants to do. this is what I did in the Florida workshop. 

https://support.google.com/chrome/answer/95414?co=GENIE.Platform=Desktop&hl=en

**Comment by hyoo** [comment]
Haven't heard after 5 months. closing.
