### ISSUE TITLE
Lactobacillus reuteri genomes lacking PLFams and PGFams (strain 480_44 is example)

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1396]
There are 7 L reuteri strains where this is an issue.  A larger check across the resource should be done to see if it is a more widespread problem.

The good news is that they all have FIGFams

**Comment by olsonanl** [comment]
An example of this appears to be 1598.259. It has recall data in

/vol/patric3/fams/2016-0904/update.out/1598.259

**Comment by mshukla1** [comment]
all public genomes have been recalled and updated in the database.
