### ISSUE TITLE
Broken links in SysBEP page in new website.

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1397]
Some of the secondary pages from the main SysBEP page have not been migrated from the old legacy site. 

https://www.patricbrc.org/content/center-for-systems-biology-of-enteropathogens-sysbep

The following internal links are broken.  Please fix, but don't worry about the Add to Group functionality for now.

http://patricbrc.org/patric/html/S_enterica_CYT.html
http://patricbrc.org/patric/html/S_enterica_IM.html
http://patricbrc.org/patric/html/S_enterica_PERI.html
http://patricbrc.org/patric/html/S_enterica_OM.html
http://patricbrc.org/patric/html/S_enterica_moonlighting.html

http://patricbrc.org/patric/html/S_enterica_pathogenesis.html

http://patricbrc.org/patric/html/S_enterica_SPI-2_effector.html
http://patricbrc.org/patric/html/S_enterica_effector.html

http://patricbrc.org/patric/html/S_enterica_SPI-2_TTSS.html

There are other broken external links, e.g., PNNL_xxxx.  Ron is checking into those again.

Ron

**Comment by hyoo** [comment]
https://github.com/PATRIC3/patric3_website/tree/master/webRoot/patric/html

this is a location of files. 

1. Do you think we need to move doc and xls files as well?
2. Do we need to keep Brucella_Annotation_Protocol directory as well?

**Comment by rkenyon** [comment]
We don't need to move the doc or xls files.  I'm not sure what the Brucella_Annotation_Protocol directory is, but it probably wouldn't hurt to move it.

**Comment by rkenyon** [comment]
Also found a few more broken internal links to transcriptomics data sets in PATRIC:

http://patricbrc.org/portal/portal/patric/SingleExperiment?cType=taxon&cId=590&eid=483361
http://patricbrc.org/portal/portal/patric/SingleExperiment?cType=taxon&cId=590&eid=867640
http://patricbrc.org/portal/portal/patric/SingleExperiment?cType=taxon&cId=629&eid=482123

**Comment by hyoo** [comment]
For the single Experiment, please use 
https://www.patricbrc.org/view/ExperimentComparison/483361#view_tab=overview

**Comment by hyoo** [comment]
I have uploaded the static pages and fixed the links.
https://github.com/PATRIC3/p3_api/commit/c2744a739674e397688344453e3fe0ce961cbc91

and updated Experiment page as well
https://github.com/PATRIC3/p3_api/commit/0b731ffd42e618ceafd7e7b163f0fc162645d69e
