### ISSUE TITLE
Can't move or delete items in workspace

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#140]
When I was testing the system before release, I annotated a genome and couldn't put it in its own folder.  It went into Genome Group, and now that annotated genome has messed up my ability to use any group I created after that point.  I can't delete or move this genome, or any of the groups.  

I am working against a deadline of making handouts for an upcoming workshop, so this is making my life VERY DIFFICULT!  Is there a quick fix that somebody can offer me?

**Comment by hyoo** [comment]
In the job list, right click of row offers delete option, but it does not work. Are we going to offer a delete function?

**Comment by dmachi** [comment]
The right click was supposed to be commented out for now, I've fixed that.  We dont' have the ability to delete jobs themselves.  I've also added the job results types to the list of valid types for the DeleteItem action.
