### ISSUE TITLE
The annotation should be shown by default on the features tab of a genome group

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1400]
![image](https://cloud.githubusercontent.com/assets/7661533/21770346/83ebc0e6-d648-11e6-8836-f6fe5188b65a.png)

**Comment by dawenx** [comment]
just wanted to make sure, so you want the 'annotation' column show up ONLY on the features tab of GenomeGroups, or on the features tab of anywhere?

**Comment by hyoo** [comment]
We need to discus to understand the rationale of the original request. The annotation field was hidden by default intentionally due to the limited horizontal space. Jim, would you describe why you think so?

**Comment by dmachi** [comment]
I agree.  Additionally we default to filtering on PATRIC annotations, so the column will always show “PATRIC” until a user changes the filters.  In the few cases where seeing the annotation is important, the column is available and can be shown by clicking on the column selector (plus icon located beside/over the last column of the grid).
