### ISSUE TITLE
prevent creating a folder in special folders (feature/genome/experiment groups)

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1403]
Shouldn't we prevent creating a folder (and maybe uploading as well?) in the special folders? 

A confusion incident was that user created a folder (assuming that is an empty group) and tried to add genomes to that folder, which did not work without any error message. 

We can provide some message on the event of action, but we also need to prevent the confusion in earlier process.

![image](https://cloud.githubusercontent.com/assets/1236467/21781889/02ffb012-d677-11e6-81df-696864286b80.png)

**Comment by mshukla1** [comment]
I have seen many users place all kinds of files and folders inside special folders. 

Conversely, they also create genome groups / feature groups etc outside of these special folders, specially when they want to share them with other users. 

I am not sure if we should care or do something about it.

**Comment by nconrad** [comment]
yeah, i'm indifferent about this because I think of those folders as simply "default folders".  It sounds like the real problem may be understanding what a genome group is?

**Comment by mshukla1** [comment]
I agree. I think more important is to allow users to search/find all genome groups / feature groups no matter where they are in their workspace, which is mentioned in another ticket. 

Closing this one.
