### ISSUE TITLE
Can't logout

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#1404]
(See gif)

![ogeykmeu35](https://cloud.githubusercontent.com/assets/1194246/21821785/6bf7071e-d73a-11e6-9b54-0b6b5cb6f55d.gif)

 Nothing shows up in console.

**Comment by nconrad** [comment]
The account settings link doesn't seem to be working for me either.

**Comment by nconrad** [comment]
This was on Chrome.  I'm still testing a little.

**Comment by hyoo** [comment]
try https://user.patricbrc.org/logout

**Comment by hyoo** [comment]
This is fixed and available on production now. Safari has a little bit different issue, but it is tracked by another ticket. So, I am closing this one.
