### ISSUE TITLE
https://user.patricbrc.org links don't work

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#1405]
When I go to reset my password, I end up at https://user.patricbrc.org where none of the links work and it's "impossible" to get back to https://patricbrc.org.

**Comment by nconrad** [comment]
It looks like this hasn't been deployed?  I just did a password reset on the production site, which sent me to user.patricbrc.org via an email link to change my password, leading to confusion.

**Comment by hyoo** [comment]
ah. right, it was deployed on alpha, but not on prod. I just deployed and restarted. try again

**Comment by nconrad** [comment]
seeing this:

![image](https://cloud.githubusercontent.com/assets/1194246/25495116/b5cd6fee-2b41-11e7-88aa-75ecb6d8c148.png)

**Comment by nconrad** [comment]
I guess the other thing is that there's no navigation back to the actual website.
