### ISSUE TITLE
cant scroll left-to-right in genome page

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1406]
I selected all of the columns for a genome:

![image](https://cloud.githubusercontent.com/assets/7661533/21855568/8d5cb9bc-d7e4-11e6-8f21-8d91bb706e72.png)

but now I can't scroll left to right and see the data for the extra columns.

![image](https://cloud.githubusercontent.com/assets/7661533/21855609/a3fcfd30-d7e4-11e6-920f-d6b5b790904f.png)

look at what is happening to the column headers as i deselect columns:

![image](https://cloud.githubusercontent.com/assets/7661533/21855666/d7665bbc-d7e4-11e6-8df9-10ca6a9a90df.png)

**Comment by hyoo** [comment]
I think this is dgrid problem, it does not show columns if horizontal space is too busy. 
you need to maintain a reasonable number of columns (depends on your browser width) to see values.

**Comment by rkenyon** [comment]
This seems to be "fixed" in that it adds all the columns scrunched together rather than enabling horizontal scrolling.
![screen shot 2018-08-03 at 5 39 15 pm](https://user-images.githubusercontent.com/3188570/43667044-594f8f2a-9744-11e8-80e9-2e8cfa5b514b.png)
