### ISSUE TITLE
Genome Browser: feature spanning origin of replication

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1407]
...is displayed incorrectly on the genome browser. See the message below from a user for details. 

Version: 3.2.74 
URL: 
https://www.patricbrc.org/view/Genome/1352.804#view_tab=browser&loc=CP014450%3A1..189452&tracks=refseqs%2CPATRICGenes%2CRefSeqGenes&highlight=
User ID: mckennep
Hi,
Just wanted to let you know that in a genome I annotated using PATRIC, 
there was a weird call in the RefSeq Annotation.
All of this plasmid (Plasmid 1 of Enterococcus faecium strains ATCC 700221:
https://www.patricbrc.org/view/Genome/1352.804#view_tab=browser&loc=CP014450%3A1..189452&tracks=refseqs%2CPATRICGenes%2CRefSeqGenes&highlight=
was annotated as a single orf of an ABC transporter.
Thanks! The new web site is a lot better.
-Peter

**Comment by hyoo** [comment]
User is complaining about RefSeq Annotation. This is not related to genome browser. And we don't have control on RefSeq Annotation as well.
