### ISSUE TITLE
Bad bug in genome viewer tab

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1408]
I submitted 49 Staph genomes to the annotation service using the p3 script, 
submit-patric-annotation.  All genomes were submitted with a strain name in the scientific name field, e.g., "Staphylococcus aureus Sample_3957".  None of the strain names are visible on the genome browser.  How can I make the strains visible for my Houston collaborator?

![image](https://cloud.githubusercontent.com/assets/7661533/21989299/fa8778c6-dbcf-11e6-88c5-cecdb40eacc8.png)

**Comment by mshukla1** [comment]
I don't this this is a UI problem. I don't see the strain names in the database either. Can you check corresponding job output file and see if the genome name is correctly displayed in GTO? 

If possible, share the command you used for submission. 

-Maulik

**Comment by jimdavis1** [comment]
You can close the issue. I screwed up the submission.  Although the strain comes over as part of the genome name and is not parsed into the strain column, which might be turn out to be a problem later.

![image](https://cloud.githubusercontent.com/assets/7661533/21994826/45682806-dbe7-11e6-8cd0-c4a264924010.png)

**Comment by mshukla1** [comment]
We try to use the provided strain name to make genome name more informative, but not the other way.

**Comment by hyoo** [comment]
closing per Jim's comment
