### ISSUE TITLE
MSA: add actions for selected features

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1410]
User wanted to select a feature and go to corresponding feature overview page. 

More generally though, the action bar should have all the options available from feature table for single/multiple feature selections. 

-Maulik

PATRIC created PATRIC-636:
-----------------------------

            Summary: Switching to feature view from MSA view
                Key: PATRIC-636
                URL: https://jira.cels.anl.gov/browse/PATRIC-636
            Project: PATRIC
         Issue Type: Bug
           Reporter: PATRIC
           Assignee: Rebecca Wattam

Version: 3.2.73 
URL: 
https://www.patricbrc.org/view/MSA/?in(feature_id,(RefSeq.28450.88.CP008834.CDS.2913163.2914197.fwd,RefSeq.1249468.3.CP004001.CDS.70438))
User ID: Bacillaene

Would like to have the function to leave msa view to feature browser for 
one sequence

**Comment by aswarren** [comment]
https://github.com/PATRIC3/patric3_website/issues/1293

**Comment by chmao1** [comment]
This is available now.
