### ISSUE TITLE
Proteome comparison: circos error

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1411]
User submitted a job, using a private genome with >4000 contigs and it failed with the following circos error. 

We need to either fix the config to address the issue or present a clear message to the user indicating that the genome have too many contigs and it can not be handled properly. 

-Maulik

circos_opts = $VAR1 = {
          'image' => '/scratch/tmp/M6BI7QpOFR/circos/image.conf',
          'ideogram' => '/scratch/tmp/M6BI7QpOFR/circos/ideogram.conf',
          'radius' => 450,
          'colors' => '/scratch/tmp/M6BI7QpOFR/circos/colors.conf',
          'karyotype' => '/scratch/tmp/M6BI7QpOFR/circos/karyotype.txt',
          'large_tiles' => '/scratch/tmp/M6BI7QpOFR/circos/large.tiles.txt',
          'housekeeping' => '/scratch/tmp/M6BI7QpOFR/circos/housekeeping.conf',
          'comp_genomes' => [
                              '/scratch/tmp/M6BI7QpOFR/circos/comp_genome_1.txt',
                              '/scratch/tmp/M6BI7QpOFR/circos/comp_genome_2.txt',
                              '/scratch/tmp/M6BI7QpOFR/circos/comp_genome_3.txt'
                            ],
          'is_user_genome' => {},
          'circos' => '/scratch/tmp/M6BI7QpOFR/circos/circos.conf',
          'ticks' => '/scratch/tmp/M6BI7QpOFR/circos/ticks.conf',
          'ref_type' => 'genome_id',
          'plots' => '/scratch/tmp/M6BI7QpOFR/circos/plots.conf',
          'ref_genome' => '/scratch/tmp/M6BI7QpOFR/circos/ref_genome.txt'
        };
Error running cmd=circos -conf /scratch/tmp/M6BI7QpOFR/circos/circos.conf -outputdir /scratch/tmp/M6BI7QpOFR/circos, stdout:
debuggroup summary 0.17s welcome to circos v0.67-7 16 Mar 2015 on Perl 5.020002
debuggroup summary 0.17s loading configuration from file /scratch/tmp/M6BI7QpOFR/circos/circos.conf
debuggroup summary 0.17s found conf file /scratch/tmp/M6BI7QpOFR/circos/circos.conf
debuggroup summary 0.46s debug will appear for these features: output,summary
debuggroup summary 0.46s SVG output image /scratch/tmp/M6BI7QpOFR/circos/circos.svg
debuggroup summary 0.46s HTML map file /scratch/tmp/M6BI7QpOFR/circos/circos.html
debuggroup summary 0.46s parsing karyotype and organizing ideograms
debuggroup summary 1.27s karyotype has 4353 chromosomes of total size 5,636,423

  *** CIRCOS ERROR ***

  You have asked to draw [4353] ideograms, but the maximum is currently set at
  [2000]. To increase this number change max_ideograms in etc/housekeeping.conf.
  Keep in mind that drawing that many ideograms may create an image that is too
  busy and uninterpretable.

  If you are having trouble debugging this error, first read the best practices
  tutorial for helpful tips that address many common problems

      http://www.circos.ca/documentation/tutorials/reference/best_practices

  The debugging facility is helpful to figure out what's happening under the
  hood

      http://www.circos.ca/documentation/tutorials/configuration/debugging

  If you're still stumped, get support in the Circos Google Group

      http://groups.google.com/group/circos-data-visualization

  Stack trace:

stderr:
 at /disks/patric-common/runtime/circos-0.67-7/bin/../lib/Circos/Error.pm line 418, <F> line 4353.
	Circos::Error::fatal_error("ideogram", "max_number", 4353, 2000) called at /disks/patric-common/runtime/circos-0.67-7/bin/../lib/Circos.pm line 335
	Circos::run("Circos", "outputdir", "/scratch/tmp/M6BI7QpOFR/circos", "configfile", "/scratch/tmp/M6BI7QpOFR/circos/circos.conf") called at /disks/patr
ic-common/runtime/bin/circos line 38

**Comment by hyoo** [comment]
Yes, we have seen this problem and thought displaying more than 2000 contigs may not make sense to users. The other ticket regarding job error message will take care of this issue.

**Comment by chmao1** [comment]
I set maximum contig number to 5000 now.

**Comment by chmao1** [comment]
@olsonanl I made a pull request for this fix. Please review and merge. Thanks.

**Comment by chmao1** [comment]
@mshukla1 The fix is now available on production. The maximum contig number now set to 5000.
