### ISSUE TITLE
PDF: bug while using multiple filters

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1412]
https://jira.cels.anl.gov/browse/PATRIC-631

https://www.patricbrc.org/view/Taxonomy/140#view_tab=proteinFamilies

Selected include/exclude filters as shows to show PF present in three genomes, but absent in other four. Two PFs found. 

Then, I search for "EC" using keyword search. and it went back to all protein families. 

Se the attached screenshots. 

<img width="1120" alt="screen shot 2017-01-16 at 3 10 42 pm" src="https://cloud.githubusercontent.com/assets/1236463/21999175/64716a20-dbfe-11e6-9144-b038a735237a.png">

<img width="1119" alt="screen shot 2017-01-16 at 3 10 18 pm" src="https://cloud.githubusercontent.com/assets/1236463/21999177/67a09f04-dbfe-11e6-8af1-44d631cf7b4e.png">

**Comment by hyoo** [comment]
fix will be available on alpha soon.

**Comment by hyoo** [comment]
this has been deployed on production.
