### ISSUE TITLE
Assembly: integer for min contig coverage

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1413]
Assembly submission form -> advanced paramenters -> min contig coverage

User tried to enter an integer number and got warning, i.e. value 2.0 works, but 2  generates error, which is non intuitive. 

-Maulik

<img width="367" alt="screen shot 2017-01-16 at 5 47 35 pm" src="https://cloud.githubusercontent.com/assets/1236463/22002739/ec1ec552-dc13-11e6-8804-53bd6621bc8c.png">

<img width="368" alt="screen shot 2017-01-16 at 5 47 25 pm" src="https://cloud.githubusercontent.com/assets/1236463/22002743/eff3849c-dc13-11e6-9ff9-e4b8af4f97c8.png">

**Comment by mshukla1** [comment]
Harry, I believe this is simple JS check issue. Can you fix it?

**Comment by dawenx** [comment]
i will fix this soon. somehow, it required to provide a tenth digit in the original form... i will relax this constraint to make it the same as other inputs in this form.

**Comment by dawenx** [comment]
This is on alpha, please verify and close. @mshukla1

**Comment by mshukla1** [comment]
I just tried it. The integer numbers work fine now. However, if I enter a non-integrer value, it complains that "The value entered is not valid", but doesn't say what the valid values are! 

Please change the message to "Please provide an integer value" for both min contig length and min coverage input boxes.  

<img width="428" alt="Screen Shot 2019-06-03 at 11 16 29 AM" src="https://user-images.githubusercontent.com/1236463/58817377-3687e900-85f1-11e9-9fec-e5ff7e6f56a0.png">

**Comment by AllanDickerman** [comment]
If we are going to have a min-coverage parameter, I have to change the code to add a mapping of reads to assembly, followed by samtools depth.
I believe it would be a good thing to do. User’s may enjoy having a bam file they could look at in the genome browser.
This will take a while to implement and test. Could it come along a little later?

Also, there is no technical reason for the min coverage to be required to be an integer.

Allan

**Comment by mshukla1** [comment]
Allan, This tickets was in the context of the current assembly service submission form.

However, is you said, it would be good to have it available in the new service as well, perhaps later.

-Maulik



On Jun 3, 2019, at 12:26 PM, Allan Dickerman <notifications@github.com<mailto:notifications@github.com>> wrote:

If we are going to have a min-coverage parameter, I have to change the code to add a mapping of reads to assembly, followed by samtools depth.
I believe it would be a good thing to do. User’s may enjoy having a bam file they could look at in the genome browser.
This will take a while to implement and test. Could it come along a little later?

Also, there is no technical reason for the min coverage to be required to be an integer.

Allan

**Comment by dawenx** [comment]
@mshukla1 i just updated invalid message for both "min contig length" and "min contig coverage" and it's in PR 878.

@AllanDickerman this issue is for current assembly service and it was open more than 2 years ago. it was assigned to me on in april this year. anyway, i think i have fixed it now.
