### ISSUE TITLE
MSA viewer not working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1414]
I have tried several times to build an MSA with the following four genes, but it never loads.  They are from private genomes...that shouldn't make a difference, I wouldn't think:
fig|234.71.peg.1958
fig|234.72.peg.2428
fig|234.73.peg.214
fig|234.74.peg.416

**Comment by ARWattam** [comment]
Tried to do it again with a different set of proteins from private genomes on PFS.  Here's what the code says...
<img width="1440" alt="screen shot 2017-01-19 at 8 39 06 am" src="https://cloud.githubusercontent.com/assets/11475316/22108938/7b24fabc-de23-11e6-9a6c-540dbc24195c.png">

**Comment by aswarren** [comment]
@ARWattam try it again should be fixed now.

**Comment by ARWattam** [comment]
Yes!  Working!!

----- Original Message -----
