### ISSUE TITLE
global search frustration

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1416]
while we're fixing global search we need to make it possible to trivially get to features whose IDs we know. I'd like to see something like an "extract everything that looks like an ID from a chunk of text" where I could paste an email from Rebecca into a page and have it extract a list of IDs. Here, I laboriously constructed an OR search of IDs and got results that were nearly completely incorrect.
![capture](https://cloud.githubusercontent.com/assets/2152226/22109525/ba741e92-de1d-11e6-99d3-e9e5b42c2ae7.PNG)

**Comment by chmao1** [comment]
I've added an option "Any exact item" to take care this problem. Please let me know whether this is still an issue.

**Comment by chmao1** [comment]
tested and confirmed.
