### ISSUE TITLE
Download from BLAST table doesn't show BLAST e value, % coverage, % identity

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1417]
This is very frustrating.  You download from the BLAST table when you did BLASTN against the genome sequences, you get the information of all the contigs, but not any of the information you wanted, which is the details on the BLAST hits

**Comment by mshukla1** [comment]
If you download the whole table as txt or cvs using the table download button above the table, 
it gives you %identity, score and value. Results are kept in the same order as shown in the table. 
See the attached screenshot. 

However, when you select few entries for the table and then use the download from the action 
bar, it downloads only the features or sequences, without blast values. I can see that this 
would be confusing to the user. 

<img width="1118" alt="screen shot 2017-01-20 at 9 11 25 am" src="https://cloud.githubusercontent.com/assets/1236463/22157057/a9829c1a-defb-11e6-8e17-5532f304577f.png">

**Comment by ARWattam** [comment]
I just did that and I didn't get that.  See attached.

----- Original Message -----

**Comment by ARWattam** [comment]
Also, I can't get access to your screenshot.


----- Original Message -----

**Comment by mshukla1** [comment]
I didn't get your screenshot either! It seems it doesn't work if you attach it with email! 

Here is mine! 

<img width="1118" alt="screen shot 2017-01-20 at 9 11 25 am" src="https://cloud.githubusercontent.com/assets/1236463/22157071/ba7e26f6-defb-11e6-98eb-d522a3ff242f.png">

**Comment by hyoo** [comment]
Here are list of columns you should see from the downloaded file when you blast against genome sequences.

["Genome", "Genome ID", "Accession", "Description", "Product", "Identity", "Query cover", "Subject cover", "ALN Length", "Score", "E value"]
