### ISSUE TITLE
Discrepancy between sequences listed - inconsistency on the same page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1419]
In the genomes list for Brucella inopinata BO1, it has 55 contigs listed in the table, but when you highlight that row, in the information panel it says there are 48 sequences:
<img width="1440" alt="screen shot 2017-01-22 at 10 14 08 am" src="https://cloud.githubusercontent.com/assets/11475316/22183412/c6e34d5e-e08b-11e6-8987-7e763827893b.png">

Then when I go to the landing page for the genome and click on the sequences, it says that there are 55 again:
<img width="439" alt="screen shot 2017-01-22 at 10 16 34 am" src="https://cloud.githubusercontent.com/assets/11475316/22183420/f30f96bc-e08b-11e6-83c3-0335f5f4d2c5.png">

**Comment by mshukla1** [comment]
Ok, I will look into it.

**Comment by mshukla1** [comment]
Sequences column have been been deprecated, as it created confusion between contigs and sequences. Instead, now, contigs indicate the total number of contigs, including chromosomes, plasmids, and unmapped contigs. 

For this genome, now the number of contigs and total sequences in the genome both are 55. 

https://patricbrc.org/view/Genome/470735.4#view_tab=sequences
