### ISSUE TITLE
Job status update latency

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#142]
Both Bob and Andrew have noticed some latency with respect to updating the job status for fast acting jobs. Both Annotation and Differential Expression jobs have completed but are still reported as Running in the Jobs counter and Jobs grid up to 5-10 minutes after completion.

**Comment by olsonanl** [comment]
This should now be fixed. Strange bug relating to the POSTing of a REST url that contained a body of a single "0" never getting through, and resulting in a 5-minute timeout. Fixed in this commit.

https://github.com/olsonanl/app_service/commit/a155646a86d3fcafd4feee382a2dec9eb0388cbb
