### ISSUE TITLE
Subject coverage in BLAST needs some adjusting

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1420]
Check out the screenshot.  Is the Subject coverage based on the entire contig, and is that the way it should be?
<img width="1121" alt="screen shot 2017-01-22 at 2 15 53 pm" src="https://cloud.githubusercontent.com/assets/11475316/22185114/752e4424-e0ad-11e6-96af-b8b74d8d5036.png">

**Comment by mshukla1** [comment]
Yes, it is based on the entire subject sequence, in this case, entire contig, hence only 2%. 

It may not be informative when subject is entire contig sequence, but it is not incorrect!
