### ISSUE TITLE
View on gene transcriptomic page not showing all metadata.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1422]
The metadata for experimental conditions, etc. are hidden under the tabs.  See fig|511145.12.peg.1001 and screenshot below
<img width="1075" alt="screen shot 2017-01-29 at 2 23 45 pm" src="https://cloud.githubusercontent.com/assets/11475316/22407593/f9ddb00c-e62e-11e6-8b9d-9949fce58d29.png">

**Comment by chmao1** [comment]
This is due to the limited space in the panel. The solution is using mouse-over to the pie slices to view the metadata.

**Comment by mshukla1** [comment]
- The pie chart should show top 5 categories, plus an additional category "others", that contain all remaining samples. 

- The bar chart should should show only top 5 categories.

**Comment by chmao1** [comment]
This was implemented the same way as the legacy PATRIC. The bar charts shows the top 5 categories, while pie charts shows all categories (not just top 5).
