### ISSUE TITLE
Pathway map from transcriptomic selection comes up empty

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1425]
I selected a group of genes from the transcriptomic heatmap
<img width="1435" alt="screen shot 2017-01-30 at 8 36 31 pm" src="https://cloud.githubusercontent.com/assets/11475316/22449080/ecd911be-e72b-11e6-8aa1-406e4525791b.png">
This opened a new page, and I selected all the genes and clicked on the pathway icon:
<img width="1185" alt="screen shot 2017-01-30 at 8 36 24 pm" src="https://cloud.githubusercontent.com/assets/11475316/22449087/fdd7b128-e72b-11e6-8c14-dde2d631ae6e.png">
I chose nitrogen metabolism, expecting to see at least something
<img width="1438" alt="screen shot 2017-01-30 at 8 36 15 pm" src="https://cloud.githubusercontent.com/assets/11475316/22449101/159ec3a0-e72c-11e6-9f9d-2eaaddd8a4ff.png">
I was not expecting to see an empty pathway map with no genes at all
<img width="543" alt="screen shot 2017-01-30 at 8 36 00 pm" src="https://cloud.githubusercontent.com/assets/11475316/22449109/22807442-e72c-11e6-8d1b-b841261a02c0.png">
Sad.....

**Comment by hyoo** [comment]
@ARWattam would you share your url or list of feature ids so that I can debug?

**Comment by hyoo** [comment]
please reopen if you can reproduce this problem.
