### ISSUE TITLE
BLAST for faa is not working

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1427]
BLAST returned error. See below.

![untitled](https://cloud.githubusercontent.com/assets/6361802/22896150/fdbb345a-f1ec-11e6-9bcd-f06cda039c0c.png)

**Comment by olsonanl** [comment]
The missing blast file was there in the Feb 5 filesystem snapshot:

```
$ ls -l /vol/patric3/.snapshot/weekly.2017-02-05_0015/downloads/blastdb/163164.16.PATRIC.faa.pin
-rw-r--r--. 1 mshukla collab 10440 Dec 14  2015 /vol/patric3/.snapshot/weekly.2017-02-05_0015/downloads/blastdb/163164.16.PATRIC.faa.pin
$ ls -l /vol/patric3/downloads/blastdb/163164.16.PATRIC.faa.pin
ls: cannot access /vol/patric3/downloads/blastdb/163164.16.PATRIC.faa.pin: No such file or directory
```

We should be able to copy that file back in; Maulik do you know why it was deleted?

**Comment by olsonanl** [comment]
It was there in the Feb 12 snapshot too:

```
$ ls -l /vol/patric3/.snapshot/weekly.2017-02-12_0015/downloads/blastdb/163164.16.PATRIC.faa.pin
-rw-r--r--. 1 mshukla collab 10440 Dec 14  2015 /vol/patric3/.snapshot/weekly.2017-02-12_0015/downloads/blastdb/163164.16.PATRIC.faa.pin
```

**Comment by mshukla1** [comment]
I updated all the blast databases over the weekend and this time, I used 
absolute path of the databases in stead of the relative paths last time. 
This has caused the references in the alias files to become invalid. 

I am trying to figure out what is the best way  to address it. 

-Maulik

**Comment by hyoo** [comment]
verified the fix on production.
