### ISSUE TITLE
Blast is broken

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1429]
![image](https://cloud.githubusercontent.com/assets/7661533/22938161/85dfeb10-f2a0-11e6-8574-4a0eed9464c6.png)

![image](https://cloud.githubusercontent.com/assets/7661533/22938167/8ccd61aa-f2a0-11e6-911b-4e974f9976fb.png)

**Comment by hyoo** [comment]
Blast database has been updated with wrong path. This is fixed now.
