### ISSUE TITLE
Downloading genome group from workspace in excel file returns error message

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#143]
![screen shot 2015-04-10 at 1 55 07 pm](https://cloud.githubusercontent.com/assets/11475316/7093680/4c38e4f6-df89-11e4-9eba-31fd66ce7030.png)

**Comment by dmachi** [comment]
This appears to be an error related to new versions of excel opening this file.  It works for me on my desktop with an older excel (2008).  On my laptop (and andrew's) with 2011, it works but gives an error and asks to repair the file beforehand.  I'm investigating how to fix.

**Comment by mshukla1** [comment]
I don't see this problem. Can we close it?

**Comment by ARWattam** [comment]
Nope, it is still happening from the workspace when I try and download with excel
![screen shot 2015-06-11 at 9 32 33 am](https://cloud.githubusercontent.com/assets/11475316/8108165/e30fd588-101c-11e5-9bab-57cb83a8d5ec.png)

**Comment by ARWattam** [comment]
Just demonstrated for Chunhong so there is a witness.  Download as excel, but looks like file is text...but messed up text that can't open

**Comment by dmachi** [comment]
This is a problem with opening in newer versions of excel.  I need to try a different converter to see if it resolves the problem.

**Comment by mshukla1** [comment]
The excel file downloaded from the workspace still has problem. When I try to open it I get an error saying incompatible file type. Need to fix it sooner.

-Maulik

**Comment by dmachi** [comment]
I changed out the excel handling code to use a different library.  It appears to be working for me, but I have an older excel so the previous version was already working for me.  @mshukla1 can you try this on beta and see if it resolves the problem that you were having?

**Comment by hyoo** [comment]
I have verified and works for me. I am closing.

**Comment by hyoo** [comment]
file extension is not correct.

**Comment by dmachi** [comment]
Fixed and pushed to beta.
