### ISSUE TITLE
Downloading genome sequences for private genomes from Taxon level page gives an empty zip file

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1432]
[Privat_Brucella_genomes_fna.zip](https://github.com/PATRIC3/patric3_website/files/801371/Privat_Brucella_genomes_fna.zip)

**Comment by mshukla1** [comment]
Private genome download is not supported from taxon level pages. It is confusing 
and something we need to address sooner. 

-M

**Comment by ARWattam** [comment]
Its also a drag.  I had to download 8 of them individually.  Is there a good reason for not allowing this?

----- Original Message -----

**Comment by mshukla1** [comment]
Current download is supported through FTP site, and we can’t put private genomes on FTP. 
So, supporting private genome download will require slightly different mechanism. 

It is one of those things on our list that we haven’t got to!

**Comment by hyoo** [comment]
#1470
