### ISSUE TITLE
logout in safari

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1433]
I'm currently logged in to my Houston user account on PATRIC:

![image](https://cloud.githubusercontent.com/assets/7661533/23407984/f7826176-fd8b-11e6-8db1-561a46f1b90a.png)

when I try to log out, I get the following error:
![image](https://cloud.githubusercontent.com/assets/7661533/23407997/026a1f3e-fd8c-11e6-9fe7-06fb79fc2547.png)

I'm not sure if this is useful:
![image](https://cloud.githubusercontent.com/assets/7661533/23408031/2992cc14-fd8c-11e6-8ad4-278b21fa4d0f.png)

**Comment by hyoo** [comment]
TypeError: this.resolve is not a function<br> &nbsp; &nbsp;at Function.lookup (/srv/p3_api/node_modules/express/lib/view.js:110:17)<br> &nbsp; &nbsp;at View.lookup (/srv/p3_api/enableMultipleViewRoots.js:22:25)<br> &nbsp; &nbsp;at new View (/srv/p3_api/node_modules/express/lib/view.js:85:20)<br> &nbsp; &nbsp;at EventEmitter.render (/srv/p3_api/node_modules/express/lib/application.js:569:12)<br> &nbsp; &nbsp;at ServerResponse.render (/srv/p3_api/node_modules/express/lib/response.js:960:7)<br> &nbsp; &nbsp;at ServerResponse.cls_wrapRender [as render] (/srv/p3_api/node_modules/newrelic/lib/instrumentation/express.js:167:21)<br> &nbsp; &nbsp;at Layer.&lt;anonymous&gt; (/srv/p3_api/app.js:189:6)<br> &nbsp; &nbsp;at Layer.wrappedHandle (/srv/p3_api/node_modules/newrelic/lib/instrumentation/express.js:622:19)<br> &nbsp; &nbsp;at eval (eval at wrapHandle (/srv/p3_api/node_modules/newrelic/lib/instrumentation/express.js:1:0), &lt;anonymous&gt;:4:28)<br> &nbsp; &nbsp;at Layer.handle_error (/srv/p3_api/node_modules/express/lib/router/layer.js:71:5)

**Comment by hyoo** [comment]
@dmachi , would take a look at this? I guess you've already resolved logout issue, but this seems something different.

**Comment by dmachi** [comment]
Will check it out.

**Comment by hyoo** [comment]
this is fixed on alpha and will be deployed on production soon.

#1530
