### ISSUE TITLE
filters don't update immediately in pathway view

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1434]
If I'm looking at for instance

https://www.patricbrc.org/view/GenomeList/?in(genome_id,(1434164.3,1434165.3,1434163.3))#view_tab=pathways&filter=and(eq(annotation,%22PATRIC%22),or(eq(pathway_class,%22Xenobiotics%20Biodegradation%20and%20Metabolism%22),eq(pathway_class,%22Carbohydrate%20Metabolism%22)))

and I open the filters and change the pathways being filtered, the list does not update until I reload the page.

version 3.2.84

**Comment by dawenx** [comment]
I think I have found the reason for this issue and I would like to "assign" this to myself. I still don't have permission to do anything on the right panel, e.g., assign the issue to myself, add labels, etc.

**Comment by dawenx** [comment]
I think I have fixed it and this is part of pull request #409 now.

**Comment by hyoo** [comment]
tested on alpha.
