### ISSUE TITLE
Protein family with multiple pages, will only show results for features selected on the first page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1435]
Below is a user bug report from a workshop in France.  I was able to replicate this by choosing the same protein family, which returns multiple pages in the feature table.  I selected 3 on the first page and generated an MSA, then I went to the next page and selected 2, then generated a MSA.  The MSA for the first selection was the only one that loaded.  I went to the third page, selected two, and tried to get DNA fasta.  It loaded fasta sequences from the first page.  

"I noticed some problem while I was working on Patric (the new site).
I was searching for a gene in my genome, and when I found it, I looked at the Local Patrick family (PLF_1883_00000260).
(https://www.patricbrc.org/view/Feature/PATRIC.58344.4.JOEL01000002.CDS.42085.43290.fwd#view_tab=overview)
There were 933 other proteins in that local family ( displayed on 5 pages), so I choose a few of them and ask for FASTA or MSA.
And here is my problem : as long as you stay on one page (= 200 proteins), you can do as you want,
But if you select items on several pages, then neither MSA nor FASTA sequences are available (even with a very low amount of sequences)."

**Comment by hyoo** [comment]
This is a bug from grid container and a wide spread problem.

**Comment by dawenx** [comment]
my fix in PR 549 should address this issue as well.

**Comment by dawenx** [comment]
deployed on alpha a few days ago, need verification @ARWattam
