### ISSUE TITLE
Bad character when searching for a role

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1436]
I get the following error when I try to search for the functional role

Diphtheria toxin (NAD(+)--diphthamide ADP- ribosyltransferase) (EC 2.4.2.36)

on the search bar:

[Error] Error: Unexpected ')' at character 23
	p (/js/3.2.87/p3/layer/core.js:470:371)
	onKeypress (/js/3.2.87/p3/layer/core.js:465:373)
	(anonymous function) (dojo.js:58:452)
	(anonymous function) (dojo.js:58:507)
	(anonymous function) (dojo.js:81:451)

**Comment by olsonanl** [comment]
Putting it in double quotes doesn't help

**Comment by hyoo** [comment]
![image](https://cloud.githubusercontent.com/assets/1236467/25450266/f440b95c-2a83-11e7-9845-75abe5caaa76.png)

We need to handle this error.

@maovt any idea? please assign an appropriate person to fix this issue.

**Comment by chmao1** [comment]
Fixed and will be available in the next build.

**Comment by hyoo** [comment]
available on alpha, confirmed that this is fixed.
