### ISSUE TITLE
whitespace trim on group creation

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#1437]
Whitespace at the end of the group name creates a lookup problem

e.g.
"name":"NCSU Europe "}

**Comment by dawenx** [comment]
andrew, can you assign this to me?

**Comment by aswarren** [comment]
@dawenx I can't actually. Let me see what I can do. For the time being I will assign it unto myself.

**Comment by dawenx** [comment]
I went ahead to fix it and submitted a pull request.

**Comment by hyoo** [comment]
@maovt would you test on alpha and close this ticket?

**Comment by chmao1** [comment]
tested on alpha and worked.
