### ISSUE TITLE
RNA-Seq job failed

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1438]
0e34891c-08c9-4fa3-8f51-3fcf6ef5313f

My job failed during the workshop.  Was it something I did, or is it something more.

**Comment by olsonanl** [comment]
Rockhopper puked on something:

Sequencing reads written to SAM file:   /scratch/tmp/kP1UOsmQc9/Rockhopper/MERO_75_R2.sam

Aligning sequencing reads from files:
        MHB_R1.fastq.gz
        MHB_R2.fastq.gz

stderr:
Exception in thread "main" java.lang.ArithmeticException: / by zero
        at SamOps.isTextFile(SamOps.java:823)
        at SamOps.<init>(SamOps.java:93)
        at Peregrine.getReadsInputFileType(Peregrine.java:796)
        at Peregrine.<init>(Peregrine.java:168)
        at Rockhopper.<init>(Rockhopper.java:148)
        at Rockhopper.main(Rockhopper.java:908)
:

Although it looks like it was an empty file problem:

GET WS => /scratch/tmp/kP1UOsmQc9 MHB_R1.fastq.gz /ARWattam@patricbrc.org/home/MHB_R1.fastq.gz
Error retrieving https://p3.theseed.org/services/shock_api/node/7d3eb512-2109-4a01-b3f8-d7ad25022536: {"status":400,"data":null,"error":["Node has no file"]}

Both files empty:

olson@beech:/disks/p3/task_status/0e34891c-08c9-4fa3-8f51-3fcf6ef5313f$ ws-ls -a '/ARWattam@patricbrc.org/home'|grep MHB
MHB_R1.fastq.gz                                 ARWattam@patricbrc.org reads                  2016-07-21T19:16:41          0 n         n          
MHB_R2.fastq.gz                                 ARWattam@patricbrc.org reads                  2016-07-21T19:15:43          0 n         n

**Comment by rkenyon** [comment]
This was a failed job from 6 months ago.  I presume issue is now resolved.
