### ISSUE TITLE
Download tool-genomic features tab-delimited format not working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#144]
I have created a group and am using the data download tool to try to get features from that group.  I chose:
All genomic features in tab-delimited format (*.features.tab)

And it returns the following message:
"Sorry. The requested file(s) are not available."

**Comment by hyoo** [comment]
It works for some of my group but not all. I have a test case. I will work on it.

**Comment by hyoo** [comment]
.features.tab are not available. Maulik, would you double check?

**Comment by mshukla1** [comment]
The files have been added. It should be working now. 

-Maulik
