### ISSUE TITLE
Strange behavior when searching for EC number

### ISSUE THREAD

**Issue by cshenry** [PATRIC3/patric3_website#1440]
Hey guys - I was working on the role mappings to reactions and looking for genes with a specific function. The function is associated with the EC number 2.3.1.37. I started out by just searching the patric website for this EC. I got over 400K hits, and most didn't seem to have the EC. Then I searched for "aminolevulinate". This yielded the correct result found here:
https://www.patricbrc.org/view/FeatureList/?keyword(aminolevulinate)#view_tab=features&defaultSort=-score&filter=and(or(eq(feature_type,%22CDS%22)),or(eq(annotation,%22PATRIC%22)),false)

I don't know why the search for 2.3.1.37 didn't give me the same thing. Generally, it might be good to have a little hint box to help people craft better SOLR searches. For example, I find that SOLR won't find something if your search term isn't at the beginning of a "word" (e.g. a search for levulinate" returns nothing).

**Comment by chmao1** [comment]
I've added the options "Any exact item" and  "All exact items" in global search to take care of the EC number search problem.

**Comment by chmao1** [comment]
tested and confirmed
