### ISSUE TITLE
BLAST should return error message, or improve information on sequences accepted

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1441]
User suggested:  "I had some problems running Blast on nucleotide sequences against the
plasmid database. The sequence I pasted was initially split in several
lines and PATRIC wouldn't run. I converted the sequence to a one-line
sequence and it worked fine. It would be useful if an error is reported
when pasting multi-lined sequences."

**Comment by hyoo** [comment]
![image](https://cloud.githubusercontent.com/assets/1236467/25450161/a17345b4-2a83-11e7-8695-cab94c9d70b1.png)

Here is current message.

"Please provide only one nucleotide or protein sequence" 

Any suggestion?

**Comment by ARWattam** [comment]
How about:

PATRIC BLAST accepts only one sequence at a time.  Please provide only one
sequence.

**Comment by hyoo** [comment]
sounds good. will update and deploy with May release.
