### ISSUE TITLE
Add Genome ID 1311.163

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1442]
User would like genome added to PATRIC.  Genome ID 1311.163.

**Comment by hyoo** [comment]
I can't understand the original request. 

https://www.patricbrc.org/view/Genome/1311.163

is already available and public.

**Comment by ARWattam** [comment]
Harry, that genome has no genes or protein families associated with it.

https://www.patricbrc.org/view/Genome/1311.163#view_tab=features

**Comment by hyoo** [comment]
@mshukla1 this genome was added on 2016-01-17 but has no record in genome_feature, genome_sequence, and pathway.
Do you have any idea?

**Comment by mshukla1** [comment]
It was bad genome, hence, it was removed from the database as part of the data clean up.
