### ISSUE TITLE
GFF API creation

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#1443]
GFF 9th column should only have ';' and '=' as entity separator and value assignment respectively

NC_000962   PATRIC  gene    2226244 2227920 .   +   0   ID=fig|83332.12.peg.2214;name=fig|83332.12.peg.2214;locus_tag=Rv1983;product=PE_PGRS family protein => PE_PGRS35

NC_000962   PATRIC  rRNA    1471847 1473382 .   +   0   ID=fig|83332.12.rna.19;name=fig|83332.12.rna.19;locus_tag=Rvnr01;product=Small Subunit Ribosomal RNA; ssuRNA; SSU rRNA

**Comment by mshukla1** [comment]
Yes, that's what we have. I don't understand the problem!

**Comment by aswarren** [comment]
https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md

In addition, the following characters have reserved meanings in column 9 and must be escaped when used in other contexts:
; semicolon (%3B)
= equals (%3D)
& ampersand (%26)
, comma (%2C)

Note the examples I posted have extra ';' and '=' characters in the middle of the "value" string. Making it hard to consume and violating the specification above.
Its an easy fix we just need to get rid of the extra ';' and '=' by processing the value assignment in the API function. Instead of escaping them (which would still break some programs creating extra work) I suggest replacing ';' with '|' and '=' with '-' or '->'.

**Comment by mshukla1** [comment]
@dmachi can you make the change in the data API so that we can close this ticket? 

-Maulik

**Comment by hyoo** [comment]
I can take a look. @aswarren do you have a url that i can test with my local api changes?

**Comment by aswarren** [comment]
@hyoo from https://github.com/TheSEED/app_service/blob/master/scripts/App-RNASeq.pl#L318

https://www.patricbrc.org/api/genome_feature/?and(eq(genome_id,83332.12),eq(annotation,PATRIC),or(eq(feature_type,CDS),eq(feature_type,tRNA),eq(feature_type,rRNA)))&sort(+accession,+start,+end)&http_accept=application/cufflinks+gff&limit(25000)

There are certainly some examples in there though I'm not sure its comprehensive.

**Comment by hyoo** [comment]
@aswarren i have attached two files, before.gff and after.gff

seems like urlencoding works for all of your cases. Please verify before and after and let me know so that i can commit my changes.

[Archive.zip](https://github.com/PATRIC3/patric3_website/files/1683492/Archive.zip)
