### ISSUE TITLE
Pathway Summary Page Enhancement - User request

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1447]
Add the ability to create feature list and do MSA from this page
<img width="1358" alt="screen shot 2017-03-22 at 10 36 47 am" src="https://cloud.githubusercontent.com/assets/11475316/24203258/9a6307ae-0eeb-11e7-9d0b-de71daedf2a3.png">

**Comment by dawenx** [comment]
I will work on this enhancement request.

**Comment by mshukla1** [comment]
I am not sure if it is meaningful to build MSA for all the genes in a pathway. Usually they correspond to 
different enzymes and have different domains and sequences.  We can add the option, but in most cases, 
it will lead to crappy alignment and confusion.

**Comment by dawenx** [comment]
I don't have biology background. From programer point of view, MSA takes in a list of feature_ids and perform alignment. In this case, we find all feature_ids in the selected pathways and build MSA. @ARWattam Could you please comment on Maulik's thought? I was working on it and added creating feature list and doing MSA and am doing testing now. I can keep or remove MSA option based on our discussion.

**Comment by mshukla1** [comment]
I leave it Rebecca to decide as well. 

I do think that it will be useful to have other usual feature related actions available fro selection, I.e. Download features, fasta, add to group etc., if possible.

**Comment by ARWattam** [comment]
I don't think the MSA would work, but I think a user should be able to build a feature group that contains all the genes in the pathway from that selection.  Then he/she could sort by name and quickly get all the similar proteins and generate the MSA from there.   

So, when I click on a pathway from whatever group I am examining, I would expect the both the F icon (features) and the Group icon to appear in the green bar.  I will hash it out with the user as to why the MSA would not be a good choice.

**Comment by dawenx** [comment]
OK, will work on it.

**Comment by dawenx** [comment]
This was done and tested on my local copy. A pull request was opened.

**Comment by dawenx** [comment]
this was deployed. will close it.
