### ISSUE TITLE
User confusion on Public status in Genome filter

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1448]
Directly from the user's email:
"Also genome filter option defined as false. "

Biologists don't understand what is meant by False.  Can we just have them be listed as Public or Private?

**Comment by mshukla1** [comment]
I understand and don’t mind changing it for the genomes. Need to discuss it with dustin and harry 
how best to handle it, change it in the database or change via API. 

-Maulik

**Comment by hyoo** [comment]
#1716
