### ISSUE TITLE
User request for ability to delete jobs

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1449]
This user annotated the same genome 3 different times (It happens...I have done it to and would be happy to bore you all with the reasons why I did it).  Someone might like to remove those jobs so they are no longer confused by which one they would like to choose.  Alas, it is not possible right now.

Directly from the user:
"Pseudomonas fluorescens PpR247 (May find three different copies of genome ,,, all are same, I tried to delete and remove but failed)"

**Comment by hyoo** [comment]
#398
closing duplicates
