### ISSUE TITLE
All download functions from data download tool appear to not be working.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#145]
Very frustrated here.  Got message that data wasn't available when I chose:
All annotations in GenBank file format (*.gbf).  

When I tried "Protein coding genes in tab-delimited format (*.cds.tab)" it appeared to download, but when I chose a TextEdit to open it the following screenshot popped up.
![screen shot 2015-04-12 at 8 40 10 am](https://cloud.githubusercontent.com/assets/11475316/7105615/dad59a08-e0ef-11e4-9368-e6ea864f3ac2.png)

**Comment by hyoo** [comment]
I think Maulik is generating genbank file, and I guess those files are not ready yet.

**Comment by mshukla1** [comment]
seems to be working now.
