### ISSUE TITLE
User request for plant host genomes to be added

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1450]
Please consider adding to your host list Citrus maxima (pomelo) with the accesion number MKYQ00000000.1 and Azadirachta indica (mahogany) with the accesion number AMWY00000000.2.

**Comment by mshukla1** [comment]
Our current scope for the host genomes is limited to the genomes relevant to understand bacterial infections relevant to our priority pathogens. 

Plant genomes have very different gene structures and annotations. Most of our analysis tools, i.e. RNA-seq analysis and diff expression, will not work without making necessary adjustments, which may require additional time and effort. 

Hence, my recommendation is not to add plant host arbitrarily, unless we make a policy decision to support them in PATRIC. 

-Maulik
