### ISSUE TITLE
you can't download a fasta of speciality genes

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1452]
A user alerted me to the fact that the ability to download a set of speciality genes in FASTA format (AA or DNA) is missing on the speciality genes tab.  It is kind of a huge pain to have to build a feature set in order to get this.

Here is the download button from the speciality genes tab. 

<img width="1440" alt="screen shot 2017-03-28 at 8 28 26 am" src="https://cloud.githubusercontent.com/assets/7661533/24407448/8b2bdece-1390-11e7-9d32-c1b027a68fee.png">

Here is the download button after creating a feature group:
<img width="1440" alt="screen shot 2017-03-28 at 8 25 58 am" src="https://cloud.githubusercontent.com/assets/7661533/24407379/5097a8e2-1390-11e7-87bc-ad47410e7519.png">

**Comment by hyoo** [comment]
You have "FASTA" button and once you open a window, there is a download button on the top.

![image](https://cloud.githubusercontent.com/assets/1236467/24628627/babe6aee-187c-11e7-9f87-ac15c05e426e.png)

but, agree that it would be nicer to have a shortcut as you described. Just wanted you know there is a way to download it in one click away.

**Comment by dawenx** [comment]
I will work on this. Since the FASTA data does not exist in the sp_gene table, it has to be retrieved from genome_feature table and the file name will be PATRIC_genome_feature.fasta.

**Comment by dawenx** [comment]
this is done, pull request has been submitted.

**Comment by fbjornlund** [comment]
This doesn't appear to work if there is more than one page in the result set. I just downloads 0 byte files.

**Comment by dawenx** [comment]
My understanding is that the download is only supported for results in current page. @hyoo @dmachi is this true?

**Comment by dawenx** [comment]
since #1717 was open and it's more general on URI/download, close this ticket.

**Comment by hyoo** [comment]
I agree with @dawenx, the problem @fbjornlund reported is a general grid selector problem. The selection does not work when picked across multiple pages.
