### ISSUE TITLE
Veronika and Sveta's AMR annotations should appear here:

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1454]
Also, "Literature" is somewhat misleading becuase it makes it look like we annotated it, when we in fact did not.  
![image](https://cloud.githubusercontent.com/assets/7661533/24471050/81627d2a-1486-11e7-8f47-2f8682c6280c.png)

**Comment by mshukla1** [comment]
They do appear now under AMR gene tab, if there are PATRIC AMR genes linked to the specific antibiotic. As I understand, mapping AMR roles to specific antibiotics is till work in progress. Hence, you may not see any PATRIC AMR genes for most of the antibiotics. 

Here is one example where it does show up: 

<img width="1121" alt="screen shot 2017-09-14 at 7 19 04 pm" src="https://user-images.githubusercontent.com/1236463/30461185-164e60ae-9982-11e7-9bcf-dede0c4c4a6b.png">
