### ISSUE TITLE
Resistance phenotype missing

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1456]
There are apparently values (see screenshot), but it is not defined as susceptible, resistant or intermediate.
https://www.patricbrc.org/view/Antibiotic/?eq(antibiotic_name,chloramphenicol)#view_tab=amr
<img width="1044" alt="screen shot 2017-03-30 at 3 38 18 pm" src="https://cloud.githubusercontent.com/assets/11475316/24522882/0854ea10-155f-11e7-8820-b7c80c2a164f.png">

**Comment by mshukla1** [comment]
We solely rely on the SIR phenotypes provided by BioSample/collaborators/publications. 
In other words, we do not compare given MIC values to  CLSI/EUCAST breakpoints to 
infer SIR phenotypes. S, you may have situations where MIC is present but SIR is missing. 

We have discussed automated translation of MIC to SIR in past, but it hasn’t happened yet. 

-Maulik

**Comment by hyoo** [comment]
@mshukla1 OR @ARWattam should we close this ticket?

**Comment by ARWattam** [comment]
Yes, I think we should close it.

Rebecca
