### ISSUE TITLE
No ability to save userid or password when logging in

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#146]
This used to be the standard for the website, and now I have to re-enter my username and password each time I come to the site.  Its one of those little frustrating changes that is going to make the users mad and wonder what's gone on...its certainly worked that way for me.

**Comment by mshukla1** [comment]
Do you still have the problem? I believe this is not a website problem, it is your browser/keychain setting! 

Adding Dustin, in case he wants to comment on it.

**Comment by dmachi** [comment]
Chrome seems to remember who you were logged in as unless you told it to never remember for the site.  We could add a "remember me" checkbox that would set a cookie if people want it.

**Comment by mshukla1** [comment]
Rebecca, you need to check/change your browser/security settings in order to remember username/password, just like any other site. Closing the issue.
