### ISSUE TITLE
Antibiotic View for beta-lactam remained "loading" status

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1462]
Antibiotic View for beta-lactam did not return result. It remained "loading" status
![image](https://cloud.githubusercontent.com/assets/6361802/24569344/aa932560-1633-11e7-85df-f42d09c565c9.png)

**Comment by chmao1** [comment]
This is because "beta-lactam" is not in the "antibiotics" table in solr.

**Comment by hyoo** [comment]
There is some data discrepancy due to the nature of data. beta-lactam is not an antibiotic name, rather it refers a group of antibiotics containing "beta-lactam ring". see more https://en.wikipedia.org/wiki/%CE%92-lactam_antibiotic

Maulik and I will review soon.

**Comment by chmao1** [comment]
Antibiotic View page should handle this case instead of "loading" forever.

**Comment by hyoo** [comment]
Yes, either we block it before making a link or add entries with some reasonable contents.

**Comment by mshukla1** [comment]
This is because beta lactam is a generic term referring to a class of antibiotics, hence it can not be linked to a specific antibiotic compound in pubchem. We need to go back to the original source of AMR data and see if they have provided more specific antibiotic name.

**Comment by mshukla1** [comment]
Two options. Either the page detects that the antibiotic name is not available in solr core and show a message. 

OR, I can create an empty record for that antibiotic in the solr core with minimum info.
