### ISSUE TITLE
Reimplement job status check with websocket

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1463]
I've tried several times to load this, and never seen got it to go on the public site.  Today I tried this feature:
https://www.patricbrc.org/view/Feature/RefSeq.359391.4.NC_007618.CDS.887018.887164.rev#view_tab=compareRegionViewer

Here's the error it returned:
<img width="1440" alt="screen shot 2017-04-02 at 1 05 15 pm" src="https://cloud.githubusercontent.com/assets/11475316/24589233/1cabf5f6-17a5-11e7-83b7-c09f86d83fb6.png">

**Comment by hyoo** [comment]
![image](https://cloud.githubusercontent.com/assets/1236467/24591600/1ca274f6-17cb-11e7-86c7-1d8a59b25df2.png)

This works for me. Is there any firewall?

**Comment by dmachi** [comment]
She is having problems accessing all of the ANL services today.  I think that is the actual root cause here and not a problem with compare region viewer.

**Comment by olsonanl** [comment]
Rebecca are you at VBI or elsewhere today? I'm a little worried about how fragile some things seem to be when behind firewalls etc

**Comment by ARWattam** [comment]
It didn't load when I was at home, whether I was on or off the vpn (I also
didn't have access to my workspace).  Dustin says that he has had multiple
times where chicago or ANL blocked his IP address, and he thought that was
happening to me.  When I was at home this morning, no workspace.  As soon
as I came in, I could see it.  I checked the compare region viewer then,
and it was working.

Does any of that make any sense?

**Comment by olsonanl** [comment]
It does; we need to flag the instances where this is happening so we can take it up with the ANL networking folks to see what is flagging the block if it is indeed happening. We'll need to know your IP address (http://www.whatsmyip.org will tell you) and where you are physically (home, VBI, remote somewhere etc).

**Comment by olsonanl** [comment]
FYI I am tracking this with ANL cyber folks. The traffic apparently triggered a SNORT (intrusion detection system) rule intended for detecting attempts at using the SSL Heartbleed vulnerability. 

My guess is the app service traffic patterns are somehow mimicking that. Another reason to think about a non-polling approach to the monitoring. 

@dmachi @hyoo what is your take on websocket methods for things like this?

**Comment by dmachi** [comment]
I think web sockets is exactly what should be used here.  However, I don’t think each of the backend services should individually expose web sockets.  I think it would be best to establish a web socket connection against the p3-web webserver or a standalone service and have the other services (app service and workspace service) publish events to p3-web which would then republish events back out to the correct users.

**Comment by mshukla1** [comment]
@hyoo @olsonanl @dmachi is there any action needed here or can we close this ticket?

**Comment by olsonanl** [comment]
We should still do this.

**Comment by mshukla1** [comment]
@dmachi 

Can you look into this? Can this be implemented in Dec?

**Comment by dmachi** [comment]
Not in December, but Bob and I mentioned this briefly in skype.  We'll work on a plan for this in the early part of the new year.

**Comment by olsonanl** [comment]
I'm not sure I see why this is marked critical.

**Comment by rkenyon** [comment]
@hyoo marked it as critical.  Not sure why.

**Comment by nconrad** [comment]
Agreed.  I modified the polling to use the task summary method--which is probably unrelated, but much more efficient-- and I haven't heard of this being an issue since that.

**Comment by mshukla1** [comment]
@nconrad can we close this?

**Comment by nconrad** [comment]
yeah.  closing.
