### ISSUE TITLE
Reference and representative genomes in Compare region viewer...?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1467]
When I look at the Compare region viewer for this gene:
https://www.patricbrc.org/view/Feature/RefSeq.359391.4.NC_007618.CDS.887018.887164.rev#view_tab=compareRegionViewer

It is set for Reference and Representative genomes, but only one of those genomes is a representative genome (the 2308 strain).  How is it picking the other strains to view?
<img width="1440" alt="screen shot 2017-04-03 at 10 02 30 am" src="https://cloud.githubusercontent.com/assets/11475316/24613036/0f2e4aae-1855-11e7-80e4-791eff95c408.png">

**Comment by hyoo** [comment]
yes, this is a bug, i will fix it and deploy it to alpha
