### ISSUE TITLE
GO annotations should be included in download of feature table for a genome

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1473]
Currently, users have to click on each feature individually to capture the specific GO annotation.  It might be good to include this as a column they can add to any feature table so that they can view them, too.

**Comment by chmao1** [comment]
Added and available in alpha.

**Comment by hyoo** [comment]
confirmed.
 TW, Rebecca, you can get the filtered list of features by attributes,

![image](https://cloud.githubusercontent.com/assets/1236467/25449329/1514af92-2a81-11e7-9482-0a39e141851f.png)

click Proteins with GO Assignments 956, then you will get only those features
