### ISSUE TITLE
Clicking on amikacin to get to antibiotic landing page takes me to cefotaxime

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1476]
I am trying to get to the landing page for Amikacin, so I clicked on the page for a particular genome and then on the antibiotic link:
<img width="1203" alt="screen shot 2017-04-12 at 2 01 49 pm" src="https://cloud.githubusercontent.com/assets/11475316/24972327/13ec3340-1f89-11e7-8f31-ff9aa01db6c4.png">

But the page that open up is for cefotaxime:

<img width="1135" alt="screen shot 2017-04-12 at 2 02 10 pm" src="https://cloud.githubusercontent.com/assets/11475316/24972337/20194ef0-1f89-11e7-9ba6-1e3c46431cea.png">

**Comment by ARWattam** [comment]
And no, its not listed as a synonym.  I checked that.

**Comment by hyoo** [comment]
What are the urls for each page? I guess you have confused with other tabs, because it passes antibiotic name through the url, so you should be able to see "amikacin" in the url when you open the antibiotic page through the "A" button in the green bar.

**Comment by hyoo** [comment]
Technical description is posted in #1480

**Comment by hyoo** [comment]
fixed and available on prod.
