### ISSUE TITLE
Order by count on AMR doesn't appear to be by count.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1477]
The page is here:
https://www.patricbrc.org/view/Taxonomy/2#view_tab=overview

I thought that the bar graph should look like steps down.  It reorders to show the highest count, but from then on it appears to be random.
<img width="1130" alt="screen shot 2017-04-12 at 2 10 50 pm" src="https://cloud.githubusercontent.com/assets/11475316/24972621/061559ee-1f8a-11e7-91b1-a8f27c2ff7d1.png">

**Comment by hyoo** [comment]
The count was meant to be the first series of data, in this case, the number of Resistant phenotypes.

Do you think the total count makes more sense?

**Comment by hyoo** [comment]
@ARWattam do you want to change to the total count or stay as is?

**Comment by hyoo** [comment]
Since not hearing for more than a month, and seeing this in the publication as is, I assume that this does not require any change. 
 
@ARWattam, please reopen otherwise.

**Comment by ARWattam** [comment]
Harry,

I think that this is something that Jim feels very strongly about.  Could
you check with him to be absolutely sure that you close this?  I know that
he wanted the counts to be visible, and for the to be ranked from highest
to lowest.  Jim, can you comment?

Best,

Rebecca

**Comment by hyoo** [comment]
Changing one way to another is not a big deal. Just wanted to confirm what is the correct way to do.  I will talk to Jim.
