### ISSUE TITLE
Seeing repeat of AB information in AMR bar graph

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1478]
Spelling with a capital first letter, and lower case first letter are separated for the same antibiotic.  The example here is Levofloxacin.
https://www.patricbrc.org/view/Taxonomy/286#view_tab=overview

<img width="696" alt="screen shot 2017-04-17 at 3 32 42 pm" src="https://cloud.githubusercontent.com/assets/11475316/25101742/6f22c76c-2383-11e7-986c-e78188f53399.png">

**Comment by hyoo** [comment]
fixed.

![image](https://cloud.githubusercontent.com/assets/1236467/25449661/09767a02-2a82-11e7-9538-e4e416bef379.png)
