### ISSUE TITLE
The word "Download" needs to be attached to the symbol for download on the workspace page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#148]
Its just not clear, and is a radical change from the old style.  If it takes a road sign to show users how to get their data, can we please add it?

**Comment by dmachi** [comment]
This is already done isn't it?

**Comment by mshukla1** [comment]
I see that Download is now spelled with the icon when it is displayed at the top, like below. 
![screen shot 2015-06-10 at 10 44 40 pm](https://cloud.githubusercontent.com/assets/1236463/8098789/584a50d6-0fc2-11e5-9558-ccfca53bea22.png)

**Comment by mshukla1** [comment]
However, I still see couple of places where it still shows just the icon. 
![screen shot 2015-06-10 at 10 42 33 pm](https://cloud.githubusercontent.com/assets/1236463/8098794/6f8f5ef8-0fc2-11e5-896c-6be601bd3b29.png)
![screen shot 2015-06-10 at 10 42 21 pm](https://cloud.githubusercontent.com/assets/1236463/8098795/6f8fb45c-0fc2-11e5-89bc-8916a2a04f2b.png)

**Comment by dmachi** [comment]
I don't think it belongs in those other places.  The users will be able to figure that out and it will look like crap to have the word download X times for each file.

**Comment by mshukla1** [comment]
Agree, lets consider it resolved. 

Rebecca, comment or reopen if you think otherwise.

**Comment by ARWattam** [comment]
The text all seems to be present in the workspace and looks great!  Thanks!

**Comment by ARWattam** [comment]
One question on the fna download...why isn't it showing up in the same place as the other download icon?  Shouldn't we train the user to look in a specific place?  Or are you worried that it will be to far from the other information?

**Comment by mshukla1** [comment]
I guess that is because it is associated with a single file, rather that operating on the visible collection / results!! ??
