### ISSUE TITLE
Grid selection error with different pages.

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1480]
https://www.patricbrc.org/view/Taxonomy/570#view_tab=amr&filter=false

1. select the first row in page 1

![image](https://cloud.githubusercontent.com/assets/1236467/25104529/5133b9ac-2386-11e7-9428-d66647d10d6b.png)

2. move to page 2, and select any row

![image](https://cloud.githubusercontent.com/assets/1236467/25104544/60d7c07e-2386-11e7-8db2-db43fd63bd91.png)

3. Due to the javascript error, detail info shows the previous selection and all the action buttons work on old info. 

This is what Rebecca reported regarding wrong antibiotic page linking.

This problem occurs in all the grid not specific to this AMR phenotype.

Dustin, would you take a look at?

**Comment by dmachi** [comment]
I believe I have fixed this, please test it out on alpha.

**Comment by hyoo** [comment]
confirmed. on alpha. will deploy in a week or at most by end of this month (April release)

**Comment by hyoo** [comment]
v3.3.6 has deployed on prod
