### ISSUE TITLE
Predicted region hanging off the end of visualization

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1481]
Shouldn't this be in the middle?  I came at it from the predicted region page.
https://www.patricbrc.org/view/Feature/PATRIC.1280.11371.LLAR01000153.classifier_predicted_region.2147.2588.fwd#view_tab=overview
<img width="1121" alt="screen shot 2017-04-18 at 8 52 14 am" src="https://cloud.githubusercontent.com/assets/11475316/25131609/5a259fe2-2414-11e7-8685-7269916fdb61.png">

**Comment by hyoo** [comment]
Entire contig is 2265bp. I guess there is some miscalculation (not counting margins i suspect) but I think the feature locates at the end of the contig.


On Apr 18, 2017, at 7:52 AM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


Shouldn't this be in the middle? I came at it from the predicted region page.
https://www.patricbrc.org/view/Feature/PATRIC.1280.11371.LLAR01000153.classifier_predicted_region.2147.2588.fwd#view_tab=overview
[screen shot 2017-04-18 at 8 52 14 am]<https://cloud.githubusercontent.com/assets/11475316/25131609/5a259fe2-2414-11e7-8685-7269916fdb61.png>
