### ISSUE TITLE
Genome missing strain name

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1482]
https://www.patricbrc.org/view/Genome/43770.28

Should be called Corynebacterium striatum strain BM4687

**Comment by mshukla1** [comment]
Updated to Corynebacterium striatum strain BM4687. 

https://www.patricbrc.org/view/Genome/43770.28

<img width="1122" alt="screen shot 2017-06-09 at 4 16 17 pm" src="https://user-images.githubusercontent.com/1236463/26994826-1a86414a-4d2f-11e7-83ed-e39c1f534347.png">
