### ISSUE TITLE
Sorting by name is not sorting alphabetically - AMR table

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1483]
This is for Streptococcus (https://www.patricbrc.org/view/Taxonomy/1301#view_tab=overview)

Obviously, amoxicillin should be first.
<img width="710" alt="screen shot 2017-04-20 at 12 04 23 pm" src="https://cloud.githubusercontent.com/assets/11475316/25240766/b6414ef8-25c1-11e7-8a6b-3fbb27b2ddcb.png">

**Comment by mshukla1** [comment]
I have updated converted all antibiotic names in the database to lowercase. That resolves this problem.

-Maulik

**Comment by hyoo** [comment]
confirmed on prod.

![image](https://cloud.githubusercontent.com/assets/1236467/25449574/d304e5da-2a81-11e7-85a3-1416498361de.png)
