### ISSUE TITLE
Issues with paths with spaces

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1484]
I'm thinking we have some serious issues with respect to safe usage of incoming user data. This seems we're asking for trouble with injection attacks.

![screen shot 2017-04-21 at 12 11 41 pm](https://cloud.githubusercontent.com/assets/2152226/25288602/b52fbaa2-268b-11e7-99fb-d9b5be353b13.png)

**Comment by hyoo** [comment]
@olsonanl would you describe what is happening in more detail? Did you add space in the path? Is it at the end or in the middle?

**Comment by olsonanl** [comment]
Look at the directory name - "SPACE DIR"

**Comment by olsonanl** [comment]
It's still doing it, btw.
![screen shot 2017-07-24 at 12 49 52 pm](https://user-images.githubusercontent.com/2152226/28536884-a46f6a46-706e-11e7-9e3e-240383940151.png)

**Comment by nconrad** [comment]
Looks like this didn't have anything to do with spaces--a function just wasn't being called properly.  Fixed in latest PR. 
 https://github.com/PATRIC3/p3_web/pull/493/commits/a9a00f94e34d1137957164792da49ff304ddfdd7#diff-9a563bd8704b4d7dc42a4aa376df80aaR117

**Comment by olsonanl** [comment]
OK, cool. It apparently manifested itself in paths with spaces though.

**Comment by nconrad** [comment]
Should have been any contigs, as far as I could tell.
