### ISSUE TITLE
PATRIC FTP server

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#1485]
It would be helpful to have the FTP service that Dustin wrote on live and on the official services. So that it is easier to send files up to the workspace from a remote server.

It works well. It would be a shame to lose that work.

**Comment by danielolson5** [comment]
dmachi - can you provide a link to repo, and the version that should be deployed?

**Comment by hyoo** [comment]
@dmachi for your heads up

**Comment by dmachi** [comment]
Master branch from  https://github.com/dmachi/p3-ws-ftpd <https://github.com/dmachi/p3-ws-ftpd>  is the latest.

**Comment by hyoo** [comment]
@danielolson5 for your heads up

**Comment by mshukla1** [comment]
@olsonanl @dmachi 

I believe this is addressed by the new FTP upload release. Can we close this?

**Comment by dmachi** [comment]
This has been deployed.  There are a few bugs to fix tracked in other tickets, but it otherwise works. Closing this ticket.
