### ISSUE TITLE
AMR summary graph not clickable when showing a genome group

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1486]
When I create a group and then want to look at AMR across it, I find that the Genomes by Antimicrobial Resistance graph is not clickable.  It is when I look at genomes or taxa.  With it not being clickable, I am unable to find out which of the genomes in my selection actually has resistance or susceptibility to a particular antibiotic.

**Comment by chmao1** [comment]
tested and confirmed on alpha.
