### ISSUE TITLE
Many  Lactobacillus plantarum genomes are missing PLFams

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1487]
I was surprised to see that a large number of  Lactobacillus plantarum  strains have no PLFams.  Here are the strains I counted:
CIF17A5
DSM 20246
DSM 2601
K35
MF1298
MHO2.4
MHO2.9
P14
P22
P26
P73
RI-086
RI-147
RI-162
RI-165
RI-505
RI-506
RI-507
RI-509
RI-511
T10
TISTR875

Here's the heatmap view:
https://www.patricbrc.org/view/Taxonomy/1590#view_tab=proteinFamilies
<img width="1433" alt="screen shot 2017-04-23 at 8 00 56 pm" src="https://cloud.githubusercontent.com/assets/11475316/25318580/0a69f3d6-2860-11e7-9e1c-d2bd9354bcc4.png">

**Comment by ARWattam** [comment]
Maybe we should do a systematic check to see if there are any strains without protein families.

**Comment by ARWattam** [comment]
It looks like one of these, Lactobacillus plantarum strain TISTR875, only has FIGFams.
<img width="1151" alt="screen shot 2017-04-23 at 8 05 29 pm" src="https://cloud.githubusercontent.com/assets/11475316/25318591/5039325a-2860-11e7-9d76-4bae496084b1.png">

**Comment by mshukla1** [comment]
Ok, I will check them tomorrow.

**Comment by mshukla1** [comment]
This has been taken care by the latest protein family updates. All Lactobacillus plantarum genomes now have protein families. 

https://www.patricbrc.org/view/Taxonomy/1590#view_tab=proteinFamilies

<img width="1425" alt="screen shot 2017-06-09 at 4 11 02 pm" src="https://user-images.githubusercontent.com/1236463/26994707-4fb78f46-4d2e-11e7-9bf4-59119f798626.png">
