### ISSUE TITLE
rank not visible on AMR kmers from classifier

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1488]
We don't seem to be showing the rank associated with each classifier prediction.  This is EXTREMELY important for understanding the relevance of a given kmer and the basis of the prediction.  I am worried about presenting this to the program officer on Wednesday if we don't get this fixed ASAP.  I have talked to Jim, and he is equally dismayed by not showing the rank.

**Comment by hyoo** [comment]
This is addressed by #1284

**Comment by mshukla1** [comment]
Harry, this is important for Jim and I like to review the UI functionality with him and make sure it meets his expectations before we close the ticket.

-Maulik
