### ISSUE TITLE
Why are virulence factors appearing in the AMR genes tab?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1489]
https://www.patricbrc.org/view/Antibiotic/?eq(antibiotic_name,isoniazid)#view_tab=amrGenes
<img width="1108" alt="screen shot 2017-04-24 at 2 35 54 pm" src="https://cloud.githubusercontent.com/assets/11475316/25352872/7092d4de-28fb-11e7-93f7-cbed4ccb1a64.png">

**Comment by dawenx** [comment]
It looks like this tab is using "keyword(antibioticName)" as the search string, i.e., "keyword(isoniazid)" in your case. I'm not sure whether that's intended or not, will discuss this with dustin tomorrow.

**Comment by hyoo** [comment]
this is a specialty_gene tab. As far as I remember, we intended to show all the specialty features related to the keyword (antibiotic name) so that user can see all the related features. If this is confusing, we can add a default filter condition on property field so that we display only AMR related features.

**Comment by ARWattam** [comment]
If it says AMR, it should only be AMR.  But then what happens to the other
specialty genes?  Sveta told me that she and Maulik had a conversation
about this, and it was my understanding that AMR genes were going to be
seen on the separate tab.

**Comment by mshukla1** [comment]
The AMR gene tab is accessible only from the antibiotic page and supposed to show only AMR genes for a given antibiotic.

The specialty gene tab at the taxon and genome levels will stay as it is.

**Comment by dawenx** [comment]
If that's OK for everyone, I will put in additional search constraint for this page to pull only AMR genes for a given antibiotic as suggested by Maulik.

PS. I still cannot assign myself to an issue, can someone check my permission? Thanks!

**Comment by dawenx** [comment]
I think I have fixed it and this is part of pull request #409 now.

**Comment by hyoo** [comment]
deployed on alpha 

https://www.alpha.patricbrc.org/view/Antibiotic/?eq(antibiotic_name,isoniazid)#view_tab=amrGenes

will be deploy on prod by the end of April

**Comment by ARWattam** [comment]
I have checked this on alpha for a couple of antibiotics and now it only shows AMR genes.  I think this can safely be pushed to production!

**Comment by dawenx** [comment]
I think this particular one was rolled out to the production as
part of April release.

Dawen

**Comment by ARWattam** [comment]
I checked it on production, and it is working perfectly there as well.
Close this ticket, please.
