### ISSUE TITLE
Compare region view for gene shows neighbors at PubSeed, but not at PATRIC

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#149]
This gene:
fig|1205677.3.peg.1258 

At PATRIC compare region view just show the originating genome and nothing else.  At PubSeed I can see many other genomes.  And I have seen this MANY times today!!

**Comment by hyoo** [comment]
Compre Region Viewer service returns genome that are not included in PATRIC. Will talk to ANL team.

**Comment by olsonanl** [comment]
Can you just drop those for now?

We need a comprehensive solution to the compare region problem including redoing the interface to be more interactive (I’d like to have an in-house browser implemented without gbrowse)

—bob

On Apr 13, 2015, at 9:49 AM, Harry Yoo <notifications@github.com<mailto:notifications@github.com>> wrote:


Compre Region Viewer service returns genome that are not included in PATRIC. Will talk to ANL team.

**Comment by ARWattam** [comment]
Drop them????  But I love them!!!  How long would I have to go without my fix?

----- Original Message -----

**Comment by olsonanl** [comment]
I meant the genomes that aren’t in patric - did you see them before?

On Apr 13, 2015, at 11:34 AM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:

Drop them???? But I love them!!! How long would I have to go without my fix?

----- Original Message -----

**Comment by ARWattam** [comment]
But one of the genomes showing up in the compare region view at PubSeed IS at PATRIC...so not sure why its not showing up.
Mycobacterium bovis AF2122/97

**Comment by hyoo** [comment]
Let me explain a little bit more. So, we query SAPServer with a feature id and number of genomes request. By default, Compare Region View displays 5 most similar genomes, but we actually request +10 genomes to address this type of situation. In the case of  fig|1205677.3.peg.1258, none of 14 genomes (except the genome containing fig|1205677.3.peg.1258 itself) were included in PATRIC so we were not able to display any other track.

**Comment by mshukla1** [comment]
I believe the only solution to all CR viewer problems is to have a truly PATRIC CR viewer that Bob is working on. 

Assigning it to Bob, we can close it when it is released in PATRIC, hopefully by November.

**Comment by mshukla1** [comment]
Obsolete. Will be addressed by the new compare region viewer Bob has developed. 

-Maulik
