### ISSUE TITLE
Feature List: GO term column not shown after clicking "GO term" column selection

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1491]
Clicking GO term column from the hidden column list, the GO term column is not shown until resize the columns in the grid.

**Comment by dawenx** [comment]
As you said in the meeting, this is a general issue with any grid that has lots of fields enabled. There's also a similar report in issue #1406. Is there an option to enable the horizontal scroll bar? @dmachi

**Comment by chmao1** [comment]
The solution for this particular issue is to add "Go term" column in the
css file. We're still discussing whether we should enable the horizontal
scroll bar for all grids.

**Comment by chmao1** [comment]
tested and confirmed on alpha.
