### ISSUE TITLE
Genome named incorrectly in PATRIC

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1493]
https://www.patricbrc.org/view/Genome/1590.175
We call the genome Lactobacillus plantarum strain ZJ95, but at Genbank:
https://www.ncbi.nlm.nih.gov/nuccore/CP012122,CP012123,CP012124
They call it Lactobacillus plantarum strain LZ95

**Comment by mshukla1** [comment]
Another example of genome / strain label being changed in GenBank after initial submission. 

I think I have a plan to handle such cases. With every release, check for the genome name 
updates at NCBI, if updates, rename the genome in PATRIC and keep the old genome name 
as synonym. I will try to implement the scheme for July release. 

-Maulik

**Comment by mshukla1** [comment]
I checked again, both strain names are listed at NCBI. Biosample lists strain names as ZJ95, while genbank file lists as LZ95.

https://www.ncbi.nlm.nih.gov/biosample/SAMN03854682
https://www.ncbi.nlm.nih.gov/nuccore/CP012122.1

Assuming genbank has "more correct" name, I have updated it at patric to Lactobacillus plantarum strain LZ95. 

https://www.patricbrc.org/view/Genome/1590.175
