### ISSUE TITLE
Feature tab for host genomes should default annotation to RefSeq not PATRIC

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1495]
Currently Feature tab for host genomes defaults annotation to PATRIC which makes the feature table empty

![image](https://cloud.githubusercontent.com/assets/6361802/25546029/327ba0e0-2c2f-11e7-86ee-3f153c05dda7.png)

**Comment by hyoo** [comment]
this is address by 
https://github.com/PATRIC3/p3_web/commit/305d8da8c2b8245c7d2c7a01b93316404e54d513
