### ISSUE TITLE
Specialty Genes tab download issue

### ISSUE THREAD

**Issue by dawenx** [PATRIC3/patric3_website#1496]
Sometime, the downloaded file has more records than selected rows. For example, on
https://www.patricbrc.org/view/Taxonomy/776#view_tab=specialtyGenes

when only selecting the 2nd row (Property: “Antibiotic Resistance”, source: CARD), choose either text or csv in download on the action bar, the downloaded file has 3 lines with 2 records.

**Comment by mshukla1** [comment]
I see the same problem. I think it is because the download is implemented using the 
feature id from selection. In this case, there are two specialty gene mappings for the same 
feature id. 

We should fix it if it is trivial, but I wouldn’t consider it critical or high priority. 

-Maulik

**Comment by dawenx** [comment]
I already fixed it when i worked on issue #1452.

**Comment by dawenx** [comment]
this was deployed. will close it.
