### ISSUE TITLE
Gene is incorrectly assigned as a misc_feature

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1497]
I was looking for MMAR_2656, and found that it is listed as a misc_feature.  But when I check that locus tag at GenBank, it has a full sequence and identified as a protein.
https://www.ncbi.nlm.nih.gov/protein/183175990

**Comment by mshukla1** [comment]
MMAR_2656 available as both patric and refseq annotated CDS. 

https://www.patricbrc.org/view/Feature/PATRIC.216594.6.NC_010612.CDS.3240957.3241781.fwd
