### ISSUE TITLE
Mycobacterium PLFam has Gordonia member

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1498]
PLF_1763_00147431 should be restricted to Mycobacterium, but it contains Gordonia.

https://www.patricbrc.org/view/FeatureList/?eq(plfam_id,PLF_1763_00147431)#view_tab=features

**Comment by olsonanl** [comment]
My guess is at the time we generated families last time that taxonomy ID was under genus Mycobacterium in the taxonomy data in PATRIC (that's how it appears in the underlying data).

The new families have it in the right place in the  Gordonia genus.

**Comment by ARWattam** [comment]
When will we see the new families?

**Comment by olsonanl** [comment]
Later than it would be if I hadn't gotten dragged into some talk or another :-)

Next week hopefully.

**Comment by ARWattam** [comment]
Blame Senior Shukla for that one!

**Comment by mshukla1** [comment]
The genome was labeled as Gordonia when we got it from genbank, it later got reclassified/renamed 
as Mycobacterium for the sam taxonomy id. 

Ideally, we should mark the genomes whose names do not match the taxonomy as obsolete and reload them.

**Comment by mshukla1** [comment]
With the recent taxonomy and protein family updates, gordonia genomes are no longer displayed under mycobacteriam and corresponding local families.
