### ISSUE TITLE
Protein mis-identified as misc_feature #2

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1499]
MMAR_1199 is misc_feature at PaTRIC
https://www.patricbrc.org/view/Feature/RefSeq.216594.6.NC_010612.misc_feature.1452647.1456897.fwd

At GenBank its a pretty good protein.
https://www.ncbi.nlm.nih.gov/protein/183174547

**Comment by mshukla1** [comment]
Both misc feature and CDS are annotated by RefSeq. There is no corresponding 
PATRIC feature. However, PATRIC has two smaller genes overlapping with them. 

This look like usual annotation difference between gen bank and PATRIC. I don’t see 
any problem. 

https://www.patricbrc.org/view/Feature/RefSeq.216594.6.NC_010612.misc_feature.1452647.1456897.fwd#view_tab=genomeBrowser&loc=NC_010612%3A1449646..1459896&highlight=NC_010612%3A1452647..1456897&tracks=refseqs%2CPATRICGenes%2CRefSeqGenes <https://www.patricbrc.org/view/Feature/RefSeq.216594.6.NC_010612.misc_feature.1452647.1456897.fwd#view_tab=genomeBrowser&loc=NC_010612:1449646..1459896&highlight=NC_010612:1452647..1456897&tracks=refseqs,PATRICGenes,RefSeqGenes>

![image](https://cloud.githubusercontent.com/assets/1236463/25703305/aa71d15e-309a-11e7-887c-f440cbf05fa5.png)

**Comment by mshukla1** [comment]
![image](https://cloud.githubusercontent.com/assets/1236463/25703313/b0f4d0bc-309a-11e7-89c4-8fe4139e26cb.png)

**Comment by ARWattam** [comment]
You can't get the protein sequence at PATRIC.  This is something I am doing
for Bill Jacobs, so I imagine that its something a Mycobacterium researcher
would do.  This is based on a publication for ESX proteins.  If people who
read that come to PATRIC, they won't be able to proceed.  But its not worth
fighting over.  I can navigate between GenBank and PATRIC.  A Mycobacterium
researcher willl choose GenBank, though, and we won't woo them over to our
resource.

**Comment by ARWattam** [comment]
Yes, I know!!!!  I have been doing the research on this, so I'm aware of
it!  What I was asked to do was find the closest homolog in certain TB
strains from a publication.  I wanted to BLAST them against those
genomes!!!  I had to go to GenBank to get the aa sequence because PATRIC
didn't have it, but its important enough that other people want it.

Honestly, its so frustrating.  I use the resource.  I know these things.
I'm not naive about the fact that it is not called in PATRIC.

**Comment by ARWattam** [comment]
I personally think its a mistake to close this, but fine.  Whatever.

**Comment by mshukla1** [comment]
you are looking at a misc_feature annotated by RefSeq. Misc features don’t have protein 
sequences. 

You can click on the CDS which overlaps with the misc feature from the cartoon, go to CDS page, 
and then download protein sequence from there. 
https://www.patricbrc.org/view/Feature/RefSeq.216594.6.NC_010612.CDS.1452323.1457155.fwd#view_tab=overview <https://www.patricbrc.org/view/Feature/RefSeq.216594.6.NC_010612.CDS.1452323.1457155.fwd#view_tab=overview>

As much as I like to woo biologists to come to our resource, I don’t think showing
protein sequence on a misc feature page for a CDS that just happens to overlaps 
with a misc feature and clearly much different in length, start and stop, is the solution.

-M

**Comment by ARWattam** [comment]
No, I did the search for the locus tag.  At GenBank, that is a protein.

I give up.  My opinion obviously doesn't matter.

**Comment by mshukla1** [comment]
I don’t know why you are taking it personally. I am just stating the facts. 

There is a CDS and a misc feature annotated by refseq with the same locus tag. 
We have both, CDS and misc feature at PATRIC. If you go to CDS you will see the right 
protein with function with sequence, the same way you will get it at genbank. 

… I leave it at that.
