### ISSUE TITLE
Download not capturing isolation name for some strains

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#150]
Mycobacterium setense Manresensis appears in the download tables as just "Mycobacterium settees"

**Comment by hyoo** [comment]
I guess you're mentioning this genome,
https://www.patricbrc.org/portal/portal/patric/Genome?cType=genome&cId=431269.4

and you downloaded from the genome list?
like 
https://www.patricbrc.org/portal/portal/patric/GenomeList?cType=taxon&cId=431269&dataSource=&displayMode=&pk=&kw=

I was able to confirm those isolation related fields (isolation source and isolation country) are present in the downloaded file.

**Comment by mshukla1** [comment]
checked, fixed.
