### ISSUE TITLE
Why can't I download BLAST results from BLAST table

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1500]
I am recording all the hit returns from BLAST.  Alas, when I try the download, it only gives me the information about the dumb genome!!!  I want the BLAST results.  Entering them manually is quite tedious, and I would like to spare our users this trying experience.

**Comment by hyoo** [comment]
![image](https://cloud.githubusercontent.com/assets/1236467/25680784/aca19636-3017-11e7-8e2c-8bdfbbc1a51a.png)

If you selected rows and used green bar download, then you're downloading your selection, which is genomes.

If you want to download entire result, then the download button on top of the grid is the button.
And here is the result.

**Comment by ARWattam** [comment]
Thanks.  Your email reminded me that you or Maulik showed me it before.
Sorry that I forgot that!
