### ISSUE TITLE
Trying to download specific results from BLAST downloads the whole table

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1501]
So here's the selection:
<img width="1173" alt="screen shot 2017-05-03 at 4 55 27 pm" src="https://cloud.githubusercontent.com/assets/11475316/25681190/706c7f64-3021-11e7-8615-561be0f0e63c.png">
But the downloads shows the whole table, and is not limited to the selection
<img width="955" alt="screen shot 2017-05-03 at 4 57 20 pm" src="https://cloud.githubusercontent.com/assets/11475316/25681240/9ae2def0-3021-11e7-8b1a-b5f1604addc5.png">

**Comment by mshukla1** [comment]
Downloading blast results for selection is not implemented. Rather, the selection supports actions 
related to features, i.e. download features, fasta, add to groups etc. 

Given that blast results are usually of small numbers (i.e. 50-100), downloading the entire table is probably 
fine.

-Maulik
