### ISSUE TITLE
When I open up the alignment in the BLAST returns, I see 2 alignments with very different scores

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1502]
The top alignment:
<img width="1102" alt="screen shot 2017-05-03 at 5 09 04 pm" src="https://cloud.githubusercontent.com/assets/11475316/25681690/40a714fe-3023-11e7-9049-77f71290de1a.png">
 And then I scroll down and see this little one:
<img width="1133" alt="screen shot 2017-05-03 at 5 08 02 pm" src="https://cloud.githubusercontent.com/assets/11475316/25681698/4b76e31e-3023-11e7-8c59-bf2f8774ab34.png">

Shouldn't there be only one?

**Comment by ARWattam** [comment]
Here's a better picture of the lower one:
<img width="1094" alt="screen shot 2017-05-03 at 5 10 13 pm" src="https://cloud.githubusercontent.com/assets/11475316/25681745/6f053df8-3023-11e7-9678-39912b9ed0d3.png">

**Comment by mshukla1** [comment]
It is a gapped alignment, hence there are two HSPs for the same alignment. The query matches the subject in two fragments, 
but the similarity is two low between the fragments to join them into one big alignment. 

This is typical of BLAST results, I don’t see any problem here. 

-Maulik
