### ISSUE TITLE
Another PLFam that crosses species bounds

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1503]
PLF_1763_00033211
<img width="1094" alt="screen shot 2017-05-04 at 10 55 58 am" src="https://cloud.githubusercontent.com/assets/11475316/25709817/5c1a5166-30b8-11e7-8b5c-88a3c8d90e9f.png">

**Comment by olsonanl** [comment]
This is also fixed in the new release.

GF01962151		fig|1834155.3.peg.1387	72	hypothetical protein	2231	Kocuria	2231

**Comment by mshukla1** [comment]
Corrected with the lated protein family updates. 


https://www.patricbrc.org/view/FeatureList/?eq(plfam_id,PLF_1763_00033211)#view_tab=features
