### ISSUE TITLE
Yet another PLFam that crosses genus boundaries

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1504]
PLF_1763_00001686
<img width="1106" alt="screen shot 2017-05-04 at 1 24 01 pm" src="https://cloud.githubusercontent.com/assets/11475316/25716432/03f539fa-30cd-11e7-9ea4-790f27ec000e.png">

**Comment by mshukla1** [comment]
This has been corrected with the recent protein family updates. 

https://www.patricbrc.org/view/FeatureList/?eq(plfam_id,PLF_1763_00001686)#view_tab=features
