### ISSUE TITLE
Diff Exp: header data file format 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1506]
The parser currently required the first column heading to the "Gene IDs". Several of my upload failed because I didn't have exactly the same column heading (I had "gene id" instead). 

I think, we should assume that the first column is gene id and first row is header as required by format and not rely on the column title. 

-Maulik

**Comment by mshukla1** [comment]
This is a silly error causing repeated failure for many users and cause of frustration. This needs to be addressed sooner. 

-Maulik

**Comment by chmao1** [comment]
@aswarren Could you comment on this issue as you implemented this feature? Thanks.

**Comment by aswarren** [comment]
@mshukla1 I find this not to be the case. There is explicit normalization for such cases.
Here is a recent example I got from you for mouse that works despite having "gene ids" as the column header. See data and results here https://patricbrc.org/workspace/anwarren@patricbrc.org/AndrewWarrenPublic/DiffExpTest

**Comment by chmao1** [comment]
@mshukla1  I tested using the "gene id" header as described in the issue and the import worked fine.  Could you check again to see whether it's still a problem for you?

**Comment by chmao1** [comment]
"Gene IDs" header works too

**Comment by mshukla1** [comment]
I tried geneid and it failed. Please make sure the regex being used can handle such variations. Or, rather, we should not rely on the label provided by the user for the first column at all.

**Comment by chmao1** [comment]
@mshukla1 @aswarren Is it safe to assume the first column is always gene id? If so, we don't need to validate this column header.

**Comment by chmao1** [comment]
I fixed it. Both gene list and gene matrix tables require the first column to be "Gene IDs", however, the program fails when users give different column header such as "gene", "accession id" etc to indicate gene ids. To handle this (based on Maulik's suggestion), the new fix assumes that the first column always indicates gene_id and ignores the user column header. I made the pull request. @aswarren please review the change and merge the change if it's okay.

**Comment by chmao1** [comment]
Fixed and waiting for the deployment in production

**Comment by chmao1** [comment]
The fix is available in the production website.
