### ISSUE TITLE
Bartonella elizabethae strain BeUM has no Pattyfams

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1508]
https://www.patricbrc.org/view/Genome/807.3#view_tab=proteinFamilies
<img width="1103" alt="screen shot 2017-05-10 at 6 10 28 pm" src="https://cloud.githubusercontent.com/assets/11475316/25923566/1c5a0c3a-35ac-11e7-83c4-0a899656fa19.png">

**Comment by mshukla1** [comment]
Both plfam and pgfams available for this genome now. 

<img width="1175" alt="screen shot 2017-06-09 at 3 36 09 pm" src="https://user-images.githubusercontent.com/1236463/26993599-6e12cbb8-4d29-11e7-9196-904c1700ac82.png">
