### ISSUE TITLE
Bartonella schoenbuchensis R1 strain R1 has no Pattyfams

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1509]
https://www.patricbrc.org/view/Genome/687861.3#view_tab=proteinFamilies
<img width="1144" alt="screen shot 2017-05-10 at 6 13 26 pm" src="https://cloud.githubusercontent.com/assets/11475316/25923630/67d3dec0-35ac-11e7-9ee3-5d09f427bec6.png">

**Comment by mshukla1** [comment]
Both plfam and pgfam are now available for this genome. 

<img width="1183" alt="screen shot 2017-06-09 at 3 32 33 pm" src="https://user-images.githubusercontent.com/1236463/26993505-f35cc360-4d28-11e7-96ba-b1622cbd37c0.png">
