### ISSUE TITLE
Need link to new Workspace documentation in the workspace page

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#151]
We need a message at the top of the page (similar to how we have text at the top of the Assembly and Annotation Service forms) that says something to the effect of, 

The PATRIC Workspace has a new look.  Information on how to use the new Workspace can be found here: http://enews.patricbrc.org/faqs/workspace-faqs/

**Comment by dmachi** [comment]
Link is on the right side of the green bar when user is in a workspace folder with nothing select (the default landing place for a workspace)
