### ISSUE TITLE
Vibrio parahaemolyticus strain CICESE-170 is missing PLFAMS

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1510]
https://www.patricbrc.org/view/Genome/670.1042#view_tab=features
<img width="1092" alt="screen shot 2017-05-11 at 1 08 18 pm" src="https://cloud.githubusercontent.com/assets/11475316/25962232/f1b45cca-364a-11e7-8467-9a3aca94e630.png">

**Comment by mshukla1** [comment]
both plfam and pgfams are now available for this genome. 


<img width="1127" alt="screen shot 2017-06-09 at 3 35 17 pm" src="https://user-images.githubusercontent.com/1236463/26993561-468ebcf0-4d29-11e7-89a8-f2aba778dfce.png">
