### ISSUE TITLE
Problem with blast

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1511]
I blasted against plasmid DNA and note the issue with genome names:

![image](https://cloud.githubusercontent.com/assets/7661533/26007256/42983250-3705-11e7-81a8-84ed94e17aa7.png)

**Comment by mshukla1** [comment]
Just to make sure I understand the issue, were you refering to the "Undefined" in the LHS panel? ...or something else? 

-Maulik

**Comment by hyoo** [comment]
I cannot reproduce this problem. If this happens again, please reopen this issue with detail steps and query sequence.
