### ISSUE TITLE
Specialty genes with Literature shows no PubMed ID

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1513]
In answering a user question, I filtered on Literature in Specialty Genes.  There was not PubMed id associated with that, and when I looked more closely, I saw that these were Human Homologs.  How in the world can there be Human Homologs with Literature tags, and if they do indeed exist, why don't we see the PubMed ID?

Here is the page I was on (Lactococcus garvieae:
https://www.patricbrc.org/view/Taxonomy/1363#view_tab=specialtyGenes&filter=eq(evidence,%22Literature%22)

<img width="1440" alt="screen shot 2017-05-15 at 7 05 43 am" src="https://cloud.githubusercontent.com/assets/11475316/26057071/7e25bf2e-393d-11e7-8fe4-347d1caadec7.png">

**Comment by mshukla1** [comment]
Having literature evidence for the human homolog was a mistake, it may have got added in the early day when we integrated the data and later got fixed. 

I have set evidence = BLASTP for all human homologs. 

I have cleaned up evidence for other sp genes as well.
