### ISSUE TITLE
Compare regions behaving strangely

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1516]
When I click on another protein in compare regions it does not refocus on that protien like it would at rast.

![image](https://cloud.githubusercontent.com/assets/7661533/26175501/7c4b43fe-3b18-11e7-9ae3-f647900f63c5.png)

**Comment by mshukla1** [comment]
In PATRIC compare region is displayed on the gene page. So, if you want make a different gene your focus, you would click on the gene id in the pop up, go to that gene page, and view compare region. 

In RAST or pubseed also it behaves the same way, i.e. if I click on any gene in compare region viewer, it will make me to the corresponding gene page for that gene. 

am I missing something?

**Comment by hyoo** [comment]
This is just different behavior. closing it.
