### ISSUE TITLE
Need stdout/stderr for completed jobs too

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1518]
The job viewer only allows viewing of stdout / stderr for failed jobs; there is possibly useful information  for completed jobs in those files too.

**Comment by nconrad** [comment]
I have a commit for this.  

Note that the default response is:

```
Unable to retreive additional details about this task at this task.
RequestError: Unable to load https://p3.theseed.org/services/app_service/task_info/fec34241-6ba0-424e-aea6-0b9b64de15f7/stdout status: 404
```  

![image](https://user-images.githubusercontent.com/1194246/30340973-f1e1a970-97b9-11e7-8bf7-1dfda115b326.png)
