### ISSUE TITLE
Filter buttons on genome selector are broken

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1519]
If I choose this:

<img width="491" alt="screen shot 2017-05-18 at 1 33 29 pm" src="https://cloud.githubusercontent.com/assets/2152226/26215518/9b3f035c-3bce-11e7-85bf-61ad08554244.png">

I see this in the console:

Query Filter set to: &and(eq(public,false),eq(public,true))

Also:

<img width="490" alt="screen shot 2017-05-18 at 1 35 44 pm" src="https://cloud.githubusercontent.com/assets/2152226/26215593/ebe608a0-3bce-11e7-96b7-c9d82ac77c14.png">

gives you:

Query Filter set to: &and(eq(public,false),eq(reference_genome,%22Reference%22),eq(reference_genome,%22Representative%22))

so these are entirely unusable

**Comment by zreyn** [comment]
Having just worked on this code, I definitely see what you're saying.  For the first example you provide (no check for public, no check for private) that was already there.  The reasoning I deduced is that if you don't ask us to include public and you don't ask us to include private, you don't get any results.

The same kind of applies to the second example.  If you don't want to reference or representative genomes, what genomes do you want?

Happy to fix it if you have a suggestion on how.  So, for both examples, what do you expect to get for results?

**Comment by aswarren** [comment]
Fixed in https://github.com/PATRIC3/p3_web/commit/a6554354dfab4e190e81c27daf6673f2792ee1c4
