### ISSUE TITLE
multiple sequence alignment doesn't work with 2-3 sequences

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#152]
The MSA tool crashes with a Java error when we try with 2 or 3 sequences.

**Comment by mshukla1** [comment]
With the new MSA viewer, it is working with just two sequences. Closing the ticket.

**Comment by olsonanl** [comment]
Cool!

On Jun 10, 2015, at 11:17 AM, mshukla1 <notifications@github.com<mailto:notifications@github.com>> wrote:


With the new MSA viewer, it is working with just two sequences. Closing the ticket.
