### ISSUE TITLE
Show files with unspecified type breaks Public view

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#1524]
![image](https://cloud.githubusercontent.com/assets/229173/26592974/71e0b7ce-4530-11e7-99df-dc88b29b65f6.png)
If you check the box things stop showing up in Public view until page refresh.
This isn't a show stopper for ASM since it is an uncommon workflow.

**Comment by nconrad** [comment]
ah, yes.  I don't think it's a public workspace issue, it's that the unspecified type checkbox doesn't work correctly on production either.

In any case, I've been wondering what that checkbox is used for?  It may be clearer to have a "show files with any type" checkbox instead?

**Comment by nconrad** [comment]
This was fixed when this checkbox was replaced with "show all files and folders".

![image](https://user-images.githubusercontent.com/1194246/34503094-45bba6fc-efdc-11e7-9fa9-492e77412a7d.png)
