### ISSUE TITLE
update account settings goes to different domain

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1525]
At ASM workshop, several users had trouble with this issue. 

They registered and logged in, then they went to user settings page. It goes to a different domain, and asks user to login again. Also, none of the links from the top nav work from this page. 

See the screenshot below. 
<img width="1440" alt="screen shot 2017-06-01 at 8 50 56 am" src="https://cloud.githubusercontent.com/assets/1236463/26683116/61d3c654-46a8-11e7-9c62-8ebe0c0a731d.png">

**Comment by hyoo** [comment]
1. we should remove top nav, because we cannot sync automatically. @dmachi please merge my pr
https://github.com/PATRIC3/p3_user/pull/2

2. once logged in on user.patricbrc.org, it should go to home page. i think.

**Comment by hyoo** [comment]
fixed and available on prod.
