### ISSUE TITLE
job submission: problem creating new output folder 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1526]
Several users had this problem. 

They are on assembly job submission page, click on folder icon next to output folder box, click on create new folder, nothing happens. 

These users just registered, so all they have are  special/default folders. Those are not visible in selection window. They can't create new folder, and they can't select home. 

The work around we came up with was to open another tab, create a new folder, then go to submission page and then select folder. 

This is critical issue while running workshop, needs to be fixed soon. 

-Maulik

**Comment by hyoo** [comment]
is it related to the Shock crash during the workshop?

**Comment by aswarren** [comment]
It doesn't seem so. Issue persists.

**Comment by aswarren** [comment]
@nconrad the behavior is similar to what is going on with the "show files of unspecified type" check box. Whose behavior I think we should maintain per our discussion the other day. 
After some thinking I think its best to maintain the "on-rails" functionality where the files shown match the type expected by the app. Though we could grey out non-specified types to make the case where someone has picked the wrong type more clear.

![image](https://cloud.githubusercontent.com/assets/229173/26694597/f730733c-46d5-11e7-92cb-6e9c76f07f40.png)

**Comment by nconrad** [comment]
This issue was fixed in newer branch (workspace 2.0)--didn't realize it was in the old branch.
