### ISSUE TITLE
ID Mapping from action bar missing id types

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1528]
While answering one of the user requests, I noticed that when I select ID mapping from the feature table action bar, it is missing some of the ID types present in the id_ref table in solr, for example, KO and STRING. 

Please make sure that the list of id types shown are generated from the data available in solr, either generated dynamically, or if cached, updated using the latest data. 

Also note that the list of id types displayed in the standalone ID Mapping Tool seems fine.

-Maulik

**Comment by JoshuaVSherman** [comment]
I was able to duplicate this issue

**Comment by JoshuaVSherman** [comment]
@mshukla1 neither the drop downs nor the table view are being dynamically generated, they are both hard-coded in the html file. I can fix the table display to include those missing items, but to make it all be dynamically generated would be some considerable effort. Please let me know if I should work on that request too, and then I would need information on the API endpoint where I could fetch. Thanks

**Comment by JoshuaVSherman** [comment]
@mshukla1 I created this ticket to address your request for a more dynamic generation of the id types https://github.com/PATRIC3/patric3_website/issues/1882
