### ISSUE TITLE
Data missing when drill into genome browser

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#153]
I was looking at:
fig|1773.173.peg.4048

And when I tried to look at it on the genome browser this was returned (see screenshot)
![screen shot 2015-04-13 at 4 11 49 pm](https://cloud.githubusercontent.com/assets/11475316/7124567/0fbb8bf2-e1f8-11e4-9716-e3e70faf4906.png)

**Comment by ARWattam** [comment]
And here's another one:
![screen shot 2015-04-13 at 4 16 19 pm](https://cloud.githubusercontent.com/assets/11475316/7124615/7ce28906-e1f8-11e4-8de0-2a13096b95ce.png)

**Comment by rkenyon** [comment]
Rebecca,

Did you mean to close this ticket?

Ron

Ron Kenyon
PATRIC Project Manager, patricbrc.org
Project Management Director
Virginia Bioinformatics Institute, Virginia Tech
Ph: 540-231-7470

**Comment by hyoo** [comment]
Maulik, this feature belongs to a genome (genome_id:1773.173) below, 

http://macleod.vbi.vt.edu:8080/solr/genome/select?q=genome_id:1773.173

but we're missing sequence

http://macleod.vbi.vt.edu:8080/solr/genome_sequence/select?q=genome_id:1773.173

any idea?

**Comment by mshukla1** [comment]
Fixed. All bad genomes without genomic sequences were removed and reloaded in the database.
