### ISSUE TITLE
Workspace problem

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1532]
Someday I'd like to be able to rename a file.  Now I have to reupload everything.
![image](https://user-images.githubusercontent.com/7661533/27153227-3f71c8cc-5116-11e7-8b88-33bfe1c8965f.png)

**Comment by mshukla1** [comment]
Neal is working on workspace copy / move / rename / delete functionality right now. It is almost complete and will be deployed on alpha soon, where you can test it. 

-Maulik

**Comment by nconrad** [comment]
Note: maulik discovered a bug on alpha regarding renaming objects/folders.  We'll deploy the fix tomorrow.

**Comment by hyoo** [comment]
it is on alpha now.

**Comment by nconrad** [comment]
That was fast, thanks!
