### ISSUE TITLE
download file names have to be changed

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1533]
One of my greatest pet peeves using this site is the generic file name given to every single patric download.  I currently have 10 differential expression analysis data sets that I am trying to download and they are all getting the same file name.  Very annoying.  So bad.

**Comment by mshukla1** [comment]
The default download files are usually names based on the page you download it from, i.e. PATRIC_genome, PATRIC_genome_amr, PATRIC_features, etc. 

However, it is your browser setting that controls weather you want to automatically same files with the default name or you want to be prompted for location / name before saving each file. The latter will allow you to change the name as you wish before you save the file. If you download multiple files with same names and don't change them, usually your browser saves them with a suffix added. 

Given that the files can be downloaded from anywhere on the site, from any context, and applying any number of filters, it will be hard to come up with a naming scheme that will capture what is being downloaded in a meaningful way. 

If you have any recommendations on how the files should be named, we can certainly consider them. 

-Maulik

**Comment by hyoo** [comment]
Since users browser setting overwrites our implementation, we  cannot fix anything here. closing.
