### ISSUE TITLE
MSA: show/hide cols and rows by threshold 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1536]
Andrew, 

The BioJS MSA viewer demo page provides ability to show / hid columns based on conservation threshold and sequences based on identity. This is crucial to allow users to visually analyze NA alignment of near identical genes and quickly detect SNPs without scrolling and looking at each and every column. 

http://output.jsbin.com/xurabajicu/1

<img width="519" alt="screen shot 2017-06-21 at 4 19 35 pm" src="https://user-images.githubusercontent.com/1236463/27407553-61033fe2-569e-11e7-8baa-cdf4ea92a78e.png">

**Comment by chmao1** [comment]
The enhancement is available on alpha for testing. Currently, we support show/hide cols not rows.
