### ISSUE TITLE
Seeing two versions of same genome in one Genome Browser view

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#154]
I was looking at the following gene:
fig|33894.6.peg.1712 

And when I open the genome browser I see two copies of the genome in the same view (version 4 and version 6)
![screen shot 2015-04-13 at 4 56 30 pm](https://cloud.githubusercontent.com/assets/11475316/7125349/286c75a2-e1fe-11e4-821e-8798574e68a2.png)

**Comment by mshukla1** [comment]
I believe the issue has been resolved. 
![screen shot 2015-06-10 at 10 34 21 am](https://cloud.githubusercontent.com/assets/1236463/8085072/4f75872a-0f5c-11e5-9fe5-13951a04b3c5.png)
