### ISSUE TITLE
Filtering in features tab not working

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1540]
If I bring up a feature list, say 

https://www.patricbrc.org/view/Genome/371601.6#view_tab=features&filter=and(or(eq(annotation,%22PATRIC%22)),or(eq(feature_type,%22crispr_repeat%22),eq(feature_type,%22crispr_spacer%22)))

and I click around in the filters, the list of features does not change.

**Comment by zreyn** [comment]
Looks like the filters are working in production now, so I can't reproduce this.  Please re-open if the same behavior is exhibited.
