### ISSUE TITLE
Assembly: fetch reads directly from SRA

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1541]
Downloading reads from NCBI SRA locally and then uploading them to workspace take lot of time and effort and it is very frustrating. 

We should allow users to just provide SRA run accession number as an input option and then fetch the reads directly from SRA using fastq-dump program. 

https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=fastq-dump

Below is the sample command I use to fetch paired end read files, given an SRA run accession. 

fastq-dump -I --split-files --gzip SRR5660160

-Maulik

#554

**Comment by levinas** [comment]
@aswarren Could you take a look at my proposed spec change? https://github.com/TheSEED/app_service/pull/71

If you can add an input box for SRR IDs that is on the same level as PE/SE boxes, that would be great. As @mshukla1  suggested, the backend tweak should be straightforward.

**Comment by mshukla1** [comment]
There is an option in fast-q dump for removing all technical sequences, i.e. adapters etc. 

--skip-technical	Dump only biological reads
fastq-dump -I --skip-technical --split-files --gzip SRR5660159

When I downloaded reads without that option and assembly service was having hard time trying to assemble them.

**Comment by mshukla1** [comment]
This has been addressed and the solution is already deployed on the production website. 

-Maulik
