### ISSUE TITLE
Impossible to identify genome groups in Protein Family Sorter

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1543]
I originally thought that the PFS, when comparing two groups, ordered them so that one group followed the other.  In that way, users could figure out the patterns based on that order.  I just created 2 groups, each about having 50 genomes, and was trying to see them using the PFS.  I was dismayed to find that they are not ordered that way, but instead ordered alphabetically.  This makes the tool absolutely useless for comparing groups that are any larger than about 10 genomes.  The user is forced to create lists of the genomes, and only in the heatmap view can they order them together.  Any reasonable user would quickly be disgusted by this.  Please, PLEASE identify the groups and allow users to see that!!!

**Comment by rkenyon** [comment]
Per Rebecca: Most important issue to resolve from her open issues.

**Comment by mshukla1** [comment]
#1030 duplicate.
