### ISSUE TITLE
NDARO is still missing

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1547]
![image](https://user-images.githubusercontent.com/7661533/27915385-c5606468-622b-11e7-8935-42ff2c0a52b3.png)

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/29634154-76262794-880e-11e7-8e50-1a969c4a52b1.png)

now we have it on production.

https://www.patricbrc.org/view/Genome/83332.12#view_tab=overview
