### ISSUE TITLE
publication should be listed with phenotype

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1551]
Since we are recording the papers with the phenotypes of the genomes the NCBI ID  should be an available column.  I don't know if that is what is intended by "source", but in this instance that column is empty.

![image](https://user-images.githubusercontent.com/7661533/27915612-7ea81d4e-622c-11e7-83f8-798f201aa8b6.png)

**Comment by rkenyon** [comment]
Jim triage comment: High.  This is one of the only things from the AMR table that is not offered.  It would be very good to get this in.
