### ISSUE TITLE
Missing genome

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1552]
This genome should be public in PATRIC, but it is missing:

1349.117 | Streptococcus uberis PE302

It is part of the group from Julian Reyes that he released in PATRIC independently

**Comment by mshukla1** [comment]
When I made 88 genomes from the user public, I somehow missed just this one...perhaps because it was the last one on the list and I didn't copy the list carefully. I have made it public and it can be accessed on the website now. 

-Maulik
