### ISSUE TITLE
error in filename change

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1554]
I tried to rename my file and i got this error message in dialog, but file changed successfully.

However, i tried again to reproduce it but i couldn't. Should I worry about this?

@nconrad 
And the title of dialog was "Oh no!"  something like that. Please change to be more professional. 

=======

_ERROR_Overwriting object /harry@patricbrc.org/home/MyTestContig_empty.fna and overwrite flag is not set!_ERROR_ Trace begun at /disks/p3/deployment/lib/Bio/P3/Workspace/WorkspaceImpl.pm line 143 Bio::P3::Workspace::WorkspaceImpl::_error('Bio::P3::Workspace::WorkspaceImpl=HASH(0x42e1fa8)', 'Overwriting object /harry@patricbrc.org/home/MyTestContig_empty.fna and overwrite flag is not set!') called at /disks/p3/deployment/lib/Bio/P3/Workspace/WorkspaceImpl.pm line 727 Bio::P3::Workspace::WorkspaceImpl::_validate_save_objects_before_saving('Bio::P3::Workspace::WorkspaceImpl=HASH(0x42e1fa8)', 'ARRAY(0x5d37aa8)', 0) called at /disks/p3/deployment/lib/Bio/P3/Workspace/WorkspaceImpl.pm line 593 Bio::P3::Workspace::WorkspaceImpl::_copy_or_move_objects('Bio::P3::Workspace::WorkspaceImpl=HASH(0x42e1fa8)', 'ARRAY(0x4dc2a00)', 0, 'JSON::PP::Boolean=SCALAR(0x1604030)', 'JSON::PP::Boolean=SCALAR(0x1604030)') called at /disks/p3/deployment/lib/Bio/P3/Workspace/WorkspaceImpl.pm line 2789 Bio::P3::Workspace::WorkspaceImpl::copy('Bio::P3::Workspace::WorkspaceImpl=HASH(0x42e1fa8)', 'HASH(0x4b5de60)') called at /disks/p3/deployment/lib/Bio/P3/Workspace/Service.pm line 377 eval {...} at /disks/p3/deployment/lib/Bio/P3/Workspace/Service.pm line 369 Bio::P3::Workspace::Service::call_method('Bio::P3::Workspace::Service=HASH(0x42e2140)', 'HASH(0x5cd96a0)', 'HASH(0x5cd8c50)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/RPC/Any/Server.pm line 34 eval {...} at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/RPC/Any/Server.pm line 27 RPC::Any::Server::handle_input('Bio::P3::Workspace::Service=HASH(0x42e2140)', 'HASH(0x5e2f778)') called at /disks/p3/deployment/lib/Workspace.psgi line 21 Plack::Sandbox::_2fdisks_2fp3_2fdeployment_2flib_2fWorkspace_2epsgi::__ANON__('HASH(0x5e2f778)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/App/URLMap.pm line 71 Plack::App::URLMap::call('Plack::App::URLMap=HASH(0x437ff28)', 'HASH(0x5e2f778)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Component.pm line 50 Plack::Component::__ANON__('HASH(0x5e2f778)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Middleware/CrossOrigin.pm line 176 Plack::Middleware::CrossOrigin::call('Plack::Middleware::CrossOrigin=HASH(0x437fec8)', 'HASH(0x5e2f778)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Component.pm line 50 Plack::Component::__ANON__('HASH(0x5e2f778)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Middleware/AccessLog.pm line 24 Plack::Middleware::AccessLog::call('Plack::Middleware::AccessLog=HASH(0x1544e38)', 'HASH(0x5e2f778)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Component.pm line 50 Plack::Component::__ANON__('HASH(0x5e2f778)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Util.pm line 142 eval {...} at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Util.pm line 142 Plack::Util::run_app('CODE(0x1544f10)', 'HASH(0x5e2f778)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Starman/Server.pm line 281 Starman::Server::process_request('Starman::Server=HASH(0x119e6f8)', 'Net::Server::Proto::TCP=GLOB(0x49e0000)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server.pm line 74 Net::Server::run_client_connection('Starman::Server=HASH(0x119e6f8)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server/PreFork.pm line 229 eval {...} at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server/PreFork.pm line 229 Net::Server::PreFork::run_child('Starman::Server=HASH(0x119e6f8)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server/PreFork.pm line 187 Net::Server::PreFork::run_n_children('Starman::Server=HASH(0x119e6f8)', 5) called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server/PreFork.pm line 111 Net::Server::PreFork::loop('Starman::Server=HASH(0x119e6f8)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server.pm line 60 Net::Server::run('Starman::Server=HASH(0x119e6f8)', 'port', 'ARRAY(0x14e37b0)', 'host', '*', 'proto', 'tcp', 'serialize', 'none', 'min_servers', 5, 'min_spare_servers', 4, 'max_spare_servers', 4, 'max_servers', 5, 'max_requests', 1000, 'user', 30220, 'group', '30220 30220 45056', 'listen', 1024, 'check_for_waiting', 1, 'no_client_stdout', 1, 'pid_file', '/disks/p3/deployment/services/Workspace/service.pid', 'setsid', 1, 'background', 1, 'log_file', '/disks/p3/deployment/services/Workspace/error.log') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Starman/Server.pm line 89 Starman::Server::run('Starman::Server=HASH(0x119e6f8)', 'CODE(0x119e5d8)', 'HASH(0x119e2f0)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Handler/Starman.pm line 18 Plack::Handler::Starman::run('Plack::Handler::Starman=HASH(0x119e698)', 'CODE(0x119e5d8)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Loader/Delayed.pm line 20 Plack::Loader::Delayed::run('Plack::Loader::Delayed=HASH(0xf46d90)', 'Plack::Handler::Starman=HASH(0x119e698)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Runner.pm line 277 Plack::Runner::run('Plack::Runner=HASH(0xf8bd10)') called at /disks/p3/runtime/bin/starman line 38

**Comment by nconrad** [comment]
I could not replicate this.  I have some commits to the error handling for consistency, but let me know if you see this issue again.
