### ISSUE TITLE
Icon for global search

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#1560]
Suggesting to use the "icon-search" magnifying glass, instead of "icon-search-plus", just because the "-plus" icon is typically used for "zoom in".

![image](https://user-images.githubusercontent.com/1194246/27916280-365fc102-622e-11e7-9401-f20665b3bb94.png)

**Comment by chmao1** [comment]
#1556

**Comment by chmao1** [comment]
Fixed and available on alpha for testing.

**Comment by chmao1** [comment]
available in production.
