### ISSUE TITLE
Unable to launch MSA from feature group in production from feature group

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1562]
The MSA icon does not appear in the mystical green bar when I select my feature group for 40 genes

**Comment by dawenx** [comment]
Can you provide a screen shot on where you want to launch MSA? There's no problem to launch it from Feature List View page, but that's probably not what you mean.

**Comment by mshukla1** [comment]
@dawenx here is the screenshot. Can you please add MSA button in the green bar when a single feature group is selected? 

<img width="1373" alt="Screen Shot 2019-04-15 at 8 03 58 PM" src="https://user-images.githubusercontent.com/1236463/56174770-c75f2280-5fb9-11e9-8944-114b488ef126.png">

**Comment by dawenx** [comment]
ok, i will work on it.

**Comment by dawenx** [comment]
i'm working on this. a bit involved actually, but on target for May release.

**Comment by dawenx** [comment]
This is on alpha, please verify and close. @ARWattam

**Comment by ARWattam** [comment]
Verified that it is on alpha and that it works great.  We should move to production asap
