### ISSUE TITLE
protein family should be a first-class search object:

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1564]
![image](https://user-images.githubusercontent.com/7661533/27916863-f5f002d8-622f-11e7-98a7-730f1833888f.png)

**Comment by hyoo** [comment]
have you tried genome features? protein family is an attribute of genomic features. we cannot list all the possible field names.

**Comment by hyoo** [comment]
search by protein family id works as is.

https://www.patricbrc.org/search/?keyword(%22PLF_1763_00000002%22)

![image](https://user-images.githubusercontent.com/1236467/30496995-cde1cbc2-9a16-11e7-9d45-431dfdeb86b6.png)
