### ISSUE TITLE
Action bar icons missing on Alpha (3.3.16falpha) for features

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1566]
Select a set of genes, no icons appear.
https://www.alpha.patricbrc.org/view/Genome/83332.12#view_tab=features&filter=and(eq(feature_type,CDS),eq(annotation,PATRIC))

![screen shot 2017-07-06 at 10 54 35 am](https://user-images.githubusercontent.com/3188570/27917271-8e9ab876-6239-11e7-8a64-58331379d3d9.png)

**Comment by hyoo** [comment]
cannot reproduce this. how many features were selected?

**Comment by rkenyon** [comment]
9 (nine), as shown in the screen shot

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/27920651-f0251c70-623a-11e7-9dd4-64356d0fe693.png)

Still cannot reproduce it.

**Comment by hyoo** [comment]
yes, this was due to the bug introduced by workspace2.0. The grid selection was not working when you logged out. It worked for me, since i was logged in. We have addressed this issue and available on alpha.
