### ISSUE TITLE
Download MSA.png does not show the entire alignment

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1567]
Nucleotide msa and click on download msa.png.  Only shows about 60 nts, but this is not even close to the whole alignment
![patric_msa](https://user-images.githubusercontent.com/11475316/27917409-e5af3650-6239-11e7-9a8c-b7387d722db5.png)

**Comment by chmao1** [comment]
Downloading MSA.png is no longer provided upon the request. Closing this ticket for now.
