### ISSUE TITLE
MSA selection PNG is only a screenshot of the viewed alignment, no the whole thing.

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1570]
This bug is true when you have the genes selected or if you try to download the whole alignment.

![image](https://user-images.githubusercontent.com/7661533/27917709-6cd86e4c-6232-11e7-82e6-b1a6f84e7f7f.png)

**Comment by chmao1** [comment]
#1567

**Comment by chmao1** [comment]
Downloading MSA.png is no longer provided upon the request. Closing this ticket for now.
