### ISSUE TITLE
visualization on workspace

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1571]
Note the buttons in the top right overlapping the pane.  Clicking hide and show made it render correctly.

![image](https://user-images.githubusercontent.com/7661533/27918017-505aaa0e-6233-11e7-8c5b-9fc2a2e1a94c.png)

**Comment by hyoo** [comment]
@nconrad would you take a look?

**Comment by rkenyon** [comment]
Jim triage comment: I think this might be closed. I couldn't reproduce the bug.
