### ISSUE TITLE
workspaces should be visible from the dropdown

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1572]
I have 2 workspaces, but i cant see them both in the dropdown.  This is the assembly app.

![image](https://user-images.githubusercontent.com/7661533/27918219-dd398bfc-6233-11e7-8164-5d8d9bfa1a18.png)

**Comment by hyoo** [comment]
this was because, i guess, default select "Worksapce" was looking at home directory and Jim was looking for his new workspace "For_Rebecca". 

And he was toggling between workspaces and Public workspaces but it wasn't show up until he clicked "parent".
