### ISSUE TITLE
Data not available through link on Specialty Genes data page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#158]
When I am at this page:
https://www.patricbrc.org/portal/portal/patric/SpecialtyGenes

And I try to follow the link to either VFDB or Victors, a page pops up that says the data is not available.
![screen shot 2015-04-16 at 10 37 06 am](https://cloud.githubusercontent.com/assets/11475316/7183332/ce755db0-e424-11e4-9264-787b0d4897d1.png)

**Comment by hyoo** [comment]
another issue of https vs http conflict. I may have to specify the protocol. I will work on it, in the mean time, you can modify the url (change from https://www.mgc.ac.cn/VFs/ to http://www.mgc.ac.cn/VFs/)

**Comment by hyoo** [comment]
This is fixed and available on production site. Please double check and close this issue.
