### ISSUE TITLE
sequence tab: link genome id to genome overview page

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1586]
From the sequence tab, when I select a sequence and look at the summary panel on right, the genome id is not linked to the corresponding genome overview page. 

-Maulik

<img width="1439" alt="screen shot 2017-07-11 at 11 20 31 pm" src="https://user-images.githubusercontent.com/1236463/28101688-be8bc26e-668f-11e7-9f94-4299d595a6dd.png">

**Comment by dawenx** [comment]
Just wanted to make sure: currently user can click on "Genome" button on the action bar to go to genome overview page and you want the add link to genome id on the summary panel to go to the same genome overview page?

**Comment by dawenx** [comment]
Got it, will work on it.

**Comment by dawenx** [comment]
this is fixed, pull request to develop branch submitted.
