### ISSUE TITLE
Is Borreliella a new Borrelia?

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1587]
I was reading about lyme disease this morning and became curios about how many borrelia genomes we have. So went to,

https://www.patricbrc.org/view/Taxonomy/138#view_tab=overview

and found no Borrelia burgdorferi. But when i do a global search

https://www.patricbrc.org/search/?and(keyword(Borrelia),keyword(burgdorferi))

I found 48 Borrelia burgdorferi genomes.

And here is why,

https://www.patricbrc.org/view/Taxonomy/1643685#view_tab=taxontree

There are two genus named Borrelia (taxon id: 138) and Borreliella (taxon id: 64895) having 26 and 109 genomes respectively. 

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=138&lvl=3&lin=f&keep=1&srchmode=1&unlock

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=64895&lvl=3&lin=f&keep=1&srchmode=1&unlock

So, question is, how should handle this? should merge them? or replace the link?

If user just browse Organisms tabs, they might think we don't host any Borrelia burgdorferi.
And this can be a problem for browsing genomes in app services.

**Comment by hyoo** [comment]
https://atlasofscience.org/lyme-disease-causing-borrelia-are-genetically-distinct-from-their-relapsing-fever-causing-cousins/

it says, borreliella is a group of lyme-disease casuing borrelia genomes.

**Comment by mshukla1** [comment]
Harry, we have known about this taxonomy change for about a year now, I send out an email 
when it happened. But, we didn't take any specific actions on the website. 

I think correct thing to do it to replace "Borrelia" with "Borreliella" in the the organism menu in the top nav bar. 

We can ask Rebecca / Veronika during Jam session and make the change if no objections. 

-Maulik

**Comment by mshukla1** [comment]
BTW, data is fine and as expected. There is no change needed on from the data side. 

-Maulik

**Comment by hyoo** [comment]
I will change to Borreliella.
