### ISSUE TITLE
I cant see the STDERR output of a failed job

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1588]
Note that it is rendered offscreen and i cannot make the window wide enough to see it.

![image](https://user-images.githubusercontent.com/7661533/28167465-556d0b18-67a1-11e7-827a-ee597480e07d.png)

**Comment by hyoo** [comment]
it would be better to show message in dialog, or provide an options to "copy to clipboard"

**Comment by nconrad** [comment]
I think the error dialogs were moved to these panels not that long ago, maybe by @aswarren (?).  I'm not sure how much a dialog would help anyway, so I left those as is, but made text horizontally scrollable and also added a "copy to clipboard" button, which appears after the panel is expanded:

![image](https://user-images.githubusercontent.com/1194246/30504869-b82f807e-9a36-11e7-890f-c4d928228ed6.png)

Think this is good? 

It may still be helpful if the stdout returned didn't use 8 spaces for tabs or whatever is happening there.  Tagging @olsonanl

**Comment by olsonanl** [comment]
Being able to slide the window size is helpful, if you know how to do it. I still like the notion of a "copy to clipboard" or "save as".

Stdout uses what stdout uses; it is entirely up to to whatever application is running. I'm not sure why it matters if it uses spaces or tabs.

**Comment by nconrad** [comment]
@olsonanl, yeah, you should already be able to slide the window size.  I added the scrollbar in addition to that.  It's on alpha if want to test it out.

Makes sense @ stdout spacing.
