### ISSUE TITLE
I'd like to be able to copy and paste path names from the workspace

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1589]
I can't highlight and copy the path.  Or a  the contents of a cell in the table.

![image](https://user-images.githubusercontent.com/7661533/28168219-ffc2f418-67a3-11e7-8899-020ae640f4a1.png)

**Comment by dmachi** [comment]
You can copy both of these pieces of data from the detail panel on the right.




Dustin

**Comment by nconrad** [comment]
Dustin is right, but we should be able to change the `user-select` attribute to "text" on just the workspace breadcrumb, allowing for copy/paste.  Dustin let me know if this change isn't ok.  

`user-select` is `none` on the container (BrowserHeader) for some reason... but I'll leave that as is in fear of breaking something else.

**Comment by nconrad** [comment]
So, I looked into this and made the breadcrumb path selectable.  Making the text in the folder/file list selectable seems to be non-trivial since the text would be selected while double clicking (to navigate into a folder).  Disabling text selection like this is fairly common.
