### ISSUE TITLE
PATRIC AMR genes are not visible on Specialty genes tab

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1591]
![image](https://user-images.githubusercontent.com/7661533/28173924-98494a46-67b5-11e7-870d-b99b69f216ba.png)

**Comment by hyoo** [comment]
which genome is this? would you add a url so that I can see it?

**Comment by mshukla1** [comment]
PATRIC AMR genes are displayed under specialty gene tab, when available for a genome. Below is an example for Mtb H37rv genome. 

<img width="1119" alt="screen shot 2017-09-15 at 9 58 55 am" src="https://user-images.githubusercontent.com/1236463/30489313-8d8647ac-99fc-11e7-9f95-befaa4e4315c.png">
