### ISSUE TITLE
"Specialty Genes" tab should be renamed "Specialty Proteins"

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1592]
Note that the left-hand column is all BLASTP.

![image](https://user-images.githubusercontent.com/7661533/28173944-a91caa16-67b5-11e7-846c-9a77ce0ed2b0.png)

**Comment by mshukla1** [comment]
It is not all blastp anymore. we do have essential genes predicted by flux balance analysis and now PATRIC AMR genes predicted based on k-mer search. 

We have been calling it "specialty genes" for more than 5 years now and has been mentioned in multiple publications. It doesn't make much sense to change it at this point.

**Comment by mshukla1** [comment]
besides, genes and proteins are often used interchangeably when it comes to microbes.
