### ISSUE TITLE
Phylogeny: Downloading Tree SVG gives wrong image

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1595]
For example: downloading tree SVG from the page https://www.patricbrc.org/view/Taxonomy/1763#view_tab=phylogeny
gave the wrong image:

![image](https://user-images.githubusercontent.com/6361802/28273055-3d07e6c8-6adb-11e7-8f60-725a79112a84.png)

**Comment by chmao1** [comment]
After refreshing the page, the correct tree is downloaded. However the format looked weird.
![image](https://user-images.githubusercontent.com/6361802/28273913-805e43a2-6add-11e7-9c95-2bd258e2d1b1.png)

**Comment by mshukla1** [comment]
Strange! 

When I downloaded SVG, I did get phylogenetic tree, but it looks horrible!! :(

**Comment by chmao1** [comment]
The wrong image only happens when you load the phylogeny tab for the first time.

**Comment by hyoo** [comment]
fixed by
https://github.com/PATRIC3/p3_web/commit/926bcbe2f01ab48526cfe8b23ddf692c51c93ec3
