### ISSUE TITLE
Workspace: can't access job result after moving to a different location

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1597]
....adding here for tracking. 

Neal, 

I did some data analysis for our collaborator in Thailand. 
I created a directory in my home workspace, uploaded reads, 
and then assembled and annotated their genomes. 

I wanted to share this folder with them. So, I moved it to my 
the root folder as another workspace. After that, I when to that 
new workspace and clicked on one of my job result file, the job 
result page never loads. However, if I add a . in front of the job folder, 
I can see that all job result files are there in the hidden result folder. 

Can you try this and see what is going on? If it doesn’t work as expected, 
I think it is a critical bug that needs to be fixed before the release. 

-Maulik

**Comment by dmachi** [comment]
The Job Listing only has the path to the filename/location where the Job was originally saved to.  Once moved, that path will no longer be the same and any linking to it will fail.   There is currently no way to update a Job reference (from the app_service) to associate it with a new location.

The best short term fix we can accomplish would be to disallow ‘move’ for JobResults.  We could still allow copy.

Dustin

**Comment by nconrad** [comment]
Right.  Bob says the job result viewer should alleviate this issue--I assume by using relative paths and listing all the contents of the .folder instead?

**Comment by dmachi** [comment]
From Job Results file using a relative link to the . folder works.  But from the Job list (/Jobs) it doesn’t know a path to the Job File itself.  It gets that information from the parameters supplied to launch the Job.

**Comment by mshukla1** [comment]
<img width="1070" alt="screen shot 2017-07-18 at 11 31 47 am" src="https://user-images.githubusercontent.com/1236463/28328651-d174fbbc-6bac-11e7-9f8e-8f29294d00dc.png">

**Comment by dmachi** [comment]
What are we supposed to see in this image Maulik?

**Comment by mshukla1** [comment]
The job header part is not being displayed, i.e. job start / end times, and list of parameters. 

I have shown it to both Zane and Neal.

**Comment by zreyn** [comment]
Looking into this more, Dustin is right.  This is not fixable by relative paths.  I think we'd have to copy or create a link to the original job file when moving.  I don't think either are a particularly good idea.

We could potentially put a band-aid on this by having the JRV recognize it and put a better message to the user (i.e. this job was run from another workspace) or preventing the move of job files.

**Comment by nconrad** [comment]
Update:  @zreyn, @dmachi, and I talked about this and they came up with a fix.  @zreyn should have a PR before the release tomorrow.

**Comment by zreyn** [comment]
Chatted with Dustin and Neal and agreed upon relying on the accompanying hidden folder. 
 https://github.com/PATRIC3/p3_web/pull/491

**Comment by nconrad** [comment]
Looks great!
