### ISSUE TITLE
Unable to load feature group in alpha

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1598]
I tried to load one of my feature groups and got the following error

VM43:452 Mixed Content: The page at 'https://www.alpha.patricbrc.org/' was loaded over HTTPS, but requested an insecure image 'http://enews.patricbrc.org/wp-content/uploads/2017/06/2012_Duke_UNC1_SMALL.png'. This content should also be served over HTTPS.
VM43:475 Mixed Content: The page at 'https://www.alpha.patricbrc.org/' was loaded over HTTPS, but requested an insecure image 'http://enews.patricbrc.org/wp-content/uploads/2017/05/ICSB-2017-logo.png'. This content should also be served over HTTPS.
VM43:496 Mixed Content: The page at 'https://www.alpha.patricbrc.org/' was loaded over HTTPS, but requested an insecure image 'http://enews.patricbrc.org/wp-content/uploads/2017/06/PATRIC-100000-Genomes.png'. This content should also be served over HTTPS.
VM43:515 Mixed Content: The page at 'https://www.alpha.patricbrc.org/' was loaded over HTTPS, but requested an insecure image 'http://enews.patricbrc.org/wp-content/uploads/2014/05/AR_carousel.jpg'. This content should also be served over HTTPS.
VM43:533 Mixed Content: The page at 'https://www.alpha.patricbrc.org/' was loaded over HTTPS, but requested an insecure image 'http://enews.patricbrc.org/wp-content/uploads/2013/05/Mycobacterium_tuberculosis_14313982_1.jpg'. This content should also be served over HTTPS.
VM43:651 Mixed Content: The page at 'https://www.alpha.patricbrc.org/' was loaded over HTTPS, but requested an insecure image 'http://enews.patricbrc.org/wp-content/uploads/2015/03/Assembly-thumb-100x75.png'. This content should also be served over HTTPS.
VM43:666 Mixed Content: The page at 'https://www.alpha.patricbrc.org/' was loaded over HTTPS, but requested an insecure image 'http://enews.patricbrc.org/wp-content/uploads/2012/03/protein_family_sorter_for_homepage_tool.png'. This content should also be served over HTTPS.
VM43:685 Mixed Content: The page at 'https://www.alpha.patricbrc.org/' was loaded over HTTPS, but requested an insecure image 'http://enews.patricbrc.org/wp-content/uploads/2012/03/collage-100x75-05.png'. This content should also be served over HTTPS.
VM43:705 Mixed Content: The page at 'https://www.alpha.patricbrc.org/' was loaded over HTTPS, but requested an insecure image 'http://enews.patricbrc.org/wp-content/uploads/2012/05/Genome-Annotation-thumb-100x70.png'. This content should also be served over HTTPS.
VM43:715 Mixed Content: The page at 'https://www.alpha.patricbrc.org/' was loaded over HTTPS, but requested an insecure image 'http://enews.patricbrc.org/wp-content/uploads/2012/03/comparative_pathways_for_homepage_tool.png'. This content should also be served over HTTPS.
VM43:727 Mixed Content: The page at 'https://www.alpha.patricbrc.org/' was loaded over HTTPS, but requested an insecure image 'http://enews.patricbrc.org/wp-content/uploads/2013/06/gene_page_homepage_tool.jpg'. This content should also be served over HTTPS.
dojo.js.uncompressed.js:324 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
s.getText @ dojo.js.uncompressed.js:324
2p3.theseed.org/services/Workspace Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by hyoo** [comment]
s.getText @ dojo.js.uncompressed.js:324
2p3.theseed.org/services/Workspace Failed to load resource: the server responded with a status of 500 (Internal Server Error)

this is relevant error. Others are related to home page.

**Comment by dawenx** [comment]
@ARWattam i'm wondering whether this was a temporary issue at the time, do you still have this problem?

**Comment by nconrad** [comment]
Bump. I'm wondering the same.

**Comment by nconrad** [comment]
Obsolete
