### ISSUE TITLE
svg file for tree download has weird branches

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1599]
I expected to see a standard tree, but what I saw was this:
<img width="404" alt="screen shot 2017-07-18 at 9 46 20 am" src="https://user-images.githubusercontent.com/11475316/28323364-2e1b2364-6b9e-11e7-8698-6cb15c53aa14.png">

**Comment by hyoo** [comment]
fixed by
https://github.com/aswarren/phyloview/commit/d7c2dfd075d93100a3a54bb2c1710d4dbf2dbfb5

and available on alpha.
