### ISSUE TITLE
MSA: use patric ids / refseq locus tags in downloads

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1605]
When I download MSA in clustal or fasta format, it contains internal feature ids, which are not that meaningful for the users. 

Please use patric_id and/or refseq_locus_tag instead. 

The same applies to the tree newick download as well.

-Maulik

**Comment by chmao1** [comment]
Fixed and available on alpha

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/29632617-23a3281e-8809-11e7-9cb4-2dcbb56eb185.png)

confirmed from production.
