### ISSUE TITLE
my job file disappeared after changing name!

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1612]
I was testing renaming again. here is a list of actions

1. select one of my job ("my second job") and click "rename" button
2. in the dialog, i changed it to "my second job2" and double clicked "rename" button. yes, intentionally double clicked.
3. saw the file name changed correctly. so far so good.
4. i wanted to change back. clicked "my second job2" and removed 2 at the end. click "rename" button once.
5. got an error that there is a file name "my second job" so, i need to choose a unique name. Weird, there no such name.
6. clicked "show hidden" button
7. find that .my second job folder. I am not sure whether this was there after changing file name or just renamed in step5
8. clicked the .my second job and add "2" at the end, hoping that my job comes back
9. no luck. .my second job2 still exists, but i cannot see my job file

**Comment by nconrad** [comment]
Yeah, there is strange service behavior if you call `copy` (with 'move' = true) twice.   I should be able to guard against this by disabling the 'rename' button after the first click... but that won't fix the state of your workspace.

There must be some kind of race conditions in the service, which @olsonanl probably knows about.  @olsonanl, if you want a specific example, I can no longer create a folder called `/devuser@patricbrc.org/home/Escherichia testing6`

The error is:

`mkdir /disks/p3/workspace/P3WSDB/devuser@patricbrc.org/home//Escherichia testing6: File exists`

**Comment by olsonanl** [comment]
The workspace service is riddled with potential race conditions. It needs a lot of work.

**Comment by nconrad** [comment]
Should be fine UI-wise.  I put a ticket here:  PATRIC3/Workspace#60
