### ISSUE TITLE
what happened on my old jobs?

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1613]
This is diff import file that i imported this year.

![image](https://user-images.githubusercontent.com/1236467/28433993-6991004c-6d53-11e7-8a4f-d4ec043fea6d.png)

this is something that i uploaded back in 2014.

it still works to launch "genes" button. but show nothing when i double click the job.

![image](https://user-images.githubusercontent.com/1236467/28434015-862bbf4e-6d53-11e7-98a7-63825f1e32cd.png)

**Comment by hyoo** [comment]
i guess this is related to job result viewer (@zreyn), but ccing @nconrad as well.

**Comment by zreyn** [comment]
I believe this has been fixed by https://github.com/PATRIC3/p3_web/pull/491
