### ISSUE TITLE
WorkspaceObjectSelector is not working

### ISSUE THREAD

**Issue by dawenx** [PATRIC3/patric3_website#1615]
This was reported in #1614, I created this new ticket because the problem is not just for tree service. We CAN NOT do July release with this problem: it breaks lots of services, for example, selecting genome group or feature group is not working:
https://www.alpha.patricbrc.org/app/PhylogeneticTree
https://www.alpha.patricbrc.org/app/SeqComparison
https://www.alpha.patricbrc.org/app/ProteinFamily

**Comment by nconrad** [comment]
should be addressed in https://github.com/PATRIC3/p3_web/pull/500.
