### ISSUE TITLE
Not able to choose more than one group in phylogenetic tree service

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1616]
Can choose multiple private genomes, but only one group at a time.  Users may want to add more than one group.

**Comment by dawenx** [comment]
User should be able to add more than one group when total number of genome does not exceed max allowed number (50 for Ingroup and 5 for Outgroup). Also, a genome or genome group CANNOT be placed in both ingroup and outgroup table. 

If you can share the 2 groups you wanted to add, I can look into it as I only have limited testing group in my workspace.

**Comment by dawenx** [comment]
This is similar to #1644 and I added notice when selecting a new group exceeds the maximum allowed number. Close this ticket as it's resolved. I agree that we should discuss whether to change the maximum allowed number.
