### ISSUE TITLE
job result viewer: shortcut to genome overview page when it is an annotation job

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1619]
during the workshop, we noticed that it would be much easier to get to overview page from the job result list. Maybe we can check whether it is an annotation job and if so, we can activate "G" button to get to genome overview page.

**Comment by olsonanl** [comment]
I'm going to bounce this one to Neal since it's a web UI thing.

**Comment by mshukla1** [comment]
I vote for consistency over exception to provide shortcut for one job type. 

The current jobs view has a consistent representation and actions for all job types, view results and report issue. 

If we create an exception for genomes, we will soon have to provide similar shortcuts for other jobs as well, i.e. results of proteome comparison, diuff expression, streaming RNA-seq to genome browser, etc. 

My suggestion is to leave it as it is for now.
