### ISSUE TITLE
remove old url dependency

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1621]
i come across some hard-coded urls that contain old PATRIC urls.

We need to replace with new url pattern.

```
$ grep -r "/portal/portal/patric" *
app/p3app.js:			xhr.post("/portal/portal/patric/GenomicFeature/GenomicFeatureWindow?action=b&cacheability=PAGE", {
app/p3app.js:				document.location = "/portal/portal/patric/GlobalSearch?cType=taxon&cId=131567&dm=&pk=" + results;
widget/WorkspaceBrowser.js:				xhr.post("/portal/portal/patric/FIGfam/FIGfamWindow?action=b&cacheability=PAGE", {
widget/WorkspaceBrowser.js:					Topic.publish("/navigate", {href: "/portal/portal/patric/MSA?cType=&cId=&pk=" + results});
widget/WorkspaceBrowser.js:				xhr.post("/portal/portal/patric/IDMapping/IDMappingWindow?action=b&cacheability=PAGE", {
widget/WorkspaceBrowser.js:					Topic.publish("/navigate", {href: "/portal/portal/patric/IDMapping?cType=taxon&cId=131567&dm=result&pk=" + results});
widget/WorkspaceBrowser.js:				xhr.post("/portal/portal/patric/TranscriptomicsEnrichment/TranscriptomicsEnrichmentWindow?action=b&cacheability=PAGE", {
widget/WorkspaceBrowser.js:					Topic.publish("/navigate", {href: "/portal/portal/patric/TranscriptomicsEnrichment?cType=taxon&cId=131567&pk=" + results});
```

**Comment by dawenx** [comment]
harry, i don't have knowledge on what should be used to replace those hard-coded urls, can you give me an example or more details? i know this might take you longer time than fixing it directly, but i wanted to learn and go through the files if you don't mind. thanks.

**Comment by hyoo** [comment]
each url is mapped to a tab or service

- /portal/portal/patric/GenomicFeature -> features tab in genome or taxon
- /portal/portal/patric/GlobalSearch -> global search
- /portal/portal/patric/FIGfam/ -> protein families tab in genome or taxon 
- /portal/portal/patric/MSA -> MSA
- /portal/portal/patric/IDMapping/ -> services -> IDMapping
- /portal/portal/patric/TranscriptomicsEnrichment/ -> transcriptomics tab (?)

before we mechanically change this, I suggest to track down where we are using these, and if we don't use it, i would like to remove them. 

@dawenx would you track down this ?

**Comment by dawenx** [comment]
I will look into it.

**Comment by dawenx** [comment]
harry, i made change in app/p3app.js and pushed my change to my fork.

i have hard time understanding what xhr.post() was doing in WorkspaceBrowser.js, i also don't have much testing data in my workspace to even see MSA, Pathway Summary and IDMapping action icons, can you take over fixing WorkspaceBrowser.js? thanks!
