### ISSUE TITLE
need a different copy icon for "copy to clip board" from grid

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1622]
![image](https://user-images.githubusercontent.com/1236467/28726816-b2e8343e-7390-11e7-8b46-9e52bbd0e2b4.png)

Now we have "Copy" function on workspace and we are using same icon for two different functions.  I think this button would make more sense if we use clipboard icon. 

https://www.google.com/search?q=icon+clipboard+copy&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwjl9-SztKzVAhWi6oMKHcReAIgQsAQIMw&biw=1028&bih=1023&dpr=2

**Comment by nconrad** [comment]
oh yeah, I noticed this too.  +1 for clipboard icon.

**Comment by zreyn** [comment]
Swapped icon in PR: https://github.com/PATRIC3/p3_web/pull/506

**Comment by zreyn** [comment]
Deployed
