### ISSUE TITLE
Cannot tab into username/pw fields in login

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1623]
When I click the login button, the login textbox does not have focus and I cannot tab into it (nothing ever seems to get focus).

**Comment by mshukla1** [comment]
@olsonanl @dmachi 

Is this still a problem? Any action? If not please close the ticket.

**Comment by olsonanl** [comment]
It still behaves that way.

**Comment by dmachi** [comment]
This is fixed in the p3-user updates that will be landing in January

**Comment by JoshuaVSherman** [comment]
link to pull request
https://github.com/PATRIC3/p3_web/pull/662

**Comment by hyoo** [comment]
#1763
