### ISSUE TITLE
Cant download fasta file for private genome

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1626]
I want the fasta file corresponding to these pegs:

![image](https://user-images.githubusercontent.com/7661533/29083973-2eed3f8c-7c30-11e7-89a0-34e9942e1174.png)

**Comment by hyoo** [comment]
you can go to workspace, annotation job result page, and there are [your_gneome_name]_features_dna.fasta and _features_protein.fasta

![image](https://user-images.githubusercontent.com/1236467/30179586-81baa6c8-93d2-11e7-985b-c839d4c65d56.png)

**Comment by hyoo** [comment]
download private genomes with download tool is not implemented yet.

see more detail
#1432

**Comment by hyoo** [comment]
I am going to close this one to consolidate tickets.

#1470
