### ISSUE TITLE
No check boxes in phylogenetic tree service

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1628]
I am trying to build a tutorial for next week's workshop.  There are not check boxes to differentiate between the different types of genomes when you are trying to select individual genomes to load.  Could this please be fixed ASAP?
![screen shot 2017-08-10 at 12 13 36 pm](https://user-images.githubusercontent.com/11475316/29180366-9dfea1ae-7dc5-11e7-9a71-c070c917aaa5.png)

**Comment by ARWattam** [comment]
Sorry.  REalized that I was working on alpha. It has bewen fixed.

**Comment by dawenx** [comment]
This is using GenomeNameeSelector, if it has problem, it will affect multiple services. I'm closing this ticket since it is false alarm.
