### ISSUE TITLE
Can't add outgroup in phylogenetic tree building service on production-URGENT

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1629]
Clicking the Plus icon for outgroup does nothing, although it does work well for ingroup genomes
![screen shot 2017-08-10 at 12 25 11 pm](https://user-images.githubusercontent.com/11475316/29180927-51279bfe-7dc7-11e7-8aa9-c479be23df57.png)
.  I need this before the workshop next week!  Could this be fixed ASAP?

**Comment by hyoo** [comment]
does this genome group have more than 5 genomes?


On Aug 10, 2017, at 11:27 AM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


Clicking the Plus icon for outgroup does nothing, although it does work well for ingroup genomes
[screen shot 2017-08-10 at 12 25 11 pm]<https://user-images.githubusercontent.com/11475316/29180927-51279bfe-7dc7-11e7-8aa9-c479be23df57.png>
. I need this before the workshop next week! Could this be fixed ASAP?

**Comment by ARWattam** [comment]
It has 6.  Is there a limit for 5?
I noticed that I can add genomes individually
![screen shot 2017-08-10 at 12 35 35 pm](https://user-images.githubusercontent.com/11475316/29181262-81a39ec6-7dc8-11e7-83b4-8f2fef6b691e.png)

**Comment by ARWattam** [comment]
Okay...now I see that its 5 genomes.  I thought that it had been decided to have more, but I personally like the 5 option.  Guess I got greedy.

**Comment by dawenx** [comment]
We set the limit to 50 genomes for ingroup and 5 for outgroup. We can change it if we want, but that's what we decided.

**Comment by hyoo** [comment]
@dawenx we need to display a message, why nothing is happening when user clicked/chose something. It would be better to say, "your genome group/selection has more then 5 genomes that are current limit. please reduce the number of genome."

**Comment by dawenx** [comment]
the limit is 5 and i added notice in addressing #1644 which has been merged. so this is resolved.
