### ISSUE TITLE
Comparative Pathway tool not working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#163]
I create a group and deploy the tool, choosing that group.  I get the pathway summary table, and I see the correct number of genomes.  I choose one pathway....it takes a while to load...then I see that the pathway is summarizing 33,219 genomes.  Actually, I'm impressed that it was able to do that, but I only wanted to see the summary across my 3 genomes.

Sigh....a frustrating day in PATRIC land....

**Comment by hyoo** [comment]
this is fixed and available on beta.

**Comment by mshukla1** [comment]
Tested on beta, working.
