### ISSUE TITLE
Need to be able to do password reset by username

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1630]
![image](https://user-images.githubusercontent.com/7661533/29181300-488cdc36-7dc0-11e7-91ba-71d6e713ec4c.png)

**Comment by jimdavis1** [comment]
It would also be really good if you sent the username in the registration name.

**Comment by mshukla1** [comment]
@dmachi , is it easy to add user name in the password reset email?

**Comment by dmachi** [comment]
Should be straight forward. I’ll add this into the p3-user changes we are working on.

Dustin

**Comment by JoshuaVSherman** [comment]
@dmachi we implemented a change password within the User Account page, is that what is being requested here?

**Comment by dmachi** [comment]
I think he is wanting the username to be passed in the reset email, though I believe there is a separate request for the change password on the account form.  This one needs to be changed in p3-user instead of p3-web, leave this ticket assigned to me and I’ll fix.

**Comment by JoshuaVSherman** [comment]
@dmachi please let me know when I should test out your update api call

**Comment by JoshuaVSherman** [comment]
https://github.com/PATRIC3/p3_web/pull/686
