### ISSUE TITLE
Why in the world are we showing the parameters this way in the workspace job view?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1632]
Not that I think its a bad thing...but as a biologist, I am bemused by seeing this parameters section at the top of my job when I am trying to view it.  I think we could come up with a better way of summarizing the parameters than showing it this way?  It takes up a lot of room and distracts the eye from seeing the downloads below.  Maybe we could make it clickable, if its really necessary?
<img width="1138" alt="screen shot 2017-08-11 at 7 30 07 am" src="https://user-images.githubusercontent.com/11475316/29211526-967ae364-7e67-11e7-8bfb-5fa03360a3d3.png">

**Comment by ARWattam** [comment]
Okay, having said that, I just used the parameters to figure out what algorithm I used to run the tree job.  So it is useful, but not very understandable.  Could we summarize the parameters for the user (like FastTree with progressive refinement, or RaxML with no refinement)?  That would make it a bit clearer as to what is going on.

**Comment by mshukla1** [comment]
I have also complained about it in the past. We should try to present parameters in a more biologist friendly way. We should try to address it as part of genetic work space / jobs browser or streamlined workflow tasks. 

-M

**Comment by zreyn** [comment]
I'll work with Rebecca to design the new top part of the page.  These modifications should include the job id (from issue #1705).

**Comment by zreyn** [comment]
https://github.com/PATRIC3/p3_web/pull/566

**Comment by zreyn** [comment]
PR for develop branch: https://github.com/PATRIC3/p3_web/pull/573

**Comment by hyoo** [comment]
deployed on production.
