### ISSUE TITLE
Need to be able to see the size of files in the public workspace.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1633]
There are no options that show the size of files in the public workspace.  That would be helpful.
<img width="846" alt="screen shot 2017-08-11 at 10 17 13 am" src="https://user-images.githubusercontent.com/11475316/29217103-c0071ce0-7e7e-11e7-900f-00d8b71dddc9.png">

**Comment by nconrad** [comment]
The size is given by default now.  On prod.
