### ISSUE TITLE
Lets change default for tree to FastTree with no refinement

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1634]
I've done a small analysis on the time it takes for the trees to run, and I suggest that we reset the defaults for the phylogenetic tree so that users can get some returns in a reasonable time, with the ability for them to scale up if they desire.

**Comment by ARWattam** [comment]
I also think that we need to have a serious discussion about how many genomes users can compare at a time, or expanding the computational resources to handle tree building.  I started a series of trees with the same genomes and all possible parameters.  There were 22 ingroup genomes, and 5 outgroup genomes, and the ingroup genomes were all Escherichia.  When I run this tree at Va Tech, it might take 10 hours.  The first tree, with RaxML and progressive refinement as the options, has been running 20 hours now, but what concerns me is that it has tied up the queue, and two of the trees have are not even "in progress" after 20 hours.  If the service is popular, it could drag down other services.

**Comment by dawenx** [comment]
I made the change on the submission GUI and submit a pull request. @hyoo

**Comment by hyoo** [comment]
deployed
