### ISSUE TITLE
Why are there 2 Download icons in the vertical green bar on the production website in the Workspace-Genome Groups view.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1635]
This is a bit confusing.
<img width="1182" alt="screen shot 2017-08-11 at 12 00 17 pm" src="https://user-images.githubusercontent.com/11475316/29221451-ce708970-7e8c-11e7-9ced-23114a45f73e.png">

**Comment by mshukla1** [comment]
It's for back up, in case the first icon doesn't work!

...just kidding, I find it strange too!

**Comment by nconrad** [comment]
I can fix this, but need to know if the first download button is of any use?  It seems to download a JSON structure with the object ids like this:

```
{"id_list":{"genome_id":["1316919.3","1358410.3","887299.3","887315.3","887316.3","887317.3","887318.3","887319.3","887320.3"]},"name":"testing"}
```

**Comment by nconrad** [comment]
Any input on how this should work/look?  I just don't know what these things are used for...

**Comment by zreyn** [comment]
One is the download widget (the lower one with the tool tip 'Download Selection'), which applies to the selected items and supplies a table-type of download:
https://github.com/PATRIC3/p3_web/blob/develop/public/js/p3/widget/GridContainer.js#L337-L373

I would expect that one to show when multiple items are selected, though it doesn't in this case.  Not sure why... Copy is modeled after this and it does show for multi-selections.

The other is the WS download item:
https://github.com/PATRIC3/p3_web/blob/develop/public/js/p3/widget/WorkspaceBrowser.js#L208-L225

My recommendations would be:
1) Find a way to get the table download to work with multiple items and only multiple items.  Then, only one button appears at any given time.

2) Remove the table download button from this type all together.

**Comment by nconrad** [comment]
The second table download button only shows up when one item is selected because each item is a set of genomes, or features, etc.  I'm guessing nobody wants to download tables with genomes from multiple groups.  So, I'm going to leave 1 as is.   I also wouldn't remove the table download all together because that actually seems useful.  It was just the JSON download button that I wasn't sure about (the first one).

**Comment by nconrad** [comment]
I'm going to remove the "JSON download" button, unless there any objections.
