### ISSUE TITLE
unable to download Newick file from tree job results.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1636]
Why isn't there a download for this?  Users need to download this.  They will open it in other tools, and its the only way to look at the support values.
<img width="1115" alt="screen shot 2017-08-11 at 3 39 25 pm" src="https://user-images.githubusercontent.com/11475316/29229290-85272084-7eab-11e7-9a0e-5afb663f5b7e.png">

**Comment by zreyn** [comment]
It's just not in the download list:
https://github.com/PATRIC3/p3_web/blob/master/public/js/p3/WorkspaceManager.js#L17-L31

I'll submit a PR to fix this shortly.

**Comment by zreyn** [comment]
Fix: https://github.com/PATRIC3/p3_web/pull/513

**Comment by ARWattam** [comment]
So its fixed?  Do I need to reload my browser to see this?

**Comment by zreyn** [comment]
Sorry, premature closing...

**Comment by ARWattam** [comment]
We need this before the workshop on Monday

**Comment by zreyn** [comment]
New PR: https://github.com/PATRIC3/p3_web/pull/514

Putting this quick fix in for the upcoming workshop and deferring the "exclusion list" solution for later.

**Comment by ARWattam** [comment]
I still don't see the ability to download.  Should I see it on production?

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/29255960-09e00c70-806c-11e7-8385-0ceef5978435.png)

just deployed on production.
