### ISSUE TITLE
Feature request: Report bug button on failed jobs

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#1637]
Put a bug icon on the green bar when failed jobs are selected. Clicking it would bring up the feedback window with a Job ID in the title or body of the message auto-populated
![image](https://user-images.githubusercontent.com/229173/29278102-b63758aa-80e1-11e7-81d2-54e769ed9da7.png)

![image](https://user-images.githubusercontent.com/229173/29278077-a2d8d2de-80e1-11e7-8bdd-fe1976b2dd4a.png)

**Comment by nconrad** [comment]
This is on prod now.  The app name is title; job id and everything else in body.  You can comment on successful jobs too.  Let me know if anything should be changed.
