### ISSUE TITLE
Transcriptomic BLAST is not working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#164]
I know we have BLAST issues, but I thought I could count on Transcriptomic BLAST to work.  I submitted a protein and the job started, then the following page returned.
![screen shot 2015-04-17 at 7 43 21 am](https://cloud.githubusercontent.com/assets/11475316/7201478/964b5d8e-e4d5-11e4-9c9a-7c904dcf14ec.png)

If it weren't for bad luck I'd have no luck at all.....

**Comment by mshukla1** [comment]
NONE of the BLAST searches are working at the moment. We didn't make the BLAST service work after we switched to the new ID scheme and moved the web server to cluster. Given that it was taking unacceptably long time to run, we decided not to patch fix the current BLAST, but rather wait until we get a chance to completely redesign it for P3. 

-Maulik

**Comment by olsonanl** [comment]
I'm guessing fixing BLAST isn't doable for August, correct?  or are we trying for a quick fix?

**Comment by dmachi** [comment]
There are a bunch of blast tickets that cover all these aspects. Closing
