### ISSUE TITLE
upload dialog doesn't select newly uploaded file

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1642]
If in one of the services (I used similar genome finder), when I choose to upload a new contigs file, when the upload is finish that uploaded file should be selected in the browser. Otherwise I need to go browse a second time to find the file I just uploaded.

**Comment by dawenx** [comment]
The fix in PR 624 might address this issue as well -- i just tested it on my local dev using similar genome finder service and it works for me.

**Comment by dawenx** [comment]
fix is on alpha

**Comment by mshukla1** [comment]
Working as expected on production.
