### ISSUE TITLE
Phylogenetic Tree Building App Issue

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#1644]
We saw some issues using the “outgroup genomes” fields at https://www.patricbrc.org/app/PhylogeneticTree.  it seems I can select and add my first genome group, but not the second.  There were selection issues with the "outgroup genomes" in general.

<img width="381" alt="i79 pimgpsh_fullsize_distr" src="https://user-images.githubusercontent.com/1194246/29323946-260a3e10-81a8-11e7-98b9-dd87f16ee694.png">

**Comment by dawenx** [comment]
We only allow up to 5 genomes in the outgroup, how many genomes are there in "new group" and "a genome group"? if the total is larger than 5, the 2nd group cannot be added.

**Comment by nconrad** [comment]
Oh, ok.  Since there was confusion, it'd be good to have notice in the app (i.e., a prompt) that says this when the user tries to select more than 5.

**Comment by nconrad** [comment]
....oh, and listing the counts (and maybe even total) could be user friendly as well.

**Comment by dawenx** [comment]
That's a good idea and I was thinking to add it. The problem is where should we put such prompt? I couldn't find similar example on other apps. @hyoo do you have suggestion?

**Comment by dawenx** [comment]
once a folder is selected, I did display total count in the folder in the selected list. anyway, i will work on it to make it more user friendly. thanks!

**Comment by nconrad** [comment]
cool.  I don't think we have a true standard for dealing with these sorts of error/warning messages, but a dialog is sufficient IMO...something like ```new Dialog({title: "Notice", content: "Sorry, you can only add up to 5 genomes total and you are trying to select "+count + "."}).show();```

**Comment by dawenx** [comment]
Will do, thanks for suggestion.

**Comment by dawenx** [comment]
This is addressed on develop and pull request submitted.
