### ISSUE TITLE
tn-seq job result doesn't have job icon

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1648]
![image](https://user-images.githubusercontent.com/1236467/29334702-f5c71356-81cd-11e7-9a44-81091a6b3d1b.png)

https://www.patricbrc.org/workspace/public/anwarren@patricbrc.org/tnseq/tnseq

**Comment by mshukla1** [comment]
Just checked, tn-seq jobs results do have checkered flag now.
