### ISSUE TITLE
Unable to change order of rows in circular viewer

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1649]
When delete certain feature rows in the circular viewer, I would expect that the tracks I want would move up, but they don't.  I tried to manually move them, but was unable to.  Harry tells me that this is a bug.  All the tracks that have been selected should be next to each other.
<img width="1308" alt="screen shot 2017-08-16 at 9 41 59 am" src="https://user-images.githubusercontent.com/11475316/29369115-46829aa6-8267-11e7-9523-b1df87dc7da6.png">

**Comment by hyoo** [comment]
This is critical to users. Users have very limited space to display their data of interest.

**Comment by mshukla1** [comment]
@maovt I do think this is a bug and it is kind of critical. 

The reason most users would wan't to deselect / remove a track is to make space for others or add more tracks. If removed track still occupies space in the viewer, it doesn't help much. This keeps 
in every workshop while showing circular viewer and needs to be fixed. 

Can you please look into it?

**Comment by chmao1** [comment]
I implemented the remove buttons which will fix this issue. I've made the pull request.

**Comment by chmao1** [comment]
Fixed and tested on alpha.
