### ISSUE TITLE
All genomes from genome group not showing up in Protein Family Sorter

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#165]
Am I cursed?  I created a group first with Streptococcus pneumoniae D39 and saved to to my workspace.  Then I added Streptococcus pyogenes MGAS315 to the same group.  When I check in my workspace, all appears normal:
![screen shot 2015-04-17 at 8 04 26 am](https://cloud.githubusercontent.com/assets/11475316/7201709/86780152-e4d8-11e4-88c1-0123ea736632.png)
However, when I deploy the protein family sorter , select that group, and put in something simple, like DnaA, this is what returns, showing that there is only one genome in the group
![screen shot 2015-04-17 at 8 03 59 am](https://cloud.githubusercontent.com/assets/11475316/7201727/a4907656-e4d8-11e4-889e-8eab62e54bb0.png)

And yes, both genomes have dnaA.

**Comment by hyoo** [comment]
I cannot reproduce this problem. Rebecca, can you test again?
Here is what I did.
1. Go to genome finder 
http://www.alpha.patricbrc.org/portal/portal/patric/GenomeFinder?cType=taxon&cId=131567&dm=

2. change keyword to genome name (in 2. Enter keyword) and add
Streptococcus pneumoniae D39
Streptococcus pyogenes MGAS315

and click search

3. create a genome group with two genomes found.

4. go to PFS and select the group I created.

5. put dnaA in "Filter by one or more keyword" textarea.

6. click filter

this is what I have

![pfs](https://cloud.githubusercontent.com/assets/1236467/7209300/6e209690-e515-11e4-83da-6a8a9fca9c08.png)

**Comment by hyoo** [comment]
This is a problem of workspace api. If you create a group with selection, it will work fine. If you create a group and add next item to the existing group, the group content is corrupted. 

case 1. two genomes were added when the group is created.
{
    "error": null,
    "id": "1",
    "result": [
        [
            [
                [
                    "pfs test",
                    "genome_group",
                    "/harry@patricbrc.org/home/Genome Groups/",
                    "2015-04-17T19:14:10",
                    "ED584910-E535-11E4-808A-EFF3682E0674",
                    "harry@patricbrc.org",
                    68,
                    {},
                    {
                        "item_count": 2
                    },
                    "o",
                    "n",
                    ""
                ],
                "{\"id_list\":{\"genome_id\":[\"373153.27\",\"198466.3\"]},\"name\":\"pfs test\"}"
            ]
        ]
    ]
}


case 2. second genome added into the existing group
{
    "error": null,
    "id": "1",
    "result": [
        [
            [
                [
                    "pfs test2",
                    "genome_group",
                    "/harry@patricbrc.org/home/Genome Groups/",
                    "2015-04-17T20:33:40",
                    "084C1FAC-E541-11E4-8234-4BF5682E0674",
                    "harry@patricbrc.org",
                    86,
                    {},
                    {
                        "item_count": 2
                    },
                    "o",
                    "n",
                    ""
                ],
                "{\"id_list\":{\"genome_id\":[\"198466.3\"],\"genome_group\":[\"373153.27\"]},\"name\":\"pfs test2\"}"
            ]
        ]
    ]
}

**Comment by hyoo** [comment]
The bug related adding items to existing group is fixed. However, you many need to delete the old group and create another to make it work

**Comment by mshukla1** [comment]
Tested on beta. working as expected.

**Comment by rwill1** [comment]
what about external users with existing groups?�� Do we have a way
    to let them know this information?� Was� it just groups created in a
    small interim - or all existing groups or ??� (that is, how bad is
    our exposure w/ external users?)
    
    On 4/17/15 6:52 PM, Harry Yoo wrote:
    
    
      The bug related adding items to existing group is fixed.
        However, you many need to delete the old group and create
        another to make it work
      �
        Reply to this email directly or view
          it on GitHub.

**Comment by dmachi** [comment]
It is isolated to when users added to an existing group (regardless of when it was created) from UI components defined on the jboss side of the application.
