### ISSUE TITLE
Download circular viewer as .tiff or .jpeg

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1651]
Some of our users have requested this as it is more adaptable.

**Comment by hyoo** [comment]
there are a lot of online tool that can convert svg to any other format.

https://www.google.com/search?q=svg+to+tiff&oq=svg+to+tiff&aqs=chrome..69i57j0l5.2894j0j7&sourceid=chrome&ie=UTF-8

I don't know how much effort to do this, but i am more skeptical to reinventing wheels.

**Comment by chmao1** [comment]
@ARWattam Please review this request. Is this still needed?

**Comment by chmao1** [comment]
I'm closing this issue for now as we provide SVG files for images. Please reopen if needed.

**Comment by ARWattam** [comment]
I think we're fine with not doing this, especially if there is an online option.
