### ISSUE TITLE
Sorting issue

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#1655]
A table under "Specialty Genes" tab is sortable by any column, except “Classification”.  If one tries to sort by this field, all the contents of the table simply disappears.   Strange, that only this column is not sortable 

<img width="825" alt="screen shot 2017-08-16 at 1 59 40 pm" src="https://user-images.githubusercontent.com/20665963/29380415-452d9f60-828b-11e7-83c2-807ac749e962.png">

**Comment by hyoo** [comment]
multi-valued field is not sortable.

**Comment by rkenyon** [comment]
Is it possible to make a multi-value field sortable, or should we just close this ticket?

**Comment by hyoo** [comment]
Classification field should not be sortable. This is a limitation from database (solr). Currently the field is not configured correctly, I will fix it soon.
