### ISSUE TITLE
Async issues with download link not being created on streaming

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#1657]
Async issues with download link not being created on streaming for bai. Sometimes we have to try clicking the browser button several times for RNA-Seq to get the BAM file to work. Jbrowse gives a red box error saying that it can't access the BAI.

**Comment by zreyn** [comment]
This is potentially due to the download links not being available from the service to pack into the url that sends data to JBrowse. This is especially a problem when there are a lot of tracks.  I will look into disabling the button until the download links are ready.

**Comment by zreyn** [comment]
I can't seem to recreate this.  Even on larger jobs where there are a lot of tracks.  I know the effect is sporadic, but is there an example job that tends to be problematic?

**Comment by zreyn** [comment]
I believe this is related to #1960

**Comment by zreyn** [comment]
Fix in https://github.com/PATRIC3/p3_web/pull/795

**Comment by aswarren** [comment]
I believe this has been fixed.
