### ISSUE TITLE
No browser button for variation service

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#1658]
There are bam files and maybe some other streamables in a Variation job result

**Comment by mshukla1** [comment]
@aswarren @zreyn 

Please make sure result streaming and browser buttons are available for all relevant services, i.e. genome assembly, variation service, RNA-seq, and Tn-seq services.

**Comment by zreyn** [comment]
Variation, RNA-seq, and TN-seq are currently included.  GenomeAssembly is missing reference_genome_id in the parameters, which is required for JBrowse as far as I can tell.

**Comment by zreyn** [comment]
The fix for this is related to #2024

**Comment by mshukla1** [comment]
This was addressed a while ago. Now, there is a browser button from the variation analysis results, which allows you to see vcf and bam files as tracks in the genome browser. 

<img width="1070" alt="screen shot 2018-08-27 at 11 30 53 am" src="https://user-images.githubusercontent.com/1236463/44671989-b2169300-a9ec-11e8-82a2-a13ff4e02244.png">
