### ISSUE TITLE
genome finder: search by genome id or genome name

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#166]
The keyword search sometimes can introduce unwanted result, If user specifically wants to search by genome_id and genome_name. 

Add genome_id, and genome_name on the 'search on' options.

**Comment by mshukla1** [comment]
Tested. Genome ids working fine as expected. Search by genome names will still find the genome names with partial match. For example, Brucella melitensis M28 returns 
Brucella melitensis M28 and
Brucella melitensis bv. 1 str. M28-12.
This issue will not be solved even if we add double quotes to the search strings. 

I think we need to try different solr query solution for exact match problem.

**Comment by hyoo** [comment]
This is due to the fact that we set string_ci for genome_name
