### ISSUE TITLE
Feature Overview: Links to CDD do not work / missing 

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#1661]
“NCBI CDD Search” tool/link on a peg page did not work for multiple proteins in PATRIC, e.g. -
fig|246196.19.peg.377
fig|246196.19.peg.375
fig|246196.19.peg.367
fig|1001989.3.peg.4468
                                        Why doesn't CDD view load properly?  

<img width="1025" alt="screen shot 2017-08-16 at 4 29 31 pm" src="https://user-images.githubusercontent.com/20665963/29386197-6c883f06-82a0-11e7-89d7-85ecd6c0fe3d.png">

**Comment by hyoo** [comment]
i will take a look. it is possible they changed some form or params.

**Comment by hyoo** [comment]
will be deployed on alpha soon

**Comment by mshukla1** [comment]
@chris-c-thomas CDD links are still missing.

**Comment by chris-c-thomas** [comment]
On production. Closing.
