### ISSUE TITLE
The jobs queue has a genomes with status "undefined init" instead of queued.

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1663]
![image](https://user-images.githubusercontent.com/7661533/29459974-9a73de6a-83eb-11e7-984b-c75a47a9086a.png)

**Comment by nconrad** [comment]
I should be able to make this state say "queued", which would be consistent with the status counts.

**Comment by nconrad** [comment]
I think this should be fixed on alpha.
