### ISSUE TITLE
Compare region viewer: doesn't load for private genomes

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1664]
During the Germany Workshop, several participants noted that the compare region viewer wasn't working for private genomes.

-Maulik

<img width="1435" alt="screen shot 2017-08-19 at 10 17 31 am" src="https://user-images.githubusercontent.com/1236463/29487986-d7f9d8de-84c7-11e7-9c36-98e353979236.png">

**Comment by hyoo** [comment]
i have tried with my private genome and got error like below

![image](https://user-images.githubusercontent.com/1236467/29635923-446d5474-8814-11e7-9dc9-09aeabb23d2e.png)

![image](https://user-images.githubusercontent.com/1236467/29635939-5f33975a-8814-11e7-96c9-3e71bd7e160b.png)

**Comment by hyoo** [comment]
this is fixed on alpha. will be deployed with other fixes soon.

**Comment by hyoo** [comment]
working well on production now.
