### ISSUE TITLE
Related to case # 1659

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#1666]
The situation with case #1659 did not improve --
First, the “undefined” features still appear on top of Search results under the “Specialty Genes” rubric 
Second, the **functions** of “Genomic Features” shown in Search results  are seriously off!  They are (1) outdated  and (2) do not correspond to the actual functions currently in PATRIC.   Where do they even come from..?  These functions are not  displayed on  the corresponding protein web pages in PATRIC at all

<img width="713" alt="screen shot 2017-08-21 at 10 56 15 pm" src="https://user-images.githubusercontent.com/20665963/29548131-0501f494-86c4-11e7-8d2a-9fe60fcd5ffb.png">

**Comment by chmao1** [comment]
@mshukla1 Could you check to see whether the second point is a data issue?
The first one is fixed.

**Comment by chmao1** [comment]
#1113

**Comment by chmao1** [comment]
Fixed and verified on alpha.
