### ISSUE TITLE
Job status is not changing seamlessly

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1669]
I have ~60 completed annotation jobs that still show up as running or queued.

![image](https://user-images.githubusercontent.com/7661533/29583606-7ed76c86-8746-11e7-9155-f2e1d820880c.png)

**Comment by olsonanl** [comment]
I don't know what the bug is here... @jimdavis1  ?

**Comment by nconrad** [comment]
I'm not sure what the issue was here either?  Did those jobs ever finish?

**Comment by mshukla1** [comment]
No enough details to understand the problem.
