### ISSUE TITLE
Assembly job never returned results.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#167]
I submitted a job on April 1 and it is still running with no results returned

**Comment by mshukla1** [comment]
I submitted an assembly job just now, using the same read files that I have assembled with success in the past, and the job failed. 

Assigning it to Andrew to start to investigate the problem and follow up with others, if needed.  

-Maulik

**Comment by mshukla1** [comment]
Details of a failed job, if it helps. 

Proc genome $VAR1 = {
          'parameters' => [
                            {
                              'allow_multiple' => bless( do{\(my $o = 1)}, 'JSON::PP::Boolean' ),
                              'required' => 0,
                              'group' => [
                                           {
                                             'desc' => 'FASTQ or FASTA file or reads',
                                             'id' => 'read1',
                                             'label' => 'Read file 1',
                                             'type' => 'wstype',
                                             'required' => 1,
                                             'wstype' => 'ReadFile'
                                           },
                                           {
                                             'wstype' => 'ReadFile',
                                             'required' => 0,
                                             'type' => 'wstype',
                                             'label' => 'Read file 2',
                                             'id' => 'read2',
                                             'desc' => 'FASTQ or FASTA file or reads'
                                           },
                                           {
                                             'required' => 0,
                                             'default' => bless( do{\(my $o = 0)}, 'JSON::PP::Boolean' ),
                                             'type' => 'bool',
                                             'label' => 'Are the paired end reads interleaved?',
                                             'id' => 'interleaved'
                                           },
                                           {
                                             'required' => 0,
                                             'id' => 'insert_size_mean',
                                             'label' => 'Average insert size',
                                             'type' => 'int',
                                             'default' => undef
                                           },
                                           {
                                             'required' => 0,
                                             'label' => 'Average insert standard deviation',
                                             'id' => 'insert_size_stdev',
                                             'default' => undef,
                                             'type' => 'float'
                                           }
                                         ],
                              'id' => 'paired_end_libs',
                              'default' => undef,
                              'type' => 'group'
                            },
                            {
                              'wstype' => 'ReadFile',
                              'type' => 'wstype',
                              'allow_multiple' => $VAR1->{'parameters'}[0]{'allow_multiple'},
                              'required' => 0,
                              'default' => undef,
                              'id' => 'single_end_libs',
                              'desc' => 'FASTQ or FASTA file or reads',
                              'label' => 'Read file'
                            },
                            {
                              'wstype' => 'Contigs',
                              'required' => 0,
                              'type' => 'wstype',
                              'default' => undef,
                              'id' => 'reference_assembly',
                              'label' => 'Contig file',
                              'desc' => 'Reference set of assembled DNA contigs'
                            },
                            {
                              'required' => 0,
                              'type' => 'enum',
                              'default' => 'auto',
                              'desc' => 'Recipe used for assembly',
                              'id' => 'recipe',
                              'label' => 'Assembly recipe',
                              'enum' => [
                                          'auto',
                                          'full_spades',
                                          'fast',
                                          'miseq',
                                          'smart',
                                          'kiki'
                                        ]
                            },
                            {
                              'required' => 1,
                              'id' => 'output_path',
                              'desc' => 'Path to which the output will be written. Defaults to the directory containing the input data. ',
                              'label' => 'Output Folder',
                              'default' => undef,
                              'type' => 'folder'
                            },
                            {
                              'required' => 1,
                              'label' => 'File Basename',
                              'id' => 'output_file',
                              'desc' => 'Basename for the generated output files. Defaults to the basename of the input data.',
                              'type' => 'wsid',
                              'default' => undef
                            }
                          ],
          'script' => 'App-GenomeAssembly',
          'description' => 'Assemble reads into a set of contigs',
          'id' => 'GenomeAssembly',
          'label' => 'Assemble reads'
        };
$VAR2 = {
          'recipe' => 'auto',
          'output_file' => 'Mvaccae_assembly',
          'output_path' => '/mshukla@patricbrc.org/home/Tests',
          'paired_end_libs' => [
                                 {
                                   'read1' => '/mshukla@patricbrc.org/home/Tests/m_vac_gDNA_80_1.fastq.gz',
                                   'interleaved' => 'false',
                                   'read2' => '/mshukla@patricbrc.org/home/Tests/m_vac_gDNA_80_2.fastq.gz'
                                 }
                               ],
          'reference_assembly' => ''
        };
$VAR3 = {
          'reference_assembly' => '',
          'paired_end_libs' => $VAR2->{'paired_end_libs'},
          'output_file' => 'Mvaccae_assembly',
          'output_path' => '/mshukla@patricbrc.org/home/Tests',
          'recipe' => 'auto'
        };
total 348
drwx------.   2 iris  iris         4096 Apr 20 14:14 .
drwxrwxrwx. 197 olson seed-users 348160 Apr 20 14:14 ..
-rw-rw-r--.   1 iris  iris            0 Apr 20 14:14 m_vac_gDNA_80_1.fastq.gz
$VAR1 = {
          '/mshukla@patricbrc.org/home/Tests/m_vac_gDNA_80_1.fastq.gz' => \*{'::$fh'}
        };
$VAR2 = [
          [
            '/mshukla@patricbrc.org/home/Tests/m_vac_gDNA_80_1.fastq.gz',
            $VAR1->{'/mshukla@patricbrc.org/home/Tests/m_vac_gDNA_80_1.fastq.gz'}
          ]
        ];
$VAR3 = [
          [
            [
              'm_vac_gDNA_80_1.fastq.gz',
              'reads',
              '/mshukla@patricbrc.org/home/Tests/',
              '2015-04-20T19:07:46',
              '87E7689C-E790-11E4-B953-CD0F692E0674',
              'mshukla@patricbrc.org',
              1131687135,
              {},
              {},
              'o',
              'n',
              'https://p3.theseed.org/services/shock_api/node/fdf33c91-21d5-44c2-b01e-e33a47e2d91d'
            ],
            'https://p3.theseed.org/services/shock_api/node/fdf33c91-21d5-44c2-b01e-e33a47e2d91d'
          ]
        ];
/mshukla@patricbrc.org/home/Tests/m_vac_gDNA_80_1.fastq.gz /scratch/tmp/ZYe3B09Ib5/m_vac_gDNA_80_1.fastq.gz:
total 1105512
drwx------.   2 iris  iris             4096 Apr 20 14:14 .
drwxrwxrwx. 197 olson seed-users     348160 Apr 20 14:14 ..
-rw-rw-r--.   1 iris  iris       1131687135 Apr 20 14:15 m_vac_gDNA_80_1.fastq.gz
total 1105512
drwx------.   2 iris  iris             4096 Apr 20 14:15 .
drwxrwxrwx. 197 olson seed-users     348160 Apr 20 14:14 ..
-rw-rw-r--.   1 iris  iris       1131687135 Apr 20 14:15 m_vac_gDNA_80_1.fastq.gz
-rw-rw-r--.   1 iris  iris                0 Apr 20 14:15 m_vac_gDNA_80_2.fastq.gz
$VAR1 = {
          '/mshukla@patricbrc.org/home/Tests/m_vac_gDNA_80_2.fastq.gz' => \*{'::$fh'}
        };
$VAR2 = [
          [
            '/mshukla@patricbrc.org/home/Tests/m_vac_gDNA_80_2.fastq.gz',
            $VAR1->{'/mshukla@patricbrc.org/home/Tests/m_vac_gDNA_80_2.fastq.gz'}
          ]
        ];
$VAR3 = [
          [
            [
              'm_vac_gDNA_80_2.fastq.gz',
              'reads',
              '/mshukla@patricbrc.org/home/Tests/',
              '2015-04-20T19:08:02',
              '91472E72-E790-11E4-B8CA-B310692E0674',
              'mshukla@patricbrc.org',
              1145147211,
              {},
              {},
              'o',
              'n',
              'https://p3.theseed.org/services/shock_api/node/ed5eb7b4-bd35-4e1f-a6c3-9a72aaa89531'
            ],
            'https://p3.theseed.org/services/shock_api/node/ed5eb7b4-bd35-4e1f-a6c3-9a72aaa89531'
          ]
        ];
/mshukla@patricbrc.org/home/Tests/m_vac_gDNA_80_2.fastq.gz /scratch/tmp/ZYe3B09Ib5/m_vac_gDNA_80_2.fastq.gz:
total 2223824
drwx------.   2 iris  iris             4096 Apr 20 14:15 .
drwxrwxrwx. 197 olson seed-users     348160 Apr 20 14:14 ..
-rw-rw-r--.   1 iris  iris       1131687135 Apr 20 14:15 m_vac_gDNA_80_1.fastq.gz
-rw-rw-r--.   1 iris  iris       1145147211 Apr 20 14:15 m_vac_gDNA_80_2.fastq.gz

GET WS => /scratch/tmp/ZYe3B09Ib5 m_vac_gDNA_80_1.fastq.gz /mshukla@patricbrc.org/home/Tests/m_vac_gDNA_80_1.fastq.gz
GET WS => /scratch/tmp/ZYe3B09Ib5 m_vac_gDNA_80_2.fastq.gz /mshukla@patricbrc.org/home/Tests/m_vac_gDNA_80_2.fastq.gz
Running ar-run -r auto --pair /scratch/tmp/ZYe3B09Ib5/m_vac_gDNA_80_1.fastq.gz /scratch/tmp/ZYe3B09Ib5/m_vac_gDNA_80_2.fastq.gz
Error submitting run. Run command=ar-run -r auto --pair /scratch/tmp/ZYe3B09Ib5/m_vac_gDNA_80_1.fastq.gz /scratch/tmp/ZYe3B09Ib5/m_vac_gDNA_80_2.fastq.gz, stdout:

stderr:
HTTP error: Bad Gateway (HTTP status code 502)

**Comment by mshukla1** [comment]
Assigned to Bob: "Lost the arast control server. We should figure out why this keeps crashing here."

**Comment by olsonanl** [comment]
Closing; proper solution is covered elsewhere (at least in #369 ... this is in the general realm of "engineer better for failure).
