### ISSUE TITLE
Outdated Product names displayed in Search results? 

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#1671]
Gene functions (="Product" field in Patric) shown in Search results are seriously off:  they are outdated and do not correspond to the actual functions (= Product) currently in PATRIC.  Where do they even come from..? These Product names are not displayed on the corresponding protein pages in PATRIC any more.  Can this bug be due to outdated indexing in Patric...? 
This bug affects only  search results for "Genome features"; while the search results for "Specialty genes" show current, NOT outdated Product names (see example #2 below).  Weird....

Example #1:  if you try searching by "Tet(50)", you will get the following search results, none of which are Tet(50) actually: 
<img width="713" alt="screen shot 2017-08-22 at 10 29 46 pm" src="https://user-images.githubusercontent.com/20665963/29597613-6cee5c6c-8789-11e7-8098-7b2e91b8c71c.png">

Example #2:  try searching by "Tet(32)", you will get the following search results: 
<img width="676" alt="screen shot 2017-08-22 at 10 14 37 pm" src="https://user-images.githubusercontent.com/20665963/29597317-759aaf7a-8787-11e7-965e-0233afad4102.png">

**Comment by mshukla1** [comment]
This is not an indexing bug. 

In the search result, you are looking at a RefSeq annotation matching your search criteria. When you click on it, it takes you to the corresponding gene annotated by PATRIC, if available. Often, For the same gene, the function assigned by Patric and RefSeq could be quite different! 

-Maulik

**Comment by Sveta-user** [comment]
Maulik, please consider displaying Patric annotations on the Search page by default, NOT RefSeq annotation.  Pretty please....  
-- first, because ever since you and Bob have established regular annotation update cycles -  our in-house Patric annotations became better than those from Refseq
-- second, it is confusing for a user to see one function in search results, and a completely different one on the actual gene page!  Especially because it is not explained anywhere....  
-- third, the default annotations for Specialty Genes Search results are Patric's.   So a user faces this additional contradiction on the Search results page itself! 

And if you really want to keep RefSeq annotations available to users -  maybe we could add them to each gene page?  I really like how you display the AMR data from 3 sources + from PATRIC.  Could Patric do the same for the Product field maybe?  Showing in-house Patric annotations and those from Refseq side by side?   What do you think?

**Comment by chmao1** [comment]
#1113

**Comment by chmao1** [comment]
Fixed and will be available in the next build.

**Comment by chmao1** [comment]
Verified on alpha.

**Comment by Sveta-user** [comment]
Thank you !!  Search results look really clean and satisfying now.  I mean, you get exactly what you asked for, nothing more, nothing less. Cool!

**Comment by chmao1** [comment]
@Sveta-user Thanks for testing and the feedback. I'm glad that my fixes work as expected.
