### ISSUE TITLE
Weird characters (in AMR genes) break Search

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#1672]
Patric does not allow to search for any text string containing weird characters (even between quotation marks), including:
prime
prime-prime
 =>
slash
and others

SEED curators have been using these characters a lot for AMR genes, as  there is no other way to annotate them without, unfortunately...  So it is really important for PATRIC Search engine to accommodate these weird characters now.  Note, that the search engine Bob created for SEED tolerates them all well.  
Examples -
Tetracycline resistance, MFS efflux pump => Tet(B)
Tetracycline resistance, ribosomal protection type => Tet(32)
Aminoglycoside 7''-phosphotransferase (EC 2.7.1.-) => APH(7'')-I
Class A beta-lactamase (EC 3.5.2.6) => CARB family, carbenicillin-hydrolyzing
Aminoglycoside 3'-phosphotransferase (EC 2.7.1.95) => APH(3')-III/APH(3')-IV/APH(3')-VI/APH(3')-VII

**Comment by chmao1** [comment]
Fixed and will be available in the next build.

**Comment by hyoo** [comment]
this fix is available on alpha now.

**Comment by Sveta-user** [comment]
THANK YOU !

**Comment by chmao1** [comment]
Verified on alpha.

**Comment by Sveta-user** [comment]
I love how search work on Alpha now!!  It finds ANYTNG you ask it, even smth weird like this, for example:   Aminoglycoside N(6')-acetyltransferase (EC 2.3.1.82) => AAC(6')-Ib/AAC(6')-II
Great!

**Comment by chmao1** [comment]
Great! Thanks for the feedback.
