### ISSUE TITLE
add explanation of what a workspace is

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#1673]
Perhaps here:

![image](https://user-images.githubusercontent.com/1194246/29637872-22962856-881b-11e7-9435-d13c67c93cb7.png)

**Comment by mshukla1** [comment]
There is a link to the workspace user guide in the green action bar now, which addresses this issue. 

<img width="706" alt="Screen Shot 2019-04-15 at 8 25 57 PM" src="https://user-images.githubusercontent.com/1236463/56175442-d1ceeb80-5fbc-11e9-8704-a4195a9758ce.png">
