### ISSUE TITLE
Increase disk space prior to workshop

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1675]
We seem to have a problem with this for each workshop.  We should make sure that there will be enough space prior to a workshop.  Here is an error message from a job submitted during the ANL workshop in August:
From a Tn-Seq job from yesterday
Traceback (most recent call last):
File "/disks/p3/deployment/pybin/p3_tnseq.py", line 301, in 
main(server_setup, job_data)
File "/disks/p3/deployment/pybin/p3_tnseq.py", line 261, in main
run_alignment(genome_list, library_dict, job_data)
File "/disks/p3/deployment/pybin/p3_tnseq.py", line 174, in 
run_alignment
subprocess.check_call(cur_cmd) #call bowtie2
File "/disks/patric-common/runtime/lib/python2.7/subprocess.py", line 
540, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tpp', '-bwa', 'bwa', '-ref', 
'/disks/awe/work/72/f8/26/72f82693-660d-4a0f-afbd-5fde702eb2fe_0_0/work/83332.12.fna', 
'-reads1', 
u'/disks/awe/work/72/f8/26/72f82693-660d-4a0f-afbd-5fde702eb2fe_0_0/work/U19_92_R1.fastq.gz', 
'-output', 
u'/disks/awe/work/72/f8/26/72f82693-660d-4a0f-afbd-5fde702eb2fe_0_0/work/treatment2']' 
returned non-zero exit status 1
close failed in file object destructor:
IOError: [Errno 28] No space left on device
Command failed: p3_tnseq --jfile 
/disks/awe/work/72/f8/26/72f82693-660d-4a0f-afbd-5fde702eb2fe_0_0/jobdesc.json 
--sstring
{"data_api":"https://www.patricbrc.org/api/"}
-o 
/disks/awe/work/72/f8/26/72f82693-660d-4a0f-afbd-5fde702eb2fe_0_0/work

**Comment by olsonanl** [comment]
I have found an issue where temp data from variation jobs were not cleared; this will help.
After tomorrow's downtime when we move the mongo database for shock off our main compute node will also help.

The technical solution for making jobs not fail in the case of short disk space is tracked at #1696

**Comment by rkenyon** [comment]
Closing since covered by #1696
