### ISSUE TITLE
Strain name visible on genome landing page, but not in taxon genome list table

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1679]
The strain should be visible in both places.  Two screenshots below
<img width="1167" alt="screen shot 2017-08-24 at 5 34 01 pm" src="https://user-images.githubusercontent.com/11475316/29689815-921c06dc-88f2-11e7-8fa7-216dae923883.png">

<img width="1222" alt="screen shot 2017-08-24 at 5 33 49 pm" src="https://user-images.githubusercontent.com/11475316/29689825-9700de84-88f2-11e7-8a8a-33b3f686bba5.png">

**Comment by mshukla1** [comment]
There was a bug in the data parsing script which ended up adding genome names without strain in the genome_amr table. I have corrected all data and scripts. 

-Maulik
