### ISSUE TITLE
user reports error with compare region viewer

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1680]
q is undefined"
I was trying to look at the gene context of fig|655184.88.peg.5877 but it 
also does not work with other genes.

**Comment by hyoo** [comment]
#1664 
This is fixed on alpha. will be deployed soon.

**Comment by ARWattam** [comment]
When is it expected to go to production?

Thanks,

Rebecca

**Comment by hyoo** [comment]
If this is urgent, i can release it tonight. Otherwise, I am going to wait other bug fixes by Wednesday, and deploy them together by Wednesday evening or early morning on Thursday.

**Comment by hyoo** [comment]
this is available on production now.
