### ISSUE TITLE
Problems with RNA-seq jobs during ANL workshop

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1682]
From Andrew Warren, and he says the following:

All RNASeq jobs failed last night and this morning. The same input worked a 
month ago.
Traceback (most recent call last):
File "/disks/patric-common/runtime/bin/prok_tuxedo.py", line 243, in 
main(genome_list,library_dict,args.p,output_dir,gene_matrix)
File "/disks/patric-common/runtime/bin/prok_tuxedo.py", line 164, in 
main
run_alignment(genome_list, library_dict, parameters, output_dir)
File "/disks/patric-common/runtime/bin/prok_tuxedo.py", line 67, in 
run_alignment
subprocess.check_call("samtools index "+bam_file, shell=True)
File "/disks/patric-common/runtime/lib/python2.7/subprocess.py", line 
540, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'samtools index 
/scratch/tmp/FMTczs1nVo/Rocket/208964.12/PAO1_algZH175A/replicate1/H17SA-1_S25_L008_R1_001.fastq.bam' 
returned non-zero exit status 1
App	RNASeq
Job ID	1260925e-266b-4529-8d42-1d060f4bea7f
Status	failed
Submitted	2017-08-16T07:31:34.749-05:00
Start	2017-08-16T08:31:47.743-05:00
Completed	0001-01-01T00:00:00Z

**Comment by aswarren** [comment]
This was due to disk full.
