### ISSUE TITLE
Downloading data through website does not get all available genomes

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1684]
We have had two users that have recently noted discrepancies in the data that appears to be available for download in PATRIC, and the number that actually comes with the download.  Here is one user request that notes this (PATRIC 968):

I decided to download genome files (faa and others) and parse them locally. I was wondering why can I locate only 5810 Escherichia coli files out of 6296 that can be found in "genome_summary".

**Comment by mshukla1** [comment]
This was due to missing download files after the last release. I have updated all download files on the FTP site. The problem should be solved now. 

-Maulik
