### ISSUE TITLE
Keeping track of PATRIC tool use

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1685]
I would like to keep track of PFS, CPV, BLAST and Similar Genome Finder jobs.  My goal is to have a detailed analysis of the services and tools in PATRIC, and how much they are used by our community.  I recognize that PFS and CPV are deployed at taxon levels, but I think we could look at the jobs submitted through the services tab to keep track of this.

Also ID Mapping.

**Comment by hyoo** [comment]
Service usage can be viewed here
https://analytics.google.com/analytics/web/#report/content-event-overview/a11736060w124923404p129251014/%3Foverview-dimensionSummary.selectedGroup%3Dvisitors%26overview-dimensionSummary.selectedDimension%3Danalytics.eventAction/

<img width="992" alt="image" src="https://user-images.githubusercontent.com/1236467/33689463-2a342202-daa5-11e7-9bae-ae900b458dc7.png">

or in full report

https://analytics.google.com/analytics/web/#report/content-event-events/a11736060w124923404p129251014/%3Fexplorer-segmentExplorer.segmentId%3Danalytics.eventAction/
