### ISSUE TITLE
Burkholderia ubonensis is not included in the Burkholderia cepacia complex and it should be.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1686]
User reports that ubonensis is part of the B. cepacia complex, but this is not reflected in PATRIC.  Looking at NCBI taxonomy, it should be.

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=101571&lvl=3&lin=f&keep=1&srchmode=1&unlock

**Comment by mshukla1** [comment]
Recent updates in taxonomy data at PATRIC has taken care of this. IT is now part of the complex. 

<img width="1012" alt="screen shot 2018-07-14 at 9 53 58 am" src="https://user-images.githubusercontent.com/1236463/42725603-13301d14-874c-11e8-8531-2e519ea5e1ee.png">
