### ISSUE TITLE
Request for ftp uploader

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1688]
Several participants at workshops (JIRA-938 and 939, to name a few) have requested the ability to do a batch upload by ftp.  It seems to be quite tedious for them to upload them one by one, and also some of the files that they are getting from sequencers are difficult to transfer over by the path they must follow in the PATRIC interface.  We should enable this functionality.

**Comment by nconrad** [comment]
I think this was done and now we just need a tutorial?  #1986 covers the need for tutorial.  Closing.
