### ISSUE TITLE
Adding new member to an existing group can cause disconnect in workspace table

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#169]
I created a group that I wanted to include 38 features.  After I created the group and saved it, I realized that I hadn't resized the table, so the group only contained 20 features.  I resized the table and added all features to the same group.  When I went to my workspace, then to features, it looked like there were 58 features in that group (20 first and then 38 added), but it should be 38.
![screen shot 2015-04-17 at 11 52 50 am](https://cloud.githubusercontent.com/assets/11475316/7205636/a173abda-e4f8-11e4-866f-4c1c8ee9fa50.png)

When I opened the group, it only had 38.  Also, when I went back to the table, it still said 58.
![screen shot 2015-04-17 at 11 56 11 am](https://cloud.githubusercontent.com/assets/11475316/7205663/c4934bfc-e4f8-11e4-994f-add3fcef5f2e.png)

**Comment by hyoo** [comment]
I thought I reported the same problem and Dustin fixed it, but I cannot find the ticket. Dustin, it seems like the size is not counting actually number of ids, but replying on a counter that is increased when items are added to the group. Or is this a auto-metadata?

**Comment by mshukla1** [comment]
Dustin, this is still an issue. If I add the same genome twice to the same group, it gets counted twice in the genome count displayed in the group list. Please see if it can be addressed before the release.

**Comment by dmachi** [comment]
This occurs because addToGroup simply appends a list of ids to the exist list of group Ids.  I have added a filter in to avoid this for any new groups created, but cannot solve it for existing groups as part of the application.  We could write a script that loads all the existing groups and resaves them with duplicates removed, but prob not before release.  I will deploy to beta this evening.

**Comment by mshukla1** [comment]
Looks like this is resolved. I tried to add the same genomes multiple times to the same group and it didn't inflate the counts.
