### ISSUE TITLE
Taxonomy of Burkholderia vietnamiensis incorrect in PATRIC-does not reflect its place in the Burkholderia cepacia complex

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1691]
A user has noted problems that we have with our Burkholderia taxonomy in PATRIC, and that it leaves out several species out of the  Burkholderia cepacia complex.  Burkholderia vietnamiensis is needs to be included
<img width="1141" alt="screen shot 2017-08-30 at 8 33 33 am" src="https://user-images.githubusercontent.com/11475316/29872581-346c9928-8d5e-11e7-83f3-c5e2694ab38e.png">

**Comment by ARWattam** [comment]
[Burkholderia cepacia complex_list species.docx](https://github.com/PATRIC3/patric3_website/files/1263566/Burkholderia.cepacia.complex_list.species.docx)

**Comment by mshukla1** [comment]
This has been addressed with the recent taxonomy updates. 

<img width="1214" alt="screen shot 2018-07-14 at 12 51 57 pm" src="https://user-images.githubusercontent.com/1236463/42728178-06736c88-877a-11e8-8c1c-9273d7fca60c.png">

**Comment by mshukla1** [comment]
Note that in the bread crumbs we show only select taxonomy levels, i.e. genus and species, not sub genus or sub species, to limit the length of the Bread crumbs.
