### ISSUE TITLE
Venn Diagram-creating group from selected region does not give any indication that it is working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1698]
I think that this needs a pop-up or something that indicates that the group was created.  I only saw it when I went in and checked my groups.  It would also be nice if I was allowed to name it, like I am for every other group in PATRIC, but I can settle for it the way it is.

**Comment by chmao1** [comment]
The message "The group has been successfully created. Click here to view" appears above the venn diagram (see the screenshot, the highlighted part). Is this acceptable?
![image](https://user-images.githubusercontent.com/6361802/30167387-39fdcb30-93b4-11e7-8f74-078bcf3b9a15.png)

**Comment by chmao1** [comment]
Fixed and will be available in the next build.

**Comment by chmao1** [comment]
@ARWattam could you test this issue on alpha and let me know whether you're satisfied with the fix. Thanks!

**Comment by hyoo** [comment]
@maovt I guess this must be deployed on production. Would you double check and close this issue?

**Comment by chmao1** [comment]
tested and verified on production.
