### ISSUE TITLE
Assembly fails with filenames with special characters

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1700]
Parentheses in user read filenames cause assembly service to fail:

Enabling curl due to large files:
\@submit_cmd = $VAR1 = [
          'ar-run',
          '-r',
          'auto',
          '--single',
          '/scratch/tmp/TsQaCSXqVq/WIS_14(389)_S5_L004_R1_001.fastq',
          'platform=infer',
          '--curl'
        ];
Running ar-run -r auto --single /scratch/tmp/TsQaCSXqVq/WIS_14(389)_S5_L004_R1_001.fastq platform=infer --curl
Error submitting run. Run command=ar-run -r auto --single /scratch/tmp/TsQaCSXqVq/WIS_14(389)_S5_L004_R1_001.fastq platform=infer --curl, stdout:

stderr:
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `arast run -r auto --single /scratch/tmp/TsQaCSXqVq/WIS_14(389)_S5_L004_R1_001.fastq platform=infer --curl '

**Comment by mshukla1** [comment]
#1949 duplicate.
