### ISSUE TITLE
Similar Genome Finder: file selection doesn't work

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1702]
Upload FASTA and file selection box needs to be consistent with other services. 

The dropdown menu showing recent fasta files look different than that on other services. 

When I click on the folder icon and select a fasta file from the public workspace, PATRIC Workshop, it doesn't show up in the box. 

-Maulik

**Comment by hyoo** [comment]
@dawenx since you are familiar to other service submission form, would you take a look?

**Comment by dawenx** [comment]
@hyoo i saw two ways of using WorkspaceObjectSelector, one is to defined it in the template and the other is to create the instance in startup(). this one and a few others like ProteinFamily.js and ComparativePathway.js, are doing it in startup(). once i added "this.inherited(arguments);" in startup(), i'm able to select a fasta file from a folder that's not visited before. BUT, i broke the whole app, no matter what i select, even using GenomeNameSelector to choose a genome, i got below error:

We were not able to complete your request. Please let us know with detail message below.

SyntaxError: Unexpected token < in JSON at position 0

can you look at it? i don't know have information on the backend to dig into it more.

**Comment by hyoo** [comment]
no that is coming from bundle.js, where i bundled multiple external libraries. For some reason, it triggers sending message with empty string, it complains that the empty cannot be parsed with JSON parser. Don't worry about this part and send PR for your fix.

**Comment by dawenx** [comment]
OK, PR sent...

**Comment by hyoo** [comment]
deployed on production
