### ISSUE TITLE
Job id should be part of job output directory

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1705]
I did a variation analysis and was looking for the job id and couldn't find it.  I had to go to the jobs page, which is a bad place to get it if you are doing a lot of jobs.

![image](https://user-images.githubusercontent.com/7661533/30284315-30fd263c-96e0-11e7-89b6-0ec563a763d6.png)

**Comment by zreyn** [comment]
I'm not sure I understand this request.  What does it mean for the job id to be "part of job output directory"?  Does that mean it's in the directory name?  As a file in the directory?  

You can find job ids from the jobs page without having to navigate to the job detail page:
<img width="557" alt="jobid-ss" src="https://user-images.githubusercontent.com/10354900/30596077-1fc60a5e-9d21-11e7-8fb7-bbfcb05aa253.png">

**Comment by zreyn** [comment]
I'll be modifying the job result page, as part of #1632, so I will include some of this information in the header as well.

**Comment by zreyn** [comment]
Headed to alpha in [PR #566](https://github.com/PATRIC3/p3_web/pull/566)

**Comment by zreyn** [comment]
PR for develop branch: https://github.com/PATRIC3/p3_web/pull/573

**Comment by hyoo** [comment]
deployed on production
