### ISSUE TITLE
Circular viewer does not display uploaded file

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1706]
I was at this genome:
https://www.patricbrc.org/view/Genome/1351.436#view_tab=circular
and uploaded the attached file
[test upload.txt](https://github.com/PATRIC3/patric3_website/files/1299867/test.upload.txt)
Although it looks it should be loaded, based on what you can see in the left side display, but nothing appears in the view (see screen shot)
<img width="1284" alt="screen shot 2017-09-13 at 11 03 54 am" src="https://user-images.githubusercontent.com/11475316/30384806-519fe962-9873-11e7-8521-8b8a9834733d.png">

**Comment by chmao1** [comment]
Fixed and will be available in the next build.

**Comment by chmao1** [comment]
verified on alpha
