### ISSUE TITLE
Circular viewer-non CDS features in view, but color not in side panel

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1707]
I'm at this genome:
https://www.patricbrc.org/view/Genome/1351.436#view_tab=circular

The third track in is light blue.  Hovering over the lines I can see that they are non-CDS features, but  on the left side, that particular line has not color attached to it.
<img width="1284" alt="screen shot 2017-09-13 at 11 03 54 am" src="https://user-images.githubusercontent.com/11475316/30385004-d494c3b0-9873-11e7-9029-df600e6d8e59.png">

**Comment by chmao1** [comment]
The foreground color display on the left side for non-CDS features was disabled because this track contains multiple colors representing multiple types of non-CDS features.
