### ISSUE TITLE
Text search box on feature page producing some odd results that don't contain the right text.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1708]
I am on this page:
https://www.patricbrc.org/view/Genome/1351.436#view_tab=features&filter=and(or(eq(feature_type,%22CDS%22)),or(eq(annotation,%22PATRIC%22)),false)

I entered the word "tetracycline" in the text box filter at the top, but it returns a lot of genes that do not have tetracycline anywhere.
<img width="1359" alt="screen shot 2017-09-13 at 11 09 55 am" src="https://user-images.githubusercontent.com/11475316/30385182-5c79daf4-9874-11e7-8329-bc237a71487b.png">

**Comment by hyoo** [comment]
if you go to feature overview page (select a row and click "F"), you will see it matches some pathway names.

![image](https://user-images.githubusercontent.com/1236467/30385454-dc48b802-986c-11e7-84fe-08c3b21f2eda.png)

**Comment by ARWattam** [comment]
Ahh....well now I understand.  Thanks for the enlightenment.
