### ISSUE TITLE
Proteome comparison allows comparison against contigs

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1709]
One can apparently submit a genome comparison against contig data (cf job f7e54a54-25e2-4e85-8e6d-38a01ff6f91d). It causes BLAST to blow up and use huge memory and does not work anyway.

```
$VAR2 = {
          'output_path' => '/nida@patricbrc.org/home/Experiment Groups',
          'output_file' => 'proteome comparison',
          'user_genomes' => [
                              '/nida@patricbrc.org/home/ATCC_BAA835.fasta',
                              '/nida@patricbrc.org/home/NM1_reorder.fna.fas'
                            ],
          'genome_ids' => [
                            '1647988.3'
                          ],
          'max_e_val' => '1e-5',
          'min_seq_cov' => '0.3',
          'reference_genome_index' => 2,
          'min_ident' => '0.1'
        };
```

This is a case where the user uploaded data and declared them protein, but they were contig

```
olson@beech:~$ ws-ls -a '/nida@patricbrc.org/home'
Name                Owner              Type                  Moddate             Size    User perm Global perm
Experiments         nida@patricbrc.org folder                2017-09-12T04:58:58       0 n         n          
Genome Groups       nida@patricbrc.org folder                2017-09-12T04:58:58       0 n         n          
Experiment Groups   nida@patricbrc.org folder                2017-09-12T04:58:58       0 n         n          
Feature Groups      nida@patricbrc.org folder                2017-09-12T04:58:58       0 n         n          
NM2_reorder.fna     nida@patricbrc.org contigs               2017-09-12T05:15:12 2830775 n         n          
output              nida@patricbrc.org folder                2017-09-12T05:18:52       0 n         n          
ATCC_BAA835.fasta   nida@patricbrc.org feature_protein_fasta 2017-09-13T06:50:08 2702228 n         n          
NM1_reorder.fna.fas nida@patricbrc.org feature_protein_fasta 2017-09-13T06:51:17 3039677 n         n          
olson@beech:~$ ws-cat --shock -a '/nida@patricbrc.org/home/ATCC_BAA835.fasta'
>CP001071.1 Akkermansia muciniphila ATCC BAA-835, complete genome
AAATCTTATAAAATAACCACATAACTTAAAAAGAATTATGCGGATTTTTAATCCGTCCCCGGCTACGGCT
TCTCCGAGCCTTTCGGGTTTAGCTGCTCTGATGATGCGCCGCAGCATCTAAAACCCATTTCCCCCCCCTC
CGCCGGATTTCCAAAAACAATGCGGTTTTTTATTTTCCAGTACCTGTCCGGTATCGGAGCCTTCACTTCA
TGCGGCATCCTGAACGGCAAAATCCTGAGAAAAGAAAACGCAGCTTCTCACAAGCGAGATTCCAATCCAA
CATTCATATCCCCGTGTGGATATGTGCACCGGAATAACAGTACTCCACGGTTTTCCAGGGCGGAAAGTGC
CGGGGGGAGGCTTCCAATTGTCAATCAAGCTGTGCATCATTGTGCATGCTTTTTTGACCATATGATACCC

I suspect at least part of the solution is a last-chance check in the app to ensure it has protein and not contig data. We should probably think about type-checking uploads that are marked as protein data.

**Comment by chmao1** [comment]
Actually, proteome comparison service only allows feature_protein_fasta type not contigs type. However, when the user uploads the fasta file from the workspace uploader, if the file contains contig data, but the user selects feature_protein_fasta type instead of contigs, the file is upload as feature_protein_fasta type. This was probably the reason for this problem.  Currently, PATRIC workspace uploader utility only checks the file format, not the content. It does not distinguish aa sequences from nt sequences. This needs to be better handled.

**Comment by olsonanl** [comment]
Agreed. But until that happens I'd like to have a check in the proteome tool itself since it seems to bear the brunt of mislabeled uploads and results in badness on the backend server.

**Comment by chmao1** [comment]
@levinas Can you handle this from the server side?

**Comment by chmao1** [comment]
@olsonanl Is this still an issue?

**Comment by olsonanl** [comment]
I have not made any changes to the service. If one can still submit contigs data it's still an issue.

**Comment by chmao1** [comment]
@olsonanl The Proteome Comparison service does not accept the config file type. It only accepts the protein fasta type when users update the user fasta file. It works for me. Could you check again to see whether this is still an issue? Thanks.

**Comment by olsonanl** [comment]
Right, the problem we had was that people were explicitly giving contigs files the protein-fasta type. What we need is the service to detect DNA-only input and reject it.

On Aug 17, 2018, at 12:22 PM, maovt <notifications@github.com<mailto:notifications@github.com>> wrote:


@olsonanl<https://github.com/olsonanl> The Proteome Comparison service does not accept the config file type. It only accepts the protein fasta type when users update the user fasta file. It works for me. Could you check again to see whether this is still an issue? Thanks.

**Comment by chmao1** [comment]
Fixed and available in production
