### ISSUE TITLE
Alignment length is not reported in blast ouput.

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1714]
I got really confused by the "Length" column, which I was expecting to be alignment length.  This is the most common length output for BLAST. I realized that alignment length is not reported.  It should be.

Also, 
1.  The name of the "Length" column should be changed to "Subject Length".  
2. The Query Length should be reported as a column (i know its in the window output above the alignment,  but having one as a column but not the other is weird).

![image](https://user-images.githubusercontent.com/7661533/30497117-4bb89f94-9a17-11e7-970b-d09d080f84a4.png)

![image](https://user-images.githubusercontent.com/7661533/30497141-65d4805a-9a17-11e7-866a-1d2b91bb1a96.png)

**Comment by hyoo** [comment]
Jim, which website are you using? 
Please use www.alpha.patricbrc.org or production website, www.patricbrc.org

Your column setting looks different.

![image](https://user-images.githubusercontent.com/1236467/30502267-222ee994-9a2b-11e7-8a68-cded7129d7fb.png)

**Comment by hyoo** [comment]
never mind. It seems like you are searching against faa.

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/30502979-169c6e78-9a2e-11e7-8c16-43c53cb37bf2.png)

fixed. deployed on alpha now.
