### ISSUE TITLE
Change file type for multiple files

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1715]
It would be good to allow users to select multiple files in the worskpace and change their file types in batch mode, by providing an action button in the green bar. 

-Maulik

<img width="1134" alt="screen shot 2017-09-17 at 11 01 17 am" src="https://user-images.githubusercontent.com/1236463/30522563-cd39fc44-9b97-11e7-9fd4-a6212bf2124e.png">

**Comment by nconrad** [comment]
![image](https://user-images.githubusercontent.com/1194246/34176740-afb67116-e4c6-11e7-8dab-282fcc75276f.png)

**Comment by hyoo** [comment]
This feature was demonstrated on sys dev call and confirmed working on alpha.
