### ISSUE TITLE
Grid general: Cannot select across pages.

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1719]
Here is how to produce error.

https://www.alpha.patricbrc.org/view/Taxonomy/1386#view_tab=genomes

select first two rows,

![image](https://user-images.githubusercontent.com/1236467/30611156-2fe6db5a-9d46-11e7-9595-547a172b3f82.png)

go to 2nd page, and select first two as well,

![image](https://user-images.githubusercontent.com/1236467/30611167-39bd364c-9d46-11e7-931a-fc6b1d9d0f28.png)

and click "genomes" button in the selection action bar,

![image](https://user-images.githubusercontent.com/1236467/30611185-4f43d700-9d46-11e7-8015-ac13e07f680a.png)

you will see undefined error.

Please discard the JSON related error, this is another issue and i am working on it.

**Comment by dawenx** [comment]
@hyoo with lots of help from @dmachi , i think i got it fixed. PR submitted.

**Comment by dawenx** [comment]
deployed to alpha a few days ago, need more testings from team members, but it passed my tests.
