### ISSUE TITLE
BLAST doesn't accept sequence with spaces between amino acids

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1727]
A user pointed this out when trying to do a BLAST.  The user also stated: "More informative error message would be better."

**Comment by mshukla1** [comment]
I ran blastp on the patric website with a protein sequence with a bunch of spaces in it and it worked fine. So, I don't understand the issue. I am going to ask user to provide the exact sequence for debugging. 

MSIEKLKAALPEYAK  DIKLNLSSITRSSVLDQEQLWGTLLASAAATRNPQVLADIGAEAT
DHLSAAARHAALGAAAIMG  MNNVFYRGRGFLEGRYDDLRPGLRMNIIANPGIPKANFELW
SFAVSAINGCSHCLVAHEHTLR  TVGVDREAIFEALKAAAIVSGVAQALATIEALSPS

**Comment by mshukla1** [comment]
Never mind, I see that user did provide a sample sequence. I tried it and it did not work. 
I think we can remove any white spaces  from the query sequence before posting it.  

M R Q V E A L V E A S K E E V K A A A A P V T G P L A D D P I Q F D D F A K 
V D L R V A L I E N A E F V E G S D K L L R L T L D L G G E K R N V F S G I 
R S A Y P D P Q A L I G R H T I M V A
