### ISSUE TITLE
0 byte size after copying

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#1728]
I just copied the annotation files from `/PATRIC/PATRIC Workshop/Annotations` to my own workspace twice, and both times the same 3 out of 4 visible files are showing 0B.  The files are there, the size is just wrong.  I think we really ought to prioritize a fix.

![image](https://user-images.githubusercontent.com/1194246/30756774-a8fc2818-9f91-11e7-876d-01560fe4d1d6.png)

**Comment by mshukla1** [comment]
@olsonanl, do you know what is going on here?

**Comment by olsonanl** [comment]
No, I attribute it to more flaky ws code that I want to replace.

**Comment by olsonanl** [comment]
The problem appears to be related to the workspace reviewer tokens not being able to access shock data. Not clear why things aren't a lot more flaky if that is true.

**Comment by olsonanl** [comment]
Here's the bug: apparently after a copy, sometimes, the node's owner is not given read permissions. This causes the call that populates the size field to fail with an authorization error.

**Comment by olsonanl** [comment]
Here's the deal .. a large number (140K or so) of nodes in Shock had no "read" acl entries for the owner of the node (the reviewer account that owns the shock nodes on behalf of the workspace). 

This script:

https://github.com/olsonanl/Workspace/blob/master/fix-shock-acls

finds any shock node owned by reviewer that does not have read access for reviewer and adds it. I ran this on the system and it fixed the problem of copying from the workspace in the original bug. @nconrad if you go to your folder where you'd copied the data I believe you should get sizes on the shock files.

It's possible we still have a copy bug with non-shock files. I'll need to look into that as well. (It appears that on a copy of a file in the workspace the size field is not copied).

**Comment by nconrad** [comment]
Cool.  Yeah, the contig files have sizes now.  The job_result files are still 0 (assuming those are non-shock).  

![image](https://user-images.githubusercontent.com/1194246/33857531-b36e179a-de91-11e7-82bd-806f445de519.png)

Testing again gives same:

![image](https://user-images.githubusercontent.com/1194246/33857582-e5b476d6-de91-11e7-8516-cacefed97c83.png)

**Comment by olsonanl** [comment]
Yup, they are. I need to look at that (tomorrow) then we can close this out.

**Comment by olsonanl** [comment]
I have run another fixup script to correct the zero-sized non-shock files, and committed this fix to the workspace that fixes the underlying problem on copy: 
https://github.com/olsonanl/Workspace/commit/859edbb66bae39daf9a6e4e20c70256b34660765
