### ISSUE TITLE
HPI-PPI not working

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#173]
In HPI-PPI tool, no matter what organism or option I select, "View N interactions" button keeps showing spinning wheel. Also, interaction tab at the genome level also shows only spinning wheels.   

-Maulik

**Comment by hyoo** [comment]
This is due to the facet that old data api path changed in recent release. Need to change source code (base url for the api). will work on it

**Comment by hyoo** [comment]
this is fixed and available on production.
