### ISSUE TITLE
Failure trying to submit a metabolic reconstruction job

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1730]
Here is the error message I got:
submit failed: Can't connect to walnut.mcs.anl.gov:7080 (Connection refused) LWP::Protocol::http::Socket: connect: Connection refused at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/LWP/Protocol/http.pm line 49. { "info" : { "priority" : 2, "userattr" : { "parameters" : "{\n \"fulldb\" : 0,\n \"output_file\" : \"E_coli_MRSN388634\",\n \"media\" : \"/chenry/public/modelsupport/patric-media/7H9\",\n \"output_path\" : \"/ARWattam@patricbrc.org/home/Metabolic_Reconstruction\",\n \"genome\" : \"PATRICSOLR:562.10627\"\n}\n", "workspace" : null, "app_id" : "ModelReconstruction", "task_file_id" : "bc6834fc-a061-11e7-8687-59d2682e0674" }, "clientgroups" : "AppService-p3.theseed.org", "project" : "AppService", "user" : "ARWattam@patricbrc.org", "name" : "ModelReconstruction", "pipeline" : "AppService" }, "tasks" : [ { "userattr" : {}, "outputs" : [ { "filename" : "awe_stdout.txt", "name" : "awe_stdout.txt", "node" : "-", "host" : "http://p3.theseed.org/services/shock_api" }, { "filename" : "awe_stderr.txt", "name" : "awe_stderr.txt", "node" : "-", "host" : "http://p3.theseed.org/services/shock_api" } ], "dependsOn" : [], "cmd" : { "name" : "App-ModelReconstruction", "args" : "https://p3.theseed.org/services/app_service/task_info @app @params", "description" : "App-ModelReconstruction", "taskid" : "0", "inputs" : [ { "filename" : "app", "name" : "app", "node" : "f9fabd86-d180-4877-b559-b9c4ed0168c5", "host" : "http://p3.theseed.org/services/shock_api" }, { "filename" : "params", "name" : "params", "node" : "1039e454-85bd-4b67-b875-f825972df74d", "host" : "http://p3.theseed.org/services/shock_api" } ], "partinfo" : {}, "skip" : 0, "totalwork" : 1 } ] }
Reset
 
Reconstruct

**Comment by mshukla1** [comment]
Metabolic reconstruction service seems to be working now. closing the ticket.
