### ISSUE TITLE
Finding some genomes that have geographic location, but it is not listed in table

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1734]
I have been looking at Brucella melitensis data and I have found a bunch of genomes that were apparently added somewhat recently, but they don't have country data.  When I look at the data for the selected genome in the table, I can see the country listed beyond the green bar
<img width="1418" alt="screen shot 2017-09-26 at 4 19 18 pm" src="https://user-images.githubusercontent.com/11475316/30882404-cd067e1e-a2d6-11e7-93a1-e9526db855d4.png">

**Comment by mshukla1** [comment]
I have added missing isolation country infor for ~15,000 genomes, where information was already available in the geographic location. 

-Maulik
