### ISSUE TITLE
Impossible to quickly see in progress jobs

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1737]
The only way to see my "in progress" jobs is to sort the column, page through to page 19, and then scroll down the page.   When I scroll down the page the browser freezes.

![image](https://user-images.githubusercontent.com/7661533/31016604-054ebf46-a4eb-11e7-970a-2823b0f1cf3c.png)

**Comment by nconrad** [comment]
The changes on alpha should help with this.  Could you test it out next time you are doing big runs, @jimdavis1 ?

**Comment by mshukla1** [comment]
I believed this is fixed now with the recent changes to the jobs page.
