### ISSUE TITLE
No google analytics for workspace and app service pages

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#174]
It seems that we do not have google analytics code embedded on the workspace pages, hence, page views are not recorded for any of the pages in the user workspace. 

-Maulik

**Comment by hyoo** [comment]
the file content of tracking.jsp is need for this. There are a few lines of javascript in the file.

**Comment by mshukla1** [comment]
I think the same goes for app service pages. They are not recorded as of now either.

**Comment by dmachi** [comment]
Harry fixed this with his GA additions a few weeks ago
