### ISSUE TITLE
Add protein to group is not working

### ISSUE THREAD

**Issue by dawenx** [PATRIC3/patric3_website#1741]
On https://www.patricbrc.org/view/TranscriptomicsExperiment/?in(eid,(1071603))
click on heatmap tab, click on a protein on the heatmap, it shows something like below, when clicking on "Add Protein to Group", it does not do anything. 
![screenshot-2017-10-3 transcriptomics genes](https://user-images.githubusercontent.com/26723038/31140277-f4b046b4-a841-11e7-9a73-c4def997bd59.png)

**Comment by mshukla1** [comment]
<img width="1440" alt="screen shot 2017-12-07 at 11 58 15 am" src="https://user-images.githubusercontent.com/1236463/33730561-edfd07da-db45-11e7-9699-23a00c13ad3c.png">
