### ISSUE TITLE
Time on new workspace out of whack

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1742]
<img width="908" alt="test workspace time" src="https://user-images.githubusercontent.com/11475316/31193267-9f4f13d2-a911-11e7-87a3-e36d6dfd6ea0.png">

I created the workspace sometime after 1pm EZT, and it says 5:38pm

**Comment by nconrad** [comment]
I think @olsonanl fixed this server side, right?   closing.

**Comment by olsonanl** [comment]
Yes, this should be fixed now by adding timezone to the returned timestamps and making the browsers treat times uniformly.
