### ISSUE TITLE
logout is not working from user.patricbrc.org

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1746]
![image](https://user-images.githubusercontent.com/1236467/31293992-e30118da-aa9e-11e7-83a1-c8e863664349.png)

**Comment by dmachi** [comment]
These aren’t real problems for users as they are differences because  you are an admin user.  Will get them fixed.

**Comment by hyoo** [comment]
Closing this issue. This will be addressed by #1763
