### ISSUE TITLE
genome count seems incorrect

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1748]
Website says there are 123,262 bacterial genomes, but there are only 116,003 in /vol/patric3/downloads/genomes/

![image](https://user-images.githubusercontent.com/7661533/31317183-1c8511e2-ac02-11e7-924d-7b20ca48ba71.png)

**Comment by mshukla1** [comment]
If you were logged in, the count will also include your private genomes, which are not made available on the FTP site. 

I checked FTP and made sure all public genomes are available on the FTP site. 

-Maulik
