### ISSUE TITLE
Discrepancy between tabs showing uploads and jobs completed

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1749]
I have two tabs open.  One showed a job complete, that I was able to annotate.  The second tab showed jobs in progress, even after I reloaded the page. 
<img width="269" alt="screen shot 2017-10-09 at 7 11 34 am" src="https://user-images.githubusercontent.com/11475316/31335626-5c4b4b24-acc1-11e7-816c-5ea3c82065ca.png">
<img width="256" alt="screen shot 2017-10-09 at 7 11 26 am" src="https://user-images.githubusercontent.com/11475316/31335627-5c4c7634-acc1-11e7-8c3b-2a07a6059efa.png">

**Comment by nconrad** [comment]
I'm not sure I completely understand the states your jobs were in, but it's entirely possible that these counts don't match because each browser tab is polling for updates every 15 seconds.

**Comment by mshukla1** [comment]
If multiple tabs are open, the job counts can be slightly off because each updates counts independently every 15 sec. This is expected. 

Closing the ticket.
