### ISSUE TITLE
dropdown highlighting inconsistency

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#175]
Once on a "Services" page, the dropdown menu (blue) hover highlighting stops working.

![screen shot 2015-04-22 at 2 21 33 pm](https://cloud.githubusercontent.com/assets/1194246/7283330/6b7c84c8-e8fb-11e4-8390-f5b50e1286da.png)

Also, in the other menus (such as "Data"), the highlighting is inconsistent, with only the text being highlighted for some of the items, an no highlighting for others.  There is no blue background highlighting here as well.

![screen shot 2015-04-22 at 2 21 45 pm](https://cloud.githubusercontent.com/assets/1194246/7283491/90bb547a-e8fc-11e4-84bd-a0badc6ab4f5.png)

**Comment by dmachi** [comment]
This is not critical to the release, but I will figure out how to get it to be consistent with the jboss version of the dropdown async

**Comment by hyoo** [comment]
this is specific to outdated website.
