### ISSUE TITLE
Filtering on Protein Family sorter is broken

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1751]
From my genome group (but I also did it from the genus Bartonella), I tried to use the filtering function at the bottom of the filter.  First, I could see that there were protein families that met the requirement I wanted (families with both 58 and 57 protein families per group.
<img width="1142" alt="screen shot 2017-10-12 at 10 13 44 am" src="https://user-images.githubusercontent.com/11475316/31500828-82b0ac6a-af36-11e7-8ef5-52a78dd41d43.png">
then I selected the filter options for number of proteins per family
<img width="256" alt="screen shot 2017-10-12 at 10 14 00 am" src="https://user-images.githubusercontent.com/11475316/31500849-9697c254-af36-11e7-8578-82b7f1c22e0b.png">
And this returned no results, even though I had checked previously to verify that protein families meeting this criterion exist
<img width="594" alt="screen shot 2017-10-12 at 10 14 12 am" src="https://user-images.githubusercontent.com/11475316/31500883-bb0712a2-af36-11e7-8257-c51ac7c73b04.png">
I also tried the filter on the number of genomes per family, being careful to choose filtering criteria that I knew matched the data
<img width="273" alt="screen shot 2017-10-12 at 10 14 33 am" src="https://user-images.githubusercontent.com/11475316/31500919-d863d7b8-af36-11e7-926a-df9d5870cea6.png">
And once again, it returned nothing
<img width="687" alt="screen shot 2017-10-12 at 10 14 41 am" src="https://user-images.githubusercontent.com/11475316/31500941-e4fef3ea-af36-11e7-9d54-c8e7caffe562.png">

I'm sure that this was working earlier this week.

**Comment by hyoo** [comment]
because,  > 58 and < 57 is empty set.

**Comment by mshukla1** [comment]
Harry, please add a check condition on user input and swap the values if min > max. 

This will make the filter more robust and avoid such user mistakes. 

-Maulik
