### ISSUE TITLE
selection on taxonomy tab does not show any button

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1753]
![image](https://user-images.githubusercontent.com/1236467/31520951-4db9c2a8-af6d-11e7-9256-d3622e92d850.png)

we used to have a button that takes me to the selected taxon level. I don't have it here.

![image](https://user-images.githubusercontent.com/1236467/31520971-67dd2eae-af6d-11e7-9ce7-5aefffc78e36.png)

**Comment by hyoo** [comment]
@dawenx is this related to the recent grid change?

**Comment by dawenx** [comment]
i'm not sure. i left my laptop in the office and could not check it, will look at it first thing tomorrow morning.

**Comment by dawenx** [comment]
@hyoo this seems to be introduced recently because i was not aware that taxonomy tab does not have primaryKey property.

should i check out master branch to work on a hot fix? or use develop branch as usual? i will work on the fix tomorrow.

**Comment by dawenx** [comment]
this was fixed, pr submitted.

**Comment by dawenx** [comment]
saw the fix on production.
