### ISSUE TITLE
copy on feature tab does not carry some fields

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1756]
https://www.patricbrc.org/view/Taxonomy/773#view_tab=features

![image](https://user-images.githubusercontent.com/1236467/31673472-e3917ca2-b324-11e7-8d59-0ac745e4e9ea.png)

and copied (full table with header option).

![image](https://user-images.githubusercontent.com/1236467/31673514-00f8a680-b325-11e7-87b6-dc9757ea29aa.png)

and PATRIC Local family and PATRIC Global family are missing.

I suspect, you miss spelled field name, like pgfam instead of pgfam_id, and plfam instead of plfam_id.

Please double check all the columns

**Comment by zreyn** [comment]
Ahh, it's an issue where some of the column keys are different than the object keys.  

https://github.com/PATRIC3/p3_web/pull/590

**Comment by zreyn** [comment]
Deployed in prod.
