### ISSUE TITLE
BLAST: make input sequence header optional

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1757]
It keeps saying "Blast only accepts one sequence at a time".  This happens when I go to the website and type in a  sequence.  

I have discovered that if you add a header line it will run, but none of our users are going to figure that out because NCBI doesn't require this on the blast website.

![image](https://user-images.githubusercontent.com/7661533/31723630-08c2b1ba-b3e5-11e7-8cb6-9ea55c810bec.png)

**Comment by mshukla1** [comment]
Looks like it is expecting the query sequence to be in fasta format or have the definition 
line starting with “>”. 

Harry, can you change it so that OI can just cut and paste sequence without fasta def line?

**Comment by hyoo** [comment]
We are using header line to distinguish sequences.

**Comment by mshukla1** [comment]
You can assume that if there are no header lines provided, user has entered only one query sequence. 

You can also clean up the query sequence by removing any white spaces before you submit. 
I think there is another ticket for that. 

-Maulik
