### ISSUE TITLE
BLAST Enhancement

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1758]
When I am doing a blastn against contigs, I would like to be able to see the region of the match in the genome browser.

![image](https://user-images.githubusercontent.com/7661533/31730012-3bd0e660-b3f6-11e7-9b92-472fbaff5cb0.png)

**Comment by mshukla1** [comment]
You can select a hit and click the genome browser icon in the action bar. It will take you to 
the genome browser, which matching region highlighted in yellow. 

If that what you wanted? Or did you have something different in mind?

-Maulik

**Comment by hyoo** [comment]
@jimdavis1 We're waiting your response.

**Comment by mshukla1** [comment]
@jimdavis1, can we close this issue?
