### ISSUE TITLE
sorting by nucleotide length isn't working

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1759]
I'm on the features tab for the following genome, selected only repeat regions and tried to sort, but it took like 3 minutes to sort 100ish items. 

![image](https://user-images.githubusercontent.com/7661533/31791611-bf45adf8-b4de-11e7-81dc-ae3ecc7cdb95.png)

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/31954817-2f286a68-b8ac-11e7-950d-8b05f16f286a.png)

https://www.patricbrc.org/view/Genome/573.13408#view_tab=features&filter=or(eq(feature_type,%22repeat_region%22))

this works for me. 

![image](https://user-images.githubusercontent.com/1236467/31954837-3f4cffbc-b8ac-11e7-829d-4e129b766635.png)

it took 13 secs to load

**Comment by mshukla1** [comment]
I am thinking it might be a temporary slowness from the database side. Closing the ticket.
