### ISSUE TITLE
No href or event for workspace caret 'link'

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#176]
(see subject)

![screen shot 2015-04-22 at 2 35 45 pm](https://cloud.githubusercontent.com/assets/1194246/7283646/8c61bb5c-e8fd-11e4-817a-ff87efd99682.png)

**Comment by mshukla1** [comment]
Looks like the link has been added.

**Comment by nconrad** [comment]
Looks like it's still there to me.

![screen shot 2015-06-10 at 4 29 47 pm](https://cloud.githubusercontent.com/assets/1194246/8094660/2033deda-0f8e-11e5-8fed-a7617c17b7a9.png)

**Comment by nconrad** [comment]
Double ticket!  Genome annotation is still failing.   And maybe modeling too.
