### ISSUE TITLE
Unable to upload SRA file to assembly selected files box

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1760]
I tried to take a specific SRA file (SRX2521124) and assemble it.  I put it into the SRA Run Accession, and then hit the arrow to load it into the selected files box, and nothing happens.  I think its broken.

**Comment by mshukla1** [comment]
You need to provide SRA run accession as mentioned in the search box, which starts with SRR. 

SRX corresponds to an experiment, which may result in multiple sequence libraries.
