### ISSUE TITLE
fasta files

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1761]
Regarding fasta files, I would like to advocate that we retire the locus tag and VBI id from the fasta header as well as the genome ID in brackets to simplify the fasta header so that it would go from looking like this:

>fig|511145.12.peg.1852|b1779|VBIEscCol129921_1852|   NAD-dependent glyceraldehyde-3-phosphate dehydrogenase (EC 1.2.1.12)   [Escherichia coli str. K-12 substr. MG1655 | 511145.12]

To looking like this:
>fig|511145.12.peg.1852 NAD-dependent glyceraldehyde-3-phosphate dehydrogenase (EC 1.2.1.12)   [Escherichia coli str. K-12 substr. MG1655]

It would be nicer to look at and easier to parse.  I would also point out that the amount of space between the function and the [genome name] is kind of bizarre.  It's like 3 spaces on the ftp site, but I'm not sure that it is 3 spaces if you make a call to solr.

**Comment by mshukla1** [comment]
> Regarding fasta files, I would like to advocate that we retire the locus tag and VBI id from the fasta header as well as the genome ID in brackets to simplify the fasta header so that it would go from looking like this:
> 
> fig|511145.12.peg.1852|b1779|VBIEscCol129921_1852| NAD-dependent glyceraldehyde-3-phosphate dehydrogenase (EC 1.2.1.12) [Escherichia coli str. K-12 substr. MG1655 | 511145.12]
> 
> To looking like this:
> 
> fig|511145.12.peg.1852 NAD-dependent glyceraldehyde-3-phosphate dehydrogenase (EC 1.2.1.12) [Escherichia coli str. K-12 substr. MG1655]
> 
I would not mind dropping VBI locus tags as those are obsolete and probably no one cares about them. 

I think we should not remove refseq/genbank locus tags as we have heard over the years that is the id biologists care about the most. 
I think Rebecca would agree. 

The reason genome ids were added is because we have hundreds of genomes with exactly the same name, making it hard to distinguish 
them without the genome ids.

> It would be nicer to look at and easier to parse. I would also point out that the amount of space between the function and the [genome name] is kind of bizarre. It's like 3 spaces on the ftp site, but I'm not sure that it is 3 spaces if you make a call to solr.
> 
I thought we trying to match the fasta header format in all places to make it consistent. We should double check and fix it, if it is not the case. 

-Maulik

**Comment by mshukla1** [comment]
Verified that the fasta file format and the number of spaces is consistent between the files on the FTP site and the sequences downloaded from the website and data API. 

I do not want to change the definition line as this is the frmat we have used for past 10 years and there are lot of users who have adapted there pipelines and scripts to match it. 

-Maulik

**Comment by rkenyon** [comment]
Jim triage comment: Low/no action.  It looks like I am a minority party here. my gripe is that we are carrying a lot of extra stuff in the fasta header.
