### ISSUE TITLE
Phylogenetic tree viewer needs to root tree on outgroup selected genomes

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1762]
Its not doing this

**Comment by aswarren** [comment]
![image](https://user-images.githubusercontent.com/229173/31904339-f8572744-b7f8-11e7-9eb4-dd30cc0b4834.png)

Job ID: 09412b9c-16d4-4b53-93f8-00b147602182 and user name katunge_cc

The tree should have a separate root for the outgroup in the rendering. This looks to be a viewer problem.

**Comment by aswarren** [comment]
![image](https://user-images.githubusercontent.com/229173/31904572-aa47c15c-b7f9-11e7-86da-5a618f8b79bf.png)

Should look like this

**Comment by aswarren** [comment]
![image](https://user-images.githubusercontent.com/229173/38761863-54dbd86a-3f54-11e8-9e7a-f5b4734c2ccd.png)
Fixed
