### ISSUE TITLE
copy na/aa sequence to the clip board

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1764]
Suggestion from a user: 

On the gene page, provide "Copy" button to copy na/aa sequence directly to clip board, so that it can be used to search in other public databases. 

Currently, user will have to first click view, which opens another tab, then manually select the sequence and then copy. 

<img width="419" alt="screen shot 2017-10-27 at 5 10 23 am" src="https://user-images.githubusercontent.com/1236463/32099313-6d5b52ca-bad5-11e7-9859-e7a1401b4e5c.png">

-Maulik

**Comment by mandywil** [comment]
To duplicate:
Go to Feature View/Genome browser, select a CDS.

**Comment by hyoo** [comment]
confirmed on production
