### ISSUE TITLE
Unable to see cancel or ok button on upload page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1767]
The user may not realize that they have to scroll down to see the buttons that they need to.  The center panel could be decreased in size to resolve this issue.
<img width="839" alt="screen shot 2017-10-28 at 10 07 27 am" src="https://user-images.githubusercontent.com/11475316/32135140-09ba2ce8-bbc8-11e7-9b74-c4c494dc671c.png">

**Comment by dawenx** [comment]
duplicate issue as #1810

**Comment by hyoo** [comment]
closing duplicates
