### ISSUE TITLE
Metadata template FAQ link in Expression import leads to an error page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1770]
Click on the information icon:
<img width="326" alt="screen shot 2017-11-03 at 2 20 23 pm" src="https://user-images.githubusercontent.com/11475316/32389826-5c20f9ec-c0a2-11e7-82d2-0839b3715933.png">
In the pop-up window, click on FAQ:
<img width="360" alt="screen shot 2017-11-03 at 2 20 35 pm" src="https://user-images.githubusercontent.com/11475316/32389838-6bb000f6-c0a2-11e7-946a-d5f5dbf2fd48.png">
This leads to an error page:
<img width="1398" alt="screen shot 2017-11-03 at 2 20 57 pm" src="https://user-images.githubusercontent.com/11475316/32389846-757ca242-c0a2-11e7-8640-e0a612cd2a40.png">

**Comment by dawenx** [comment]
@hyoo @mshukla1 do you know the correct URL? this can be fixed quickly.

Also, i removed this link in the new static content page. will add it back once we know the correct URL.

**Comment by dawenx** [comment]
The FAQ link has been removed in current production site as we could not locate the source URL. I noticed some display issue in in-line help for Expression Import service. Mentioned it to @hyoo already.

**Comment by hyoo** [comment]
This is fixe on 
https://www.patricbrc.org/app/Expression

by this
https://github.com/PATRIC3/p3_docs/commit/2a40f5be094eb7248af3997dad9547568cec55ce

format was rst but somehow it was named .md, which broke the link format.

**Comment by hyoo** [comment]
@dawenx would you double check and close this one?
