### ISSUE TITLE
Don't show internal feature ids in the header 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1772]
...we should be showing patric ids or refseq locus tags or just summarize the number at the top. 

<img width="1223" alt="screen shot 2017-11-03 at 3 56 46 pm" src="https://user-images.githubusercontent.com/1236463/32395574-af58f756-c0af-11e7-9b8a-d031f2bba5f7.png">

**Comment by dawenx** [comment]
i can go ahead to remove the query part for Feature List View, but i would like to double check before i do so. for now, those internal feature ids are in the url, i.e., part of the query, and we only display 2 of them in the header. why do we want to "hide" to make this particular one not consistent with other tab viewers?

**Comment by hyoo** [comment]
We need to discuss the solution. Some feature type, such as source, misc_feature, or assembly_gap does not have any meaningful ID beside feature_id.

@dawenx fyi,
feature_id is designed for internal use only. This is more like a composite key in RDBMS, combing annotation, seq id, start and end position, and strand as a way to generate a unique string for each feature. This is too long, and sometimes information inside the string can be invalid. So, we decided to use unique key purpose only. 

As Maulik suggested, PATRIC ID is more meaningful representation of feature. RefSeq annotation would not have PARIC ID, so in that case, RefSeq_locus_tag should be displayed. However, some feature types (source, assembly_gap) does not have any meaningful IDs.

**Comment by dawenx** [comment]
decided to remove the query part and only show the number on the top. PR submitted on 11/15.
