### ISSUE TITLE
Unable to load bam files from RNA Seq job

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1774]
I have run the RNA Seq job that will be used at the workshop, but when I try to see them in the genome browser, it throws an error.  It would be really great if this were fixed before the workshop
<img width="1427" alt="screen shot 2017-11-04 at 1 22 03 pm" src="https://user-images.githubusercontent.com/11475316/32407718-6fc44fdc-c163-11e7-8825-b2d041fc7cf1.png">

**Comment by zreyn** [comment]
If you tried to load this page from your job result page using the blue Browser button, the problem could be that the downloadable URLs needed for JBrowse weren't loaded yet.  I don't get an error when trying to recreate it, however, I also don't see anything in the Rockhopper_COL_75.bam track.  @aswarren might have better insight

**Comment by mshukla1** [comment]
I believe this was working by the time of workshop. 

@ARWattam, can we close this ticket?

**Comment by hyoo** [comment]
This works on production.

To reproduce, you can go to
https://www.patricbrc.org/workspace/public/anwarren@patricbrc.org/AndrewWarrenPublic/RNA-Seq/Acinetobacter%20baumannii%20AR%20Rockhopper

and click browser.

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/1236467/35636153-e0b22adc-0675-11e8-98e1-4f3765fc6fa6.png">
