### ISSUE TITLE
Able to see heatmap on Google Chrome with Pathway tool, but it doesn't load with same genomes using Protein Family sorter

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1775]
This is an odd one.  I can see the heatmap with the pathways:
<img width="1299" alt="screen shot 2017-11-05 at 11 18 27 am" src="https://user-images.githubusercontent.com/11475316/32416687-3e423614-c21b-11e7-9b6b-b042eb7b51ca.png">

Moments later, when I try to see the data from the same genomes, but using the ProteinFamily Sorter in Google Chrome, I get a message saying that I have to download Adobe Flash:
<img width="1382" alt="screen shot 2017-11-05 at 11 18 43 am" src="https://user-images.githubusercontent.com/11475316/32416697-629528aa-c21b-11e7-9e6a-a8b6308a4843.png">

**Comment by hyoo** [comment]
message is not saying your need to **download**, but **enable**

With the images, i cannot tell whether those are from same browser. **Each** browser needs to enable FLASH plugin. Were you using same browser?

**Comment by mshukla1** [comment]
We know heatmap generally works for both protein family and pathway for all browsers after installing and enabling flash. I am closing this unless we can reproduce it.
