### ISSUE TITLE
phylogenetic tree.sup gives error

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1776]
Clicking on this particular file opens a page with no tree:
<img width="1437" alt="screen shot 2017-11-06 at 11 26 11 am" src="https://user-images.githubusercontent.com/11475316/32451715-8bc4f82a-c2e5-11e7-8282-317e66db50da.png">

The error is as follows:
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at eval (core.js.uncompressed.js:5214)
/js/3.4.13/p3/widget/JobManager.js:170 rownum:  bde6637f-63c5-487a-8ec2-bd1fcb77c320
/js/3.4.13/p3/widget/JobManager.js:171 Row:  Object
/js/3.4.13/p3/widget/JobManager.js:177 selection:  Array(1)
/js/3.4.13/p3/widget/JobManager.js:94 SEL:  Object
core.js.uncompressed.js:30785 Uncaught TypeError: b.clearSelection is not a function
    at Object.eval (core.js.uncompressed.js:30785)
    at HTMLDivElement.<anonymous> (dojo.js.uncompressed.js:3288)
    at Function.k.emit (dojo.js.uncompressed.js:6014)
    at HTMLDivElement.eval (core.js.uncompressed.js:31418)
    at HTMLDivElement.<anonymous> (dojo.js.uncompressed.js:5894)

**Comment by rkenyon** [comment]
I'm not getting an error with this file.  Double-clicking it does nothing and clicking the View icon renders a blank page.  
![screen shot 2018-08-16 at 2 24 08 pm](https://user-images.githubusercontent.com/3188570/44227224-18372680-a160-11e8-9574-1d323e371c80.png)
What is this file type and what is it for?

**Comment by mshukla1** [comment]
@dawenx Not sure if this is still an issue. You may have fixed it recently, when you fixed the Tree button at the top. 

Can you please check with Rebecca to confirm and close this ticket?

**Comment by ARWattam** [comment]
Still an issue with PEPR tree jobs, but as we are making codon trees the default, and because we no longer have Eric to fix it, perhaps we can leave this closed.  Does anybody agree?
