### ISSUE TITLE
Misspelling in job results dialogs

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1778]
"Parameters". It's wrong in metagenome and proteome comparison at least.

<img width="797" alt="screen shot 2017-11-07 at 1 32 11 pm" src="https://user-images.githubusercontent.com/2152226/32513601-39fcfb74-c3c0-11e7-9249-601698437ca2.png">

**Comment by zreyn** [comment]
Oops.  This is fixed in PR #602.

Para Mater?
https://www.tapatalk.com/groups/carsthetoys/imageproxy.php?url=http://i655.photobucket.com/albums/uu280/djjd21wales/vlcsnap-2012-01-03-17h37m51s107.png

**Comment by zreyn** [comment]
Deployed in prod.
