### ISSUE TITLE
Add public filter on various tabs

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1779]
Just noticed that we have public = true /false filter available only for genome list. 

We do not have the same available on features, AMR phenotype, specialty genes, and other similar tabs. We need to systematic review  all relevant tabs and add such filter where appropriate. 

-Maulik

**Comment by dawenx** [comment]
i chat with harry this morning and wanted to know more on the back-end data structure. i'm planning to have a discussion with him when i visit next week, and work on this afterward.

**Comment by dawenx** [comment]
this is fixed, PR submitted on 11/15.
