### ISSUE TITLE
sample gene matrix file has wrong headers

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#178]
Gene IDs Sample1 Sample2

Should be Gene ID Comparison1 Comparison2

**Comment by mshukla1** [comment]
This is somewhere in wordpress, can't figure out  how to get to it.

**Comment by mshukla1** [comment]
Ron, if you can find the excel files on the page below, please change Sample1, Sample2...in both the files to Comparison1 Comparison2.

**Comment by rkenyon** [comment]
Yes, I'll see if I can find it and fix it.

Ron Kenyon
PATRIC Project Manager, patricbrc.org
Project Management Director
Virginia Bioinformatics Institute, Virginia Tech
Ph: 540-231-7470

**Comment by rkenyon** [comment]
I have made the changes and uploaded the files to WordPress. WordPress 
created a new URL for each, which I have updated in the FAQs, but which 
also needs to be updated in the Diff Exp App Help. Use these new URLs 
instead:

http://enews.patricbrc.org/wp-content/uploads/2015/06/Sample-Genes.xlsx

http://enews.patricbrc.org/wp-content/uploads/2015/06/Sample-Metadata.xlsx

Ron

Ron Kenyon
PATRIC Project Manager, patricbrc.org
Project Management Director
Virginia Bioinformatics Institute, Virginia Tech
Ph: 540-231-7470

**Comment by aswarren** [comment]
Links updated
