### ISSUE TITLE
Misalignment on list pages

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1780]
Something seems to be a little off with size calculations on the list pages; the bottom seems to always be cut off because there is a little extra height that is triggering a scroll bar.

<img width="376" alt="screen shot 2017-11-07 at 2 29 32 pm" src="https://user-images.githubusercontent.com/2152226/32516216-3a09aeca-c3c8-11e7-8bad-f9925344cbd5.png">

**Comment by olsonanl** [comment]
BTW this is version 3.4.13 seen on Safari

**Comment by hyoo** [comment]
which page is this? 
it looks okay this my safari.
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/1236467/32957512-7c8fabe4-cb81-11e7-81bc-ae0c1a2ce034.png">

**Comment by olsonanl** [comment]
I see it on the feature list at least.

![screen shot 2017-11-20 at 11 27 12 am](https://user-images.githubusercontent.com/2152226/33032088-d261dd1a-cde5-11e7-8bab-cc0cc119ab8f.png)

Safari Version 10.1.2 (11603.3.8)

**Comment by JoshuaVSherman** [comment]
https://github.com/PATRIC3/p3_web/pull/672
