### ISSUE TITLE
Drag and drop on linux?

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1782]
Rob was trying drag and drop to upload data on Ubuntu; it looked like it accepted the drop but didn't add the file info to the window.

**Comment by hyoo** [comment]
As far as i know, drag and drop is supported by chrome browser only. Did he use chrome?

**Comment by olsonanl** [comment]
Hm, I don’t know but I can check. It looked like it worked but didn’t do anything once the drop happened.

I just tried in firefox and chrome and it appeared to work properly (Ubuntu 14.04). I’ll ping Rob on his versions.



On Nov 13, 2017, at 10:25 AM, hyoo <notifications@github.com<mailto:notifications@github.com>> wrote:


As far as i know, drag and drop is supported by chrome browser only. Did he use chrome?

**Comment by dawenx** [comment]
@olsonanl have you checked with Rob on this? I tested this in Firefox and Chromium on Ubuntu 16.04 and it worked for me.

**Comment by olsonanl** [comment]
I did - he said to close the ticket as he was not able to reproduce.
