### ISSUE TITLE
binning submission page issues

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1783]
If you make any mistake in the binning submission page it is easy to get it into a state where you go back and fix the problem but the submit button doesn't  get reenabled.

**Comment by hyoo** [comment]
i have fix validation code so i guess this is resolved. Would you double check on alpha? If it is not fixed, please give me instructions to reproduce the symptom.

**Comment by olsonanl** [comment]
I have trouble with this:

Pick a contigs file
Click the folder under output folder.
Browse to a folder, and browse into the folder you want for output. Note that it says "Selection: out" for e.g. /olson@patricbrc.org/Binning/out which is where I went, and which is what I want for my output folder.
Click OK.
The output folder drop down is left empty. Sometimes I'm left with a red non-valid indicator.
This time I wasn't, and could fill in an output name and group name and hit submit.

After hitting submit, it says job has been queued, and then the output folder box turns red.

The job fails with an invalid path error because it did indeed get submitted with an empty output path.

**Comment by hyoo** [comment]
@dawenx since you've been working on service form more recently. would you take a look?

**Comment by dawenx** [comment]
I noticed some issues on binning service UI as well, e.g., the submit button is enabled when the file name is empty (after some random clicking). I will take a look. This is also similar to #1831 although I was not able to reproduce the issue in #1831.

**Comment by dawenx** [comment]
i have implemented some enhancements for this UI, e.g., a user cannot choose both paired read library and contigs, same file for a paired is not allowed, etc. it's on alpha.

**Comment by dawenx** [comment]
the fix is on production.
