### ISSUE TITLE
Job submission should block until uploads completed

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1784]
We really need to have the UI block submission of a job until its input files are finished uploading. We're running into that over and over in the session with Rob this morning.

**Comment by hyoo** [comment]
checking the uploaded file size would help? We will not know the right size of file but would know that it shouldn't be zero.

**Comment by olsonanl** [comment]
I’ve made this argument before. The right solution is for the client to block, since only the client knows whether the upload completed successfully and whether it will ever complete successfully. I haven’t heard a good argument for it to be any other way.

On Nov 13, 2017, at 10:23 AM, hyoo <notifications@github.com<mailto:notifications@github.com>> wrote:


checking the uploaded file size would help? We will not know the right size of file but would know that it shouldn't be zero.

**Comment by dawenx** [comment]
@nconrad i had a discussion with @dmachi on this. i will work on this if you don't mind.

**Comment by nconrad** [comment]
@dawenx sure!  It sounds like you know how to deal with the events.

**Comment by dawenx** [comment]
i think (or hope) i have a fix. i will submit a PR after some codes cleanup. can someone help me out on testing (after it's pushed to alpha)? so far i only test my fix on expected behavior, but i have not submitted any real job.

**Comment by dawenx** [comment]
tested on assembly service and PR submitted.

**Comment by olsonanl** [comment]
Is it on alpha now?

**Comment by dawenx** [comment]
no, not yet.

**Comment by mshukla1** [comment]
Verified the fix on production site. Its working as expected.

**Comment by dawenx** [comment]
this fix applies to metagenome binning service as well (on alpha), will be on production on next release.
