### ISSUE TITLE
Assembly service won't take a valid ERR number

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1787]
I just dumped an err number "ERR1008629" into the SRA run accession box for the assembly service and it did not work.  This should be a valid SRA accession number even though it originated from ENA.

**Comment by mshukla1** [comment]
I have seen the same problem. I think the service is expecting the accession to start with ERR. It needs to be fixed.

**Comment by mshukla1** [comment]
Hopefully, this is an easy fix. Most likely, there is a check on the UI or service side, that says the accession should start with SRR, which needs to be changed to SRR or ERR. 

-Maulik

**Comment by mshukla1** [comment]
#1785
