### ISSUE TITLE
app field promptMessage doesn't stay attached to field when scrolling

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#179]
Before scrolling:
![screen shot 2015-04-28 at 12 08 44 pm](https://cloud.githubusercontent.com/assets/1194246/7375638/a8fd3ff6-ed9f-11e4-8571-cf949ffad457.png)

After scrolling:
![screen shot 2015-04-28 at 12 08 48 pm](https://cloud.githubusercontent.com/assets/1194246/7375644/b261b400-ed9f-11e4-9eac-0682b8896c68.png)

**Comment by mshukla1** [comment]
@dawenx  can you take care of this for all submission forms?

**Comment by dawenx** [comment]
ok, will do

**Comment by dawenx** [comment]
I looked into this, also had a brief discussion with @dmachi 

this is a bug/issue in the underlying dijit widget, i will do a search to see whether there's a walk around, but i can not promise to get this resolved for "Dec 2017 - Minor release".

**Comment by dawenx** [comment]
I have tried without luck as this is related to bug/issue in the underlying dijit widget. Need help.

**Comment by nconrad** [comment]
@dawenx oh yeah, I reported this ages ago! :)   Yeah, I'm not sure there is a solution that is worthwhile, given this is also low priority.  Definitely a dojo issue: https://bugs.dojotoolkit.org/ticket/15388 .    I would close.

**Comment by dawenx** [comment]
ok, i changed some tags and will go ahead to close it.
