### ISSUE TITLE
Vertical green bar should be scrollable

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1790]
SEveral participants have not been able to get to the correct icon because it is not scrollable.  They have requested that this be way.  There has been a bit of frustration over this issue

**Comment by dawenx** [comment]
this is fixed, PR submitted. 

@ARWattam this is NOT in the alpha yet, it will be rolled out some time later.

**Comment by dawenx** [comment]
this is on production and i verified it. close the ticket.
