### ISSUE TITLE
Workshop participant requests Phaster as part of PATRIC

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1791]
PHASTER (PHAge Search Tool Enhanced Release) is a significant upgrade to the popular PHAST web server for the rapid identification and annotation of prophage sequences within bacterial genomes and plasmids.

There was some discussion of phage annotation in PATRIC during the workshop.  Seems like people would like this

**Comment by mshukla1** [comment]
Moving it to PATRIC4, as future enhancement to the annotation system.
