### ISSUE TITLE
inconsistency in the number of PATRIC CDSs

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1795]
When I search for this genome, the table says that there are 1003 patric cdss, but when I click on the genomes and bring up the feature page, there are only 752.

![image](https://user-images.githubusercontent.com/7661533/32862108-91a9aa04-ca1c-11e7-96b8-d598f3f01c67.png)

![image](https://user-images.githubusercontent.com/7661533/32862095-87d0ac9e-ca1c-11e7-89f4-d74ce481042e.png)

**Comment by mshukla1** [comment]
As part of genome QC, I am trying to find all cases of inconsistent data in the database. Mismatches in the number of CDSs and genome sequences are part of the checks I am running.

**Comment by rkenyon** [comment]
Jim triage comment: This example got fixed.

**Comment by mshukla1** [comment]
As part of the ongoing genome QC and clean up, I have corrected many such cases and deleted ~5000 corrupted genomes.
