### ISSUE TITLE
User need git link for command line tutorial

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1797]
This appears to be missing and several of the workshop participants need this.

**Comment by dawenx** [comment]
do you mean the source codes to generate the pages? if so, it is : https://github.com/PATRIC3/p3_docs/tree/master/docroot/cli_tutorial

**Comment by mshukla1** [comment]
Bob, 

The following page has a link to CLI installation tutorial that leads to a blank page. 
https://docs.patricbrc.org//cli_tutorial/index.html

the CLI installation guide seems to be missing on the docs site. 
https://docs.patricbrc.org//cli_tutorial/cli_installation.html

We should either modify the first page or add content on the second one. 

-Maulik

**Comment by olsonanl** [comment]
Closing as duplicate of #1796
