### ISSUE TITLE
tuxedo rnaseq pipeline fails on read files with spaces

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1799]
'samtools view -Su /scratch/tmp/m0vTd6q_Uk/Rocket/1009714.9/Phage_3_5/replicate1/Phage 3.5_R1.fastq.sam | samtools sort -o - - > /scratch/tmp/m0vTd6q_Uk/Rocket/1009714.9/Phage_3_5/replicate1/Phage 3.5_R1.fastq.bam' 

Unescaped command line argument getting through.

**Comment by aswarren** [comment]
This has been fixed for a bit. https://github.com/aswarren/Prok-tuxedo/commit/20a634e886b4b06423c323877c25906f922b7ffe
