### ISSUE TITLE
Modal changes needed  for "forgot password" functionality

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#18]
1)  I think the login modal should say "Forgot Your password?" instead of "Forget Your password?"

2) once you have submitted the info the modal says "Your Password has been reset
Reset Code: undefined"   I think it needs to say something like "Please follow the instructions received in your email to complete your password reset"  (or a writer could probably do better than that!)

**Comment by brettin** [comment]
When I enter an incorrect email address while attempting to reset my password, the error message says “502 Bad Gateway”. It could say something like “Unable to find this email address, perhaps you registered with a different email”

**Comment by dmachi** [comment]
Both of these have been resolved and pushed to alpha and beta.

**Comment by rwill1** [comment]
OK, this is really a nit .... and I KNOW it just says what I typed (bc I just overwrote the "e" with an "o" from what was there.    But anyway, it's not at all clearly why the "Y" in "Your" is capitalized .... seems like it should be a lower case "y"?
