### ISSUE TITLE
Genome list: links from no of sequences not working

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#180]
Bug:

Went to all bacteria, genome list, added "sequences" as a column, clicked on #of sequences for one of the genomes. 

Result: it went to the sequence tab, but it was showing all the sequences from all bacteria, instead of 
only the sequences for the genome I clicked on. 

-Maulik

**Comment by hyoo** [comment]
fixed and available on beta.

**Comment by mshukla1** [comment]
checked, working.
