### ISSUE TITLE
Provide download from the pathway summary page

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1802]
Version: 3.4.13 
URL: https://www.patricbrc.org/view/PathwaySummary/
User ID: kcherny1
I can see the pathway list on the pathway summary page, but I can not 
download it.

-Maulik for user

**Comment by mshukla1** [comment]
Add the following: 

1. Download button above the table to download the entire table as shown. 

2. Copy button in the action bar for downloading selected records.

**Comment by mshukla1** [comment]
Harry, 

Can you please check the CSV download? When I open it in excel, the comma in some pathway names cause it to split into multiple columns. You need to put those names into double quotes. 

https://www.alpha.patricbrc.org/view/PathwaySummary/?features=PATRIC.83332.12.NC_000962.CDS.99684.100451.fwd,PATRIC.83332.12.NC_000962.CDS.83996.85168.fwd,PATRIC.83332.12.NC_000962.CDS.77619.78896.rev,PATRIC.83332.12.NC_000962.CDS.76237.77622.rev,PATRIC.83332.12.NC_000962.CDS.72274.74511.rev,PATRIC.83332.12.NC_000962.CDS.65771.66694.fwd,PATRIC.83332.12.NC_000962.CDS.53354.55699.fwd,PATRIC.83332.12.NC_000962.CDS.50021.51124.rev,PATRIC.83332.12.NC_000962.CDS.43562.46471.fwd,PATRIC.83332.12.NC_000962.CDS.37259.38947.fwd,PATRIC.83332.12.NC_000962.CDS.34295.36610.fwd,PATRIC.83332.12.NC_000962.CDS.25913.26881.rev,PATRIC.83332.12.NC_000962.CDS.21637.23172.rev,PATRIC.83332.12.NC_000962.CDS.18759.20207.rev,PATRIC.83332.12.NC_000962.CDS.17467.18762.rev,PATRIC.83332.12.NC_000962.CDS.15590.17470.rev,PATRIC.83332.12.NC_000962.CDS.14914.15612.fwd,PATRIC.83332.12.NC_000962.CDS.2052.3260.fwd

<img width="588" alt="screen shot 2017-12-12 at 6 57 34 am" src="https://user-images.githubusercontent.com/1236463/33885760-e3d7e992-df09-11e7-9cd5-8212f3c309bc.png">

**Comment by hyoo** [comment]
fix will be available on alpha soon.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/1236467/33897423-06f271ce-df2b-11e7-8d1b-277415fdc05f.png">
