### ISSUE TITLE
RNA-Seq: replace "|" with " vs " in gmx file 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1803]
Currently, in the gmx file generated by the rna seq pipeline, the comparison label contains a pipe, 
i.e. sample1|sample2. 

The pipe character is not handled well in the flash heatmap viewer, which results in labels not being 
displayed. As a quick fix, I am suggesting that the RNA-seq pipeline is changed to use " vs " instead 
of "|" in the comparison labels. 

This comes up in every single workshop and it needs to be fixed as soon as possible. 

-Maulik

**Comment by aswarren** [comment]
Fixed as part of the RNA-Seq upgrade.
