### ISSUE TITLE
MSA: tree and MSA don't match 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1804]
This was reported by one of the workshop participants. 

Version: 3.4.13 
URL: 
https://www.patricbrc.org/view/MSA/?and(in(genome_id,(643561.4,343013.3,397945.6,573060.9,535289.3,999386.3,1144317.3,1276755.3,232721.9,358220.3,1736280.3,1736296.3,1268622.3,1736492.3,80878.5,1855285.3,596153.4,596154.3,1200791.3,1121116.3,1450524.3,1265502.3,946483.4,80864.16,80864.17,1458425.3,1458426.3,614083.3,1298913.3,1457173.3,1219031.4,1121348.4,1121349.4,1223521.5,225992.4,1055192.4,688245.4,1265504.3,1714344.3,398578.5,742013.3,65786.3,795665.3,1736490.3,1437444.3,887062.3,1458275.3,1610491.3,1293045.4,1678129.3,1100720.3,1658672.3,1122623.4,1736434.3,1736580.3,365044.20,1144318.3,1504672.3,1305734.3,296591.12,1257078.4,1736316.3,1736318.3,1736365.3,365046.3,28065.5,28065.6,28065.7,28065.8,1111071.4,81479.8,28066.3,338969.11,192843.3,1484693.3,1842727.3,1802019.3,1123255.3,1157708.3,595537.3,543728.3,34073.19,1144315.3,1380385.4,565443.5,391735.7,1123504.3)),in(figfam_id,(FIG00000148)))
User ID: cryomics

In the example attached, the first entry is selected.
The MSA shows the sequence as MARYIGPVAKL
The sidebar shows the sequence MARYLGPKAKL
I believe the sidebar is right, but then where is the MSA getting this 
other sequence?

I see what happened, the MSA output isn't sorted by the phylogeny....

![image](https://user-images.githubusercontent.com/1236463/32972107-23979d96-cbb6-11e7-8dfb-fffd2fe384b4.png)

**Comment by mshukla1** [comment]
@maovt : This is critical problem, which may make user question the whole MSA tool. We need to address it asap.

**Comment by chmao1** [comment]
I'll look into it ASAP.

**Comment by aswarren** [comment]
This bug reemerged with changes to the Phylogenetic tree viewer.
Fixed in the following https://github.com/PATRIC3/p3_web/pull/628
