### ISSUE TITLE
Browse genomes buttons vanished from job viewer

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1805]
Weren't we able to go directly to the genomes before?

![screen shot 2017-11-20 at 11 25 41 am](https://user-images.githubusercontent.com/2152226/33032033-995f2cf2-cde5-11e7-8cbb-fa3f5889091c.png)

**Comment by mshukla1** [comment]
I suspect if it has something to do with job type “GenomeAnnotationGenbank”
instead of “GenomeAnnotation”. I don’t see the view icon for any of former ones. 

-Maulik

**Comment by zreyn** [comment]
Maulik is right; since this is a new app type it wasn't in the lists for what gets those blue buttons.

Fixed in [PR#615](https://github.com/PATRIC3/p3_web/pull/615)

**Comment by mshukla1** [comment]
Fixed. Verified on alpha.
