### ISSUE TITLE
Data API: prevent solr errors

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1806]
there are a couple of different types of errors, most cases, those are coming from wrong structured queries. 

![image](https://user-images.githubusercontent.com/1236467/33087255-a9152744-ceaf-11e7-88bf-6e34a05b9cfe.png)

Maybe we can check in data API level and respond with Error code and don't pass queries to solr.

**Comment by hyoo** [comment]
one relevant log from data api
```
[Tue, 21 Nov 2017 17:37:17 GMT] - OPTIONS /taxonomy?q=()%20AND%20(taxon_rank:(superkingdom)^7000000%20OR%20taxon_rank:(phylum)^6000000%20OR%20taxon_rank:(class)^5000000%20OR%20taxon_rank:(order)^4000000%20OR%20taxon_rank:(family)^3000000%20OR%20taxon_rank:(genus)^2000000%20OR%20taxon_rank:(species)^1000000%20OR%20taxon_rank:*)&fl=taxon_name,taxon_id,taxon_rank,lineage_names&qf=taxon_name 204 1.258 [-] ms - -
[Tue, 21 Nov 2017 17:37:17 GMT] - GET /taxonomy?q=()%20AND%20(taxon_rank:(superkingdom)^7000000%20OR%20taxon_rank:(phylum)^6000000%20OR%20taxon_rank:(class)^5000000%20OR%20taxon_rank:(order)^4000000%20OR%20taxon_rank:(family)^3000000%20OR%20taxon_rank:(genus)^2000000%20OR%20taxon_rank:(species)^1000000%20OR%20taxon_rank:*)&fl=taxon_name,taxon_id,taxon_rank,lineage_names&qf=taxon_name 404 15.908 [QUERY 6] ms - -
```

**Comment by hyoo** [comment]
maybe relevant to "Cannot parse 'genome_id':"

```
org.apache.solr.search.SyntaxError: Cannot parse '(genome_id: AND source:CARD)': Encountered " <AND> "AND ""
```

**Comment by hyoo** [comment]
https://github.com/PATRIC3/p3_api/commit/e6d9c3b54b90cd480243b66afc5e07b866c2bb18

This will prevent `feature_id_a:()` type errors

**Comment by hyoo** [comment]
https://github.com/PATRIC3/p3_web/commit/df0a8b744a972ddc92b9277d6fb0c9da07aca4ba

This will prevent ```genome_id: AND property:...``` and ```genome_id:()``` errors. Those were coming from specialty gene tab and sequences tab, respectively when the page is reloaded.

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/36265860-be897d4a-1235-11e8-9d31-a42565cd67e5.png)

Three patterns left.

**Comment by mshukla1** [comment]
@hyoo can we close this?
