### ISSUE TITLE
TaxonNameSelector: don't fire query when keyword is empty

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1807]

**Comment by hyoo** [comment]
it seems like taxonNameSelector build query based on the keyword that user typed in.

In some case, it fires with empty string, which cause errors like below,
see #1806 

some example query is like

[Tue, 21 Nov 2017 17:37:17 GMT] - OPTIONS /taxonomy?q=()%20AND%20(taxon_rank:(superkingdom)^7000000%20OR%20taxon_rank:(phylum)^6000000%20OR%20taxon_rank:(class)^5000000%20OR%20taxon_rank:(order)^4000000%20OR%20taxon_rank:(family)^3000000%20OR%20taxon_rank:(genus)^2000000%20OR%20taxon_rank:(species)^1000000%20OR%20taxon_rank:*)&fl=taxon_name,taxon_id,taxon_rank,lineage_names&qf=taxon_name 204 1.258 [-] ms - -
[Tue, 21 Nov 2017 17:37:17 GMT] - GET /taxonomy?q=()%20AND%20(taxon_rank:(superkingdom)^7000000%20OR%20taxon_rank:(phylum)^6000000%20OR%20taxon_rank:(class)^5000000%20OR%20taxon_rank:(order)^4000000%20OR%20taxon_rank:(family)^3000000%20OR%20taxon_rank:(genus)^2000000%20OR%20taxon_rank:(species)^1000000%20OR%20taxon_rank:*)&fl=taxon_name,taxon_id,taxon_rank,lineage_names&qf=taxon_name 404 15.908 [QUERY 6] ms - -

**Comment by dawenx** [comment]
i have fixed it and PR submitted.
