### ISSUE TITLE
Disappearing upload button when selecting file type

### ISSUE THREAD

**Issue by enordber** [PATRIC3/patric3_website#1810]
![screen shot 2017-11-29 at 2 21 57 pm](https://user-images.githubusercontent.com/1380281/33394569-c0b18dea-d510-11e7-80e5-23548bda9dc7.png)
![screen shot 2017-11-29 at 2 22 07 pm](https://user-images.githubusercontent.com/1380281/33394570-c0bf3486-d510-11e7-93b6-641de89055ec.png)
no scroll bar to indicate buttons below.

**Comment by hyoo** [comment]
@nconrad would you put this issue into Feb or March milestone? It is your call.

**Comment by hyoo** [comment]
@nconrad can we  shrink drag & drop zone (or increase the height of dialog, but shouldn't be too big for low resolution screens) so that buttons can show up? I found myself confusing, because I couldn't find submit or upload button until i scroll down.

**Comment by nconrad** [comment]
@hyoo, yeah, I'll improve this for the July release

**Comment by dawenx** [comment]
I ran into this when I'm working on Uploader.js @nconrad the padding for dnd-zone is too big, i.e., it currently sets to 85px, this would add 170px vertically. We should be able to adjust it to make Uploader use less vertical space.

**Comment by dawenx** [comment]
@nconrad i'm going through issues. i remember you implemented a few rounds of improvement on this part of UI, is this issue addressed? if so, can we close it?

**Comment by nconrad** [comment]
yeah, this should be fixed.  I left it open probably because it could be better.
