### ISSUE TITLE
FTP SITE IS BROKEN!!

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1811]
How can we have a reference genome that does not exist on the ftp site?
This is E. coli O157:H7 strain Sakai: 
![image](https://user-images.githubusercontent.com/7661533/33439823-35062b64-d5a3-11e7-86ca-f49933dc131f.png)

/vol/patric3/downloands/genomes/386585.9/
does not exist

**Comment by mshukla1** [comment]
Because we don’t call it “downloands”! ;)
