### ISSUE TITLE
Genome groups: can't create groups in a shared workspace

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1813]
I just created a shared workspace for a collaboration and I wanted to create fe feature groups / genome groups relevant for the project. 

I realized that there is no way to create new groups in the shared workspace. All groups 
end up in their default group folders in the home workspace, So, I had to move them to the desired workspace after their creation. 

We need to modify the group creation widget to allow users to save genome groups in select workspace. 

-Maulik

**Comment by dawenx** [comment]
I will look into this. I need to get some help from @nconrad to better understand workspace first.

**Comment by dawenx** [comment]
this fell through the crack of my desk, @nconrad has graciously agreed to help, especially to provide a way to list all workspaces a user has edit access.

**Comment by mshukla1** [comment]
@nconrad 

It looks like your changes have been deployed on the production site. I tried to create a genome group in a shared workspace  multiple times, however, every time, regardless of the folder I selected, the new group still ended up in my default genome group folder. 

On a positive note, I was able to copy a genome group from my home to a shared workspace. 

-Maulik

**Comment by nconrad** [comment]
So I'm not sure why this worked when I tested, but made a PR for the fix.   PATRIC3/p3_web#699 

Thanks!

**Comment by nconrad** [comment]
This is complete.
