### ISSUE TITLE
genome overview: collection date not displayed properly

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1814]
https://www.patricbrc.org/view/Genome/573.15432

The collection date looks fine in the solr, however not displayed correctly on the genome overview page. 

<img width="347" alt="screen shot 2017-12-05 at 11 15 34 am" src="https://user-images.githubusercontent.com/1236463/33620597-e653ac44-d9ad-11e7-9a7b-632903f11e8f.png">
<img width="423" alt="screen shot 2017-12-05 at 11 15 11 am" src="https://user-images.githubusercontent.com/1236463/33620598-e661b528-d9ad-11e7-9f75-093cac5e1528.png">

**Comment by nconrad** [comment]
The dates are expected to be of form MM/DD/YYYY (or MM-DD-YYYY, etc).  I'm guessing this one is DD/MM/YYYY ?   Some conversion may be needed before import?

The date picker on the genome editor saves the collection_date as a full datetime in solr, by the way.  I.e., 2017-12-14T06:00:00.000Z

**Comment by nconrad** [comment]
this was fixed by displaying whatever is given for `collection_date` (unless in ISO format)
