### ISSUE TITLE
NaN appears as cell in downloaded text file from heatmap

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1815]
I'm not sure what NaN is doing as a value for the number of proteins available in a particular protein family for a specific genome.  Look at attached spreadsheet
[ROS genes PGFams.txt](https://github.com/PATRIC3/patric3_website/files/1536604/ROS.genes.PGFams.txt)

**Comment by hyoo** [comment]
how can i reproduce this problem. how did you get the page before you click download button?

**Comment by hyoo** [comment]
@ARWattam NaN is typical javascript issue when it expect numbers but the value is not. I need more info, where were you, which dataset you were loading, etc.

**Comment by hyoo** [comment]
I believe this is due to the same reason #1823

**Comment by hyoo** [comment]
the fix is deployed on production.
