### ISSUE TITLE
Workspace: default sorting for list of groups

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1816]
Every time I create a new genome or feature group and then want to see it, I will have to go to the group list page, sort by date created, and then reverse sort it in order to find the group I just created. 

I think the default sort order should the most recent first, it will help cut down few clicks for most users. 

-Maulik

**Comment by nconrad** [comment]
I have a commit for this, but should note it could throw people off by having the sort order for groups different from the rest of the workspaces.  It's also just the creation time, not modification time.

**Comment by hyoo** [comment]
this fix is working as requested on alpha. closing.
