### ISSUE TITLE
Genome list: Remove disease from default view

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1817]
Genome list: 

The disease column is very sparse and not manually curated. I suggest that we remove it from the default table view to make room for other more important attributes. The disease should still be available from column selection menu. 

Please make sure the change is made in all related places, i.e. genome list, genome group etc. 

-Maulik

**Comment by dawenx** [comment]
this is done, added to the PR 625, will be on alpha soon.

**Comment by mshukla1** [comment]
Awesome! Thanks!

**Comment by hyoo** [comment]
deployed on alpha.

**Comment by mshukla1** [comment]
Please remove it disease from the facet / filter panel as well. 

-Maulik

**Comment by dawenx** [comment]
done, will be in next PR.

**Comment by mshukla1** [comment]
Looks good. Thanks. Verified on alpha.
