### ISSUE TITLE
ID Mapping: showing unwanted results 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1818]
I tried to search using a set of refseq locus tags below to find corresponding PATRIC ids.  

BB0457
BB0836
BB0839
BB0344
BB0467

The result table show multiple matches for each of the ids, mapping to PATRIC and refseq features, and CDS and non CDS features, like shown in the attached image. This is very confusing for users for several reasons. 

1. When I ask for a match to patric ids, the results should not show anything that doesn't have PATRIC ids. 
Solution: : match for only annotation = PATRIC or PATRIC ID not null. 

2. The table shows matches to multiple annotation sources and feature types. However, those attributes are not shown in the table. Making it difficult to understand what they are. 
Solution: make the id mapping result table look similar to the feature table + one additional column for user provided ids. It will be good to have the facet filter above the table as well, to provide easy filtering. 

<img width="1126" alt="screen shot 2017-12-07 at 6 35 46 am" src="https://user-images.githubusercontent.com/1236463/33716197-e1289bbc-db1a-11e7-925b-1731363fe552.png">

**Comment by aswarren** [comment]
Resolved in https://github.com/PATRIC3/p3_web/pull/643
