### ISSUE TITLE
ID Mapping: hide the form after submission 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1819]
I search for for > 20 ids using ID Mapping tool. 

When the results are displayed, the submission form is still there, taking up most of the page. I had to scroll down to see the results. 

Solution: hide the submission form whole displaying results, with a button at the top for "Edit and Resubmit". Please look at the to the BLAST tool for example. 

<img width="1439" alt="screen shot 2017-12-07 at 6 44 08 am" src="https://user-images.githubusercontent.com/1236463/33716132-a4effa28-db1a-11e7-888e-dda137e6358d.png">

**Comment by hyoo** [comment]
@JoshuaVSherman would you take a look? Try similar genome finer or blast.
When user submits a request, it should close the form and activate "Edit and Resubmit" button.

**Comment by JoshuaVSherman** [comment]
https://github.com/PATRIC3/p3_web/pull/672
