### ISSUE TITLE
in Genome List page, show nn per page and columns displayed are not preserved for browser back

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#182]
If I have a list of genomes (e.g. All Bacteria from Organism Dropdown, Genome List tab) facet Filter on Venter.   Change Show 20 to Show 250 and click Apply to All Tables (or just hit return), delete a bunch of columns but show Sequencing Center and Host Health.   Click on one of the Genomes, Show More for metadata and then do Browser Back and my column choices and number of genomes per page is rest to default.

(And, as a bonus question - I won't enter it as a separate issue though - is there any reason that on the table column headers, I can click on the "twisty" and then on Columns and the list stays there and I can select and deselect to my heart's content.   But if I click on Show/Hide in the Tool Bar, I can only do selection / deselection at a time and then I have to click Show/Hide again?   It's so frustrating to me when I click in the wrong place, that I would probably choose to get rid of the Tool Bar instance if it can't be made to be multiselect - even though it's easier to find.   Just my $.02

**Comment by mshukla1** [comment]
Harry, as we discussed,  column heading and contents are getting misaligned after I user back button. 
This is not critical for the June release, but we need to fix it as soon as possible after the release. 

![screen shot 2015-06-10 at 3 01 09 pm](https://cloud.githubusercontent.com/assets/1236463/8091390/9f922bbc-0f81-11e5-9362-0e7dcc1a90ab.png)

**Comment by hyoo** [comment]
this is specific to outdated website.
