### ISSUE TITLE
taxonomy

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1824]
Maulik, The following genomes do not have taxonomy information in SOLR.

1125778.3								
1608995.3								
1905567.4								
1939646.3								
1940241.3								
525366.3

**Comment by mshukla1** [comment]
ok, I will check and correct it. 

-Maulik

**Comment by mshukla1** [comment]
I have script now that can identify all genomes with obsolete taxon ids that are merged with some new taxon id, and update them accordingly.

There were 277 such genomes in the database at this time, they are all being updated as part of the July 2018 release.
