### ISSUE TITLE
Colors for job status page are indistinguishable. 

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1827]
Why do we have 2 shades of green?  In my opinion, blue was a fine color for completed.  I should add that I am color blind and can barely distinguish these. 

![image](https://user-images.githubusercontent.com/7661533/34110453-5298310e-e3cc-11e7-9501-8def0ed3c743.png)

**Comment by hyoo** [comment]
this is deployed on production.
