### ISSUE TITLE
Plasmid annotated with one feature shows no features

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1828]
I annotated a plasmid with the genome annotation service; it ran properly and created a single feature. That feature is in solr (query output below) but the features tab shows no output.

http://localhost:8983/solr/genome_feature/select?indent=on&q=genome_id: 45421.16&wt=json
{
  "responseHeader":{
    "status":0,
    "QTime":1,
    "params":{
      "q":"genome_id: 45421.16",
      "indent":"on",
      "wt":"json",
      "_":"1513711186158"}},
  "response":{"numFound":2,"start":0,"docs":[
      {
        "taxon_id":45421,
        "na_length":321,
        "start":2,
        "genome_name":"Plasmid pRKD418",
        "na_sequence":"ctgtgcacgatccccatgggacgtcgacctgaggtaattataacccgggccctatatatggatccaattgcaatgatcatcatgacagatctgcgcgcgatcgatatcagcgctttaaatttgcgaattctagctatagttctagaggtaccggttgttaacgttagccggctacgtatactccggaatattaataggcctaggatgcatatggcggccgcctgcagctggcgccatcgatacgcgtacgtcgcgaccgcggacatgtacagagctcgagaagtactagtggccacgtgggccgtgcaccttaagcttggc",
        "aa_sequence":"LCTIPMGRRPEVIITRALYMDPIAMIIMTDLRAIDISALNLRILAIVLEVPVVNVSRLRILRNINRPRMHMAAACSWRHRYAYVATADMYRAREVLVATWAVHLKLG",
        "sequence_id":"45421.16.con.0001",
        "feature_type":"CDS",
        "public":false,
        "aa_sequence_md5":"4a5ba19a6996c2c1f46b95a49e0c2253",
        "segments":["2..322"],
        "end":322,
        "genome_id":"45421.16",
        "owner":"olson@patricbrc.org",
        "feature_id":"PATRIC.45421.16.S77908.CDS.2.322.fwd",
        "aa_length":107,
        "accession":"S77908",
        "strand":"+",
        "location":"2..322",
        "product":"hypothetical protein",
        "pos_group":"45421.16.con.0001:322:+",
        "annotation":"PATRIC",
        "patric_id":"fig|45421.16.peg.1",
        "date_inserted":"2017-12-19T19:14:19.709Z",
        "date_modified":"2017-12-19T19:14:19.709Z"},
      {
        "na_length":322,
        "taxon_id":45421,
        "start":1,
        "genome_name":"Plasmid pRKD418",
        "feature_type":"source",
        "sequence_id":"45421.16.con.0001",
        "public":false,
        "end":322,
        "segments":["1..322"],
        "owner":"olson@patricbrc.org",
        "genome_id":"45421.16",
        "feature_id":"RefSeq.45421.16.S77908.source.1.322.fwd",
        "accession":"S77908",
        "strand":"+",
        "location":"1..322",
        "pos_group":"45421.16.con.0001:322:+",
        "annotation":"RefSeq",
        "date_inserted":"2017-12-19T19:14:19.709Z",
        "date_modified":"2017-12-19T19:14:19.709Z"}]
  }}

**Comment by hyoo** [comment]
use this link

https://www.patricbrc.org/view/Genome/45421.16#view_tab=features&filter=false

I saw some similar cases. A few months ago, we added some logic to decide which fields will be shown by default, I suspect this falls into a corner case of that logic. I will take a look.

Harry


On Dec 19, 2017, at 1:22 PM, olsonanl <notifications@github.com<mailto:notifications@github.com>> wrote:


I annotated a plasmid with the genome annotation service; it ran properly and created a single feature. That feature is in solr (query output below) but the features tab shows no output.

http://localhost:8983/solr/genome_feature/select?indent=on&q=genome_id: 45421.16&wt=json
{
"responseHeader":{
"status":0,
"QTime":1,
"params":{
"q":"genome_id: 45421.16",
"indent":"on",
"wt":"json",
"_":"1513711186158"}},
"response":{"numFound":2,"start":0,"docs":[
{
"taxon_id":45421,
"na_length":321,
"start":2,
"genome_name":"Plasmid pRKD418",
"na_sequence":"ctgtgcacgatccccatgggacgtcgacctgaggtaattataacccgggccctatatatggatccaattgcaatgatcatcatgacagatctgcgcgcgatcgatatcagcgctttaaatttgcgaattctagctatagttctagaggtaccggttgttaacgttagccggctacgtatactccggaatattaataggcctaggatgcatatggcggccgcctgcagctggcgccatcgatacgcgtacgtcgcgaccgcggacatgtacagagctcgagaagtactagtggccacgtgggccgtgcaccttaagcttggc",
"aa_sequence":"LCTIPMGRRPEVIITRALYMDPIAMIIMTDLRAIDISALNLRILAIVLEVPVVNVSRLRILRNINRPRMHMAAACSWRHRYAYVATADMYRAREVLVATWAVHLKLG",
"sequence_id":"45421.16.con.0001",
"feature_type":"CDS",
"public":false,
"aa_sequence_md5":"4a5ba19a6996c2c1f46b95a49e0c2253",
"segments":["2..322"],
"end":322,
"genome_id":"45421.16",
"owner":"olson@patricbrc.org<mailto:olson@patricbrc.org>",
"feature_id":"PATRIC.45421.16.S77908.CDS.2.322.fwd",
"aa_length":107,
"accession":"S77908",
"strand":"+",
"location":"2..322",
"product":"hypothetical protein",
"pos_group":"45421.16.con.0001:322:+",
"annotation":"PATRIC",
"patric_id":"fig|45421.16.peg.1",
"date_inserted":"2017-12-19T19:14:19.709Z",
"date_modified":"2017-12-19T19:14:19.709Z"},
{
"na_length":322,
"taxon_id":45421,
"start":1,
"genome_name":"Plasmid pRKD418",
"feature_type":"source",
"sequence_id":"45421.16.con.0001",
"public":false,
"end":322,
"segments":["1..322"],
"owner":"olson@patricbrc.org<mailto:olson@patricbrc.org>",
"genome_id":"45421.16",
"feature_id":"RefSeq.45421.16.S77908.source.1.322.fwd",
"accession":"S77908",
"strand":"+",
"location":"1..322",
"pos_group":"45421.16.con.0001:322:+",
"annotation":"RefSeq",
"date_inserted":"2017-12-19T19:14:19.709Z",
"date_modified":"2017-12-19T19:14:19.709Z"}]
}}

**Comment by olsonanl** [comment]
Odd, it shows up then. Going in the usual way when I click  on filters it shows there are none configured.

**Comment by hyoo** [comment]
https://github.com/PATRIC3/p3_web/commit/45bffba7d7d48082c6d86e6eebb7ea849fbfd2cf

This is fixed on alpha. When you don't have taxon_lineage_ids, it breaks here and stop going further.

Harry


On Dec 19, 2017, at 1:53 PM, olsonanl <notifications@github.com<mailto:notifications@github.com>> wrote:


Odd, it shows up then. Going in the usual way when I click on filters it shows there are none configured.

**Comment by JoshuaVSherman** [comment]
@hyoo above comment says that this is fixed on alpha, so can I put your name on this unassigned issue?
