### ISSUE TITLE
Missing download button for new type

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1832]
I added XML to the workspace types; when I browse to a folder containing an XML file I find it doesn't have an available download button.

<img width="1303" alt="untitled" src="https://user-images.githubusercontent.com/2152226/34179683-88f9a72c-e4d1-11e7-95f1-cb9734f57e2a.png">

**Comment by JoshuaVSherman** [comment]
@dmachi @hyoo I'm going to look into this issue, but i'm not able to assign it to myself, so please add me to this repository's write permissions please.  Thanks

**Comment by JoshuaVSherman** [comment]
ok this is now fixed in my fork, https://github.com/JoshuaVSherman/p3_web

![image](https://user-images.githubusercontent.com/13340120/35236865-db324b06-ff76-11e7-9b7b-8fbbfda1d448.png)

**Comment by hyoo** [comment]
@JoshuaVSherman make a pull request to develop branch. and please make sure you forked from develop branch.

**Comment by JoshuaVSherman** [comment]
pull request submitted
https://github.com/PATRIC3/p3_web/pull/661/files

**Comment by hyoo** [comment]
verified by Bob. closing.
