### ISSUE TITLE
Diff expression: use url encode for "," in experiment title

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1837]
A user used "," in the experiment title in the differential expression job ("CX vs UN, WT vs Mut"). The job completed successfully. When tried to access the results using the gene list and experiment
links from the job result page, it failed  because of the comma in the url (which I believe is also used
as a separator for multiple experiments). 

Please make sure that any special characters in the experiment title are URL encoded. 

The one below is the original url from the link, did not work. 
https://alpha.patricbrc.org/view/TranscriptomicsExperiment/?&wsExpId=/saatkinson@patricbrc.org/home/Kristich_RNAseq/Rockhopper_expression_analysis/CX%20vs%20UN,%20WT%20vs%20Mut

The one below after replacing , with %2C and it worked. 
https://alpha.patricbrc.org/view/TranscriptomicsExperiment/?&wsExpId=/saatkinson@patricbrc.org/home/Kristich_RNAseq/Rockhopper_expression_analysis/CX%20vs%20UN%2C%20WT%20vs%20Mut

-Maulik

**Comment by hyoo** [comment]
this is fixed and deployed on alpha, 3.5.2a
