### ISSUE TITLE
Annotation: uncommon genetic code 25

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1838]
The annotation job below failed because of uncommon genetic code / translation table 25. which is 
not handled by prodigal. 

Detailed of genetic code 25 available at: 
https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi#SG25 

[Please feel free to add any additional information regarding this issue here.]

********************** JOB INFO *************************

Job ID: 421390a6-6dfe-4fda-9403-399e1e0cf85e
Job Status: failed
App Name: GenomeAnnotationGenbank

Stdout: https://p3.theseed.org/services/app_service/task_info/421390a6-6dfe-4fda-9403-399e1e0cf85e/stdout
Stderr: https://p3.theseed.org/services/app_service/task_info/421390a6-6dfe-4fda-9403-399e1e0cf85e/stderr

Submit Time: 2017-12-31T10:15:17.682-06:00
Start Time: 2017-12-31T10:15:17.682-06:00
Completed Time: 2017-12-31T10:15:17.682-06:00

Paremeters:
{code}
{
    "output_file": "GCA_001007975.1",
    "_clientgroup": "AppService-batch",
    "genbank_file": "/PATRIC@patricbrc.org/home/Reference Data/Genomes_from_GenBank/Dec2017/GCA_001007975.1/GCA_001007975.1.gbff",
    "public": 1,
    "output_path": "/PATRIC@patricbrc.org/home/Reference Data/Genomes_from_GenBank/Dec2017/GCA_001007975.1",
    "import_only": 0,
    "queue_nowait": 1
}
{code}

**Comment by olsonanl** [comment]
Aha. Prodigal release 2.6.2 release notes:

Added support for NCBI Genetic Code 25.

https://github.com/hyattpd/Prodigal/releases

**Comment by olsonanl** [comment]
Updated to prodigal 2.6.3 and modified code to log prodigal version, not run glimmer on gc25 jobs. Still need GUI fixed per #2193
