### ISSUE TITLE
Similar genome finder needs the query genome in the output

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1841]
The results page for the similar genome finder  should have an indication of what the query genome is. We find we keep forgetting what we searched for when looking at the output.

**Comment by JoshuaVSherman** [comment]
@olsonanl Hey Bob, is this something for you to investigate or someone else please?

**Comment by olsonanl** [comment]
This is a UI issue.

**Comment by JoshuaVSherman** [comment]
@olsonanl Good morning, can I just remove the button Edit Form and Resubmit and have that initial form display aways there?
![image](https://user-images.githubusercontent.com/13340120/35513990-d1bb91d4-04d2-11e8-9f99-c705cac557da.png)

**Comment by JoshuaVSherman** [comment]
https://github.com/PATRIC3/p3_web/pull/672
