### ISSUE TITLE
Need to update Specialty Genes Data Landing Page with new data sources

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1842]
For Antibiotic Resistance description, remove ARDB and add PATRIC AMR curation and NDARO (https://www.ncbi.nlm.nih.gov/pathogens/antimicrobial-resistance/). 

Need 2 new categories with descriptions: 
1. Transporters (uses TCDB http://www.tcdb.org/)
2. Essential genes (uses PATRIC model reconstruction?  need link)

**Comment by hyoo** [comment]
@rkenyon or @mshukla1 would you provide one line description about the data type?

**Comment by hyoo** [comment]
how does this sound like?

Transporters refer to proteins that serve the function of moving other materials within an organism. We have integrated and mapped proteins from Transporter Classification Database.

Essential genes refer to the genes that are critical for the organism's survival. We have built PATRIC reconstruction model to identify essential genes.

**Comment by hyoo** [comment]
<img width="981" alt="image" src="https://user-images.githubusercontent.com/1236467/36038200-a667c1e6-0d84-11e8-9afb-eaa661000283.png">

updated
