### ISSUE TITLE
similar genome finder doesn't work with fasta upload

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1846]
Selecting a fasta seems to trigger a validation problem; it doesn't turn on the submit button.

<img width="762" alt="screen shot 2018-01-16 at 1 50 55 pm" src="https://user-images.githubusercontent.com/2152226/35016644-6375d792-face-11e7-8e55-3e43914dbc4b.png">

**Comment by dawenx** [comment]
this is fixed and it's on alpha.

**Comment by dawenx** [comment]
verified this fix on production, close the ticket.
