### ISSUE TITLE
PATRIC user unable to copy to PATRIC Workshop Workspace

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#1847]
Today I had to become the PATRIC user to help setup the PATRIC Workshop workspace.
During that time I was unable to copy a file into a shared workspace folder but I was able to copy it to the top level workspace itself.

https://patricbrc.org/workspace/public/PATRIC@patricbrc.org/PATRIC%20Workshop/RNA-Seq

The file/folder in question:
rockhopper_stream_bam can now be found at 
https://patricbrc.org/workspace/public/PATRIC@patricbrc.org/PATRIC%20Workshop

Further it seems the PATRIC user doesn't have permission to delete/move that job result folder after it was placed there.
![image](https://user-images.githubusercontent.com/229173/35061378-138bc964-fb8f-11e7-9177-a8576f2a0227.png)

**Comment by aswarren** [comment]
@nconrad believes this to be a sulogin / sudo issue.
This seems likely since when I login through sulogin shared workspaces do not appear.
![image](https://user-images.githubusercontent.com/229173/35062314-e75e3d06-fb91-11e7-8db5-b3a22a849122.png)

Unlike when signed in directly through the user
![image](https://user-images.githubusercontent.com/229173/35062343-06b803a8-fb92-11e7-991c-88d628440301.png)

**Comment by mshukla1** [comment]
I believe this has been resolved with the new SU implementation. When I login as SU now or pretend to be another user, I see relevant shared workspaces.
