### ISSUE TITLE
JBrowse sub queries are not optimal

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1849]
i noticed that Jbrowse queries in multiple chunks with some overlaps,
```
[Wed, 17 Jan 2018 23:12:48 GMT] - GET /jbrowse/genome/520456.3/features/NZ_EQ999575?annotation=RefSeq&start=0&end=149999 200 14492.107 [-] ms - 311478
[Wed, 17 Jan 2018 23:12:48 GMT] - GET /jbrowse/genome/520456.3/features/NZ_EQ999575?annotation=RefSeq&start=0&end=99999 200 14572.648 [-] ms - 210596
[Wed, 17 Jan 2018 23:12:48 GMT] - GET /jbrowse/genome/520456.3/features/NZ_EQ999575?annotation=RefSeq&start=0&end=249999 200 14595.846 [-] ms - 520099
[Wed, 17 Jan 2018 23:12:48 GMT] - GET /jbrowse/genome/520456.3/features/NZ_EQ999575?annotation=RefSeq&start=0&end=199999 200 14635.131 [-] ms - 412058
[Wed, 17 Jan 2018 23:12:48 GMT] - GET /jbrowse/genome/520456.3/features/NZ_EQ999575?annotation=RefSeq&start=99999&end=349999 200 14729.849 [-] ms - 515803
[Wed, 17 Jan 2018 23:12:49 GMT] - GET /jbrowse/genome/520456.3/features/NZ_EQ999575?annotation=RefSeq&start=49999&end=299999 200 14742.314 [-] ms - 523296
[Wed, 17 Jan 2018 23:12:49 GMT] - GET /jbrowse/genome/520456.3/features/NZ_EQ999575?annotation=RefSeq&start=0&end=124999 200 227.641 [-] ms - 260175
[Wed, 17 Jan 2018 23:12:49 GMT] - GET /jbrowse/genome/520456.3/features/NZ_EQ999575?annotation=RefSeq&start=149999&end=399999 200 339.670 [-] ms - 516371
[Wed, 17 Jan 2018 23:12:49 GMT] - GET /jbrowse/genome/520456.3/features/NZ_EQ999575?annotation=RefSeq&start=24999&end=149999 200 266.165 [-] ms - 260038
[Wed, 17 Jan 2018 23:12:49 GMT] - GET /jbrowse/genome/520456.3/features/NZ_EQ999575?annotation=RefSeq&start=49999&end=174999 200 237.629 [-] ms - 261708
[Wed, 17 Jan 2018 23:12:49 GMT] - GET /jbrowse/genome/520456.3/features/NZ_EQ999575?annotation=RefSeq&start=99999&end=224999 200 243.090 [-] ms - 257752
[Wed, 17 Jan 2018 23:12:49 GMT] - GET /jbrowse/genome/520456.3/features/NZ_EQ999575?annotation=RefSeq&start=74999&end=199999 200 252.572 [-] ms - 260147
[Wed, 17 Jan 2018 23:12:49 GMT] - GET /jbrowse/genome/520456.3/features/NZ_EQ999575?annotation=RefSeq&start=124999&end=249999 200 213.227 [-] ms - 262180
```

see start and end in params.

Is it possible to minimize overlaps? it seems like window size is 250,000 is set somewhere. @aswarren or @dmachi , do you know where it is coming from?

**Comment by dmachi** [comment]
I’m not exactly sure where the size comes from (other than 25k being our default query size limit).  Its not clear to me how easy this will be to change in jbrowse.  I think the overlapping has to do with how it wants to page and keep chunks that are larger than the view you are actually seeing on the screen, but I can’t remember for sure.

**Comment by aswarren** [comment]
This is related https://github.com/PATRIC3/patric3_website/issues/1328 but this will only help if it is the transfer time not the query time.
I have yet to find the logic governing parameters of how it issues these queries.

**Comment by aswarren** [comment]
I whittled the URL down to just load the PATRIC track.
https://patricbrc.org/view/Genome/316407.9#view_tab=browser&tracks=PATRICGenes&loc=AC_000091%3A1..100000&highlight= 
The first request seems to have a long response time:

![image](https://user-images.githubusercontent.com/229173/35589236-2e4fe5fe-05d1-11e8-8efd-bb8c45b4f45d.png)

![image](https://user-images.githubusercontent.com/229173/35589285-5442b462-05d1-11e8-9ced-13de2eef6ea6.png)


Waiting (TTFB). The browser is waiting for the first byte of a response. TTFB stands for Time To First Byte. This timing includes 1 round trip of latency and the time the server took to prepare the response.

**Comment by hyoo** [comment]
This was query time that taking inside solr. This was due to multiple OR conditions and  i was able to remove many of them. 
https://github.com/PATRIC3/p3_api/commit/3c29e48853e40c4ee4fe57b03675d14a3b815a10

This change makes queries respond in half time. 96s to 45s, for example.
