### ISSUE TITLE
data problem?

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#185]
I  come across this genome and found one feature without patric ID nor product, but it has coordination and feature type though.

https://www.patricbrc.org/portal/portal/patric/FeatureTable?cType=genome&cId=1773.224&featuretype=&annotation=PATRIC&filtertype=#

**Comment by mshukla1** [comment]
There were total 517 CDS in the database without patric id, function and aa sequence. I have added missing information for all of them. 

-Maulik
