### ISSUE TITLE
Proteome comparison needs to take genome group

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1850]
The proteome comparison tool needs to accept a genome group to define the comparison genomes.

**Comment by chmao1** [comment]
@ARWattam could you comment on this requirement from users' perspectives. Thanks.

**Comment by ARWattam** [comment]
I think that we need to think this request through carefully.  Users will try to upload groups with many more genomes than the service can handle, and then what do we do?  Take a random 9?  Take the first 9 alphabetically?  I like the idea of making the user select each individually.  Perhaps if we had a drop down box that showed all the genomes in the group and allowed them to select individually?  But that seems like a lot of front end changes for questionable value.

**Comment by mshukla1** [comment]
I think one of the objectives here is to have consistent way of selecting genomes in all the comparative 
tools: Select one at a time or select existing groups. As of now, some services (or most) allow selection 
of genome groups, and some don’t.  

If the selected genome group contains more genomes than what is supported by a respective service, 
we can always alert the user, like we do in phylogenetic tree service (see attached screenshots). 
The message can say there are more genomes in your genome group than supported by the current 
service (8 genomes), you can create another genome group with less than N genomes to use in this 
service. 

Say, I want to have a genome group of 8 genomes and run proteome comparison, build tree and 
see them in protein family and pathways. Currently, I will have to go and make the same selections 
separately in each of the tools. If the service fails, or if I want to compare with a different reference 
or try different parameters, each time I will have to select 8 genomes one by one. 

-Maulik

**Comment by ARWattam** [comment]
I like the idea of the message.  Then the user is forced to make a decision on what to include.  I haven't tried loading anything too big on the tree service (as you know I strictly follow the rules) but if we have that in place, it seems like it would not be too bad to include something similar here.

**Comment by chmao1** [comment]
@olsonanl Could you give me a permission to access to the server side codes for Proteome comparison service?

**Comment by olsonanl** [comment]
Which code do you mean?

**Comment by olsonanl** [comment]
I'm with maulik on this. I submitted this bug because at the workshop a user in fact already had a genome group that he wanted to compare. There is no reason in interfaces where we allow multiple genomes to not allow a genome group. If there are limitations in the service on numbers of genomes allowed, the options are to say that and disallow the group, or better, bring up a dialog that offers an easy way to select a subset.

**Comment by chmao1** [comment]
@olsonanl Bob, I meant the backend service app that Fangfang implemented. Is that code in git? How do I access it? Thanks.

**Comment by chmao1** [comment]
I should be able to add this enhancement.

**Comment by olsonanl** [comment]
The application script is here

https://github.com/TheSEED/app_service/blob/master/scripts/App-GenomeComparison.pl

**Comment by chmao1** [comment]
Implemented and made a pull request to p3_web.

**Comment by mshukla1** [comment]
thanks, Chunhong.

**Comment by olsonanl** [comment]
Very cool. That'll cut 5 minutes off Rebecca's proteome webcast :-)

Is it possible to change the order of the genomes in the list after they've been added?

**Comment by chmao1** [comment]
If the genomes are individually added, the users can delete and re-add the genomes in the order they want. However, currently, if they add a genome group, the order of the genomes in the group is the same as what's in the workspace.

**Comment by chmao1** [comment]
Available in production.
