### ISSUE TITLE
Need user id, name, and email in the feedback

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1851]
Neal, 

We need user login name, full name (first and last name), and email address in the jira tickets generated by the "provide feedback" and "report job" from on the website. 

Without this information, Rebecca and I need to go to several different places or people to get such information before we can respond to the user. This is becoming more and more frustrating now as we are getting multiple user requests per day. 

Can you please address this in all relevant places on the website and submit a pull request asap (i.e., in next few days)?

-Maulik

**Comment by dmachi** [comment]
The email portion of this has been fixed in terms of the email address correctly getting into Jira as the 'reporter' for the Provide Feedback dialog.  The message itself has not been changed.

**Comment by nconrad** [comment]
I don't see a ticket for today to see if the email address issue is fixed.  Is there still more to do then? 
 Should I assign this to you, @dmachi?

**Comment by dmachi** [comment]
The message still needs to get updated at https://github.com/PATRIC3/p3_web/blob/master/routes/reportProblem.js#L101-L109
but what gets passed to that function also needs to be sure to include the desired info at https://github.com/PATRIC3/p3_web/blob/master/routes/reportProblem.js#L159 so needs to be passed along from the middleware function before it.  
I was just trying to make sure the other part was fixed since Maulik assigned the ticket to you :)  But I can fix this part as well.

**Comment by JoshuaVSherman** [comment]
I have this fixed in my fork
![image](https://user-images.githubusercontent.com/13340120/35243453-ef9b25f4-ff8a-11e7-8cf9-5806a7d831a4.png)

**Comment by JoshuaVSherman** [comment]
pull request submitted
https://github.com/PATRIC3/p3_web/pull/661/files

**Comment by hyoo** [comment]
1. report with signed in
<img width="751" alt="image" src="https://user-images.githubusercontent.com/1236467/35636755-d38250b0-0677-11e8-818f-349519f7a7e1.png">

2. report without signed in, and leave email field empty
<img width="750" alt="image" src="https://user-images.githubusercontent.com/1236467/35636808-f8291494-0677-11e8-9233-fa4969678877.png">

3. report without signed in, and provide email
<img width="751" alt="image" src="https://user-images.githubusercontent.com/1236467/35636821-ffa7c5da-0677-11e8-95b9-f95db4839f9e.png">

**Comment by hyoo** [comment]
from job report issue.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/1236467/35637002-7bedfede-0678-11e8-883d-91269fa50b58.png">

**Comment by hyoo** [comment]
I think every case works as expected. closing.
