### ISSUE TITLE
Proteome comparison: fails due to bad patric id

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1852]
Chunhong, 

The proteome comparison job below failed because one of the genomes had a CDS with weird 
PATRIC id, rast|0.CDS.1|JS78_09620|, because of a bug in the annotation service. 

Bob and I are working on fixing the bug in the annotation service and correcting patric_ids 
for the features already in the database. In addition to that, we should also update the proteome 
comparison service so it can handle such ids without failing. 

You can reproduce this problem by using the following two genomes in proteome comparison. 
Can you please look into it and fix it? 

       "2754.20",
        "2754.24"

*** CIRCOS ERROR ***

  The line

  id=rast|0.CDS.1|JS78_09620|

  from file

  /scratch/tmp/ZAheHqi4QC/circos/ref_genome.txt

**Comment by chmao1** [comment]
I tried it and also failed. The error is from the server side (Fangfang's code). Unfortunately, I don't have an access to his repository. Could you or someone grant me an access to his repository or @levinas take a look at this?

**Comment by mshukla1** [comment]
@maovt any progress on this?

**Comment by chmao1** [comment]
@mshukla1 @olsonanl I checked again and the job failed. The web UI works fine and parameters are passed correctly. Unfortunately, I'm not able to test the backend program. I checked the source code (https://github.com/TheSEED/app_service/blob/master/scripts/App-GenomeComparison.pl), and noticed the following lines:

line 29    my $data_api = Bio::KBase::AppService::AppConfig->data_api_url;
line 30    # my $data_api = 'http://www.alpha.patricbrc.org/api';
line 30
line 32    my $script = Bio::KBase::AppService::AppScript->new(\&process_proteomes);

Could it be  possible that $data_api is using the wrong url? I'm not familiar with KBase code. It seems that this app is fetching the wrong feature ids. @olsonanl could you help to check and see whether this app is using the correct data api url? Thanks

**Comment by mshukla1** [comment]
Chunhong, find me online Tomorrow and I will explain the problem.

**Comment by chmao1** [comment]
okay

**Comment by mshukla1** [comment]
I have updated the erroneous peg ids in the database, which were causing problem with the circos. 

I have tested proteome comparison with the two genomes above and it is working fine. 

<img width="850" alt="screen shot 2018-07-14 at 12 15 15 pm" src="https://user-images.githubusercontent.com/1236463/42726787-bbebe3ee-875f-11e8-807b-f1107cbefd5b.png">
