### ISSUE TITLE
Bad patric ids for selenocysteine proteins

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1854]
There are >6500 proteins with weird patric ids in the database, like rast|0.CDS.1. 

https://www.patricbrc.org/view/FeatureList/?and(keyword(rast),keyword(cds))#view_tab=features&defaultSort=-score

It looks like selenocysteine proteins are called by a special module, which doesn’t assign the appropriate peg ids to those proteins. 

         "annotations" : [
            [  
               "Add feature called by find_special_proteins",
               "find_special_proteins",
               1500812770.61732,
               "fa107313-549e-4617-ab34-53aa50b8b526"
            ],
            [
               "Set function to Selenide,water dikinase (EC 2.7.9.3) @ selenocysteine-containing",
               "find_special_proteins",
               1500812770.61732,
               "fa107313-549e-4617-ab34-53aa50b8b526"
            ],
            [
               "Function updated to Selenide,water dikinase (EC 2.7.9.3) @ selenocysteine-containing",
               "annotate_proteins_kmer_v2",
               1500812951.1051,
               "1d5b4d31-3c41-4f6a-af65-a3455e36db15"
            ],
            [
               "3 aliases propagated from fig|1277350.3.peg.2039",
               "PATRIC@patricbrc.org",
               1500812970.17148,
               "5f5abc68-4294-4fc2-b9df-cc145a1f5f08"
            ],
            [
               "Feature renumbered from rast|0.CDS.3 to rast|0.CDS.1",
               "PATRIC@patricbrc.org",
               1500812972.23812,
               "77598842-b6c0-49ec-8219-b18079a90ef0"
            ]
         ]

**Comment by olsonanl** [comment]
This is resolved at least in the latest release going in this week; it appears to have also been resolved in the currently running production system.
