### ISSUE TITLE
Job submission forms: check for same file in paired end reads

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1855]
One of the common mistake users make  is that they select the same file twice in paired end read files, which results in job failure. 

"paired_end_libs": [
"/ARWattam@patricbrc.org/home/SRR6382381_1.fastq",
"/ARWattam@patricbrc.org/home/SRR6382381_1.fastq"
]

If possible, we should check if same file is selected in pair1 and pair2 boxes, raise a flag and disable the submission button. 

This fix should be applied to all relevant services, i.e. assembly, variation, rna-seq, tn-seq and metagenomics binnning. 

-Maulik

**Comment by dawenx** [comment]
working on this.

**Comment by dawenx** [comment]
i have fixed this for assembly, variation, rna-seq, tn-seq services. metagenomics UI seems to be different and i need to discuss with @hyoo to make a plan.

@mshukla1 let me know if you want me to submit a PR just for those 4 services so that we can roll it out in Jan. release. thanks!

**Comment by hyoo** [comment]
https://github.com/PATRIC3/p3_web/pull/665
already deployed on alpha.

need to verify

**Comment by dawenx** [comment]
This particular fix is not done for metagenomics binning service. Since I'm planning to work on it along with another 2 issues, maybe we can close this one?

**Comment by hyoo** [comment]
I have verified the fix on assembly, variation, rna-seq, and tn-seq pages. Lets leave metagenome binning to  #1783 and close this.

**Comment by dawenx** [comment]
just wanted to make record complete: this is fixed for metagenome binning and it's on alpha now.
