### ISSUE TITLE
Workspace: unable to copy group to a shared workspace

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1856]
This problem was reported by a user and then verified by me. 

Currently, I can not copy a genome or feature group I created to a workspace shared with me with edit privileges. When I click copy, only the workspaces owned by me are shown in the file selector. 

Also note that the website doesn't allow me to create new groups directly into the shared worksace either! 

Both of these issues need to be addressed with high priority. 

-Maulik

**Comment by nconrad** [comment]
Regarding first issue, this must be some sort of oversight--sorry.  I'll get that fixed.  

Regarding the second issue, @dawenx was last working on that in https://github.com/PATRIC3/patric3_website/issues/1813.

**Comment by nconrad** [comment]
I looked into this and it turns out to be a workspace inconsistent permission issue that is causing the problem (the way it is coded anyway).   https://github.com/PATRIC3/Workspace/issues/61

@olsonanl  Have you happened to look into that issue?

**Comment by olsonanl** [comment]
As I referred to in the other ticket, I'd need to see the specific inconsistency that is causing this problem.

**Comment by nconrad** [comment]
I can try to see if I can get another workspace into that state next week.  

I think I have addressed this ticket with the last commit.
