### ISSUE TITLE
Workspace: job status table: Add Service column to be consistent with service names

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1860]
Currently, this table uses app names which often are not consistent with the service names we use in the dropdown list..

**Comment by chmao1** [comment]
The "App" column will be hidden, but still can be added back with the "plus" button.

**Comment by chmao1** [comment]
The item detail panel will also include the corresponding service names.

**Comment by chmao1** [comment]
Will be available in the next build

**Comment by hyoo** [comment]
verified.
<img width="793" alt="image" src="https://user-images.githubusercontent.com/1236467/35638120-e0a37c66-067b-11e8-801e-c3318459d9a4.png">
