### ISSUE TITLE
Reset on Variation service clears page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1861]
I am trying to run all combinations on the Variation service, and I have a number of reads.  When I hit the reset button, the page clears, and I have to laboriously select and enter all the reads, all over again.  The service should leave the entered reads.  The proteome comparison service does this quite well, and it should be the model for assembly and variation.  Probably RNA-Seq, too, although I haven't marched through that.

**Comment by dawenx** [comment]
@ARWattam I understand different behaviors on different services cause confusion.

But the 'reset' should set the UI to the initial state by definition, e.g., when the service UI is first loaded. I would argue proteome comparison service could have a bug on reset or this behavior was specifically requested and implemented. maybe we should have a discussion. @maovt @hyoo

**Comment by mshukla1** [comment]
I just tried variation service myself. I selected a set of fastq files from the workshop example and submitted with default parameters. 

After submission, all the form values stay as is, including selected fastq files. The only field that gets cleared is output name, to prevent user from accidentally resubmitting the same job or another job with the same output name. 

I can select a different recipe or reference genome and a new output name, without selecting fastq files again. 

This behavior is consistent with all other apps. 

Closing the issue. 

<img width="750" alt="Screen Shot 2019-04-15 at 6 18 53 AM" src="https://user-images.githubusercontent.com/1236463/56129274-55e68c00-5f47-11e9-8b06-6ee30194465d.png">

**Comment by ARWattam** [comment]
I do this myself, but the user will not understand this and will hit the reset button.  If you really want this as the alternative, I suggest that you remove the reset button.

**Comment by dawenx** [comment]
I suggest to have a discussion on this on Tuesday. To me, 'reset' means resetting everything and most services are behaving like this, in fact, most places, not just PATRIC, a reset button resets everything. I personally don't think we should remove the reset button, in stead, maybe we should educate our users and set their expectation to right level.

**Comment by ARWattam** [comment]
You know what?  You both are absolutely right.  I have had some pre-conceived notion…maybe based on how the website used to work…that reset just enabled it to resubmit the job.  It is working correctly now and doesn’t need to be adjusted.
