### ISSUE TITLE
ID Mapper should provide examples of ID types

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1863]
I always get confused when I look at the long list.  I think for RefSeq locus tag we should provide an example (Like Rv001) to distinguish it from RefSeq (which I assume is an NP number or some such).  Often the user does not know what exactly they are trying to map over.

**Comment by JoshuaVSherman** [comment]
@mshukla1 Good morning, I just spoke with Rebecca, and I hope that you have something to send me that explains what are the categories for ID mapper drop-down? My email is josh73@bi.vt.edu and if you have some time for a phonecall to discuss further, that would be awesome, my cell is 540-494-8035
