### ISSUE TITLE
Proteome Comparison order in circos should match order when genomes submitted

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1866]
Is it possible to do this?  I have been paying attention to the order of the comparison genomes when I submit them, and in the circos view they don't have the same order.  A user might want to arrange the genomes by phylogeny for the svg that they use for a publication

**Comment by chmao1** [comment]
@ARWattam Can you provide an example where the order is not what you expected? I'll look into it.

**Comment by chmao1** [comment]
The order is from outer to inner ring.
