### ISSUE TITLE
DATA - missing metadata non-NCBI genomes from March release

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#187]
combining info from several emails from multiple people and putting here to track
Harry reported that 3202 genomes are missing genome_status
Becky surmised that it was 3088 from the Strep pneumoniae, 108 from  from Mtb Beijing and probably 6ish other genomes that the PATRIC users submitted to RAST and asked us to include at PATRIC.

Besides genome status, other issues include
Strep pneumoniae doesn't have sequencing center or Assembly method or a comment that allows us to tie them together as a project (unless we use publication 25101644)
Mtb Beijing doesn't have sequencing center or Assembly method

not sure about the user submitted genomes or if there is other metadata that should be included

**Comment by mshukla1** [comment]
- Genome status have been added for all genomes. 

- 109 Mtb Beijing genomes: Project title has been added as comment: "Global diversity of the Mycobacterium tuberculosis Beijing genotype". They also have common pubmed id: 25599400

- 3084 Strep pneumoniae: Project title added as comment: "Streptococcus pneumoniae evolution and population structure during longitudinal sampling in a defined human population". They also have same pubmed id: 25101644
