### ISSUE TITLE
job status detail panel is not formatted while it is running.

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1872]
phylogenetic tree job is not well rendered while it is running.

<img width="318" alt="image" src="https://user-images.githubusercontent.com/1236467/35640557-203e33be-0683-11e8-81a2-2486d5ecc268.png">

**Comment by nconrad** [comment]
This is duplicate of https://github.com/PATRIC3/patric3_website/issues/2035.  I'll address for may.
