### ISSUE TITLE
Weird collection date

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1873]
https://www.patricbrc.org/view/Genome/34095.3
Has collection data of NaN/NaN/NaN

**Comment by mshukla1** [comment]
This is what gets displayed when the collection date is “not collected” in the database. 
They all will be cleaned up by the end of the day as part of the release. 

-Maulik

**Comment by hyoo** [comment]
#1814

**Comment by hyoo** [comment]
this is not fixed by Jan 2018 data release. I still see it. pushing to Feb

**Comment by mshukla1** [comment]
All collection dates were cleaned up as part of the last data release. I don't see this error any more. 

-Maulik
