### ISSUE TITLE
When ID mapper gets a 404

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#1874]
It should give a failure message instead of just showing the spinning wheel
![image](https://user-images.githubusercontent.com/229173/35698093-1ac5f25a-075a-11e8-8c33-5357ac867bee.png)

**Comment by JoshuaVSherman** [comment]
@aswarren no longer receiving a 404, but was still locked up with source undefined, so I fixed that issue.

**Comment by JoshuaVSherman** [comment]
https://github.com/PATRIC3/p3_web/pull/672/commits

**Comment by JoshuaVSherman** [comment]
@aswarren guess this is not fixed, just received a 404 this morning

**Comment by JoshuaVSherman** [comment]
https://github.com/PATRIC3/p3_web/pull/672
