### ISSUE TITLE
Missing columns in Variation Service?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1875]
When I run the variation service using BWA-mem and FreeBayes, the following 2 columns are included at the end of the all.var.html and  and all.var.tsv files:
snpEff_type 
snpEff_impact
These two columns are extremely valuable.  When I run any of the other combinations (see below), they are missing.  Is this something that is specific to that combination, or is it a bug that prevents the column being added to the other options.
BWAmem	SAMtools
BWAmem-strict	FreeBayes
BWAmem-strict	SAMtools
Bowtie2	FreeBayes
Bowtie2	SAMtools
LAST	FreeBayes
LAST	SAMtools

**Comment by mshukla1** [comment]
We discussed this during hackathon.

Those columns require genbank file and input, which we don't have on the FTP site. 

We are planning to add support for genbank and other file types in the data API. 

-Maulik

**Comment by chmao1** [comment]
@mshukla1 The variation service requires the genbank files at the PATRIC FTP site. ftp://ftp.patricbrc.org/genomes/$gid/$gid.PATRIC.gbf
However, the PATRIC.gbf files are not available. Are you going to provide these files?

**Comment by mshukla1** [comment]
No, the goal is to generate the genbank files on the fly by calling another set of scripts. 
That way, it can work for both public and private genomes. 

Bob can provide details on those scripts and hoe to call them from the variation service. 

-Maulik

**Comment by chmao1** [comment]
@olsonanl Hi Bob, Please see above comments. Could you provide details on the genbank file generation scripts and how to call them from the variation service? Thanks!

**Comment by olsonanl** [comment]
```p3-gto 511145.12```

will write 511145.12.gto

then

```rast-export-genome -i 511145.12.gto -o 511145.12.gb genbank```

will write it as a genbank file in 511145.12.gb.

**Comment by chmao1** [comment]
@olsonanl I have a couple of questions:
1. Are the script calls from  Bio::KBase::AppService::AppScript? If not, what library do we use?
2. When using "p3-gto 511145.12", where the output file is stored? do we need to specify the path?
3. When using "rast-export-genome -i 511145.12.gto -o 511145.12.gb genbank", do we need to specify the path where the input and output files are located? Is "genbank" a parameter and should be used as is?

Thanks

**Comment by olsonanl** [comment]
They'd be called from the variation app as needed (App-Variation.pl). You'd use a system command to invoke them.

The p3-gto output goes into genome-id.gto (that's where the 511145.12.gto came from in my example).

The app scripts are set up by the infrastructure to run in a location where current directory is in temp space so you can write files without specifying a full path (assuming you haven't had the script change directory).

**Comment by chmao1** [comment]
@olsonanl I meant when we use p3-gto and rast-export-genome in App-Variation.pl, which library should we include in App-Variation.pl?  e.g. "use Bio::KBase::AppService::AppScript"?

**Comment by olsonanl** [comment]
There's no library needed. Those are command line programs that will be available in your path

**Comment by maovt** [comment]
@olsonanl what are the commands for generating .gff and .fna files?

**Comment by olsonanl** [comment]
For gff use gff instead of genbank in the rast-export-genome command. GFF is a funny format and not completely specified so I’m not sure if it will agree with what the tool is looking for.

For fna I assume you mean feature DNA; use rast-export-genome with the parameter feature_dna.

—bob

On Aug 2, 2018, at 2:30 PM, maovt <notifications@github.com<mailto:notifications@github.com>> wrote:


@olsonanl<https://github.com/olsonanl> what are the commands for generating .gff and .fna files?

**Comment by chmao1** [comment]
Thanks

**Comment by chmao1** [comment]
Fixed and available in production. @ARWattam please test it.

**Comment by chmao1** [comment]
tested and worked on production
