### ISSUE TITLE
new p3-user sulogin

### ISSUE THREAD

**Issue by dmachi** [PATRIC3/patric3_website#1876]
I've done some basic review of the sulogin functionality for the new p3-user/p3-web service.  The following should be updated:

1.  For admin users, add a link to the sulogin page from the person menu in the top right
2. Change the text on the su login page:
   a.  Put a header at the top of the form that says something like "Impersonate User"
   b.  Put some instructions at the top saying what this does and warning people to be careful (with great power comes great responsibility)
   c.  The target user field should be labeld "User to Impersonate".  The password field shoud be labeled "Your Password"
3.  When an invalid targetUser or password is provided, there is no error shown, it simply redirects you to the home page still logged in as the original user.
4.  When Impersonating a user, the "revert to original user" button should be in the top right person menu.  It can also remain on the the /sulogin page.

**Comment by mshukla1** [comment]
I like to add one more thing, if it isn’t address already. 

The workspace menu in the top navigation bar doesn’t show the home workspace and 
groups for the user impersonated. I usually modify the page url manually to go to the 
workspace home.

-Maulik

**Comment by dmachi** [comment]
Maulik,  that particular issue has been addressed.

**Comment by mshukla1** [comment]
I just tried, I don’t see the change on alpha. Is it deployed?

**Comment by dmachi** [comment]
This ticket is related to the testing we are doing on the new p3-user system, so the comment was related to that system.  However, for the current p3-user it is fixed on production as well.   I will deploy that update to alpha too as I forgot to update that one.

**Comment by dmachi** [comment]
I’ve updated the alpha version now too.
