### ISSUE TITLE
Do not allow slashes in file, folder, and workspace names

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1878]
Often special characters (like # , ; etc) break the services and links to result pages. 

- Come up with system-wide policy and guidelines for supporting special characters in workspace file/dir and job names
- make sure special characters are handled appropriately and don’t break any services or links
- implement it consistently across the system.

**Comment by JoshuaVSherman** [comment]
https://github.com/PATRIC3/p3_web/pull/729

**Comment by JoshuaVSherman** [comment]
@olsonanl I could prevent submission if names include pound symbol, semicolon, and slashes if that is what you all decide, just let me know, thanks

**Comment by olsonanl** [comment]
I see no reason to eliminate any character but slash since that defines the folder hierarchy. Code that breaks in the face of those characters is broken and needs to be fixed.

**Comment by JoshuaVSherman** [comment]
@olsonanl I will prevent slashes then (frontend) and submit a new ticket for any backend services that may need validation, thanks
