### ISSUE TITLE
Need to resolve host metadata

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1881]
Human and Homo sapiens must be combined to Human, Homo sapiens.  A user has complained about this (and its not me).  When its messed up, it looks like the attached
<img width="441" alt="screen shot 2018-02-12 at 8 13 37 am" src="https://user-images.githubusercontent.com/11475316/36098375-b682c112-0fcc-11e8-9a26-cc31f5d9fb4f.png">

Other metadata appears to be pretty badly in need of a tune up.

**Comment by mshukla1** [comment]
Host data has been cleaned up recently, which has taken care of such cases. 

We maintain list of synonyms for host names and have scripts to automatically clean them up periodically. We run it for every bi-monthly data release now. 

-Maulik
