### ISSUE TITLE
Circular view is not showing all of user uploaded file

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1885]
Go here:
https://www.patricbrc.org/view/Genome/520456.3#view_tab=circular
and then upload the attached file.  You will find that it only shows the genes on one contig, and on none of the others.  Very frustrating.
[BNWLFG2_S5 start stop for circular view.txt](https://github.com/PATRIC3/patric3_website/files/1721572/BNWLFG2_S5.start.stop.for.circular.view.txt)

**Comment by chmao1** [comment]
Need to handle the extra header line  in the user file.

**Comment by chmao1** [comment]
fixed and made a pull request.

**Comment by ARWattam** [comment]
Is this on alpha?  I tried it and am still getting the same error.

Rebecca

**Comment by chmao1** [comment]
Should be available in the next build

**Comment by hyoo** [comment]
@maovt please double check on production. we deployed yesterday.

**Comment by chmao1** [comment]
Tested and verified on production.
