### ISSUE TITLE
Genome annotation UI uses incorrect key for taxonomy id

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#189]
When I run the genome annotation app I'm not seeing the user-supplied tax ID getting passed in the parameters; I see it's getting passed as tax_id instead of taxonomy_id as is specified in the app spec:

$VAR2 = {
          'scientific_name' => 'bbuch new',
          'contigs' => '/olson@patricbrc.org/home/buchnera.fa',
          'domain' => 'Bacteria',
          'output_file' => 'new',
          'tax_id' => '2',
          'output_path' => '/olson@patricbrc.org/home/otuput',
          'code' => '11'
        };

**Comment by aswarren** [comment]
Fix for this has been committed. Should show up on beta soon.

**Comment by olsonanl** [comment]
Has the update happened? I am still seeing the problem this morning.

$VAR2 = {
          'scientific_name' => 'Buchnera aphidicola (Aphis gossypii)',
          'contigs' => '/olson@patricbrc.org/home/buchnera.fa',
          'domain' => 'Bacteria',
          'output_file' => 'x3',
          'tax_id' => '98785',
          'output_path' => '/olson@patricbrc.org/home/otuput',
          'code' => '11'
        };

**Comment by aswarren** [comment]
Strange. Is your page refreshed/cached cleared?

Here is what I am getting as the final JSON being generated from the UI side.

![image](https://cloud.githubusercontent.com/assets/229173/7866437/6d29a0d6-053d-11e5-8b6b-cb3cacff1ec8.png)

**Comment by aswarren** [comment]
Looks like i didn't scour out the tax_id but taxonomy_id is there now too.

**Comment by olsonanl** [comment]
Looks like a reload fixed it. Thanks.


On May 28, 2015, at 12:28 PM, Andrew Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


Strange. Is your page refreshed/cached cleared?

Here is what I am getting as the final JSON being generated from the UI side.

[image]<https://cloud.githubusercontent.com/assets/229173/7866437/6d29a0d6-053d-11e5-8b6b-cb3cacff1ec8.png>
