### ISSUE TITLE
download dialog: need error checking

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1894]
![image](https://user-images.githubusercontent.com/1236467/36499806-045853b0-1708-11e8-8d01-8810624af40c.png)

To go
https://www.patricbrc.org/view/Taxonomy/570#view_tab=genomes

select one -> download button on green bar,

No option has selected. Submit, cause error

![image](https://user-images.githubusercontent.com/1236467/36499888-38562570-1708-11e8-8fc9-4b6e6d7794bd.png)

We should add check mechanism to prevent this. At least one field should be selected.

**Comment by dawenx** [comment]
this is fixed and PR submitted.

**Comment by dawenx** [comment]
I verified this fix on alpha. close the ticket.
