### ISSUE TITLE
compare regions: drawing region not big enough

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1895]
If I have a compare regions  and request the full 50 genomes, the drawing canvas is not set to be large enough to render them.

For example. fig|662755.4.peg.1546. Choose 50 genomes to display; the underlying service is telling me it found the full 50 but the display truncates at 15:

![screen shot 2018-02-22 at 11 51 19 am](https://user-images.githubusercontent.com/2152226/36555117-ba96eb78-17c6-11e8-99c8-59528ccb8613.png)

**Comment by hyoo** [comment]
Ah,, this was fixed but for some reason, the fix was sleeping on my local repo. 
https://github.com/PATRIC3/p3_web/commit/b13c98ff30024e0c6d48281ce6910f692a3a20c3

I just merged it. Will update when i deploy to alpha.

**Comment by hyoo** [comment]
deployed on alpha

https://alpha.patricbrc.org/view/Feature/fig|662755.4.peg.1546#view_tab=compareRegionViewer

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/1236467/36560844-9073e6b4-17d7-11e8-8ec9-60e3ef8eef92.png">

**Comment by olsonanl** [comment]
Cool. And I see you have hooked up the doubleclick handler - excellent!
