### ISSUE TITLE
RNA-Seq job: system reports file not present

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#1897]
job id: 56c6ce09-f509-4b2c-a696-36b98a73705a
From the stdout there is a report that the alignment worked and the resulting sam was present:

$VAR3 = bless( {
                 'DIRNAME' => '/scratch/tmp/l3DBYSjf4c',
                 'REALNAME' => '/disks/tmp/l3DBYSjf4c',
                 'CLEANUP' => 1,
                 'LAUNCHPID' => 11180
               }, 'File::Temp::Dir' );
/scratch/tmp/l3DBYSjf4c/Rockhopper
total 101486536
-rw-r--r--. 1 iris iris 12625691386 Feb  4 15:34 merged_HFS35-RCtrl-1-SD0-RNA.sam

But then from the stderr when trying to run samtools we get:
stderr:
[E::hts_open_format] fail to open file '/scratch/tmp/l3DBYSjf4c/Rockhopper/merged_HFS35-RCtrl-1-SD0-RNA.sam'
[bam_sort_core] fail to open '/scratch/tmp/l3DBYSjf4c/Rockhopper/merged_HFS35-RCtrl-1-SD0-RNA.sam': No such file or directory

**Comment by olsonanl** [comment]
What we don't know is if that file was there when samtools ran as we don't have timestamps. Is this a repeatable problem? 

There are tmp cleaners on that system but for the p3 space they clear data that is 10 days old.
