### ISSUE TITLE
Genome report pdf vs. html

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1898]
To get around the pdf versus html issue for the genome report, is it possible to render the initial version in "print-friendly" html?  If so, the user can print to pdf.

**Comment by nconrad** [comment]
So, that is basically how it currently works.  :)

First html is produced, and then headless chrome (Pupeteer) is used to convert that to a pdf.    The resulting pdf will look identical to a user hitting the 'print to pdf' button-- it's just being done programmatically.  

Here's an example of the html output: https://nconrad.github.io/demo/46170.310/genome-report.html
[I'm going to remove this demo url at some point]
