### ISSUE TITLE
Circular genome viewer: add specialty genes tracks

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1899]
Add specialty genes tracks to the circular genome viewer. This will also be included in the genome report.

**Comment by mshukla1** [comment]
Chunhong, the your recent circular viewer enhancements are now deployed on alpha and it looks GREAT!! 

One small issue, foreground color selector is missing for the non-CDS features. Hence, there is no way to display them. Please see the attached screenshot. 

<img width="336" alt="screen shot 2018-03-11 at 8 51 57 am" src="https://user-images.githubusercontent.com/1236463/37254292-ea72d500-2509-11e8-812c-7c82b9266203.png">

**Comment by mshukla1** [comment]
Few more suggestions on the order of the tracks: 

CDS - fwd
CDS - rev
Non-CDS features
AMR genes 
VF genes
Transporters
Drug targets

Human homologs - remove => not predicted any more 
Essential genes - remove => sparse, available only for reference and rep genomes

Please also check the range for GC content and GC skew plots, which seem to be -1 to +1. 
However, I believe the values for both are always 0-1. So if you adjust them, the plots will 
look better.

**Comment by chmao1** [comment]
1. The color palette was disabled for Non-CDS features, because multiple colors (not a single) were used for different types of Non-CDS features. We could change it to use a single color for all Non-CDS features.

2. I can remove the tracks for Human homologs and Essential genes tracks

3. The range for GC content is 0 to 1 and for GC skew plots is -1 to +1.

**Comment by chmao1** [comment]
The feature is available on alpha
