### ISSUE TITLE
DATA!!!!  Multiple TBArc genomes with different versions

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#190]
For the Uganda genomes, all the genomes with TRUG as a strain name (ex TRUG0001) are actually an early version of the final genome, which has a strain name that begins with UT (ex UT0001).  Both those genomes currently exist in PATRIC, but the last one with the UT is the best and final.  We need to get rid of all the TRUG versions.

**Comment by mshukla1** [comment]
There are 105 genomes in total for which we have multiple versions present in PATRIC. We will try to clean them up before the August release. Out of 105, 75 are Mtb genomes.

**Comment by mshukla1** [comment]
Redundant version of the Mtb genomes have been removed from the database.
