### ISSUE TITLE
Charts missing axis labels on genome overview

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#1902]
(See "Genomic Features" and Speciality Genes")

![image](https://user-images.githubusercontent.com/1194246/37310215-378090c8-2611-11e8-8f1b-fa6febbdac6e.png)

**Comment by JoshuaVSherman** [comment]
https://patricbrc.org/view/Genome/520456.3
i'm assuming he means the units on the x-axis for protein features and Specialty Genes, but I think those are just a simple count of how many there are?

**Comment by JoshuaVSherman** [comment]
My confusion with this UI is that the label for each chart is above the chart and there is no separation between charts so it is not easy to tell which chart goes with which heading. So just move the heading closer to the chart that matches it, and put more spaces in between each chart  or a separation of some sort.

**Comment by JoshuaVSherman** [comment]
https://github.com/PATRIC3/p3_web/pull/706
