### ISSUE TITLE
File upload: upload button not visible

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1904]
Please reduce the size of the select file or drag here area so that the cancel and start upload buttons are visible in the window by default without requiring scrolling. 

-Maulik

<img width="826" alt="screen shot 2018-03-14 at 10 38 02 am" src="https://user-images.githubusercontent.com/1236463/37412990-025120de-2774-11e8-8714-4520f1fffbc6.png">

**Comment by dawenx** [comment]
duplicate issue as #1810

**Comment by dawenx** [comment]
close this issue since the duplicate one, i.e., #1810, was closed.
