### ISSUE TITLE
Command line programs do not exist

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1905]
There is no p3-mkdir 
I copied this straight from the online tutorial, so this is bad.

![image](https://user-images.githubusercontent.com/7661533/37413262-a55906c0-2774-11e8-9d32-9ad3beff43c7.png)

**Comment by JoshuaVSherman** [comment]
Bruce Parrello works on CLI

**Comment by olsonanl** [comment]
p3-mkdir is now in the release.
