### ISSUE TITLE
OK button not visible on screen when zoomed in.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1906]
When people have their window zoomed in, they can't see the  OK button when they are uploading.  I just had a user on a winndows computer that had to go in and change the resolution.  This made his computer shut down to do the channge, and then he had to upload it all over againn.  Just so he could see the OK button.  Maybe we should move that button up.  I have had trouble with that myself

**Comment by mshukla1** [comment]
@ARWattam is this upload to workspace or upload / file selection from the service? 

Can you add a screenshot just to be clear?

**Comment by dawenx** [comment]
duplicate issue as #1810

**Comment by ARWattam** [comment]
Its on upload.  Here is my screenshot showing it.  I am not allowed to
scroll down and click on OK, or whatever it is.

Rebecca

**Comment by dawenx** [comment]
close this issue since the duplicate one, i.e., #1810, was closed.
