### ISSUE TITLE
Surface-ipad-firefox does not load jobs page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1908]
We are seeing a weird error.  Someone has a Surface ipad and is trying to see her jobs page.  Clicks and clicks on it, and nothing appears.  never seen that before.  When changed to Chrome, she could see the jobs page.  Only Firefox.

**Comment by hyoo** [comment]
if possible, can we have info,

- is it Surface notebook (Microsoft) or Apple iPad?
- what is the version of firefox?
- what is the error message in console (broswer -> developer console), if exists ?

**Comment by chris-c-thomas** [comment]
I'm confused by this issue. Is this a Surface (MS Windows) or an iPad (iOS) tablet? 

I'm inclined to close this if it's an iPad as #1917 encompasses iOS as a whole not playing nice with PATRIC...

**Comment by chris-c-thomas** [comment]
@nconrad then again you had a Win10 tablet at the workshop today having a few issues? Should possibly have two tickets for each OS.

**Comment by chris-c-thomas** [comment]
As I read this again it makes me think it is a Surface Windows Machine. Chrome and Firefox are different on Windows where on an iOS device they would actually be about the same (WebKit as the base aka Safari). 

I'm closing this and opening a specific Win10 Tablet issues ticket.
