### ISSUE TITLE
Genome/Taxon Overview: Genomic Feature Summary: View more feature types doesn't work

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#191]
...when clicked on view more feature types, get the message: 

Genomic Feature Summary
Data is not available now. Please try again later.

-Maulik

**Comment by hyoo** [comment]
It was failed due to other issue (faceting on string_ci was not working on solr 5), which is fixed now. And this seems working back.

**Comment by mshukla1** [comment]
Checked. working.
