### ISSUE TITLE
Binning

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1910]
You should be able to submit more than one set of paired end reads for a metagenomic binning job, just like for a regular assembly job.

![image](https://user-images.githubusercontent.com/7661533/37428750-3a8c6a72-279b-11e8-9671-2932ebea38fe.png)

**Comment by dawenx** [comment]
I'm not the one who worked on the initial UI, but I can work on it if we choose to support it. Before I do anything on this, does the back-end service support multiple pairs of reads? @olsonanl

**Comment by olsonanl** [comment]
The current metagenome spades does not accept multiple read sets. 

Bruce has done this by concatenating them, but that seems fraught if you ask me. I'd like to understand exactly spades --meta doesn't accept more than one pair.

**Comment by dawenx** [comment]
close this ticket for now. will re-open it later if this is supported by the back-end.
