### ISSUE TITLE
this is a bad one - AMR classifiers on plasmids

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1912]
Here is an example of a plasmid that went through the adaboost classifiers when you integrated the plasmid data. Note the declaration of "susceptible".    This tool is trained on whole genome data, so the assumptions have been violated.   Ciprofloxacin, for instance,  is a mutation in the gyrA gene (which is encoded on the chromosome).  

I am beginning to think that the classifiers should be taken down if they aren't going to be used correctly.  I am also beginning to think that they should be taken down if they can't be adequately distinguished from true laboratory derived phenotypic data.

![image](https://user-images.githubusercontent.com/7661533/37458586-78f4045a-2813-11e8-9787-b90e5d897e56.png)

**Comment by mshukla1** [comment]
Loading of the plasmids is just revealing the problem that was always there. 

Classifiers are part of the default PATRIC annotation pipeline. Everything that is submitted 
to the pipeline, goes through it, regardless of whether it is complete genome, near complete
genome, a partial genome, a plasmid, or a phage or a metagenome derived bin…..whether it is 
public or private user supplied genome. Specially, we have no control over what users submit. 

I don’t think we have ever mentioned this assumption in the tutorial, FAQ or in any of the workshops, 
i..e. telling users that AMR works only for near complete genomes (and what we mean by that) and 
if your genome is not near complete, how would you interpret the AMR results. 

If this is serious problem, I think the assumption should be checked for before invoking AMR classifiers,
check for the genome length and completeness using QC parameters and run the AMR classifiers only 
if the genome passes QC. 

Regarding, distinguishing the predictions from panel evidence, would it be sufficient if we add another column
called “Evidence” with two values, Experimental or Computational?….or I am open to whatever you suggest. 

-Maulik

**Comment by jimdavis1** [comment]
I suggest that a "plasmid" not be considered "genome" anywhere in patric  because its not a genome.  
This problem is also showing up when in the search.  I was just looking at a genome that got counted 6 times.  Maybe we need to start thinking about having "bacterial genomes" "plasmids" "phage" "viruses' etc.

Regarding annotation, we have the same problem when you annotate phage.  It goes into the generic anonotation service pipeline, and all the overlapping gene calls get mowed down by the overlap resolution.  Same goes for the all of the assumptions regarding gene callers. Should all of these modules be changed to accommodate phage? No.  I think we should take some time to think about the correct pipelines for these elements before we make them public.

**Comment by mshukla1** [comment]
I agree, we need to think more carefully about the full support for plasmids and phage. 

However, in the mean while, at the very least, we need to add some information in the FAQS/Tutorials 
about how to interpret AMR results on non-complete genomes. 

-Maulik

**Comment by rkenyon** [comment]
Jim triage comment:  Highest.  In my eyes this might be the worst "bug" I have ever encountered and it is still not fixed.  This is a flagrant misuse of the AMR classifiers.  These plasmid annotations were performed based on the assumption that they are complete genomes, which is not true.  In essence, we are packaging and distributing an incorrect and misleading prediction to an unsuspecting user.  It is particularly bad for our reputations. 

The solution:  Don't do AMR classification on plasmids unless we build a special tool for it. 

Plasmids should also not be considered genomes in the database. Phage and plasmids require a separate designation in SOLR.

**Comment by mshukla1** [comment]
I have removed AMR phenotype data for all public plasmid genomes.

We need to fix it in the annotation pipeline to prevent inappropriate use of AMR classifiers. 

@jimdavis1 , you still need to come up with specific conditions under which AMR classifiers will not be run on a genome and work with @olsonanl to get them implemented in the annotation service. 

** The sooner you define the exact criteria for when to run AMR classifiers and when not, the sooner it will get fixed in the annotation service.

**Comment by olsonanl** [comment]
I have modified the pipeline to no longer call amr classifiers on any genome where all contigs are noted as having a replicon_type of plasmid. At this point this is as close as we can get to detecting plasmids.

**Comment by mshukla1** [comment]
This is useful for the public genomes or when user submits properly formatted genbank files. 

However, it doesn’t address the issue if user uploads just plasmid sequence as contigs or uploads 
partial/incomplete genome (which is significantly smaller than those used in the training).

Jim, I wanted you to be aware of it. If you think it is not sufficient, you should specify additional criteria 
for when to run classifiers and when not. 

-Maulik
