### ISSUE TITLE
presentation of amr data

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1913]
This presentation of the AMR phenotype is not informative.

![image](https://user-images.githubusercontent.com/7661533/37459210-60c59b58-2815-11e8-9b32-ca8b701614aa.png)

**Comment by nconrad** [comment]
@jimdavis1 / @mshukla1  I could use some help on what should be changed?   I know there is there is the AMR table on the overview page...

![image](https://user-images.githubusercontent.com/1194246/37482974-8f9665a0-2853-11e8-9e98-fd7032d83abb.png)

**Comment by jimdavis1** [comment]
I think that the predictions should exist on a separate page or link.  But The thing I am complaining about here is the "Antimicrobial phenotype: Resistant Susceptible"

**Comment by jimdavis1** [comment]
I think it should say that this is "mixed", its just odd.

**Comment by mshukla1** [comment]
"Antimicrobial phenotype: Resistant Susceptible” predates the more elaborate AMR phenotype 
tables available now. I agree that it is confusing and not much useful. We can change it as part of the 
current metadata overhaul. 

Two possible options: 

1. In the overall genome metadata, just indicate whether the genome has AMR phenotype data available or not. 
Or what level of evidence we have. i.e. 

AMR phenotypes = yes / no
AMR phenotypes = experimental and/or computational

2. In addition to above field, add two additional fields AMR_phenotype_resistant and 
AMR_phenotype_susceptiblae, each will be multi value field, which will contain list of antibiotics. i.e. 

AMR_phenotype_resistant: amikacin, …..
AMR phenotype_susceptible: vancomycin,…

One problem with 2 is that people may still get confused about whether the phenotypes are experimental 
or computational, specially when we have both. 

Please share your thoughts. 

-Maulik
