### ISSUE TITLE
issue with blast

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1914]
I can search within plamids with BLASTN but not BLASTP??

![image](https://user-images.githubusercontent.com/7661533/37460286-c3b4ec66-2818-11e8-9377-1c2379678b90.png)

![image](https://user-images.githubusercontent.com/7661533/37460293-cf992d94-2818-11e8-99f7-b096d44edaa1.png)

**Comment by hyoo** [comment]
@mshukla1 can we make plasmid protein database?

**Comment by mshukla1** [comment]
I have added new blast databases for plasmid genes, proteins and contig sequences. 

-Maulik
