### ISSUE TITLE
Proteome comparison: changes similar to circular viewer

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1919]
Chunhong, 

The proteome comparison circular view looks very fragmented when too many contigs in the reference genome chosen. Can you please apply the changes you made to the circular genome browser to this viewer as well, i.e. remove label for position 0 for every contig and reduce the gap between the contigs. 

Thanks. 

-Maulik

**Comment by mshukla1** [comment]
<img width="663" alt="screen shot 2018-03-16 at 7 32 17 am" src="https://user-images.githubusercontent.com/1236463/37520748-46d501ca-28ec-11e8-9554-376eb52ad06f.png">

**Comment by mshukla1** [comment]
I also noticed that this viewer also shows contig numbers, which gets crowded when many small contigs. I think it is unnecessary and can be removed. 

-Maulik

**Comment by chmao1** [comment]
This was implemented differently. Fangfang knows more about this.

**Comment by chmao1** [comment]
I'll look into this and try to fix it.

**Comment by chmao1** [comment]
@olsonanl Hi Bob, I just made a pull request to app_service. Could you review the code and merge and include it in the alpha build? I'll do some testing after you're done. Thanks.

**Comment by chmao1** [comment]
@mshukla1 Maulik, I think I fixed it. It's now in production. Please test it and let me know whether the fix satisfies your request.
