### ISSUE TITLE
Columns dropdown from column headers on genome list table has problems - Chrome only?

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#192]
If am on a genome list page - e.g. 
https://www.beta.patricbrc.org/portal/portal/patric/GenomeList?cType=taxon&cId=909768&dataSource=&displayMode=&pk=&kw=#
And I want to change the columns that I see and I try to use the functionality in the column headers (sort ascending / sort descending / columns) to do that the column list will appear, but will instantly disappear if I move my mouse over to the least of columns to try and check one
beta.patricbrc.org
Chrome only?   I couldn't duplicate the problem on Safari or Firefox

**Comment by hyoo** [comment]
I haven't seen this before. I suspect recent version of chrome may introduce this bug. 
However, you still can use toolbar button (Show/Hide).

And I remember, at some point, this menu bar disappears after checking one box. It wasn't like that.

**Comment by mshukla1** [comment]
Harry, I also see the same problem. I don't think it is critical for the June release, but we need to solve it soon after that.

**Comment by hyoo** [comment]
This starts working for me from this morning. I have Chrome Version 43.0.2357.124 (64-bit).

**Comment by rwill1** [comment]
It's now working OK for me in Chrome also.  Same version as Harry, except .130
