### ISSUE TITLE
doc.patric searches missing some return pages

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1920]
For instance, searching "p3-ls" (a CLI command) does not return a hit to http://docs.patricbrc.org/cli_tutorial/cli_services.html however searching "assemble" does. Both terms are in the user guide.  Suspicion is that it is a parsing error due to the "-" in the search term.  

To test, Googling "p3-ls site:docs.patricbrc.org" _does_ work.

**Comment by chris-c-thomas** [comment]
Sphinx Doc search tool may not be very sophisticated. @hyoo had mentioned possibly replacing it with Google, etc.

http://www.sphinx-doc.org/en/1.6.4/web/searchadapters.html

**Comment by hyoo** [comment]
check this one.
https://p3.theseed.org/p3_pages/

I have replaced the search form to connect to google search. I think this works better.

**Comment by chris-c-thomas** [comment]
@hyoo is this the route we want to go? 

Prod docs.patricbric.org still uses internal Sphinx search. 

That version above does use Google search but may confuse users? I do agree it's more accurate BUT it's not immediately accurate. If we add a new docs page I believe it may take a day or two to be indexed by Google's SEO crawlers.

**Comment by hyoo** [comment]
https://github.com/PATRIC3/p3_docs/commit/8cd61d504d289894c741f0b23bf424a9bac6d163

I am replacing search box with google search.
