### ISSUE TITLE
Patric_alpha layout comment

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#1928]
attached

![patric_alpha_layout](https://user-images.githubusercontent.com/20665963/37989521-419a7f9c-31c9-11e8-86fe-7e2564b9ff36.png)

**Comment by dmachi** [comment]
Something looks strange on your view.  Those headers are completely different:

**Comment by Sveta-user** [comment]
Hmmm.. Strange...  I was using Crome on this computer below.  Now on FireFox it does look different, you are right!  But what is some users will access Patric via Crome..?

<img width="571" alt="screen shot 2018-03-27 at 2 32 10 pm" src="https://user-images.githubusercontent.com/20665963/37990378-bd1c86cc-31cb-11e8-961e-1d5399ceb502.png">

**Comment by hyoo** [comment]
this is an artifact due to the css changes on homepage. If you connect to alpha (and refresh if it exists), you will not see the broken header.
