### ISSUE TITLE
Command line tutorials "@patricbc.org" 

### ISSUE THREAD

**Issue by Tinyman392** [PATRIC3/patric3_website#1929]
All of the command line tutorials tell the user to use /PatricUser@patricbc.org/ to access their directories, shouldn't it be patricbrc.org (I haven't had luck using patricbc.org).  

<img width="707" alt="screen shot 2018-03-28 at 1 18 38 pm" src="https://user-images.githubusercontent.com/5612784/38048850-38c183de-328c-11e8-8494-5c826927e40e.png">

**Comment by mshukla1** [comment]
I just checked the doc site and tutorials. It seems it has already been corrected.
