### ISSUE TITLE
Annotation app stuck with bad taxon

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#193]
I have seen this get stuck a couple times where I give the app a valid taxon ID and it says it is not valid:

![screen shot 2015-05-29 at 12 10 25 pm](https://cloud.githubusercontent.com/assets/2152226/7888118/c8366e00-05fb-11e5-8264-eaca1bff7216.png)

**Comment by olsonanl** [comment]
Seeing this in the dev console. I also don't have dropdowns loaded for the genome name and taxon id.

Can we make this disable attempts at validation if the dropdown data is missing?

[Log] Val:  load 1 ExternalCheckVal:  load 1
[Error] ReferenceError: Can't find variable: text
	_setDisplayedValueAttr (undefined, line 183)
	set
	_setBlurValue
	_onBlur
	l (dojo.js, line 69)
	_onBlur
	l (dojo.js, line 69)
	_onBlur
	l (dojo.js, line 69)
	_onBlur
	_setStack
	_onTouchNode
	_onFocusNode
	(anonymous function)
	focus ([native code], line 0)
	focus
	(anonymous function)
	map (dojo.js, line 62)
	validate
	(anonymous function) (dojo.js, line 57)
[Log] ExternalCheck:  empty
[Log] Val:  load 1 ExternalCheckVal:  load 1
[Log] ExternalCheck:  empty
[Log] Val:  load 1 ExternalCheckVal:  load 1

**Comment by olsonanl** [comment]
I continue to see this on my firefox that has freshly had caches cleared. 

Cannot submit any annotations at this point !

**Comment by dmachi** [comment]
I think this is fixed now, can you please try again and see if the interactions are better for you now?  Reopen this issue if it isn't.

**Comment by olsonanl** [comment]
I'm seeing exactly the same behavior, and the same "text is not defined" error on the console.

**Comment by olsonanl** [comment]
This was with Firefox on mac with caches flushed before a reload of the site.

**Comment by dmachi** [comment]
Hmm, you are testing on beta, right?   When you enter a tax id, does the dropdown show the taxon names alongside the taxon ids?  The text not defined error came from the fact that it wasn't automatically selecting the first item in the list if you didn't specifically select one on your own.  It is working for me in both chrome and firefox.  I know you said you cleared cache, but it doesn't seem like the cache was cleared (btw, I will have a change up soon so that clearing cache won't be necessary)

**Comment by olsonanl** [comment]
I’m starting with the genome name; I select contigs file, then type “43255” into the genome name to match the Clostridium strain I’m running. I click on the name that filled out, and I get “43255” in the name, cursor moves to tax id field which is empty and red.

—bob

On Jun 4, 2015, at 9:30 AM, Dustin Machi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm, you are testing on beta, right? When you enter a tax id, does the dropdown show the taxon names alongside the taxon ids? The text not defined error came from the fact that it wasn't automatically selecting the first item in the list if you didn't specifically select one on your own. It is working for me in both chrome and firefox. I know you said you cleared cache, but it doesn't seem like the cache was cleared (btw, I will have a change up soon so that clearing cache won't be necessary)

**Comment by dmachi** [comment]
I just ran through this same test you described in firefox and chrome.  I enter 43255 into the organism name, select Peptoclostridium difficile ATCC 43255 from the dropdown, and then it fills in 499175 in the taxid with no errors.  The only box remaining red is the output name at the bottom. Note that I'm not trying to discount what you've said, i'm just not seeing that same behavior on beta currently.   

Can you confirm that when you type into the tax_id selector, you see both IDs and names in the dropdown?

**Comment by olsonanl** [comment]
And I’m seeing the same behavior in firefox and chrome with caches flushed. See

http://youtu.be/xnEPSSOf9ME

If these things are relying on a large amount of data preloaded into the browser, then that might be a difference between running here at ANL and running locally at PATRIC.

If you have your MCS account, it might be interesting to run a socks proxy over ssh from your place to ANL, and fire up the browser pointing at the proxy to get the timing difference. There is also a tool available for the mac that emulates a slower / higher latency connection.

—bob

On Jun 4, 2015, at 9:39 AM, Dustin Machi <notifications@github.com<mailto:notifications@github.com>> wrote:


I just ran through this same test you described in firefox and chrome. I enter 43255 into the organism name, select Peptoclostridium difficile ATCC 43255 from the dropdown, and then it fills in 499175 in the taxid with no errors. The only box remaining red is the output name at the bottom. Note that I'm not trying to discount what you've said, i'm just not seeing that same behavior on beta currently.

Can you confirm that when you type into the tax_id selector, you see both IDs and names in the dropdown?

**Comment by olsonanl** [comment]
I don't get stuff filled in when I type in the tax ID.

https://youtu.be/2IKricnLv-A

**Comment by dmachi** [comment]
Hi bob, can you try this again please?

**Comment by olsonanl** [comment]
It’s getting there - it works erratically at first but then (apparently after everything loads) it seems to do the right thing.

There’s no indication however that the completion is not working because the data is not yet loaded.

On Jun 4, 2015, at 12:20 PM, Dustin Machi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi bob, can you try this again please?

**Comment by dmachi** [comment]
I noticed that there was a problem on one of the api nodes.  It was working when happened to hit one node, but not the other. I've restarted it so you can try again, and I'm working on figuring out why it was stalling in the first place.

Dustin

**Comment by olsonanl** [comment]
Ah - much better.

On Jun 4, 2015, at 1:04 PM, Dustin Machi <notifications@github.com<mailto:notifications@github.com>> wrote:

I noticed that there was a problem on one of the api nodes. It was working when happened to hit one node, but not the other. I've restarted it so you can try again, and I'm working on figuring out why it was stalling in the first place.

Dustin

**Comment by olsonanl** [comment]
There is still a problem when entering tax ID. If I reload the page to a clean interface, then start typing 499175 it turn the 4 into a 6  and changes the other digits as well.if I type it really quickly it does the right thing.

On Jun 4, 2015, at 1:04 PM, Dustin Machi <notifications@github.com<mailto:notifications@github.com>> wrote:

I noticed that there was a problem on one of the api nodes. It was working when happened to hit one node, but not the other. I've restarted it so you can try again, and I'm working on figuring out why it was stalling in the first place.

Dustin

**Comment by dmachi** [comment]
Yah, this is harder one to solve because solr has those IDs as numbers instead of strings.  I was in the middle of IMing Maulik to see if we could have those as strings like the rest of the IDs in at least the taxonomy core.  In the mean time I'll adjust the delay that happens between when you stop typing and it starts searching so that you have more time to get a full id out before it searches.

**Comment by dmachi** [comment]
I got rid of the list of other IDs for auto completion, so it only shows things with an exact match.
