### ISSUE TITLE
New home page: global search field at the top is missing for other pages

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1930]
When using the global search at the new home page, the search result page and the pages linked from the search result miss the global search field at the top.

![image](https://user-images.githubusercontent.com/6361802/38153040-b19f801e-3438-11e8-9822-e39fec85dc95.png)

![image](https://user-images.githubusercontent.com/6361802/38153067-d30abe76-3438-11e8-9ec3-10f2dcaec7e0.png)

**Comment by chris-c-thomas** [comment]
What's interesting is this only happens after you've visited the new home page and go to another static page.

If you go to the current homepage and then any of these pages the global search bar is still there. 

If you go to the the new homepage, then another page, and refresh the page the global search will reappear.

**Comment by chris-c-thomas** [comment]
Fixed in PR: https://github.com/PATRIC3/p3_web/pull/743

**Comment by chris-c-thomas** [comment]
Fixed on Alpha
