### ISSUE TITLE
Back button in browser works unexpectedly for Subsystems tab

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1932]
When I am on the Subsystems tab https://patricbrc.org/view/Taxonomy/234#view_tab=subsystems on the Subsystems Overview submenu item and I click on one of the other submenu items (Subsystems, Genes) and then click "Back" in the browser, it goes back to some previous page, not the Subsystems Overview.  Is this by design?

**Comment by hyoo** [comment]
yes, currently we're not recording subtabs in url, so, browser thinks sub tabs are within one page. This is same behavior on protein families and pathways.
