### ISSUE TITLE
RNAseq won't render output in safari

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1937]
When I try to look at the output in the workspace browser I can doubleclick on the job result, the URL changes, but the result is not shown.

Path is https://www.patricbrc.org/workspace/olson@patricbrc.org/home/test/rnaseq_baumanii_1505311

```
[Error] TypeError: Not enough arguments
	replaceState
	go (/js/3.5.8/p3/layer/core.js:195:274)
	(anonymous function) (/js/3.5.8/p3/layer/core.js:95:112)
	f (dojo.js:97:127)
	emit (dojo.js:88:366)
	emit (dojo.js:89:449)
	emit (dojo.js:95:285)
	publish (dojo.js:94:444)
	(anonymous function) (/js/3.5.8/p3/layer/core.js:624:328)
	(anonymous function) (dojo.js:58:507)
	dispatchEvent
	emit (dojo.js:89:428)
	(anonymous function) (/js/3.5.8/p3/layer/core.js:641:88)
	(anonymous function) (dojo.js:88:141)
```

**Comment by olsonanl** [comment]
It worked in chrome; it also worked in Safari if I brought the page up and then reloaded.

**Comment by aswarren** [comment]
It seems that the job object was simply empty in this case.
For the link provided the job object is empty in chrome and safari.
This works if the job object is populated:
https://www.patricbrc.org/workspace/public/PATRIC@patricbrc.org/PATRIC%20Workshop/RNA-Seq/Acinetobacter_AMR_treatments
