### ISSUE TITLE
Missing sequences in Feature Summary

### ISSUE THREAD

**Issue by mandywil** [PATRIC3/patric3_website#1938]
In both production and Alpha, when viewing the Feature Summary, there is no sequence displayed in the Sequences section.  This seems to be in DataItemFormatter.js, and the sequence seems to render properly everywhere else I saw this widget used.

Thanks!
![image](https://user-images.githubusercontent.com/276697/38281333-23db8bea-3778-11e8-8e4c-747ab5265211.png)

**Comment by dmachi** [comment]
This is because of the fairly recent change that removed those sequence strings for these queries inside of the Genome Browser, so the data isn’t there for it to render.

**Comment by mandywil** [comment]
I'm sorry -- are you saying this is a "feature", then? :)

I am just asking because I am working on another issue, and this is not a "problem" but it leads to unexpected behavior.

**Comment by dmachi** [comment]
No, not saying it is a feature.  I was just explaining why it is not rendering any sequence there. There are three ways to solve this:

	1.  Change the Genome Browser queries to include this data as it used to.  This was originally change for performance reasons (to reduce the amount of data transferred). Not sure it is a great idea.
	2. Retrieve the full record only when necessary before sending data on to DataItemFormatter.  This is challenging because it is down in the guts of Browse
	3. When the sequence is missing, change things so that there is a link to the fasta viewer page (i.e., /view/FASTA/dna/?in(feature_id,(PATRIC.1211817.3.CCAT010000002.CDS.3464.4063.fwd))  

I’d think #3 is what needs to be done here.

**Comment by mshukla1** [comment]
This was an intended change to address the genome browser performance issue. 

If I remember correctly, earlier, we were fetching NA and AA sequences for all features,
just to show first N characters (10-20) of the sequences in the feature overview pop up, and then 
provide link to view the whole sequence, which was going back to database to fetch the 
sequence again. So, high performance cost, for not much value. Hence, we decided to 
remove them. 

CC’ing Harry as he is the one who actually made the change. 

-Maulik
