### ISSUE TITLE
RNA-Seq job failed 

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#194]
The RNA-Seq job was submitted but returned with "failed" status.

Please see error message below:

/scratch/tmp/j0lKWrf93w
GET WS => /scratch/tmp/j0lKWrf93w wt_7H9_1_DR1_R1.fastq /cmao@patricbrc.org/home/wt_7H9_1_DR1_R1.fastq
Error retrieving https://p3.theseed.org/services/shock_api/node/a8726955-a1bc-4fa7-aa59-a68f6ed6a1dd: {"status":400,"data":null,"error":["Node has no file"]}
GET WS => /scratch/tmp/j0lKWrf93w wt_hypoxia_1_DR13_R1.fastq /cmao@patricbrc.org/home/wt_hypoxia_1_DR13_R1.fastq
Error retrieving https://p3.theseed.org/services/shock_api/node/a02b77e2-7de1-474d-8f89-ec8fc53cf34e: {"status":400,"data":null,"error":["Node has no file"]}
curl https://www.beta.patricbrc.org/api/genome_sequence/?eq(genome_id,83331.22)&select(accession,genome_name,description,length,sequence)&sort(+accession)&http_accept=application/json&limit(25000)
curl https://www.beta.patricbrc.org/api/genome_feature/?and(eq(genome_id,83331.22),eq(annotation,PATRIC),eq(feature_type,CDS))&select(accession,start,end,strand,aa_length,patric_id,protein_id,gene,refseq_locus_tag,figfam_id,product)&sort(+accession,+start,+end)&limit(25000)&http_accept=application/json
curl https://www.beta.patricbrc.org/api/genome_feature/?and(eq(genome_id,83331.22),eq(annotation,PATRIC),or(eq(feature_type,tRNA),eq(feature_type,rRNA)))&select(accession,start,end,strand,na_length,patric_id,protein_id,gene,refseq_locus_tag,figfam_id,product)&sort(+accession,+start,+end)&limit(25000)&http_accept=application/json
$exps = $VAR1 = [
          [
            [
              '/scratch/tmp/j0lKWrf93w/wt_7H9_1_DR1_R1.fastq'
            ]
          ],
          [
            [
              '/scratch/tmp/j0lKWrf93w/wt_hypoxia_1_DR13_R1.fastq'
            ]
          ]
        ];
cmd = java -Xmx1200m -cp /home/fangfang/programs/Rockhopper.jar Rockhopper -o /scratch/tmp/j0lKWrf93w/Rockhopper -g /scratch/tmp/j0lKWrf93w/83331.22/NC_002755 -L 7H9,hypoxia /scratch/tmp/j0lKWrf93w/wt_7H9_1_DR1_R1.fastq /scratch/tmp/j0lKWrf93w/wt_hypoxia_1_DR13_R1.fastq

Error running cmd=java -Xmx1200m -cp /home/fangfang/programs/Rockhopper.jar Rockhopper -o /scratch/tmp/j0lKWrf93w/Rockhopper -g /scratch/tmp/j0lKWrf93w/83331.22/NC_002755 -L 7H9,hypoxia /scratch/tmp/j0lKWrf93w/wt_7H9_1_DR1_R1.fastq /scratch/tmp/j0lKWrf93w/wt_hypoxia_1_DR13_R1.fastq, stdout:

Aligning sequencing reads from file:	wt_7H9_1_DR1_R1.fastq

stderr:
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at SamOps.isTextFile(SamOps.java:823)
	at SamOps.(SamOps.java:93)
	at Peregrine.getReadsInputFileType(Peregrine.java:796)
	at Peregrine.(Peregrine.java:168)
	at Rockhopper.(Rockhopper.java:136)
	at Rockhopper.main(Rockhopper.java:908)

**Comment by mshukla1** [comment]
Andrew, please verify the issue is addressed and close the ticket.
