### ISSUE TITLE
I can't close the Venn Diagram

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1940]
I just created a Venn Diagram, and there is now way to close the pop-up window.  I have to kill the tab to get rid of it.
![screen shot 2018-04-04 at 6 21 57 pm](https://user-images.githubusercontent.com/11475316/38337894-3ac19a3a-3835-11e8-8f4b-f903c3a5fbf6.png)

**Comment by JoshuaVSherman** [comment]
@ARWattam need your help please to reproduce the issue, thanks
