### ISSUE TITLE
Genome has PGFams, but no PLFams

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1941]
This genome: Microbacteriaceae bacterium strain strain Alg239_V181

Found here: 
https://www.patricbrc.org/view/Genome/1873462.3#view_tab=features

Looks like this
<img width="1118" alt="screen shot 2018-04-05 at 7 43 15 am" src="https://user-images.githubusercontent.com/11475316/38364068-0e3e20d0-38a5-11e8-8da6-72ce773572d1.png">

**Comment by mshukla1** [comment]
The PLFams are computed for only those genomes that belong to a genus with more than five 
genomes at the time of constructuion of new protein families. 

This genome is part of the unclassified Microbacteriaceae, it does not have designated genus. 
Hence, it doesn’t have PLFams. 

-Maulik
