### ISSUE TITLE
GBK files need to be added back in

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1942]
Several users have requested the gbk file, and its needed for the variation service.  I have hope in my heart that it will once again be part of the PATRIC annotation process.  I hope that the image moves Maulik so deeply that the gbk file moves to the top of his list....
![screen shot 2018-04-05 at 9 31 05 am](https://user-images.githubusercontent.com/11475316/38368761-2a14e154-38b4-11e8-81b7-aec6f14ea80f.png)

**Comment by mshukla1** [comment]
I take this as a coded message: Give me gbk files or pack your bags! ;)

**Comment by olsonanl** [comment]
The variation service now generates genbank files where needed; does this address this concern?

**Comment by chmao1** [comment]
This is fixed and available on production. Please see issue #2065.

**Comment by ARWattam** [comment]
yes it does!
