### ISSUE TITLE
inconsistent job "running" colors

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#1943]
![image](https://user-images.githubusercontent.com/1194246/38379159-7c1a6512-38c5-11e8-924e-f09ea08fbb6c.png)

![image](https://user-images.githubusercontent.com/1194246/38379144-71aaadc6-38c5-11e8-9f59-995d0a1226df.png)

**Comment by hyoo** [comment]
this is visual illusion, due to the background color. I verified with color meter app in mac.
