### ISSUE TITLE
global search drill down not working on beta?

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#195]
If I search for Klebsiella pneumoniae UHKPC29 and it gets 17 genomes as a result.  If I click on either Genomes (17) in the left nav (Show Results in) or on the 17 after Genomes in the results panel, it doesn't go anywhere.   (tried on safari, firefox and chrome)

**Comment by olsonanl** [comment]
See if it works for you after you click on a genus grouping in the Organisms tab. I was seeing similar behavior today.

On May 29, 2015, at 4:29 PM, rwill1 <notifications@github.com<mailto:notifications@github.com>> wrote:


If I search for Klebsiella pneumoniae UHKPC29 and it gets 17 genomes as a result. If I click on either Genomes (17) in the left nav (Show Results in) or on the 17 after Genomes in the results panel, it doesn't go anywhere. (tried on safari, firefox and chrome)

**Comment by hyoo** [comment]
This is fixed and available on beta. Thanks for reporting.

**Comment by mshukla1** [comment]
checked, working now.
