### ISSUE TITLE
Workspace object selector: selecting the folder does not work, only selecting the workspace and single click on folder works, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [PATRIC3/patric3_website#1954]
This will fail if you double-clicked the folder:
![image.png](https://images.zenhubusercontent.com/56be23566caf56c9d38c78ce/aeecae56-c24c-4bd8-af0c-b13ba57cb518)

**Comment by nconrad** [comment]
I think i need some more info.  I'm not sure what you mean by fail?   Double clicking was the original implementation of how to navigate folders (along with clicking on the icons)...

**Comment by nconrad** [comment]
duplicate/fixed.  see https://github.com/PATRIC3/patric3_website/issues/2030
