### ISSUE TITLE
Please fix the positioning of these plus and minus buttons for the grid

### ISSUE THREAD

**Issue by JoshuaVSherman** [PATRIC3/patric3_website#1955]
![image](https://user-images.githubusercontent.com/13340120/38616287-7dd0efc0-3d61-11e8-99b3-f5372281eb43.png)

**Comment by nconrad** [comment]
I'm not sure who did this or why?

**Comment by nconrad** [comment]
This was fortunately addressed by @chris-c-thomas in https://github.com/PATRIC3/p3_web/commit/1e94db31724a661ae20a333c367e5a44c9d0c301
