### ISSUE TITLE
Collapsable top table in job view

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#1956]
highlighted blue here.
It would be helpful if the top div was resizable to maximize usable screen space.

![image](https://user-images.githubusercontent.com/229173/38687284-5173423c-3e44-11e8-9b04-483df715c438.png)

**Comment by JoshuaVSherman** [comment]
@aswarren These divs are position absolute, so whoever works on it will need to edit the workspace widget to add a toggle, and the report div needs to be set as height 800px, top 0px

to toggle it back it would be 
height: 544px
top: 238px

this is the div where the report gets placed
class="dijitContentPane FileViewer-child FileViewer-dijitContentPane FileViewerPane dijitAlignCenter"
id="dijit_layout_ContentPane_6"

**Comment by mshukla1** [comment]
#2156 described the same issue. Closing this one.
