### ISSUE TITLE
Sequence list: link from sequence id doesn't work

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1957]
Pointed by one of our collaborators. 

The link from sequence id does not work. It goes to NCBI where the sequence does not exist. 

ACTION: 
- Add link from accession to NCBI, when accession doesn't look like sequence id. 
- Link sequence id to feature list, filtered for showing features only from that sequence, or to genome browser showing that sequence. 

https://patricbrc.org/view/Genome/72407.639#view_tab=sequences

![image](https://user-images.githubusercontent.com/1236463/38769335-d92d07d4-3fc6-11e8-8797-c216c4739bef.png)

**Comment by chmao1** [comment]
Fixed and available in production.
