### ISSUE TITLE
DATA - AMR genomes missing at PATRIC

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#196]
The following are genomes that were in AMR metadata and as far as I can tell are available at NCBI but are missing at PATRIC.

We will need to make sure that the metadata is included when the genomes are included .   I think the metadata for all the genomes is in the May release curated folder, but if we don't do a data release, we will need to move them again

- [x] **Pseudomonas aeruginosa BWHPSA005** - at GenBank PRJNA219866  AXQX01 
- [x] **Enterobacter cloacae BWH 29** - at GenBank - w.ncbi.nlm.nih.gov/nuccore/AYIR00000000.1/

see email from Becky subj:Re: AMR genomes and metadata from December release - action needed date: 22-Apr 4:44 PM (not the one earlier in the day) if you want more context

WARNING - in this next set there are genomes of duplicate names and other assorted problems 

GENOMES THAT NEED TO BE ADDED TO PATRIC From GSCID_BROAD_Acinetobacter
- [x] **Acinetobacter baumannii CIP 70.34T** - at GenBank, needs to be added to PATRIC http://www.ncbi.nlm.nih.gov/nuccore/APRG00000000.1/
- [x] Acinetobacter calcoaceticus CIP 81.8 - name needs to be changed in metadata to **Acinetobacter calcoaceticus DSM 30006 = CIP 81.8** and accession number must be added to metadata file -  at GenBank as APQI http://www.ncbi.nlm.nih.gov/nuccore/APQI00000000.1/ probably not at PATRIC because there is another genome of the same name -
- [x] Acinetobacter lwoffii CIP 64.10 - name needs to be changed in metadata to **Acinetobacter lwoffii NCTC 5866 = CIP 64.10**  and accession number must be added to metadata  http://www.ncbi.nlm.nih.gov/nuccore/APQS00000000.1/ not at PATRIC probably because of dup name
- [x] Acinetobacter parvus CIP108168 - name needs to be changed in metadata to **Acinetobacter parvus DSM 16617 = CIP 108168**, and accession added to metadata http://www.ncbi.nlm.nih.gov/nuccore/APOM00000000.1/ not at PATRIC because there is another genome of the same name
- [x] Acinetobacter radioresistens CIP 103788 - name needs to be changed in metadata to - -
- [x] **Acinetobacter radioresistens DSM 6976 = NBRC 102413 = CIP 103788** and accession added to metadata http://www.ncbi.nlm.nih.gov/nuccore/APQF00000000.1/ - not at PATRIC HOWEVER, ADDITIONAL MAULIK ACTION there appear to be 2 genomes w/ this name at PATRIC - both w/ "GenBank Accession" BAGY- but different assembly accessions and different BioSample Accessions and Different BioProjects Accessions and different Contigs but same completion date .....
- [x] Acinetobacter tjernbergiae CIP 107465 - name needs to be changed in metadata to --**Acinetobacter tjernbergiae DSM 14971 = CIP 107465** AYEV, you know the drill by now
- [x] Acinetobacter ursingii CIP 107286 - name / accession needs to be changed in metadata to **Acinetobacter ursingii DSM 16037 = CIP 107286**  APQA,
- [x] Acinetobacter venetianus CIP 110063 - name / accession in metadata **Acinetobacter venetianus RAG-1 = CIP 110063 **- APPO

GENOMES THAT NEED TO BE ADDED TO PATRIC From MRSA CLEAR

- [x] **Staphylococcus aureus M13403** - At NCBI http://www.ncbi.nlm.nih.gov/nuccore/JDHW00000000.1/, not sure why it's not at PATRIC - MRSA Clear - Broad
- [x] **Staphylococcus aureus T74141** - at NCBI http://www.ncbi.nlm.nih.gov/nuccore/JEUD00000000.1/ - not sure why it's not at PATRIC - MRSA CLEAR
- [x] **Staphylococcus aureus T86792** - at NCBI http://www.ncbi.nlm.nih.gov/nuccore/JFRX00000000.1/ - not sure why it's not at PATRIC - MRSA CLEAR
- [x]  **Staphylococcus aureus W31947** - at NCBI http://www.ncbi.nlm.nih.gov/nuccore/JDFZ00000000.1/ - not sure why not at PATRIC MRSA CLEAR
- [x] **Staphylococcus aureus W73649** - at NCBI http://www.ncbi.nlm.nih.gov/nuccore/JEVR00000000.1/ - not sure why not at PATRIC MRSA CLEAR

For more context see email from me subject:remainder of the December unmapped metadata action items including Action Items  date: 30-Apr

**Comment by mshukla1** [comment]
Will try to get them added in August release.

**Comment by rwill1** [comment]
From Maulik's 8-July email Re: NIAID-NCBI-PATRIC call about Broad CRE data set

5 Genomes present in NCBI AMR spreadsheet, but not PATRIC
...

The following four genomes are not available in PATRIC yet. They will be added in the next release. 

SAMN02138663 Enterobacter cloacae BIDMC 33A
SAMN02356620 Enterobacter cloacae UCI 40
SAMN02581258 Escherichia coli UCI 52
SAMN02581260       Escherichia coli UCI 54

**Comment by mshukla1** [comment]
It seems the new data ingestion pipeline is working really well. 

All the genomes listed above are now present in PATRIC with related metadata.
