### ISSUE TITLE
Incorrect Routing

### ISSUE THREAD

**Issue by chris-c-thomas** [PATRIC3/patric3_website#1964]
There are currently many routes that basically lead to nothing. No 404s or redirects, etc. @dmachi I believe you originally set up the routes and views for P3_web according to @hyoo ? I understand the way you went about things but wanted to loop you in. 

For instance if you go to https://www.patricbrc.org/search you'll come up with this:

![screenshot-2018-4-25 patric](https://user-images.githubusercontent.com/22353987/39273055-607deaca-48a3-11e8-80f5-5b1dadfa5712.png)

To my knowledge this happens for:

- /content
- /remote
- /view
- /search
- /app
- /job
- /help
- /uploads

**Special Cases**
- /workspace
If you are logged in then the route works fine. If you are not logged in then it's like the screenshot.

- /users
If you attempt this route you'll be presented with a completely blank page (no Patric header, etc) and the words "respond with a resource"

- /login
If you are not logged in you will be presented with the login form (albeit very stretched since it normally loads in a pop up modal that has fixed width). If you ARE logged in then you get absolutely nothing. Just a complete blank page.

I understand some of these routes are probably necessary for URLs nested deeper down but typing these in shouldn't really be accessible or should at least present a message, go back button, 404, etc. 

Our 404 page is also not user friendly. Presents the error just fine but nothing for the user to go back to where they were or a nice message explaining the page doesn't exist.

**Comment by mshukla1** [comment]
If there is any action item here, please address it by May Release.

**Comment by chris-c-thomas** [comment]
Routes are correct. 404s and catch alls can be addressed elsewhere. Closing.
