### ISSUE TITLE
drop "" subsystem superclass from pie chart

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#1966]
Per @olsonanl and Veronika, we should remove the empty string superclass.

![image](https://user-images.githubusercontent.com/1194246/39383100-9f6e5676-4a2d-11e8-9e13-fe312879ba8c.png)

**Comment by hyoo** [comment]
this is a data problem.

**Comment by olsonanl** [comment]
Not really; the data is correct (empty classification means the subsystem does not have a clear classification) and Veronika does not want those rendered in the diagram.
