### ISSUE TITLE
Pubmed link is broken

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1967]
![image](https://user-images.githubusercontent.com/7661533/39430121-9282dfaa-4c52-11e8-9cda-706b962ac321.png)

**Comment by hyoo** [comment]
<img width="477" alt="image" src="https://user-images.githubusercontent.com/1236467/39779659-840dcc04-52cf-11e8-97c0-47c29f4a3877.png">

http://localhost:8983/solr/sp_gene/select?indent=on&q=feature_id:PATRIC.590.963.590.963.con.0007.CDS.67195.83880.fwd&wt=json

data is corrupted somehow.

@mshukla1 we need to double check the json object has right format.

**Comment by mshukla1** [comment]
Cleaned up all the sp gene records with erroneous pubmed ids.
