### ISSUE TITLE
User requests link to SRA from genome landing pages when such accessions exist

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1970]
Here's what the user said:
Hi! I was searching complete genomes of E. coli
https://www.patricbrc.org/view/Taxonomy/2#view_tab=genomes&filter=and(eq(genome_status,Complete),and(keyword(Escherichia),keyword(coli)))
and it resulted in 462 results. I am interested in those results with SRA
entries. I see that when clicked and the details are shown they are
displayed. However, when I export the data to excel, there is no SRA column
in the spreadsheet. Is it possible to add it? Thanks!

link to JIRA 1499

**Comment by dawenx** [comment]
so the user wants "SRA Accession" in the download? If so, @hyoo can you add it to p3_api/blob/master/middleware/ExtractCustomFields.js assuming that's OK for you and @mshukla1 
(I checked with @dmachi on this already)

I also found out "sra_accession" is missing in the column list and i will add it.

**Comment by hyoo** [comment]
Note: verify the list with schema.
