### ISSUE TITLE
Comprehensive genome analysis failure

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1971]
My job (89f13d9f-beed-4e60-8b98-88190a0db378) says it completed, but when I click on it, I get a workspace object not found.  When I look at the error report from the job page, it says:
Bio::P3::Workspace::WorkspaceClientExt::download_json: failed to load /ARWattam@patricbrc.org/home/Test folder/.Mycobacterium leprae ancient metagenome/assembly: Object not found!

**Comment by olsonanl** [comment]
Duplicate of #1973
