### ISSUE TITLE
Assembly associated with comprehensive genome analysis not viewable

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1972]
The assembly from the comprehensive genome announcement says it completed, but when I click on it, it says that the object is not found.  Job ID 0fb9be71-54fa-471b-847e-57676ae9ae86

**Comment by mshukla1** [comment]
I believe this problem existed in the early days of CAS release, that AWE failed to report failed jobs as such. So the job was shown as completed, but no job result folder existed. 

@olsonanl can you confirm this is fixed?

**Comment by olsonanl** [comment]
yes, that is correct. That is a job that AWE marked as successful when it actually failed, and that reporting has been corrected.
