### ISSUE TITLE
download svg from KEGG pathway view not working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1975]
I got proteins from the Protein Family Sorter that were sepcific to Buchnera genomes isolated from a particular aphid (green peach aphid), looked at the pathways, and then loaded the folate biosynthesis pathway.  I tried to download an svg of that pathway, and got the error you can see in the attached screenshot
![screen shot 2018-05-04 at 3 46 20 pm](https://user-images.githubusercontent.com/11475316/39649123-a95c87d6-4fb2-11e8-8b82-4625b99dcdb7.png)

**Comment by hyoo** [comment]
https://alpha.patricbrc.org/view/PathwayMap/?annotation=PATRIC&genome_id=83332.12&genome_ids=83332.12&pathway_id=00010

![image](https://user-images.githubusercontent.com/1236467/43010876-57614b88-8c07-11e8-90d1-d54b1c836f73.png)

**Comment by rkenyon** [comment]
I tried it and it worked for me on alpha.
