### ISSUE TITLE
object selector double-click issue

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#1978]
The similar genome finder selector is buggy, particularly when reselecting. 

![image](https://user-images.githubusercontent.com/1194246/39719362-9e293852-51fe-11e8-8046-124a47f907d0.png)

To replicate:
1) select a fasta file from your workspace using the object browser
2) open object browser again.  
3) *quickly* double click a new contig
4) repeat #3
5) notice the new selection may or may not be selected.

It may be a race condition or issue with setting/getting state. Need to make sure object selectors are battle proof, because it's causing confusion and it's probably not the only selector.

Probably related to #1517 and  #1954.

**Comment by dawenx** [comment]
@nconrad this is very hard to reproduce (and I was not able to reproduce it), but I understand your concern. A question: do you see similar issue in other services? This is a very important question as I have below theory/guess:

I originally thought this must be a WorkspaceObjectSelector issue. But WorkspaceObjectSelector is used in pretty much all services, why did we only experience this here? To my surprise, the implementation of this service, along with 3 others (BLAST, CompartativePathway and ProteinFamily), is slightly different, i.e., we create a WorkspaceObjectSelector object in the js codes, in stead of setting data-dojo-type as "p3/widget/WorkspaceObjectSelector" in the template html. In theory, this is just different way of using WorkspaceObjectSelector. I'm a little bit confused... @hyoo and @dmachi do you have insight on this?

**Comment by dawenx** [comment]
OK, neal and I played with this for a while via Skype, it looks like we can reproduced it when using touchPad on the mac and the problem is: sometime double clicking does not select the new object. We were not able to reproduce it when I used a separate mouse.

**Comment by dawenx** [comment]
neal and i made progress on this and the 'fix' is relatively easy. neal will take care of it. :)

**Comment by nconrad** [comment]
fix is on alpha and see https://github.com/PATRIC3/patric3_website/issues/2030 for remaining work.
