### ISSUE TITLE
multiple accounts with cmd line

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#1983]
This is weird:
```
$ p3-whoami 
You are logged in as:
devuser2@patricbrc.org
$ p3-login --status
You are logged in as PATRIC user nconrad
$ p3-login --logout
Logged out of PATRIC.
$ p3-whoami 
You are logged in as:
devuser2@patricbrc.org
$ p3-login nconrad
Logged in with username nconrad@patricbrc.org
$ p3-whoami 
You are logged in as:
devuser2@patricbrc.org
```

**Comment by Tinyman392** [comment]
<img width="682" alt="screen shot 2018-05-09 at 10 23 30 am" src="https://user-images.githubusercontent.com/5612784/39825571-b054d2dc-5377-11e8-99ad-dae12b259f9c.png">

I've got a similar issue with it saying I'm not logged in when using p3-whoami

**Comment by olsonanl** [comment]
This is a too many cooks in the code problem. I need to do a purge of some of the older scripts.


________________________________

**Comment by olsonanl** [comment]
https://github.com/olsonanl/Workspace/commit/af1c6830504310604931cf93bc8413f3f3507bef removes the incorrect p3-whoami.

https://github.com/olsonanl/p3_auth/commit/d2c15a1b887c4ae3470964ae4037dd2fec59dbcf adds a corrected p3-whoami and the new p3-logout.
