### ISSUE TITLE
variation analysis viewer doesn't load vcf track

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1984]
![image](https://user-images.githubusercontent.com/1236467/39827309-39cb3e2a-537d-11e8-88ed-9fcb29b45517.png)

to reproduce

https://alpha.patricbrc.org/workspace/public/PATRIC@patricbrc.org/PATRIC%20Workshop/Variation/TMP-2

click "Browser" 

and check "SE1.var.vcf.gz"

**Comment by aswarren** [comment]
Fixed here https://github.com/PATRIC3/p3_web/pull/767 @hyoo
