### ISSUE TITLE
Subsystem chart presence/absence colors are the same

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1993]
<img width="1022" alt="screen shot 2018-05-18 at 11 55 36 am" src="https://user-images.githubusercontent.com/2152226/40247639-b0735a6e-5a92-11e8-9927-8fd846f22c32.png">

On a later run, I don't get a graphic for the presence/absence at all:

<img width="1349" alt="screen shot 2018-05-18 at 12 13 12 pm" src="https://user-images.githubusercontent.com/2152226/40248242-e6c18b98-5a94-11e8-8d90-4f30ebbd9559.png">

**Comment by mshukla1** [comment]
I think this was fixed a while back. We have different colors for genes in subsystems or not. 

<img width="1164" alt="Screen Shot 2019-04-08 at 4 04 51 PM" src="https://user-images.githubusercontent.com/1236463/55756865-29e37c00-5a18-11e9-9b28-d00021e41602.png">
