### ISSUE TITLE
User Account Settings no longer editable

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1994]
In the past, I believe a user could change their account settings such as username, password, email address, etc.  Now, when you are logged in and click on Account Settings, all that comes up is some static information in the top left of the page.

![screen shot 2018-05-18 at 2 20 11 pm](https://user-images.githubusercontent.com/3188570/40251200-a3143564-5aa6-11e8-8752-b8b7665443bf.png)

**Comment by hyoo** [comment]
this version is deprecated. New user service pages are integrated on p3_web and works as expected.
