### ISSUE TITLE
Error dialog hard to close

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1995]
This error dialog:

<img width="310" alt="screen shot 2018-05-21 at 12 36 38 pm" src="https://user-images.githubusercontent.com/2152226/40321128-aa80e35c-5cf3-11e8-9bf5-7feaae073f7b.png">

Appears to be unclosable. It is missing an explicit close button, and the "X" to close the dialog is obscured by text.

**Comment by dmachi** [comment]
CSS/Styling must be keeping this dialog from getting as wide as it needs to support the provided title.  The X is the explicit close button, so we’ll need to adjust the styling to make sure it doesn’t get obscured.  You can also just hit escape on any of the dialogs to close them (I do realize that isn’t an answer for users).

**Comment by olsonanl** [comment]
I'd argue that all dialogs should have an action button (here, "Close") since it may not be intuitive to hunt for the dim grey X.

**Comment by olsonanl** [comment]
Here's another example that's even harder to close.

<img width="328" alt="screen shot 2018-05-21 at 1 58 55 pm" src="https://user-images.githubusercontent.com/2152226/40324773-308fb33c-5cff-11e8-8ea5-89d9433e311c.png">

**Comment by hyoo** [comment]
can you give us an instruction how to reproduce this error?

**Comment by olsonanl** [comment]
Check out #1997 for an example.
