### ISSUE TITLE
Compare regions fatal error

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1997]
I'm trying to use compare regions on phages and am seeing this error dialog:

<img width="328" alt="screen shot 2018-05-21 at 1 58 55 pm" src="https://user-images.githubusercontent.com/2152226/40324798-449d7094-5cff-11e8-984a-b85a47f3aa88.png">

For example:

https://patricbrc.org/view/Feature/PATRIC.GCA_002592465.1.JQ740791.CDS.7079.9250.fwd#view_tab=compareRegionViewer

I don't get a backtrace that seems related, though I do see:

```
getText @ dojo.js.uncompressed.js:324
VM1223 remote:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at eval (core.js.uncompressed.js:5488)
/view/Genome/GCA_002592465.1#view_tab=features:1 Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at eval (core.js.uncompressed.js:5488)
```

Looking at the code related to these errors I saw the follow, where it appears JSON parse errors aren't trapped (though the code seems to assume the parser returns null sometimes and handles that).

```
      /* istanbul ignore next */
      on(window, 'message', function (msg) {
        // console.log('onMessage: ', msg);
        if (msg && msg.data === 'RemoteReady') {
          return;
        }
        msg = JSON.parse(msg.data);
        // console.log('Message From Remote: ', msg);
        if (msg && msg.topic) {
          Topic.publish(msg.topic, msg.payload);
        }
      }, '*');
```

**Comment by olsonanl** [comment]
This is apparently showing up on all genomes so is more critical to get chased down.

Here it is on a regular reference genome.

https://www.patricbrc.org/view/Feature/PATRIC.483179.4.NC_010103.CDS.6822.8462.rev#view_tab=compareRegionViewer

<img width="1362" alt="screen shot 2018-05-21 at 2 58 22 pm" src="https://user-images.githubusercontent.com/2152226/40327136-734d837c-5d07-11e8-9a4c-f6c324480858.png">

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/41926272-741c7f58-7934-11e8-9929-29ac621a3799.png)

it works for me. What am i missing?

**Comment by olsonanl** [comment]
Apparently something changed between then and now. Didn't you have some lint pass that resulted in True being used but not defined?

**Comment by hyoo** [comment]
The True issue was resolved. I deployed hot fix at that time. 
And yes, now the linter will check the undefined variable, so hopefully this type of mistake will not happen again.
