### ISSUE TITLE
Genomes missing a number of sequences

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2003]
The following genomes lack a number in the "Sequences" field

{"id_list":{"genome_id":["1496.2589","1496.2590","1496.2592","1496.2593","1496.2595","1496.2594","1496.2591","1496.2598","1496.2597","1496.2596","1496.2599","1496.2600","1496.2601","1496.2603","1496.2602","1496.2604","1496.2605","1496.2606","1496.2608","1496.2607","1496.2657","1496.2658","1496.2635","1496.2636","1496.2637","1496.2639","1496.2640","1496.2638","1496.2641","1496.2642","1496.2645","1496.2643","1496.2644","1496.2646","1496.2647","1496.2649","1496.2651","1496.2650","1496.2648","1496.2652","1496.2653","1496.2654","1496.2656","1496.2655","699035.42","1496.2609","1496.2610","1496.2611","1496.2613","1496.2614","1496.2616","1496.2615","1496.2612","1496.2617","1496.2618","1496.2619","1496.2620","1496.2622","1496.2621","1496.2623","1496.2624","1496.2625","1496.2626","1496.2627","1496.2628","1496.2629","1496.2630","1496.2633","1496.2631","1496.2632","1496.2634","1496.2659","1496.2660","1496.2661","1496.2662","1496.2530","1496.2531","1496.2533","1496.2532","1496.2534","1496.2535","1496.2536","1496.2554","1496.2556","1496.2542","1496.2544","1496.2543","1496.2545","1496.2555","1496.2557","1496.2560","1496.2559","1496.2562","1496.2564","1496.2563","1496.2566","1496.2561","1496.2565","1496.2567","1496.2568","1496.2537","1496.2538","1496.2539","1496.2540","1496.2546","1496.2547","1496.2548","1496.2550","1496.2549","1496.2551","1496.2552","1496.2553","1496.2541","1496.2571","1496.2581","1496.2578"]},"name":"weird_cdiffs"}

**Comment by mshukla1** [comment]
Because of the earlier complains about the confusion between contigs and sequences, we have decided to deprecate the sequence column and rather use contigs to show total number of contigs (including complete chromosomes and plasmids)  in a genome. 

We need to make sure that the tables on the website are showing contigs as the default column. 

Also, need to remove sequences from tables as well as overview pages.
