### ISSUE TITLE
Can we please please please please be allowed to copy data from tables?

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2004]
If you guys use the website frequently, this will annoy you.  Here is an example where I just wanted to copy the first few lines from my blast results to get genome names and some statistics.

Clicking the download button puts you many clicks away from from actually having something that you should have instantly. 

![image](https://user-images.githubusercontent.com/7661533/40921882-51b3dd86-67d6-11e8-86a8-c8a382d0d511.png)

**Comment by hyoo** [comment]
use COPY button.
![image](https://user-images.githubusercontent.com/1236467/41296508-afa41b8e-6e22-11e8-8da8-cc25d3990d9c.png)

![image](https://user-images.githubusercontent.com/1236467/41296546-c87521d0-6e22-11e8-9550-a7dc2ed1ce1c.png)


![image](https://user-images.githubusercontent.com/1236467/41296521-b83f7d10-6e22-11e8-8ca3-5d9564236b88.png)
