### ISSUE TITLE
search on protein family

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2009]
can we add protein family to the global search drop down?
![image](https://user-images.githubusercontent.com/7661533/41472394-f1782720-707b-11e8-82aa-3db078e6ff8d.png)

**Comment by chris-c-thomas** [comment]
Would this be the correct search results? Showing the protein families tab?

![gs](https://user-images.githubusercontent.com/22353987/41617169-621e302c-73c5-11e8-866b-3479759157e3.png)


![gs-protein-families-results](https://user-images.githubusercontent.com/22353987/41617173-656a6dcc-73c5-11e8-847c-28111fc3e4ed.png)

**Comment by hyoo** [comment]
search on protein family may mean, 

1.  search on protein family definition. your result will be a list of protein family id and family names, and you can link to all features within that protein family. 

2. search on features that match to one or list of protein family id(s).

3. search on genomes matches your keyword criteria and show protein family tab.

or something else. @jimdavis1 i saw same request multiple times. Would you clarify your need?

**Comment by hyoo** [comment]
Maulik and I discussed, and we're going to address this issue on PDP5, nov 2018 release. closing.
