### ISSUE TITLE
Comparative Pathway tool does not show private genome when group compared

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#201]
2 Ochrobactrum
40 Public Brucella
1 private Brucella
The tool showed all the genomes except the private Brucella genome

**Comment by hyoo** [comment]
This is due to the facet that genome annotation app does not assign genome_status, which will be filtered by the condition as below,

{!join from=genome_id to=genome_id fromIndex=genome}taxon_lineage_ids:131567 AND genome_status:(complete OR wgs)

**Comment by mshukla1** [comment]
I have updated missing genome_status for ~3000 genomes, including the newly annotated private genomes, and made necessary change in the parser so that it gets assigned to private genomes from now on. 

Pathways are shown for the private genomes and they work when private genomes are in group.
