### ISSUE TITLE
enhancement: add protein families to blast output table

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2011]
It would be good if we could see protein families here:
![image](https://user-images.githubusercontent.com/7661533/41476220-893dc7ae-7086-11e8-9a68-d8f9d5f72c44.png)

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/43010727-d60d996a-8c06-11e8-9fd5-5d05e505ac63.png)

![image](https://user-images.githubusercontent.com/1236467/43010745-e23f65e2-8c06-11e8-8999-719106fb8393.png)

**Comment by rkenyon** [comment]
When I tried it on alpha, I did not get the additional PATRIC Global or Local Family.  I used a common Mtb feature.
![screen shot 2018-07-20 at 11 41 28 am](https://user-images.githubusercontent.com/3188570/43011588-f9696320-8c11-11e8-8b7e-99731fdd2065.png)

**Comment by hyoo** [comment]
yes, because you searched for sequence, not gene/CDS. 

change your target database to ffn
