### ISSUE TITLE
Update workshops page

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#2016]
https://patricbrc.org/webpage/website/workshops.html

**Comment by rkenyon** [comment]
New ones to be added:

ASM Microbe 2018; Atlanta, GA; Jun-18, 43 participants
Argonne National Laboratory; Argonne, IL; May-18; 26 participants
Baylor Medical College; Houston, TX; Mar-18; 37 participants
University of California at San Diego; San Diego, CA; Jan-18; 30 participants
Argonne National Laboratory; Argonne, IL; Nov-17; 34 participants

**Comment by hyoo** [comment]
https://github.com/PATRIC3/p3_docs/blob/master/docroot/website/workshops.rst

**Comment by hyoo** [comment]
fyi, static pages are hosted in p3_docs,
https://github.com/PATRIC3/p3_docs/tree/master/docroot/website

and will be updated automatically.

**Comment by rkenyon** [comment]
Have updated the page in GitHub.  Will close ticket when it is (auto-)updated on the website.

**Comment by rkenyon** [comment]
Done
