### ISSUE TITLE
 Need SRA run accession on RNA-Seq

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2018]
We have this on assembly.  It would be good to have it on this service as we provide for Assembly, and I could see that our users would make use of it.

**Comment by mshukla1** [comment]
SRA accession is already supported in RNA-seq service now. Closing the ticket. 

<img width="366" alt="Screen Shot 2019-04-06 at 5 51 45 PM" src="https://user-images.githubusercontent.com/1236463/55676189-c2e98a00-5894-11e9-8760-df86aff42981.png">
