### ISSUE TITLE
Remove MOSAIK from Variation Service input form

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#2022]
This recipe keeps failing, so removing this option for now.  Also need to update the Tutorial and User Guide correspondingly.

**Comment by rkenyon** [comment]
Dawen will update the service input form, Ron will update the User Guide and Tutorial.

**Comment by dawenx** [comment]
The form has been updated and PR submitted.

**Comment by dawenx** [comment]
Ron, this fix is on alpha, feel free to update the user guide and tutorial.

**Comment by hyoo** [comment]
App deployed on alpha, and removed from p3_docs repo.

**Comment by dawenx** [comment]
verified this on production.
