### ISSUE TITLE
Genome Browser: displays features from multiple genomes

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#203]
I have annotated few private genomes, all using as as input genomesequence of Mtb H37Rv genome. 
So, all the genome versions have the same accession number. When I load the genome browser
for one of the private genomes, it shows data from all the genome versions, instead of the one I am 
currently looking it. 

It seems that it tries to get features using just the sequence accession, instead of genome id _ accession. 

See the attached screenshot. 

-Maulik
![screen shot 2015-06-02 at 3 17 43 pm](https://cloud.githubusercontent.com/assets/1236463/7944835/2af82488-093b-11e5-86a0-6907a78a1fb3.png)

**Comment by hyoo** [comment]
fixed and available on beta

**Comment by mshukla1** [comment]
verified, resolved.
