### ISSUE TITLE
Genome Browser: congratulates when it failes

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2032]
Genome browser failed to load for a genome because the genome sequences are missing (which is a data problem). 

However, instead of saying that it failed to load because of data problem, I get the following message!!!

<img width="1025" alt="screen shot 2018-07-13 at 11 35 25 am" src="https://user-images.githubusercontent.com/1236463/42703104-1d456734-8691-11e8-8597-ec2a364c58af.png">

**Comment by hyoo** [comment]
new message.
![image](https://user-images.githubusercontent.com/1236467/43010566-634d4fe2-8c06-11e8-951e-741a02fa9bc1.png)
