### ISSUE TITLE
searching on taxa doesn't work

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#2033]
https://patricbrc.org/view/TaxonList/?and(keyword(Pseudomonas),keyword(parafulva),keyword(DSM),keyword(%2217004%22))

or
https://patricbrc.org/view/TaxonList/?keyword(Pseudomonas)

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/43010478-357e6f2e-8c06-11e8-9e6f-676298f27838.png)

works on alpha now.

**Comment by rkenyon** [comment]
worked for me on alpha
![screen shot 2018-07-20 at 11 56 22 am](https://user-images.githubusercontent.com/3188570/43012312-ff194978-8c13-11e8-8f44-fc605795c1d5.png)
