### ISSUE TITLE
Fix broken links in AMR Phenotypes User Guide

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#2034]
https://docs.patricbrc.org//user_guides/organisms_taxon/amr_phenotypes.html

Broken links are 
  Antibiotics Data
  Antibiotic Resistance Data

Both of these will require generation of new user guides.

**Comment by rkenyon** [comment]
There are many additional broken links found by http://www.brokenlinkcheck.com/

**Comment by chris-c-thomas** [comment]
Yes there are quite a few being listed by that program. Would you like me to go through and update them?

**Comment by rkenyon** [comment]
I have a complete list and I'm starting to work on them.  Most should be very straightforward.  I am not fixing the ones in the News since they point to pages that are now obsolete.

**Comment by rkenyon** [comment]
Many reported broken links were in either old News items which reference obsolete items, or in the old User Guides.  Neither of these categories will be fixed.
The remaining have been fixed except for ones in the CLI Tutorial section.  These require some additional research back to the source material.  See #2040
