### ISSUE TITLE
reset button results in console error

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#2036]
In annotation app.  Maybe not critical, but should be fixed.

![image](https://user-images.githubusercontent.com/1194246/42970012-b841dade-8b6d-11e8-8851-eb42c8716e89.png)

![image](https://user-images.githubusercontent.com/1194246/42970320-9dabb860-8b6e-11e8-8955-286cd31987fc.png)

**Comment by nconrad** [comment]
Hey @dawenx, I'm assigning this to you because it may be related to https://github.com/PATRIC3/patric3_website/issues/2039

**Comment by dawenx** [comment]
yeah, this is related issue and i'm going to take care of it.

**Comment by hyoo** [comment]
this is fixed on alpha. thanks.
