### ISSUE TITLE
Keep list of webinars up-to-date

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2038]
We need to keep the page listing upcoming and past webinars up-to-date. 

https://docs.patricbrc.org//webinar/#upcoming-webinars

**Comment by chris-c-thomas** [comment]
https://github.com/PATRIC3/p3_docs/pull/53

Added the event for next month. Will continue to add events along with details such as date & time every time Rebecca let's me know.

**Comment by rkenyon** [comment]
We (Ron) will add as they are scheduled and update when recorded.  Closing the ticket.
