### ISSUE TITLE
prevent broken data api call from taxonomy ID selector

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#2039]
Taxonomy ID selector triggers broken query, for example, Annotation or Comprehensive Genome Analysis app,

![image](https://user-images.githubusercontent.com/1236467/43263982-72569a68-90aa-11e8-862c-fe9507e988af.png)

click drop down button,

![image](https://user-images.githubusercontent.com/1236467/43264007-837195be-90aa-11e8-86bb-0c82520a57bc.png)

![image](https://user-images.githubusercontent.com/1236467/43264030-93198076-90aa-11e8-84e7-84ea06bc030e.png)

**Comment by hyoo** [comment]
this is part of #1806

**Comment by dawenx** [comment]
i believe i have fixed it, PR submitted.

**Comment by hyoo** [comment]
confirmed on alpha.
