### ISSUE TITLE
Similar Genome Finder documentation

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#2041]
A better explanation of the advanced parameters in the help is needed in the i-box and on the help page. Specifically an explanation of the "distance","p-value" parameters.

**Comment by rkenyon** [comment]
I'll be glad to put them in tine document, but I would need someone to provide the explanations.

**Comment by aswarren** [comment]
The "Distance" parameter sets the maximum MASH distance to include in the similar genome finder results.
MASH distances are probabilistic estimates associated with p-values. The "p-value threshold" parameter sets the maximum allowable p-value associated with the MASH Jaccard estimate used in calculating the distance.

**Comment by rkenyon** [comment]
@aswarren please check out https://github.com/PATRIC3/p3_docs/blob/master/docroot/user_guides/services/similar_genome_finder_service.md to see if this is sufficient.

**Comment by rkenyon** [comment]
I'm assuming the updated text is sufficient.  Closing ticket.
