### ISSUE TITLE
Creating a feature group from the Protein Family Sorter with a specific PLF and 66 genomes returns mutliple PLFams and 146 genomes

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2057]
This is VERY FRUSTRATING!!!!  Everything appears to be broken in the Protein Family sorter and it is making my life miserable.  

I have 2 genome groups with private genomes.  As the filter box doesn't work, I had to page through the PFS table until I found PLF_1279_00002629.  I created a feature group of that across my 66 genomes.  But when I went to look at that group, here were the PLFs associated with it:

PLF_1279_00000541
PLF_1279_00002617
PLF_1279_00002629

So now I have to manually go in and manipulate the group....AGAIN!!!!!

**Comment by mshukla1** [comment]
I suspect you created went through paging, selected PLF_1279_00000541, created a group, then continued 
to next pages until you found PLF_1279_00002617, created another group, and then selected PLF_1279_00002629, 
and created third group….without each time without deselecting previous choice. That is why each of your 
feature groups contain previous selection as well. 

Unless you reload page or manually deselect, the selections you have made are kept, including those you made 
on previous page while using pagination in the tables. 

Hope this explains. 

-Maulik

**Comment by ARWattam** [comment]
That makes sense. I believe you are right. Thanks for your help.

Rebecca
