### ISSUE TITLE
Filter on top of feature page not isolating PLFams correctly

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2058]
Somebody can log into my account and look at the genome group PB and RB Yeaman.  Click on that group, go to the group view, and then click on the Feature tab.  In the filter box at the top of that tap put in PLF_1279_00000541 and hit return.  The table filters itself to show TWO PLFs that don't even look similar.  Why is this happening?
<img width="1124" alt="screen shot 2018-07-28 at 2 39 21 pm" src="https://user-images.githubusercontent.com/11475316/43359687-6f4851ba-9274-11e8-961f-238406c77ccb.png">

**Comment by mshukla1** [comment]
Use double quotes: “PLF_1279_00000541”

without it, you will get all there records that have PLF AND 1279 AND 00000541
