### ISSUE TITLE
New CGA tutorial is missing from Tutorials page

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#2059]
https://docs.patricbrc.org//tutorial/

![screen shot 2018-07-30 at 10 50 43 am](https://user-images.githubusercontent.com/3188570/43404836-731684ec-93e6-11e8-8457-8daa53b98c09.png)

**Comment by chris-c-thomas** [comment]
![screen shot 2018-07-30 at 9 59 47 am](https://user-images.githubusercontent.com/22353987/43405476-8822b1e6-93df-11e8-9568-e50eb157a3e9.png)

Fixed on my local dev. Merging with Master and should update on production soon. Will close out when I see it there.
