### ISSUE TITLE
Job numbers are incorrect on jobs page

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2063]
I actually have zero running and 2 failed. 

![image](https://user-images.githubusercontent.com/7661533/43653654-504882a0-970e-11e8-80b2-5931dbfe5bd2.png)

**Comment by nconrad** [comment]
Thanks for reporting.  Marking this as duplicate of https://github.com/PATRIC3/patric3_website/issues/2060.
