### ISSUE TITLE
Protein Family Sorter: always displays only 10 genomes in the table

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#207]
Protein family sorter seems to be having few bugs. 

- For both PFS tab and tool, regardless of how many genomes I choose, for all the max genome count displayed in the table is 10. 

- In some cases, when I select a protein family from the table and try to generate multiple sequence alignment, the number of proteins in the table and passed to MSA do not match. The same if I click on the family description and go to the member list. 

See the attached screen shots. 

-Maulik

![screen shot 2015-06-02 at 3 26 16 pm](https://cloud.githubusercontent.com/assets/1236463/7958426/327f332c-09bd-11e5-8e0a-289d86c94a43.png)

![screen shot 2015-06-03 at 6 54 19 am](https://cloud.githubusercontent.com/assets/1236463/7958439/63f1949a-09bd-11e5-9b7b-9aaf8698fd0b.png)

**Comment by hyoo** [comment]
fixed and available on beta.

**Comment by mshukla1** [comment]
As we discussed in the evening, there are still inconsistencies in the number of members on the PFS page and the member list when drilled down. Changing the status back.

**Comment by hyoo** [comment]
fixed the genome count. It was due to the dataAPI limit for 25000 rows for return.

**Comment by hyoo** [comment]
Still have an issue using keyword search
Inosine-5'-monophosphate dehydrogenase (EC 1.1.1.205)

**Comment by mshukla1** [comment]
The problem was that proteins maped to the same figfam have two versions of product names, with and without EC number.
Inosine-5'-monophosphate dehydrogenase (EC 1.1.1.205)
Inosine-5'-monophosphate dehydrogenase

When searched for "Inosine-5'-monophosphate dehydrogenase (EC 1.1.1.205)”, it finds all features matching the keyword and groups them by figfam id. However, when clicked on a figfam, it gets all the features that match the figfam id, which ends up returning more results than before. 

This is not  a website bug, but artifact of having two function names for the same figfam. This issue will be resolved when we recall the functions of all proteins in PATRIC.
