### ISSUE TITLE
improvement:  add publication to the AMR data tab

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2072]
I think it is important to have the source publication (when possible) on the AMR tab becuase it shows the experiment where the phenotype was characterized.

![image](https://user-images.githubusercontent.com/7661533/44113464-c54f5eda-9fcd-11e8-855f-c6d6ac1e04e1.png)

**Comment by mshukla1** [comment]
Currently, PMIDs are attached only to genomes as part of the genome metadata. They are not attached directly to the AMR phenotype data. 

I will look into it and add PMIDs to the AMR table, if possible. 

-Maulik

**Comment by mshukla1** [comment]
PMIDs have been added to most of the AMR data gathered from publications. 

There are a small number of records missing PMIDs, which will be added soon. 

<img width="1362" alt="Screen Shot 2019-04-07 at 10 12 22 AM" src="https://user-images.githubusercontent.com/1236463/55685580-a8a7be80-591d-11e9-8321-46e846598908.png">
