### ISSUE TITLE
Add keywords to all tutorials and user guides

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2074]
From the discussion Today on how to increase the search-ability on google and increase user traffic: 

Add relevant keywords /  synonyms / tags on tutorials and user guides that we think our users might use to find them in google search.

**Comment by chris-c-thomas** [comment]
This should be about done, will double check and dynamically/statically add what's needed.

**Comment by mshukla1** [comment]
I just checked. Most of the services now have relevant keywords. Closing the ticket.
