### ISSUE TITLE
Organisms: Add list of priority pathogens

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2075]
In order to increase the visibility in google searches and drive traffic: 

Currently, the organism page below directly jumps to organism tabs etc, without describing what organisms we have, what we offer, etc. 

https://docs.patricbrc.org/user_guides/organisms_tab.html

- [ ] Add list of priority pathogens on the following page, with some description. 

- [ ] Add description for how to search for taxon or genome. 

<img width="537" alt="screen shot 2018-08-14 at 2 46 57 pm" src="https://user-images.githubusercontent.com/1236463/44114502-fa68d0a8-9fd0-11e8-96bd-684990fc25d5.png">

**Comment by rkenyon** [comment]
Added information on organisms and how to access them at the multiple levels.
