### ISSUE TITLE
Title and meta tags on all website pages

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2076]
In order to increase the visibility in google searches and drive traffic:

Please make sure we have proper title and meta tags on all web pages: 

- [ ] taxon / genome and gene level pages
- [ ] services 
- [ ] tools

**Comment by chris-c-thomas** [comment]
This should be about done, will double check and dynamically/statically add what's needed.

**Comment by chris-c-thomas** [comment]
Front matter is being addressed elsewhere.
