### ISSUE TITLE
Variation Service: add url links to the PATRIC features in the html file 

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#2077]
Link the Gene ID column to the PATRIC feature page.

![image](https://user-images.githubusercontent.com/6361802/44157520-a9cf6700-a080-11e8-8eb8-f8b965ebcd6f.png)

**Comment by chmao1** [comment]
Fixed and available on production

**Comment by mshukla1** [comment]
Awesome! Thanks, Chunhong!

I submitted a variation job Today and verified it has 
- var.snpEff.vcf file in the results 
- snpEff type and snpEff impact in the SNP table
- and gene ids are linked to corresponding gene pages. 

-Maulik
