### ISSUE TITLE
metagenomic binning service doesn't work

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2078]
I am attempting to launch a binning job from a set of single-end reads.  The reads are located in the public workspace under PATRIC_Workshop/Metagenomic_Binning/ICU

Why can't I submit with single end reads?  Is this the problem?  I thought this did the assembly for me, is it asking for contigs?

![image](https://user-images.githubusercontent.com/7661533/44162874-3ed55e80-a087-11e8-86c7-8b02d9663be7.png)

**Comment by dawenx** [comment]
As discussed in Skype channel, the backend currently does not support single end reads.
