### ISSUE TITLE
Pathway summary: selected genes are not correctly highlighted in blue

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#208]
I selected one genome, H37Rv sanger, went to the pathway tab, selected checkbox for TCA cycle, 
ran pathway summary. The pathway summary table correctly shows that all the annotated genes 
in the TCA cycle are selected. However, when I click on the pathway link, the map has only subset EC numbers highlighted in blue, instead of all of them. 

Screen shot attached. 

This issue links now combines other similar issues:  #168 #139 #23

**Comment by mshukla1** [comment]
![screen shot 2015-06-03 at 8 25 20 am](https://cloud.githubusercontent.com/assets/1236463/7959931/c2179cba-09ca-11e5-920a-da9210f9b8fe.png)

**Comment by hyoo** [comment]
fixed and available on beta.

**Comment by mshukla1** [comment]
Checked, working now.
