### ISSUE TITLE
subsystem tab exists but has no data

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2081]
![image](https://user-images.githubusercontent.com/7661533/44223358-06985380-a14d-11e8-88ba-ad7aa671bd19.png)

**Comment by jimdavis1** [comment]
As an update to this, after about 5 min it populated and looked like this:  Note the yellow print.
![image](https://user-images.githubusercontent.com/7661533/44223438-7a7e3000-a13c-11e8-9995-76952d35abe7.png)

**Comment by mshukla1** [comment]
Assuming you were looking at MG1655 reference genome, I was able to load the subsystem 
overview and table. I checked the database as well and the data looks fine. 

I noticed Yesterday that sometimes it took a while for the page to load ( about a minute) though.

**Comment by mshukla1** [comment]
Refresh the page and see if it load then. 

We do need visual indicators on all pages to tell when a page is waiting for data and when the request 
has timed out. 

-Maulik
