### ISSUE TITLE
Similar Genome Finder Advanced Parameters

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#2087]
ATCC and Midwestern workshops: in both cases people have had confusion as to why they are not getting results from similar genome finder. This can be improved by the following changes:

1. Not hiding the Advanced parameters by default (they don't seem very "Advanced" and most people would want to know what they are searching)
2.  The default should be all public genomes. (Ref&Rep is the special filter that is actually the advanced case)

**Comment by aswarren** [comment]
@jimdavis1 supports this message.
Also see these other tickets where this has been a problem:
https://github.com/PATRIC3/patric3_website/issues/2080
https://github.com/PATRIC3/patric3_website/issues/1962

**Comment by mshukla1** [comment]
FWIW, We encountered the same problem with similar genome finder last week during phage workshop. 

I agree to both the suggestions by Andrew.

**Comment by dawenx** [comment]
i will work on this.

**Comment by dawenx** [comment]
I have changed the submission UI, PR submitted.

**Comment by dawenx** [comment]
The fix is on alpha now.

**Comment by dawenx** [comment]
this is on production, please verify and close, thanks @aswarren @mshukla1
