### ISSUE TITLE
FIlter "More" failure.

### ISSUE THREAD

**Issue by disz** [PATRIC3/patric3_website#209]
When I click "more" on a filter item and then click one of the choices, it closes the more, and I have to click "more" to click another choice; R&R. It should stay open until I click "less".

**Comment by mshukla1** [comment]
...not critical for the release, but we need to look into it later, as part of usability improvements.

**Comment by hyoo** [comment]
Would you please direct me the page? Which tool are you at?

**Comment by mshukla1** [comment]
Harry, this is about the genome list page. Click more on a facet, then select one of the facet values, it goes back to less, which is annoying, specially if you want to select multiple values for the same attribute.

**Comment by hyoo** [comment]
We have new website with better capability handing facet items.
