### ISSUE TITLE
bug: filters are missing on taxon list

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2090]
I search for "Buchnera" under "Taxa" from the drop down in the search bar.  It gives me buchnera, but I can't filter for public or private.

![image](https://user-images.githubusercontent.com/7661533/44268545-a35aff80-a1e6-11e8-8d5c-b49ab15982db.png)

**Comment by jimdavis1** [comment]
https://www.patricbrc.org/view/TaxonList/?keyword(Buchnera)

**Comment by mshukla1** [comment]
It is a list of taxon ids and names from the taxonomy dictionary. Hence it’s all public. 

You may have public or private genomes under a given taxon level, which is not shown in this table. It summarizes only public genomes for a give. Taxon level based on pre computed counts.

**Comment by mshukla1** [comment]
Currently, there are no filters/facets available for taxon list. 

We should add the following filters: taxon_rank and division

**Comment by mshukla1** [comment]
The filters have been added. 

<img width="1363" alt="Screen Shot 2019-04-08 at 3 12 26 PM" src="https://user-images.githubusercontent.com/1236463/55753787-c99d0c00-5a10-11e9-8a4b-3ed43021c602.png">
