### ISSUE TITLE
Suggest to change BLAST DB names

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2091]
As a biologist, it is not clear to me what is meant by "Transcriptomics Genomes proteins"

We also have an upper case lower case issue with the names, which is no big deal but kind of ugly.

![image](https://user-images.githubusercontent.com/7661533/44268913-ccc85b00-a1e7-11e8-873c-b2625f441000.png)

**Comment by jimdavis1** [comment]
Actually as i am mulling this over, The first one "Reference or Representative Genome proteins (faa)" is also weird.  It should just be "Reference and Representative Genomes", because the user has selected that it is blastp -search protein database.   So a proposed cleanup would be:

1. Reference and representative genomes 
2. I still don't know what this one is
3. plasmids
4. phages
5. search within selected genome
6. search within selected genome group
7. search within a taxon

**Comment by jimdavis1** [comment]
Also, after I have selected blastp i see this "Search for genes proteins or RNA", which can't be right becasue it would be impossible to find RNA genes and other DNA features etc.

![image](https://user-images.githubusercontent.com/7661533/44269200-b078ee00-a1e8-11e8-9ba0-dda4c9d0ff85.png)

**Comment by mshukla1** [comment]
Second one is list of genomes for which we have public gene expression / transcriptomics data.

**Comment by jimdavis1** [comment]
I am reading it as "Transcriptomics, genomes, protiens".  I would have interpereted it to be blast against all of patric protien NR.

**Comment by jimdavis1** [comment]
As an update to this, Rebecca suggested that #2 should be called "Genomes with transcriptomic data"

**Comment by hyoo** [comment]
Based on discussion above, do you agree to change the list to

1. Reference and representative genomes
2. Genomes with transcriptomic data
3. Plasmids
4. Phages
5. Search within selected genome
6. Search within selected genome group
7. Search within a taxon

@mshukla1 @jimdavis1 ?

**Comment by hyoo** [comment]
We need to update the tutorial as well after we made a decision.

https://docs.patricbrc.org/tutorial/blast/blast.html

**Comment by mshukla1** [comment]
Agree with the list. 

Please make the change and deploy when you get a chance.

**Comment by mshukla1** [comment]
@hyoo can we make the change and close this ticket please?
