### ISSUE TITLE
Example genome name in several service input forms does not work

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#2092]
This is an easy one.  In Similar Genome Finder, Phylogenetic Tree, and Proteome Comparison Services, the example genome name in the Select Genome input box is "M. tuberculosis CDC1551."  However, if you start typing this, nothing will appear in the dropdown once you get past "M. t."  Just need to change the example to a string it will recognize, such as "Mycobacterium tuberculosis CDC1551."

**Comment by dawenx** [comment]
somehow these 3 services use its own placeholder, i.e., "M. tuberculosis CDC1551". i removed it and all of them are using the default placeholder which is "Mycobacterium tuberculosis H37Rv".

this is included in the PR i submitted this morning now.

**Comment by dawenx** [comment]
The fix is on alpha now.

**Comment by dawenx** [comment]
the fix is on production, verify and close.
