### ISSUE TITLE
Contrasts information button on RNA-Seq service missing any information

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2093]
You click on it and it says "Help text missing"

**Comment by rkenyon** [comment]
I can take this one, but need some text for it.  I'm not sure exactly how it is supposed to work and it is not in the Tutorial https://docs.patricbrc.org//tutorial/rna_seq_submission/submitting_rna_seq_job.html.

**Comment by mshukla1** [comment]
The help text was added a while ago. 

I have updated text for contrast in the user guide and it will show up in the contrast tool top from the submission form. 

"Contrasts specify which pairs of conditions to compare in differential expression analysis. The RockHopper strategy performs all vs all contrats by default, hence, no cotrasts need to be specified."
