### ISSUE TITLE
Disable Contrast panel when you use Rockhopper in RNA-Seq

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2095]
Rockhopper automatically does all vs all.  The contrast panel should be grayed out.

**Comment by mshukla1** [comment]
@dawenx, I think it would make sense to provide two options in the contrast panel, all vs all and custom pairwise selection. Then, we can male all vs all as default when Rockhopper is selected and gray out the custom selection option. I think that would make the choices more explicit to the users. 

@aswarren How does Rockhopper compare to Tuxedo in terms of analysis steps / quality of results and acceptance by the community? In other words, if it provides limited capabilities, does it make sense to still offer it as an option?

**Comment by mshukla1** [comment]
We got a complain from a user Today that he is not able to select contrasts when using Rockhopper strategy. 

I tried it myself, the conditions are not available for selection in the contrast panel, I can't bypass contrast selection step, and the submit button is never enabled. 

Given all that, How does one submit a job with Rockhopper. 

This needs to be addressed ASAP. 

-Maulik

**Comment by aswarren** [comment]
Fixed in https://github.com/PATRIC3/p3_web/commit/bcc8e77bb11b904e1be6453b539581d3b15cabf0
