### ISSUE TITLE
Phylogenetic trees-number of genes and characters that built tree needs to be at the top and visible in an obvious way

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2096]
I can find the following buried in the pepr.log report:
2018-08-16 17:41:17 INFO  PhylogenomicPipeline2 - 	taxa: 46
2018-08-16 17:41:17 INFO  PhylogenomicPipeline2 - 	genes: 132
2018-08-16 17:41:17 INFO  PhylogenomicPipeline2 - 	characters: 39531

This needs to be at the top of some report that is very obvious to the user.  It has really important data that they need to include in their publications

**Comment by mshukla1** [comment]
@AllanDickerman Can we provide Summary.txt as part of the job output, which provides a concise summary of the input genomes, protein families, alignment size etc in a user friendly way?

**Comment by AllanDickerman** [comment]
Yes, I can write a short script to pull this out and write to a simple text file.
The script can be invoked by the code that cleans up after PEPR and moves files to the user's workspace.

**Comment by mshukla1** [comment]
This has been addressed in the new codon tree service. The number of protein families used and other alignment stats are displayed in the HTML report.

Given Codon Tree is the preferred and default strategy over PEPR, I am not going to worry about fixing it in PEPR.  

Closing the ticket.
