### ISSUE TITLE
Any output from any service with a peg ID should link back to feature page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2097]
This is an issue with RNA-Seq and the variation service.  We need to allow the users to go directly to the information by hyperlink to feature page, rather than having to use global search to find it.  It takes them far away from their research, and breaks the analysis flow.

**Comment by mshukla1** [comment]
I assume you are talking about having links from any HTML-style result page generated by any service.

@maovt, given you have recently made yourself familiar with the variation service code, can you add links for the patric ids in the following table? 

<img width="834" alt="screen shot 2018-08-23 at 1 47 01 pm" src="https://user-images.githubusercontent.com/1236463/44545913-f26bcd80-a6db-11e8-941b-b6b6d398aae4.png">

**Comment by mshukla1** [comment]
@ARWattam Can you please specify other services / pages where we need to add similar links? ...I couldn't find any in the RNA-seq output.

**Comment by chmao1** [comment]
@mshukla1 Yes. See #2077

**Comment by mshukla1** [comment]
Fixed. Verified on alpha. 

<img width="963" alt="screen shot 2018-08-27 at 10 26 51 am" src="https://user-images.githubusercontent.com/1236463/44668974-724bad80-a9e4-11e8-90af-dc6648a81b55.png">

**Comment by mshukla1** [comment]
@ARWattam, are there any other services that need similar links? I can't think of any!
