### ISSUE TITLE
Reference genomes-Brucella pinnipedialis B2/94 has two different sequences

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#21]
Two different centers have sequenced this genome, but only one is the true reference.  Its the older sequence.  The other sequence should be removed from the references

**Comment by hyoo** [comment]
http://www.beta.patricbrc.org/portal/portal/patric/GenomeList?cType=taxon&cId=520461&dataSource=&displayMode=&pk=&kw=

**Comment by mshukla1** [comment]
Updated. Now only complete genome is marked as representative.
