### ISSUE TITLE
Phylogenetic Tree Building App Weirdness 

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#2101]
The size of text and form labels becomes larger when the browser is resize.

Before resize:

![image](https://user-images.githubusercontent.com/1194246/44424641-59a84700-a54f-11e8-89f3-36fb31c62085.png)

After resize:

![image](https://user-images.githubusercontent.com/1194246/44424667-6c228080-a54f-11e8-9909-4a5ec9a93970.png)

**Comment by dawenx** [comment]
I will look into it. It looks like Proteome Comparison service has similar problem.

**Comment by dawenx** [comment]
The reported issue has been addressed for both Phylogenetic Tree service UI and Proteome Comparison service UI. It's included in PR 798. @hyoo

**Comment by dawenx** [comment]
the fix is on alpha now.

**Comment by dawenx** [comment]
@nconrad i believe this fix on production, please verify, thanks

**Comment by nconrad** [comment]
@dawenx, looks like the help text is fixed, but the input labels still change size/fonts.

Before:
![image](https://user-images.githubusercontent.com/1194246/45451288-43019580-b6a0-11e8-9b82-b67563197e6f.png)

After:
![image](https://user-images.githubusercontent.com/1194246/45451302-4d239400-b6a0-11e8-9f79-1bef65b704d3.png)

**Comment by dawenx** [comment]
@nconrad thanks, i think this is fixed on alpha now

**Comment by dawenx** [comment]
@nconrad i believe this is fixed on production now, please verify and close it, otherwise, you need to work on it. :)

**Comment by nconrad** [comment]
looks good!

**Comment by nconrad** [comment]
@dawenx Do you have any idea why the class "App" is being removed from app forms on resize?  That is what was causing this and adding assembly.css > .paramlabel element is kinda a hack.  I'm seeing that other apps have the same problem, such as Comprehensive Genome Analysis.
