### ISSUE TITLE
PLF and PGF do not appear in sidebar of feature table. 

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2102]
I am trying to click on the PLF ID for the following AMR gene.   There is no link within the table, **AND I CANNOT COPY AND PASTE FROM  TABLE**, and there is no link or PLF or PGF id in the sidebar, which means I have to type that thing into a search widow  to view the family members.  
 
https://www.patricbrc.org/view/Genome/83332.12#view_tab=features&filter=and(or(eq(feature_type,%22CDS%22)),or(eq(annotation,%22PATRIC%22)),keyword(pncA))

![image](https://user-images.githubusercontent.com/7661533/44471143-e820d500-a5f0-11e8-8867-181f9c749a7c.png)

**Comment by mshukla1** [comment]
@nconrad 

- [ ] add PLfam and PGfam in the feature overview panel, on the right of the table, as well as feature overview page. 
- [ ] Link the plfam and pgfam ids to the feature list showing all members of that family.
