### ISSUE TITLE
bad bug: can't click on problematic roles in binning report

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2104]
If you need a binning job to see this:
https://www.patricbrc.org/workspace/jimdavis@patricbrc.org/home/Midwestern_AZ/.Binning_Medium/BinningReport.html

Job id: 15bb2c34-a595-4590-9718-baf73e637628

This job ran successfully last week and I was able to click on the problematic roles in the AZ workshop, but it was broken when I tried to do it for UCLA.

![image](https://user-images.githubusercontent.com/7661533/44821267-a02e1f00-aba9-11e8-9d9b-4e4e15fe4bad.png)

**Comment by dawenx** [comment]
@jimdavis1 i cannot access your workspace, so i cannot verify whether this is still an issue or not. @olsonanl can you help to check?

**Comment by bparrello** [comment]
Has this ever recurred? The code has been revised extensively in the past 9 months.

**Comment by mshukla1** [comment]
looks like this has been fixed.
