### ISSUE TITLE
website slowness:

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2105]
34 seconds:
![image](https://user-images.githubusercontent.com/7661533/44861735-fba1f080-ac2d-11e8-83dc-d590ab049a02.png)

52 seconds
![image](https://user-images.githubusercontent.com/7661533/44861810-3015ac80-ac2e-11e8-8cfa-1816fa1006c4.png)

18 seconds
![image](https://user-images.githubusercontent.com/7661533/44861858-4e7ba800-ac2e-11e8-9d59-30b95ec160a4.png)

two and a half minutes just to return no results found which cant be right.  

![image](https://user-images.githubusercontent.com/7661533/44862085-d19cfe00-ac2e-11e8-8e5a-326cf86b1375.png)

**Comment by dawenx** [comment]
not sure what should be done about this ticket, but i know the performance has been improved a lot lately. i suggest to close this issue. @hyoo @olsonanl what do you think?

**Comment by olsonanl** [comment]
I'd close, but add a ticket that adds monitoring of these sort of times so we can track problems. We still see rocky performance on searches.

**Comment by dawenx** [comment]
OK, i'm opening #2205 as a follow up.
