### ISSUE TITLE
Upload dialog requires a scroll to see submit buttons

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2106]
In order to see the submit button you have to scroll down in the upload dialog; this is confusing and unnecessary since there's tons of screen real estate.

![screen shot 2018-08-31 at 12 33 38 pm](https://user-images.githubusercontent.com/2152226/44927464-3a14d980-ad1a-11e8-85b1-e9466bbc5720.png)

**Comment by nconrad** [comment]
@olsonanl the size of the select files area is smaller on alpha, if you want to try there.  The thing that makes this complicated is the lack of fixed footers in dojo's dialogs, i think.

**Comment by dawenx** [comment]
@nconrad i think we should roll out this fix to production asap, there are several duplicate tickets on this...

**Comment by dawenx** [comment]
@olsonanl i guess the fix mentioned by @nconrad is fixed by now?

**Comment by olsonanl** [comment]
Yes, I think it's been corrected.
