### ISSUE TITLE
Need viruses option in genome annotation apps

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2107]
Wherever we have a domain selection in the genome annotation submission apps (annotation & CGA) we need to have a Viruses option available (for the phages)

**Comment by dawenx** [comment]
This should be easy to add, which one should be the default? Still Bacteria? Followed by Archaea, then Viruses? @mshukla1

**Comment by dawenx** [comment]
the new option is on production, please verify. I will close this issue later this week.
