### ISSUE TITLE
Weird problem with heat map view in Protein Family Sorter

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#211]
I was looking at my private genome and 42 other genomes.  I found an area that was unique to my genome and only two others, and I could not select those specific genes from the heat map view.  Other genes I could get with no problem, but not these specific ones.  And if you don't believe me or think that I was drinking and testing, Maulik couldn't get it either.

**Comment by mshukla1** [comment]
...but that doesn't mean we both weren't drinking and testing! ;)

**Comment by mshukla1** [comment]
Do you still see the same problem, Rebecca?

**Comment by ARWattam** [comment]
Still a problem.  Harry is looking at it

**Comment by hyoo** [comment]
this is specific to outdated website.
