### ISSUE TITLE
Need API to retrieve user information

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2112]
I need to be able to programmatically retrieve user details given a user id

**Comment by dmachi** [comment]
Request from https://user.patricbrc.org/user/USERID with accept: application/json using a valid admin token (for any user) or the USERID's token for that specific user.

**Comment by hyoo** [comment]
This worked for me.
```
curl -H 'Accept:application/json' -H 'Authorization:[admin_token_here]' 'https://user.patricbrc.org/user/[target_user_id_here]' 
```

**Comment by nconrad** [comment]
@hyoo beat me to it.

**Comment by olsonanl** [comment]
Great, thank you.
