### ISSUE TITLE
Bottom line of group "Add genomes" confirmation message is obscured

### ISSUE THREAD

**Issue by gdpusch** [PATRIC3/patric3_website#212]
Under Google Chrome on my MacBook Pro (OS/X 10.9.5 "Mavericks"), when I create a new group of genomes, a small folder-graphic briefly animates over the "Workspace>Add Genomes" tab-widget that confirms the number of genomes added to that group, plus something else that is on a line below this number.

Whatever that "something else" actually says is obscured from my view; it displays mostly below the frame that surrounds the "Workspace>Add genomes" tab-widget. I can only see a tiny little bit of the top of this line of letters.

**Comment by mshukla1** [comment]
it says: 
xxx genome(s)
added to workspace

**Comment by mshukla1** [comment]
![screen shot 2015-06-10 at 2 35 47 pm](https://cloud.githubusercontent.com/assets/1236463/8090780/01e0c278-0f7e-11e5-8e57-68e2a49f3643.png)

**Comment by mshukla1** [comment]
Harry, check the notification panel. After 200 genomes, "added to workspace" is not visible in the panel.

Not critical, see if it can be addressed later.

**Comment by hyoo** [comment]
we need to consider centralized notification system.

**Comment by hyoo** [comment]
this is specific to outdated website.
