### ISSUE TITLE
enhancement proteome comparison

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2122]
Maybe Rebecca should weigh in on this, but I think it is odd that we offer PGFams for the reference genome in the proteome comparison tool, but no corresponding PGFam for the target genome.

![image](https://user-images.githubusercontent.com/7661533/45927621-046fa480-bf04-11e8-8cf0-25270d461352.png)

**Comment by ARWattam** [comment]
I use this tool a lot and I think it would make it even heavier if you added all that information for the comparison genomes.  They can get to the PLFam and PGFam by using the peg ID.  I would prefer not to have additional columns of information duplicated across all the comparison genomes.

**Comment by chmao1** [comment]
Closed this based on Rebecca's comments.
