### ISSUE TITLE
Folder or file names with special characters break workspace browsing

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2125]
This valid workspace path can't be browsed

```
/teaguejo@patricbrc.org/home/Genome Groups/.S. aureus group comparison #2
```

**Comment by olsonanl** [comment]
This is affecting user ticket 1877

https://jira.cels.anl.gov/browse/PATRIC-1877

**Comment by chris-c-thomas** [comment]
https://www.w3schools.com/tags/ref_urlencode.asp

Replacing special characters with the utf-8 encodings in the URL can still allow special characters if needed as a workaround. Otherwise use a RegExp to limit file names?

**Comment by olsonanl** [comment]
I do not want to limit the filenames. Isn't this just a matter of URL-encoding any paths when they show in a URL ? There shouldn't be any fragile magic involved, just consistent practice of quoting when going into a URL and unquoting when required coming out.
