### ISSUE TITLE
Submit button not enabled when public sharing option selected

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2126]
Create a new workspace
Click the Share button in green bar
Click "Publicly Readable"
Submit button remains greyed out
Add a user to share to
Submit button enables
Remove that user
Submit button stays enabled
Then you can click Submit and add public read perms.

https://youtu.be/W3raLr0oJFk

**Comment by nconrad** [comment]
The public permission was actually being changed on checkbox change.  It's fixed in https://github.com/PATRIC3/p3_web/pull/812.  Thanks.
