### ISSUE TITLE
Can a group name be changed after it is created?

### ISSUE THREAD

**Issue by gdpusch** [PATRIC3/patric3_website#213]
Can group names be changed after creation?
If not, it would be nice to make the group-names editable.

**Comment by dmachi** [comment]
There isn't currently a rename function in the UI and probably won't be for this release, but I'll leave this ticket open so we can get it on a subsequent release.

**Comment by hyoo** [comment]
@nconrad how much work needed for this?

**Comment by mshukla1** [comment]
It seems now you cane rename, copy, move and delete genome groups, just like any other files / folders in the workspace. 

I checked on the production site and it seems to be working as expected. 

-Maulik
