### ISSUE TITLE
"add" button in tree app and proteome comparison app

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#2131]
1) go to tree service
2) select your newest genome group
3) click add
4) notice the group is often not added

![image](https://user-images.githubusercontent.com/1194246/46559482-224ee900-c8b6-11e8-98c8-a5c5fef90bf2.png)

This is also an issue if you (quickly?) select a genome id and click add.  The field focus may not be allowing the click the on the add button or something odd.  

A separate issue: since there is a request being made when you select a genome group, we really should add a "loading..." status.   If the data api or network is slow, I get particularly frustrated using the apps.

**Comment by nconrad** [comment]
FWIW, using a dojo button does fix this.  Something like:
```html
<button data-dojo-type="dijit/form/Button" data-dojo-attach-event="click:onAddGenome" class="app-btn">
  <i class="icon-plus"></i> Add
</button>
```

It should be a button anyway for accessibility and so forth.

**Comment by dawenx** [comment]
@nconrad since i' switched to use button when i added Codon Tree method, i think this problem is fixed. i also took your suggestion to show "loading..." info.

please verify on alpha. thanks.

**Comment by chris-c-thomas** [comment]
My only comment is that I noticed it shows loading when you click add even if it's not actually loading anything.

**Comment by dawenx** [comment]
what do you mean by "even if it's not actually loading anything"? i believe i turn on "loading..." after user chooses to add a genome group and we are loading data from workspace in the background.

**Comment by chris-c-thomas** [comment]
If I click "add", even if I haven't selected anything, it display's "loading..."

![Screen Shot 2019-04-03 at 10 04 14 AM](https://user-images.githubusercontent.com/22353987/55489829-4dfa2400-55f8-11e9-872f-e076b43a02c0.png)

The add button above this one does not act that way.

**Comment by dawenx** [comment]
that's a good catch @chris-c-thomas i should have included this in my testing, will fix it

**Comment by dawenx** [comment]
can we close this issue? your concerns had been addressed in tree service UI. @nconrad 

notes: proteome comparison service was not updated for this and there might be similar issue for other services.

**Comment by nconrad** [comment]
sure.
