### ISSUE TITLE
carousel display

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#2137]
![image](https://user-images.githubusercontent.com/1236467/47378442-c231b280-d6bd-11e8-8c42-b7af80f61edd.png)

1. When there is no image in the carousel item, please expand text more so that it takes empty space.

2. I think it would be good to listen docServiceURL in the config to base the carousel request. Then, we can easily test on local machines. 

https://github.com/PATRIC3/p3_web/blob/master/views/index.ejs#L28

3. when no image is given, please skip the img tag
![image](https://user-images.githubusercontent.com/1236467/47378537-09b83e80-d6be-11e8-86cd-2d340c93db0c.png)

**Comment by rkenyon** [comment]
Also, at the risk of duplicating another issue, still need the carousel to cycle through the announcements automatically.

**Comment by chris-c-thomas** [comment]
Per the new homepage design:

![Screen Shot 2019-10-22 at 10 04 04 AM](https://user-images.githubusercontent.com/22353987/67300262-52fac400-f4b3-11e9-92ac-a4f4bb4765ce.png)
