### ISSUE TITLE
Lost sequence link on feature page

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2138]
You can no longer download a fasta sequence from the protein page.

there used to be a button in the bottom left corner

![image](https://user-images.githubusercontent.com/7661533/47451063-68e48480-d78c-11e8-8369-35339f3c1f64.png)

**Comment by dawenx** [comment]
this is fixed on beta: https://www.beta.patricbrc.org/

**Comment by dawenx** [comment]
i have verified fix on production.
