### ISSUE TITLE
Back button is broken after search

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2139]
I am searching for something from the home page, getting a result, but if i click the back button it doesn't nothing happens.  It should send me back to the home page.

**Comment by chris-c-thomas** [comment]
Duplicate of https://github.com/PATRIC3/patric3_website/issues/1999 I believe.

The back button in general is broken and we need to finish finding a solution to this that works everywhere.

**Comment by mshukla1** [comment]
I just tried several scenarios and back button seems to be working as expected. 

Closing the ticket.
