### ISSUE TITLE
RNA-Seq Form Undefined in Dropdown

### ISSUE THREAD

**Issue by Tinyman392** [PATRIC3/patric3_website#2141]
Some odd things happening to produce an undefined value in the dropdown menu.  **Note that I haven't been able to reproduce it with these steps, but it's what I was doing at the time**.  

- Load up RNA-Seq, go straight into the paired end reads and use the folder button to traverse to /Public Workspace/PATRIC Workshop/RNA Seq/COL_75_R1.fq.gz in the first space. 
- Do the same for COL_75_R2.fq.gz.  
- Add COL to the Group/Conditions.  
- Select the folder icon next to the first of the paired end reads (should read COL_75_R1.fq.gz)
- Immediately cancel
- The first box will be empty
- Add MERO to the Group/Conditions
- Add MHB to the Group/Conditions
- Select the MERO (top to bottom)
- Dropdown contained an undefined

<img width="1680" alt="screen shot 2018-10-24 at 3 34 04 pm" src="https://user-images.githubusercontent.com/5612784/47459664-5a08cc80-d7a2-11e8-8f92-3deeea2aa377.png">

**Comment by aswarren** [comment]
I haven't been able to reproduce this either.
We can reopen when we can make it reproducible.
