### ISSUE TITLE
Need better label in Proteome Comparison

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2143]
The label "FASTA FILE" in the dialog should explicitly mention fasta of proteins; it's easy to get confused and not understand what should be there. Perhaps a help icon as well would help.

<img width="357" alt="image" src="https://user-images.githubusercontent.com/2152226/47462742-e4086380-d7a9-11e8-97e8-203f944a8446.png">

**Comment by dawenx** [comment]
I will go head to update the label. The help icon next to "Comparison Genome" does make it explicitly: 

> And/or select FASTA file
> Select or upload an external genome file in protein FASTA format.

**Comment by dawenx** [comment]
this is fixed on beta: https://www.beta.patricbrc.org/
