### ISSUE TITLE
PATRIC user requests molecular weight (mass) of proteins and ability to download them in mass

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2145]
Tied to JIRA 1956.  My response is below.

PATRIC does not currently calculate mass (molecular weight) for the predicted protein sequences.  There are online tools that will allow you to do this (like 
https://web.expasy.org/compute_pi/).  We will consider adding this feature in the future.

**Comment by mshukla1** [comment]
In the last 15 years, we have got only one or two request for someone asking for molecular weights. 

I am going to punt this to P4 and close the ticket.
