### ISSUE TITLE
Genome with no annotated proteins - Naked genome alert!

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2148]
Streptococcus dysgalactiae strain NCTC8547
Genome ID	1334.136

Please, please clothe this genome in warm and comforting proteins

**Comment by dawenx** [comment]
@mshukla1 can you take a look? there's a similar issue #2192 and i assigned this to you as well. a more important question is: do we know why this happened?

**Comment by mshukla1** [comment]
This and other naked genomes have been deleted from the database.
