### ISSUE TITLE
undefined genome group name

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#2149]
Rebecca shared a genome group with me and it resulted in an "undefined" name in the genome group view.  Url: https://patricbrc.org/view/GenomeGroup/ARWattam@patricbrc.org/My%20pal%20Neal/Representative%20Brucella%20and%202%20private%20genomes#view_tab=genomes

![image](https://user-images.githubusercontent.com/1194246/48089461-2b3f1d00-e1ca-11e8-861d-b29e57000003.png)

**Comment by mshukla1** [comment]
@nconrad This is still the case. Can you fix it please?
