### ISSUE TITLE
Broken link in annotation tutorial

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2153]
https://docs.patricbrc.org//tutorial/genome_annotation/annotation.html
The link in "Analyzing Genome Quality" is broken

**Comment by ARWattam** [comment]
<img width="738" alt="screen shot 2018-11-19 at 3 38 58 pm" src="https://user-images.githubusercontent.com/11475316/48733719-779a4c00-ec11-11e8-960f-0d5a5fc426ae.png">

**Comment by chris-c-thomas** [comment]
Fixed in https://github.com/PATRIC3/p3_docs/pull/75

Will update automatically soon.
