### ISSUE TITLE
workspace: view result files

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2157]
From the job result page, if I select a file and double click or click view button, it still keeps the job summary information at the top, which ends up taking half of the page. 

This is becoming a problem now as we have more and more services with HTML reports in the output. 
They will look much better when the job result summary is not at the top and almost entire page is allocated to the file being viewed. 

When I select view file, it should simply show the file, with perhaps file name as bread crumb.

<img width="1072" alt="screen shot 2018-12-04 at 5 44 10 am" src="https://user-images.githubusercontent.com/1236463/49439837-b8ed3880-f787-11e8-8977-e812eaf3026e.png">

**Comment by dawenx** [comment]
I have a fix for this ticket by removing the table, but I keep the caption and download button above the table.

**Comment by dawenx** [comment]
@mshukla1 when you get a minute, can you please verify this fix on alpha? thanks!

**Comment by dawenx** [comment]
@mshukla1 please verify the fix on alpha. i will ask @hyoo to push it to production after that.
