### ISSUE TITLE
RNA-seq: missing operon file

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2159]
With the recent updates, we lost the operon file in the results, which we used to have before! 

We need to add it back. 

-Maulik

**Comment by mshukla1** [comment]
I noticed that we have operon file for RockHopper but not tuxedo.

**Comment by aswarren** [comment]
It is present as a transcripts.txt, but it needs to be named appropriately. 
We will try to do a naming overhaul as part of the hackathon.

**Comment by aswarren** [comment]
Duplicate as of https://github.com/PATRIC3/patric3_website/issues/2155
