### ISSUE TITLE
Please update annotation results spreadsheet format

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2160]
We should move this from FigFams to PLFs and PGFs.

![image](https://user-images.githubusercontent.com/7661533/49596545-2b087d80-f940-11e8-89b7-d3089a7fae60.png)

**Comment by mshukla1** [comment]
Bob, this file is generated by the annotation service / rasttk as part of job results.

**Comment by olsonanl** [comment]
Added in version 1.26 of FigKernelScripts/rast_export_genome.pl in CVS; will propagate to github on next SEED code update.
