### ISSUE TITLE
bugs in transcriptomics tab

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2164]
I clicked on "all bacteria" and then on the transcriptomics tab, because I still cant figure out how many experiments we have.  
I am here:
https://www.patricbrc.org/view/Taxonomy/2#view_tab=transcriptomics

I ended up getting this, which means I still don't know how many transcriptomic experiments we have:
![image](https://user-images.githubusercontent.com/7661533/49687251-253ca480-fac6-11e8-9626-f24dd6154a85.png)

So I clicked on the little "?" button in the yellow bar to see if i could figure out how to get rid of this forced filter, and this is what I got:
![image](https://user-images.githubusercontent.com/7661533/49687269-4dc49e80-fac6-11e8-980c-564ec2ce1089.png)

I guess I will never know how many transcriptomic experiments we have.

**Comment by chmao1** [comment]
Fixed and will be available in the next production build.
