### ISSUE TITLE
Update of Kosakonia radicincitans DSM16656 required as genome is out of date

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2166]
From a user:
I was checking your web interface regarding the genome of Kosakonia radicincitans DSM16656. 
I have noticed that for the chromosome sequence the old taxonomic name and version (version1, contigs) still appear (Completion date: 7/19/12, GCA_000280495.1 <http://www.ncbi.nlm.nih.gov/assembly/GCA_000280495.1>), while the plasmids, announced in the newer version 2, are available and the updated name is given (Completion date: 4/4/17, GCA_000280495.2 <http://www.ncbi.nlm.nih.gov/assembly/GCA_000280495.2>).

The genome was re-sequenced completely in 2017. I that run the plasmids were discovered as well. The complete sequences for the two plasmids and the chromosome were uploaded to NCBI at the same time with the correct taxonomic name (GCA_000280495.2 <http://www.ncbi.nlm.nih.gov/assembly/GCA_000280495.2>).

Could you update the entry/record for the chromosome as well as it is still missing (‘old"), or will it be done with the current updating process?

**Comment by mshukla1** [comment]
New version of this genome has been added to the database. I have responded to the user and closed the JIRA ticket. 

https://www.patricbrc.org/view/Genome/1177180.18
