### ISSUE TITLE
Proteome comparison fails when Feature Group is set as the reference

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2167]
Two users and I have reported.  All have a similar error message:
circos_opts = $VAR1 = {
          'comp_genomes' => [
                              '/scratch/tmp/ofRUvDdFLd/circos/comp_genome_1.txt',
                              '/scratch/tmp/ofRUvDdFLd/circos/comp_genome_2.txt',
                              '/scratch/tmp/ofRUvDdFLd/circos/comp_genome_3.txt',
                              '/scratch/tmp/ofRUvDdFLd/circos/comp_genome_4.txt',
                              '/scratch/tmp/ofRUvDdFLd/circos/comp_genome_5.txt',
                              '/scratch/tmp/ofRUvDdFLd/circos/comp_genome_6.txt'
                            ],
          'is_user_genome' => {},
          'karyotype' => '/scratch/tmp/ofRUvDdFLd/circos/karyotype.txt',
          'ideogram' => '/scratch/tmp/ofRUvDdFLd/circos/ideogram.conf',
          'housekeeping' => '/scratch/tmp/ofRUvDdFLd/circos/housekeeping.conf',
          'circos' => '/scratch/tmp/ofRUvDdFLd/circos/circos.conf',
          'ticks' => '/scratch/tmp/ofRUvDdFLd/circos/ticks.conf',
          'colors' => '/scratch/tmp/ofRUvDdFLd/circos/colors.conf',
          'ref_genome' => '/scratch/tmp/ofRUvDdFLd/circos/ref_genome.txt',
          'large_tiles' => '/scratch/tmp/ofRUvDdFLd/circos/large.tiles.txt',
          'image' => '/scratch/tmp/ofRUvDdFLd/circos/image.conf',
          'ref_type' => 'user_feature_group',
          'radius' => 450,
          'plots' => '/scratch/tmp/ofRUvDdFLd/circos/plots.conf'
        };
Error running cmd=circos -conf /scratch/tmp/ofRUvDdFLd/circos/circos.conf -outputdir /scratch/tmp/ofRUvDdFLd/circos, stdout:

**Comment by chmao1** [comment]
Fixed and will be available in the next build.

**Comment by chmao1** [comment]
@ARWattam The fix is available in production now. Please test and verify.
