### ISSUE TITLE
Downloading genome group will only show first 20 when downloading from genome groups table

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2169]
I tried to download all the genomes from my group (Yeaman Group Two Base) and it only downloads 25 of the 63 genomes.  when I open the group, and select them, I get the whole thing.  I think it must be set to show only 25
<img width="998" alt="screen shot 2019-01-10 at 4 05 47 pm" src="https://user-images.githubusercontent.com/11475316/50997082-afc35a00-14f1-11e9-95c6-f503d2d78e66.png">
<img width="1143" alt="screen shot 2019-01-10 at 4 02 48 pm" src="https://user-images.githubusercontent.com/11475316/50997083-afc35a00-14f1-11e9-8de2-5e953be9d0c4.png">

 from that page.

**Comment by nconrad** [comment]
This is fixed on prod.  The limit is 25000 now.
