### ISSUE TITLE
fna files be added to ftp site for specialty genes

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2175]
User finds the .faa files per source in the ftp site very useful and would like .fna files

**Comment by mshukla1** [comment]
Do you know if the request is for the external reference speciality gene databases (i.e. genes from CARD, VFDB etc) or for the specialty genes annotated in all genomes using blast?

**Comment by mshukla1** [comment]
We don't have fna files for all sources, as we only use  fasta protein sequences and BLASTP in our specialty genes pipeline. We can refer user to the individual sources for fna sequences.
