### ISSUE TITLE
Jobs Count Error

### ISSUE THREAD

**Issue by Tinyman392** [PATRIC3/patric3_website#2177]
Failed jobs count says 9 on the top of the page, there are actually 58.  

<img width="1680" alt="screen shot 2019-01-15 at 10 55 32 am" src="https://user-images.githubusercontent.com/5612784/51196314-7c4b4b80-18b4-11e9-9f41-566038381f7e.png">

**Comment by nconrad** [comment]
This is duplicate of https://github.com/PATRIC3/patric3_website/issues/2060
