### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by disz** [PATRIC3/patric3_website#218]
See below, the gene we want is hidden by the title "Refseq Annotation"

![screen shot 2015-06-04 at 11 14 25 am](https://cloud.githubusercontent.com/assets/5824759/7988801/e7bc4d68-0aaa-11e5-8622-0dfc2691fc2a.png)

**Comment by mshukla1** [comment]
I believe this has been a jbrowse issue/feature from the very beginning. You can drag/pan the view to the right to bring the hidden feature in the display.
