### ISSUE TITLE
Heatmap from subsystems page not limited by selected genomes

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2183]
To reproduce: select a set of genomes. Go to subsystem view. Select a subsystem:

![screen shot 2019-01-22 at 4 18 50 pm](https://user-images.githubusercontent.com/2152226/51565992-754aad00-1e61-11e9-8352-5a10c1da24a2.png)

Click on map, get a subsystem map for a lot more genomes than you selected. 

![screen shot 2019-01-22 at 4 22 09 pm](https://user-images.githubusercontent.com/2152226/51566175-e4c09c80-1e61-11e9-9e3e-1eb8993e9e50.png)

https://youtu.be/-kIRe164J4g

**Comment by hyoo** [comment]
I cannot tell with the current screen capture, but i believe we activated "reference genome view" by default, to compare the current set of genomes with reference genomes. 

This was a request from Veronika or Sveta as far as i remember. @mshukla1 can you double check?

**Comment by olsonanl** [comment]
Whatever the intent, it acts differently than the other PATRIC tools in this respect.


________________________________

**Comment by mshukla1** [comment]
#1976 duplicate.
