### ISSUE TITLE
RNA-Seq - unable to add contrasts

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2184]
I have had a user complain about not being able to submit his RNA-Seq job (JIRA 2139). I have tried this myself using the same samples that we use for the workshop and establishing the same conditions.  It doesn't work with either Rockhopper or Tuxedo.

**Comment by mshukla1** [comment]
There was a problem with adding contrasts with RockHopper, which has been fixed. 

I have verified it on production site.
