### ISSUE TITLE
prok_tuxedo needs a threadcount option

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2186]
Please add a command line flag for prok_tuxedo to specify the threads being used; we need this for good integration with other running applications on the shared compute servers.

Thanks!

**Comment by olsonanl** [comment]
FYI this is the effect of terminating just after 14:20 a 24-thread cufflinks that was making redwood overcommitted. Red is system CPU (overhead):

![image](https://user-images.githubusercontent.com/2152226/51706433-03e73780-1fe4-11e9-8709-3c0acce35483.png)

**Comment by aswarren** [comment]
@olsonanl I've made two updates relevant to this. Prok_tuxedo has been updated with an override parameter mechanism that allows the specification of the number of threads to be used for each component.
I also made a pull request for the RNA-Seq app-service wrapper that gives the JSON override to set the number of threads to 2 for each component.
Not sure if you had something more dynamic in mind.

**Comment by olsonanl** [comment]
Perfect. I'll tweak the perl wrapper to let the app configuration specify the thread count to use.

Thanks.
