### ISSUE TITLE
Expression import reorders conditions

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2187]
The default view of the data in the experiment view for an imported data file reorders the conditions into alphabetical order, rather than showing the original order of the data in the file. This seems odd, since it erases the groupings that were in place in the original data.

Original data:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/2152226/51629000-83a5d100-1f14-11e9-832d-bb7a058941bb.png">

Initial view:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/2152226/51629276-3413d500-1f15-11e9-977b-39fa975dd669.png">

I realize that in the analysis the order gets switched around but for an initial perusal of the data it make sense to me that it be in the order as defined by the user.

**Comment by chmao1** [comment]
Fixed and waiting for the deployment in the production

**Comment by chmao1** [comment]
The fix is available in production.
