### ISSUE TITLE
Example IDs not showing in ID Mapper

### ISSUE THREAD

**Issue by Tinyman392** [PATRIC3/patric3_website#2189]
Example IDs in the ID mapper won't show examples for anything that isn't a "PATRIC ID".  Use the dropdown box and select something that isn't "PATRIC ID".  

<img width="1680" alt="screen shot 2019-01-24 at 1 34 20 pm" src="https://user-images.githubusercontent.com/5612784/51703773-de0a6480-1fdc-11e9-82b9-eefdcbb483a6.png">

**Comment by dawenx** [comment]
looks like only small subset of options on left/right have example assigned, e.g., PATRIC ID, RefSeq (Protein ID), RefSeq Locus tag. i don't know the requirement and background on this service. Do we want to have example for all options on left/right? If so, could someone provide a mapping? I can update the UI afterward. @Tinyman392 @aswarren

**Comment by dawenx** [comment]
@mandywil the main thing is to find out what's requirement, @aswarren probably has insight on this as he is the 'owner' of ID Mapper service.

**Comment by mandywil** [comment]
Hi Andrew, I think if you could provide a list of example identifiers for each of the identifiers in the list (preferably all for the same sequence, though I don't think we implied anything of that kind) or -- even better -- tell me where I can find that information (so I learn :) ), then I can take care of this.
Thanks!

**Comment by mshukla1** [comment]
@dawenx I don't think we can / should provide separate examples for each of the id types. 

Please remove the "Example" from under the dropdown menus.

Instead,   just add the following gray text in the text box itself. 

Enter one or more identifiers separated by comma, space, or newline, e.g. Rv0001 Rv0002 Rv0003 Rv0004 Rv0005

**Comment by dawenx** [comment]
ok, will do.

updated: reassign this to @mandywil

**Comment by ARWattam** [comment]
But its true, right, that one of the IDs has to be PATRIC.  What Marcus showed in the screenshot will not work (convert Drugbank ID to KEGG ID).  You could only convert Drugbank to PATRIC, and then PATRIC to KEGG.  So PATRIC ID needs to be in the example, unless this is no longer the way that ID Mapper is set up.

**Comment by Tinyman392** [comment]
The screenshot was just to show that example IDs didn't show up unless it was a PATRIC ID.  So if I wanted to convert a PATRIC ID to a KEGG ID, it would show an example of a PATRIC ID but not of a KEGG ID.
