### ISSUE TITLE
Layout Problem

### ISSUE THREAD

**Issue by disz** [PATRIC3/patric3_website#219]
Displaying 5 features, the fifth is below the window and we can't move it up to see it.

![screen shot 2015-06-04 at 12 59 28 pm](https://cloud.githubusercontent.com/assets/5824759/7990875/9049b6c4-0ab9-11e5-9b7e-c6136182f416.png)

**Comment by hyoo** [comment]
I cannot reproduce it. Which browser are you using?

**Comment by mshukla1** [comment]
I tried too, cannot reproduce it. 

Please respond / reopen it you still see the problem.
