### ISSUE TITLE
Need to include taxon_id field to search on global search

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2190]
I just searched for "1280" the tax id for staph aureus, and here is what it returned.  Note that it did not find 1280.
![image](https://user-images.githubusercontent.com/7661533/51708339-4e1ee780-1fe9-11e9-8473-79f005868ac8.png)

**Comment by mshukla1** [comment]
It returns all the taxon nodes that have 1280 as either taxon id or somewhere in taxon name.

If you look at taxon they all have 1280 in them.

-Maulik



On Jan 24, 2019, at 3:04 PM, jimdavis1 <notifications@github.com<mailto:notifications@github.com>> wrote:


I just searched for "1280" the tax id for staph aureus, and here is what it returned:
[image]<https://user-images.githubusercontent.com/7661533/51708339-4e1ee780-1fe9-11e9-8473-79f005868ac8.png>

**Comment by dmachi** [comment]
It doesn’t appear to actually be returning results with taxon id == 1280 or in a substring of the taxon_id.

I suspect these aren’t part of the keyword/text search field and that is why.  I don’t remember whether taxon_id in solr is an int or text field.   One possible solution for this is to modify the query (link) that the search generates from ?keyword(1280) to ?or(eq(taxon_id,1280),keyword(1280)).  

https://patricbrc.org/view/TaxonList/?or(eq(taxon_id,1280),keyword(1280)) <https://patricbrc.org/view/TaxonList/?or(eq(taxon_id,1280),keyword(1280))>

**Comment by mshukla1** [comment]
Ahh, I see the problem now.

You are right, Dustin. Taxon id is not included in copy field for keyword search.

Harry, can you please add taxon id in the copy field?

-M



On Jan 24, 2019, at 3:48 PM, Dustin Machi <notifications@github.com<mailto:notifications@github.com>> wrote:

It doesn’t appear to actually be returning results with taxon id == 1280 or in a substring of the taxon_id.

I suspect these aren’t part of the keyword/text search field and that is why. I don’t remember whether taxon_id in solr is an int or text field. One possible solution for this is to modify the query (link) that the search generates from ?keyword(1280) to ?or(eq(taxon_id,1280),keyword(1280)).

https://patricbrc.org/view/TaxonList/?or(eq(taxon_id,1280),keyword(1280)) <https://patricbrc.org/view/TaxonList/?or(eq(taxon_id,1280),keyword(1280))>

**Comment by mshukla1** [comment]
Harry, can you change the solr schema so that the taxon id is also included in the copy field? 

-Maulik

**Comment by hyoo** [comment]
I think we can modify from the UI side, to search on taxon_id field. @chris-c-thomas would you start looking into this?

**Comment by hyoo** [comment]
Two entry points:
1. in global search, choose target "Taxa" and search with 1280
2. global search with 1280 and click "Taxa" Title name.

**Comment by hyoo** [comment]
We can discuss possible solutions, but my quick suggestion is to changing query

from

https://patricbrc.org/view/TaxonList/?keyword(%221280%22)

to

https://patricbrc.org/view/TaxonList/?or(keyword(%221280%22),eq(taxon_id,1280))

**Comment by chris-c-thomas** [comment]
@hyoo yes I will start looking into this solution.

**Comment by mshukla1** [comment]
This has been fixed with the migration to solr cloud. Now, when searched by taxon id, it appears at the top of the search results. 

<img width="1357" alt="Screen Shot 2019-06-03 at 11 30 14 AM" src="https://user-images.githubusercontent.com/1236463/58818175-1527fc80-85f3-11e9-9a35-62675fcd7794.png">
