### ISSUE TITLE
Genetic code 25 missing from user interface

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2193]
I've about got the backend fixed for #1838 but the submission interface doesn't pick gc 25 when choosing a genome with that genetic code (e.g. 1643353) and the drop down doesn't offer 25 as an option.

The taxonomy core has the correct value.

**Comment by dawenx** [comment]
@olsonanl if you give me label for this particular code, e.g., label for 11 is "11 (Archaea & most Bacteria)", i can add this option to UI quickly.

**Comment by olsonanl** [comment]
"Candidate Division SR1 and Gracilibacteria"

**Comment by mshukla1** [comment]
Dawen, I see the annotation service now shows genetic code 25. The same needs to be shown on the comprehensive genome analysis service as well.

**Comment by dawenx** [comment]
UI for CAS has been updated as well.

**Comment by dawenx** [comment]
on alpha now for both Annotation and CAS services, please verify.
