### ISSUE TITLE
Need to update BLAST database

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2194]
Tied to JIRA 2141
User is unable to blast the following sequence against these genome IDs (2065118.12, 2065118.14, 1639.5069, 1639.5025)

MANLKVIENEATILASIPKHNVDYNARVMQSVSVDYERDMIYWTQQYSGKKMTDAGAGES
YNITRTDLKGNYIDQMWCLNGGHGTNIALDYNLESKKMHIWSAYKINNKWEVVCYPYESN
KILKGTESSIFISKVESGSYNRISGDLKNDMLVFHSGGDPKTFNIRIVRASSVREGKLEV
LYKVKATEANDAYVYQGCALDFPYLYTASGTGGVEEPKQLTCVDIVTGKRVYQTTFKFNT
KAMQTTESNFAEPENVCVYYKNNQKHIVVGYALGGAGNRMNRAFDLVENNSENIETEIES
LRNLIISRKRTEVIFDQSTKGDMTTNFKLRETLNNFDIIQVVLESGGGYTTASRLVSPKL
FEASKSFIFASSNIGDTSGNNVDMYEYAANFNDDLTSFKNDRAVKIEVSNNGTVRGNITN MGIKKIYGIVL

**Comment by mshukla1** [comment]
All BLAST databases have been updated after the January Release.

**Comment by mshukla1** [comment]
I have updated all blast databases. I tried the specific query above and it is working now.
