### ISSUE TITLE
cant click on icons in job results page

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2195]
![image](https://user-images.githubusercontent.com/7661533/52302552-2c135680-2953-11e9-876f-5d5f86b1a1f0.png)

**Comment by nconrad** [comment]
I was with Jim when we saw this.  Although this is general problem, it's a problem in the job result page because of the full width on the title div and whatnot.  @dawenx Should be simple to fix, so feel free to assign back to me if you don't want the joy of closing this. :)
