### ISSUE TITLE
Tree: view tree icon not working 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2197]
On the tree job result page, the View Tree icon at the top right corner is not working. 

It takes one to the tree page, but the tree never load. 

If I select a newick file and then click on the tree icon in the green bar, that works fine. 

<img width="1078" alt="screen shot 2019-02-06 at 2 00 46 pm" src="https://user-images.githubusercontent.com/1236463/52370306-26cc0f80-2a18-11e9-80c3-7c31fbf4404c.png">

**Comment by dawenx** [comment]
@aswarren I need your help on this. there are 2 things we found so far: 1) when using PATRIC Workshop folder under public, "the /public/ part is an artifact of the web URL not part of the ws path" 2) the viewer does not work even after "/public" part is manually removed from the link. https://github.com/PATRIC3/p3_web/blob/master/public/js/p3/widget/viewer/PhylogeneticTree.js#L129 might be the reason as there are more 1 json file @dmachi 

@mshukla1 how many json files in your result folders?

**Comment by nconrad** [comment]
I did a test run yesterday with the following and I can't view the tree.   Job ID: ef018135-f005-40f1-9177-7b4bda78cce0


```
{
  "output_file": "buchnera with wigglesworthia",
  "out_genome_ids": [
    "36868.4"
  ],
  "full_tree_method": "ft",
  "output_path": "/nconrad@patricbrc.org/home/rebecca-tests",
  "refinement": "no",
  "in_genome_ids": [
    "261317.3",
    "1005057.4",
    "561501.4",
    "563178.4",
    "118109.3",
    "1265350.3",
    "1005090.4",
    "713600.3",
    "713601.3",
    "713603.3",
    "713602.3",
    "372461.17",
    "1878935.3",
    "1921549.3",
    "224915.9",
    "198804.5",
    "1009858.3",
    "1009857.3",
    "107806.10",
    "1009856.3",
    "1009859.3",
    "1921549.6",
    "118110.3",
    "9.55",
    "655384.3",
    "98804.3",
    "2173854.3",
    "98794.7",
    "118101.4",
    "1921552.3"
  ]
}
```

![image](https://user-images.githubusercontent.com/1194246/52656670-70a37280-2ebc-11e9-8224-0dccd8ce31d6.png)

![image](https://user-images.githubusercontent.com/1194246/52656733-929cf500-2ebc-11e9-833e-ab141b2a5139.png)

**Comment by mshukla1** [comment]
I see three tree (nwk) files in the job output, see the screenshot attached. 

Come to think of it, why do we have three nwk files in the output in the first place? 

<img width="366" alt="screen shot 2019-02-12 at 11 55 55 am" src="https://user-images.githubusercontent.com/1236463/52657042-59b15000-2ebd-11e9-8fc1-3f4fa226fff8.png">

**Comment by nconrad** [comment]
ah, from Rebecca: 

.nwk has the names (and ids after the `_@_`)
```
(Buchnera_aphidicola_str._Tuc7_Acyrthosiphon_pisum_@_561501.4:2.3E-4,((Buchnera_aphidicola_str._APS_Acyrthosiphon_pisum_@_107806.10:0.0015,(Buc
```

.final.nwk has just ids
```
((1921552.3:0.32086,(((98804.3:0.33432,((1878935.3:0.11241,261317.3:0.1212)100:0.15623,(372 . ...
```

and .final_rooted.nwk is the midpoint rooted version with ids
```
((1921552.3:0.32086,(((98804.3:0.33432,((1878935.3:0.11241,261317.3:0.1212)100:0.15623,(372461.17:0.16484,(655384.3:0.18485,(9.55:0.19155,(1921549.3:1.5E-4,1921549.6:1.6E- ...
```

**Comment by dmachi** [comment]
I don’t know the differences in the nwk files, I thought one was used to generate the other so that it includes IDs, but I could be wrong about that.  However, as Dawen mentioned, the issue is the .json files, not the nwk files.  The current code was expecting a single json file.  It needs to change to allow multiple json files to exist and to do that he needs to know which one.

**Comment by dawenx** [comment]
i don't know why i'm assigned to this issue... i did look into the codes a bit the other day, t**he viewer expects only 1 .json file, if there's more than 1 .json files, it fails**. looks like there are more than 1 .json files in the results now and that's the problem. if someone tells me a rule to pick a .json file, i will try to fix it.

**Comment by mshukla1** [comment]
Please link using final.nwk and assign the issue back to me for review when fix is deployed.




On Feb 14, 2019, at 9:24 AM, Dawen Xie <notifications@github.com<mailto:notifications@github.com>> wrote:


i don't know why i'm assigned to this issue... i did look into the codes a bit the other day, the viewer expects only 1 .json file, if there's more than 1 .json files, it fails. looks like there are more than 1 .json files in the results now and that's the problem. if someone tells me a rule to pick a .json file, i will try to fix it.

**Comment by dmachi** [comment]
Dawen, I think the answer is to use the .json file that matches the name of whatever nwk file is being used.  That, I assume, should be either .final.nwk or .final_rooted.nwk.  I’m not sure which of those is correct to use for the button at the top.  Perhaps since there are now multiple nwk files, there should just not be a button at the top and people should choose the specific nwk file they want to view.

**Comment by dawenx** [comment]
@dmachi so remove the 'view' icon on the top for now?

**Comment by mshukla1** [comment]
I suggest to keep the icon for the consistency sake and use the final.nwk to link it.

There us not much difference between the nwk files, one uses genome name and one
uses genome id, so they can be used in other external programs as needed.

For our viewer, it doesn’t;t make much difference.

-Maulik




On Feb 14, 2019, at 9:36 AM, Dawen Xie <notifications@github.com<mailto:notifications@github.com>> wrote:


@dmachi<https://github.com/dmachi> so remove the 'view' icon on the top for now?

**Comment by dawenx** [comment]
OK, i checked in a fix and it's in PR 837. I believe it fixes both '/public' issue and multiple json files issue.

**Comment by dawenx** [comment]
@mshukla1  this is on alpha now, i have tested it on safari/firefox/chrome, please verify.
https://www.alpha.patricbrc.org/view/PhylogeneticTree/?&labelSearch=true&idType=genome_id&labelType=genome_name&wsTreeFolder=/public/PATRIC@patricbrc.org/PATRIC%20Workshop/Phylogenetic%20tree/Buchnera%20Wigglesowrthia%20Blochmannia

**Comment by mshukla1** [comment]
Verified. It is working on alpha now. Thanks.
