### ISSUE TITLE
Feature Overview: add link to identical nucleotide sequences

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2198]
Now that we have na_sequence_md5 field available in the genome_feature core

We should add a link to the identical gene / nucleotide sequences on the feature overview page.

<img width="694" alt="screen shot 2019-02-06 at 2 18 39 pm" src="https://user-images.githubusercontent.com/1236463/52371232-96db9500-2a1a-11e9-8e25-878aff26dfed.png">

**Comment by chris-c-thomas** [comment]
Verified on alpha.

**Comment by chris-c-thomas** [comment]
Verified on prod.
