### ISSUE TITLE
Proteome comparison: download files tooltip doesn't go away

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2199]
On proteome comparison job result page, click on the "DWNLD" icon on top right. 

It shows the tool tip for downloading table or svg file, which just stays there and doesn't go away 
when clicked again on the same icon or clicked anywhere else on the page. 

Please check job result pages for other job types as well to make sure the issue is not more wide spread.  

<img width="1207" alt="screen shot 2019-02-06 at 2 53 56 pm" src="https://user-images.githubusercontent.com/1236463/52373195-b0331000-2a1f-11e9-929e-7506802d1918.png">

**Comment by dawenx** [comment]
i found the problem and fixed it. it's in PR #837 @hyoo

**Comment by dawenx** [comment]
@mshukla1 this is on alpha now, please verify:
https://www.alpha.patricbrc.org/workspace/public/PATRIC@patricbrc.org/PATRIC%20Workshop/Proteome%20comparison/Escherichia%20coli%20MRSN388634%20Comparison

**Comment by dawenx** [comment]
verified on production.
