### ISSUE TITLE
More genomes missing strain names, although listed in metadata

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#22]
http://beta.patricbrc.org/portal/portal/patric/Genome?cType=genome&cId=235.15

Should be BDW

**Comment by hyoo** [comment]
This is a data problem. 

http://dayhoff.vbi.vt.edu:8080/solr/genome/select?q=genome_id%3A235.15&fl=genome_name

Will discuss with Maulik to fix.

**Comment by hyoo** [comment]
#20
