### ISSUE TITLE
The special URL, http://tb.patricbrc.org, gives a 503 error

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#220]
It used to redirect to https://www.patricbrc.org/portal/portal/patric/TB which is the special TB page we set up in PATRIC at NIAID's request.  We need the http://tb.patricbrc.org functional again because that is the URL we distributed.  Becky says this probably has something to do with the move to the cluster.

**Comment by mshukla1** [comment]
Dustin, please address this before the release. 

-Maulik

**Comment by dmachi** [comment]
I will deploy a fix tomorrow.

**Comment by dmachi** [comment]
http://tb.patricbrc.org now redirects to https://www.patricbrc.org/portal/portal/patric/TB
