### ISSUE TITLE
Remove Alt locus tag from standard table view

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2200]
Nobody cares about seeing those.  We should remove them from the standard table format.  I guess we should keep them available for adding in, though.

**Comment by dawenx** [comment]
on which page?

**Comment by mshukla1** [comment]
From the transcriptomics gene list, hide alt locus tags and genome name from the default
view. Allow users to show them using “add column widget” if they want to.



On Feb 7, 2019, at 12:23 PM, Dawen Xie <notifications@github.com<mailto:notifications@github.com>> wrote:


on which page?

**Comment by dawenx** [comment]
You are talking about this page, correct? I will work on this. https://www.patricbrc.org/view/TranscriptomicsExperiment/?in(eid,(1071603,1150517))

**Comment by dawenx** [comment]
i have updated default columns, both "genome name" and "alt locus tag" are not displayed by default. 

this is part of PR 837 now. @hyoo

**Comment by dawenx** [comment]
@ARWattam  this is on alpha now, please verify. https://www.alpha.patricbrc.org/view/TranscriptomicsExperiment/?in(eid,(1071603,1150517))

**Comment by dawenx** [comment]
verified on production.
