### ISSUE TITLE
Metagenomic binning: links from HTML report break when copied to another location

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2201]
Bob, not sure if this belongs to you or Bruce or workspace/UI people. 

I copied a completed metagenomic binning job result from Rebecca's workspace to public workshop folder and made those bins public, so that we can use them in workshop. 

https://www.patricbrc.org/workspace/PATRIC@patricbrc.org/PATRIC%20Workshop/Metagenome%20Binning/Louse%20Fly%20Metagenome/.Louse%20flie%20metagenomes%20ERR969522/BinningReport.html

The binning report and genomes are accessible. However, when I click on the link for problematic roles, it breaks because it points to the files in Rebecca's workspace. 

It looks like the link it hard coded with fixed url, instead being relative to the directory it is on, which could be a problem when users try to copy/move job results. 

Who would be the right person to address this? 

-Maulik

**Comment by olsonanl** [comment]
This is fixed in a2860ab33fb5a277e1377f33e95d90617e32973b and will deployed shortly.
