### ISSUE TITLE
CLI: p3-put-genome-group and p3-put-feature-group gives error

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2203]
For the workshop Today, I downloaded and installed latest version of CLI and found that the 

p3-put-genome-group and p3-put-feature-group command are not working. 

I get the following error when I use -h option. 

mshukla:~/cli_demo> p3-put-genome-group -h
Can't locate JSON/RPC/Legacy/Client.pm in @INC (you may need to install the JSON::RPC::Legacy::Client module) (@INC contains: /Applications/PATRIC.app/deployment/lib /Applications/PATRIC.app/runtime/lib/perl5/site_perl/5.28.1/darwin-2level /Applications/PATRIC.app/runtime/lib/perl5/site_perl/5.28.1 /Applications/PATRIC.app/runtime/lib/perl5/5.28.1/darwin-2level /Applications/PATRIC.app/runtime/lib/perl5/5.28.1) at /Applications/PATRIC.app/deployment/lib/P3WorkspaceClient.pm line 10.
BEGIN failed--compilation aborted at /Applications/PATRIC.app/deployment/lib/P3WorkspaceClient.pm line 10.
Compilation failed in require at /Applications/PATRIC.app/deployment/plbin/p3-put-genome-group.pl line 15.
BEGIN failed--compilation aborted at /Applications/PATRIC.app/deployment/plbin/p3-put-genome-group.pl line 15.

**Comment by olsonanl** [comment]
which CLI version do you have? This appears to be working for me in 1.024

**Comment by olsonanl** [comment]
This has long been resolved.
