### ISSUE TITLE
Can't change column width

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2204]
https://www.patricbrc.org/view/Feature/PATRIC.562.23850.562.23850.con.0017.CDS.50114.51616.rev

I am in safari and I cant adjust the column width to read the information about this transporter in the bottom table. 

![image](https://user-images.githubusercontent.com/7661533/52570968-48dbde00-2dda-11e9-98ff-544d91c790d9.png)

**Comment by dawenx** [comment]
look like this table is implemented using pure html table tag... @chris-c-thomas @nconrad do you know a way to make it adjustable using CSS?

**Comment by dawenx** [comment]
ignore my previous comment as i spoke too soon, i will work on this...

**Comment by chris-c-thomas** [comment]
@dawenx is it specific to Safari or does Firefox/Chrome also cause issues? I'm curious if the CSS is being rendered differently.

I imagine the issue can occur in other areas?

**Comment by dawenx** [comment]
@chris-c-thomas no, this is not a browser related issue and i have a solution for this. thanks.

**Comment by dawenx** [comment]
this is part of PR 837 now.

**Comment by dawenx** [comment]
@jimdavis1 this is on alpha now, please verify: https://www.alpha.patricbrc.org/view/Feature/PATRIC.562.23850.562.23850.con.0017.CDS.50114.51616.rev
