### ISSUE TITLE
What version of MLST are we using?

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2207]

**Comment by dawenx** [comment]
@olsonanl @mshukla1 Bob/Maulik, do you know?

**Comment by olsonanl** [comment]
It is a modified-to-run-here version of whatever we inherited from the person who is no longer with the project. Code at https://github.com/patric3/p3_mlst

Database used is /disks/patric-common/data/mlstdb-2015-1123

**Comment by dawenx** [comment]
can we go ahead and close this "issue" then?

@jimdavis1 i'm wondering why you opened an issue for a question, or, do i understand this incorrectly?

**Comment by rkenyon** [comment]
Dawen,

Jim, Rebecca, or Maulik can maybe verify, but I believe that the MLST references/designations can change over time, and the database may need to be updated.

Ron

**Comment by dawenx** [comment]
@rkenyon thanks for the info.

Assign this to @olsonanl @mshukla1 then, feel free to assign it to others. Maybe we should update the subject as it looks like a question to me.

**Comment by rkenyon** [comment]
Yes, the MLSTs are dynamic .  Maulik will be able to address the version issue, but we probably do need to update them.

Rebecca

From: "Kenyon, Ronald W (rwk4gy)" <rkenyon@virginia.edu>
Date: Friday, February 15, 2019 at 8:44 AM
To: PATRIC3/patric3_website <reply@reply.github.com>, PATRIC3/patric3_website <patric3_website@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>, "Shukla, Maulik" <mshukla@anl.gov>, "Wattam, Rebecca (arw3s)" <wattam@virginia.edu>
Subject: Re: [PATRIC3/patric3_website] What version of MLST are we using? (#2207)

Dawen,

Jim, Rebecca, or Maulik can maybe verify, but I believe that the MLST references/designations can change over time, and the database may need to be updated.

Ron

**Comment by mshukla1** [comment]
Yes, we do. it has been long overdue.

-Maulik

On Feb 15, 2019, at 7:50 AM, rkenyon <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes, the MLSTs are dynamic . Maulik will be able to address the version issue, but we probably do need to update them.

Rebecca

From: "Kenyon, Ronald W (rwk4gy)" <rkenyon@virginia.edu<mailto:rkenyon@virginia.edu>>
Date: Friday, February 15, 2019 at 8:44 AM
To: PATRIC3/patric3_website <reply@reply.github.com<mailto:reply@reply.github.com>>, PATRIC3/patric3_website <patric3_website@noreply.github.com<mailto:patric3_website@noreply.github.com>>
Cc: Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>, "Shukla, Maulik" <mshukla@anl.gov<mailto:mshukla@anl.gov>>, "Wattam, Rebecca (arw3s)" <wattam@virginia.edu<mailto:wattam@virginia.edu>>
Subject: Re: [PATRIC3/patric3_website] What version of MLST are we using? (#2207)

Dawen,

Jim, Rebecca, or Maulik can maybe verify, but I believe that the MLST references/designations can change over time, and the database may need to be updated.

Ron

**Comment by rkenyon** [comment]
Does it include re-calling MLSTs on existing genomes in the database as well?

Ron

**Comment by mshukla1** [comment]
Yes.



On Feb 15, 2019, at 9:32 AM, rkenyon <notifications@github.com<mailto:notifications@github.com>> wrote:

Does it include re-calling MLSTs on existing genomes in the database as well?

Ron

**Comment by jimdavis1** [comment]
I genuinely missed Bob's pointer to the github.  I actually forgot that i wrote this previous ticket last week.  I have written a lot of tickets and emails about the MLST tool, and it has been an ongoing issue for several years.  

Anyway, for those of you who thing this is a low priority, or a fit of histrionics, it is not. 

To get a handle on this, I cloned Torsten Seeman's MLST caller (he's the prokka guy) from https://github.com/tseemann/mlst. I then called two data sets with it.  The first data set has 1330 Staph aureus genomes.  From this set, I was able to download a MLST call for 71 of these genomes from SOLR.  Then when I ran it through the Seeman MLST caller, I got MLST calls _for all of the genomes except 19._

I then repeated this with a set of 1474 E. coli genomes.  We have MLSTs for most of these genomes in SOLR and they largely agree with the Seeman MLST calls.  If you compare the two sets the patric call is totally missing or "wrong" in 10 cases. I am attaching the data below. 

So its a mixed bag: the Staph data is horrific, and the E. coli data is pretty much okay (as far as I can tell).  

_It is my opinion that this tool is in bad enough shape that it should take precedence over the current deployment of new tools._ The PATRIC MLST repo was last touched on Dec 1 2016. 

If nobody in the group understands or trusts the code, it might be reasonable to cut over to the seeman version.  It seems nice and can dump json formatted output.  This really should be a rasttk module. 


[MLST_comparison.xlsx](https://github.com/PATRIC3/patric3_website/files/2895180/MLST_comparison.xlsx)

**Comment by mshukla1** [comment]
I am working on updating MLST databases and MLST assignments for all public genomes.

I will have some update by next Tuesday.

-M



On Feb 22, 2019, at 12:21 PM, jimdavis1 <notifications@github.com<mailto:notifications@github.com>> wrote:


I genuinely missed Bob's pointer to the github. I actually forgot that i wrote this previous ticket last week. I have written a lot of tickets and emails about the MLST tool, and it has been an ongoing issue for several years.

Anyway, for those of you who thing this is a low priority, or a fit of histrionics, it is not.

To get a handle on this, I cloned Torsten Seeman's MLST caller (he's the prokka guy) from https://github.com/tseemann/mlst. I then called two data sets with it. The first data set has 1330 Staph aureus genomes. From this set, I was able to download a MLST call for 71 of these genomes from SOLR. Then when I ran it through the Seeman MLST caller, I got MLST calls for all of the genomes except 19.

I then repeated this with a set of 1474 E. coli genomes. We have MLSTs for most of these genomes in SOLR and they largely agree with the Seeman MLST calls. If you compare the two sets the patric call is totally missing or "wrong" in 10 cases. I am attaching the data below.

So its a mixed bag: the Staph data is horrific, and the E. coli data is pretty much okay (as far as I can tell).

It is my opinion that this tool is in bad enough shape that it should take precedence over the current deployment of new tools. The PATRIC MLST repo was last touched on Dec 1 2016.

If nobody in the group understands or trusts the code, it might be reasonable to cut over to the seeman version. It seems nice and can dump json formatted output. This really should be a rasttk module.

MLST_comparison.xlsx<https://github.com/PATRIC3/patric3_website/files/2895180/MLST_comparison.xlsx>

**Comment by olsonanl** [comment]
It's not clear whether this is a code or a database problem. Seeman appears to be using the same pubmlst databases we are. I'd hold the firetrucks back until we see what Maulik's update shows.

I'd also like to reiterate: discussions of such issues are perfect fodder for the Tuesday calls.

**Comment by rkenyon** [comment]
I had planned to add it to this coming Tuesday’s agenda, and will do so.

Ron

**Comment by mshukla1** [comment]
All MLST databases have been updated in February, 2019 and deployed in the annotation pipeline. 

MLST assignments for all public genomes have also been updated.
