### ISSUE TITLE
CLI: p3-get-contig-data giving errors

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2209]
I tried to search for contigs using multiple each criteria, all failed. 

mshukla:~> p3-get-contig-data -e genome_id,83332.12 -a genome_id,accession
Invalid object Getopt::Long::Descriptive::Opts::__OPT__::1=HASH(0x7fd139c596b0). at /Applications/PATRIC.app/deployment/lib/P3Utils.pm line 655.
mshukla:~> p3-get-contig-data --eq genome_id,83332.12 -a genome_id,accession
Invalid object Getopt::Long::Descriptive::Opts::__OPT__::1=HASH(0x7ff798cc74a0). at /Applications/PATRIC.app/deployment/lib/P3Utils.pm line 655.
mshukla:~> p3-get-contig-data --eq genome_id,83332.12                       
Invalid object Getopt::Long::Descriptive::Opts::__OPT__::1=HASH(0x7fea8cca5698). at /Applications/PATRIC.app/deployment/lib/P3Utils.pm line 655.
mshukla:~> p3-get-contig-data --keyword 83332.12
Invalid object Getopt::Long::Descriptive::Opts::__OPT__::1=HASH(0x7fe7db526ad0). at /Applications/PATRIC.app/deployment/lib/P3Utils.pm line 655.

**Comment by olsonanl** [comment]
p3-get-contig-data has been replaced with p3-get-genome-contigs; it does not show the option error.
