### ISSUE TITLE
Source id hyperlink broken in specialty genes landing page for private genome

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#221]
On the landing page for my private genome, I clicked on the ARDB which took me to specialty genes landing page:
![screen shot 2015-06-04 at 4 06 11 pm](https://cloud.githubusercontent.com/assets/11475316/7993362/a377a9c6-0ad3-11e5-9b39-2ff7167d3693.png)
When I click on the source id for the gene, it takes me to an error page
![screen shot 2015-06-04 at 4 06 48 pm](https://cloud.githubusercontent.com/assets/11475316/7993375/bdbe535c-0ad3-11e5-8d8c-c9cbc4c6ca13.png)

**Comment by hyoo** [comment]
fixed and available on beta.
