### ISSUE TITLE
metadata cleanup idea

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2214]
I am currently looking at this genome. 
The metadata says that it was assembled with Illumina, but SRA says MinION.  
The assembly method is unicycler, which I believe is a long read assembler.   
If many mistakes like this exist, we should consider looking for incongruous assembler/platform pairs, or try pulling the platform from SRA and double checking
 
https://www.patricbrc.org/view/GenomeList/?keyword(%22SAMN09237643%22)

**Comment by dawenx** [comment]
I'm not sure whether opening a ticket here is the best approach for a discussion like this. maybe we should discuss this in data meeting first, then come up with concrete items so that we can assign them to different people, just my 2-cent. @mshukla1 please review.

**Comment by mshukla1** [comment]
we get sequencing platform, assembly method, and sequence coverage information straight out of the GenBank records or metadata files curated by us from publications. In either case, this is as provided by the original submitter, which may help identify source of poor assemblies at some point in future.  We have never applied any additional review or curation for these fields.  

I understand that some of these information can be incorrect or inconsistent. However, getting it from SRA might not help much, as that is also provided by original submitter and would have similar errors.

Besides, I am not sure how much value add it would be for the amount of curation  efforts and if it is of any further use to us or other users. 

Let me know if you disagree or have some special use case in mind. 

-Maulik
