### ISSUE TITLE
Bad sharing data, can't fix

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2215]
My workspace /olson@patricbrc.org/test  has a sharing value of "undefined" for brettin. The sharing editor crashes on this.

![image](https://user-images.githubusercontent.com/2152226/53845205-e35cb680-3f6d-11e9-94f7-b14fe22d9096.png)

![image](https://user-images.githubusercontent.com/2152226/53845161-c1633400-3f6d-11e9-9787-ea3e5a857510.png)

**Comment by nconrad** [comment]
@olsonanl so, I can address this, but it looks like this may be from that workspace "." corrupted data issue that was fixed a long time ago?

```
[
    [
        "brettin@patricbrc",
        {
            "org": "a"
        }
    ],
    [
        "ARWattam@patricbrc.org",
        "r"
    ],
    [
        "mshukla@patricbrc.org",
        "r"
    ],
    [
        "global_permission",
        "n"
    ]
]
```

**Comment by olsonanl** [comment]
Could be ..  looks like it. the GUI shouldn't' crash tho


________________________________

**Comment by nconrad** [comment]
*stares*.  That's not "crashing".  It's just "not working" because the service isn't returning what it should, which is a string with "a", "r", "n", "w".  The service should return valid data.  :)

**Comment by olsonanl** [comment]
tomato tomahto, or


Postel's law.


________________________________

**Comment by nconrad** [comment]
<img width="717" alt="Screen Shot 2019-03-18 at 12 38 52 PM" src="https://user-images.githubusercontent.com/1194246/55240162-368cf680-5206-11e9-92a2-31e93fa4d06b.png">
