### ISSUE TITLE
Phylogenetic tree job - tree icon view in upper right (not in green bar) does not work

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2217]
I get several user complaints about this, as they click on it and it goes nowhere.
<img width="1074" alt="screen shot 2019-03-08 at 10 56 59 am" src="https://user-images.githubusercontent.com/11475316/54021670-f9968c80-4190-11e9-9847-e88ea3fee93a.png">
<img width="1440" alt="screen shot 2019-03-08 at 10 57 44 am" src="https://user-images.githubusercontent.com/11475316/54021710-0adf9900-4191-11e9-96b6-e8b71daceaeb.png">

**Comment by mshukla1** [comment]
This seems to be working now for my trees after the latest fix by @dawenx. 

@ARWattam Can you please verify it is working for you?

**Comment by dawenx** [comment]
this duplicates #2197 and the fixed was deployed to alpha a while ago. @hyoo do you know when it was deployed to production? before or after 03/07?

**Comment by dawenx** [comment]
close this ticket as the fix for #2197 is on production. @ARWattam please re-open this if needed and provide an example.
