### ISSUE TITLE
Harry: No feature core data for shared genome

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2219]
Aaron Best shared this genome with me.  None of the data from the feature core will load.  This is true of ~100 other genomes that he sent me. 

![image](https://user-images.githubusercontent.com/7661533/54358114-9643a900-462d-11e9-8c18-77d9f8ade163.png)

here are contigs for this genome.  You can see these:
![image](https://user-images.githubusercontent.com/7661533/54358216-c9863800-462d-11e9-95b5-2c124fcba32d.png)

**Comment by mshukla1** [comment]
I checked the database. It seems update operation did not complete as expected.

I have re-shared these genomes with you. You should be able too see them now.

@harry, can you check the Solr log and see if there were any errors?

-Maulik



On Mar 14, 2019, at 7:50 AM, jimdavis1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Aaron Best shared this genome with me. None of the data from the feature core will load. This is true of ~100 other genomes that he sent me.

[image]<https://user-images.githubusercontent.com/7661533/54358114-9643a900-462d-11e9-8c18-77d9f8ade163.png>

here are contigs for this genome. You can see these:
[image]<https://user-images.githubusercontent.com/7661533/54358216-c9863800-462d-11e9-95b5-2c124fcba32d.png>
