### ISSUE TITLE
Another error on specialty page for private genome-error when click on hyperlink to gene page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#222]
I clicked on the peg id from the specialty gene page for my private genome
![screen shot 2015-06-04 at 4 06 11 pm](https://cloud.githubusercontent.com/assets/11475316/7993402/f595d0fc-0ad3-11e5-86a0-588c38c7bd1e.png)

and it returned this:
![screen shot 2015-06-04 at 4 07 41 pm](https://cloud.githubusercontent.com/assets/11475316/7993430/161afe06-0ad4-11e5-8c45-a52ff3e843ae.png)

**Comment by hyoo** [comment]
fixed and available on beta
