### ISSUE TITLE
Sharing private genomes

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2220]
We keep getting queries from the users that they shared their workspace with their collaborators, but they still can't access the private genomes in the shared workspace. 

The problem is that users don't know that they need to share the genomes separately, in addition to sharing workspace. 

I understand that automatically sharing genomes when a workspace is shared is complicated. 

As an intermediate solution, we can show the following message to the users in the workspace sharing widget after they perform sharing action, with link to "My Genomes". 

"Sharing your workspace does not provide access to your private genomes. If you like to share your private genomes, please go to "My Genomes", select the genomes you like to share, and then share them with select users."

<img width="504" alt="Screen Shot 2019-03-18 at 7 59 14 AM" src="https://user-images.githubusercontent.com/1236463/54532303-7249d580-4955-11e9-9d15-06e691e49cbf.png">

**Comment by nconrad** [comment]
@mshukla1 Good plan.  

Maybe this would be effective enough?  Having a popup may be a little obtrusive for some.

![image](https://user-images.githubusercontent.com/1194246/54559508-35e69b80-498e-11e9-9830-993bab26c168.png)

**Comment by mshukla1** [comment]
I was thinking it would be a message in the same share workspace window, after you hit same button
….leading to next action user needs to perform.

In the same window, you can have “OK” or “CLOSE” button, as a way for user to acknowledge that
They have read the instruction.

-Maulik



On Mar 18, 2019, at 2:59 PM, nconrad <notifications@github.com<mailto:notifications@github.com>> wrote:


@mshukla1<https://github.com/mshukla1> Good plan.

Maybe this would be effective enough? Having a popup may be a little obtrusive for some.

[image]<https://user-images.githubusercontent.com/1194246/54559508-35e69b80-498e-11e9-9830-993bab26c168.png>

**Comment by nconrad** [comment]
I understand what you are saying.  @chris-c-thomas and I think we should at least start with this notice strategy because it makes it known what you are doing before you do it and the user doesn't have to deal with an additional step.   It's just cleaner, and not everybody will be sharing genomes, I would think.

**Comment by mshukla1** [comment]
Fine. Something is better than nothing. Can you work on it and get it deployed it on alpha soon?

-M

On Mar 18, 2019, at 3:11 PM, nconrad <notifications@github.com<mailto:notifications@github.com>> wrote:


I understand what you are saying. @chris-c-thomas<https://github.com/chris-c-thomas> and I think we should at least start with this notice strategy because it makes it's it known what you are doing before you do it and the user doesn't have to deal with an additional step. It's just cleaner, and not everybody will be sharing genomes, I would think.

**Comment by nconrad** [comment]
Sure, I just made a PR for it.  It will be an experiment on user behavior.  :) . We could give it a few weeks and go with what you are saying if needed.
