### ISSUE TITLE
Implement compliance with EU GDPR

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#2222]
The new EU GDPR privacy laws require that people must opt in to be on mailing lists, rather than being automatically added.  They must also be able to opt out at any time.  For PATRIC, probably the best way to do this is 

1. Add a field in the user database for an opt-in flag
2. Set all records to false for this field
3. Add a note and checkbox in login box and registration form allowing users to "opt-in" if they would like to receive emails on upcoming workshops, or other important PATRIC news or events
4. Post something on the workspace page and profile that either allows users to opt-in or takes them to login where they can opt in.  Provide a way to "dismiss" this message so that users aren't pestered by it.

**Comment by chris-c-thomas** [comment]
Adding @hyoo for visibility.

**Comment by chris-c-thomas** [comment]
Closing and opening a new ticket, apologies.
