### ISSUE TITLE
tree service UI (on alpha) padding bug

### ISSUE THREAD

**Issue by dawenx** [PATRIC3/patric3_website#2228]
This was introduced when adding codon service. To produce it, choose any genome group and click on '+add'.
<img width="1045" alt="Screen Shot 2019-03-25 at 12 28 13 PM" src="https://user-images.githubusercontent.com/26723038/54936947-e6f2b600-4ef9-11e9-9dbe-a655e23cd7d9.png">

**Comment by dawenx** [comment]
declaimer: this bug was caused by @dawenx and @chris-c-thomas gladly takes the challenge to fix it.

**Comment by chris-c-thomas** [comment]
Initial thoughts are extra padding in the input field but will confirm and fix.

**Comment by chris-c-thomas** [comment]
@dawenx off the top of you head do you know any other forms or menus that this might occur? I feel it might not be an isolated incident.

**Comment by nconrad** [comment]
@chris-c-thomas this shouldn't be an issue in other forms.  But, it is, in part, why we need to migrate to using some single "selectedTable" widget for every form.

**Comment by dawenx** [comment]
@nconrad you have a good point. i was trying to use "selectedTable" initially and i really like the feature to be able to remove a single genome from selection.

it looks like we need to expand selectedTable's functionality if we want to support a case like this: e.g., have a way to show a group of genomes only in a row. the problem here is a user could choose lots of genomes and showing one genome per row could be an issue.

**Comment by nconrad** [comment]
@dawenx Right.  Some minor changes may be needed to support every use case.  But, I don't think it's much, because that widget should already be able to accept data that isn't rendered, like 

```
table.addRow({
    name: "foo group", 
    genomeIDs: [83333.1, 83333.2]
    ...
})
```

or such.

Then, something like 
```
table.getRows().reduce((acc, obj) => [...acc, ...obj.genomeIDs], [])
```
 is all the ids. 
 [I've been writing haskell lately :)]

**Comment by dawenx** [comment]
@chris-c-thomas any progress on this? i can take this issue back on Monday PM if needed. but this should be a good practice for you to try out p3_web bug fixing process. :)

**Comment by dawenx** [comment]
verified on alpha
