### ISSUE TITLE
SRA extensions not working for Metagenomic REad mapping

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2229]
I think that something is wrong when using SRA extensions for metagenomic read mapping.  All of the jobs I submitted failed with the same file that I used for taxonomic classification, with this error message: Errors found in parameter processing:
    Required parameter Input Type (input_type) missing
<img width="1731" alt="Screen Shot 2019-03-26 at 11 48 58 AM" src="https://user-images.githubusercontent.com/11475316/55012281-8d53bf80-4fbd-11e9-8894-707e102f1f6d.png">

**Comment by dawenx** [comment]
we are aware of multiple issues in the back-end, will let you know when this service is ready for testing. thanks! @AllanDickerman

**Comment by dawenx** [comment]
@olsonanl please remove "input_type" from JSON specification as well. can we give this service a push today/tomorrow as we planned to include it in coming release.

**Comment by olsonanl** [comment]
This is fixed with an update to the backend.
