### ISSUE TITLE
Another error on specialty gene landing page for private genome

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#223]
From the landing page I clicked on the source (ARDB)
![screen shot 2015-06-04 at 4 06 11 pm](https://cloud.githubusercontent.com/assets/11475316/7993474/53da2640-0ad4-11e5-88aa-8a69968dfa2f.png)

and it went somewhere very strange:
![screen shot 2015-06-04 at 4 10 17 pm](https://cloud.githubusercontent.com/assets/11475316/7993486/5fb7bee6-0ad4-11e5-82f6-0db523ae4d0a.png)

**Comment by hyoo** [comment]
fixed and available on beta.
