### ISSUE TITLE
Variation service missing amino acid information

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2230]
[DH5alpha SNP analysis.xlsx](https://github.com/PATRIC3/patric3_website/files/3014686/DH5alpha.SNP.analysis.xlsx)
This large analysis has many read files compared to the reference, and 
while I can see in the downloadable file that there are synonymous and 
nonsynonymous changes, the amino acid columns do not show any differences 
(and they should for the nonsynonymous). Also, I am concerned that all of 
the snpEff_impact show MODIFIER. It looks to me like some of the snps 
should result in a frameshifts, and yet both the Frameshift and snpEff_type 
are empty. I fear that something has changed in PATRIC that has impacted 
one of my favorite services.

**Comment by dawenx** [comment]
@mshukla1 I don't have insight on this issue, can you assign it to relevant people?

**Comment by chmao1** [comment]
Fixed and available in production.
