### ISSUE TITLE
Proteome Comparison Too Many Genomes Error

### ISSUE THREAD

**Issue by Tinyman392** [PATRIC3/patric3_website#2231]
So when trying to add a genome group with exactly 9 genomes, it shows no error and does nothing (no error).  An error should be displayed, text should also reflect this as it says select up to 9 genomes for comparison, should probably say 8.

**Comment by dawenx** [comment]
I did not implement this, but I checked the codes, yeah, looks like the logic in UI supports up to 8 genomes. Do you want me to update the text on the UI? Or change the logic to support up to 9 genomes. @Tinyman392

**Comment by dawenx** [comment]
@chmao1 can you comment? thanks!

**Comment by ARWattam** [comment]
I will comment.  I think that you should update the text.  It is confusing, and even I make the mistake when I read it.

**Comment by ARWattam** [comment]
Actually, Chunhong and I just looked at this.  You can have 9 comparison genomes to one reference when you add them individually.  This is actually a bug where the genome group with 8 genomes is accepted, and one with 9 genomes isn’t.  So that is what needs to be changed.  Not the text.

**Comment by chmao1** [comment]
Fixed and will be available in the next build.

**Comment by chmao1** [comment]
The fix is now available in production.
