### ISSUE TITLE
Create Taxonomic Classification Service for metagenomes

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#2233]
Build and validate a Kraken database for a representative set of PATRIC genomes. Kraken is a rapid k-mer-based tool for identifying the taxonomy for reads in a metagenome.

See Project: https://github.com/PATRIC3/patric3_website/projects/4

**Comment by mshukla1** [comment]
Taxionomic classification service has been released in March. Hence closing the ticket.
