### ISSUE TITLE
Need to update user guides

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#2238]
- [x] Add Results section to Genome Assembly Service
- [x] Add more detailed description and screenshot of html output file to Genome Annotation Service
- [x] Add visualization information to Proteome Comparison Service user guide
- [x] Add Results section to BLAST Service
- [x] Add Results section to Similar Genome Finder Service
- [x] Add Results section to Variation Analysis Service
- [x] Add Results section to Tn-Seq Analysis Service
- [x] Add Results section to Phylogenetic Tree Building Service
- [x] Add Results section to Expression Data Import Service
- [x] Add Results section to Protein Family Sorter Service
- [x] Add Results section to Proteome Comparison Service
- [x] Add Results section to Comparative Pathway Service
- [x] Add Results section to Model Reconstruction Service
- [x] Add Results section to ID Mapper Service
- [x] Add additional information to Results section of RNA-Seq Analysis Service

**Comment by chris-c-thomas** [comment]
@rkenyon what do you mean by the first one? Which title?

**Comment by nconrad** [comment]
@rkenyon I have a ticket that is dependent on these updates. https://github.com/PATRIC3/patric3_website/issues/2243

I started to link the "GUIDE" button in the job result viewer to the "Results" anchor for each service, but quickly noticed the assembly results section was missing and the titles aren't consistent.  
Ex: 
https://docs.patricbrc.org/user_guides/services/genome_annotation_service.html#results 
vs 
https://docs.patricbrc.org/user_guides/services/comprehensive_genome_analysis_service.html#output-results

Just let me know when you are done with this update, and I'll add the links on the p3_web side?  I know everybody (read: Maulik) will be very happy when I can close my ticket.  

Keep in mind we can never change the links/title again. :)

**Comment by rkenyon** [comment]
@nconrad  all of the service user guides now use ## Output Results for that section of the guide. So, please update the links as needed. 

I promise to never update link titles again...hopefully.

**Comment by rkenyon** [comment]
All pending user guide updates complete
