### ISSUE TITLE
Proteome Comparison download table needs to be sorted on second column (ref_genome_gene)

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2239]
I'm not sure what the order is determined by, but its all over the place and it should be sorted by the gene order in the reference genome

**Comment by mshukla1** [comment]
@chmao1 

In order to get desired order, you need to sort the table on 

ref_genome_contig (i.e. accession) + ref_genome_start

-M

**Comment by chmao1** [comment]
Fixed and made a pull request

**Comment by chmao1** [comment]
The fix is now available in production.
