### ISSUE TITLE
Unable to get aa sequence for gene in private genome

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#225]
I went to a random gene landing page and clicked on the aa sequence, and only a blank popup loaded
![screen shot 2015-06-04 at 4 20 57 pm](https://cloud.githubusercontent.com/assets/11475316/7993676/cf26e364-0ad5-11e5-94dd-caee292110e8.png)

**Comment by hyoo** [comment]
fixed and available on beta.

**Comment by hyoo** [comment]
#228

**Comment by mshukla1** [comment]
resolved.
