### ISSUE TITLE
5S rRNA is lost in E.coli K-12 genome

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2250]
For some reason, we are calling it a MISC RNA.
![image](https://user-images.githubusercontent.com/7661533/56296677-99322d80-60f4-11e9-87d5-d68a0d9dfd96.png)

![image](https://user-images.githubusercontent.com/7661533/56296703-a4855900-60f4-11e9-8500-43cf9ee50841.png)

**Comment by mshukla1** [comment]
You are looking at two different RNAs right next to each other. 

fig|511145.12.rna.4 is Large Subunit Ribosomal RNA; lsuRNA; LSU rRNA, which is shown as such in genome browser as well. 

fig|511145.12.rna.5 is misc_rna, with no additional description. 

<img width="1365" alt="Screen Shot 2019-04-17 at 1 25 28 PM" src="https://user-images.githubusercontent.com/1236463/56311869-96473500-6114-11e9-8adc-f97c73cddb8c.png">
<img width="670" alt="Screen Shot 2019-04-17 at 1 25 53 PM" src="https://user-images.githubusercontent.com/1236463/56311870-96473500-6114-11e9-9bad-60672b7618c1.png">
<img width="203" alt="Screen Shot 2019-04-17 at 1 26 01 PM" src="https://user-images.githubusercontent.com/1236463/56311871-96473500-6114-11e9-9823-30a0fbf11c79.png">
