### ISSUE TITLE
Job counter does not reflect actual job status

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2251]
A user (Philippe Chlenski) reports the following:
"When I look at the jobs page, the top right bar displays something like the 
following:
1 queued; 0 running; 149 completed; 0 failed.
In reality, I have 5 failed jobs. These display if I click on '0 failed'."

I have seen this as well, and it has been reported by other users.

**Comment by mshukla1** [comment]
#2235 duplicate.
