### ISSUE TITLE
User reports missing reference genome that should be included in PATRIC

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2253]
User says:
"I noticed that the genome of an archaea of interest to me is missing on
PATRIC. The organism is Pyrodictium delaneyi strain Su06 (Refseq
NZ_CP013011.1) and its genome is available on NCBI."

In the immortal words of Pokemon, "Maulik Shukla, I choose you!"

**Comment by mshukla1** [comment]
I have added the genomes to the database.
