### ISSUE TITLE
User requests that important genome sequenced in 2016 be added to PaTRIC

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2255]
She says:
"This is a public genome of a multi drug resistant CDC sequenced isolate,
with the accession number -NZ_MPCF00000000.1.

Can this genome please be added to the Patric database?
Relevant information attached
The following links have the relevant info regarding sequence information.
CDC AR Bank# 0040 Information with Sequence Accession#
<https://wwwn.cdc.gov/ARIsolateBank/Panel/IsolateDetail?IsolateID=40>
NCBI Assembly page for AR-0040
<https://www.ncbi.nlm.nih.gov/assembly/GCF_001875105.1/>
NCBI Genome contigs for AR_0040
<https://www.ncbi.nlm.nih.gov/nuccore/?term=SAMN04014881>"

**Comment by mshukla1** [comment]
This genome is already available in PATRIC:
Klebsiella pneumoniae strain AR_0040
https://patricbrc.org/view/Genome/573.7031
