### ISSUE TITLE
From genome browser, click on gene, from pop up window, click on Transcriptomics data

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#226]
My private genome-went to genome browser-selected one gene-popup window pops up, click on the choice for Transcriptomics data and see the below (and yes, I know it shouldn't return anything, but I didn't expect this!)
![screen shot 2015-06-04 at 4 22 47 pm](https://cloud.githubusercontent.com/assets/11475316/7993741/34267978-0ad6-11e5-86f6-8c18fdcb2935.png)

**Comment by hyoo** [comment]
it will take some time to hide those links from the popup, but I have address the page error, so it will display pages without data for now.

#227

**Comment by mshukla1** [comment]
Page shows zero results instead of showing errors. I think this is fine for now.
