### ISSUE TITLE
Visual change when in sudo mode on website

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2261]
It would be useful to make a visual change on the PATRIC site when one is logged in as an admin and sudo'd to a different user. Perhaps change the people icon at the top right to red.

**Comment by ARWattam** [comment]
I think that is an excellent idea.  Could prevent some embarrassing job submissions.  I personally only use safari when I am a superuser to prevent those kind of accidents.

**Comment by mshukla1** [comment]
I second the suggestion. I keep switching accounts when answering user requests, and it is easy to
Loose track of when I am logged in as super user and when not.
