### ISSUE TITLE
enhancement feature page

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2269]
It would be nice if we could add to a feature group from the feature view page:
![image](https://user-images.githubusercontent.com/7661533/57318034-09fab300-70bf-11e9-917a-d601d0b92049.png)

**Comment by dmachi** [comment]
Is this not what the "Add to Group" does or are you saying that isn't working?

**Comment by mshukla1** [comment]
there is an add to group button and it is working.
