### ISSUE TITLE
Pop-up window from genome browser, gene selected, correlated genes return error

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#227]
Started here from my private genome
![screen shot 2015-06-04 at 4 25 20 pm](https://cloud.githubusercontent.com/assets/11475316/7993765/7581e128-0ad6-11e5-9a23-b63d31329049.png)

![screen shot 2015-06-04 at 4 25 08 pm](https://cloud.githubusercontent.com/assets/11475316/7993760/64bf6a40-0ad6-11e5-90eb-89b7807edbef.png)

When I clicked on correlated genes I got this

**Comment by ARWattam** [comment]
Reverse the text with the images above and you'll have the situation.

**Comment by mshukla1** [comment]
Ok, now it is showing page with zero results, instead of showing errors, which I think is fine for now. 

Even for public genome, if it doesn't have any transcriptomics data, you will not see any results on transcriptomics or  correlated genes tabs.

I think this issue is resolved for now.
