### ISSUE TITLE
Update job scheduler

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#2271]
To improve performance

**Comment by rkenyon** [comment]
Bob testing it now.  Trying using old jobs against new scheduler.  Still doing some tuning by service.  Replaces the application service. Switching from Awe scheduler to RDB that keeps up with job status and history (minus PATRIC staff). Try to deploy week of May 27 at least in Beta?

**Comment by olsonanl** [comment]
This is complete and has been in production for over a year.
