### ISSUE TITLE
Create new Assembly Service to replace ARAST

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#2274]
A service that uses the latest tools and is more stable, and faster if possible.

**Comment by rkenyon** [comment]
Need to include Dawen (and others?) in the thread.  For now, Bob can use current UI form to run the service.  Allan has been providing the CL script.  Need to give some thought how we handle mixed long and short reads, in terms of deducing read type, and trade offs between methods.

**Comment by olsonanl** [comment]
This is all in production now.
