### ISSUE TITLE
Phylogeny tab suggestion

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2277]
I clicked on "All bacteria" from the drop down on the front page and then clicked the phylogenetic tree tab.  This never loaded.  After talking to harry, i learned that we have no master tree, so this tab should not be be available as an option for any input selection that is larger than a genus-level selection. 

![image](https://user-images.githubusercontent.com/7661533/57466617-a3a09c80-7246-11e9-8eb1-81cd13bd9367.png)

**Comment by mshukla1** [comment]
I am not sure if it is possible to completely hide the tab without major changes. 

It might be easier to display a clear and concise message when tree is not available. i.e. Trees are constructed at the bacterial order levels and, hence,  and not available for higher taxonomic levels. 

Another an d probably better option would be to list all the orders with tree as a dropdown and let user select one to display. In that case, we should display the first one in the list as default.

**Comment by mshukla1** [comment]
#1264 duplicate. closing this one. keeping other open.

**Comment by nconrad** [comment]
I forgot to comment on this.  Jim and I discussed this, and we think a large (or all) the confusion was that the API request was slow, and so he never saw any message at all.

I agree that a detailed message is better than removing the tab anyhow.
