### ISSUE TITLE
NT sequence from gene landing page in private genome doesn't load

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#228]
see the screenshot
![screen shot 2015-06-04 at 4 30 19 pm](https://cloud.githubusercontent.com/assets/11475316/7993857/164266fa-0ad7-11e5-9266-97a1ef22a959.png)

**Comment by hyoo** [comment]
fixed and available on beta.

**Comment by mshukla1** [comment]
checked, resolved.
