### ISSUE TITLE
Not able to log in to Model SEED using PATRIC credentials

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#2286]
I ran a Model Reconstruction job and when I chose the View option, it takes me to the ModelSEED site where I can log in as a RAST or PATRIC user.  I tried my PATRIC login credentials, but just get a forever spinning login: 
<img width="684" alt="Screen Shot 2019-06-07 at 12 35 42 PM" src="https://user-images.githubusercontent.com/3188570/59119642-4a995680-8921-11e9-811c-9ca03a6f1b02.png">

**Comment by nconrad** [comment]
I looked into this and there was a modelseed upgrade that resulted in breaking both modelseed sign-ins.  So, just waiting on the modelseed team to push the fix now.

**Comment by nconrad** [comment]
This should be fixed now (on the ModelSEED side).  @rkenyon would you mind testing and close as needed?

The linkage with '?login=patric' in url originally defaulted the prompt to the PATRIC sign-in, but that seems to have stopped working in chrome.  It still works in firefox/safari.
