### ISSUE TITLE
rna-seq interface

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#2294]
We've decided to deprecate Rockhopper. Dawen can you remove it from the recipe dropdown in the RNA-Seq interface?

**Comment by dawenx** [comment]
yes sir, I will take care of it soon.

@rkenyon @ARWattam Can you update user guide and tutorial as well? Looks like Rockhopper is shown in the screenshot.

**Comment by ARWattam** [comment]
I will change the tutorial by end of August
