### ISSUE TITLE
Genome names are wrapping in the middle of words

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2296]
In the organism info for a genome, if the genome name needs to wrap it's wrapping it in the middle of a word - see attached. It should break on spaces in the name

<img width="987" alt="image" src="https://user-images.githubusercontent.com/2152226/61078080-78246480-a3e5-11e9-922d-8f262a5a407b.png">

**Comment by nconrad** [comment]
Agreed.  Will fix.  Thanks.
