### ISSUE TITLE
SRR upload needed on Metagenomic Binning service GUI

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2299]
All services that deal with fastq files should provide this.

**Comment by dawenx** [comment]
this is not just a UI issue. we have a duplicate ticket (#2017) on this, according to @olsonanl , the back-end of metagenomic binning service does not support SRR.

**Comment by mshukla1** [comment]
This has been added and deployed in alpha.bv-brc. 

https://alpha.bv-brc.org/app/MetagenomicBinning

**Comment by mshukla1** [comment]
Added as part of latest enhancements for bv-brc.
