### ISSUE TITLE
Blue highlight boxes not appearing when Pathway Summary tool is clicked

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#23]
Generally, when the genes are listed in a table, and you click the pathway summary button, then you click the name of a particular pathway, when the pathway shows up, the genes from the original list are highlighted blue.  They are green right now.

**Comment by hyoo** [comment]
In current production site, all boxes are green after following your workflow. I guess this feature is omitted when we migrated to solr. I will work on it later to implement this.

**Comment by mshukla1** [comment]
Checked, it is working as expected now.
