### ISSUE TITLE
docs nav issue

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#2301]
1) go to https://docs.patricbrc.org/

2) the nav menu before clicking "Scientific Working Group" is:

![image](https://user-images.githubusercontent.com/1194246/62137181-2287fd00-b2ab-11e9-8b5c-31fa63e14f92.png)

3) after clicking "Scientific Working Group", "Acknowledgements" changes to "Scientific Collaborations":

![image](https://user-images.githubusercontent.com/1194246/62137264-45b2ac80-b2ab-11e9-9b60-c35eb2b05755.png)

**Comment by chris-c-thomas** [comment]
This should no longer be an issue when the docs were restructured. Closing.
