### ISSUE TITLE
links to KEGG and FIGFAM in gene landing page from private genome rewrite page...should open new page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#231]
Started here
![screen shot 2015-06-04 at 4 38 12 pm](https://cloud.githubusercontent.com/assets/11475316/7994009/3126160a-0ad8-11e5-9386-ec91e714b540.png)

and when I clicked on FIGfam or Kegg it overwrote the page.  I hate that.  Just saying.

**Comment by hyoo** [comment]
I thought the rule underlying is that open a new window if it goes outside PATRIC, replace current page if it is PATRIC page. 

But, as we discussed, we can change it if it disrupts the workflow.

**Comment by mshukla1** [comment]
Harry, please open both kegg and figfam links in a new tab. 

-Maulik

**Comment by hyoo** [comment]
fixed and available on beta.
