### ISSUE TITLE
Subsystem heat map not loading 

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2311]
I went to the landing page for Brucella ovis, which includes 15 genomes.  I click on the Subsystems tab.  
Then I clicked on Subsystems and, when that loaded, clicked on Histidine Biosynthesis.  When I clicked on the heatmap view, it never loaded:
https://patricbrc.org/view/SubSystemMap/?taxon_id=236&genome_ids=1293922.3,1293913.3,1293916.3,1293919.3,1293920.3,1198678.3,236.3,1169230.3,1169231.3,1169232.3,1293912.3,1293914.3,1293915.3,1293917.3,1293918.3,1293921.3,444178.3&subsystem_id=Histidine_Biosynthesis&genome_count=16&role_count=12&gene_count=208&genome_name=Brucella%20ovis%20IntaBari-2009-88-4&display_reference_genomes=false

<img width="2554" alt="Screen Shot 2019-09-03 at 4 11 17 PM" src="https://user-images.githubusercontent.com/11475316/64205471-1244de00-ce66-11e9-8a0e-f506d1d20e0c.png">

Here is some good news...if I go through the Subsystems Overview diagram and then navigate to Metabolism and then to Histidine Biosynthesis, I do get the heatmap view, but when trying to filter on it, for the table, something very strange showed up...a weird filter box.
<img width="2505" alt="Screen Shot 2019-09-03 at 4 19 53 PM" src="https://user-images.githubusercontent.com/11475316/64205842-f3931700-ce66-11e9-99d8-10007b70a8ff.png">

**Comment by mshukla1** [comment]
Not sure what happened there. However, I just tried it and it loaded for me, both, with and without reference genomes.
Screenshots attached.

Can you please try again and see it the problem persists?

[cid:78B967C5-6714-4B7C-B9EB-A41A82CFF039@cels.anl.gov][cid:1D84DDE7-010B-4D82-B9CF-EFD9CCDFFFDF@cels.anl.gov]



On Sep 3, 2019, at 3:22 PM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


I went to the landing page for Brucella ovis, which includes 15 genomes. I click on the Subsystems tab.
Then I clicked on Subsystems and, when that loaded, clicked on Histidine Biosynthesis. When I clicked on the heatmap view, it never loaded:
https://patricbrc.org/view/SubSystemMap/?taxon_id=236&genome_ids=1293922.3,1293913.3,1293916.3,1293919.3,1293920.3,1198678.3,236.3,1169230.3,1169231.3,1169232.3,1293912.3,1293914.3,1293915.3,1293917.3,1293918.3,1293921.3,444178.3&subsystem_id=Histidine_Biosynthesis&genome_count=16&role_count=12&gene_count=208&genome_name=Brucella%20ovis%20IntaBari-2009-88-4&display_reference_genomes=false

[Screen Shot 2019-09-03 at 4 11 17 PM]<https://user-images.githubusercontent.com/11475316/64205471-1244de00-ce66-11e9-8a0e-f506d1d20e0c.png>

Here is some good news...if I go through the Subsystems Overview diagram and then navigate to Metabolism and then to Histidine Biosynthesis, I do get the heatmap view, but when trying to filter on it, for the table, something very strange showed up...a weird filter box.
[Screen Shot 2019-09-03 at 4 19 53 PM]<https://user-images.githubusercontent.com/11475316/64205842-f3931700-ce66-11e9-99d8-10007b70a8ff.png>

**Comment by nconrad** [comment]
Thanks.  I have this (sometimes-hard-to-replicate) issue captured in another ticket here: https://github.com/PATRIC3/patric3_website/issues/2246

This is an issue I've sort of dreaded addressing with the new heatmap...  but, now's the time!

**Comment by ARWattam** [comment]
Just happened again for me, this time with Shigella.
https://patricbrc.org/view/SubSystemMap/?taxon_id=620&genome_ids=300267.13,198214.7,766154.3,300269.12,624.361,300268.11&subsystem_id=Arsenic_resistance&genome_count=5&role_count=6&gene_count=40&genome_name=Shigella%20dysenteriae%20Sd197&display_reference_genomes=false

<img width="1665" alt="Screen Shot 2019-09-04 at 3 06 34 PM" src="https://user-images.githubusercontent.com/11475316/64283578-b93c7f00-cf25-11e9-98c1-dc6d1dd90d5b.png">

**Comment by ARWattam** [comment]
It keeps happening to me, so I don't think that its closed!
<img width="1665" alt="Screen Shot 2019-09-04 at 3 06 34 PM" src="https://user-images.githubusercontent.com/11475316/64286339-4d5d1500-cf2b-11e9-8674-f567b84e1044.png">
That is all Shigella

**Comment by mshukla1** [comment]
Again, not sure, what happened there. It worked for me.

I am sure there is a problem, not sure how to reproduce or trace it.

Given we are close to launching new viewer, I think it is better to make sure it doesn't happen with the new viewer.

-Maulik


[cid:8F61DF7C-1376-4719-9233-B96D9D840EAE@cels.anl.gov]



On Sep 4, 2019, at 2:07 PM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


Just happened again for me, this time with Shigella.
https://patricbrc.org/view/SubSystemMap/?taxon_id=620&genome_ids=300267.13,198214.7,766154.3,300269.12,624.361,300268.11&subsystem_id=Arsenic_resistance&genome_count=5&role_count=6&gene_count=40&genome_name=Shigella%20dysenteriae%20Sd197&display_reference_genomes=false

[Screen Shot 2019-09-04 at 3 06 34 PM]<https://user-images.githubusercontent.com/11475316/64283578-b93c7f00-cf25-11e9-98c1-dc6d1dd90d5b.png>
