### ISSUE TITLE
return type in new app service

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#2317]
For the new app service API, the second value returned by `enumerate_tasks_filtered` (the total number of records) is a `string` instead of `int`.

![image](https://user-images.githubusercontent.com/1194246/67135674-b0f08880-f1e1-11e9-8b1d-5e01ffaadfaa.png)

**Comment by olsonanl** [comment]
fixed

**Comment by nconrad** [comment]
Confirmed.  Thanks.

**Comment by nconrad** [comment]
Ahh, same issue with `query_app_summary`, just so you know.

![image](https://user-images.githubusercontent.com/1194246/68061623-cda5b980-fcd3-11e9-9640-a835be52a0f4.png)

**Comment by olsonanl** [comment]
see if that fixed it.
________________________________

**Comment by nconrad** [comment]
Looks good.  Closing.
