### ISSUE TITLE
Feature Overview: duplicate EC numbers displayed

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2318]
On the feature overview page, the same EC number if displayed multiple times. 

I believe we get EC numbers from the pathway table and it needs to be converted into unique list 
before being displayed. 

https://patricbrc.org/view/Feature/PATRIC.83332.12.NC_000962.CDS.2052.3260.fwd#view_tab=overview

**Comment by mshukla1** [comment]
The same goes for list of pathways as well, they are also duplicated. Need to display as a non-redundant list. 

-Maulik

**Comment by chris-c-thomas** [comment]
https://github.com/PATRIC3/p3_web/pull/940

**Comment by chris-c-thomas** [comment]
On production. Closing.
