### ISSUE TITLE
From genome landing page, click on proteins with FIGFam assignment and table that pops up does not show FIGFam id

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#232]
The subject says it all

**Comment by mshukla1** [comment]
Harry, as we discussed before, please add FIGFAM_ID as a column in the feature table. 

-Maulik

**Comment by hyoo** [comment]
I have added FIGfam ID column on feature list and feature finder. 

If we need to make it consistent, we need check what other tables are relevant and add column in each table. (for example, Transcriptomics Feature page)

**Comment by mshukla1** [comment]
Thanks, Harry. You da man!
