### ISSUE TITLE
File selection from apps: show hidden / all files not intuitive 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2320]
User trying to select contigs generated by assembly job in other apps, i.e. annotation or similar genome finder. 

The workspace file selection widget by default shows only files and folders, while the job results and corresponding result folders are hidden. 

Users need to use the check the box, "Show all files and folders" to see job result folders and then select contig files in them, which is non-intuitive.   

<img width="831" alt="Screen Shot 2019-10-23 at 11 25 04 AM" src="https://user-images.githubusercontent.com/1236463/67413965-cd951380-f587-11e9-9874-43cb0b69ad1f.png">

**Comment by nconrad** [comment]
Solution: use application folders (typed job folders) instead of hidden folders.  We could even have 
just have a single type--a "Job Result" folder.

I could instead make all folders visible all the time?

**Comment by mshukla1** [comment]
@nconrad yes, make all folders visible by default time by making the show hidden files box checked b y default. 

Please find and deploy on alpha ASAP.

**Comment by nconrad** [comment]
The (short-term) fix I deployed to alpha automatically shows hidden folders/files when selecting contigs.
