### ISSUE TITLE
docs nav hover color

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#2323]
- It's fairly odd that there is no indication of hovering on the top-level nav items in the revised sphinx styling.  

![image](https://user-images.githubusercontent.com/1194246/68724928-7c72b100-0582-11ea-9629-378ba0339689.png)

Ideally, there'd also be the same logo, if not also the same blue bar across the top.

**Comment by mshukla1** [comment]
@chris-c-thomas , please address this week while you are already fixing other issues on the doc site.

**Comment by chris-c-thomas** [comment]
I've added hover styles to the vertical navigation menu and it's on production docs. Closing.
