### ISSUE TITLE
Jobs list: incorrect start and end time when job is queued. 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2327]
The start and end time in the right hand panel are incorrect and misleading when the job is still queued. This should be corrected soon. 

<img width="260" alt="Screen Shot 2019-11-20 at 7 29 32 PM" src="https://user-images.githubusercontent.com/1236463/69245805-88d3bb00-0bcd-11ea-8899-d4a030dcf2f3.png">

**Comment by nconrad** [comment]
This is what the old app service was returning.  Bob already fixed with the new app service:

![image](https://user-images.githubusercontent.com/1194246/69262670-82235480-0b89-11ea-9ab3-d542fb06b015.png)

**Comment by nconrad** [comment]
....although it seems there is no start time until the job finished, @olsonanl?
