### ISSUE TITLE
Need ability to run multiple fastq files to metagenomic binning

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2328]
Many of our other services have this, and we need to add it into metgenomic binning.  Sometimes multiple lanes of the same sample are run on a sequencing machine, and users would like to combine these to increase the coverage.  Would that break the service (I seem to remember that it was size senitive).

**Comment by mshukla1** [comment]
added as part of the latest enhancements for bv-brc. 

https://alpha.bv-brc.org/app/MetagenomicBinning
