### ISSUE TITLE
Human homlog link goes to weird page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#233]
From this page (the landing page for my private genome):
![screen shot 2015-06-04 at 4 46 38 pm](https://cloud.githubusercontent.com/assets/11475316/7994186/6e46dd2a-0ad9-11e5-9c61-75f6937ecef5.png)

I click on Human as the source and it take me to an assembly
![screen shot 2015-06-04 at 4 48 11 pm](https://cloud.githubusercontent.com/assets/11475316/7994215/933d28c8-0ad9-11e5-9d82-6a3a9e51e725.png)

**Comment by hyoo** [comment]
I think that was intended. Maulik, do you remember the reason?

**Comment by mshukla1** [comment]
Yes, it is intended. IT is the home page for the annotation of reference human genome at NCBI. Not a bug. 

-Maulik
