### ISSUE TITLE
Job list: change columns displayed

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2338]
In the Jobs List: 

Now that we have the clean[er] job ids, we should them to be displayed in the default view. 
This will save us from checking the box to show job id, every time we want to search for a user job by id while responding to user requests. I think it will be useful to the users as well. 

Please also change the default column order as shown in the screenshot below. 

<img width="1347" alt="Screen Shot 2020-01-14 at 10 19 02 AM" src="https://user-images.githubusercontent.com/1236463/72361592-5a4afb80-36b7-11ea-938f-d58dcc46bc99.png">

**Comment by chris-c-thomas** [comment]
@mshukla1 just to clarify it should be sorted by descending ID by default and with the columns in that order?

**Comment by mshukla1** [comment]
Yes, you can sort by descending job id.



On Jan 21, 2020, at 9:50 AM, Chris Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


@mshukla1<https://github.com/mshukla1> just to clarify it should be sorted by descending ID by default and with the columns in that order?

**Comment by chris-c-thomas** [comment]
![Screenshot_2020-01-21 PATRIC Jobs](https://user-images.githubusercontent.com/22353987/72820885-4eba8000-3c35-11ea-871f-1c1244ba4572.png)

Updates committed for next PR.

In retrospect, keeping the default submit time order since that's essentially the same thing as job id sorting.

**Comment by mshukla1** [comment]
Yes, job id or submission date, either would work.



On Jan 21, 2020, at 10:06 AM, Chris Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


[Screenshot_2020-01-21 PATRIC Jobs]<https://user-images.githubusercontent.com/22353987/72820885-4eba8000-3c35-11ea-871f-1c1244ba4572.png>

Updates committed for next PR.

In retrospect, keeping the default submit time order since that's essentially the same thing as job id sorting.

**Comment by nconrad** [comment]
@chris-c-thomas Related to this, since we are going to be displaying the ids, sorting that column would currently do a string sort (since the ids are returned as strings).  They used to be hashes, and so this behavior was reasonable.  Can you look into sorting by number?

![image](https://user-images.githubusercontent.com/1194246/72833939-74538380-3c4d-11ea-8244-014bebb9b6e0.png)

**Comment by nconrad** [comment]
@chris-c-thomas  Also, it should be safe to make the default width of that column a little smaller now.

**Comment by chris-c-thomas** [comment]
@nconrad it's set to create equal width columns that span the entire browser page.

**Comment by chris-c-thomas** [comment]
On production. Closing.
