### ISSUE TITLE
TTD link doesn't open up anything

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#234]
From the same landing page for my private genome
![screen shot 2015-06-04 at 4 46 38 pm](https://cloud.githubusercontent.com/assets/11475316/7994252/df12898c-0ad9-11e5-8128-d12c7d82a49b.png)

I click on the TDD link, and nothing ever comes up...well, eventually this does
![screen shot 2015-06-04 at 4 51 21 pm](https://cloud.githubusercontent.com/assets/11475316/7994272/f876ed8c-0ad9-11e5-8a5d-ee34dbdd7409.png)

**Comment by hyoo** [comment]
It seems like TDD site is down. I already changed it to http. http://bidd.nus.edu.sg/

**Comment by mshukla1** [comment]
Links to the individual target pages at TTD are working. However, link to the TTD home is not working, because the page is not reachable. 

Harry,  please change the link to: http://bidd.nus.edu.sg/group/cjttd/

**Comment by hyoo** [comment]
This is specific to outdated website.
