### ISSUE TITLE
DrugBank hyperlink didn't return anything, either

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#235]
Starting in the same place
![screen shot 2015-06-04 at 4 46 38 pm](https://cloud.githubusercontent.com/assets/11475316/7994309/4e0931e2-0ada-11e5-8fae-0d7d1dce5cca.png)

Clicked DrugBank and the link never loaded.

**Comment by hyoo** [comment]
It seems like DrugBank is down.

**Comment by mshukla1** [comment]
Drugbank website structure has changed completely. Need to revisit it after the release.

**Comment by mshukla1** [comment]
Duplicate #99

**Comment by hyoo** [comment]
This is specific to outdated website. new website has a correct link
