### ISSUE TITLE
Numbers not appear on outside of circular viewer for private genomes

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2355]
A user has complained about this for his particular genomes, and when I reannote them in my account, I also see that the numbers are missing.  What are the limits to numbers being portrayed outside the circle?  
<img width="869" alt="Screen Shot 2020-05-05 at 9 17 43 AM" src="https://user-images.githubusercontent.com/11475316/81071026-1b34f600-8eb2-11ea-8660-50eb24cb8eab.png">

**Comment by chmao1** [comment]
Fixed and made a pull request.

**Comment by nconrad** [comment]
@chmao1 Could you push your change? https://github.com/PATRIC3/p3_web/pull/962#issuecomment-624787284

**Comment by nconrad** [comment]
@ARWattam This is on alpha now!  The reloading issue should also be fixed there.

**Comment by nconrad** [comment]
On prod.
