### ISSUE TITLE
Pathway Summary STILL not working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2358]
I have a list of genes in a table.  I click on the Pathway Summary icon in the vertical green bar. It never returns results.  I got another JIRA ticket about this today.  Could we please look into this?  I have told users that we have been working on this for a very long time.

**Comment by chris-c-thomas** [comment]
The pathway summary page is loading for me.

<img width="1091" alt="Screen Shot 2020-05-12 at 10 33 56 AM" src="https://user-images.githubusercontent.com/22353987/81713933-1f29c080-943c-11ea-999c-38cd4b419a3f.png">

**Comment by nconrad** [comment]
Sometimes works, sometimes doesn't.  @hyoo I've looked into this before but made no headway.  Do you have any ideas?  There's a history of related issues.  https://github.com/PATRIC3/patric3_website/issues/1339 and maybe https://github.com/PATRIC3/patric3_website/issues/852

**Comment by nconrad** [comment]
Duplicate.  Closing in favor of #2362
