### ISSUE TITLE
Private genome-Disease tab should have "No Data for this Genome"

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#236]
Instead it gets an error message
![screen shot 2015-06-04 at 4 55 37 pm](https://cloud.githubusercontent.com/assets/11475316/7994342/a61e41f6-0ada-11e5-9a53-a612f0cf6cd1.png)

**Comment by hyoo** [comment]
#239

**Comment by mshukla1** [comment]
disease tab removed for private genomes.
