### ISSUE TITLE
The variation analysis service job fails when using Bowtie2 followed by FreeBayes with data from SRR10961160.  The job completes normally with other pipelines.

### ISSUE THREAD

**Issue by JacobPorter** [PATRIC3/patric3_website#2364]
stderr:
Building a SMALL index
1333334 reads; of these:
  1333334 (100.00%) were paired; of these:
    122323 (9.17%) aligned concordantly 0 times
    1170845 (87.81%) aligned concordantly exactly 1 time
    40166 (3.01%) aligned concordantly >1 times
    ----
    122323 pairs aligned concordantly 0 times; of these:
      24792 (20.27%) aligned discordantly 1 time
    ----
    97531 pairs aligned 0 times concordantly or discordantly; of these:
      195062 mates make up the pairs; of these:
        183864 (94.26%) aligned 0 times
        7308 (3.75%) aligned exactly 1 time
        3890 (1.99%) aligned >1 times
93.11% overall alignment rate
[bam_rmdup_core] processing reference CP002956...
[bam_rmdup_core] processing reference CP002958...
[bam_rmdup_core] processing reference CP002957...
[bam_rmdup_core] 34683 / 1179459 = 0.0294 in library '	'
sh: line 1: 11739 Segmentation fault      (core dumped) bcftools consensus -c chain -f ref.fa var.vcf.gz > consensus
FAILED: bcftools consensus -c chain -f ref.fa var.vcf.gz >consensus at /opt/p3/deployment/plbin/var-map.pl line 398.
	main::run("bcftools consensus -c chain -f ref.fa var.vcf.gz >consensus") called at /opt/p3/deployment/plbin/var-map.pl line 112
	main::compute_consensus() called at /opt/p3/deployment/plbin/var-map.pl line 68

**Comment by JacobPorter** [comment]
This seems related to bcftools since it gives a seg fault.

Successful pipelines include:
Bowtie2 -> SAMtools
BWA-mem -> FreeBayes
BWA-mem -> SAMTools

See job 564424.

**Comment by JacobPorter** [comment]
The input for the variation analysis job was:

```
$VAR2 = {
          'paired_end_libs' => [
                                 {
                                   'read2' => '/jsporter@patricbrc.org/home/Test_Files/SRR10961160_2.fastq',
                                   'read1' => '/jsporter@patricbrc.org/home/Test_Files/SRR10961160_1.fastq'
                                 }
                               ],
          'output_path' => '/jsporter@patricbrc.org/home/Test_Files',
          'mapper' => 'Bowtie2',
          'reference_genome_id' => '1035377.4',
          'output_file' => 'webapp_bcftools_dump_test',
          'caller' => 'FreeBayes'
        };
```

**Comment by JacobPorter** [comment]
The singularity container uses bcftools 1.3, so I reproduced this with bcftools 1.9 from the data files.  I wrote an issue against bcftools for this.

https://github.com/samtools/bcftools/issues/1245

**Comment by olsonanl** [comment]
What needs to be done?

**Comment by JacobPorter** [comment]
This was fixed in bcftools (https://github.com/samtools/bcftools/commit/dc2971c4bd048081cb39007d5cfab23cdd752d10).

We could use an update to samtools/bcftools eventually.

**Comment by olsonanl** [comment]
So it's not yet in a released bcftools, is that correct? How urgent is the update? I worry quite a bit about version skew and problems that the various toolmakers introduce so we may need to have a custom bcftools just for this application.

**Comment by JacobPorter** [comment]
It appears that it has not been released yet.  I don't think that it is urgent.  It looks like a rare problem.  I tried to reproduce the bug with other inputs and pipelines but was unable to reproduce the bug.

**Comment by olsonanl** [comment]
I have updated the production site to the build-74 container which has the updated bcftools.

**Comment by olsonanl** [comment]
This case is in the QA set and has been resolved for some time.
