### ISSUE TITLE
Private genome- Literature tab opens up an error page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#237]
I think it should say something like "No data available for this genome" and instead I got this:
![screen shot 2015-06-04 at 4 56 53 pm](https://cloud.githubusercontent.com/assets/11475316/7994356/cee2c526-0ada-11e5-9164-7e5b2b3b4564.png)

**Comment by mshukla1** [comment]
It looks like server problem at the time. I could not reproduce it with my private genomes. 

Please try again and let me know if you still see the problem.
