### ISSUE TITLE
docs index

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#2378]
I noticed these empty anchor links in the all the video tutorial indexes:

https://docs.patricbrc.org/videos/protein_family_sorter.html

![image](https://user-images.githubusercontent.com/1194246/88599352-2cb11880-d031-11ea-8b90-461f2929aa26.png)

Different, but related issue: I find that having the page anchors in the lefthand index makes it difficult to navigate in general.  I wonder if it's possible to have the table of contents of anchor links on the right side instead.  I've seen many sites with that organization, and think it could help quite a bit with these deeply nested trees.  

Some examples:
![image](https://user-images.githubusercontent.com/1194246/88599252-f5426c00-d030-11ea-8702-0b6717ee4ada.png)

![image](https://user-images.githubusercontent.com/1194246/88599293-0ee3b380-d031-11ea-933f-8cb0e55d6ad4.png)

For our site, many of the anchor links are for small pages, sometimes with redundant sections.

**Comment by chris-c-thomas** [comment]
Fixed on production docs

<img width="888" alt="Screen Shot 2020-08-06 at 11 09 23 AM" src="https://user-images.githubusercontent.com/22353987/89555181-59a1c000-d7d5-11ea-8164-e775cb2d7ecb.png">
