### ISSUE TITLE
wrong translation of rql queries

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#2379]
There is a query like below
```
/?or(eq(genome_name,**),eq(genome_id,**))and(not(reference_genome,%22Reference%22),not(reference_genome,%22Representative%22),%20eq(public,true))&select(genome_id,genome_name,strain,public,owner,reference_genome,taxon_id) ```
```
, which translated to
```
      { q: '((genome_name:** OR genome_id:**) AND (NOT reference_genome AND NOT reference_genome AND object:%20eq(public,true)))',
        fl: 'genome_id,genome_name,strain,public,owner,reference_genome,taxon_id',
        start: '0',
        rows: '24',
        wt: 'json' }
```
and caused an error
```
  error:
   { metadata:
      [ 'error-class',
        'org.apache.solr.common.SolrException',
        'root-error-class',
        'org.apache.solr.common.SolrException' ],
     msg: 'undefined field object',
     code: 400 } }
```
@dmachi would you check why `object` field was introduced? 
@nconrad would you check where this query is sent? I think we better not to use `or(eq(genome_name:**),eq(genome_id,*))` this doesn't make sense.

**Comment by dmachi** [comment]
I’m on vacation this week, but can take a look when I get back. All that said, my guess is that the space in front of eq(public,true) is causing this.

**Comment by hyoo** [comment]
@dmachi thanks for the quick response and suggestion. @nconrad if we can find where this query is fired, can we try to remove the space that Dustin pointed?

**Comment by hyoo** [comment]
yes, the patch fixed the problem on alpha. Thanks for the quick responses.
