### ISSUE TITLE
Genes not loading properly from Pathway tab in private genome

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#238]
Started here for my private genome
![screen shot 2015-06-04 at 5 01 36 pm](https://cloud.githubusercontent.com/assets/11475316/7994470/af061572-0adb-11e5-906f-f9b227b62c21.png)

Then click on the EC tab...started with Glycolysis for some reason
![screen shot 2015-06-04 at 5 01 43 pm](https://cloud.githubusercontent.com/assets/11475316/7994476/bd4ca9ca-0adb-11e5-84cf-f5b918a08f48.png)

Then I clicked on genes and it only showed five of them.  It doesn't make sense to me.
![screen shot 2015-06-04 at 5 01 50 pm](https://cloud.githubusercontent.com/assets/11475316/7994481/c6f4f310-0adb-11e5-9f32-d33d842d580e.png)

**Comment by mshukla1** [comment]
I tried with my private genome and could not reproduce this problem. 

Rebecca, can you please try again and tell us if you still see the problem? If yes, I need to see it Tomorrow.

**Comment by ARWattam** [comment]
Seems to be working
