### ISSUE TITLE
p3_tnseq crash with existing genome

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2385]
If you invoke p3_tnseq and the .fna file for the reference genome is already in place, it crashes

Singularity p3-build-81.sif:/vol/patric3/QA/applications> p3_tnseq --jfile /vol/patric3/QA/applications/App-TnSeq/2020-08-31-22-45-40/jobdesc.json --sstring '{"data_api":"https://p3.theseed.org/api"}' -o /vol/patric3/QA/applications/App-TnSeq/2020-08-31-22-45-40/work
{u'reference_genome_id': u'83332.12', u'protocol': u'sassetti', u'experimental_conditions': [u'control', u'treatment'], u'output_file': u'out.2020-08-31-22-45-40', u'recipe': u'resampling', u'read_files': {u'control': {u'library': u'control', u'replicates': [{u'read1': u'/vol/patric3/QA/applications/App-TnSeq/2020-08-31-22-45-40/stage/U19_73_R1.fastq.gz'}, {u'read1': u'/vol/patric3/QA/applications/App-TnSeq/2020-08-31-22-45-40/stage/U19_74_R1.fastq.gz'}]}, u'treatment': {u'replicates': [{u'read1': u'/vol/patric3/QA/applications/App-TnSeq/2020-08-31-22-45-40/stage/U19_91_R1.fastq.gz'}, {u'read1': u'/vol/patric3/QA/applications/App-TnSeq/2020-08-31-22-45-40/stage/U19_92_R1.fastq.gz'}], u'library': u'treatment'}}, u'output_path': '/vol/patric3/QA/applications/App-TnSeq/2020-08-31-22-45-40/work', u'contrasts': [[u'control', u'treatment']], u'primer': u''}
Traceback (most recent call last):
  File "/opt/p3/deployment/pybin/p3_tnseq.py", line 422, in <module>
    main(server_setup, job_data)
  File "/opt/p3/deployment/pybin/p3_tnseq.py", line 350, in main
    genome_dirs, contig_ids = get_files(job_data, server_setup)
  File "/opt/p3/deployment/pybin/p3_tnseq.py", line 83, in get_files
    _, iterm_ids = get_genome(job_data)
  File "/opt/p3/deployment/pybin/p3_tnseq.py", line 49, in get_genome
    return target_file, contig_ids
UnboundLocalError: local variable 'contig_ids' referenced before assignment

**Comment by JacobPorter** [comment]
I did a pull request to fix this.
https://github.com/PATRIC3/p3_tnseq/pull/3
