### ISSUE TITLE
Download link on private genome landing page gets a weird alert

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#239]
On my private genome landing page:
![screen shot 2015-06-04 at 5 05 25 pm](https://cloud.githubusercontent.com/assets/11475316/7994516/031a9bc4-0adc-11e5-8ee0-94524b2478bd.png)

I clicked on "Download genome data" and got this
![screen shot 2015-06-04 at 5 05 34 pm](https://cloud.githubusercontent.com/assets/11475316/7994533/17cd2dd4-0adc-11e5-9832-0dc5ced7232c.png)

**Comment by mshukla1** [comment]
This is because the download files are not available on the ftp site for private genomes. 
Currently, FTP download is only available for public genomes, because FTP area is open 
for all. Need to discuss how to handle private genomes or disable the download link.

**Comment by hyoo** [comment]
for private genome, we will hide Transcriptomics, Interactions, Disease tabs and genome download link.

**Comment by olsonanl** [comment]
Genome download for those could go to the workspace browser page for the genome. Downloads are available there.

On Jun 5, 2015, at 12:28 PM, Harry Yoo <notifications@github.com<mailto:notifications@github.com>> wrote:


for private genome, we will hide Transcriptomics, Interactions, Disease tabs and genome download link.

**Comment by mshukla1** [comment]
I thought about it, problem is I don't think indexed genome in solr has any pointer back to the original annotation results in the workspace.
