### ISSUE TITLE
Links to Jmol generating error message

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#24]
http://beta.patricbrc.org/portal/portal/patric/Jmol?structureID=4X54

Never loaded

**Comment by hyoo** [comment]
Actually, you're seeing production website. You need to use http://www.beta.patricbrc.org/portal/portal/patric/Jmol?structureID=4X54

www.beta.patricbrc.org not beta.patricbrc.org

There was a bug and I fixed it in this release.

**Comment by ARWattam** [comment]
I had production totally shut down and was using beta.  See attached screenshshot.  The error is at beta.

----- Original Message -----

**Comment by hyoo** [comment]
![jmol_on_beta](https://cloud.githubusercontent.com/assets/1236467/6653229/92690d1e-ca5f-11e4-8cdb-686014769e1d.png)

It works for me. Don't forget to register www.beta.patricbrc.org to your applet white list.

Preferences -> Java -> Security tab -> Edit Site List -> add "http://www.beta.patricbrc.org" -> click Ok -> click Ok

You may have to restart your browser to make it effective.

Harry
