### ISSUE TITLE
Workspace / feature group: PATRIC_ID not displayed

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#241]
PATRIC ID is not displayed in the workspace feature group member list. 

I think it missed out the memo on change seed_id to patric_id! :)

-Maulik
![screen shot 2015-06-05 at 8 09 44 am](https://cloud.githubusercontent.com/assets/1236463/8005633/4078d2d2-0b5a-11e5-85fa-b2a97b0de819.png)

**Comment by dmachi** [comment]
Fixed and pushed to beta
