### ISSUE TITLE
Gobs sit in queue without starting for too long after the last week outage 

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#2419]
I am not in a hurry, but this doesn't seem right - 

I have submitted 3 types of jobs today roughly at the same time, about 2 hours ago:
   Codon Tree, 
   Genome annotation, 
   Proteome Comparison.  
While two Genome annotation jobs started immediately and  completed fast, two other TYPES of jobs still haven't started (after almost 2 hours in the queue).  This never ever happened before in PATRIC.  I've check my log of ~230 jobs: the longest time laps between a job submission and a job start was half hour 

![image](https://user-images.githubusercontent.com/20665963/127042708-8585b50e-17af-4663-a27f-0bbe71f8d390.png)

**Comment by Sveta-user** [comment]
Opps, as I was writing this, all my job just changed to "running".  Sorry to have bothered you in vain!

**Comment by olsonanl** [comment]
We have many hundred jobs in the queue at the moment; the fair share policy keeps availability for people with small numbers of jobs but there are also long-running jobs on the cluster that need to complete to open up slots for new jobs.

**Comment by Sveta-user** [comment]
Thank you, Bob!  Sounds fair.  Really glad that PATRIC is popular and overrun with eager users! :D
