### ISSUE TITLE
genome annotation validation

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#242]
One more nit on this - if you click the "more choices" button in the dropdown it drops out of the dropdown with the original typed in text in place

**Comment by aswarren** [comment]
Dustin recently implemented this. He probably has a better idea how to adjust this behavior.

**Comment by mshukla1** [comment]
I believe this refers to the genome annotation submission form, right? 

Please add details and change label/assignee/milestone if needed.

**Comment by olsonanl** [comment]
Closing as a duplicate of #307 where I've been collecting issues about this UI.
