### ISSUE TITLE
Blast is down completely

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#2424]
Public and private genomes can't be searched by BLAST as of October 1: 

Failed: 500 Can't connect to p3.theseed.org:443 URL = genome?in(genome_id,(1685.607,1685.576,302911.134,302911.132,302911.133,302911.119,391904.5,1682.124,1679.210,1681.980,1168290.3))&select(genome_id,public,owner)&limit(25000,0)

![image](https://user-images.githubusercontent.com/20665963/135675444-7d4cd386-f1f5-4056-9d95-9b844772cd6f.png)

**Comment by olsonanl** [comment]
Should be better now.

**Comment by Sveta-user** [comment]
Works perfectly!!  Just rested.  Thank you very much, Bob!!
