### ISSUE TITLE
Nucleotide sequence not appearing in genome browser for private genome

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#243]
When I launched the genome browser with my private genome and clicked on one of the features, the message box opens and tells me the length of the feature, but does not provide the nucleotide sequence.

**Comment by mshukla1** [comment]
keep your calm and clear your cache! ... problem solved!

**Comment by rkenyon** [comment]
clearing cache did not work...

**Comment by mshukla1** [comment]
I just tried for one of my private genomes, and I get the NA sequence from the genome browser.

I am going to close the issue, please comment/reopen if you still see it.

**Comment by mshukla1** [comment]
![screen shot 2015-06-09 at 1 49 04 pm](https://cloud.githubusercontent.com/assets/1236463/8065271/6fdf909a-0eae-11e5-96e3-72e35fa0f7b0.png)
