### ISSUE TITLE
BLAST issue after July 5 downtime

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#2434]
Greetings!

Error message when trying to blast against private genomes ( e.g. 1502.1869  or 1502.2501 )

We were not able to complete your BLAST request. Please let us know with detail message below.
mkdir /disks/patric-common/data/homology_service/private-genomes/saxerdupont@patricbrc.org: Permission denied

**Comment by olsonanl** [comment]
Try it again now.

**Comment by Sveta-user** [comment]
It worked!  Thanks so much, Bob!

**Comment by olsonanl** [comment]
You are welcome.
