### ISSUE TITLE
Link to a Peg ID from a feature in my private genome gives invalid identifier error

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#244]
at the SEED Viewer site.

**Comment by olsonanl** [comment]
Those should not get linked to SEED since SEED won’t know anything about the private genomes.

On Jun 5, 2015, at 1:19 PM, rkenyon <notifications@github.com<mailto:notifications@github.com>> wrote:


at the SEED Viewer site.

**Comment by mshukla1** [comment]
Link to seed and other external resources are created by using a base URL and some common/expected id such as seed id / refseq id / uniprot id. However, it is not always guaranteed that the feature or corresponding page will exist on a given resource. Without storing all third party id mappings locally, there is no way for us to tell which links would be active and which will not be. 

The links that may fall in these category are: 
pseed/pubseed
string
stitch

**Comment by mshukla1** [comment]
We have remove the links to PSEED gene pages on the new beta site.
