### ISSUE TITLE
Phylogenetic Tree jobs failing

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#2440]
Greetings - 
Several CodonTree jobs failed on January 25th,  for example these two.  No Error output was created for them, so I don't know why. Could you please let me know what went wrong? 

Service	CodonTree
Job ID	10185005
Status	failed
Submitted	2023-01-26T04:20:50Z
Start	2023-01-26T04:20:58Z
Completed	2023-01-26T04:20:58Z

Service	CodonTree
Job ID	10185001
Status	failed
Submitted	2023-01-26T04:03:45Z
Start	2023-01-26T04:03:55Z
Completed	2023-01-26T04:03:55Z

Would really appreciate your help,
Sveta

**Comment by Sveta-user** [comment]
Some of the genomes are private (mine), others are private+shared with me.  Could this be causing this problem?  
I've started a tree to test this hypothesis: it doesn't include any private+shared genomes -

Service	CodonTree
Job ID	10185006
Status	in-progress
Submitted	2023-01-26T04:27:33Z

**Comment by olsonanl** [comment]
No, there was a problem with the scheduler that resulted in some jobs failing with no output. They have been restarted; 5001 is completed and 5005 is running now.

--bob

**Comment by Sveta-user** [comment]
Thank you very much!!

**Comment by olsonanl** [comment]
You are welcome!
