### ISSUE TITLE
Job are queuded for 12 hours

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#2446]
Greetings,
I started 4 jobs yesterday, Friday evening June 30.  All 4 have been in queue for 12 hours now.  Does this mean than some BV-BRC services will be down this long weekend?  There are no warning posted on your web site though... . Asking so I could plan accordingly
Thank you ! 

jobs # 10969246,  10969246,  10969076  Comprehensive Genome Analysis
job #10959202 Codon Tree 

Application | CodonTree
Job ID | 10959202
Status | queued
Submitted | 2023-07-01T01:23:27Z

**Comment by Sveta-user** [comment]
And the Blast server is not working either, jobs are getting queued too.  I do hope this is just a scheduled downtime, and not due to some disaster...

**Comment by olsonanl** [comment]
Hi Sveta - we had an issue with the BV-BRC job scheduler. Should be resolved now.

**Comment by Sveta-user** [comment]
Hi Bob,

Thank you very much for fixing this issue.  And for doing it on this long weekend

Happy 4th of July !

Gratefully,
Sveta
