### ISSUE TITLE
Phylogenetic trees are not working ?

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#2447]
Greetings -
I started 3 Trees last night, all tree are still being reported as "running" now, the next morning .  
Similar trees before didn't take more than 3 -4 hours.  This time is has been 10 hours already...  
 Job IDs:  12012064, 12012065, 12012127

Application | CodonTree
Job ID | 12012064
Status | in-progress
Submitted | 2023-08-28T22:14:25Z

Thank you for looking into this!
Sveta

**Comment by olsonanl** [comment]
Hi Sveta - We have a maintenance window coming up tomorrow; the estimated runtime for your jobs causes them to overlap the window so they will run when we are finished.

Thanks,
Bob

**Comment by Sveta-user** [comment]
Ho Bob - thanks for letting me know!  This is not urgent at all
S
