### ISSUE TITLE
Download gene list is not working in transcriptomics heatmap tab

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#247]
When selecting the gene list from the heapmap view of the Transcriptomics page, Download Genes doesn't work.
![image](https://cloud.githubusercontent.com/assets/6361802/8013341/83fcb942-0b96-11e5-96ae-3622a97cf994.png)

**Comment by maovt** [comment]
![screen shot 2015-06-05 at 3 17 29 pm](https://cloud.githubusercontent.com/assets/6361802/8013468/7521ddac-0b97-11e5-94cc-92ee48e338c7.png)

**Comment by hyoo** [comment]
fixed and available on beta.

**Comment by mshukla1** [comment]
Working now.
