### ISSUE TITLE
FASTA protein and FASTA DNA buttons don't work on the Pathway Summary page

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#248]
FASTA protein and FASTA DNA buttons (under View and Download) don't work on the Pathway Summary page

**Comment by maovt** [comment]
![image](https://cloud.githubusercontent.com/assets/6361802/8013652/eb19aa52-0b98-11e5-9a78-766325477fc4.png)

**Comment by maovt** [comment]
![screen shot 2015-06-05 at 3 37 50 pm](https://cloud.githubusercontent.com/assets/6361802/8013684/0a545296-0b99-11e5-8782-66e0f0773d51.png)

**Comment by hyoo** [comment]
fixed and available on beta

**Comment by mshukla1** [comment]
Checked, working now.
