### ISSUE TITLE
too much scrolling needed in facets

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#249]
See screen shot; in genome list view, list of facets requires scrolling even though there is plenty of vertical room to show the entire list.

![screen shot 2015-06-05 at 3 24 27 pm](https://cloud.githubusercontent.com/assets/2152226/8014500/f852f5cc-0b96-11e5-9af8-77c9962176ab.png)

**Comment by hyoo** [comment]
Although this ticket is for current production, new website takes care of it and we're planning to have beta soon. So, I am closing this ticket.
