### ISSUE TITLE
Beta site won't let me create a group

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#253]
Even though I am logged in, the beta site asks me to log in each time I create a genome group.  If I log in and go back to the page, it will still ask me to log in when I try and create it.

**Comment by mshukla1** [comment]
We discussed it this morning in the sync call. Harry confirmed that the problem was there yesterday, but we can not reproduce it Today. Please let us know if you still see the problem.

**Comment by ARWattam** [comment]
I just tried it now and it worked.

----- Original Message -----
