### ISSUE TITLE
data API does not support old api calls

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#256]
I was trying to migrate old api call to new data api, but it not working now.

https://www.beta.patricbrc.org/api/ppi/?descendants((2,33208))&between()&keyword(PATRIC.444461.3.ARFQ01000110.CDS.150263.150466.rev)&eq(is_hpi,Y)&facet((sort,+rownum))&limit(0,0)

**Comment by dmachi** [comment]
The new data api doesn't support the descendants() operator yet (any more?).  I hadn't planned on adding it back if we don't need it any more.  I think with the taxon_lineage_ids change that was made quite some time ago, that piece isn't needed.  Similarly, between() doesn't exist either, but I can also add that in if needed.

**Comment by mshukla1** [comment]
Does this affect any of the functionality? In other words, is anything broken on the site, because the old api call is not supported? If not, close the ticket!

**Comment by dmachi** [comment]
This impacts PPI.  I was planning to leave the old data api running for this until I could get these functions added or replaced in the new one.

**Comment by hyoo** [comment]
I have filled in this function but we already implemented new Interactions tab. closing.
