### ISSUE TITLE
Transcriptomics Gene List: shows only subset of genes

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#258]
Went to Mycobacterium transcriptomics tab, clicked on number of genes(GSE8839, genes: 3839), for one of the experiments. The gene list shows only  717 genes. 

I believe the reason is that gene list is getting back only first 25000 rows from the data API, and displaying them, instead of getting all the rows. 
![screen shot 2015-06-09 at 12 36 24 pm](https://cloud.githubusercontent.com/assets/1236463/8063811/d09566c6-0ea4-11e5-89bc-c0e7111a4ca6.png)
![screen shot 2015-06-09 at 12 36 09 pm](https://cloud.githubusercontent.com/assets/1236463/8063812/d095f8ca-0ea4-11e5-9a9c-5bf4cb960480.png)

**Comment by hyoo** [comment]
fixed and available on beta.

**Comment by mshukla1** [comment]
Checked, working as expected now.
