### ISSUE TITLE
Gene Overview: link to uniprot broken

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#259]
https://www.beta.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=PATRIC.83332.12.NC_000962.CDS.15590.17470.rev

 UnitProt: I6Y2I5  goes to https://www.uniprot.org/uniprot/I6Y2I5 which doesn't exist. 

Change link from https to http.

**Comment by hyoo** [comment]
fixed and available on beta.
