### ISSUE TITLE
Genomes missing from genome group

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#26]
I selected a group of 20 genomes and added them to a new group.  When I went to the workspace, there were only 13 genomes in the group.  I tried it again with a different set of 20 genomes and this time, only 15 were in the group in the workspace.

**Comment by dmachi** [comment]
This can happen when some of the genomes (or their id's) no longer exist in solr.  I'm not sure if that is the case here or not, but will investigate.

**Comment by rkenyon** [comment]
Do you want the original list?  I simply chose Francisella organism and 
the first 20 genomes that show up in the list for the first test, then 
the same thing for Helicobacter for the second test.


Ron Kenyon
PATRIC Project Manager, patricbrc.org
Project Management Director
Virginia Bioinformatics Institute, Virginia Tech
Ph: 540-231-7470

**Comment by dmachi** [comment]
I'll let you know.  I'll try to reproduce independently first.

Dustin

**Comment by dmachi** [comment]
This was a configuration issue.  Wrong database pointer.
