### ISSUE TITLE
Data: empty features on beta

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#260]
Go to all bacterial features. Sort ascending AA length
https://www.beta.patricbrc.org/portal/portal/patric/FeatureTable?cType=taxon&cId=2&featuretype=&annotation=PATRIC&filtertype=#

**Comment by mshukla1** [comment]
Related to #185. 

There are ~500 patric features (out of ~100M) that got indexed without patric_id and aa _sequence because of a parsing error. Trying to figure out how I can add the missing information.

**Comment by mshukla1** [comment]
There were total 517 CDS in the database without patric id, function and aa sequence. I have added missing information for all of them.

-Maulik
