### ISSUE TITLE
assembly job data and results not loading

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#261]
I ran an assembly yesterday. The Jobs pane says it is complete. There is a result object in my workspace. 

When I double click on the job in the jobs table, it hangs with a message "Loading job results"

PATRIC_Workshop / home / Acinetobacter baumannii Genome seq / Acinetobacter baumannii 1000160 (Taxonomy ID 1310800) / a_baumannii_1000160 
Loading Job Results...

When I double click on the results object in the workspace browser, it hangs with a message "Loading job results"

PATRIC_Workshop / home / Acinetobacter baumannii Genome seq / Acinetobacter baumannii 1000160 (Taxonomy ID 1310800) / a_baumannii_1000160 
DETAIL
Loading Job Results...

**Comment by dmachi** [comment]
This appears to be a problem in the Job_Result object.  The output_files property of the job_result object is an empty array.  I can confirm that the hidden folder and contigs were created, but this array doesn't contain their references.  I know that @olsonanl did a new deployment recently and so I'm not sure if the changes were required to fix this or if this is a new problem. Any ideas Bob?

The request:

{"id":2,"method":"Workspace.get","params":[{"objects":["/PATRIC_Workshop@patricbrc.org/home/Acinetobacter baumannii Genome seq/Acinetobacter baumannii 1000160 (Taxonomy ID 1310800)/a_baumannii_1000160"],"metadata_only":true}],"jsonrpc":"2.0"}

Response:

{"jsonrpc":"2.0","id":2,"result":[[[["a_baumannii_1000160","job_result","/PATRIC_Workshop@patricbrc.org/home/Acinetobacter baumannii Genome seq/Acinetobacter baumannii 1000160 (Taxonomy ID 1310800)/","2015-06-05T21:14:32","DBEE3E9C-0BC7-11E5-9445-7E05692E0674","PATRIC_Workshop@patricbrc.org",4334,{},{"app":{"parameters":[{"group":[{"required":1,"desc":"FASTQ or FASTA file or reads","type":"wstype","label":"Read file 1","id":"read1","wstype":"ReadFile"},{"required":0,"desc":"FASTQ or FASTA file or reads","type":"wstype","label":"Read file 2","id":"read2","wstype":"ReadFile"},{"required":0,"type":"bool","default":"0","label":"Are the paired end reads interleaved?","id":"interleaved"},{"required":0,"type":"int","default":null,"label":"Average insert size","id":"insert_size_mean"},{"required":0,"type":"float","default":null,"label":"Average insert standard deviation","id":"insert_size_stdev"}],"allow_multiple":"1","required":0,"default":null,"type":"group","id":"paired_end_libs"},{"allow_multiple":"1","required":0,"desc":"FASTQ or FASTA file or reads","type":"wstype","default":null,"label":"Read file","id":"single_end_libs","wstype":"ReadFile"},{"required":0,"desc":"Reference set of assembled DNA contigs","type":"wstype","label":"Contig file","default":null,"id":"reference_assembly","wstype":"Contigs"},{"required":0,"desc":"Recipe used for assembly","enum":["auto","full_spades","fast","miseq","smart","kiki"],"type":"enum","default":"auto","label":"Assembly recipe","id":"recipe"},{"required":1,"desc":"Path to which the output will be written. Defaults to the directory containing the input data. ","type":"folder","default":null,"label":"Output Folder","id":"output_path"},{"required":1,"desc":"Basename for the generated output files. Defaults to the basename of the input data.","type":"wsid","default":null,"label":"File Basename","id":"output_file"}],"script":"App-GenomeAssembly","label":"Assemble reads","id":"GenomeAssembly","description":"Assemble reads into a set of contigs"},"start_time":1433531789.51014,"hostname":"redwood.mcs.anl.gov","elapsed_time":7082.45892000198,"job_output":{"arast_job_id":"1"},"parameters":{"output_file":"a_baumannii_1000160","output_path":"/PATRIC_Workshop@patricbrc.org/home/Acinetobacter baumannii Genome seq/Acinetobacter baumannii 1000160 (Taxonomy ID 1310800)","paired_end_libs":[{"read2":"/PATRIC_Workshop@patricbrc.org/home/Acinetobacter baumannii Genome seq/Acinetobacter baumannii 1000160 (Taxonomy ID 1310800)/SRR1033693_2.fastq.gz","read1":"/PATRIC_Workshop@patricbrc.org/home/Acinetobacter baumannii Genome seq/Acinetobacter baumannii 1000160 (Taxonomy ID 1310800)/SRR1033693_1.fastq.gz","interleaved":"false"}],"recipe":"auto","reference_assembly":""},"end_time":1433538871.96906,"output_files":[],"id":"bda8d22e-e04f-4af0-ab99-d1118630d664"},"o","n",""]]]]}

**Comment by olsonanl** [comment]
Odd. I will recheck this when assembly comes back online; it appears the job ran and created results without issue

**Comment by dmachi** [comment]
Yes, the job runs fine and outputs files, but the output_files property of the job_result is empty for some reason.

**Comment by olsonanl** [comment]
Right, and that's filled by an enumeration of the workspace so it is quite odd that it didn't get filled in.

**Comment by dmachi** [comment]
Just ran a new assembly job.  It has output_files defined and the job_result viewer shows its content properly.  Tom, can you verify and close this ticket if you don't see any problems.

**Comment by olsonanl** [comment]
we should try a run with paths and filenames with spaces included; that's the only thing that I noted as different in the job that had the problem

________________________________

**Comment by brettin** [comment]
Things seem to be working smoothly now. Closing ticket.
