### ISSUE TITLE
no css on enews from beta site

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#263]
Dustin, I think it is because of https and certificate issue, which may go away when we deploy on production. Please verify.
![screen shot 2015-06-10 at 8 59 36 am](https://cloud.githubusercontent.com/assets/1236463/8082965/4d4686fa-0f4f-11e5-9244-1ff64ea3128f.png)

**Comment by dmachi** [comment]
I think you should just be going to http://enews.patricbrc.org/faqs  instead of https://

**Comment by mshukla1** [comment]
I clicked on the link from the about menu, which took me to https. IT doesn't see to be the caae now though!

**Comment by dmachi** [comment]
In production it links to http:// in beta it appears to link to https:// .  I believe this needs to stay http://.  I couldn't tell from your last comment whether it appears to work for you now with https:// (it doesn't for me) or whether you were just saying it was linking to http:// for you.

Dustin
