### ISSUE TITLE
Pathway summary-sorting of column not working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#264]
I sorted on the number of genes and it should go from 19-1, or from 1-19.  I get what you see below
![screen shot 2015-06-10 at 10 51 13 am](https://cloud.githubusercontent.com/assets/11475316/8085537/b3b9a55c-0f5e-11e5-8498-2974e2be3355.png)

**Comment by mshukla1** [comment]
Harry, the sorting is done as string instead of on numeric values. Can you fix it?

**Comment by mshukla1** [comment]
Checked, sorting is now working as expected. Thanks, Harry. You da man! :)
