### ISSUE TITLE
When filter on log for transcriptomics with individual gene, diagram does not reflect data

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#265]
I filtered on 3, but the diagram that shows the log ratio graph is empty.  There should be 16 comparisons that have this
![screen shot 2015-06-10 at 11 19 44 am](https://cloud.githubusercontent.com/assets/11475316/8086303/b8c6049c-0f62-11e5-9cef-c85f1f191339.png)

**Comment by mshukla1** [comment]
I can't reproduce the problem. Please add a link to the page, if you still see the problem.

**Comment by ARWattam** [comment]
This gene:
fig|511145.12.peg.2835 | b2741 | VBIEscCol129921_2835 | rpoS | RNA polymerase sigma factor RpoS  expand or shrink bread crumb

https://www.beta.patricbrc.org/portal/portal/patric/TranscriptomicsGeneExp?cType=feature&cId=PATRIC.511145.12.NC_000913.CDS.2864581.2865573.rev&sampleId=&colId=&log_ratio=&zscore=

----- Original Message -----

**Comment by hyoo** [comment]
fixed and available on beta.

**Comment by mshukla1** [comment]
Checked and verified.
