### ISSUE TITLE
eNews: update Benefits of Registration page

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#266]
Ron, I this we need to update bunch of pages on the news site, starting with: 

http://enews.patricbrc.org/faqs/workspace-faqs/registration-faqs/

Now that we have more stuff available with login, i.e. assembly, annotation, etc, it needs to be reflected on the faqs page.

**Comment by rkenyon** [comment]
Updated the Benefits of Registration page in WordPress.
