### ISSUE TITLE
Assembly App: hidden folders are now shown in the output folder selection

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#267]
don't remember seeing them before. 

![screen shot 2015-06-10 at 3 03 21 pm](https://cloud.githubusercontent.com/assets/1236463/8091473/fcd782fe-0f81-11e5-992b-8497ad9e3ca8.png)

**Comment by dmachi** [comment]
Fixed and pushed to beta.

**Comment by mshukla1** [comment]
looks better now! :)
