### ISSUE TITLE
can't compare reference to user genome

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#268]
If I want to compare just a reference genome to my user genome, it appears I can't do that. It requires a genome to compare in addition to the user genome.

I'd also like to compare multiple user genomes.

**Comment by maovt** [comment]
This is a design issue. For the current release, we only allow one user genome (uploaded as faa file). However, we allow multiple user private genomes if they're already annotated using our annotation pipeline and indexed in solr.

**Comment by olsonanl** [comment]
Ah- got it. that makes sense. Thanks.

On Jun 10, 2015, at 4:02 PM, maovt <notifications@github.com<mailto:notifications@github.com>> wrote:

This is a design issue. For the current release, we only allow one user genome (uploaded as faa file). However, we allow multiple user private genomes if they're already annotated using our annotation pipeline and indexed in solr.

**Comment by mshukla1** [comment]
It seems I can close this issue now.
