### ISSUE TITLE
Genome Comparison: need genome names in legends

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#269]
As discussed before, we need to add genomes names as legend for the circular viewer in the genome comparison tool. Right now, there is no way for user to tell which track represents which genome!
![screen shot 2015-06-10 at 5 04 17 pm](https://cloud.githubusercontent.com/assets/1236463/8094077/c6a35314-0f92-11e5-9e23-80ffb51b2538.png)

**Comment by maovt** [comment]
It's fixed. The fix won't work for the old results. Please try again with a new comparison job.

**Comment by maovt** [comment]
It's fixed. The fix won't work for the old results. Please try again with a new comparison job.

**Comment by mshukla1** [comment]
Thanks, Chunhong. Suggestion for layout, two possible options: 

1. If we have the genomes names listed on the left, like you have now, keep then left of the circle view side-by-side. So that, it doesn't push the circle all the way down, specially if I am comparing 8 genomes. 

2. Or, print the genome names in paragraph mode, similar to the way we are displaying tracks in the genome circular viewer tab.

**Comment by mshukla1** [comment]
This is what it looks like when comparing 8 genomes, it is B E A U T I F U L! 

The layout suggestion is not critical, rather enhancement!


![screen shot 2015-06-10 at 6 20 39 pm](https://cloud.githubusercontent.com/assets/1236463/8095598/9310bb8a-0f9d-11e5-8e40-4e5af7442b44.png)
