### ISSUE TITLE
Two copies of "Genome Groups" are now in my workspace

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#27]
Not sure how/why this happened.

**Comment by rkenyon** [comment]
None of the other groups are there, just 2 copies of Genome Groups.

**Comment by dmachi** [comment]
I cannot figure out how the workspace got into this state.  Its possible there was another error somewhere else that prevented things from completing.  However, I cleared this workspace and did a re-import and all is fine there now.  I'm going to close this ticket, but we can reopen if we see the issue again.
