### ISSUE TITLE
Expression Import: "Differential" should be in the name

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#271]
Expression Import: Does it mean I can import my single channel or RNA-Seq expression data? 

The app can handle ONLY differential expression data! So, IMHO, to avoid confusion, the word "Differential" needs to be there in the title! 

"Differential Expression Import" ...too long?

**Comment by aswarren** [comment]
With the 'differential' on there it was a bit long. Also since there is no other expression import functionality to confuse it with, it seems fine to me. I thought it more important that it fit in the menu. Though admittedly 'Expression Import' does make it seem more appetizing than it actually is.

**Comment by mshukla1** [comment]
We know what the name implies and what the app does. From a user perspective, they won't know thats the only expression app and that it implies differential expression only! :)

**Comment by aswarren** [comment]
Ok, though i highly doubt there will be much confusion (just stymied interest). To avoid this whole discussion all over again: what about "Diff. Expression Import", "DiffExp Import" or simply "DE Import"?

**Comment by rkenyon** [comment]
Maybe "Expression Data Import?"  The user can figure out that it is differential expression when they go to the form and it gives additional information.

Ron

**Comment by maovt** [comment]
I vote for "Diff. Expression Import".

**Comment by mshukla1** [comment]
Diff Expression Import....it is! ;)

**Comment by aswarren** [comment]
Accepted and pushed. Needs deploying.
