### ISSUE TITLE
Jobs list automatically resorts itself every X seconds

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#272]
Before:

![screen shot 2015-06-10 at 4 35 00 pm](https://cloud.githubusercontent.com/assets/1194246/8094795/d520b778-0f8e-11e5-9f32-3e41b91bec01.png)

After X seconds:

![screen shot 2015-06-10 at 4 35 09 pm](https://cloud.githubusercontent.com/assets/1194246/8094905/b9ce061e-0f8f-11e5-8238-df0d72a0760b.png)

**Comment by mshukla1** [comment]
I believe it is because the page/list gets refreshed every X seconds to get the latest status, but it doesn't remember the sort order.  Assigning it to Dustin.

**Comment by dmachi** [comment]
Fixed.
