### ISSUE TITLE
Protein-protein interactions working at genome level, but not at gene level

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#273]
From the H37Rv genome page I can see that DnaK has interaction data, but when I go to the tab on the gene landing page, it says that no data is available.

**Comment by hyoo** [comment]
This is because new PATRIC feature id is not included in the xref field. We need to integrate our feature id.

**Comment by hyoo** [comment]
this is available at www.beta.patricbrc.org

**Comment by hyoo** [comment]
we need update interactors (patric ID mapping part).

**Comment by hyoo** [comment]
this is specific to outdated website.
