### ISSUE TITLE
Assembly and RNA-Seq app layouts not consistent

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#274]
In the annotation app, read upload comes first and then parameter and output selection. 
In the RNA-Seq, the order is reversed. I think they should be consistent. 
![screen shot 2015-06-10 at 6 03 48 pm](https://cloud.githubusercontent.com/assets/1236463/8095340/5c1e9d42-0f9b-11e5-96c8-ab75840fb228.png)
![screen shot 2015-06-10 at 6 03 41 pm](https://cloud.githubusercontent.com/assets/1236463/8095341/5c1f0700-0f9b-11e5-8c61-feab8e62cfab.png)

**Comment by aswarren** [comment]
Multiple people discussed this in the UI meeting and decided it was a non-issue.
