### ISSUE TITLE
Jobs tooltip covers jobs button, making navigation difficult.

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#276]
![screen shot 2015-06-10 at 5 12 00 pm](https://cloud.githubusercontent.com/assets/1194246/8095547/c94727ba-0f94-11e5-94d4-c28ea6b03cdd.png)

**Comment by nconrad** [comment]
Related, all links should probably have an "active" styling to indicate where you are.

**Comment by mshukla1** [comment]
I think it would be better it we make the entire Jobs status bar hyperlinked, including the white area and numbers. which seems to be the case for the Uploads area right now. So, lets make them both consistent. 

![image](https://cloud.githubusercontent.com/assets/1236463/8095688/446a5094-0f9e-11e5-86be-4f9c54731b7d.png)

**Comment by dmachi** [comment]
Fixed on beta

**Comment by mshukla1** [comment]
Thanks, Dustin. This is much better. I like how the tooltip comes up above the box. 
Can we do the same for the uploads tooltip as well? :)

**Comment by dmachi** [comment]
Already in progress. Almost done.

**Comment by dmachi** [comment]
UploadStatus widget updated now too.

**Comment by mshukla1** [comment]
El Perfecto!! Mucho Gracias! :)
