### ISSUE TITLE
Assembly App: help tooltip behavior inconsistent

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#278]
- Help tooltips for paired library and parameters appear after clicking. 
- The same on the selected library panel appear on mouseover. 

- Also, tooltip for he advanced parameter never appear, seems it is  hidden behind other div layers. 

![screen shot 2015-06-11 at 7 35 07 am](https://cloud.githubusercontent.com/assets/1236463/8106100/85fdafc4-100c-11e5-8977-2016e8535e78.png)

**Comment by aswarren** [comment]
Fangfang @levinas is working on the help text for the advanced parameter box.

It is consistent throughout the apps that large information boxes appear on clicking and small ones appear on mouseover. I raised the same inconsistency before and this is what we decided to go with. This inconsistency is consistent.

The advanced parameter help is indeed hidden. It only appears when the advanced box is expanded. I looked at it both ways and decided that it was less confusing to only have help for UI elements that were visible.

**Comment by mshukla1** [comment]
regarding "The advanced parameter help is indeed hidden." My point is not that the (i) link appears after opening advanced options, It is that when I click on (i) the tooltip box appears behind the parameter panel. Look closely near top right corner of the parameters panel!

**Comment by aswarren** [comment]
It wasn't hidden it was incomplete. As I alluded previously, Fangfang had not yet written the advanced help text. That is why the div was empty and the popup was showing up in measly fashion. It is now present.
