### ISSUE TITLE
from workspace to genome list

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#284]
I'd like to be able to go directly from a genome group in the workspace browser to a genome finder populated with that group's genomes - am I missing how to do that or is it not currently there?

**Comment by dmachi** [comment]
This looks like a regression. I will take a look.  You should be able to get there from two places in the workspace.  1. From the Genome Groups folder, you should be able to select a genome group and then an icon should appear for that in the green bar (this appears to have gone missing) or 2. From within a genome group in the workspace, you should be able to select a subset of the genomes in the group and go (this does work)

**Comment by hyoo** [comment]
this is specific to outdated website. In new website, we do have this functionality.
