### ISSUE TITLE
Genome Comparison: option to open image in a new tab

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#285]
In the circular genome viewer, I can right click on the circular image and open it in a new tab, so that I get the full view and I can zoom in / out. 

For the same circular view in the genome comparison viewer, when I right click, open image in new tab option is greyed out. Any idea how we can enable it? 

![screen shot 2015-06-11 at 5 24 27 pm](https://cloud.githubusercontent.com/assets/1236463/8119913/22fe5b96-105f-11e5-8fa8-e7720fe0f80a.png)

**Comment by dmachi** [comment]
There isn't currently a straight forward way to do this because there isn't a url request you can make to retrieve it.

**Comment by olsonanl** [comment]
How is it displayed in the browser currently?

**Comment by dmachi** [comment]
The reason that this is disabled is because the image is inlined into the html output of the service. It is not directly linkable (aside from creating a download of that svg, which we do as a separate button).

**Comment by hyoo** [comment]
@dmachi Can we switch this to new circular viewer?

**Comment by mshukla1** [comment]
Given we have the new view icon and ability to download SVG image, I think we can close this issue.
