### ISSUE TITLE
Private genome has genes, but when put in protein family sorter nothing shows up

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#286]
I annotated a new Pseudomonas genome, saw that it had genes in the workspace, created a genome group with other Pseudomonas.  When I put it into the Protein Family Sorter, it looks like there aren't any genes at all there (My genome is the long black streak).

Sigh.  Bitter disappointment.  Heart breaking.....
![screen shot 2015-06-11 at 6 39 38 pm](https://cloud.githubusercontent.com/assets/11475316/8120091/6bc1ec08-1069-11e5-9094-362c291fdf8a.png)

Here's the genome in my workspace when I click on the completed job
![screen shot 2015-06-11 at 6 41 43 pm](https://cloud.githubusercontent.com/assets/11475316/8120105/98706ed2-1069-11e5-89c2-b496514754e7.png)

**Comment by mshukla1** [comment]
Go to the genome overview page and check if any of the genes are assigned to figfams, most likely now. 
When the annotation service came back up Yesterday, teh figfam assignment part was still not working. Bob fixed it sometime this afternoon. 

If no genes are assigned to the figfam, please reannotate the genome and it should solve the problem. 

We apologize for any inconvenience / hurt feelings / mental trauma / emotional outbursts this may have cause you. We thank you for your patience and for continue to use PATRIC!

**Comment by dmachi** [comment]
Is this working now?

**Comment by ARWattam** [comment]
I annotated a genome 2 days ago and it worked fine.  Isolated instance?  

----- Original Message -----
