### ISSUE TITLE
Viewing freshly annotated genome failing

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#287]
I'm in the PATRIC_Workshop workspace and I clicked on the first completed Acinetobacter job.  It opened up the summary page in the workspace
![screen shot 2015-06-12 at 10 48 26 am](https://cloud.githubusercontent.com/assets/11475316/8132581/b8b073c2-10f0-11e5-85e3-08f350ee54f8.png)

But when I click on the eye to view my genome, I'm getting this:
![screen shot 2015-06-12 at 10 48 33 am](https://cloud.githubusercontent.com/assets/11475316/8132594/cd5d7694-10f0-11e5-9c04-30b9b55b74e3.png)

**Comment by dmachi** [comment]
I'm not sure why this happened.  Using a PATRIC_Workshop token, I verified that the results were coming back from the data api.  When I login to the site and view that job result, it seems to be working for me.

**Comment by dmachi** [comment]
Actually, I think this is probably because  you are on beta here.  The production and beta databases are on different solr instances, so this genome does not exist in the beta solr.

**Comment by dmachi** [comment]
This isn't really a bug, but instead just confusion between beta and prod
