### ISSUE TITLE
The up arrow for the Parent Folder doesn't work in workspace

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#29]
The up arrow for the Parent Folder doesn't work in my workspace. It's highlighted when pointing to it. But it doesn't to anything when clicking on it.

**Comment by aswarren** [comment]
Please give more detail. Which browser. Which folder, is it one you
created? Is it one that existed by default?

Thanks,
Andrew

**Comment by maovt** [comment]
Just found out that it works when double clicking it (not for single clicks)
