### ISSUE TITLE
MSA viewer doesn't show the protein tree panel

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#290]
![screen shot 2015-06-12 at 2 28 59 pm](https://cloud.githubusercontent.com/assets/6361802/8137218/bb268cf8-110f-11e5-964a-6bcb0923922b.png)

**Comment by aswarren** [comment]
This is due to login and illustrates the need for certs for alpha for proper dev/testing. A fix for this has been pushed and needs to be deployed.
