### ISSUE TITLE
RNA-Seq using Tuxedo failed 

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#291]
The job failed with the following error:

/scratch/tmp/cbIrfPWm66
GET WS => /scratch/tmp/cbIrfPWm66 trim_wt_pi_2_DR10_R1.fastq /cmao@patricbrc.org/home/trim_wt_pi_2_DR10_R1.fastq
curl -H Authorization: un=cmao@patricbrc.org|tokenid=f35670f5-8b6e-4359-8ff8-d2e89c505975|expiry=1465678278|client_id=cmao@patricbrc.org|token_type=Bearer|realm=patricbrc.org|SigningSubject=https://user.patricbrc.org/public_key|sig=8b19cc8aed81505aa45436d1ee4faf3ce044b872bbf27ad9f98b3eafcea95a2bacd6da3635d1740d512c4bb31204e95831d1314d6cb8ab5eff2d3943ec1c90b885c9b16dbca0244625c7069a644194e42e7fadad2c1fb63144b72d4a153d3504a0dc9ca749183dd1fc1c550eb40229bf194649c02259712953e5136097a53dd1 -H Content-Type: multipart/form-data ftp://ftp.patricbrc.org/patric2/patric3/genomes/83331.22/83331.22.PATRIC.gff
curl -H Authorization: un=cmao@patricbrc.org|tokenid=f35670f5-8b6e-4359-8ff8-d2e89c505975|expiry=1465678278|client_id=cmao@patricbrc.org|token_type=Bearer|realm=patricbrc.org|SigningSubject=https://user.patricbrc.org/public_key|sig=8b19cc8aed81505aa45436d1ee4faf3ce044b872bbf27ad9f98b3eafcea95a2bacd6da3635d1740d512c4bb31204e95831d1314d6cb8ab5eff2d3943ec1c90b885c9b16dbca0244625c7069a644194e42e7fadad2c1fb63144b72d4a153d3504a0dc9ca749183dd1fc1c550eb40229bf194649c02259712953e5136097a53dd1 -H Content-Type: multipart/form-data ftp://ftp.patricbrc.org/patric2/patric3/genomes/83331.22/83331.22.fna
Could not find RNA-Rocket: prok_tuxedo.py

**Comment by levinas** [comment]
Can you try again? This should be fixed.

**Comment by olsonanl** [comment]
Assigned to retry the job and close if not an active issue.

**Comment by aswarren** [comment]
From @levinas message and subsequent tuxedo testing this seems to be a non-issue. If this comes back up we need to share the specific input.
