### ISSUE TITLE
0 bytes upload confusion for users

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#295]
Just making this ticket to keep track of this.  The 0 bytes after upload thing is causing confusion for users.   The UI should update the size somehow, whether by refreshing the page or by some other means.

**Comment by dmachi** [comment]
I believe that @olsonanl  found and resolved this issue in the workspace code.  Bob can you confirm and close if that is the case?

**Comment by olsonanl** [comment]
Yes, this has been fixed.
