### ISSUE TITLE
Can't select home as output folder

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#296]
@brettin has just pointed out that the user can't select their home directory as an output folder.  Here are the steps to replicate:

1) User is at assembly app, clicks on output folder input.

![screen shot 2015-06-15 at 10 49 55 am](https://cloud.githubusercontent.com/assets/1194246/8164103/9f351192-134c-11e5-9ac6-a51636ad5e3e.png)

2) User then sees this:

![screen shot 2015-06-15 at 10 55 22 am](https://cloud.githubusercontent.com/assets/1194246/8164204/2d50ecf8-134d-11e5-9a36-9fb6d5f6b895.png)

Note: "ok" is an option, but doesn't actually work.

3) If the user clicks the 'Parent Folder' item, and then selects home, the user gets "ok" as an option.  This doesn't work either.

![screen shot 2015-06-15 at 10 50 15 am](https://cloud.githubusercontent.com/assets/1194246/8164209/3463797a-134d-11e5-8762-28d4a52fb0af.png)

**Comment by dawenx** [comment]
@nconrad this is a pretty old ticket, since you are our workspace guru now, can you check? i can reproduce step 2, but step 3 seems to work, at least, "home" was left in the output folder after I clicked the 'Parent Folder' item, and then selected home.

**Comment by nconrad** [comment]
Yeah, this is fixed since you can select home now.  I've been meaning to auto-select the currently viewed folder (similar to copy/move/etc) to make things easier/intuitive.
