### ISSUE TITLE
Disease Map (Healthmap) no longer working?

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#297]
The rest of Disease View seems to be working, but the HealthMap portion comes up empty.

https://www.patricbrc.org/portal/portal/patric/DiseaseOverview?cType=taxon&cId=1485

![disease_map](https://cloud.githubusercontent.com/assets/3188570/8164232/b6a39a16-1355-11e5-9ca6-076c4bc2825a.PNG)

**Comment by hyoo** [comment]
Mixed Content: The page at 'https://www.patricbrc.org/portal/portal/patric/DiseaseOverview?cType=taxon&cId=138' was loaded over HTTPS, but requested an insecure resource 'http://healthmap.org/mapframe/?ps=162'. This request has been blocked; the content must be served over HTTPS.

Currently, we are using iframe to http site. They do have https site, but certificate issue as well.

**Comment by hyoo** [comment]
we no longer have disease tab
