### ISSUE TITLE
MINOR (IMHO) - should we check there is a "RefSeq" annotation before putting that on the genome browser

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#3]
Mycobacterium tuberculosis H37RvHA apparently doesn't have "RefSeq" annotation.   So, for example, from its landing page http://patricbrc.org/portal/portal/patric/Genome?cType=genome&cId=757420.3
 and then select the Feature Table tab, if I Click to filter on Annotation Source, RefSeq does NOT appear in the dropdown box - only PATRIC or All.

However, if I select the Genome Browser tab, tracks appear for both PATRIC annotation and RefSeq Annotation.  Should we not a) default try to populate the RefSeq Annotation track if there is no RefSeq annotation b) not provide a RefSeq Annotation in the list of Available Tracks on the left side of the Genome Browser page?

**Comment by mshukla1** [comment]
The refseq track is displayed by default regardless of refseq annotations are there. This is useful for consistency, at least it makes user aware that there are no refseq annotations.
