### ISSUE TITLE
PPI is not working

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#30]
http://www.beta.patricbrc.org/portal/portal/patric/HPITool?dm=tab&cType=taxon&cId=773&hpi=false&bm=

http://www.beta.patricbrc.org/portal/portal/patric/HPITool?dm=tab&cType=taxon&cId=773&hpi=false&bm=

it seems like nginx proxy is not set.

**Comment by dmachi** [comment]
I don't see anything specific to HPI/ppi in the current production config on stahl. Everything is currently being sent to JBOSS aside from thing matching this rule

location ~ ^\/(view|workspace|job|public|js|auth|app|users|login|logout) 

So I'm not sure what needs to be configured for HPI Tool to work.

**Comment by hyoo** [comment]
PPI tool points to http://www.alpha.patricbrc.org/patric/pig/

Checkout https://github.com/cidvbi/pig/tree/patric-prod (branch patric-prod)

Either symbolic link inside /usr/share/jboss_deploy/jboss-as/server/patric/patric_website/webRoot/patric

OR

checkout wherever you want and make proxy so that /patric/pig can point to that directory.

**Comment by dmachi** [comment]
Reassigning to Harry to verify submodule fix works
