### ISSUE TITLE
Expression Import: job list still says DiffExpresison

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#301]
We changed the name of the service in the top nav and the submission page. 

However, when I go to the job list, it still says DifferentialExpression. 

![screen shot 2015-06-16 at 5 42 42 am](https://cloud.githubusercontent.com/assets/1236463/8181331/9c705356-13ea-11e5-881b-234f510e640d.png)

**Comment by dmachi** [comment]
Thats because that is the name on the app_service.

**Comment by aswarren** [comment]
menu item and title have been updated to Diff. Expression Import and Differential Expression Import respectively. So the app_service name is once again appropriate.
