### ISSUE TITLE
model data files should have excel versions

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#302]
we should write native excel versions of the model output files since the first thing Chris does for each of them is to copy and paste the contents into excel

**Comment by nconrad** [comment]
This should be assigned to Chris since the transformation happens on the backend (I can't change the assignee).

**Comment by nconrad** [comment]
Should I close this one as 'won't fix'?

**Comment by mshukla1** [comment]
All output files are tab delimited txt files, hence, can be opened easily in excel. 

I recommend that we simply change the output file extensions to .txt, to make it obvious for users and suggested applications for opening the files. 

-Maulik

**Comment by nconrad** [comment]
The file names end in .fbatbl, cpdtbl, .fluxtbl, etc, to distinguish the data type.   @olsonanl was suggesting to use excel files instead of tab delimited, but I doubt that's going to change anytime soon.
