### ISSUE TITLE
GenomeComparison does not allow users to compare one ref and one external genomes

### ISSUE THREAD

**Issue by levinas** [PATRIC3/patric3_website#306]
The submit button is grayed out in the screenshot:

![screen shot 2015-06-16 at 4 15 37 pm](https://cloud.githubusercontent.com/assets/1056733/8195036/2c999ed8-1445-11e5-9d57-e3e10b849d19.png)

**Comment by maovt** [comment]
Currently "Add Up to 8 Genomes" selection is required.

**Comment by olsonanl** [comment]
Giving to FangFang as he appears to own the backend code; is this a restriction there or on the GUI? If the GUI go ahead and reassign to @maovt since it looks like she wrote the gui.

(It seems to me one should be able to compare an external fasta to a reference genome)

**Comment by maovt** [comment]
I'll work on this. 

Chunhong

**Comment by levinas** [comment]
@maovt Chunhong, any update on this?

**Comment by maovt** [comment]
Fixed
