### ISSUE TITLE
A number of users complaining about Genome Annotation Organism Name and Output name

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#307]
This has been a source of angst for several of the users in the workshop.  We need better instructions, the autofill is problematic with users thinking that they have to take what autofill gives them rather than putting in their own name, and having the differences between Organism Name and Output Name is very confusing for them.  We have to improve this functionality.

**Comment by olsonanl** [comment]
I concur; the autofill is still not behaving reliably. I saw it have the behavior yesterday where the name autofilled, but clicking on it didn’t fill the tax id (this was happening during Jim’s demo IIRC).

Rebecca and I chatted yesterday and we think part of a way to resolve the output name problem is to default the output filename to be the same as the organism name.

On Jun 16, 2015, at 4:49 PM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


This has been a source of angst for several of the users in the workshop. We need better instructions, the autofill is problematic with users thinking that they have to take what autofill gives them rather than putting in their own name, and having the differences between Organism Name and Output Name is very confusing for them. We have to improve this functionality.

**Comment by dmachi** [comment]
I believe the problem with the current approach is this.  If the user chooses an existing name the tax id selector can fill out properly.  If they enter a custom name, then there is no tax id associated with it.  So they are forced to choose an existing name first to complete the tax id and after that they have to edit that name to customize it.  This, I agree, is confusing.  Secondly, most people will want to simply use the same name as organism name for their output name, but we can't say that this decision is universal.

Here is a mockup of how I am thinking to address this issue.

1.  Taxon ID selector comes before the name.  It has a search icon beside it.  You can either type in an ID as you do now or you can click the search icon to search for an ID by name in a popup.
2.  The organism name becomes optional.  If left blank the name will use whatever the name is associated with the taxon ID.  If you type something in that name will be used instead.
3.  The output options become optional from the user's perspective.  If they don't enter anything, the folder will default to a folder based on the job type (annotation, assembly, etc) and the name will default to the value for the organism name (which still follows the rules for number 2 above).  By default the Optional output options/parameters would be minimized.

If we take this approach, the output options would need to be applied to all applications.  Additionally, if the output name already exists at the output folder location, we would need to append an index (e.g., _1, _2) to guarantee its uniqueness.

**Comment by dmachi** [comment]
![untitled](https://cloud.githubusercontent.com/assets/190574/8211256/214f15a4-14e4-11e5-8ae9-30720d189244.png)

**Comment by dmachi** [comment]
And yes, "Optional Output Options" sounds awful and would be something better.

**Comment by olsonanl** [comment]
Would this help with the strange behavior we seem to see that is dependent on if the backing store for the completion data is loaded or not?

On Jun 17, 2015, at 10:24 AM, Dustin Machi <notifications@github.com<mailto:notifications@github.com>> wrote:

I believe the problem with the current approach is this. If the user chooses an existing name the tax id selector can fill out properly. If they enter a custom name, then there is no tax id associated with it. So they are forced to choose an existing name first to complete the tax id and after that they have to edit that name to customize it. This, I agree, is confusing. Secondly, most people will want to simply use the same name as organism name for their output name, but we can't say that this decision is universal.

Here is a mockup of how I am thinking to address this issue.

1. Taxon ID selector comes before the name. It has a search icon beside it. You can either type in an ID as you do now or you can click the search icon to search for an ID by name in a popup.
2. The organism name becomes optional. If left blank the name will use whatever the name is associated with the taxon ID. If you type something in that name will be used instead.
3. The output options become optional from the user's perspective. If they don't enter anything, the folder will default to a folder based on the job type (annotation, assembly, etc) and the name will default to the value for the organism name (which still follows the rules for number 2 above). By default the Optional output options/parameters would be minimized.

If we take this approach, the output options would need to be applied to all applications. Additionally, if the output name already exists at the output folder location, we would need to append an index (e.g., _1, _2) to guarantee its uniqueness.

**Comment by dmachi** [comment]
The backing store doesn't load anything ahead of time, it queries on the fly so I don't think that is the actual problem.  There may be times when it is slow, but it is never required to load fully.  But it would get rid of the co-dependent selections.

**Comment by olsonanl** [comment]
Aha - so you aren’t filling in the genome name at all for completion? That seems good.

I wouldn’t call the output options optional, but would fill in the defaults that you mentioned earlier.

On Jun 17, 2015, at 10:29 AM, Dustin Machi <notifications@github.com<mailto:notifications@github.com>> wrote:


[untitled]<https://cloud.githubusercontent.com/assets/190574/8211256/214f15a4-14e4-11e5-8ae9-30720d189244.png>

**Comment by olsonanl** [comment]
OK; it seems to act differently the first time than it does later on which makes me thing about sluggish queries.

On Jun 17, 2015, at 10:35 AM, Dustin Machi <notifications@github.com<mailto:notifications@github.com>> wrote:

The backing store doesn't load anything ahead of time, it queries on the fly so I don't think that is the actual problem. There may be times when it is slow, but it is never required to load fully. But it would get rid of the co-dependent selections.

**Comment by olsonanl** [comment]
BTW this gets closer to the RAST model where we do no on the fly fillin at all; you type in the tax id, hit “lookup”, and all of the information (including domain and genetic code) is filled for you.

On Jun 17, 2015, at 10:35 AM, Dustin Machi <notifications@github.com<mailto:notifications@github.com>> wrote:

The backing store doesn't load anything ahead of time, it queries on the fly so I don't think that is the actual problem. There may be times when it is slow, but it is never required to load fully. But it would get rid of the co-dependent selections.

**Comment by dmachi** [comment]
Yah, i think it straddles the line and takes good things from both sides.  In terms of secondary changes do you mean that if you select a name, it fills the tax id, but then if you change the name subsequently it doesn't change the taxon id?  That is currently intended behavior (though I can see why it is confusing in some cases).

**Comment by olsonanl** [comment]
FWIW this is how it looks in RAST, and is quite reliable. Not sure we've really had folks asking for the capability of searching by name. However a similar "type in something and search for it" interface, rather than dynamically populating really big dropdowns, might be a way to go.

https://www.youtube.com/watch?v=oWb6I5r2KOI

**Comment by aswarren** [comment]
See the latest annotation interface update.
