### ISSUE TITLE
deleted job in awe shows as failed job in job page

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#309]
Deleting a job from awe should result in job being deleted from job page. Currently, a deleted job in awe displays as a failed job in the job page.

**Comment by olsonanl** [comment]
Per discussion in the room:

Fields we can use to sort the jobs include completion time, start time, submit time, and last update time. Default sort is last update time.

**Comment by dmachi** [comment]
Thinking about this a bit further, I think the way we'd want to show this from the UI is based on a date range.  For example, by default we'd show all jobs from the past week.  So querying by date would be required for this.  Also, the ability to filter by completion status would be useful.

**Comment by nconrad** [comment]
We decided to filter out "deleted" jobs from the UI (with addition of a "kill job" button).   PR was https://github.com/PATRIC3/p3_web/pull/774 and will be on alpha.
