### ISSUE TITLE
RAST, GO Search, EC Search should be removed from Tool list page

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#31]
http://www.beta.patricbrc.org/portal/portal/patric/Tools

**Comment by hyoo** [comment]
1. most of tool links are broken. Need default parameter (taxon Id). 
 - comparative pathway, protein family sorter, pig, Antibiotic Resistance Gene Search, ...

2. default taxon should be consistent unless it makes sense. 
 - trasncriptomics gene list page goes to Mycobacterium, while disease view goes to M.tuberculosis.
 - genome metadata goes to all bacteria, which makes sense.

**Comment by rkenyon** [comment]
GO and EC Searches have been removed.  The Genome Annotation Tool still links to the RAST page, but will be switched over to the Annotation App form page when the production site is released.  Also, will add a Genome Assembly Tool that points to the Assembly App form when the production site is released.

1. These have all been fixed
2. These have been made consistent where appropriate
3. The domain names have been removed.
