### ISSUE TITLE
Names and scale not appearing in Genome Comparison tool

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#310]
When users open up their results, all they see is a page with a line of text.  
![screen shot 2015-06-17 at 8 52 43 am](https://cloud.githubusercontent.com/assets/11475316/8208636/459e8a22-14ce-11e5-8238-f0ef7a34a8cd.png)

**Comment by ARWattam** [comment]
They have to click on the svg image to download it, but the scales isn't available there.  Nor are the list of genomes in the comparison.  You have to open the excel to see that, but then you aren't sure of the order.

**Comment by maovt** [comment]
Hi Fangfang  and Bob,

Could you check the log from the server end to see any error? There is no error reported on the client end. The user genome files used for circos were empty and the comparison features for the user genomes were empty. Fangfang, could you check to see whether the sequences were retrieved successfully and the bi-drectional blast hits were processed successfully for this case?

Thanks,

Chunhong

**Comment by olsonanl** [comment]
I don't see any errors. I will paste stdout and stderr in subsequent comments

**Comment by olsonanl** [comment]
stdout:

-bash-4.1$ cat stdout
Proc proteomes $VAR1 = {
          'description' => 'Compare the proteome sets from multiple genomes using Blast',
          'parameters' => [
                            {
                              'allow_multiple' => bless( do{\(my $o = 1)}, 'JSON::PP::Boolean' ),
                              'desc' => 'Genome IDs',
                              'label' => 'Genome IDs',
                              'default' => undef,
                              'type' => 'string',
                              'id' => 'genome_ids',
                              'required' => 0
                            },
                            {
                              'id' => 'user_genomes',
                              'default' => undef,
                              'allow_multiple' => $VAR1->{'parameters'}[0]{'allow_multiple'},
                              'type' => 'wstype',
                              'required' => 0,
                              'desc' => 'Genome protein sequence files in FASTA',
                              'label' => 'Genome protein sequence files',
                              'wstype' => 'feature_protein_fasta'
                            },
                            {
                              'required' => 0,
                              'id' => 'reference_genome_index',
                              'type' => 'int',
                              'label' => 'Index of genome to be used as reference',
                              'default' => 1,
                              'desc' => 'Index of genome to be used as reference (1-based)'
                            },
                            {
                              'required' => 0,
                              'type' => 'float',
                              'id' => 'min_seq_cov',
                              'label' => 'Minimum coverage of query and subject',
                              'default' => '0.3'
                            },
                            {
                              'label' => 'Maximum E-value',
                              'default' => '1e-05',
                              'type' => 'float',
                              'id' => 'max_e_val',
                              'required' => 0
                            },
                            {
                              'label' => 'Minimum fraction identity',
                              'default' => '0.1',
                              'required' => 0,
                              'type' => 'float',
                              'id' => 'min_ident'
                            },
                            {
                              'required' => 0,
                              'type' => 'float',
                              'id' => 'min_positives',
                              'label' => 'Minimum fraction positive-scoring positions',
                              'default' => '0.2'
                            },
                            {
                              'default' => undef,
                              'label' => 'Output Folder',
                              'desc' => 'Path to which the output will be written. Defaults to the directory containing the input data. ',
                              'required' => 1,
                              'id' => 'output_path',
                              'type' => 'folder'
                            },
                            {
                              'required' => 1,
                              'id' => 'output_file',
                              'type' => 'wsid',
                              'label' => 'File Basename',
                              'default' => undef,
                              'desc' => 'Basename for the generated output files. Defaults to the basename of the input data.'
                            }
                          ],
          'id' => 'GenomeComparison',
          'label' => 'Blast-based genome proteome comparison',
          'script' => 'App-GenomeComparison'
        };
$VAR2 = {
          'min_seq_cov' => '0.3',
          'reference_genome_index' => 1,
          'output_file' => 'test 0615',
          'max_e_val' => '1e-5',
          'output_path' => '/mshukla@patricbrc.org/home/Tests/Genome Comparison',
          'genome_ids' => [
                            '83332.12',
                            '419947.8',
                            '83331.22'
                          ]
        };
$VAR3 = {
          'reference_genome_index' => 1,
          'output_path' => '/mshukla@patricbrc.org/home/Tests/Genome Comparison',
          'output_file' => 'test 0615',
          'min_ident' => '0.1',
          'min_seq_cov' => '0.3',
          'min_positives' => '0.2',
          'genome_ids' => $VAR2->{'genome_ids'},
          'max_e_val' => '1e-5'
        };

/scratch/tmp/_wlgxSX77j/83332.12.faa, 83332.12

/scratch/tmp/_wlgxSX77j/419947.8.faa, 419947.8

/scratch/tmp/_wlgxSX77j/83331.22.faa, 83331.22
curl -H Authorization: un=mshukla@patricbrc.org|tokenid=090730f9-e42d-4127-bc16-5b81d9b66172|expiry=1465992970|client_id=mshukla@patricbrc.org|token_type=Bearer|realm=patricbrc.org|SigningSubject=https://user.patricbrc.org/public_key|sig=9e99f9e48707c2137df39ffa518135c3416e73e01b9ddb1fd40720bc0ad00f8af66f49e2913b615d78b0f6bbb3558fb8a57fd4f3788c8edcea103b7309a9c7d780aca32a709f2420997e7d269e78a09eb1e03df240e05df3a8b6cc4755ad61d820e697911f60e821a5b3feb0b580fa38c256ec9cfe09089ab414afb0b78e48c6 -H Content-Type: multipart/form-data https://www.patricbrc.org/api//genome_feature/?and(eq(genome_id,83332.12),eq(annotation,PATRIC))&select(patric_id,accession,start,end,strand,product,refseq_locus_tag,gene)&sort(+accession,+start,+end)&http_accept=application/json&limit(25000)
curl -H Authorization: un=mshukla@patricbrc.org|tokenid=090730f9-e42d-4127-bc16-5b81d9b66172|expiry=1465992970|client_id=mshukla@patricbrc.org|token_type=Bearer|realm=patricbrc.org|SigningSubject=https://user.patricbrc.org/public_key|sig=9e99f9e48707c2137df39ffa518135c3416e73e01b9ddb1fd40720bc0ad00f8af66f49e2913b615d78b0f6bbb3558fb8a57fd4f3788c8edcea103b7309a9c7d780aca32a709f2420997e7d269e78a09eb1e03df240e05df3a8b6cc4755ad61d820e697911f60e821a5b3feb0b580fa38c256ec9cfe09089ab414afb0b78e48c6 -H Content-Type: multipart/form-data https://www.patricbrc.org/api//genome_feature/?and(eq(genome_id,419947.8),eq(annotation,PATRIC))&select(patric_id,accession,start,end,strand,product,refseq_locus_tag,gene)&sort(+accession,+start,+end)&http_accept=application/json&limit(25000)
curl -H Authorization: un=mshukla@patricbrc.org|tokenid=090730f9-e42d-4127-bc16-5b81d9b66172|expiry=1465992970|client_id=mshukla@patricbrc.org|token_type=Bearer|realm=patricbrc.org|SigningSubject=https://user.patricbrc.org/public_key|sig=9e99f9e48707c2137df39ffa518135c3416e73e01b9ddb1fd40720bc0ad00f8af66f49e2913b615d78b0f6bbb3558fb8a57fd4f3788c8edcea103b7309a9c7d780aca32a709f2420997e7d269e78a09eb1e03df240e05df3a8b6cc4755ad61d820e697911f60e821a5b3feb0b580fa38c256ec9cfe09089ab414afb0b78e48c6 -H Content-Type: multipart/form-data https://www.patricbrc.org/api//genome_feature/?and(eq(genome_id,83331.22),eq(annotation,PATRIC))&select(patric_id,accession,start,end,strand,product,refseq_locus_tag,gene)&sort(+accession,+start,+end)&http_accept=application/json&limit(25000)
-bash-4.1$

**Comment by olsonanl** [comment]
stderr:

-bash-4.1$ cat stderr
tmpdir = /scratch/tmp/_wlgxSX77j
curl -H Authorization: un=mshukla@patricbrc.org|tokenid=090730f9-e42d-4127-bc16-5b81d9b66172|expiry=1465992970|client_id=mshukla@patricbrc.org|token_type=Bearer|realm=patricbrc.org|SigningSubject=https://user.patricbrc.org/public_key|sig=9e99f9e48707c2137df39ffa518135c3416e73e01b9ddb1fd40720bc0ad00f8af66f49e2913b615d78b0f6bbb3558fb8a57fd4f3788c8edcea103b7309a9c7d780aca32a709f2420997e7d269e78a09eb1e03df240e05df3a8b6cc4755ad61d820e697911f60e821a5b3feb0b580fa38c256ec9cfe09089ab414afb0b78e48c6 -H Content-Type: multipart/form-data https://www.patricbrc.org/api//genome_feature/?and(eq(genome_id,83332.12),eq(annotation,PATRIC),eq(feature_type,CDS))&sort(+accession,+start,+end)&http_accept=application/protein+fasta&limit(25000)
curl -H Authorization: un=mshukla@patricbrc.org|tokenid=090730f9-e42d-4127-bc16-5b81d9b66172|expiry=1465992970|client_id=mshukla@patricbrc.org|token_type=Bearer|realm=patricbrc.org|SigningSubject=https://user.patricbrc.org/public_key|sig=9e99f9e48707c2137df39ffa518135c3416e73e01b9ddb1fd40720bc0ad00f8af66f49e2913b615d78b0f6bbb3558fb8a57fd4f3788c8edcea103b7309a9c7d780aca32a709f2420997e7d269e78a09eb1e03df240e05df3a8b6cc4755ad61d820e697911f60e821a5b3feb0b580fa38c256ec9cfe09089ab414afb0b78e48c6 -H Content-Type: multipart/form-data https://www.patricbrc.org/api//genome_feature/?and(eq(genome_id,419947.8),eq(annotation,PATRIC),eq(feature_type,CDS))&sort(+accession,+start,+end)&http_accept=application/protein+fasta&limit(25000)
curl -H Authorization: un=mshukla@patricbrc.org|tokenid=090730f9-e42d-4127-bc16-5b81d9b66172|expiry=1465992970|client_id=mshukla@patricbrc.org|token_type=Bearer|realm=patricbrc.org|SigningSubject=https://user.patricbrc.org/public_key|sig=9e99f9e48707c2137df39ffa518135c3416e73e01b9ddb1fd40720bc0ad00f8af66f49e2913b615d78b0f6bbb3558fb8a57fd4f3788c8edcea103b7309a9c7d780aca32a709f2420997e7d269e78a09eb1e03df240e05df3a8b6cc4755ad61d820e697911f60e821a5b3feb0b580fa38c256ec9cfe09089ab414afb0b78e48c6 -H Content-Type: multipart/form-data https://www.patricbrc.org/api//genome_feature/?and(eq(genome_id,83331.22),eq(annotation,PATRIC),eq(feature_type,CDS))&sort(+accession,+start,+end)&http_accept=application/protein+fasta&limit(25000)
\@genomes = $VAR1 = [
          '/scratch/tmp/_wlgxSX77j/83332.12.faa',
          '/scratch/tmp/_wlgxSX77j/419947.8.faa',
          '/scratch/tmp/_wlgxSX77j/83331.22.faa'
        ];
BBH options: $VAR1 = {
          'min_ident' => '0.1',
          'verbose' => 1,
          'program' => 'blastp',
          'min_cover' => '0.3',
          'min_positives' => '0.2',
          'max_e_val' => '1e-5',
          'blast_opts' => '-a 24'
        };
Run bidir_best_hits::bbh: /scratch/tmp/_wlgxSX77j/83332.12.faa <=> /scratch/tmp/_wlgxSX77j/419947.8.faa
Blasting /scratch/tmp/_wlgxSX77j/83332.12.faa against /scratch/tmp/_wlgxSX77j/419947.8.faa ...
Blasting /scratch/tmp/_wlgxSX77j/419947.8.faa against /scratch/tmp/_wlgxSX77j/83332.12.faa ...
Done blasting
Run bidir_best_hits::bbh: /scratch/tmp/_wlgxSX77j/83332.12.faa <=> /scratch/tmp/_wlgxSX77j/83331.22.faa
Blasting /scratch/tmp/_wlgxSX77j/83332.12.faa against /scratch/tmp/_wlgxSX77j/83331.22.faa ...
Blasting /scratch/tmp/_wlgxSX77j/83331.22.faa against /scratch/tmp/_wlgxSX77j/83332.12.faa ...
Done blasting
curl -H Authorization: un=mshukla@patricbrc.org|tokenid=090730f9-e42d-4127-bc16-5b81d9b66172|expiry=1465992970|client_id=mshukla@patricbrc.org|token_type=Bearer|realm=patricbrc.org|SigningSubject=https://user.patricbrc.org/public_key|sig=9e99f9e48707c2137df39ffa518135c3416e73e01b9ddb1fd40720bc0ad00f8af66f49e2913b615d78b0f6bbb3558fb8a57fd4f3788c8edcea103b7309a9c7d780aca32a709f2420997e7d269e78a09eb1e03df240e05df3a8b6cc4755ad61d820e697911f60e821a5b3feb0b580fa38c256ec9cfe09089ab414afb0b78e48c6 -H Content-Type: multipart/form-data https://www.patricbrc.org/api//genome_sequence/?eq(genome_id,83332.12)&select(genome_name,accession,length)&sort(+accession)&http_accept=application/json&limit(25000)
$gid = $VAR1 = '83332.12';
$out = $VAR1 = '[{"accession":"NC_000962","length":4411532,"genome_name":"Mycobacterium tuberculosis H37Rv"}]';
Wrote table to /scratch/tmp/_wlgxSX77j/genome_comparison.txt
Wrote table to /scratch/tmp/_wlgxSX77j/circos/ref_genome.txt
Wrote table to /scratch/tmp/_wlgxSX77j/circos/comp_genome_1.txt
Wrote table to /scratch/tmp/_wlgxSX77j/circos/comp_genome_2.txt
Wrote table to /scratch/tmp/_wlgxSX77j/circos/karyotype.txt
Wrote table to /scratch/tmp/_wlgxSX77j/circos/large.tiles.txt
circos_opts = $VAR1 = {
          'ref_genome' => '/scratch/tmp/_wlgxSX77j/circos/ref_genome.txt',
          'ideogram' => '/scratch/tmp/_wlgxSX77j/circos/ideogram.conf',
          'karyotype' => '/scratch/tmp/_wlgxSX77j/circos/karyotype.txt',
          'circos' => '/scratch/tmp/_wlgxSX77j/circos/circos.conf',
          'large_tiles' => '/scratch/tmp/_wlgxSX77j/circos/large.tiles.txt',
          'housekeeping' => '/scratch/tmp/_wlgxSX77j/circos/housekeeping.conf',
          'comp_genomes' => [
                              '/scratch/tmp/_wlgxSX77j/circos/comp_genome_1.txt',
                              '/scratch/tmp/_wlgxSX77j/circos/comp_genome_2.txt'
                            ],
          'ticks' => '/scratch/tmp/_wlgxSX77j/circos/ticks.conf',
          'image' => '/scratch/tmp/_wlgxSX77j/circos/image.conf',
          'radius' => 450,
          'is_user_genome' => {
                                '2' => 0,
                                '1' => 0
                              },
          'colors' => '/scratch/tmp/_wlgxSX77j/circos/colors.conf',
          'plots' => '/scratch/tmp/_wlgxSX77j/circos/plots.conf'
        };
Output folder = /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615
Saving /scratch/tmp/_wlgxSX77j/genome_comparison.txt => /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615/genome_comparison.txt ...
$VAR1 = '{"status":200,"data":{"id":"18903b26-ff68-4e05-adb8-66d765766354","version":"114d465ff9ed1d1c6179bcded795e0e0","file":{"name":"genome_comparison.txt","size":1387284,"checksum":{"md5":"874e10d25316cc47565b6255ceee3905"},"format":"","virtual":false,"virtual_parts":[]},"attributes":null,"public":false,"indexes":{"size":{"total_units":2,"average_unit_size":1048576}},"tags":[],"linkages":[],"created_on":"2015-06-15T07:25:51.386-05:00","last_modified":"2015-06-15T07:25:51.566384226-05:00","type":"basic"},"error":null}';
Output folder = /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615
Saving /scratch/tmp/_wlgxSX77j/genome_comparison.json => /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615/genome_comparison.json ...
$VAR1 = '{"status":200,"data":{"id":"1b23ff4c-ba8d-43a0-acaf-4c455db43d79","version":"5e64e55553abb1fce64d701a37e81ff4","file":{"name":"genome_comparison.json","size":4763766,"checksum":{"md5":"8d7863dc23d58e0c9cd0eb19a54b5c39"},"format":"","virtual":false,"virtual_parts":[]},"attributes":null,"public":false,"indexes":{"size":{"total_units":5,"average_unit_size":1048576}},"tags":[],"linkages":[],"created_on":"2015-06-15T07:25:51.731-05:00","last_modified":"2015-06-15T07:25:52.068240857-05:00","type":"basic"},"error":null}';
Output folder = /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615
Saving /scratch/tmp/_wlgxSX77j/circos/ref_genome.txt => /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615/ref_genome.txt ...
$VAR1 = '{"status":200,"data":{"id":"d86f9a78-e69e-4d71-a3ac-f9781ffc8878","version":"a7c52e1e9952035782f03cf3836a7ef9","file":{"name":"ref_genome.txt","size":219397,"checksum":{"md5":"668327e6ccc57508b1f17104ed526c48"},"format":"","virtual":false,"virtual_parts":[]},"attributes":null,"public":false,"indexes":{"size":{"total_units":1,"average_unit_size":1048576}},"tags":[],"linkages":[],"created_on":"2015-06-15T07:25:52.242-05:00","last_modified":"2015-06-15T07:25:52.326219974-05:00","type":"basic"},"error":null}';
Output folder = /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615
Saving /scratch/tmp/_wlgxSX77j/circos/comp_genome_1.txt => /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615/comp_genome_1.txt ...
$VAR1 = '{"status":200,"data":{"id":"59e540e6-44a9-40fa-bbcd-53e6538762ff","version":"91bb41d3e11538edcc4d77965e105287","file":{"name":"comp_genome_1.txt","size":247165,"checksum":{"md5":"c31c2886f25c02899a76bcdcc3c9e060"},"format":"","virtual":false,"virtual_parts":[]},"attributes":null,"public":false,"indexes":{"size":{"total_units":1,"average_unit_size":1048576}},"tags":[],"linkages":[],"created_on":"2015-06-15T07:25:52.483-05:00","last_modified":"2015-06-15T07:25:52.572501315-05:00","type":"basic"},"error":null}';
Output folder = /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615
Saving /scratch/tmp/_wlgxSX77j/circos/comp_genome_2.txt => /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615/comp_genome_2.txt ...
$VAR1 = '{"status":200,"data":{"id":"1ced85bc-ebc5-4dc8-b33e-437d0489b2d8","version":"144e8c1c8565be8d5b80c9125a99d597","file":{"name":"comp_genome_2.txt","size":244583,"checksum":{"md5":"f87ccf77934e88d9875214ff64da470c"},"format":"","virtual":false,"virtual_parts":[]},"attributes":null,"public":false,"indexes":{"size":{"total_units":1,"average_unit_size":1048576}},"tags":[],"linkages":[],"created_on":"2015-06-15T07:25:52.723-05:00","last_modified":"2015-06-15T07:25:52.809329671-05:00","type":"basic"},"error":null}';
Output folder = /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615
Saving /scratch/tmp/_wlgxSX77j/circos/karyotype.txt => /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615/karyotype.txt ...
$VAR1 = [
          [
            'karyotype.txt',
            'txt',
            '/mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615/',
            '2015-06-15T12:25:52',
            'A9F2BD48-1359-11E5-A4BF-B0D8682E0674',
            'mshukla@patricbrc.org',
            33,
            {},
            {},
            'o',
            'n',
            ''
          ]
        ];
Output folder = /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615
Saving /scratch/tmp/_wlgxSX77j/circos/large.tiles.txt => /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615/large.tiles.txt ...
$VAR1 = [
          [
            'large.tiles.txt',
            'txt',
            '/mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615/',
            '2015-06-15T12:25:53',
            'AA06D21A-1359-11E5-A88B-AFD8682E0674',
            'mshukla@patricbrc.org',
            20,
            {},
            {},
            'o',
            'n',
            ''
          ]
        ];
Output folder = /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615
Saving /scratch/tmp/_wlgxSX77j/circos/circos.svg => /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615/circos.svg ...
$VAR1 = '{"status":200,"data":{"id":"80e64250-5040-4e96-8643-c248f5820be9","version":"a52d2505f9cb983e9dc8544860f04cd3","file":{"name":"circos.svg","size":2114804,"checksum":{"md5":"c24b4089f2a6b39d1db7eefcadd95fdd"},"format":"","virtual":false,"virtual_parts":[]},"attributes":null,"public":false,"indexes":{"size":{"total_units":3,"average_unit_size":1048576}},"tags":[],"linkages":[],"created_on":"2015-06-15T07:25:53.151-05:00","last_modified":"2015-06-15T07:25:53.340036538-05:00","type":"basic"},"error":null}';
Output folder = /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615
Saving /scratch/tmp/_wlgxSX77j/circos/legend.html => /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615/legend.html ...
$VAR1 = [
          [
            'legend.html',
            'html',
            '/mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615/',
            '2015-06-15T12:25:53',
            'AA455EAE-1359-11E5-9BA9-AED8682E0674',
            'mshukla@patricbrc.org',
            2420,
            {},
            {},
            'o',
            'n',
            ''
          ]
        ];
Output folder = /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615
Saving /scratch/tmp/_wlgxSX77j/circos/circos_final.html => /mshukla@patricbrc.org/home/Tests/Genome Comparison/.test 0615/circos_final.html ...
$VAR1 = '{"status":200,"data":{"id":"3612b8f9-27f8-483d-88c8-36115af86295","version":"5a1a5ab1d8f47356939100d51f28ac3a","file":{"name":"circos_final.html","size":4610968,"checksum":{"md5":"8d480017c8aeae92b64dd7d18e86d2ec"},"format":"","virtual":false,"virtual_parts":[]},"attributes":null,"public":false,"indexes":{"size":{"total_units":5,"average_unit_size":1048576}},"tags":[],"linkages":[],"created_on":"2015-06-15T07:25:53.6-05:00","last_modified":"2015-06-15T07:25:53.913695521-05:00","type":"basic"},"error":null}';
$VAR1 = [
          [
            'test 0615',
            'job_result',
            '/mshukla@patricbrc.org/home/Tests/Genome Comparison/',
            '2015-06-15T12:25:54',
            'AAF79358-1359-11E5-A46F-AFD8682E0674',
            'mshukla@patricbrc.org',
            4766,
            {},
            {
              'inspection_started' => '2015-06-15T12:25:54'
            },
            'o',
            'n',
            ''
          ]
        ];
-bash-4.1$

**Comment by maovt** [comment]
I tested it and it works now. Please test and let me know any problem.

**Comment by olsonanl** [comment]
I believe this has been confirmed to work now. Closing.
