### ISSUE TITLE
Genome comparison  "Optional external genome (Protein FASTA File)" error

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#311]
A user (huay711) was doing a comparison and accidently started typing in the Optimal external genome box.  She cleared the text from the box, filled in the other parameters and then submitted the job.  When the job returned, although she only entered a reference and a second genome, there were three genomes compared.  I think it was keeping the third optional external genome, even though she had deleted it.

**Comment by olsonanl** [comment]
The job that ran did indeed have that genome included:

GET WS => /scratch/tmp/QMIfWkezU5 SRR1033693_Annotion_test.feature_protein.fasta /huay711@patricbrc.org/home/Annotation test/.SRR1033693_Annotion_test/SRR1033693_Annotion_test.feature_protein.fasta
/huay711@patricbrc.org/home/Annotation test/.SRR1033693_Annotion_test/SRR1033693_Annotion_test.feature_protein.fasta /scratch/tmp/QMIfWkezU5/SRR1033693_Annotion_test.feature_protein.fasta:
\@genomes = $VAR1 = [
          '/scratch/tmp/QMIfWkezU5/386585.9.faa',
          '/scratch/tmp/QMIfWkezU5/83334.142.faa',
          '/scratch/tmp/QMIfWkezU5/SRR1033693_Annotion_test.feature_protein.fasta'
        ];
BBH options: $VAR1 = {
          'max_e_val' => '1e-5',
          'min_ident' => '0.1',
          'min_positives' => '0.2',
          'blast_opts' => '-a 24',
          'verbose' => 1,
          'min_cover' => '0.3',
          'program' => 'blastp'
        };

**Comment by olsonanl** [comment]
In trying to replicate this just now I think I see what might have happened; I selected an optional external genome, and then deleted it. After I fiddled with making an output folder, I noticed the name of the external genome data that I had entered and erased had reappeared.

**Comment by olsonanl** [comment]
I couldn't make that happen again while recording, but I did have problems when I entered then erased the external data file - the form remained with the submit button greyed out

https://youtu.be/xl8p4hGo9yg

**Comment by maovt** [comment]
The selected genome is required to use the "+" button to add to the list.

**Comment by olsonanl** [comment]
Oh right, that is really easy to miss.
OK, I've replicated the problem. The screen capture below 

https://youtu.be/Q_ZNpwI4BT0

shows the submit being done with the optional genome field empty, but we have the following in the submitted job:

$VAR2 = {
          'output_file' => 'bob-1',
          'reference_genome_index' => 1,
          'genome_ids' => [
                            '1458924.3',
                            '1310800.4'
                          ],
          'output_path' => '/PATRIC_Workshop@patricbrc.org/home/bob-tmp',
          'min_seq_cov' => '0.3',
          'user_genomes' => [
                              '/PATRIC_Workshop@patricbrc.org/home/Annotations/.Acinetobacter baumannii 1000160/Acinetobacter baumannii 1000160.feature_protein.fasta'
                            ],
          'max_e_val' => '1e-5'
        };

**Comment by olsonanl** [comment]
Hm. This job failed too. I wonder if that fasta file was bad

-bash-4.1$ cat 21062fe9-b985-4940-9047-2824cb569017/stderr
tmpdir = /scratch/tmp/PzJfRzfuP1
curl -H Authorization: un=PATRIC_Workshop@patricbrc.org|tokenid=dabec705-b368-4a29-940d-65d14498d1a5|expiry=1466107174|client_id=PATRIC_Workshop@patricbrc.org|token_type=Bearer|realm=patricbrc.org|SigningSubject=https://user.patricbrc.org/public_key|sig=bdf4c5752ee2bd516a02029f0e5f040999306b6e29c34054aee780e081f54fbf9c2b0436be9166acad2c7333e4c6ac7f8ca0d33ab3b75d66fdaad7bbc016e3dfe3f17297aec7fa1ca4f9dc30eabcf60b8fe0939d4cff0a413be4c25c7246223a3775f54309f08828af4533f7f586230b380adba991650e980f61d9a0f63b3222 -H Content-Type: multipart/form-data https://www.patricbrc.org/api//genome_feature/?and(eq(genome_id,1458924.3),eq(annotation,PATRIC),eq(feature_type,CDS))&sort(+accession,+start,+end)&http_accept=application/protein+fasta&limit(25000)
curl -H Authorization: un=PATRIC_Workshop@patricbrc.org|tokenid=dabec705-b368-4a29-940d-65d14498d1a5|expiry=1466107174|client_id=PATRIC_Workshop@patricbrc.org|token_type=Bearer|realm=patricbrc.org|SigningSubject=https://user.patricbrc.org/public_key|sig=bdf4c5752ee2bd516a02029f0e5f040999306b6e29c34054aee780e081f54fbf9c2b0436be9166acad2c7333e4c6ac7f8ca0d33ab3b75d66fdaad7bbc016e3dfe3f17297aec7fa1ca4f9dc30eabcf60b8fe0939d4cff0a413be4c25c7246223a3775f54309f08828af4533f7f586230b380adba991650e980f61d9a0f63b3222 -H Content-Type: multipart/form-data https://www.patricbrc.org/api//genome_feature/?and(eq(genome_id,1310800.4),eq(annotation,PATRIC),eq(feature_type,CDS))&sort(+accession,+start,+end)&http_accept=application/protein+fasta&limit(25000)
GET WS => /scratch/tmp/PzJfRzfuP1 Acinetobacter baumannii 1000160.feature_protein.fasta /PATRIC_Workshop@patricbrc.org/home/Annotations/.Acinetobacter baumannii 1000160/Acinetobacter baumannii 1000160.feature_protein.fasta
/PATRIC_Workshop@patricbrc.org/home/Annotations/.Acinetobacter baumannii 1000160/Acinetobacter baumannii 1000160.feature_protein.fasta /scratch/tmp/PzJfRzfuP1/Acinetobacter baumannii 1000160.feature_protein.fasta:
\@genomes = $VAR1 = [
          '/scratch/tmp/PzJfRzfuP1/1458924.3.faa',
          '/scratch/tmp/PzJfRzfuP1/1310800.4.faa',
          '/scratch/tmp/PzJfRzfuP1/Acinetobacter baumannii 1000160.feature_protein.fasta'
        ];
BBH options: $VAR1 = {
          'min_cover' => '0.3',
          'min_positives' => '0.2',
          'min_ident' => '0.1',
          'program' => 'blastp',
          'verbose' => 1,
          'max_e_val' => '1e-5',
          'blast_opts' => '-a 24'
        };
Run bidir_best_hits::bbh: /scratch/tmp/PzJfRzfuP1/1458924.3.faa <=> /scratch/tmp/PzJfRzfuP1/1310800.4.faa
Blasting /scratch/tmp/PzJfRzfuP1/1458924.3.faa against /scratch/tmp/PzJfRzfuP1/1310800.4.faa ...
Blasting /scratch/tmp/PzJfRzfuP1/1310800.4.faa against /scratch/tmp/PzJfRzfuP1/1458924.3.faa ...
Done blasting
Run bidir_best_hits::bbh: /scratch/tmp/PzJfRzfuP1/1458924.3.faa <=> /scratch/tmp/PzJfRzfuP1/Acinetobacter baumannii 1000160.feature_protein.fasta
Blasting /scratch/tmp/PzJfRzfuP1/1458924.3.faa against /scratch/tmp/PzJfRzfuP1/Acinetobacter baumannii 1000160.feature_protein.fasta ...
[formatdb] FATAL ERROR: Database base name must be provided with multiple input files

Blasting /scratch/tmp/PzJfRzfuP1/Acinetobacter baumannii 1000160.feature_protein.fasta against /scratch/tmp/PzJfRzfuP1/1458924.3.faa ...
Done blasting
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "<html><body><h1>400 ...") at /disks/p3/deployment/plbin/App-GenomeComparison.pl line 330.

**Comment by maovt** [comment]
I think this is a common issue for the file selector widget. Dustin, could you look into it?

**Comment by maovt** [comment]
Works now. Please test and confirm. Thanks.

**Comment by olsonanl** [comment]
I just tried it again and I think we're good to go - thanks. Closing.
