### ISSUE TITLE
RNAseq crash (rockhopper)

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#313]
Job from user ijmiller2. 

Alignment in BAM, converted to fastq using tophat tool. That file was submitted to RNAseq against his patric generated genome.

Rockhopper is crashing:

Sequencing reads written to SAM file:   /scratch/tmp/jBdZvcjlBh/Rockhopper/17-June-15_Endobugula_RNA_reads.sam

stderr:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3057
        at Replicate.readInAlignmentFile(Replicate.java:281)
        at Replicate.<init>(Replicate.java:71)
        at Rockhopper.<init>(Rockhopper.java:138)
        at Rockhopper.main(Rockhopper.java:908)

Job is 535e2dda-e0c9-4216-baf3-9155c7e10231

Parameters:

$VAR2 = {
          'single_end_libs' => [
                                 {
                                   'read' => '/ijmiller2@patricbrc.org/home/RNA_seq/17-June-15_Endobugula_RNA_reads.fastq'
                                 }
                               ],
          'recipe' => 'Rockhopper',
          'output_file' => '17-June-15_Endobugula_RNA_reads3.fastq',
          'reference_genome_id' => '62100.3',
          'output_path' => '/ijmiller2@patricbrc.org/home/RNA_seq'
        };

**Comment by olsonanl** [comment]
Persistent problem. I think Tom @brettin wrote to the authors but I haven't heard about us getting a reply.

**Comment by aswarren** [comment]
Another source code problem with Rockhopper. Addressing in September meetup.

**Comment by levinas** [comment]
I reran RNAseq with the closest public genome as reference and the job succeeded. 
Now trying to reproduce the error with the specific genome Bob found for me..

**Comment by aswarren** [comment]
I think we chased down most of these during the Jam session. Is that correct?

**Comment by hyoo** [comment]
@olsonanl @aswarren @levinas This seems very old ticket. Can we close this one?
