### ISSUE TITLE
Error message when loading private genome from workspace

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#314]
It will sometimes end up loading (not always), but while waiting you see this ugly error page
![screen shot 2015-06-17 at 2 30 49 pm](https://cloud.githubusercontent.com/assets/11475316/8216669/9a82e2c0-14fd-11e5-9123-3a075dd4fc46.png)

**Comment by dmachi** [comment]
Removed the duplicate label as this was the original ticket and the dupe was already closed.

**Comment by hyoo** [comment]
This is specific to outdated website.
