### ISSUE TITLE
MSA and tree don't align

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#318]
Andrew, Below are the ids I used in the id mapping and then got the sequences and then ran MSA from there. As we saw, there are few blank nodes in the tree, which messes us tree and MSA alignment. 

fig|176299.10.peg.3564
fig|749927.5.peg.8635
fig|198094.11.peg.4457
fig|260799.14.peg.4455
fig|226900.8.peg.4406
fig|224308.43.peg.2596
fig|281309.8.peg.4272
fig|226186.12.peg.4330
fig|702459.3.peg.1640
fig|206672.9.peg.1610
fig|257313.5.peg.3309
fig|224911.5.peg.1587
fig|272560.6.peg.280
fig|192222.6.peg.1190
fig|190650.5.peg.3250
fig|471472.4.peg.18
fig|272561.5.peg.713
fig|115713.3.peg.840
fig|324602.8.peg.2798
fig|272562.8.peg.1298
fig|441771.6.peg.2400
fig|272563.8.peg.3621
fig|196627.14.peg.865
fig|227377.7.peg.67
fig|243230.17.peg.2026
fig|882.5.peg.346
fig|716541.4.peg.4387
fig|226185.9.peg.2601
fig|585057.6.peg.3450
fig|1133852.3.peg.1029
fig|386585.9.peg.3947
fig|685038.3.peg.2918
fig|585056.7.peg.3430
fig|511145.12.peg.3006
fig|402612.5.peg.229
fig|177416.18.peg.1413
fig|190304.8.peg.1465
fig|243231.5.peg.1131
fig|71421.8.peg.899
fig|85962.8.peg.795
fig|1125630.4.peg.4310
fig|272621.13.peg.1429
fig|220668.9.peg.1322
fig|362948.14.peg.627
fig|272623.7.peg.188
fig|189518.3.peg.1248
fig|169963.11.peg.1373
fig|265311.5.peg.250
fig|233413.5.peg.1109
fig|272631.5.peg.287
fig|246196.19.peg.5331
fig|83332.12.peg.1106
fig|272632.4.peg.543
fig|272634.6.peg.375
fig|242231.10.peg.2386
fig|122586.8.peg.2681
fig|167539.5.peg.1201
fig|208964.12.peg.5478
fig|272943.9.peg.787
fig|243090.15.peg.2597
fig|269796.9.peg.1142
fig|272947.5.peg.473
fig|220341.7.peg.3278
fig|99287.12.peg.3243
fig|211586.12.peg.744
fig|300267.13.peg.3788
fig|198214.7.peg.3446
fig|93061.5.peg.1501
fig|171101.6.peg.2054
fig|568814.3.peg.1935
fig|100226.15.peg.3243
fig|300852.9.peg.1581
fig|243277.26.peg.2362
fig|312309.11.peg.2146
fig|190485.4.peg.3486
fig|393305.7.peg.3611
fig|214092.21.peg.1187

![screen shot 2015-06-19 at 3 47 37 pm](https://cloud.githubusercontent.com/assets/1236463/8262795/bfc708b0-169a-11e5-9cbb-8c0551df3e46.png)

**Comment by aswarren** [comment]
Characters [();,] in the organism name were causing trouble for the newick string parsing, causing the missing labels/sequences and causing the alignment to be off. Fix pushed. Check alpha or beta.
