### ISSUE TITLE
rockhopper output file names are ambigous

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#320]
name rockhopper output files with the user provided output name. Otherwise, rockhopper runs that are different sets of conditions that map to the same reference genome will be named the same.

Also, make RNAseq results visible in the Diff Exp Import chooser.

**Comment by brettin** [comment]
Picture 1: Shows the ambiguity. 

![screen shot 2015-06-20 at 10 15 59 am]
(https://cloud.githubusercontent.com/assets/991769/8267858/8f05c342-1735-11e5-9cb6-4209a31564b6.png)

Picture 2: Shows that the user can not navigate to the .gmx file because the chooser doesn't see the rna seq result object.

![screen shot 2015-06-20 at 10 20 03 am](https://cloud.githubusercontent.com/assets/991769/8267873/fa51f9ea-1735-11e5-972e-efaa76e143e0.png)


Picture 3: Shows that there is an RNA seq result object in the workspace.

![screen shot 2015-06-20 at 10 18 51 am](https://cloud.githubusercontent.com/assets/991769/8267868/da736e38-1735-11e5-811f-8c436cf8c6e1.png)

**Comment by brettin** [comment]
Assigning to Andrew. Andrew, please reassign as necessary.

**Comment by dmachi** [comment]
Andrew, these should prefix the output with the output name like genome annotation does.

**Comment by aswarren** [comment]
The generation of the *.gmx file for rockhopper is a recent addition to the RNA-Seq wrapper. Outside of Fangfang this will probably be easiest for Bob to fix. Assigning it to him.
Bob it looks like this line might be a likely target.
https://github.com/levinas/app_service/commit/c62968a426c66b2769fff314d6d1decdb291bca0#diff-850e7ee9804d73bc168e17d02a37c086R171

 This brings up a more general issue: do we want to require universal prepending for all service output files from now on? This will produce long names and is only informative from outside the job. I think that a more elegant solution would be to show the name of job_result prepended to the file name with a slash so it would be governed by the "OuputName". For example:
my_exp1/Rockhopper_1310581_gene_exp.gmx

**Comment by olsonanl** [comment]
I agree - if the output folder name is already distinguishing, repeating that in the file names just for the purpose of the shortcut dropdowns seems redundant.

On Jun 23, 2015, at 2:08 PM, Andrew Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


The generation of the *.gmx file for rockhopper is a recent addition to the RNA-Seq wrapper. Outside of Fangfang this will probably be easiest for Bob to fix. Assigning it to him.
Bob it looks like this line might be a likely target.
levinas/app_service@c62968a#diff-850e7ee9804d73bc168e17d02a37c086R171<https://github.com/levinas/app_service/commit/c62968a426c66b2769fff314d6d1decdb291bca0#diff-850e7ee9804d73bc168e17d02a37c086R171>

This brings up a more general issue: do we want to require universal prepending for all service output files from now on? This will produce long names and is only informative from outside the job. I think that a more elegant solution would be to show the name of job_result prepended to the file name with a slash so it would be governed by the "OuputName". For example:
my_exp1/Rockhopper_1310581_gene_exp.gmx

**Comment by aswarren** [comment]
@olsonanl @dmachi I have committed some prepend functionality for the ObjectSelector dropdowns. Check out beta.

**Comment by brettin** [comment]
I downloaded 4 rockhopper results recently, they were named the same. I
could rename each after downloading.

**Comment by aswarren** [comment]
The above update should fix the ambiguity issue.
