### ISSUE TITLE
Cannot delete RNA seq results

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#321]
It seems that RNA seq results can not be deleted. I can delete diff exp results, folders, and files. Attached screen shots show the user account, workspace location, and the presence and absence of the delete icon in the vertical column towards the left.

Picture 1: shows no delete icon when selecting an rna seq result

![screen shot 2015-06-20 at 10 10 49 am](https://cloud.githubusercontent.com/assets/991769/8267846/067e0142-1735-11e5-86fc-1497f0f1d663.png)

Picture 2: shows delete icon when selecting a folder

![screen shot 2015-06-20 at 10 14 24 am](https://cloud.githubusercontent.com/assets/991769/8267850/37230900-1735-11e5-8fa0-2a15701eb298.png)

**Comment by brettin** [comment]
Assigning to Dustin so it's not unassigned, Dustin please reassign as necessary.

**Comment by dmachi** [comment]
Fixed and will be pushed to beta soon.
