### ISSUE TITLE
Certs for alpha

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#325]
I recently demo'd some new functionality on beta because there is no practically accessible user login on alpha. This issue is for getting new certs for alpha. @dmachi @olsonanl

**Comment by olsonanl** [comment]
Can you remind me precisely which hostnames we need certs for?

**Comment by dmachi** [comment]
We need a wildcard cert for *.alpha.patricbrc.org like we have for *.beta.patricbrc.org and *.patricbrc.org.

**Comment by olsonanl** [comment]
OK, requested.

**Comment by hyoo** [comment]
any update?
