### ISSUE TITLE
Default button for Show/Hide Columns on Genome Lists doesn't work?

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#326]
e.g. 
https://www.patricbrc.org/portal/portal/patric/GenomeList?cType=taxon&cId=138&dataSource=&displayMode=&pk=&kw=

Use Show/Hide dropdown to remove Genome Status, then Click Default, nothing happens

**Comment by hyoo** [comment]
you have to refresh to apply it. but we will fix the confusion in Nov release.
