### ISSUE TITLE
Delay in being able to submit a new annotation job

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#328]
After I enter and submit one annotation job, I click on the services tab and then select Genome Annotation to do another job (maybe this should just be included on the page when you submit the first annotation...would make it easier).  Nothing happens.  I click and click on Genome Annotation and...nothing.  Twice now I have had to click on Genome Assembly, and then I can click on Genome Annotation and it will get me to the right page.

**Comment by olsonanl** [comment]
Rebecca, are you still seeing this? I'm inclined to chalk this up to a transient in the system unless we can reproduce it.

**Comment by ARWattam** [comment]
Hi Bob,

I submitted a job yesterday and it went fine.

Rebecca

----- Original Message -----

**Comment by olsonanl** [comment]
OK, I'm going to go ahead and close this then.
