### ISSUE TITLE
Crash on webpage after safari restart

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#329]
I was looking at an MSA and got this when I restarted my machine and safari remembered the page:

An error occured
ERROR
Cause: javax.portlet.PortletException: org.apache.jasper.JasperException: An exception occurred processing JSP page /WEB-INF/jsp/msa.jsp at line 28 25: ObjectMapper objectMapper = new ObjectMapper(); 26: ObjectReader jsonReader = objectMapper.reader(Map.class); 27: 28: Map<String, String> key = jsonReader.readValue(SessionHandler.getInstance().get(SessionHandler.PREFIX + pk)); 29: if (key != null) { 30: featureIds = key.get("featureIds"); 31: figfamId = key.get("figfamId"); Stacktrace:
Message: org.apache.jasper.JasperException: An exception occurred processing JSP page /WEB-INF/jsp/msa.jsp at line 28 25: ObjectMapper objectMapper = new ObjectMapper(); 26: ObjectReader jsonReader = objectMapper.reader(Map.class); 27: 28: Map<String, String> key = jsonReader.readValue(SessionHandler.getInstance().get(SessionHandler.PREFIX + pk)); 29: if (key != null) { 30: featureIds = key.get("featureIds"); 31: figfamId = key.get("figfamId"); Stacktrace:
See log for stacktrace

**Comment by mshukla1** [comment]
I suspect this may have something to do with data saved in session/cookie. 

Andrew, see if any action needed or close the ticket.

**Comment by aswarren** [comment]
Yes this is a session based error. Results are thrown out for MSA once a day. We need to convert the system over to running on the cluster and think about whether we want to make them persistent.
