### ISSUE TITLE
search / add to workspace / login issue?

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#33]
working as an "OLD" PATRIC user where I didn't have to login to use Workspace to see how that goes.
So I did a global search (PRJNA259658 if you care), click on 24 genomes, [change table size to show 24], Select All,  Add to Workspace.   So it pops up the login in modal, and I login, and after I'm logged in I'm on a PATRIC Search results page, but all my search results are gone.  Is that the expected behavior (it wasn't for me :-)   clearly)

**Comment by rwill1** [comment]
ok, hold the presses - I just wiped all cookies / cache / everything else, quit the browser, restarted the browser, did global search for the same string, got 0 results, reloaded got 0 results, reloaded (or maybe repasted) got 24 results, reloaded got "ERROR
Cause: javax.portlet.PortletException: org.apache.jasper.JasperException: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to edu.vt.vbi.patric.dao.ResultType
Message: org.apache.jasper.JasperException: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to edu.vt.vbi.patric.dao.ResultType
See log for stacktrace"

**Comment by rwill1** [comment]
OK, now with many of the global search issues issues addressed, I'm back to the 1st question.  I'll repaste here w/ some edits

working as an "OLD" PATRIC user where I didn't have to login to use Workspace to see how that goes.
So I did a global search (PRJNA259658 if you care), click on 24 genomes, [change table size to show 24, Apply to ALL tables], Select All, Add to Workspace. So it pops up the login in modal, and I login, and then I get an error ....   eek different things

error like above or 
modal that says Warning please reenter keyword (I think) hit OK and then eternal spinny

**Comment by hyoo** [comment]
This is related session issue, and fixed on beta. please reopen if you see same problem again.

**Comment by rwill1** [comment]
I just tried this again on beta using both Chrome and Safari.   
search PRJNA259658
genomes
set table size to 24
select all
add to workspace
login in modal
reselect all
add to workspace
and I get the login modal again (even though the header shows that I am logged in)
after the 2nd login, I am able to successfully add to workspace.
Also note that sometimes the table size 24 sticks and sometimes it doesn't
