### ISSUE TITLE
Proteome comparison listed as Genome Comparison in jobs page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#330]
I think that this is one last issue we need to clean up.  We call it Proteome Comparison in the Services folder, but when the job is running it is listed as Genome Comparison
![screen shot 2015-07-10 at 8 04 07 am](https://cloud.githubusercontent.com/assets/11475316/8618277/7dbff706-26da-11e5-9945-54a68f277fdd.png)

**Comment by dmachi** [comment]
Fixed and will be pushed to beta soon.
