### ISSUE TITLE
assembly: same input, different output

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#331]
A user at the florida workshop got some different N# statistics using the same input and recipe as the tutorial. This could point to a pipeline bug or maybe an upload discrepancy.

User's job id: e6ba4909-73ac-439c-83d7-32d483d66db8
Demo job id: a084fe2b-1cfb-4874-8c18-c75051fd3c5c

**Comment by olsonanl** [comment]
I’ll take a look; I need to do a restart on the workspace service to update the admin list so I can pull the files so it’ll be later on.

On Jul 13, 2015, at 10:13 AM, Andrew Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


A user at the florida workshop got some different N# statistics using the same input and recipe as the tutorial. This could point to a pipeline bug or maybe an upload discrepancy.

User's job id: e6ba4909-73ac-439c-83d7-32d483d66db8
Demo job id: a084fe2b-1cfb-4874-8c18-c75051fd3c5c

**Comment by olsonanl** [comment]
The full reports are in ~olson/user.output and demo.output on the seed machines. There are slight differences in the velvet stats. I also see differences in the velvet output here:

[16.085238] Removing reference contigs with coverage < 4.318380...

A little googling implies that velvet is nondeterministic if run with the parallel processing option enabled.
