### ISSUE TITLE
MSA Viewer: no msa for my features

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#333]
Below are the list of features I was trying to produce MSA for. You can cut and paste them in ID mapping and try to generate MSA from there. 

fig|100226.15.peg.2509
fig|107806.10.peg.65
fig|1125630.4.peg.4497
fig|1133852.3.peg.752
fig|115713.3.peg.1030
fig|122586.8.peg.1948
fig|167539.5.peg.801
fig|169963.11.peg.1494
fig|171101.6.peg.1064
fig|176299.10.peg.2178
fig|177416.18.peg.1187
fig|189518.3.peg.2220
fig|190304.8.peg.1883
fig|190485.4.peg.4092
fig|190650.5.peg.3053
fig|192222.6.peg.1614
fig|196627.14.peg.2166
fig|198094.11.peg.4485
fig|198214.7.peg.3686
fig|206672.9.peg.857
fig|208964.12.peg.612
fig|211586.12.peg.1232
fig|214092.21.peg.901
fig|220341.7.peg.3450
fig|220668.9.peg.1657
fig|224308.43.peg.2629
fig|224326.49.peg.1101
fig|224326.49.peg.1102
fig|224911.5.peg.7553
fig|226185.9.peg.1428
fig|226186.12.peg.3997
fig|226900.8.peg.4437
fig|227377.7.peg.1597
fig|233413.5.peg.2604
fig|242231.10.peg.1167
fig|243090.15.peg.3058
fig|243230.17.peg.779
fig|243231.5.peg.3114
fig|243274.5.peg.1466
fig|243277.26.peg.491
fig|243277.26.peg.492
fig|246196.19.peg.4388
fig|257313.5.peg.2358
fig|260799.14.peg.4483
fig|265311.5.peg.269
fig|269796.9.peg.2993
fig|272560.6.peg.6070
fig|272561.5.peg.872
fig|272562.8.peg.1500
fig|272563.8.peg.1526
fig|272621.13.peg.1135
fig|272623.7.peg.590
fig|272631.5.peg.1536
fig|272632.4.peg.505
fig|272634.6.peg.380
fig|272943.9.peg.2342
fig|272947.5.peg.898
fig|281309.8.peg.4301
fig|300267.13.peg.3884
fig|300852.9.peg.1239
fig|312309.11.peg.2290
fig|324602.8.peg.328
fig|324602.8.peg.3283
fig|362948.14.peg.987
fig|386585.9.peg.4119
fig|393305.7.peg.3922
fig|402612.5.peg.502
fig|402612.5.peg.842
fig|402612.5.peg.2099
fig|441771.6.peg.2758
fig|471472.4.peg.175
fig|511145.12.peg.3160
fig|568814.3.peg.1371
fig|585056.7.peg.3724
fig|585057.6.peg.3691
fig|685038.3.peg.3117
fig|702459.3.peg.1383
fig|71421.8.peg.551
fig|716541.4.peg.4554
fig|749927.5.peg.6854
fig|83332.12.peg.2617
fig|85962.8.peg.10
fig|882.5.peg.1642
fig|93061.5.peg.1513
fig|99287.12.peg.3406
<img width="1440" alt="screen shot 2015-07-13 at 2 52 42 pm" src="https://cloud.githubusercontent.com/assets/1236463/8657958/d747a990-296e-11e5-8dfe-2dcee5012589.png">

**Comment by aswarren** [comment]
@mshukla1 This should be fixed now on alpha and beta (its slow to compute). Clear your cache and try it.

![image](https://cloud.githubusercontent.com/assets/229173/8858826/bd27571e-3147-11e5-87f9-7bcb7825c1b5.png)
