### ISSUE TITLE
Weird thing with annotation

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#335]
This annotation job has been going for hours, and I have no yellow button for the queue.
<img width="1297" alt="screen shot 2015-07-13 at 3 15 54 pm" src="https://cloud.githubusercontent.com/assets/7661533/8659692/19f5a06e-2972-11e5-9b06-d82f410bdd61.png">

**Comment by jimdavis1** [comment]
<img width="1297" alt="screen shot 2015-07-13 at 3 15 54 pm" src="https://cloud.githubusercontent.com/assets/7661533/8659712/3beea4b8-2972-11e5-921b-8c5e787bb889.png">

**Comment by olsonanl** [comment]
The second job (ea95d90e-79e5-46ac-9afe-061c4be799de) looks like it may have just completed.

The other one is still queued. Remember we had the problem last time where jobs serialize through the indexing process at the PATRIC side. We talked about solutions but I don't think we ever changed how it works. The jobs are also taking a long time working through the blast for specialty genes, particularly human. I didn't get the updated pushed through the annotation pipeline that fixes the precomputation cache of that data.

**Comment by olsonanl** [comment]
I don't think there's now anything to do here. The indexing speed hs been fixed, and we do the precomputation cache of specialty genes now.
