### ISSUE TITLE
filteringSelect labelFunc displayedValue

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#336]
In several cases there was slight confusion created by a mismatch between the labelFunc value and the displayedValue in the selection. As shown in the GenomeNameSelector.

**Comment by mshukla1** [comment]
Andrew, is this related to to the genome annotation [and/or other services] submission form? 

Do you know how this should be addressed, what category it belongs to, and who should it be assigned to?

**Comment by aswarren** [comment]
This was fixed.
