### ISSUE TITLE
E.C. Number missing from PATRIC record but present in SEED record

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#341]
A user of the U.F. workshop noticed that certain features for Yersinia pestis weren't showing up in the KEGG map as they should.
It turns out the feature lacks an E.C. assignment on PATRIC:
https://www.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=PATRIC.214092.21.NC_003143.CDS.4194309.4195124.fwd

But has it on SEED which we link to:
http://pubseed.theseed.org/?page=Annotation&feature=fig|214092.21.peg.4260

**Comment by mshukla1** [comment]
Bob, this is what the peg in question, fig|214092.21.peg.4260,  is called at different places. 
PATRIC: Thiazole biosynthesis protein ThiG
PSEED: Thiazole biosynthesis protein ThiG
PubSEED: Thiazole synthase (EC 2.8.1.10)
PattyFams: GF00055517 Thiazole biosynthesis protein ThiG

It looks like the function has been recently updated by Sveta. 
7/3/2015	SvetaG	Set master function to Thiazole synthase (EC 2.8.1.10)

Any idea why it did not get reflected in our latest pattyfam recall/run? Or, would it be in the next one?

**Comment by olsonanl** [comment]
Latest build of figfams call this as

fig|214092.21.peg.4260  Thiazole synthase (EC 2.8.1.10) 211     471.848816

So in the update we should get that proper EC.
