### ISSUE TITLE
Services menu wrong in WordPress pages

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#342]
still shows only the 3 old services.  This seems to keep getting overwritten.

example: http://enews.patricbrc.org/faqs/

**Comment by hyoo** [comment]
I can't remember whether I did this before and it has been overwritten by a certain process OR I kept forgetting it. 

Anyway, I have fixed this issue on enews wordpress side.

**Comment by rkenyon** [comment]
Looks to be fixed.
