### ISSUE TITLE
Carousel needs to be slowed down

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#343]
The frontpage carousel is cycling way too quickly (3 sec it looks like) if we want people to actually read the text that is there.

I just timed reading the antibiotic resistance paragraph and it took me 12 seconds to read it without spending any at all trying to deeply understand it. I'd argue for making it on the order of a 30 second cycle at least.

**Comment by rkenyon** [comment]
I'll see if I can adjust it.

Ron Kenyon
PATRIC Project Manager, patricbrc.org
Project Management Director
Virginia Bioinformatics Institute, Virginia Tech
Ph: 540-231-7470

**Comment by rkenyon** [comment]
I have not yet figured out how to do this easily in WordPress.  It may be in the back-end custom code which I have not touched.  I have asked around, and if I don't get a response, I will either reduce the language in the slide or get into the code itself.

**Comment by hyoo** [comment]
increased to 30 sec.
