### ISSUE TITLE
accessing Global Search from the Videos and Tutorials page

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#344]
If I start out on a clean browser at patricbrc.org
Click on 
About dropdown / Videos and Workflows
in the Global Search box search for kp-7
this works and results are returned.

Now go back to a clean browser
Click on 
About dropdown / FAQs
then on the left nav bar click Videos and Tutorials (yes, the wording is slightly different)
in the Global Search box search for kp-7
it just reloads the Videos and Tutorials page

I don't consider it a high priority, but thought the symptom might be interesting to some.   For once, I have no theories :-)

**Comment by hyoo** [comment]
yes, there IS a difference. The first link goes to 
https://www.patricbrc.org/portal/portal/patric/Tutorials

and the second one goes to
https://www.patricbrc.org/portal/portal/patric/Tutorials/

Now you see it.. right?
I will fix it soon though. :)

**Comment by hyoo** [comment]
fixed
