### ISSUE TITLE
Certificate warning going to enews site

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#346]
See attached.
![screen shot 2015-07-17 at 8 12 11 am](https://cloud.githubusercontent.com/assets/2152226/8747947/bfc6e452-2c5c-11e5-9a69-a69f2bdd5a25.png)

**Comment by dmachi** [comment]
Where was this linked from?  As far as I know, links to this page should be http not https (they've never been https before anyway)

**Comment by dmachi** [comment]
Fixed and will be pushed to beta soon.
