### ISSUE TITLE
heatmap (flash) is not loading

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#348]
https://www.patricbrc.org/portal/portal/patric/FIGfam?cType=taxon&cId=773&dm=result&bm=&pk=

and has error as below

GET https://www.patricbrc.org/patric-common/js/heatmap/ProteinFamilySorter.swf net::ERR_CONTENT_LENGTH_MISMATCH

I tried on chrome, firefox and safari, and none of them is working. any idea?

**Comment by olsonanl** [comment]
Hm. It came up for me in both safari and chrome, but it looks different in the two browsers … much more yellow in one than the other.

—bob

On Jul 21, 2015, at 7:49 AM, Harry Yoo <notifications@github.com<mailto:notifications@github.com>> wrote:


https://www.patricbrc.org/portal/portal/patric/FIGfam?cType=taxon&cId=773&dm=result&bm=&pk=

and has error as below

GET https://www.patricbrc.org/patric-common/js/heatmap/ProteinFamilySorter.swf net::ERR_CONTENT_LENGTH_MISMATCH

I tried on chrome, firefox and safari, and none of them is working. any idea?

**Comment by hyoo** [comment]
This was due to the lack of free space. log file was taking 18gb. I have cleaned the log file and changed logging policy in order to less verbose logs.
