### ISSUE TITLE
Pathway summary in tool bar does not appear to be working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#35]
It returns the following error:
ERROR
Cause: java.lang.NullPointerException
See log for stacktrace

**Comment by hyoo** [comment]
would you leave more information? in which page, did you launch pathway summary? what were the selected features? do you have a link that I can reproduce?

**Comment by ARWattam** [comment]
Brucella
>Pathways tab
>entered Glycolysis as Pathway name and filtered
>Clicked the Genes tab in the returned pathway table
>selected the first page of genes
>Clicked on Pathway summary icon

I had wanted to see if genes I knew would have a pathway were turning up blue in the map, but didn't get that far...

----- Original Message -----

**Comment by hyoo** [comment]
this is fixed and available on alpha. Will deploy this beta soon.
