### ISSUE TITLE
Upload file type issue

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#354]
We've seen a couple occurrences here where a multiple file upload resulted in not all of the files uploaded being given the selected file type (one or more showed up as "undefined")

**Comment by mshukla1** [comment]
This is very old ticket and I am not sure whether this is still an issue. I don't remember seeing this recently. Besides, if the files do get uploaded as unspecified, there is a way to change the filetype from the workspace. 

-Maulik
