### ISSUE TITLE
RNAseq error on upload when condition specified without associated read pair

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#355]
Jim submitted a job 8fafd26f-b994-4454-89ac-ea2ee293010e where he defined a condition but didn't upload a data file; it failed with the following error. This should get caught in the UI before submission is committed.

```
$exps = $VAR1 = [
          [
            [
              '/scratch/tmp/QIZPQe9wLt/MHB_R1.fq.gz',
              '/scratch/tmp/QIZPQe9wLt/MHB_R2.fq.gz'
            ]
          ],
          undef,
          [
            [
              '/scratch/tmp/QIZPQe9wLt/COL_75_R1.fq.gz',
              '/scratch/tmp/QIZPQe9wLt/COL_75_R2.fq.gz'
            ]
          ],
          [
            [
              '/scratch/tmp/QIZPQe9wLt/MERO_75_R1.fq.gz',
              '/scratch/tmp/QIZPQe9wLt/MERO_75_R2.fq.gz'
            ]
          ]
        ];
Can't use an undefined value as an ARRAY reference at /disks/p3/deployment/plbin/App-RNASeq.pl line 160.
```

**Comment by aswarren** [comment]
Can you give me a little bit more explanation on how you acheived this? The interface is setup to prevent you adding a read singleton/pair without specifying a condition, when conditions are turned on. Also, its setup to prevent you from submitting unless you have a read in the selected list.

**Comment by olsonanl** [comment]
All the pairs had a condition assigned, but I had created a condition and did not assign a read to it.

**Comment by aswarren** [comment]
Fixed. On production.
