### ISSUE TITLE
upload box will go off screen

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#357]
When I grab a bunch of files to upload to the workspace, if its too many, I cannot view the "upload button" because it is below the bottom of the page, and I can't scroll down.
<img width="1188" alt="screen shot 2015-07-21 at 12 25 20 pm" src="https://cloud.githubusercontent.com/assets/7661533/8810460/0026c8ce-2fa4-11e5-8793-9596d8918e44.png">

**Comment by mshukla1** [comment]
Neal this is still a problem. It would be nice if you can add a vertical scroll bar in the file listing area.
