### ISSUE TITLE
Reset Password should be in the user profile

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#358]
I discovered that the only way to reset your workspace password is to do a "forgot password" from the login window.  This should be a user preference.
<img width="817" alt="screen shot 2015-07-21 at 12 34 01 pm" src="https://cloud.githubusercontent.com/assets/7661533/8810618/ef8eb778-2fa4-11e5-8a06-f4636fd55ec8.png">

**Comment by hyoo** [comment]
no, people needs "reset password" when they no longer remember their password. it has to be in login window so that they can reset and login.
