### ISSUE TITLE
Differential Expression - job gets suspended

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#36]
I tried to upload gene list using the following format:
VBICloDif38397_0011	BDM vs Control (CD630)	-1.61094
VBICloDif38397_0013	BDM vs Control (CD630)	-1.85835
VBICloDif38397_0014	BDM vs Control (CD630)	-1.54013
VBICloDif38397_0017	BDM vs Control (CD630)	1.65133
VBICloDif38397_0021	BDM vs Control (CD630)	1.9105
VBICloDif38397_0029	BDM vs Control (CD630)	-1.70367
VBICloDif38397_0030	BDM vs Control (CD630)	2.72798
VBICloDif38397_0031	BDM vs Control (CD630)	5.00728
VBICloDif38397_0049	BDM vs Control (CD630)	2.58713
VBICloDif38397_0050	BDM vs Control (CD630)	3.32919
...

I selected PATRIC legacy ID.

The job got suspended without any error messages

**Comment by aswarren** [comment]
Both gene list and gene matrix formats require headers as illustrated at

http://enews.patricbrc.org/faqs/transcriptomics-faqs/upload-transcriptomics-data-to-workspace-faqs/

So in this case you would need
Gene IDComparison IDLog Ratio

**Comment by maovt** [comment]
This was the file I used to upload in the old workspace workflow and worked before.

**Comment by maovt** [comment]
I added the header and the job still got suspended.
