### ISSUE TITLE
Alignment tool is broken

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#360]
I can't get the alignment tool to render the alignment.  Here is what it looks like:
<img width="1196" alt="screen shot 2015-07-21 at 3 03 15 pm" src="https://cloud.githubusercontent.com/assets/7661533/8813615/bf5ecb46-2fb9-11e5-84c6-f7878fbc850c.png">

**Comment by jimdavis1** [comment]
https://www.patricbrc.org/portal/portal/patric/MSA?pk=-2181953846986415073

**Comment by jimdavis1** [comment]
Note that the statistics all look okay.

**Comment by olsonanl** [comment]
Hm, it worked for me. Can you bring up the javascript console and see if there is an error there?

**Comment by aswarren** [comment]
@jimdavis1 can you give the feature ID's you were using here? the link doesn't work past a certain amount of time or maybe per session.

**Comment by aswarren** [comment]
This should be working now. Let me know if you have any more problems.
