### ISSUE TITLE
another MSA crash

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#361]
A user with a Eee nettop running windows & chrome is getting crashes on MSA (the Oh Snap broken page window) for this figfam 

https://www.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=PATRIC.61435.4.JPRE01000005.CDS.258443.260041.rev

I initially thought it was a low-memory issue (machine has 2GB RAM) but when I booted up a 500MB VM with windows7 & chrome I was able to get the MSA.

**Comment by hyoo** [comment]
Bob, this link goes to a single feature. Do you have a list of features that the user tried to load? Currently, I cannot replicate the issue.

**Comment by olsonanl** [comment]
Sorry - it was in trying to create a MSA for the features in the figfam assigned to that feature.

It worked for me as well, but failed on the netbook.

—bob

On Jul 29, 2015, at 11:26 AM, Harry Yoo <notifications@github.com<mailto:notifications@github.com>> wrote:


Bob, this link goes to a single feature. Do you have a list of features that the user tried to load? Currently, I cannot replicate the issue.

**Comment by hyoo** [comment]
Andrew, would you take a look at this issue? It might be difficult to reproduce without netbook, though.

**Comment by aswarren** [comment]
The entire figfam (92 members) worked fine for me on a chromebook acer c720 with 2Gb of RAM. That is the only netbook I have access to right now.
