### ISSUE TITLE
clicking on folder icon only partially changes page

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#362]
In my home workspace I clicked on the folder icon for the tests folder, and it looks like the page partially moved - the status at the top says olson / home / tests, but it is still showing the files in my home.

<img width="1445" alt="screen shot 2015-07-22 at 11 18 44 am" src="https://cloud.githubusercontent.com/assets/2152226/8833481/badacc32-3063-11e5-8e2e-ddfc71146cfe.png">

**Comment by dmachi** [comment]
There was a conflict from the select action and the drill down action (dbl click or click on icon).  Added slight delay to the select to allow drilldown to win the race.
