### ISSUE TITLE
Structural Genomics: Not prefilling SSGCID Community Target Request forms w/ known PATRIC info

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#363]
https://www.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=PATRIC.483179.4.NC_010103.CDS.6822.8462.rev
On the PATRIC feature page it says we have a UniProt ID and that there isn't a structure and it gives me the link to submit a community request to SSGCID.   But then the request form isn't isn't pre-filling. like it's supposed to, with the UniProt ID and sequence info, etc.

**Comment by hyoo** [comment]
it was a bug and fixed

**Comment by mshukla1** [comment]
Checked and verified. The information is now pre-filled in the structure request submission form. 

-Maulik
