### ISSUE TITLE
Structural Genomics: Need URL change and GI Number for links to CSGID Community Request form

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#364]
We need to update our URL and add passing (only?) the GI number for requests for structure targets to the CSGID team - example of current bad link on feature page
https://www.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=PATRIC.198214.7.NC_004337.CDS.6918.7958.rev

per email from Jacek Grzebyta of the CSGID team

From: "Jacek Grzebyta Grzebyta" <j.grzebyta@ucl.ac.uk>
To: "Dustin Machi" <dmachi@vbi.vt.edu>
Cc: "rkenyon" <rkenyon@vbi.vt.edu>, "Wayne F Anderson" <wf-anderson@northwestern.edu>, "mshukla Shukla" <mshukla@vbi.vt.edu>, "Rick stevens" <stevens@anl.gov>, "Rebecca Will" <rwill1@vbi.vt.edu>, "Christine Orengo" <c.orengo@ucl.ac.uk>, "Elisabetta Sabini" <e-sabini@northwestern.edu>
Sent: Tuesday, July 15, 2014 12:27:17 PM
Subject: PATRIC - CSGID Submission Portal link

Dear Dustin,

Apologies for such a huge delay! I have found that to fix this problem I needed to solve many other issues. Finally, I can announce that I have solved that task.
To link PATRIC resources with our Submission Portal it is enough to create a following link:

http://csgid-submissions.org/CSGIDSubmissionPortal/?gid=<resource-GI-number> e.g.: http://csgid-submissions.org/CSGIDSubmissionPortal/?gid=7302820

The submission portal accepts multiple GIs as well. In that case put the numbers in comma delimited format. Unfortunately our portal does not support automatic submission and requires the user action.

Regards,
Jacek Grzebyta

**Comment by hyoo** [comment]
Made a change accordingly, but need a verification, since, it goes to a login page.

**Comment by rwill1** [comment]
I tried logging in.  It doesn't look like they're doing anything with the information that we've passed.   Rick owns the action item of restarting a relationship with CSGID if he thinks it's worthwhile.  I think that we can close this until there is a PATRIC / CSGID relationship moving forward again.
