### ISSUE TITLE
shift RNA-Rocket string to Tuxedo

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#365]
It was misleading to put the RNA-Seq strategy as "RNA-Rocket" since none of the methods were created there and the procedure followed is commonly known outside of RNA-Rocket.
For this reason I shifted from the "RNA-Rocket" to Tuxedo on the front end.

We should probably make this change in the RNA-Seq wrapper as well because the results are being  prepended with RNA-Rocket which is potentially confusing.

![image](https://cloud.githubusercontent.com/assets/229173/8854847/125eb1f4-3130-11e5-96a9-93cf99c892bf.png)

Hmm strangely this doesn't seem consistent (both the above and below run on the same day).

![image](https://cloud.githubusercontent.com/assets/229173/8854978/b7a09a42-3130-11e5-8a95-67120f0821db.png)

**Comment by olsonanl** [comment]
Can someone comment why we have that prefix on all the files at all?

**Comment by olsonanl** [comment]
This is the relevant code:

'''
    my @outputs;
    my $prefix = $recipe;
    if ($recipe eq 'Rockhopper') {
        @outputs = run_rockhopper($params, $tmpdir);
    } elsif ($recipe eq 'Tuxedo' || $recipe eq 'RNA-Rocket') {
        @outputs = run_rna_rocket($params, $tmpdir);
        $prefix = 'Tuxedo';
    } else {
        die "Unrecognized recipe: $recipe \n";
    }
'''

so they should be seeing Tuxedo for the RNA-Rocket requests; if we are still seeing RNA-Rocket something weird is going on. Can we verify if that appears still>

**Comment by aswarren** [comment]
In subsequent testing I haven't seen any more occurrences of this. Will reopen if reoccurs.
