### ISSUE TITLE
Structural Genomics - PATRIC is soliciting community structure requests for proteins that already have a structure

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#371]
For example, see http://csgid.org/space_tree/view/IDP04376 for a structure that exists and its PATRIC feature page https://www.patricbrc.org/portal/portal/patric/Feature?cId=PATRIC.195103.10.NC_008261.CDS.2820518.2821972.rev&cType=feature telling users to submit a request for a structure.

**Comment by mshukla1** [comment]
Checked and verified that no list for submitting structure request are displayed where theer are already structures available.
