### ISSUE TITLE
PATRIC AntibioticResistance Data Landing Page has reverted again

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#372]
https://www.patricbrc.org/portal/portal/patric/AntibioticResistance
Reachable from carousel Investigating Antibiotic Resistance link or from Data / Antibiotic Resistance dropdown

In the description at the top, it Is back to saying "In the near future, we will also incorporate antibiotic susceptibility testing results as additional genome metadata"   I know that Ron has fixed this numerous times.  We need to find a way to keep the website from reverting to old content

**Comment by mshukla1** [comment]
Harry, 

It looks like the content on data landing page is not in sync with what is in wordpress. 
Can you please  check? 

https://www.patricbrc.org/portal/portal/patric/AntibioticResistance

This is what it says on in the corresponding wordpress page wright now: 

Antibiotic Resistance refers to the ability of bacteria to develop resistance to antibiotics through gene mutation or acquisition of antibiotic resistance genes. We collect known antibiotic resistance genes from reputed external databases and publications and map them to homologous genes in PATRIC using BLASTP. For more information see Specialty Genes FAQs.

We also incorporate antibiotic susceptibility testing results as additional genome metadata. Summary filterable AMR metadata are available from PATRIC genome lists (see Antimicrobial Resistance and Other Clinical Metadata). Additional AMR data (including panel data when provided), are available for download.

**Comment by rkenyon** [comment]
This keeps happening.  I've pushed the update several, several times.  
Harry figured it out at some point, but I don't know what the long term 
fix is.

Ron Kenyon
PATRIC Project Manager, patricbrc.org
Project Management Director
Virginia Bioinformatics Institute, Virginia Tech
Ph: 540-231-7470

**Comment by hyoo** [comment]
DLP caches will be generated at deploy time.
