### ISSUE TITLE
Problem with download Features from Workspace

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#374]
I created a group, and from my workspace I wanted to download the table so I could look at the amino acid length.  Two problems:  
1.  When I tried to download in excel it said that it wasn't in the right format and failed.
2. I downloaded in text, selected, copied and put it into excel and found that the the text file is also formatted incorrectly.  No tabs between fields and they all run together.  Very frustrating, and quite unattractive as well.

**Comment by dmachi** [comment]
The first part of this is a duplicate issue.  I will check on the text version you are referring to.

**Comment by hyoo** [comment]
This is specific to outdated website.
