### ISSUE TITLE
Workspace-Adding additional columns sometimes doesn't add them

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#378]
I've run into this a couple of times today.  I want to see the AA length and add that column.  It says that it has added it, but nothing pops up.  To fix this I generally have to go back to the higher level (Features) and select the group again.
![screen shot 2015-08-05 at 1 11 37 pm](https://cloud.githubusercontent.com/assets/11475316/9092362/bfe68ba6-3b73-11e5-9a37-0e9170fb289b.png)

**Comment by dmachi** [comment]
This should have been fixed previously on other tickets and is due to size/css. Please verify.

**Comment by hyoo** [comment]
verified
