### ISSUE TITLE
is there a reason that a PATRIC genome metadata doesn't link out to BioSample

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#379]
Actually, I think that both BioSample and Assembly Accession don't link but Pub, BioProject, RefSeq, and GenBank do provide the links

**Comment by mshukla1** [comment]
Nope, no specific reason! :)

We added BioSample and Assembly Accessions in the March data release, started displaying them, but forgot to add links. 

Harry, below are the sample urls for linkouts, please add them when you get a chance. 

BioSample Accession: http://www.ncbi.nlm.nih.gov/biosample/SAMN02585803
Assembly Accession:  http://www.ncbi.nlm.nih.gov/assembly/GCA_000735705.1

<img width="719" alt="screen shot 2015-08-05 at 3 31 36 pm" src="https://cloud.githubusercontent.com/assets/1236463/9097209/b2d52f30-3b87-11e5-8b60-cb7a411a029f.png">
