### ISSUE TITLE
Link to tutorials page from workspace broken

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#380]
Went to workspace, clicked on about: Video & Tutorials, it stayed in the workspace and gave the following page. Notice the url and multiple icons on the page. 

<img width="1440" alt="screen shot 2015-08-05 at 2 23 05 pm" src="https://cloud.githubusercontent.com/assets/1236463/9095684/2ea9bd2e-3b7e-11e5-8616-1a4051501e4b.png">

**Comment by dmachi** [comment]
Fixed and will be pushed to beta soon.
