### ISSUE TITLE
DATA - cleanup of GenBank Accessions metadata in PATRIC

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#381]
Attached is a screenshot of a spreadsheet (sigh)  with 6 representative genomes (not a complete list) showing issues in the genbank_accessions metadata field.  The spreadsheet is the PATRIC download metadata spreadsheet with columns hidden if you want to unhide them to see more info - Maulik has the spreadsheet if you want it, or you can ask me .... Or if I knew how to share a PATRIC workspace ..... 

There are 2 genomes with bugs (one with no link  and one with an erroneous link) 

There are also 4 different formats for what happens if you click on a GenBank link at PATRIC

So one can PROBABLY justify that there's a different format for complete genomes and WGS genomes and I MIGHT back down on a busy day

And one can PROBABLY justify that there's a different format for complete genomes w/o plasmids and complete genomes w/ plasmids and I MIGHT back down on a busy day.

But I DON'T buy 2 different ways to reference WGS genomes at GenBank (one as a search result that returns pointers to all the contigs, and one that points to the WGS master)

We could be consistent by providing all of them as search results pages, but I think we can probably do better
![screen shot 2015-08-05 at 5 39 09 pm](https://cloud.githubusercontent.com/assets/1243115/9098679/4c66844e-3b99-11e5-85e8-af8195ba9be4.png)

**Comment by mshukla1** [comment]
All existing partial genbank accessions for the wgs records have been updated to full accessions. 
For example,  for the genome below, genbank accession has been changed from AWXM02 to AWXM00000000. 
https://www.patricbrc.org/portal/portal/patric/Genome?cType=genome&cId=1389955.3

Changes are visible on the public site.

**Comment by mshukla1** [comment]
I have also added genbank accessions for 654 additional genomes. At this point, I believe, all the genomes that should have genbank accessions have been assigned genbank accessions in PATRIC. 

-Maulik
