### ISSUE TITLE
Workspace-Feature summary-data not in consistent order

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#382]
This is quite annoying.  Everytime I am looking in the summary information to the right of the green bar, it is in a different order.  So I have to look really hard to find the peg id.  It is giving me eye strain!!!  Some examples of the revolving information can be seen below
![screen shot 2015-08-06 at 12 12 25 pm](https://cloud.githubusercontent.com/assets/11475316/9116871/a67d297e-3c34-11e5-8b02-27f76caeb5f1.png)
![screen shot 2015-08-06 at 12 09 32 pm](https://cloud.githubusercontent.com/assets/11475316/9116869/a67aa53c-3c34-11e5-8b59-7d02e69fa581.png)
![screen shot 2015-08-06 at 12 08 58 pm](https://cloud.githubusercontent.com/assets/11475316/9116872/a67d8842-3c34-11e5-8ce0-3c0cf6079a40.png)
![screen shot 2015-08-06 at 12 08 40 pm](https://cloud.githubusercontent.com/assets/11475316/9116870/a67bc368-3c34-11e5-972c-0f24c950bff2.png)

**Comment by dmachi** [comment]
This is simply because the default/fall through viewer of this information shows the data in the order it comes back from solr.  We can either make a specific viewer for each type or do something like alphabetize the output so it is consistently ordered.

**Comment by ARWattam** [comment]
I think alphabetical would be fine.  It really is annoying to try and sift through all the lines of data

**Comment by mshukla1** [comment]
I agree with Rebecca.

**Comment by dmachi** [comment]
I've changed the default to list these properties in alphabetical order. Not pushed to production yet.
