### ISSUE TITLE
Global search being naughty

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#383]
This happens about 20% of the time when I'm using global search to find a peg ID.  In this instance, I entered "fig|359391.4.peg.3403" and the search returns nothing, but when I look at the search box again, it has entered some additional characters into the search.  I know to redo the search, but a less sophisticated user than Moi might just think that the data doesn't exist and get really angry.  See attached screenshot to see what I'm complaining about
![screen shot 2015-08-06 at 12 18 14 pm](https://cloud.githubusercontent.com/assets/11475316/9117002/811df4c8-3c35-11e5-8c91-1dfe871b25f2.png)

**Comment by mshukla1** [comment]
Rebecca, I tried this multiple times, global search as well as going off to some other page and coming back to global search using back button. 

I believe you, and I think I have seen this behavior in past.  But, I can not reproduce the problem. 
Can you tell if it is totally random? Or, how to reproduce it? 

-Maulik

**Comment by ARWattam** [comment]
I believe that it is totally random, but I will send you each one that I have trouble with.  I think it has something to do with the pipe symbol.

Rebecca

----- Original Message -----
