### ISSUE TITLE
DATA - cleanup of PATRIC metadata for Isolation source / Isolation Site / Body Sample Site / Body Sample Subsite

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#384]
For Posterity
PATRIC metadata fields Isolation source / Isolation site are leftovers from earlier PATRIC / BRC / GSCID  metadata sheets
Body Sample Site / Body Sample Subsite are from HMP (and are carried in BioSample in key-value pairs)
The new GCID / BRC metadata template defines 3 fields
- Specimen Category (says whether it is clinical / host associated or environmental)
- Specimen Type  - for host associated
- Environmental Material for environmental samples

PATRIC is going to map all of this into 2 fields - Isolation source (same as GenBank metadata name) and Specimen Category 

So the action items
Rebecca will
- decide what the values will be for the Specimen Category field (NIAID template says the valid values are  "Clinical/host-associated pathogen" or "environmental/food/other pathogen”  so these are the values you MAY ... or may not ... get from the GCIDs going forward)
Maulik will 
- merge isolation site information into Isolation Source - and give to Rebecca to curate 
- merge Body Sample Site and Subsite into Isolation Source and prefill the Specimen Category with whatever the "host associated" value is
Rebecca will
- curate the Isolation Source values from the Isolation Source / Site field merger 
- fill in the Specimen Category field if obvious for the non HMP data
- presumably the HMP data is pretty clean and will not need curating?
Harry will 
- fix the website to display the new fields

**Comment by mshukla1** [comment]
I will try to consolidate the metadata attributes as discussed and work with Rebecca to populate appropriate values. 

I will need to work with Harry to make necessary changes on the website to reflect the changes in the metadata schema. 

-Maulik

**Comment by mshukla1** [comment]
- Isolation site is now merged into isolation source. I have removed all isolation site values. We will remove the field in the next website release. 

- Body_sample_subsite is now merged into body_sample_subsite. I have removed all body_sample_subsite values for now. We will rename this field to  "Specimen Category" or something in the next website release.
