### ISSUE TITLE
DATA - enhance  JCVI Klebsiella AMR metadata based on comparison with NCBI

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#385]
from Maulik's 16-July email to the team, the differences are
- BioSample mismatch - NCBI will fix theirs
- Drug name (minor) mismatch - suggest that NCBI add a synonym, PATRIC does nothing
- PATRIC missing SIR values  aka phenotype interpretation - Maulik will add these to PATRIC from NCBI
- PATRIC missing vendor / testing platform - Maulik will add these to PATRIC from NCBI

**Comment by mshukla1** [comment]
Any differences in the metadata have been reconciled and all additional AMR metadata from NCBI have been incorporated into patric.
