### ISSUE TITLE
Update protein families / PattyFams

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#386]
Recompute local and global families [Bob, 1 pw]
Evaluate families programmatically / quantitative [Maulik, 0.5pw]
Manual review of protein families by biologists [Rebecca, Veronica, Sveta, 1pw each]
Recall function for all genomes [Bob, 1pw]
Update recall data in solr [Maulik, 1pw]
Update download files [Maulik 0.5pw]

**Comment by hyoo** [comment]
I need to work on it as well. If we want to completely switch to new family id, my part will be minimum, but  if we want to have a UI control, and let users choose family type (FIGfam vs PattyFarms), I may need a few more days.

**Comment by mshukla1** [comment]
Done.
