### ISSUE TITLE
Minor data / metadata enhancements / cleanup

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#388]
Add missing PATRIC ids for ~500 genes
Add missing genome sequences
Add missing protein sequences
Remove plasmid only genomes and test genomes
Metadata: 
Add strain names to genome names, 
correct no of sequences, 
add tRNA and rRNA counts

**Comment by mshukla1** [comment]
- [x] Add missing PATRIC ids for ~500 genes - DONE
- [x] Add missing genome sequences 
- [x] Add missing protein sequences - DONE
- [x] Remove plasmid only genomes and test genomes
- [x] Metadata: 
- [x] Add strain names to genome names - DONE 
- [x] correct no of sequences - DONE
- [-] add tRNA and rRNA counts -- not critical
