### ISSUE TITLE
Unable to add genes to Features group from Protein Family Table

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#396]
I have added the same genes to the same group 4 times this morning in my workspace and while I was able to create the group from the gene page, but when I go to the Protein Family page by following the FIG id, I cannot add additional genes to that group.  When I go to the individual gene pages from the table, I can add them to the group.

I was doing it from the protein family table a couple of days ago and it worked fine.  What changed?

**Comment by hyoo** [comment]
This is specific to outdated website.
