### ISSUE TITLE
MSA: only partial alignment shown after changing color scheme

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#397]
Select a bunch of proteins with reasonable length, so that you get horizontal scroll bar in the alignment. 
The whole alignment is displayed when it loads first. Try to change color to clustal/clustal2. Only first part 
of the MSA is displayed. If you try to scroll to the right, web logos are displayed for the full alignment, 
however, the alignment it self is not. This =has happened multiple times over multiple days, on both pub and beta. 
![screen shot 2015-08-14 at 11 36 55 am](https://cloud.githubusercontent.com/assets/1236463/9278941/cd3bbcf6-4279-11e5-926b-14acd90401fc.png)
![screen shot 2015-08-14 at 11 36 08 am](https://cloud.githubusercontent.com/assets/1236463/9278942/cd4483a4-4279-11e5-90a9-455783b784da.png)

Scereenshot attached.

**Comment by aswarren** [comment]
This bug is proving hard to replicate. I have seen it before but I can not make it reliably happen. If any of the people using the MSA viewer frequently @mshukla1 @jimdavis1 @olsonanl have any insight into how to make this show up consistently it would be extremely helpful.

**Comment by aswarren** [comment]
No longer possible since we prevent full canvas expansion.
