### ISSUE TITLE
DATA - Need to clean up some TB-ARC Mali genomes (different "genomes" have same GenBank Accession)

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#4]
From Maulik - "There was a set of 48 "Mycobacterium tuberculosis" genomes with same name and same project id, some of them were included in PATRIC before, with different name and project id and probably different sequence version. Will have to reconcile them later."

in response to 
At PATRIC - 2 genomes have the same GenBank Accession JKXM
http://patricbrc.org/portal/portal/patric/Genome?cType=genome&cId=1773.204

and

http://patricbrc.org/portal/portal/patric/Genome?cType=genome&cId=1773.174

others that may have the same problem (but not limited to)
        JKXO01
        JKXR01
        JKXM01
        JKXN01
        JKXP01
        JKXQ01
        JKXS01
        JKXT01

**Comment by mshukla1** [comment]
This issue is similar to #190

**Comment by mshukla1** [comment]
75 Mtb genomes were loaded multiple times in the database. Redundant copy of these genomes have been removed from the database.
