### ISSUE TITLE
KEGG save map gives NULL pointer exception

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#402]
![image](https://cloud.githubusercontent.com/assets/229173/9314362/60789678-44f6-11e5-9af4-600b442bc937.png)

Clicking 'Save Map' does not work

![image](https://cloud.githubusercontent.com/assets/229173/9314374/72ae60ac-44f6-11e5-9864-40fa15a408eb.png)

**Comment by hyoo** [comment]
I cannot reproduce this problem. Would you please provide context? Which pathway_id? which taxon or genome were you in?
