### ISSUE TITLE
Uploading experimental data to PATRIC-appears only in workspace, not where I could analyze with transcriptomic tools

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#406]
We uploaded an RNA seq experiment and then talked about how you could look at up and down regulation, or at your own microarray data using the transcriptomic tool suite.  When we go to the genome, to the transcriptomics tab, you don't see the data.  We uploaded it AGAIN, and it did not appear.  This seems to be broken.

**Comment by mshukla1** [comment]
BYO transcriptomics data is not as fully integrated with the public data as BYO genomes. 

That means, user uploaded transcriptomics data, specially differential expression data, appears only in the user workspace. 
IT is not displayed at the taxon/genome/gene level pages. Those pages show only public trabscriptomics data. 

The only way to compare public and private data WAS to put them in the same experiment group and then launch gene list from there. 
However, with the redesign of the workspace, we lost the ability to add private experiments to experiment groups, which needs to be 
supported again as soon as possible. 

Assigning it to Dustin: ability to add private differential gene expression datasets to the experiment group, like we had in P2. 

-Maulik

**Comment by hyoo** [comment]
This is specific to outdated website.
