### ISSUE TITLE
Remove BLAST temporarily

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#408]
Remove BLAST temporarily
- widget on the home page
- links from the searches/tools menu
- and widgets/links from any other places on the website 

We will resume them when we have next version of BLAST service working

-Maulik

**Comment by hyoo** [comment]
1. from homepage, it is already removed. (see https://www.patricbrc.org/portal/portal/patric/Home)

2. This needs 3 changes:
 - JBoss: I have removed and committed to repo. This is available on beta and will be deployed on prod at release.
 - enews: I have removed. This is available on production now.
 - p3web: need change from Dustin.

3. I don't know any other place other than two above.

**Comment by dmachi** [comment]
Fixed for p3web, will push to beta soon.
