### ISSUE TITLE
Can't load genomes from phylogeny viewer

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#41]
It looks like I'm creating a group, and then nothing appears in my workspace:
http://www.beta.patricbrc.org/portal/portal/patric/Phylogeny?cType=taxon&cId=234

**Comment by hyoo** [comment]
I think this is related to the workspace JS api pointing wrong solr instance. it works now on beta.
Please feel free to reopen this issue if you want to discuss further or other problem related.
