### ISSUE TITLE
figfam member list: show only CDSs

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#410]
The figfam member list page, the one that is linked from the figfam id on the genome overview page, 
currently lists both CDSs and pseudogenes. Please change it to show only CDSs. 

-Maulik

![screen shot 2015-08-24 at 11 29 48 am](https://cloud.githubusercontent.com/assets/1236463/9445784/7b4400a2-4a53-11e5-8e80-3e686b88eec0.png)

**Comment by hyoo** [comment]
#395
