### ISSUE TITLE
ID Mapping: handle blank lines in the id list

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#413]
If user provides a list of identifiers with any blank lines in them, search returns 0 results. 

The blanks should be handled correctly and ignored from the list. Here is an example: 

Rv0001

Rv0088
Rv0897c
Rv0898c
Rv0899

**Comment by mshukla1** [comment]
Try the list below. For some reason, it is not working, gives zero results. 

Rv0001

Rv0088
Rv0897c
Rv0898c
Rv0899
Rv0900
Rv0901
Rv0902c
Rv0903c
Rv0904c
Rv0905
Rv0906


Rv0907
Rv0908

Rv0909
Rv0910
Rv0911
Rv0912

Rv0913c
Rv0089
Rv0914c
Rv0915c
Rv0916c
Rv0917

**Comment by hyoo** [comment]
Have you cleared browser cache?

**Comment by mshukla1** [comment]
Seems to be working now. Thanks.
