### ISSUE TITLE
PPI: PPI graphs not showing up sometimes

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#416]
I think, probably, the reason is that interactor ids are not mapped to PATRIC ids?!!!

Example: Mycobacterium H37Rv 
https://www.beta.patricbrc.org/portal/portal/patric/HPITool?dm=tab&cType=genome&cId=83332.12&hpi=false&bm=

![Uploading Screen Shot 2015-08-26 at 2.37.10 PM.png…]()

It does work for brucella through, which shows patric ids in the table. 

https://www.beta.patricbrc.org/portal/portal/patric/HPITool?dm=tab&cType=taxon&cId=234&hpi=false&bm=

**Comment by olsonanl** [comment]
Commenting

**Comment by olsonanl** [comment]
It worked.
