### ISSUE TITLE
Genes on the reverse strand need the start and stop indicators switched

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#42]
The start and end in the annotation box are the same if the gene is on the forward or reverse strand.  They should be switched when the gene is on the reverse strand (end comes before start)
http://patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=PATRIC.521006.8.NC_011035.CDS.787694.787807.rev

**Comment by mshukla1** [comment]
We never had them reversed in the history of the project. Start is always the left most coordinate on the chromosome and end is always the right most coordinate. The directionality is represented by the strand field. This is consistent with the gff/ptt and other file formats.
