### ISSUE TITLE
Legend on KEGG pathway map is wrong

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#420]
The legend shows that the olive drab color is listed as "Not annotated" but it should say that only some of the genomes have this EC number.  Language could be "Present in some, but not all genomes"
![screen shot 2015-08-27 at 10 23 13 am](https://cloud.githubusercontent.com/assets/11475316/9523027/02b5fc94-4ca6-11e5-971c-c167d5182efe.png)

**Comment by ARWattam** [comment]
Also, when you are looking across groups of genomes, none are selected.  This legend should read as follows
White box: Not annotated
Green box: Annotated
Olive box: Present in some genomes
Blue box: Selected genes (or something like that....)

**Comment by ARWattam** [comment]
I forgot one:
Red box: Selected from EC table

**Comment by hyoo** [comment]
Would you check whether this is correct now?
https://www.patricbrc.org/portal/portal/patric/CompPathwayMap?cType=taxon&cId=234&dm=&feature_id=&ec_number=&map=00010&algorithm=PATRIC&pk=

**Comment by ARWattam** [comment]
Looks good except for the blue box.  What if we said something like..."From selected feature group".  Or "From selected gene group"

Does anybody else have any ideas?

----- Original Message -----

**Comment by mshukla1** [comment]
I like "Selected" or "Selected Genes" better, because genes can be selected from multiple places in multiple ways, in addition to gene group/feature group. 

-Maulik

**Comment by ARWattam** [comment]
So what are we going with?  I don't like Selected.  Selected Genes would be better.

**Comment by mshukla1** [comment]
I had the same thought at first. But, then, given that we already have have “Annotated” / “Not annotated” and 
“Annotated in some genomes” as legend, without qualifying it with genes or EC numbers, I thought 
“Selected” would fit the pattern, no?

…I am fine with either though. Your call.
