### ISSUE TITLE
Antibiotic Resistance Gene Search error

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#421]
When I go to the antibiotic gene search from the data landing page, get errors. 

https://www.patricbrc.org/portal/portal/patric/AntibioticResistanceGeneSearch

<img width="1440" alt="screen shot 2015-08-27 at 7 40 28 pm" src="https://cloud.githubusercontent.com/assets/1236463/9536610/800607c8-4cf3-11e5-9242-e4538a337f30.png">

**Comment by hyoo** [comment]
this is a problem of link. As error message says, we should have context params when we call the search page. The search itself has not broken. I will update wordpress to fix the link.

**Comment by hyoo** [comment]
fixed and available on production.
