### ISSUE TITLE
SVG download from circular viewer appears to be flawed

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#422]
I have downloaded genome data from the circular viewer, but I can't open it in Adobe Illustrator.  I can open other svg files in Adoble Illustrator, so I am beginning to feel that the problem is with what is being downloaded from PATRIC.

**Comment by mshukla1** [comment]
Don't have Adobe Illustrator, so can't check it myself. 

Harry, please check with Rebecca and see if it is the problem with the file format or the app not understanding the file extension or something. 

-Maulik

**Comment by hyoo** [comment]
This ticket refers to the circos and we already have new circular viewer in production.
