### ISSUE TITLE
DATA possible AMR data addition

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#423]
as part of the NIAID / NCBI / PATRIC calls, we compared our JCVI (Klebsiella) AMR data to what was at NCBI.  

Maulik's mail to the team said

3. PATRIC has only MIC measurements, no SIR values / resistance phenotype  interpretations. The SIR designations are not present in the metadata we received from JCVI. Also, given that we do not know the year and testing standards used, we cannot translate the given MIC values to SIR. 
4. PATRIC does not have the vendor and testing platform information, as it wasn't provided in the metadata. 

Bill Klimke replied
these last two look like additional info that was supplied to us by JCVI. Does it meant that PATRIC will copy the values from NCBI's biosamples, or is this something PATRIC will follow-up with JCVI about?

So the question is, do we want to pick up the S/I/R values and the planform information from NCBI BioSamples and include them in PATRIC.   Should be easy enough to do since Maulik already has the info in a spreadsheet.

**Comment by mshukla1** [comment]
all additional AMR metadata from NCBI have been incorporated into PATRIC.
