### ISSUE TITLE
"Save Map" on the KEGG map in the comparative pathway view not working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#427]
When I click on "Save Map" it should open a window that shows the entire pathway map.  Instead I got this:
![screen shot 2015-09-03 at 11 55 56 am](https://cloud.githubusercontent.com/assets/11475316/9663542/f8a1a054-5232-11e5-9ac4-daa9f9fa454f.png)

**Comment by hyoo** [comment]
this works in the new website. closing this issue.
