### ISSUE TITLE
figfam id does not match to production description

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#428]
for example, 
http://harad.vbi.vt.edu:8983/solr/genome_feature/select?q=patric_id:fig|445986.17.peg.17&wt=json&indent=true

this feature says figfam_id is FIG00434305, but in product, FIG00434306: hypothetical protein

**Comment by olsonanl** [comment]
Yup, that happens. Not a bug. The annotations (esp of hypotheticals) and figfam ids of the proteins drifted.

—bob

On Sep 3, 2015, at 11:01 AM, Harry Yoo <notifications@github.com<mailto:notifications@github.com>> wrote:


for example,
http://harad.vbi.vt.edu:8983/solr/genome_feature/select?q=patric_id:fig|445986.17.peg.17&wt=json&indent=true<http://harad.vbi.vt.edu:8983/solr/genome_feature/select?q=patric_id:fig%7C445986.17.peg.17&wt=json&indent=true>

this feature says figfam_id is FIG00434305, but in product, FIG00434306: hypothetical protein

**Comment by mshukla1** [comment]
I believe, many of the hypothetical product names are stripped off of the FIGXXXXX in the new recall. 
That, plus the fact that now we have alternate protein families, hopefully, will reduce the confusion going forward. 

However, there may still be some with FIGXXXXX in the product names. It is part of manual curation in CoreSEED. We will not be addressing this issue.
