### ISSUE TITLE
Missing tabs on gene feature page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#429]
I was seeing this a lot last night, and now I'm seeing it again.  I click on a gene from the search results and while the information appears to load, the tabs across the top of the page that give me access to the genome browser, compare region viewer, etc. are all missing.  This is VERY annoying as there are few times that I want to look at the genome browser, but this happens to be one of them.
![screen shot 2015-09-03 at 1 25 19 pm](https://cloud.githubusercontent.com/assets/11475316/9665614/6e28f8ca-523f-11e5-8947-4f83e19e8829.png)

**Comment by mshukla1** [comment]
Harry , I saw the same think just now [tabs disappeared], when I pinged you on skype and you told me jaboss having problem. 

I wonder if the disappearance of the tabs is related to the jboss problems!!

-Maulik
