### ISSUE TITLE
404 not found on Interactions link

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#43]
From a protein page  e.g.

http://www.beta.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=RefSeq.1403831.3.HG738867.CDS.12163.14079.fwd

when I click the interactions tab I get a 404:

http://www.beta.patricbrc.org/portal/portal/patric/HPITool?dm=tab&cType=feature&cId=PATRIC.1403831.3.HG738867.CDS.12163.14079.fwd&hpi=false&bm=

**Comment by hyoo** [comment]
I don't know how to merge issues. This is a duplicated issue as  following,

https://github.com/PATRIC3/patric3_website/issues/30

I am going to close this one and will continue discuss on the other one.
