### ISSUE TITLE
Cufflinks patch deployment

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#431]
Passed a shell script for installing updated cufflinks to @olsonanl

**Comment by aswarren** [comment]
Just a ping on this. I've got some RNA-Seq jobs that seem rather long running. I'm not sure if its Cufflinks but it seems possible.

**Comment by olsonanl** [comment]
Is this still the right hash?

hash="753c109e31818dcf7aa8a2c8ecdac4fa43d2ab9b"

**Comment by aswarren** [comment]
Yes thats right.

-Andrew

**Comment by olsonanl** [comment]
I have a new version of the cufflinks tools built on a staging machine; do you have an incantation that we can use as a quick test, or is it likely we're ok? We've gone from version:

cuffcompare v2.2.1 (4237)

to

cuffcompare v2.2.2 (exported)

**Comment by aswarren** [comment]
I think we will be ok.

That being said, probably the easiest way to test is using this command
from the readme (though there might be a slight shift in results if they
have adjusted their processing logic):

cufflinks ./test_data.sam

You should see the following output:

[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
File ./test_data.sam doesn't appear to be a valid BAM file, trying SAM...
[13:23:15] Inspecting reads and determining fragment length distribution.
> Processed 1 loci.                            [*************************] 100%
Warning: Using default Gaussian distribution due to insufficient
paired-end reads in open ranges.
It is recommended that correct paramaters (--frag-len-mean and
--frag-len-std-dev) be provided.
> Map Properties:
>       Total Map Mass: 102.50
>       Read Type: 75bp x 75bp
>       Fragment Length Distribution: Truncated Gaussian (default)
>                     Estimated Mean: 200
>                  Estimated Std Dev: 80
[13:23:15] Assembling transcripts and estimating abundances.
> Processed 1 loci.                            [*************************] 100%

Verify that the file transcripts.gtf is in the current directory and looks
like this (your file will have GTF attributes, omitted here for clarity)

test_chromosome Cufflinks       exon    53      250     1000    +       .
test_chromosome Cufflinks       exon    351     400     1000    +       .
test_chromosome Cufflinks       exon    501     550     1000    +       .

**Comment by olsonanl** [comment]
This is complete. I have added eigen and cufflinks build scripts to bootstrap at 

https://github.com/olsonanl/bootstrap/tree/master/p3_eigen
https://github.com/olsonanl/bootstrap/tree/master/p3_cufflinks

This now makes use of the late-model gcc and boost installation in /disks/patric-common/runtime/gcc-4.9.3
