### ISSUE TITLE
Genomes not in alphabetical order in genome groups when in tool

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#434]
When you are looking at a number of genomes, and you want to deselect a few, it would help if they were listed alphabetically.  Its hard to find individual genomes otherwise.
![screen shot 2015-09-09 at 2 01 31 pm](https://cloud.githubusercontent.com/assets/11475316/9769988/76ff99d4-56fb-11e5-8a21-3fed0c48b9e4.png)

**Comment by hyoo** [comment]
This is specific to outdated website.
