### ISSUE TITLE
Can't download all heatmap summary data

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#437]
I have downloaded all the data from the protein family sorter, but I am also interested in getting that data summarized in the heatmap as it is easier to see what genome is missing what proteins.  Just to be clear, I want the colors summarized as numbers. I am having trouble downloading all the heatmap summary data.  I selected it all, and when I tried to download it (in excel), an error message popped up.
![screen shot 2015-09-14 at 11 21 56 am](https://cloud.githubusercontent.com/assets/11475316/9855415/acc3a390-5ad3-11e5-8715-a3778c87b5b6.png)

Here's what it looks like when I try and get the text document
![screen shot 2015-09-14 at 11 28 45 am](https://cloud.githubusercontent.com/assets/11475316/9855446/d9fd400a-5ad3-11e5-896b-d98246213d7a.png)

**Comment by hyoo** [comment]
This is a bug specific to the JBoss website.
