### ISSUE TITLE
Creating new genome groups in workspace not working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#438]
FRUSTRATING!!!!  I am logged in and created the same group three times and nothing shows up in my workspace!

**Comment by olsonanl** [comment]
What is the name of the group? There is currently a limitation where “:” cannot be in the name

On Sep 15, 2015, at 8:15 AM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


FRUSTRATING!!!! I am logged in and created the same group three times and nothing shows up in my workspace!

**Comment by mshukla1** [comment]
Seems to be working for me. 

Rebecca, do you still see the same problem or Can you reproduce it?

**Comment by ARWattam** [comment]
Yes, it seemed to be a weird thing that was transient.  I discussed this with Dustin, I believe, when it happened.  I couldn't get it to work for several hours, but later it was fine.

Rebecca

----- Original Message -----

**Comment by mshukla1** [comment]
seems the problem has magically disappeared!!

closing the ticket.
