### ISSUE TITLE
Search not responding

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#439]
I just put in a search for "fig|1121866.3.peg.99" at the production site and it never returned. While it was spinning I brought up a new tab and the search worked immediately. 

New relic monitors showed issues too.

![screen shot 2015-09-16 at 3 32 15 pm](https://cloud.githubusercontent.com/assets/2152226/9917603/266f80c8-5c88-11e5-9d2f-8954b52c3cc3.png)

BTW how much do we pay them? The new relic site seems astonishingly slow.

**Comment by mshukla1** [comment]
It seems to be working now. Not sure what can be done here. 

Assigning it to Dustin, in case he wants to comment on the new relic and/or the snapshot and close it.

-Maulik
