### ISSUE TITLE
Time represented in log

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#44]
It seems to be universal time

**Comment by dmachi** [comment]
Which "log" page were you seeing this on?

**Comment by mshukla1** [comment]
Not sure which log this refers to. The time displayed in job status log and groups look properly formatted. 
![Uploading Screen Shot 2015-06-11 at 7.19.36 AM.png…]()
![screen shot 2015-06-11 at 7 19 27 am](https://cloud.githubusercontent.com/assets/1236463/8105805/6b5d50c2-100a-11e5-8442-2e6dc7c82577.png)
