### ISSUE TITLE
Can't copy a feature ID from MSA

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#440]
say I see something in the MSA and I want to look at that protein. There doesn't appear to be any way to either directly go to that protein, or even to copy and paste. If I select the fid in display-gene-id mode, the bullet in front of the fid flashes and the selection vanishes.

![screen shot 2015-09-16 at 3 37 55 pm](https://cloud.githubusercontent.com/assets/2152226/9917771/139d4588-5c89-11e5-9f00-8515312c2ac9.png)

**Comment by mshukla1** [comment]
Andrew, the MSA MAN!! :)

**Comment by aswarren** [comment]
This has been solved in the MSA viewer to be released as part of the site overhaul. The new tree viewer is in D3/SVG so the IDs are selectable and copyable.
