### ISSUE TITLE
Failure going to peg page for fig|1236941.3.peg.86

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#441]
Searched for "fig|1236941.3.peg.86" which took me to

https://www.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=PATRIC.1236941.3.BALU01000001.CDS.69260.69808.rev

got this error on the page:

ERROR
Cause: java.lang.NullPointerException
See log for stacktrace

**Comment by olsonanl** [comment]
This shows up on both beta and production.

**Comment by mshukla1** [comment]
I have seen this error couple of times this morning. 

-Maulik

**Comment by mshukla1** [comment]
Harry, I checked the data, the genome and feature has correct taxon id and taxon lineage. 

Can you please check what is going on? Assign it back to me if it is related to data.

**Comment by hyoo** [comment]
Here is a problem.

This feature has a taxon_id:1236941

http://macleod.vbi.vt.edu:8983/solr/genome_feature/select?q=feature_id:PATRIC.1236941.3.BALU01000001.CDS.69260.69808.rev

but there is no information in taxon core for this taxon id

http://macleod.vbi.vt.edu:8983/solr/taxonomy/select?q=taxon_id%3A1236941&wt=json&indent=true

This is where it returns null pointer error. I will handle this case, but we will not able to display correctly until we update taxon core or find correct taxon_id.

**Comment by hyoo** [comment]
update. NCBI has this taxon info.

http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1236941

**Comment by hyoo** [comment]
https://www.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=PATRIC.1236941.3.BALU01000001.CDS.69260.69808.rev

this is fixed.

**Comment by mshukla1** [comment]
Thanks. I will update taxonomy core in the next data release. 

-Maulik
