### ISSUE TITLE
Correlated Genes: Add description and link to FAQs

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#443]
Please add the following description on the Correlated genes tab, above the table. 

"For this gene, the table below shows the list of genes that have correlated expression profiles (positively or negatively) across all available transcriptomics data sets in PATRIC, which may help identify genes that are co-regulated or have similar functions or infer potential function for a hypothetical gene. To learn more, see Gene Page Transcriptomics User Guide."

**Comment by hyoo** [comment]
This is specific to outdated website.
