### ISSUE TITLE
BLAST Service Implementation

### ISSUE THREAD

**Issue by dmachi** [PATRIC3/patric3_website#445]
Reference: Sequence Similarity Search Requirements: https://docs.google.com/document/d/1H7zKdm8RC5oBKhvaGeaihP5meJAJ7Q2vuR-zyydYPdU/edit 
Design app service framework for BLAST that work with/without authentication to access private/public genomes
Place for creating and storing blast databases.
Prototype submission interface for BLAST

A search is against one of several classes of target:
1.  Genome. Search against one or more given genomes.
2.  Taxonomy tree. Search against all genomes at or below a given NCBI taxonomy ID. (species or genus only and only where we have existing genomes)
3.  Genome group. Search against all genomes in a given genome group.
4.  Feature group. Search against all features in a given feature group.
5.  Enumerated database. Search against an explicitly curated database. Type is either protein or DNA.

Returned data: Essentially content of blast –m8 output. Some search mechanisms may not return some columns.

Enumerate databases call needs to be REST capable

Searching against a genome implies a choice of one of the following three searches:

(a)   Amino acid sequences of its protein encoding genes. Returns PATRIC feature IDs.
(b)  DNA sequences of individual features. Returns PATRIC feature IDs.
(c)   DNA sequences of contigs. Returns PATRIC genome sequence IDs.

**Comment by mshukla1** [comment]
this is complete now and supports all the requirements laid out earlier.
