### ISSUE TITLE
byte range indexing into shock files

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#446]
Shock support for byte range indexing. This is necessary to support streaming of RNA-Seq results to the genome browser.

**Comment by aswarren** [comment]
An example hosted outside of Shock is as follows 

https://www.google.com/url?q=http://www.alpha.patricbrc.org/portal/portal/patric/GenomeBrowser?cType%3Dgenome%26cId%3D588858.6%26addTracks%3D%255B%257B%2522type%2522%253A%2522JBrowse%252FView%252FTrack%252FAlignments2%2522%252C%2522key%2522%253A%2522streamtest%2522%252C%2522store%2522%253A%252212345%2522%252C%2522label%2522%253A%2522streamtest%2522%257D%255D%26addStores%3D%257B%252212345%2522%253A%257B%2522type%2522%253A%2522JBrowse%252FStore%252FSeqFeature%252FBAM%2522%252C%2522urlTemplate%2522%253A%2522http%253A%252F%252Fbrcdownloads.patricbrc.org%252Fstream%252F14028s_stream.bam%2522%252C%2522baiUrlTemplate%2522%253A%2522http%253A%252F%252Fbrcdownloads.patricbrc.org%252Fstream%252F14028s_stream.bam.bai%2522%257D%257D%26loc%3DCP001362%253A1..10000%26tracks%3DDNA%252CPATRICGenes%252Cstreamtest%26highlight%3D&sa=D&ust=1443026091255000&usg=AFQjCNHK7jJfpkIR7rMYfHwE7xtrJmOUnQ

**Comment by olsonanl** [comment]
As far as I know this is now working.
