### ISSUE TITLE
Null Pointer Exception when exploring pathways

### ISSUE THREAD

**Issue by bparrello** [PATRIC3/patric3_website#45]
My sequence of actions:

Search for "41514.7". Click on the genome.

Select the "Feature Table" tab.

On page 2, select pegs 34, 35, and 36. Ask for the "Pathway Summary".

Choose the "Ubiquinone and other terpenoid-quinone biosynthesis".

In the table on the left, click the "10" under "Feature Count" on the row labelled "3.2.1.-".

page says

   ERROR 
   Cause: java.lang.NullPointerException
   See log for stacktrace

**Comment by hyoo** [comment]
this is fixed and available on www.beta.patricbrc.org. please make sure delete cache, since some javascript needs to be updated. thanks for reporting this bug. if you have further question, please reopen this issue.
