### ISSUE TITLE
Migrate Pathways page to new platform

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#454]
Genome List / Taxon level:
https://www.patricbrc.org/portal/portal/patric/CompPathwayTable?cType=taxon&cId=1763&algorithm=PATRIC&ec_number=

Genome:
https://www.patricbrc.org/portal/portal/patric/CompPathwayTable?cType=genome&cId=83332.12&algorithm=PATRIC&ec_number=

Feature:
https://www.patricbrc.org/portal/portal/patric/PathwayTable?cType=feature&cId=PATRIC.83332.12.NC_000962.CDS.34.1524.fwd

**Comment by hyoo** [comment]
It looks like some problem on pathway implementation. I remember this was working correctly before.

https://www.alpha.patricbrc.org/view/Taxonomy/111504#view_tab=pathways

shows 125 pathways, which does not match to

https://www.patricbrc.org/portal/portal/patric/CompPathwayTable?cType=taxon&cId=111504&algorithm=PATRIC&ec_number=

2. ec number tab, also does not match

3. gene tab. shows only one feature

**Comment by hyoo** [comment]
pathway map is deloyed to alpha and ready for test.
