### ISSUE TITLE
Migrate Correlated Genes page to new platform

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#461]
https://www.patricbrc.org/portal/portal/patric/TranscriptomicsGeneCorrelated?cType=feature&cId=PATRIC.83332.12.NC_000962.CDS.34.1524.fwd

**Comment by hyoo** [comment]
Here is one version.

https://www.alpha.patricbrc.org/view/Feature/PATRIC.83332.12.NC_000962.CDS.2052.3260.fwd#view_tab=correlatedGenes


- Need to implement filter
- Need to add default sorting condition
- Make sure toolbar buttons are working
