### ISSUE TITLE
Strange behavior on Safari after logging in during initial account creation

### ISSUE THREAD

**Issue by cshenry** [PATRIC3/patric3_website#48]
When I created a fresh account and logged in via Safari, I got very weird behavior from the workspace. My workspace was empty and didn't have the default folders. Generally, I couldn't really do anything on the interface (like uploading a file).

**Comment by mshukla1** [comment]
It first appeared empty, then after couple of seconds folders were created. I had to refresh the page to see the folders though.  

![screen shot 2015-06-10 at 11 03 24 pm](https://cloud.githubusercontent.com/assets/1236463/8098984/f138809a-0fc4-11e5-94d6-e5eef6fa7488.png)
![screen shot 2015-06-10 at 11 03 09 pm](https://cloud.githubusercontent.com/assets/1236463/8098985/f13a67ca-0fc4-11e5-9282-cc68ba7c944b.png)

**Comment by dmachi** [comment]
Same bug as #367 which seems to be trying to view the workspace before the creation of the default workspace and structure has been completed.
