### ISSUE TITLE
Migrate Interactions page to new platform

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#481]
Genome list / taxon:
https://www.patricbrc.org/portal/portal/patric/HPITool?dm=tab&cType=taxon&cId=1763&hpi=false&bm=

Genome:
https://www.patricbrc.org/portal/portal/patric/HPITool?dm=tab&cType=genome&cId=83332.12&hpi=false&bm=

Feature:
https://www.patricbrc.org/portal/portal/patric/HPITool?dm=tab&cType=feature&cId=PATRIC.83332.12.NC_000962.CDS.34.1524.fwd&hpi=false&bm=

**Comment by hyoo** [comment]
we already delivered in new Interactions tab.
