### ISSUE TITLE
Migrate Phylogeny page to new platform

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#483]
Genome list / taxon:
https://www.patricbrc.org/portal/portal/patric/Phylogeny?cType=taxon&cId=1763

Genome:
https://www.patricbrc.org/portal/portal/patric/Phylogeny?cType=genome&cId=83332.12
- [x]  Basic phylogeny tree viewer
- [x] Cladogram
- [x]  Phylogram: shows negative branches
- [x]  Show support button not working
- [x]  No color by genus/species button
- [ ]  Selecting multiple nodes by command+click is not clear. Add check boxes?
- [x] Select a subtree by clicking on internal nodes
- [x]  Create genome group not working
- [ ]  Do we have a plan for keeping the trees up-to-date?

**Comment by mshukla1** [comment]
- [ ] Basic phylogenetic tree viewer
- [ ] Phylogram: shows negative branches
- [ ] Show support not working
- [ ] Show support button not working
- [ ] No color by genus/species button
- [ ] Selecting multiple nodes by command+click is not clear. Add check boxes? 
- [ ] Create genome group not working
- [ ] Do we have a plan for keeping the trees up-to-date?

**Comment by hyoo** [comment]
Most of them are addressed and there is a separate discussion going on tree building. I am closing this.
