### ISSUE TITLE
Migrate Literature page to new platform

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#484]
Taxon:
https://www.patricbrc.org/portal/portal/patric/Literature?cType=taxon&cId=1763&time=a&kw=none

Genome:
https://www.patricbrc.org/portal/portal/patric/Literature?cType=genome&cId=83332.12&time=a&kw=none

Feature:
https://www.patricbrc.org/portal/portal/patric/Literature?cType=feature&cId=PATRIC.83332.12.NC_000962.CDS.34.1524.fwd&time=a&kw=none

**Comment by hyoo** [comment]
#240
closing duplicates
