### ISSUE TITLE
handling of shock located files in DIffExp viewer

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#488]
Sample files above a certain size are getting placed on shock. The Experiment.js viewer did not expect this.

**Comment by dmachi** [comment]
I committed a fix for this in https://github.com/dmachi/p3-web/commit/37de53e6bf4bfb09ab1bf32c7e7ef1b677e050d6  , though i've just noticed i committed to the djm branch instead of master

**Comment by aswarren** [comment]
Dustin's fix has been deployed.
