### ISSUE TITLE
Protein Family sorter is not loading any families

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#492]
I created a genome group, clicked on it when deploying the PFS
![screen shot 2015-10-02 at 8 06 48 am](https://cloud.githubusercontent.com/assets/11475316/10246200/f73d02ec-68dc-11e5-8b8b-6635d42b0d95.png)

This is what returned
![screen shot 2015-10-02 at 8 07 01 am](https://cloud.githubusercontent.com/assets/11475316/10246208/037be6f4-68dd-11e5-977c-e53cab545b82.png)

**Comment by mshukla1** [comment]
I created a group with the same two genomes and it worked for me!

**Comment by ARWattam** [comment]
Cleared cache and it worked
