### ISSUE TITLE
Can't download family details from Protein Family sorter table

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#493]
I've tried several times, and nothing downloads.  I finally opened the developer tools and saw that there is an error that says:
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
globalWSObject.js:191 The XMLHttpRequest progress event property 'position' is deprecated. Please use 'loaded' instead.
FIGfam:20 Uncaught TypeError: Cannot set property 'value' of undefined

Here's the Screenshot:
![screen shot 2015-10-02 at 7 49 16 pm](https://cloud.githubusercontent.com/assets/11475316/10260096/fb35e5dc-693e-11e5-848c-8bdd5b2d7260.png)

**Comment by hyoo** [comment]
Sorry, I missed to check this option. I am currently deploying my fix to beta. I will let you know when this is fixed and deployed to production.

**Comment by hyoo** [comment]
this is fixed and confirmed by Rebecca. Please reopen if anyone find otherwise.
