### ISSUE TITLE
Download from protein family table not working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#494]
I had a group, I used the protein family sorter, as the table download is not working, I went to the heatmap and got all the proteins from there.  Then, when I try to download the information in either text or excel, it comes up blank.  Excel won't even load.  Here's the url for the download:
https://www.patricbrc.org/portal/portal/patric/SingleFIGfam?cType=taxon&cId=131567&pk=2915440694212265347

Here is the screenshot of what I get:
![screen shot 2015-10-05 at 7 22 07 am](https://cloud.githubusercontent.com/assets/11475316/10279278/4a9bf09a-6b32-11e5-8478-ef78463a1a05.png)

**Comment by hyoo** [comment]
this is in single family page.

**Comment by hyoo** [comment]
fixed and available on beta.

**Comment by mshukla1** [comment]
checked. working as expected.

**Comment by ARWattam** [comment]
I verify that this is working on beta
