### ISSUE TITLE
Anchoring genome on heat map view is failing, and overall loading of tool is TERRIBLE

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#495]
I am having a student examine Corynebacterium and compare 142 genomes.  Loading the data takes an extremely long time, and I tried to show him how to anchor a genome and it totally failed.  I am demoing the website to some interested user in Quebec this afternoon.  If these issues continue, it will be a horrible experience for them, and an embarrassing one for me.

**Comment by hyoo** [comment]
#499
