### ISSUE TITLE
Add to workspace default

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#496]
The add to workspace button should default the workspace to be the last one used.

**Comment by mshukla1** [comment]
one plus from Maulik and Rebecca!

**Comment by dawenx** [comment]
I'm going through Website/UI label... Is this issue still relevant with workspace 2.0 release? If so, can i suggest to remove "Website/UI" label? :)

**Comment by mshukla1** [comment]
This is very old ticket and I believe refers to the old website. 

On the current website, the most recent groups are listed first from the drop down. Also, theer is a folder icon, hat allows you to see all files/folders/groups, and sort them by name or date. 

<img width="854" alt="screen shot 2017-09-17 at 11 18 44 am" src="https://user-images.githubusercontent.com/1236463/30522700-0036d14c-9b9a-11e7-93de-7b1764af6a7b.png">
<img width="841" alt="screen shot 2017-09-17 at 11 18 22 am" src="https://user-images.githubusercontent.com/1236463/30522701-00378880-9b9a-11e7-95f2-c140b2111150.png">
