### ISSUE TITLE
search for exact string

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#497]
I am searching for "DNA-directed RNA polymerase beta subunit" in the feature finder, and I put this in double and single quotes, but it keeps finding the beta' subunit.

<img width="928" alt="screen shot 2015-10-08 at 10 04 00 am" src="https://cloud.githubusercontent.com/assets/7661533/10370370/10d8e574-6da4-11e5-8729-d6314d00beb5.png">

<img width="1119" alt="screen shot 2015-10-08 at 10 04 13 am" src="https://cloud.githubusercontent.com/assets/7661533/10370373/1325d60c-6da4-11e5-8263-cb8ab67b7d10.png">

**Comment by hyoo** [comment]
This is "Solr" issue rather than website issue. I am closing because this website no longer exists.
