### ISSUE TITLE
Scroll Bar in alignment viewer disappears

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#498]
The scroll bar disappears unless I am already scrolling with my fingers using the track pad, but I don't want to scroll with my fingers because I'm afraid of swiping forward or backward and leaving the page.

<img width="653" alt="screen shot 2015-10-08 at 10 12 42 am" src="https://cloud.githubusercontent.com/assets/7661533/10370575/29234cd6-6da5-11e5-9581-9fdc5c537f25.png">

**Comment by aswarren** [comment]
As of yet I can't make mine disappear in any browser. Got any tips?

**Comment by aswarren** [comment]
In the upcoming site overhaul the MSA scroll bar will become part of the canvas element so this shouldn't happen anymore.
