### ISSUE TITLE
Anchoring is not working in the heatmap view for protein families.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#499]
Its generating some error that I can't read:
![screen shot 2015-10-08 at 11 21 20 am](https://cloud.githubusercontent.com/assets/11475316/10370854/c7039aba-6dae-11e5-8a4a-b19b43e82d38.png)

**Comment by hyoo** [comment]
The implemented mechanism is that anchoring genome is re-ordering along the gene order in the specified genome, not re-ordering by the value (# of occurence). So, in most of cases, heatmap will not change dramatically. Should we change the logic?

**Comment by mshukla1** [comment]
checked. working as expected. 

couldn't check with the pl/pgfam though. Need to test it again on production after the release.

**Comment by ARWattam** [comment]
I agree that it is working with FigFams...why can't we test with the Pattifams?

**Comment by mshukla1** [comment]
Working in production and with the new protein families.
