### ISSUE TITLE
No Uniprot Accession in the ID mapping tool

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#5]
There is no Uniprot Accession option in the ID mapping tool. We have many other options but not the Uniprot Accession which is given by us throughout the site.

**Comment by hyoo** [comment]
aswarren// UniprotKB Accession is added

rwill1// Error was due to some exception when previous query result is empty. This case is handled now.

Fixed version is available at www.alpha.patricbrc.org.
