### ISSUE TITLE
Heatmap does not reload after selection is made of left side filter

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#500]
If the filter doesn't control the heatmap, then it shouldn't be visible on that page.  It used to.
![screen shot 2015-10-08 at 11 22 57 am](https://cloud.githubusercontent.com/assets/11475316/10370941/136cd204-6daf-11e5-9026-8d68720fb598.png)

**Comment by hyoo** [comment]
This does work for me on the production. Would you give me more information so that I can reproduce?

**Comment by ARWattam** [comment]
Still happening for me.  Load the protein families, wait until the table loads, click the heatmap tab, let that load.  then deselect all the genomes (Absent) and choose one genome for present.  The heatmap never reloads to show this:
![screen shot 2015-10-12 at 7 26 23 pm](https://cloud.githubusercontent.com/assets/11475316/10441493/5a467ee4-7117-11e5-8463-5be16dee5c93.png)

**Comment by hyoo** [comment]
Now I got the problem and fixed on beta.

**Comment by mshukla1** [comment]
add pop up box with the message.

**Comment by hyoo** [comment]
fixed and available on alpha.

**Comment by ARWattam** [comment]
Checked and verified that works on alpha
