### ISSUE TITLE
Genome browser only shows first 30 contigs-no way to see the next 30

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#502]
Very frustrating!
![screen shot 2015-10-08 at 11 33 51 am](https://cloud.githubusercontent.com/assets/11475316/10371278/9621e79c-6db0-11e5-9f09-d4081cda27c6.png)

**Comment by mshukla1** [comment]
#602 this is a duplicate issue

**Comment by hyoo** [comment]
this is already fixed. see #602
