### ISSUE TITLE
PFS: Filter Search in protein family sorter

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#504]
Each word that you search becomes an OR search, so if you search for  RNA polymerase beta, it is actually searching for anything with "RNA" -or- "polymerase" or "beta".  This makes it really hard to filter down the list.  Its default behavior is different from the behavior of the feature finder which is also different from the global search bar.  

<img width="1191" alt="screen shot 2015-10-08 at 10 38 02 am" src="https://cloud.githubusercontent.com/assets/7661533/10371429/f9269ab6-6da8-11e5-83da-e71004e3d34e.png">

**Comment by mshukla1** [comment]
After some more thought, I believe the keyword search always behaved this way! 

It is a bug and should be fixed, but I am surprised why we didn't catch it until now!

**Comment by hyoo** [comment]
I think OR condition allows users filter by multiple family ids. We should consider that use case as well and probably come up with interface that can incorporate both AND and OR.

**Comment by mshukla1** [comment]
The logic should be: 

- AND for keywords on the same line, to allow searching for multi word functions

- OR for all keywords entered on new lines

**Comment by hyoo** [comment]
this is specific to outdated website.
