### ISSUE TITLE
PFS: Search for a gene id from the protein family page

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#505]
I am looking at the protein family page, and I want to find the family containing fig|1408167.3.peg.850.

<img width="1030" alt="screen shot 2015-10-08 at 10 46 52 am" src="https://cloud.githubusercontent.com/assets/7661533/10371671/10e1f8a2-6daa-11e5-8e21-0533578261d2.png">

**Comment by hyoo** [comment]
This is specific to outdated website.
