### ISSUE TITLE
Add to workspace from global search results page

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#506]
We should be able to add features or genomes to a workspace directly from the search results page

**Comment by mshukla1** [comment]
Just to add more details, this is about ability to add to group directly from the global search result page, without clicking on a specific data type. 

![screen shot 2015-10-09 at 11 28 47 am](https://cloud.githubusercontent.com/assets/1236463/10399557/f50b3808-6e78-11e5-98e0-2087a5a2d7f8.png)

**Comment by hyoo** [comment]
This is specific to outdated website.
