### ISSUE TITLE
PFS: if you click on the protein family nothing happens

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#507]
It is confusing to me that if you click on the protein family, nothing happens, but if you click on the annotation it takes you to the list of proteins.  Does it make sense that if you click anywhere in the row it takes you to the gene list?
<img width="937" alt="screen shot 2015-10-08 at 10 54 20 am" src="https://cloud.githubusercontent.com/assets/7661533/10371927/2ac37524-6dab-11e5-9b39-ff23a6e8b089.png">

**Comment by mshukla1** [comment]
I agree, the family id should also be linked to the list of members. 

Regarding, doing the same when you clink anywhere in the row, most tables on the 
website have different fields linking to different pages, i.e 
- genome name goes to genme overview page
- sequence accession to genbank/refseq record
- feature id to feature overview page etc. 

Hence, to make it consistent in all tables, we don't have row wide actions/links. 

Having said that, I think links, selection and actions from the table should be carefully re-considered as we are redesigning the website. 

-Maulik
