### ISSUE TITLE
The protein family table should sort when you filter on the number of genomes or proteins

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#508]
I filtered the protein family table on a range of proteins per family from 12 to 100.  Then the table came back unsorted and then I had to manually sort it.  Check out the first column in the picture.

<img width="914" alt="screen shot 2015-10-08 at 10 58 11 am" src="https://cloud.githubusercontent.com/assets/7661533/10372014/a5d88b96-6dab-11e5-8d17-e9d80aa5e99c.png">

**Comment by mshukla1** [comment]
I believe, currently, the table keeps the same sort order that you had before you applied the filters. 

Are you suggesting that the table automatically sort based by number of proteins, if you filter by number of proteins? 

Remembers, multiple the filters on the left side can be used in any  combination and user may want to keep the same. So, changing sort order based on filters may lead to unnecessary confusion!

**Comment by hyoo** [comment]
this is specific to outdated website.
