### ISSUE TITLE
Download from workspace not showing all my genomes

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#509]
Argh!  I guess this has already been reported.  When will this be fixed?  I have 48 genomes and can only download information for 25.

**Comment by dmachi** [comment]
I thought this had already been fixed and pushed to beta, but there seemed to still be a bug.  I've fixed it now and pushed to both beta and production and was able to download a group with more than 25 members now.  Please try again and then close the ticket if you don't have any problems.

Dustin

**Comment by ARWattam** [comment]
I just tried on the production site.  Got all 48 of my 48 genomes.  I'm closing this one down.
