### ISSUE TITLE
All genomes in my group aren't loading into Protein Family sorter...only seeing subset! Really BAD!

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#510]
Oh No!  It gets worse!!  I have 48 genomes in my group.  
![screen shot 2015-10-08 at 5 57 08 pm](https://cloud.githubusercontent.com/assets/11475316/10381097/17628bc4-6de6-11e5-9cc4-042196b5105c.png)
I go to the protein family sorter, and on the landing page where I pick my groups, I opened up that group and counted the genomes.  There are only 30 of the total 48 that should be there.  You can see that in this view of the final table:
![screen shot 2015-10-08 at 6 02 21 pm](https://cloud.githubusercontent.com/assets/11475316/10381202/cb7bbaae-6de6-11e5-9fb5-d7788295f15a.png)

**Comment by mshukla1** [comment]
Questions: 
- are any of these private genomes? 
- Can you make sure you actually have 48 genomes in your group and some of them are not double counted?

**Comment by ARWattam** [comment]
They are all public genomes.  Mycobacterium.  Here is the list I typed by hand while having the group open in workspace:
![image](https://cloud.githubusercontent.com/assets/11475316/10383999/ffd9c1fc-6e03-11e5-89f3-d7b45eca5442.png)

**Comment by mshukla1** [comment]
Both Rebecca and I re-created the same genome group with the same set of genomes, and it seems to be working fine now. 

However, the old group Rebecca gas, still doesn't work. Harry or Dustin need to check it out. 

-Maulik

**Comment by dmachi** [comment]
This bug no longer applies.
