### ISSUE TITLE
When searching for protein family, click on gene, click on protein family and table does not immediately show which protein family it is.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#512]
Having the protein family should be the default load for this table:
![screen shot 2015-10-09 at 9 29 09 am](https://cloud.githubusercontent.com/assets/11475316/10394951/5f21c7c2-6e68-11e5-8903-369750f082de.png)

**Comment by ARWattam** [comment]
What's more, I can't even add the protein family in with the column options
![screen shot 2015-10-09 at 9 32 44 am](https://cloud.githubusercontent.com/assets/11475316/10395031/c94d5594-6e68-11e5-8d96-ae291f8ea608.png)

And yet, when I try and copy and paste a row, I can see that the protein family is listed there:
![screen shot 2015-10-09 at 9 34 24 am](https://cloud.githubusercontent.com/assets/11475316/10395071/02b18472-6e69-11e5-8be2-255396cafecc.png)

**Comment by mshukla1** [comment]
Because you are looking at a single family, it is displayed at the top, above the table, as heading. 

Are you suggesting that the family name is also displayed as a column in the table? 

..I like the suggestion. I would also add that ALL feature-like tables, should have all 
three protein family ids available from show/hide columns. 

-Maulik

**Comment by ARWattam** [comment]
Yes, its at the top of the page initially, but disappears if you use the filter and that name is not included in the family:
![screen shot 2015-10-09 at 10 09 27 am](https://cloud.githubusercontent.com/assets/11475316/10395983/f6806a88-6e6d-11e5-997d-d579a9ebef56.png)

**Comment by mshukla1** [comment]
I see. Yes, we need to add the columns!

**Comment by hyoo** [comment]
This is on legacy now, but contains insight for having family id column on the single family page. However, new production site supports this with feature list view. So, I am tagging "Obsolete"
