### ISSUE TITLE
Local Patty Fam appears to be global

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#513]
I was looking for the Patty Fams for a set of Mycobacterium genomes, and was surprised to see that the family I was interested in, the one I thought was local (ie same genus) was actually global:
![screen shot 2015-10-09 at 1 03 16 pm](https://cloud.githubusercontent.com/assets/11475316/10400393/60f4c608-6e86-11e5-8df7-adefbea0056e.png)

**Comment by olsonanl** [comment]
This is the quotes vs no quotes thing again. If you search for “PLF_1763_00002521” you just get the MTB features.

Looks like it split on underscore and gave you features matching 1763.

—bob

On Oct 9, 2015, at 12:05 PM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


I was looking for the Patty Fams for a set of Mycobacterium genomes, and was surprised to see that the family I was interested in, the one I thought was local (ie same genus) was actually global:
[screen shot 2015-10-09 at 1 03 16 pm]<https://cloud.githubusercontent.com/assets/11475316/10400393/60f4c608-6e86-11e5-8df7-adefbea0056e.png>

**Comment by ARWattam** [comment]
Okay...now I see.
