### ISSUE TITLE
PFS: make figfam default for now

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#514]
A couple of users complained that their private genome don't appear in the protein family sorter. 
The reason was that in PFS default is PLfam, and it is not computed for the private genomes, yet. 

To avoid this confusion, both Rebecca and I think that we should make figfam as default for the 
PFS for until next release. This will make the September release kind of "soft launch" for the new 
families and will give users for time to get used to them. 

By November, we will have private genomes annotated with the new families, and users somewhat more used to them. At that point, we can make PLfam default again. 

-Maulik

**Comment by mshukla1** [comment]
Need to make figfam as default from the PFS Tool search interface as well. 

-M

**Comment by hyoo** [comment]
fixed and available on alpha
