### ISSUE TITLE
Protein Family Sorter-Choose a specific family to download and it returns all

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#515]
I chose one family from the selection on the table of the protein family sorter, and it returned all of them.
![screen shot 2015-10-11 at 8 08 02 am](https://cloud.githubusercontent.com/assets/11475316/10416715/61b3a054-6fef-11e5-87b0-0c0796d4aade.png)

**Comment by mshukla1** [comment]
I believe this is true for all the tables in PATRIC, i.e. text and excel table downloads always give you all the results in a table, not just those selected. 

That is how it is throughout the site, not saying it is intuitive or how it should be though. 

I think we should reconsider the options in the table toolbars and iron out any kinks as part of redesign/reimplementation. 

-Maulik

**Comment by hyoo** [comment]
this will be more informative and intuitive when we have a new grid. Any action related to selection will be displayed in the left-hand-side-green tool bar and grid level actions will be on top of the grid it self.

**Comment by hyoo** [comment]
as discussed, we have new website. closing this issue.
