### ISSUE TITLE
Annotation Service - Detect close relative, propagate gene calls

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#516]
In this release, a module will be added that automatically detects the closest relatives of the genome that is being annotated. In addition, a module will be added that enables the direct propagation of gene calls and annotations from a closely related reference strain. User options will be added that allow users to select or deselect annotation steps, which allows customized annotation jobs.

Requires some changes in UI.

**Comment by rkenyon** [comment]
10/14: On target for November Release, per Bob

**Comment by rkenyon** [comment]
10/28: Working in prototype form now. Just need to integrate into Production.

**Comment by olsonanl** [comment]
Test case for the propagation is to import the new version of Desulfitobacterium hafniense DCB-2

**Comment by rkenyon** [comment]
11/18: On target for November release

**Comment by rkenyon** [comment]
11/23: Service is updated.  Bob will update spec and Andrew will update UI. Not sure if possible by Monday.

**Comment by aswarren** [comment]
@olsonanl is the reference_genome_id parameter being accepted on the server side?
Do you have a good help-text explanation for this feature?

beta UI https://www.beta.patricbrc.org/app/Annotation
 is updated to give reference_genome_id parameter
{
    "contigs": "/anwarren@patricbrc.org/home/test/.testing_deploy6/testing_deploy6.contigs",
    "output_file": "My bacillus",
    "domain": "Bacteria",
    "scientific_name": "My bacillus",
    "tax_id": "924",
    "code": "11",
    "reference_genome_id": "1123393.3",
    "output_path": "/anwarren@patricbrc.org/home/Foo",
    "taxonomy_id": "924"
}

**Comment by olsonanl** [comment]
I'm not using it yet. I'll need to do a little work to translate the reference ID to a genome from patric (creating a genome object from patric data)

--bob

________________________________

**Comment by rkenyon** [comment]
12/2: Bob still working on it.  Reference genome propagation is in place.

**Comment by rkenyon** [comment]
02/24: May or may not be feasible for March Release.  Depends on other tasks and projects.  Bob and Maulik will take stock of where things are and priorities and decide.

**Comment by rkenyon** [comment]
03/17: Status update - the genome annotation service has support for invoking the propagation code (fast_project.pl) but needs code added to pull reference genomes from PATRIC instead of coreseed.

**Comment by mshukla1** [comment]
We now have similar genome finder to find close relatives of any genome. 

We decided to drop the propagation of the gene calls from close relatives. 

Closing the ticket.

**Comment by olsonanl** [comment]
I don't remember deciding to drop that feature.
