### ISSUE TITLE
Assembly Service enhancements

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#517]
In this release, we will enable assembly of genomes sequenced using PacBio technology. Both raw m5 read files and filtered FASTQ files from PacBio sequencing will be accepted as input.

**Comment by rkenyon** [comment]
10/14 update: On target for November, per Fangfang

**Comment by rkenyon** [comment]
10/28: Ron check with Fangfang.

**Comment by rkenyon** [comment]
11/18: Ron check with Fangfang

**Comment by levinas** [comment]
I've redeployed the assembly service with experimental pacbio/nanopore support. 
@aswarren Can you please update the help text for the Parameters section?

#### auto
For short reads:
  1. Runs BayesHammer on reads
  2. Assembles with Velvet, IDBA and SPAdes
  3. Sorts assemblies by ALE score

For long reads (PacBio or Nanopore):
  Assembles with MiniASM

#### smart
For short reads:
  1. Runs BayesHammer on reads, Kmergenie to choose hash-length for Velvet
  2. Assembles with Velvet, IDBA and SPAdes
  3. Sorts assemblies by ALE score
  4. Merges the two best assemblies with GAM-NGS

For long reads (PacBio or Nanopore):
  Assembles with MiniASM

I could generate a pull request. I see multiple `GenomeAssemblyHelp.html` files, and I'm not sure which ones are auto generated.

**Comment by levinas** [comment]
Also `plx.h5` and `bax.h5` pacbio raw read files are now supported. FASTA and FASTQ files are automatically checked to see if they contain long reads.

**Comment by levinas** [comment]
Created pull request: https://github.com/dmachi/p3-web/pull/44
Andrew is going to deploy this on both prod and beta.

**Comment by aswarren** [comment]
Deployed

**Comment by rkenyon** [comment]
Service and UI are deployed, doing some testing.
