### ISSUE TITLE
Model Reconstruction Service - FBA based on RNA-Seq data

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#518]
In this release, planned enhancements to the metabolic modeling service revolve around extending the modeling and simulation framework to include transcription data. We will enable users to predict flux based on gene expression profiles derived from RNA-Seq data. We will also enable users to use RNA-Seq data to add additional reactions to the model, permitting reactions with highly expressed genes to function.

**Comment by rkenyon** [comment]
10/14: Ron check with Chris

**Comment by rkenyon** [comment]
Per Chris, going to be Dec 4.

**Comment by rkenyon** [comment]
12/2: Chris is confident I can get the backend for this done. My main concern is the front end. (probably won't make it)

**Comment by rkenyon** [comment]
02/24: Per Chris, probably will not make it for March.

**Comment by mshukla1** [comment]
I think we can drop this from the wish list for now. Closing the ticket.
