### ISSUE TITLE
Website Platform Conversion - Alpha Version

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#519]
Migrate our JBoss infrastructure to a new framework (i.e., ExpressJS) to ease the addition of new services and data and pave the way toward further integration between a user's workspace and the rest of the PATRIC site. This migration will also complete the segregation of our Data API from the User Interface. Due to the magnitude of the infrastructure change with this conversion, for this release, we will release the converted site in BETA for internal and limited external evaluation and testing. Pending acceptance, we will release into production in the January 2016 PATRIC Release.

See associated individual website page tickets.

**Comment by rkenyon** [comment]
10/28: Per Dustin and Harry, goal is to have all data loaded for pages for each tab, plus a rudimentary display.  From there, will continue work on UI.

**Comment by rkenyon** [comment]
02/24: New Alpha version is still feasible for March release, assuming Harry has time to work on it with Dustin.  
- demo by Dustin next week
- Alpha site is up now, but still needs to deploy new code.
- Harry will be back on PATRIC beginning of next week
- Dustin will start pushing new updates, possibly through Jenkins via Git

**Comment by rkenyon** [comment]
3/28: No new progress.  Been focused on fixing bugs.

**Comment by hyoo** [comment]
We already made migration. Time to close this ticket.
