### ISSUE TITLE
Negative Genome counts in pathway tool

### ISSUE THREAD

**Issue by bparrello** [PATRIC3/patric3_website#52]
Enter the URL

http://patricbrc.org/portal/portal/patric/CompPathwayMap?cId=131567&cType=

Several genome counts are negative.

Here is how I got there:

Start the Comparative Pathway tool.

Search for EC Number 4.4.1.15

One subsystem shows up (Cysteine and methionine metabolism)

Select the subsystem to see the error.

**Comment by bparrello** [comment]
Corrected URL

http://www.beta.patricbrc.org/portal/portal/patric/CompPathwayMap?cType=taxon&cId=131567&dm=&feature_id=&ec_number=&map=00270&pk=&algorithm=PATRIC

**Comment by hyoo** [comment]
this is fixed and available on www.beta.patricbrc.org.
