### ISSUE TITLE
User data sharing and deleting

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#520]
Users will be able to share objects that they own in their workspaces with others. They will also be able to delete objects that they own as well.

**Comment by rkenyon** [comment]
10/14 update: Per the jam session, this was limited to UI ability to see shared data by whoever has permissions.  However, the user will not yet be able to actually share with others.  The specific application for November will be just to publish high value data sets publicly (see related ticket).

**Comment by cshenry** [comment]
But this should not be assigned to me. I have no ability to modify the front end at all, and I don't think this involves any backend work.

**Comment by rkenyon** [comment]
11/18:  This is out for November.

**Comment by rkenyon** [comment]
02/24: De-priortized for now until we get some more urgent items completed.

**Comment by hyoo** [comment]
@nconrad is this targeted to May or June? please tag the milestone.
