### ISSUE TITLE
Tight linkage between Annotation and Assembly Services

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#521]
Assembling a genome using short read data and then annotating the resulting sequence using RASTtk is a common task sequence for PATRIC and RAST users. At present, a user must run these as two separate steps, using the output of one as the input for the next, and waiting until the assembly step is complete before the annotation step can be launched. We will enable users to submit sequencing reads and move through the stages of assembly, annotation, and model construction easily and with the fewest possible steps, greatly streamlining use of PATRIC for researchers.

Requires some UI changes as well, and brings up the issue of chaining services together in a generic way.

**Comment by rkenyon** [comment]
10/14 update: Feasible for Nov Release.  Significant discussion regarding UI implications.

**Comment by rkenyon** [comment]
10/28: Still feasible.  Andrew writing app specs and doing pull request.  Bob will review.  If OK, Andrew will start on UI work.

**Comment by rkenyon** [comment]
11/18: Still feasible.  Straightforward if settle on JSON coming from Assembly.  Set flag to run annotation or just used combined JSON ("annotation child").

**Comment by rkenyon** [comment]
11/23: Dependent on Annotation Service updates.

**Comment by rkenyon** [comment]
12/2: Not going to make it for November release.

**Comment by rkenyon** [comment]
02/24: De-prioritized for now until we get some other things done, such as batch upload.

**Comment by dawenx** [comment]
i'm going through issues that have "upload" word and saw this one. @rkenyon is this the originator of workflow service we are going to deliver in next march? :)

**Comment by rkenyon** [comment]
Done via new Comprehensive Genome Analysis Service.
