### ISSUE TITLE
Update molecular interaction data (STRING DB)

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#522]
External public data relating to molecular interactions will be updated and made available in this release. Molecular interaction data, such as direct physical and indirect functional associations, will be updated by integrating the latest STRING database. 
#390

**Comment by rkenyon** [comment]
10/14 update: Maulik will modify PPI scripts to bring in data from STRING DB.  On target for November Release, per Maulik.

**Comment by mshukla1** [comment]
#390

**Comment by rkenyon** [comment]
Per the Semi-Annual Report, we will compare existing PATRIC PPIs and functionality to STRING DB

**Comment by rkenyon** [comment]
11/18: Maulik will look into what STRING DB does next week and come up with summary recommendations.

**Comment by rkenyon** [comment]
11/23: Maulik has not yet had a chance to look.

**Comment by rkenyon** [comment]
12/2: Not in for November

**Comment by hyoo** [comment]
available on production.
