### ISSUE TITLE
Inconsistent host_name data in genome core

### ISSUE THREAD

**Issue by dmachi** [PATRIC3/patric3_website#524]
There are several variations on human, homo sapiens in the genome core, which makes the faceting wierd.  Can they be cleaned up?

![www patric local_3000_view_genomelist_ eq antimicrobial_resistance susceptible view_tab genomes filter eq host_name human 2c 20homo 20sapiens -1](https://cloud.githubusercontent.com/assets/190574/10504295/d8a81994-72cc-11e5-8c83-492ce2a8e7b2.png)

**Comment by mshukla1** [comment]
fixed on production solr.
