### ISSUE TITLE
Differential expression import failed

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#525]
I am trying to make a user guide for differential expression and I downloaded a microarray dataset from GEO and tried to follow the steps for uploading it and importing it.  I can see that the job failed, but I don't know why.  Could somebody check it and see what happened?

**Comment by mshukla1** [comment]
Rebecca, I believe this worked after we made small changes in the upload file, right? If so, please close the ticket.

**Comment by ARWattam** [comment]
Worked, but should keep in mind that user may not know how inflexible the requirements are.
