### ISSUE TITLE
Download of RNA sequences has everything BUT the sequence!!!

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#526]
Here's what it look likes:
![screen shot 2015-10-17 at 8 52 27 am](https://cloud.githubusercontent.com/assets/11475316/10558833/71b11baa-74ac-11e5-87a5-ca25dcfe1d68.png)

I want my sequences!!!

**Comment by mshukla1** [comment]
Not sure where you got this from. Is this from table download or FTP site? 

In either case, it looks like you downloaded tab delimited file and expecting see sequences in there, 
which were never meant to have sequences. 

If you want sequences, I would think you would either 
a) select the features from the table and download DNA sequences, or
b) go to FTP and download .frn file ftp://ftp.patricbrc.org/patric2/patric3/genomes/360116.4/360116.4.PATRIC.frn <ftp://ftp.patricbrc.org/patric2/patric3/genomes/360116.4/360116.4.PATRIC.frn>

Am I missing something?

**Comment by ARWattam** [comment]
I got it from the landing page for the genome.   I hit the download genome data button and chose the RNAS.

Why in the world would anyone want this file if it didn't have the sequences in there?  What do you envision a user doing with that file?  Without the sequences its just a list, and not a very useful one.

**Comment by mshukla1** [comment]
Can you please send me the screenshot of the page/button/link from where you downloaded it?

**Comment by ARWattam** [comment]
Here they are in order of clicks.  Screenshot on is the genome landing page for the MSU Goat genome from Coxiella.  I clicked on "download genome data"
![screen shot 2015-10-17 at 5 20 21 pm](https://cloud.githubusercontent.com/assets/11475316/10561369/a2a4ccce-74f3-11e5-9ef8-35c90eac95ae.png)
Second screenshot- hit the PATRIC RNAs:
![screen shot 2015-10-17 at 5 20 39 pm](https://cloud.githubusercontent.com/assets/11475316/10561370/b5e96506-74f3-11e5-809e-bbf3825e12f9.png)
Third screenshot
![screen shot 2015-10-17 at 5 20 50 pm](https://cloud.githubusercontent.com/assets/11475316/10561373/caf7be48-74f3-11e5-8618-453e8f3b1027.png)
 is the downloaded text file that you have already seen:

**Comment by mshukla1** [comment]
Again, rna.tab file is similar to the tab-delimited and excel files you download from the feature table and other pages on the PATRIC website all the time, and they do not contain DNA and protein sequences. 

It is not a bug, it is by design. RNA sequences are available in the .frn files in the fasta format.
