### ISSUE TITLE
PATRIC RNA fasta file on ftp site is obsolete

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#527]
A user was describing his problem to me.  He wants to get all the small subunit RNAs for all bacteria.  To do this he went to the ftp site, into patric_rna and what he found in there was sequences with the old vbi locus tag.  He needs peg ids as he needs to have the genome id imbedded in the locus tags.  This file on the ftp site needs to be updated with the peg ids.

**Comment by mshukla1** [comment]
All the frn files have been updated after we migrated to the new identifier scheme 
last year to have patric/peg ids. 

Please make sure user is getting the fern files from the current release directory on FTP, 
and not PATRIC2 achieves: 

ftp://ftp.patricbrc.org/patric2/current_release/frn/ <ftp://ftp.patricbrc.org/patric2/current_release/frn/>

**Comment by ARWattam** [comment]
Gracias, Senior Shukla
