### ISSUE TITLE
Private experiment data does not appear in list on Transcriptomics page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#529]
When I have genomes I have annotated, I can see that private data on the genomes list table when I am logged in.  For consistency, I think that we should be able to see the private experiments as well.  The only way to view that data is to go through the workspace.  It would be bad to see it in the other table as well, especially since users can then compare it to the public data sets.  We used to be able to do this.

**Comment by mshukla1** [comment]
To make private transcriptomics data throughout the site, like private genomes, required full integration of transcriptomics 
data into solr, which is not there yet. I think we have planned it for sometime early next year. 

However, I do agree that we need ability to add both public and private transcriptomics data into the same group 
and ability to load them in the same gene list, sooner.

-Maulik

**Comment by mshukla1** [comment]
#406
