### ISSUE TITLE
GC% is 0?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#530]
I was looking at some of the Mycobacterium genomes today and saw that the GC% was 0 in a number of them.  Is this something we map directly from GenBank, or are there some problems with the way it is being assigned?
![screen shot 2015-10-21 at 11 06 51 am](https://cloud.githubusercontent.com/assets/11475316/10647775/7292a282-7808-11e5-900e-550cfbca618b.png)

**Comment by mshukla1** [comment]
I will look into it and correct the ones needed.

**Comment by mshukla1** [comment]
missing GC content have been added for 4350 genomes. Now, there are only 3 genomes in the database without GC content, which is linked to another problem with those genomes. 

-Maulik
