### ISSUE TITLE
Problem with having to log in twice persists

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#531]
I was trying to create a genome group, and it asked me to login, which I did.  Then I tried to create the group a second time, and it asked me to login again.  You can see from the screenshot below that I am logged in, but the login box is still popping up.  The third time seemed to stick.
![screen shot 2015-10-28 at 6 57 35 am](https://cloud.githubusercontent.com/assets/11475316/10786640/a86ef37c-7d41-11e5-89e5-3b9d2c059fea.png)

**Comment by mshukla1** [comment]
#607

**Comment by hyoo** [comment]
#545
