### ISSUE TITLE
Heatmap of Protein Families crashing.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#533]
When I try to anchor the heatmap with a group of Corynebacterium genomes (67 genomes), I get an error message that says "A plugin Shockwave Flash is not responding" and it fails to anchor the heatmap.
![screen shot 2015-10-29 at 10 30 02 am](https://cloud.githubusercontent.com/assets/11475316/10821341/55dcc804-7e28-11e5-8681-18ac272e0d92.png)

**Comment by mshukla1** [comment]
I believe this is a web browser issue, i.e. your browser is consuming too much memory or too much data for web browser to handle. If you have any additional web pages open, closing them might help. Hopefully, website redesign will improve the performance to some extent. 

Harry, add any comment if you wish and close, if no action needed. 

-Maulik

**Comment by hyoo** [comment]
Agree with Maulik. I am currently working with new version of protein family and seeing that current implementation requires 3 copies of data, which is inefficient. I am working toward to optimize as well so that we can handle more data eventually.

**Comment by hyoo** [comment]
Implementing new heatmap display is a separate task. We can close this ticket.
