### ISSUE TITLE
Venn Diagrams???  Where are they?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#534]
We used to have the ability to generate a Venn diagram, and Chunhong had implemented a really nice one on PATRIC previously.  Then it somehow disappeared when we changed something (workspace I believe).  We just had a user question about creating a Venn diagram this week and it reminded me that we were going to reimplement this.  Do we have a plan for this?

**Comment by chmao1** [comment]
This was done.
