### ISSUE TITLE
Comparison ID not showing in Comparison Filter/Transcriptomics page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#535]
When a user downloads the log fold data for each experiment, the heading for each column is a comparison ID that matches to text that describes the condition.
![screen shot 2015-11-02 at 6 02 30 pm](https://cloud.githubusercontent.com/assets/11475316/10911395/9fe9b482-8212-11e5-9a88-b853bcd6755d.png)

The only way that a user could see what that number corresponds to is by checking the Column ID box in the column headers, but when I do this, the numbers don't show up.  
![screen shot 2015-11-03 at 9 55 38 am](https://cloud.githubusercontent.com/assets/11475316/10911422/bff6206c-8212-11e5-8fa4-3b2b0df22399.png)

**Comment by hyoo** [comment]
this is fixed on the new website.
