### ISSUE TITLE
Proteome Comparison submission form

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#536]
One of the PATRIC users tried the proteome comparison service and provided the following feedback as user request: 

Here is my first comment / suggestion:

The genome/strain selection is somewhat non-intuitive, given that only a handful of strains are shown each time. If possible, it would be more informative to show “234 more strains” at the bottom of the pop-out, or something like this. Also, when I type in "Escherichia coli str. K-12” it also shows a bunch of strains that are apparently non-K-12

I tried to repeat the process and kind of agree with users suggestions. More specifically, 
1. Organism selector shows genomes names that don't match the keywords entered by the user. 

![screen shot 2015-11-03 at 10 25 43 am](https://cloud.githubusercontent.com/assets/1236463/10913941/baf9c20a-8215-11e5-93a0-ff398f48ecf5.png)
1. The requirement that user specify output folder and file names before the submission button becomes active in not intuitive. Foe example, the output file name has a red flag next to it, indicating that it is required. However, no such flag is there next to output folder.

![screen shot 2015-11-03 at 10 26 17 am](https://cloud.githubusercontent.com/assets/1236463/10915959/b45cf1fc-821e-11e5-8410-df2ef12f630a.png)

![screen shot 2015-11-03 at 10 26 30 am](https://cloud.githubusercontent.com/assets/1236463/10915960/b45e3ed6-821e-11e5-80f0-0e36d6ca06de.png)

**Comment by hyoo** [comment]
@mshukla1  We have improved genome selector in submission form. Please review whether this is still necessary or close it.

**Comment by chmao1** [comment]
This issue is resolved.
