### ISSUE TITLE
Links to String are broken.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#538]
It seems like the changes at RefSeq are impacting our links out to the other resources.  When I was was looking at FtsZ in Corynebacterium this morning and demonstrating how you could go directly to String, the link was broken.  I tried a couple of different organisms and got the same result.  Screenshots attached.
![screen shot 2015-11-04 at 11 01 52 am](https://cloud.githubusercontent.com/assets/11475316/10943933/b2146d1e-82e4-11e5-8f45-75a665d1283d.png)
![screen shot 2015-11-04 at 11 02 32 am](https://cloud.githubusercontent.com/assets/11475316/10943935/b4f01a38-82e4-11e5-9c98-56d66cea2367.png)

**Comment by hyoo** [comment]
This is specific to outdated website.
