### ISSUE TITLE
Top section of App Forms cut off

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#54]
Sometimes when I go to the Genome Assembly or Genome Annotation forms, the top part of the form is cut off.  

http://www.beta.patricbrc.org/app/Assembly

See attached screenshot.

![workspace screen grab](https://cloud.githubusercontent.com/assets/3188570/6695572/9f7d52d4-ccb8-11e4-9b84-26f3979072fa.jpg)

**Comment by dmachi** [comment]
This is because it isn't logged in, which shouldn't be allowed and  is represented in #53, so I'm closing this as a duplicate.
