### ISSUE TITLE
Download from feature table not working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#540]
I was working with Mycobacterium marinum M, went to the feature table and sorted on PE family.  It returned 142 genes.  I selected them all, and when I tried to download using excel, nothing happened.  I oped the developer view and it lists the error as getSortersInText is not defined.
![screen shot 2015-11-04 at 12 32 31 pm](https://cloud.githubusercontent.com/assets/11475316/10946428/3ea9fc7a-82f0-11e5-8672-3fc838498f7a.png)

**Comment by hyoo** [comment]
It seems like this was due to the cache. Andrew was able to get around by using anonymous mode and I was not able to replicate it.
