### ISSUE TITLE
Why are there two "status" rows on the jobs page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#542]
I was trying to delete a job and saw this.  It looks a bit odd.
![screen shot 2015-11-18 at 1 28 33 pm](https://cloud.githubusercontent.com/assets/11475316/11250042/6ca1d3ba-8df8-11e5-926f-6b9475d7473c.png)

**Comment by dmachi** [comment]
The first is the status indicator (the colored dot) and the second is the text.  To get rid of this, these two fields will need to be collapsed into one with a new formatter.

**Comment by hyoo** [comment]
you can use "unhidable" property to remove from the column selector.
