### ISSUE TITLE
Cannot download information from heatmap when selecting from private genomes

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#544]
In Protein Family sorter, I filtered for all the genes unique to my set of private genomes.  Went to the heatmap and selected all, but no matter how I do it or try, it comes up with the pop up saying that I haven't selected anything.
![screen shot 2015-11-23 at 9 45 22 am](https://cloud.githubusercontent.com/assets/11475316/11339361/2cd2b650-91c7-11e5-877f-16a7f99d9b19.png)

**Comment by hyoo** [comment]
This is specific to outdated website.
