### ISSUE TITLE
Pathway Heatmap errors

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#547]
Mycobacterium -> pathway tab -> select TCA cycle. Pathway map looks fine. 

However, heatmap seems to have errors. Lots of genomes seems to be missing 
all the ec numbers. When I mouseover on the black cells, it displays zero members in the mouseover tooltip panel above heatmap. However, when I click on that genome name, it shows that all those proteins/ec numbers are present in the genome. 

<img width="1440" alt="screen shot 2015-11-24 at 5 12 52 am" src="https://cloud.githubusercontent.com/assets/1236463/11365206/826250be-926a-11e5-8e29-3aed112efe74.png">

<img width="1440" alt="screen shot 2015-11-24 at 5 12 59 am" src="https://cloud.githubusercontent.com/assets/1236463/11365209/8a4e31e4-926a-11e5-878a-79edcc935c30.png">

**Comment by hyoo** [comment]
I can reproduce this bug. will work on it.

**Comment by hyoo** [comment]
it was due to the 20k limit on data api side. I have fixed it and available on beta.
https://www.beta.patricbrc.org/portal/portal/patric/CompPathwayMap?cType=taxon&cId=1763&dm=&feature_id=&ec_number=&map=00020&algorithm=PATRIC&pk=

**Comment by mshukla1** [comment]
Verified. Fixed.
