### ISSUE TITLE
Download not responding to filtering-Protein Family Sorter Table

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#549]
I choose two families to download the data from:
![screen shot 2015-11-28 at 1 56 18 pm](https://cloud.githubusercontent.com/assets/11475316/11453418/1810da2a-95d8-11e5-9f9a-8b6b67a0d6f8.png)

And I got everything:
![screen shot 2015-11-28 at 1 56 46 pm](https://cloud.githubusercontent.com/assets/11475316/11453420/23f01716-95d8-11e5-955b-d5401eab9906.png)

**Comment by hyoo** [comment]
as far as I understand, download is not designed nor implemented to the selection. Yes, it is NOT consistent, but that’s what it is. Yes, this is confusing and that’s why we’re going to have two different group of action icons in new version.

On Nov 28, 2015, at 1:58 PM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


I choose two families to download the data from:
[screen shot 2015-11-28 at 1 56 18 pm]<https://cloud.githubusercontent.com/assets/11475316/11453418/1810da2a-95d8-11e5-9f9a-8b6b67a0d6f8.png>

And I got everything:
[screen shot 2015-11-28 at 1 56 46 pm]<https://cloud.githubusercontent.com/assets/11475316/11453420/23f01716-95d8-11e5-955b-d5401eab9906.png>

**Comment by mshukla1** [comment]
Second what Harry said. In almost all the tables throughout PATRIC, table/excel downloads never work with selection, 
always download all the results. We need to make sure it gets addressed to satisfection in the new design. 

-Maulik
