### ISSUE TITLE
MAJOR ERROR!!-When asking to download all genes from Protein Family Sorter Table-only getting data from single genome

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#550]
How are we going to do this workshop with ALL THESE BUGS???????
From the Protein Family Sorter Table I wanted to download all the information for 2 families. From the screenshot below you can see that the families have 45 and 47 proteins: 
![screen shot 2015-11-28 at 2 03 18 pm](https://cloud.githubusercontent.com/assets/11475316/11453445/f9448e7e-95d8-11e5-8cc0-cea9ba604db5.png)
And what I get in the download are all the proteins, and from ONE genome, a private genome, incidently:
![screen shot 2015-11-28 at 2 04 18 pm](https://cloud.githubusercontent.com/assets/11475316/11453450/261b1f80-95d9-11e5-8e5d-7f8c7b5e6c2c.png)

**Comment by mshukla1** [comment]
Again, as described in the other ticket, the table/excel download doesn’t work with selected rows. 
It always downloads all the records, something that should be addressed in the new design. 

You downloaded family details file, which contains protein families and all of their members
with protein level informations, i.e. genome name, accession, patric id, locus tag, start, end, etc. 

It seems, by default, the downloaded file is sorted by genome name. Hence,  all the members from
one genome are listed at the top. However, you should have got other 44 genomes in your download 
file as well.  

Hope this explains. 

-Maulik

**Comment by ARWattam** [comment]
I don't think you read what I said.  43 genomes were loaded, and it downloaded information for only 1.  I don't care if it downloads everything, I care that it only downloads it for one single genome and not for 43.

**Comment by ARWattam** [comment]
Okay, now I see.  It used to download either by protein family, or by alphabetical species strain.  Now it seems to be choosing to show private genomes first.  I can fix it by sorting in excel.  The changing patterns in the download is confusing to me.

**Comment by mshukla1** [comment]
Just to make sure I understood correctly, you did get all genomes in the file you downloaded, right? 

Also, Can you send me the file you downloaded, as it is without resorting it?

-M

**Comment by ARWattam** [comment]
I sent it in response to the private email. I'll forward that.  Btw, are you working on Protein Family Sorter as it has stopped working for me.  Maybe I just made it really, REALLY angry by not appreciating it.

Rebecca

----- Original Message -----

**Comment by hyoo** [comment]
This is specific to the JBoss website.
