### ISSUE TITLE
Inconsistency between data in table and what is seen in download

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#551]
I downloaded all the protein families from E. coli  K12 MG1655.  On the protein family page it says that there are 4407 families (PLFams) found:
![screen shot 2015-11-28 at 10 00 43 pm](https://cloud.githubusercontent.com/assets/11475316/11455133/b5313e24-961b-11e5-9893-bba3473a4bed.png)
But when I download it, the excel file has 4549 protein families.  Why is there discrepancy?

**Comment by mshukla1** [comment]
There are two different  excel file downloads available from protein family toolbar.

1. Excel file: which lists protein families and their summary as shown in the family list table. 
I downloaded the file and it contains exactly the same number of rows as displayed in the 
table, 4407. 



2. Family details excel file: which contains list of protein families and each of their member proteins, 
hence, it has more rows than what is displayed in the summary table…i.e. case of MG1655, there are 
4549 rows. 



I do not see any descripancy here. 

-Maulik
