### ISSUE TITLE
Is there a maximum download for names of PLFams?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#552]
I am trying to download just the names of the protein families for Escherichia.  I subdivided the genome list into 300 genomes, am able to load the protein families, but when I get to the download, I encounter an error.  I was able to download the family names for 19,000, but anything above that I get this error:
![screen shot 2015-11-29 at 8 46 24 am](https://cloud.githubusercontent.com/assets/11475316/11457410/0b3a50e4-9676-11e5-8602-fe1d21b4f923.png)

**Comment by hyoo** [comment]
I think we set 20k limit, but it should alert before it process the request. I will double check why the alert did fail.

**Comment by hyoo** [comment]
this is specific to outdated website.
