### ISSUE TITLE
SRA file format support

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#554]
@mshukla1 wanted me to throw a ticket up here for @levinas to record the support request from @ARWattam
The idea is to auto-convert SRA formatted files into a PATRIC fastq/reads object to reduce the overhead required of the user.
This would be a post-upload triggered conversion to fastq using SRA format files.
This would be especially handy when/if we get URL based uploads working.
We can use this tool for the conversion http://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=fastq-dump

**Comment by levinas** [comment]
@ARWattam @mshukla1 @ARWattam
Are there SRA formatted files that are not in SRA? 
If not, should we just let users enter SRA ID rather than re-upload their own downloaded .sra files? The backend can download the files directly from SRA using `fastq-dump`.

**Comment by aswarren** [comment]
Not that I'm aware of. Sounds like a good solution to me. That would bring
it into the realm of a URL driven uploader. Which we also need/want.

**Comment by mshukla1** [comment]
Assembly service now allows users to just provide an SRA run accession as input. The service gets relevant read files from SRA and does the assembly. 

<img width="836" alt="screen shot 2017-09-17 at 11 24 38 am" src="https://user-images.githubusercontent.com/1236463/30522740-d1107714-9b9a-11e7-80df-cdd022efceb9.png">
