### ISSUE TITLE
support for interleaved FASTQ paired-end reads in RNA-seq

### ISSUE THREAD

**Issue by levinas** [PATRIC3/patric3_website#555]
@mshukla1 found this limit in the current services.

**Comment by mshukla1** [comment]
Fangfang, any update on this?

**Comment by mshukla1** [comment]
@aswarren Do you know if this is still an issue and need to be addressed? 

If not, please close the ticket. 

-Maulik

**Comment by mshukla1** [comment]
@aswarren Can you please verify this is resolved? If not, please make it part of the July release.
