### ISSUE TITLE
Genome List: add date_inserted/modified

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#557]
We need to made date inserted and date modified available as a columns in the genome list
and make the list sortable by those columns. 

This will be the easiest way for anyone to find the most recently added/updated genomes using we website. 

-Maulik

**Comment by dmachi** [comment]
You want date inserted on each genome in the group or for the group overall?

**Comment by mshukla1** [comment]
My request was for adding it for each genome in the genome list displayed at the taxon levels. 

However, it should also apply to any table showing a list of genomes, including those in genome groups, 
genome metadata on the genome overview page, and the metadata side panel in the workspace. 

-Maulik

**Comment by dmachi** [comment]
Ok, so not in the group itself, you just want it to show date inserted/updated on every genome list?  We can certainly add that back (it was removed to make the list match what is in the jboss side).  I'm not sure I'd make it display by default as the table is crowded already, but i suppose we could.

**Comment by hyoo** [comment]
This requires some change in solr config and jboss side as well. I will work on it this evening.

Sent from my iPhone

On Dec 4, 2015, at 3:11 PM, Dustin Machi <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok, so not in the group itself, you just want it to show date inserted/updated on every genome list? We can certainly add that back (it was removed to make the list match what is in the jboss side). I'm not sure I'd make it display by default as the table is crowded already, but i suppose we could.

**Comment by hyoo** [comment]
This is available on alpha.patricbrc.org now.

**Comment by mshukla1** [comment]
Harry, see if we can push this change to production as part of bug fix release.

**Comment by hyoo** [comment]
This is already available on the production. 

https://www.patricbrc.org/portal/portal/patric/GenomeList?cType=taxon&cId=2&dataSource=&displayMode=&pk=&kw=#

btw, these fields are hidden by default.

<img width="1172" alt="date_inserted_and_modified" src="https://cloud.githubusercontent.com/assets/1236467/13400147/12346a1c-decc-11e5-858f-d950eb23ddc9.png">
