### ISSUE TITLE
Transcriptomics list showing old VBI locus tags

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#558]
When you are looking at the heatmap view on the transcriptomics page and expand the X- axis slider, it doesn't list the peg ids, but the old VBI locus tags.  Its obviously a disconnect, but neither is a good solution as both will be confusing to the user.  Best to show the gene name.

**Comment by mshukla1** [comment]
Agree. Old VBI locus tags should be replaced with the option of showing PATRIC or refseq ids. 

By gene names, if you mean short gene symbols (like phoB), I am not sure. Please remember
that those exist only for a small number of genes in a small number of genomes. 

-Maulik

**Comment by mshukla1** [comment]
It is now showing patric ids. 

@hyoo, please change the display format to =>  patric id - product

<img width="308" alt="screen shot 2016-10-25 at 12 09 57 pm" src="https://cloud.githubusercontent.com/assets/1236463/19696298/1cd13512-9aac-11e6-94d1-bb6d51515b6a.png">

**Comment by hyoo** [comment]
will be available soon.

**Comment by mshukla1** [comment]
fixed - verified on alpha.
