### ISSUE TITLE
Error message on tRNA page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#561]
Not sure what the problem is, but here is a picture of the gene with the Error message
![screen shot 2015-12-07 at 6 01 31 am](https://cloud.githubusercontent.com/assets/11475316/11626409/1ee7389a-9ca8-11e5-905e-f2eebcab4850.png)

**Comment by mshukla1** [comment]
It this it is because it is a tRNA and don’t have “protein functions”, which should 
be handled more gracefully! 

For the workshop Today, we should navigate or explain our way around it. 

-Maulik

**Comment by hyoo** [comment]
This is a same issue (#572) already fixed.
