### ISSUE TITLE
Gene expression tool

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#562]
I am worried that it is not obvious how to use the Diff. Expression Import tool.  First you must know that you have to click on the row with the gene statistics.  Then you must know that you have to click the gene list in the green column in order to see your data.  To my knowledge, this is the only app where you have to click on the green bar in order to get it to work. 
<img width="1136" alt="screen shot 2015-12-07 at 3 58 51 pm" src="https://cloud.githubusercontent.com/assets/7661533/11641060/c18f5a02-9cfb-11e5-982b-5f434bc1213d.png">
<img width="1191" alt="screen shot 2015-12-07 at 3 59 03 pm" src="https://cloud.githubusercontent.com/assets/7661533/11641061/c214cc50-9cfb-11e5-981c-3685cf660952.png">

**Comment by mshukla1** [comment]
I think it would be good to have an "eye" icon above the table that directly take you to the gene list page with all the comparisons in the experiment. 

-Maulik

**Comment by mshukla1** [comment]
We have the view and Experiment icons at the top now, which show the gene list without selecting the conditions from the table below. 

-Maulik

<img width="1070" alt="screen shot 2017-09-17 at 11 27 48 am" src="https://user-images.githubusercontent.com/1236463/30522774-570e73b6-9b9b-11e7-93db-3cc0e4dce4a7.png">
