### ISSUE TITLE
Taxon ID not showing up in Gene table, although does show up on genome landing page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#565]
I am trying to get a list of taxon ids.  I used Genome Finder and with that tool the field is empty when I add that column:
![screen shot 2015-12-14 at 12 43 41 pm](https://cloud.githubusercontent.com/assets/11475316/11788756/9e588828-a260-11e5-962b-acf76b6714cc.png)
 When I check at NCBI, a taxon ID does exist:
![screen shot 2015-12-14 at 12 43 50 pm](https://cloud.githubusercontent.com/assets/11475316/11788770/abf80dfa-a260-11e5-9607-fcae72a332a7.png)

And when I look at the individual genome, I can see the ID:
![screen shot 2015-12-14 at 12 44 23 pm](https://cloud.githubusercontent.com/assets/11475316/11788788/b986ce2a-a260-11e5-9c44-54f176183564.png)

**Comment by mshukla1** [comment]
Harry, I verified the problem. 

The taxon id shows up in the genome list, but not in genome finder. Needs to be fixed.

**Comment by hyoo** [comment]
fixed and available on beta.

**Comment by mshukla1** [comment]
It is now working on public site.
