### ISSUE TITLE
Proteome Comparison tool failing

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#566]
I have tried to submit this job twice and gotten a Bad Gateway error
![screen shot 2015-12-16 at 12 33 01 pm](https://cloud.githubusercontent.com/assets/11475316/11848672/97ba60d0-a3f1-11e5-8748-ae632241fd2c.png)

**Comment by mshukla1** [comment]
Must be a temporary glitch. I just tried and it seems to be working.
