### ISSUE TITLE
Newly created experiment group members are not displayed in workspace

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#567]
If I select a list of experiments (public) from the transcriptomics tab and save them in the workspace as an experiment group. Viewing the experiment group in workspace displays an empty table.

![experiment_group](https://cloud.githubusercontent.com/assets/6361802/11962124/660dcf9a-a8ab-11e5-839e-b5ab80e00483.png)

**Comment by mshukla1** [comment]
I had the same problem. This should be fixed soon.

**Comment by dmachi** [comment]
Fixed and pushed to beta.
