### ISSUE TITLE
Anno app fails on missing org name

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#568]
If a genome annotation app is submitted without a scientific name (possible at the API level) we get a failure in the MLST code. Need to check early on.

Use of uninitialized value $cmd[6] in join or string at /disks/p3/deployment/lib/Bio/KBase/GenomeAnnotation/Service.pm line 820.
Error invoking method annotate_strain_type_MLST: undef passed at /disks/patric-common/runtime/lib/perl5/site_perl/5.20.2/IPC/Run.pm line 1266.
    IPC::Run::_exec("/disks/p3/deployment/bin/assign_st_to_genome", "-s", 1, "-m", "/disks/patric-common/data/mlstdb-2015-1123", "--org", undef) called at /disks/patric-common/runtime/lib/perl5/site_perl/5.20.2/IPC/Run.pm line 2655
    eval {...} called at /disks/patric-common/runtime/lib/perl5/site_perl/5.20.2/IPC/Run.pm line 2534
    IPC::Run::_do_kid_and_exit(IPC::Run=HASH(0x9e7da88), HASH(0x9d99898)) called at /disks/patric-common/runtime/lib/perl5/site_perl/5.20.2/IPC/Run.pm line 1375
    IPC::Run::_spawn(IPC::Run=HASH(0x9e7da88), HASH(0x9d99898)) called at /disks/patric-common/runtime/lib/perl5/site_perl/5.20.2/IPC/Run.pm line 2807
    eval {...} called at /disks/patric-common/runtime/lib/perl5/site_perl/5.20.2/IPC/Run.pm line 2804
    IPC::Run::start(ARRAY(0x90e9ef8), "<", "/disks/tmp/RHczNDArqV", ">", File::Temp=GLOB(0x9df5110), "2>", SCALAR(0x32d35c8)) called at /disks/patric-common/runtime/lib/perl5/site_perl/5.20.2/IPC/Run.pm line 1448
    IPC::Run::run(ARRAY(0x90e9ef8), "<", "/disks/tmp/RHczNDArqV", ">", File::Temp=GLOB(0x9df5110), "2>", SCALAR(0x32d35c8)) called at /disks/p3/deployment/lib/Bio/KBase/GenomeAnnotation/GenomeAnnotationImpl.pm line 17543
    Bio::KBase::GenomeAnnotation::GenomeAnnotationImpl::annotate_strain_type_MLST(Bio::KBase::GenomeAnnotation::GenomeAnnotationImpl=HASH(0x98b17d8), GenomeTypeObject=HASH(0x9a38090)) called at /disks/p3/deployment/lib/Bio/KBase/GenomeAnnotation/GenomeAnnotationImpl.pm line 22412
    eval {...} called at /disks/p3/deployment/lib/Bio/KBase/GenomeAnnotation/GenomeAnnotationImpl.pm line 22411
    Bio::KBase::GenomeAnnotation::GenomeAnnotationImpl::run_pipeline(Bio::KBase::GenomeAnnotation::GenomeAnnotationImpl=HASH(0x98b17d8), HASH(0x98e1cf0), HASH(0x9918980)) called at /disks/p3/deployment/lib/Bio/KBase/AppService/GenomeAnnotationCore.pm line 127
    Bio::KBase::AppService::GenomeAnnotationCore::run_pipeline(Bio::KBase::AppService::GenomeAnnotationCore=HASH(0x93439c8), HASH(0x98e1cf0)) called at /disks/p3/deployment/plbin/App-GenomeAnnotation.pl line 122
    main::process_genome(Bio::KBase::AppService::AppScript=HASH(0x10733a8), HASH(0x10738a0), HASH(0x1073888), HASH(0x2520488)) called at /disks/p3/deployment/lib/Bio/KBase/AppService/AppScript.pm line 242
    Bio::KBase::AppService::AppScript::subproc_run(Bio::KBase::AppService::AppScript=HASH(0x10733a8), ARRAY(0x1073858)) called at /disks/p3/deployment/lib/Bio/KBase/AppService/AppScript.pm line 94
    Bio::KBase::AppService::AppScript::run(Bio::KBase::AppService::AppScript=HASH(0x10733a8), ARRAY(0x1073858)) called at /disks/p3/deployment/plbin/App-GenomeAnnotation.pl line 23
 at /disks/p3/deployment/lib/Bio/KBase/GenomeAnnotation/GenomeAnnotationImpl.pm line 17543.

**Comment by mshukla1** [comment]
Bob, Is this fixed already?

**Comment by olsonanl** [comment]
Hm. Unclear; I don't recall how this got triggered and if it is actually possible from the PATRIC site to submit without specifying a name.

**Comment by olsonanl** [comment]
In any event, I just pushed a fix for the pipeline to make attempts to run the pipeline with a missing scientific name not fail out in MLST.

**Comment by mshukla1** [comment]
Looks like this is fixed.
