### ISSUE TITLE
Specialty Gene Search, link to faqs broken

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#571]
https://www.patricbrc.org/portal/portal/patric/SpecialtyGeneSearch?cType=taxon&cId=131567&dm=

Link to "Specialty Gene User Guide" is broken. Please change the link to point to the following url:

http://enews.patricbrc.org/faqs/genome-feature-data-and-tools/specialty-genes-faqs/

-Maulik

**Comment by hyoo** [comment]
fixed and available on beta.

**Comment by mshukla1** [comment]
Fixed, verified on public site.
