### ISSUE TITLE
Error on feature page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#572]
I have been seeing this error on the feature pages today:
ERROR
Cause: org.hibernate.TransactionException: JDBC commit failed
Message: JDBC commit failed
See log for stacktrace
![screen shot 2016-02-02 at 1 20 21 pm](https://cloud.githubusercontent.com/assets/11475316/12759588/021b43f2-c9b0-11e5-9b64-a499fc105315.png)

**Comment by hyoo** [comment]
This is fixed.

https://www.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=RefSeq.224914.11.NC_003317.rRNA.198647.200078.fwd

**Comment by mshukla1** [comment]
Verified the fix. closing it.
