### ISSUE TITLE
Can't download sequences through the download tool

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#573]
Yet another frustration.  I have selected specific genomes that I want to get the 16S rRNA sequences from.  You can see what I selected in the screenshot below, but the file that returned only had sequences for B. melitensis 16M,which was also one of the ones I checked.  I guess I will have to go in and get them one by one...I've attached the download so that you can see for yourself.

![screen shot 2016-02-02 at 1 25 07 pm](https://cloud.githubusercontent.com/assets/11475316/12759715/b1a3c452-c9b0-11e5-8cea-1fc051c44dbd.png)

**Comment by mshukla1** [comment]
I can't find many of the genomes that you have selected in your screenshot. Are these your private genomes? 

If so, please remember that the data download tool and the FTP downloads are available only for the public genomes. I think we should have some message on the data download to make it clear to the users for now. 

Also, if you want only 16S RNA sequences for select genomes in your group, public and/or private, you can use the feature finder instead with the select genome group, search for 16S / SSU rRNAs and then download sequences using table toolbar. 

-Maulik

**Comment by ARWattam** [comment]
Ochrobactrum anthropi ATCC 49188 (in the screenshot above) is a public genome, but the others were private.  And how is a user supposed to know that you can't download the private data?  That's what makes me so frustrated.  If I don't know, how are they supposed to know?  There should be something that tells them that, and it should be something that they don't have to click to find a faq to read something very long to figure it out.  And how are they supposed to understand that you have to go to the feature table, filter on something, then do the download.  Click, click, click, click....and somewhat non-intuitive clicking.

**Comment by mshukla1** [comment]
Here are the quick fixes we can have for now. 

1. Harry, add a note on the data download tool page that it supports only public genomes.

"The Data Download Tool allows one to download data for one or more public genomes in standard file formats. Currently, it DOES NOT support private genomes. To use Data Download Tool, select one or more genomes of interest, then one or more annotation sources, followed by the file types. For further explanation, please see Download Data Tool User Guide."

2. Ron, Add the same disclaimer on the Download Tools FAQs. 

Modifying the download tool to support both public and private genomes it a major task, but something 
we should support in future. 

Regarding "And how are they supposed to understand that you have to go to the feature table, filter on something, then do the download. Click, click, click, click....and somewhat non-intuitive clicking."

Ability to find features of interest in select genome groups and save or download them, is one of the primary use cases for feature finder. If it is not intuitive, we need to make it so. If it is not explained, we should add FAQs for feature finder and explain it there. 

-Maulik

**Comment by ARWattam** [comment]
How possible would it be to, if the user had selected a private genome, a warning pops up then?

Here are some other points:
1.  Remember that there is no designation on the download tool that a genome is private or public...keep in mind that users, myself included, that reannote public genomes to make dead sure that they are all annotated exactly the same way.  How will they the users know which is public and which is private, unless they are PATRIC experts?

2.  Let's say that the warning message pops up and it says something like "Genome X is not publicly available."  Here is what they would have to KNOW to do, or we would have to explain via a faq to tell them:  "You will need to go to the genome page, click on features, filter on RNAs, filter on PATRIC annotation (or RefSeq), then click on Filter Table, then click on ALL the boxes using the radial button, then click on FASTA DNA under View at the top of the table."  Okay, see how nonintuitive it is?  

  

----- Original Message -----
