### ISSUE TITLE
Protein family table not showing empty aa length

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#574]
On a previous page I selected AA length.  PATRIC used to remember what you had chosen while you were logged in and reload the same features.  I did new search of a locus tag, opened up the PLFams, and while AA length is a column head, the field is empty:
![screen shot 2016-02-03 at 10 36 43 am](https://cloud.githubusercontent.com/assets/11475316/12787367/21b6e0fa-ca63-11e5-93c7-b2f912580dfc.png)

When I deselect, and then reselect AA length, the values appear.  This is something I haven't seen before (I do this particular exercise a lot):
![screen shot 2016-02-03 at 10 36 59 am](https://cloud.githubusercontent.com/assets/11475316/12787402/44883d4a-ca63-11e5-928a-6b0a315aba0b.png)

**Comment by hyoo** [comment]
it seems like column list information is messed up. for a quick fix, you can use “Default” button, and reload the page (I am not sure whether I fixed to reload automatically, which Maulik asked for a long time).

Yes, this is a work around. we will account this issue in the new website.

Harry

On Feb 3, 2016, at 9:45 AM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


On a previous page I selected AA length. PATRIC used to remember what you had chosen while you were logged in and reload the same features. I did new search of a locus tag, opened up the PLFams, and while AA length is a column head, the field is empty:
[screen shot 2016-02-03 at 10 36 43 am]<https://cloud.githubusercontent.com/assets/11475316/12787367/21b6e0fa-ca63-11e5-93c7-b2f912580dfc.png>

When I deselect, and then reselect AA length, the values appear. This is something I haven't seen before (I do this particular exercise a lot):
[screen shot 2016-02-03 at 10 36 59 am]<https://cloud.githubusercontent.com/assets/11475316/12787402/44883d4a-ca63-11e5-928a-6b0a315aba0b.png>

**Comment by mshukla1** [comment]
Harry, is this an easy fix that can be done as part of bug fix release? Or, should it wait for redesign?
