### ISSUE TITLE
Seeing some weird anomalies in the protein family tables

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#575]
Check out the Accession column.  Some are hyperlinks, and other aren't.  This just started happening.
![screen shot 2016-02-03 at 2 20 38 pm](https://cloud.githubusercontent.com/assets/11475316/12794099/7dd78042-ca81-11e5-8b48-cd26ee47da94.png)

**Comment by hyoo** [comment]
I think we link the accession only when it starts with NZ_ or NC_.

On Feb 3, 2016, at 1:31 PM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


Check out the Accession column. Some are hyperlinks, and other aren't. This just started happening.
[screen shot 2016-02-03 at 2 20 38 pm]<https://cloud.githubusercontent.com/assets/11475316/12794099/7dd78042-ca81-11e5-8b48-cd26ee47da94.png>

**Comment by mshukla1** [comment]
Harry, 

Given that now we get genomes from GenBank and not RefSeq, the accession numbers will not have NZ or NC prefix. We need to revisit the logic to make the links work for all NCBI genomes. 

-Maulik

**Comment by hyoo** [comment]
https://www.ncbi.nlm.nih.gov/news/03-02-2016-phase-out-of-GI-numbers/

this may impact on this issue.

**Comment by hyoo** [comment]
http://www.ncbi.nlm.nih.gov/nuccore/[ACCESSION] 

seems like working. need to verify with Maulik when he come back.

**Comment by hyoo** [comment]
this is specific to outdated website.
