### ISSUE TITLE
Download from transcriptomics gene table not working properly-New error

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#577]
I filtered on the data and got 816 genes that met the criteria I set.  Then I reset the table to 100.  I wanted only 100 of the genes that were from a specific genome, and selected download in excel.  Instead of seeing the 100 I selected, I got them all.

**Comment by mshukla1** [comment]
Download excel and text file always downloads ALL the results, not just those that are displayed on the page. This is not a bug or something new, it was always like that. 

Having said that, if it is a usability issue / confusing, we should certainly revisit it as part of the website redesign.
