### ISSUE TITLE
PLF_1716_00005034

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#578]
This PattyFam has a product description as "No significant database matches".  New way of saying hypothetical?
![annotation](https://cloud.githubusercontent.com/assets/11475316/12960063/35bb2b84-d007-11e5-8f49-8fa1925f3df1.png)

**Comment by olsonanl** [comment]
hah, that’s the annotation in coreseed for those proteins.

http://core.theseed.org/FIG/seedviewer.cgi?page=Annotation&feature=fig|100226.1.peg.8143<http://core.theseed.org/FIG/seedviewer.cgi?page=Annotation&feature=fig%7C100226.1.peg.8143>

—bob

On Feb 10, 2016, at 2:01 PM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


This PattyFam has a product description as "No significant database matches". New way of saying hypothetical?
[annotation]<https://cloud.githubusercontent.com/assets/11475316/12960063/35bb2b84-d007-11e5-8f49-8fa1925f3df1.png>

**Comment by olsonanl** [comment]
There were exactly 5 functional roles like that in the CoreSEED and all of them in Streptomyces coelicolor A3(2). Interestingly they had a period at the end of the role. Now those don’t exist in the CoreSEED anymore. Additionally there were 282 without a period. I tried to globally change them to "hypothetical protein", but the SEED viewer choked on them and I renamed the 282 to “hypothetical". Now it would be good if someone could rename the 290 “hypothetical” guys to "hypothetical protein” from the command line, without using the SEED Viewer. Gary must have missed all of them when he was cleaning up the hypotheticals. 

Veronika

**Comment by olsonanl** [comment]
Hm, search is showing them in other orgs too

I can make that change. We do have a “hypothetical” from earlier:

| prot                   | assigned_function | last_modification   |
+------------------------+-------------------+---------------------+
| fig|217.1.peg.395      | hypothetical      | 2015-11-03 13:47:57 |
| fig|296591.12.peg.2433 | hypothetical      | 2015-11-03 13:52:38 |
| fig|342108.5.peg.3976  | hypothetical      | 2015-11-03 13:54:03 |
| fig|471853.5.peg.3784  | hypothetical      | 2015-11-03 13:56:59 |
| fig|471870.8.peg.2222  | hypothetical      | 2015-11-03 13:57:05 |
| fig|573234.4.peg.13    | hypothetical      | 2015-11-03 13:58:53 |
| fig|575609.3.peg.576   | hypothetical      | 2015-11-03 13:58:59 |
| fig|657314.3.peg.422   | hypothetical      | 2015-11-03 14:00:05 |
| fig|743718.4.peg.2713  | hypothetical      | 2015-11-03 14:00:56 |
| fig|1007096.3.peg.908  | hypothetical      | 2015-11-03 14:02:19 |
+------------------------+-------------------+---------------------+

I’ll go ahead and change those as well.

—bob

On Feb 10, 2016, at 3:25 PM, Veronika Vonstein <vonstein.veronika3@gmail.com<mailto:vonstein.veronika3@gmail.com>> wrote:

There were exactly 5 functional roles like that in the CoreSEED and all of them in Streptomyces coelicolor A3(2). Interestingly they had a period at the end of the role. Now those don’t exist in the CoreSEED anymore. Additionally there were 282 without a period. I tried to globally change them to "hypothetical protein", but the SEED viewer choked on them and I renamed the 282 to “hypothetical". Now it would be good if someone could rename the 290 “hypothetical” guys to "hypothetical protein” from the command line, without using the SEED Viewer. Gary must have missed all of them when he was cleaning up the hypotheticals.

Veronika


On Feb 10, 2016, at 2:42 PM, Olson, Robert D. <olson@mcs.anl.gov<mailto:olson@mcs.anl.gov>> wrote:

hah, that’s the annotation in coreseed for those proteins.

http://core.theseed.org/FIG/seedviewer.cgi?page=Annotation&feature=fig|100226.1.peg.8143<http://core.theseed.org/FIG/seedviewer.cgi?page=Annotation&feature=fig%7C100226.1.peg.8143>

—bob

On Feb 10, 2016, at 2:01 PM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


This PattyFam has a product description as "No significant database matches". New way of saying hypothetical?
[annotation]<https://cloud.githubusercontent.com/assets/11475316/12960063/35bb2b84-d007-11e5-8f49-8fa1925f3df1.png>

**Comment by mshukla1** [comment]
Ugly, but I don't consider it something that needs to be addressed quickly. 

I guess the changed annotation will propagate when we sync the annotation next time and we can wait until then.

**Comment by olsonanl** [comment]
yes, that is correct.

On Feb 24, 2016, at 3:01 PM, mshukla1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Ugly, but I don't consider it something that needs to be addressed quickly.

I guess the changed annotation will propagate when we sync the annotation next time and we can wait until then.

**Comment by mshukla1** [comment]
Given that Bob has fixed the annotation in core seed, I am closing the issue.
