### ISSUE TITLE
download tool for faa files seem to provide other binary "crap"

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#579]
We were collecting faa files for some genomes, and we've found some weird binary files.  Here's what they look like:
1087452.3.PATRIC.faa.phr
1087452.3.PATRIC.faa.pin
1087452.3.PATRIC.faa.psq
1087453.4.PATRIC.faa
1087453.4.PATRIC.faa.phr
1087453.4.PATRIC.faa.pin
1087453.4.PATRIC.faa.psq
1087454.3.PATRIC.faa
1087454.3.PATRIC.faa.phr
1087454.3.PATRIC.faa.pin
1087454.3.PATRIC.faa.psq
1089446.3.PATRIC.faa
1089446.3.PATRIC.faa.phr
1089446.3.PATRIC.faa.pin
1089446.3.PATRIC.faa.psq
1117942.3.PATRIC.faa

**Comment by mshukla1** [comment]
It could be a temporary thing when I was generating the BLAST libraries. However, I checked the download directories for each of the genomes listed above and did not see the blast database files. 

How did you collect/see these files and from where?

-Maulik

**Comment by mshukla1** [comment]
Checked with Rebecca, the BLAST files may have been generated when she ran the phylogeny pipeline, which may have place temp blast dabatase in her original data download directory. 

Closing the issue, reopen if needed.
