### ISSUE TITLE
Getting java.lang.NullPointerException error in some pages

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#58]
Minor problem, because the page still loads.  It is happening for me on the MG-RAST page:

http://patricbrc.org/portal/portal/patric/MGRAST

![mgrast page error](https://cloud.githubusercontent.com/assets/3188570/6715376/88d815e8-cd74-11e4-8a8e-207201b0b10b.PNG)

**Comment by hyoo** [comment]
this is fixed on www.beta
