### ISSUE TITLE
Collaborator reports assembly failure, and can't figure out why the failure happened

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#580]
Here's what he did:

"I tried to run an assembly using raw data from a 200bp mate pair library and it didn't work.
I used "Paired reads library", chose the option "True" in "File 1 interleaved", 'True"in "Mate paired", and the option "auto" in "Assembly strategy".

Here's what returned:
![assembly fail](https://cloud.githubusercontent.com/assets/11475316/13123053/38ede7c0-d588-11e5-8c2f-66d4917790ea.png)

**Comment by levinas** [comment]
@olsonanl , the perl error points to this line:
https://github.com/TheSEED/app_service/blob/master/scripts/App-GenomeAssembly.pl#L195
I have not seen this error before. Could there be a reason for `$id` not to be set? Thanks.

**Comment by levinas** [comment]
I now understand the issue and have generated a pull request to fix this error. 
https://github.com/TheSEED/app_service/pull/44

I'll test on the production site once this is merged and deployed. 
We will then ask the user to try again.

**Comment by olsonanl** [comment]
This is deployed now.

On Feb 24, 2016, at 10:53 PM, Fangfang Xia <notifications@github.com<mailto:notifications@github.com>> wrote:


I now understand the issue and have generated a pull request to fix this error.
TheSEED/app_service#44<https://github.com/TheSEED/app_service/pull/44>

I'll test on the production site once this is merged and deployed.
We will then ask the user to try again.

**Comment by levinas** [comment]
Thanks Bob.

**Comment by levinas** [comment]
@mshukla1 @ARWattam : A fix has been deployed and tested on the production. We should invite the user to try again with the following caveat:

Mate pair sequencing involves generating long-insert paired-end DNA libraries with the two reads in the pair pointing outward. If the user knows the insert size is 200bp, it's likely not mate pair but regular paired end reads. In that case, the advanced "Mate paired" value should not be set.

**Comment by mshukla1** [comment]
@ARWattam : Can you please follow up with the user and ask to try again?

**Comment by ARWattam** [comment]
User is running right now.  We'll see...
