### ISSUE TITLE
Search doesn't work as expected

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#581]
A quick search of the following 15 peg ids in the feature finder yields 25 results. I then had to parse those results by hand.  It would be best that if an id is given that it returns a match to that exact id.

fig|1446588.3.peg.1885
fig|1446593.3.peg.2475
fig|1005515.3.peg.2698
fig|1444132.3.peg.2423
fig|1446594.3.peg.197
fig|1446587.3.peg.3389
fig|1116015.3.peg.4693
fig|1446595.3.peg.4606
fig|1446594.3.peg.433
fig|1446595.3.peg.5085
fig|478004.5.peg.5725
fig|1116125.3.peg.5000
fig|754080.3.peg.1370
fig|1444083.3.peg.4184
fig|1048266.3.peg.5137

**Comment by olsonanl** [comment]
If you search with double quotes "fig|1446588.3.peg.1885” it works as you expect; but I agree - identifiers that match PATRIC ids precisely should directly go to that feature’s page.

—bob

On Feb 22, 2016, at 9:54 AM, jimdavis1 <notifications@github.com<mailto:notifications@github.com>> wrote:


A quick search of the following 15 peg ids in the feature finder yields 25 results. I then had to parse those results by hand. It would be best that if an id is given that it returns a match to that exact id.

fig|1446588.3.peg.1885
fig|1446593.3.peg.2475
fig|1005515.3.peg.2698
fig|1444132.3.peg.2423
fig|1446594.3.peg.197
fig|1446587.3.peg.3389
fig|1116015.3.peg.4693
fig|1446595.3.peg.4606
fig|1446594.3.peg.433
fig|1446595.3.peg.5085
fig|478004.5.peg.5725
fig|1116125.3.peg.5000
fig|754080.3.peg.1370
fig|1444083.3.peg.4184
fig|1048266.3.peg.5137

**Comment by mshukla1** [comment]
I agree. Having advanced search option that allow you to search by specific field and get exact match is one of the requirements for the new search interface.

**Comment by dawenx** [comment]
I tried this search and chose "any exact term", it returned 15 features. With the age of this issue and lots of improvement has been done in search, maybe we can close this?
