### ISSUE TITLE
Compile a survey of host-pathogen dual RNA-Seq data sets

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#583]
We will complete and publish a survey of the available dual RNA-Seq data that is in the
public domain. (Option 3)

**Comment by rkenyon** [comment]
3/28: Andrew working on it, almost done.

**Comment by rkenyon** [comment]
3/29:  Andrew sent out draft document.  Need to review.

**Comment by hyoo** [comment]
it seems like we no longer tracking this activity here. closing.
