### ISSUE TITLE
User-Support Batch Processing

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#585]
Batch processing support will be added to PATRIC to allow users to perform genome
annotation and assembly for large sets of data. This effort encompasses allowing users
to do bulk upload/import of their data outside of PATRIC and launching analysis jobs
against the uploaded data. Once analyzed, the results will be available for download and
use within PATRIC.

**Comment by rkenyon** [comment]
02/24: We have an internal mechanism that works (Maulik uses) and an FTP mechanism, would require some file name manipulation by user.  We need to set up a working meeting to review options and finalize plan.  Has multiple dependencies, but assigned to Bob for tracking purposes.

**Comment by mshukla1** [comment]
This should be delivered as part of the CLI release in November.

**Comment by hyoo** [comment]
@mshukla1 @rkenyon @olsonanl Can we close this now?

**Comment by mshukla1** [comment]
We are almost there. I think we should close it after we have official support for annotation app in CLI, similar to how it is for assembly. 

@olsonanl what do you think? 

-Maulik

**Comment by olsonanl** [comment]
Sounds good.

**Comment by mshukla1** [comment]
This has been addressed with the CLI release. 

-Maulik
