### ISSUE TITLE
New genome annotations have PGfams, but not PLFams

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#590]
I reannotated a number of genomes JUST to get the PLFams, and they are missing.  Frustrating.
![screen shot 2016-02-25 at 2 56 38 pm](https://cloud.githubusercontent.com/assets/11475316/13332494/3cd577e2-dbd0-11e5-9f48-ffee792aba1a.png)
![screen shot 2016-02-25 at 2 54 25 pm](https://cloud.githubusercontent.com/assets/11475316/13332493/3cd29a40-dbd0-11e5-8e73-915b2ebac53e.png)

**Comment by mshukla1** [comment]
The service relies on the scientific name of the genome to determine its genus and assign genus-specific groups. 

I noticed that both of your genomes have genome name as Brucella_3305_*, which seems to confuse the service. 
Is that how you specified the genome name in the annotation submission form? 

-Maulik

**Comment by hyoo** [comment]
@mshukla1 I guess we can close this issue, but wanted to double check.
