### ISSUE TITLE
Data API: shows all fields in tsv file 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#591]
I ran the following query to the data api: 

https://www.patricbrc.org/api/genome/?eq(reference_genome,*)&select(genome_id,genome_name)&limit(100000,0)&http_accept=text/tsv

I selected only two fields for the results. However, the returned tsv file head all  other columns listed with the null values. 

-Maulik

**Comment by dmachi** [comment]
Fixed and pushed to beta.
