### ISSUE TITLE
Data API: def line for fasta dna for genomic sequences

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#593]
https://www.patricbrc.org/api/genome_sequence/?eq(genome_id,83332.12)&http_accept=application/dna+fasta

>accn|NC_000962   Mycobacterium tuberculosis H37Rv, complete genome.   [Mycobacterium tuberculosis H37Rv]
ttgaccgatgaccccggttcaggcttcaccacagtgtggaacgcggtcgtctccgaactt
aacggcgaccctaaggttgacgacggacccagcagtgatgctaatctcagcgctccgctg

The fasta def line format needs to match the format in the fna file on the ftp site: 

>accn|NC_000962   Mycobacterium tuberculosis H37Rv, complete genome.   [Mycobacterium tuberculosis H37Rv | 83332.12]
ttgaccgatgaccccggttcaggcttcaccacagtgtggaacgcggtcgtctccgaactt
aacggcgaccctaaggttgacgacggacccagcagtgatgctaatctcagcgctccgctg

However, before making the change, need to make sure it doesn't impact any of the existing services
/ functionality. 

-Maulik

**Comment by dmachi** [comment]
@levinas will this mess up anything in any of your services?

**Comment by dmachi** [comment]
I've deployed this to beta for testing.

**Comment by levinas** [comment]
This should not be a problem for the services I've worked on. Thanks @dmachi for checking with me.

**Comment by dmachi** [comment]
fixed and deployed to beta.
