### ISSUE TITLE
Gene Overview Page: get dbxrefs based on GI

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#594]
It seems that the current dbxrefs displayed on the gene overview page rely on the uniprotkb_accession in the genome_feature core. 

Some time ago, we decided that we are not going to populate uniprotkb_accession in the genome_feature core anymore, as it is hard to maintain and update. 

Please get the dbxrefs based on the GI number associated with the feature. So, it should be, 

patric_id <-> gi number <-> uniprotkb_accession gi/gi_no <-> uniprot id_type/id_value. 

-Maulik

**Comment by hyoo** [comment]
this is fixed and available on beta.

https://www.beta.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=PATRIC.83332.111.CP003248.CDS.3325980.3326114.fwd

**Comment by mshukla1** [comment]
Fixed, verified on production.
