### ISSUE TITLE
ID Mapping Tool: use gi instead of uniprotkb_accession for mapping 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#595]
Some time ago, we decided that we are not going to populate uniprotkb_accession in the genome_feature core anymore, as it is hard to maintain and update.

Please get the dbxrefs based on the GI number associated with the feature. So, it should be,

patric_id <-> gi number <-> uniprotkb_accession gi/gi_no <-> uniprot id_type/id_value.

Here is one example: uniprotkb_accession I6XFT2, doesn't map to anything if I use ID mapping. 

However, if I go to the feature page, it does show right mappings. 

https://www.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=PATRIC.83332.111.CP003248.CDS.3325980.3326114.fwd

-Maulik

**Comment by hyoo** [comment]
This is fixed and available on beta.

https://www.beta.patricbrc.org/portal/portal/patric/IDMapping?cType=taxon&cId=131567&dm=result&pk=-2872055268149684405

**Comment by mshukla1** [comment]
Fixed, verified on production.
