### ISSUE TITLE
Can't upload in brand new account

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#599]
I created a new account to use with the workshop and find that when I try to upload a file I get an empty "Upload files to workspace" dialog.

Console sez:

[Warning] Unexpected CSS token: : (font-awesome.min.css, line 4)
[Warning] Unexpected CSS token: : (font-awesome.min.css, line 4)
[Warning] Unexpected CSS token: : (font-awesome.min.css, line 4)
[Warning] Unexpected CSS token: : (font-awesome.min.css, line 4)
[Warning] Unexpected CSS token: : (font-awesome.min.css, line 4)
[Warning] Invalid CSS property declaration at: #zoom (p3.css, line 17)
[Warning] Invalid CSS property declaration at: #display (p3.css, line 18)
[Warning] Invalid CSS property declaration at: #vertical-align (p3.css, line 22)
[Warning] Invalid CSS property declaration at: #zoom (p3.css, line 41)
[Warning] Invalid CSS property declaration at: #display (p3.css, line 202)
[Warning] Invalid CSS property declaration at: #vertical-align (p3.css, line 257)
[Warning] Invalid CSS property declaration at: #overflow (p3.css, line 288)
[Warning] Invalid CSS property declaration at: #filter (p3.css, line 313)
[Warning] Invalid CSS property declaration at: #text-indent (p3.css, line 355)
[Warning] Invalid CSS property declaration at: #letter-spacing (p3.css, line 356)
[Warning] Invalid CSS property declaration at: #text-align (p3.css, line 357)
[Warning] Invalid CSS property declaration at: #text-align (p3.css, line 393)
[Warning] Invalid CSS property declaration at: #bottom (p3.css, line 496)
[Warning] Invalid CSS property declaration at: #zoom (p3.css, line 1196)
[Warning] Invalid CSS property declaration at: #display (p3.css, line 1197)
[Warning] Invalid CSS property declaration at: #display (p3.css, line 1762)
[Warning] Unexpected CSS token: : (p3.css, line 3371)
[Error] TypeError: undefined is not an object (evaluating 'b.length')
	listWorkspaceContents
	refreshWorkspace
	startup
	(anonymous function)
	forEach
	startup
	l
	startup
	l
	startup
	openChooser
	(anonymous function)

**Comment by olsonanl** [comment]
If I reload the page (which I had to do because there were no active controls visible) I then get the dialog populated.

**Comment by dmachi** [comment]
I’ll take a look at this. Its not a new problem and basically comes from new user’s home workspace being created and populated with the default structure (and something not waiting for that to complete).  Generally speaking, if you reload after registering it resolves the problem.

Dustin

**Comment by olsonanl** [comment]
Would it be possible to get this fixed before next week's workshop?

**Comment by olsonanl** [comment]
It seems the right solution to this would be to populate the workspace at the time the account creation happens.

**Comment by dmachi** [comment]
Can’t promise at the moment, but I’ll look and see if I can figure how to fix this before next week. I’ll look and see if i can add this into account creation (right now the User service is unaware of workspaces, and i’m not sure I want to put a hard dependency between the two).

**Comment by brettin** [comment]
how about the workspace service maintains a pool of anonymous empty workspaces that can be handed out/assigned to a user on requrest.

**Comment by dmachi** [comment]
I don’t think that is necessary and makes it a more complicated.  This problem shouldn’t be hard to fix, it can just be hard to isolate and test as the problem here is a race condition.

**Comment by olsonanl** [comment]
That’s why I argue the account creation logic should create everything required for the account. Something has to know the canonical set of requirements for a valid account; if it is not the lower level service that does the raw user mgmt bits then a higher level of business logic that knows all of the requirements.

On Mar 2, 2016, at 9:59 AM, Dustin Machi <notifications@github.com<mailto:notifications@github.com>> wrote:

I don’t think that is necessary and makes it a more complicated. This problem shouldn’t be hard to fix, it can just be hard to isolate and test as the problem here is a race condition.

**Comment by mshukla1** [comment]
#48 #432
