### ISSUE TITLE
Archaea phylogeny trees

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#6]
The archaea taxon page correctly notes that currently there isn't a tree.   However, for the individual archaea genomes, the phylogeny tab is just treeless w/ no explanation (and an error shows up in the logs - Dustin caught sever logged errors which is why we discovered this)   It's not clear whether we'll get the trees soon enough and nothing needs to be done in the code, or whether we should have an error handler anyway and give the user a message.

**Comment by mshukla1** [comment]
I believe this issue has been addressed. Any taxonomy node, bacteria or archaea, that doesn't have related phylogenetic tree, will show the message like below. 
![screen shot 2015-06-10 at 12 55 34 pm](https://cloud.githubusercontent.com/assets/1236463/8088544/20e83470-0f70-11e5-845b-c0f5d6e21b9e.png)
![screen shot 2015-06-10 at 12 55 14 pm](https://cloud.githubusercontent.com/assets/1236463/8088545/20e9b2dc-0f70-11e5-846d-9aa240dde488.png)
