### ISSUE TITLE
use Genome Name (instead of Organism Name) as col header in "new workspace" and "old PATRIC"

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#60]
After consulting with Maulik and Dustin and Harry, there is agreement that in genome lists throughout the site, the column header should say "Genome Name" and not "Organism Name"  (that is already what is being queried to fill the data).   This needs changes on both the current PATRIC website code and the new Workspace code.   (So this should probably be 2 tickets instead of 1?   I assume the 1st fix can go in as a comment and the 2nd fix can close this issue?)

**Comment by dmachi** [comment]
I just committed the rename of that column in the workspace's genome list.

Dustin

**Comment by hyoo** [comment]
I have change genome list/genome finder as well.
