### ISSUE TITLE
Long lags in genome browser

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#601]
I'm looking at various contigs in the genome I just assembled & annotated, and it is taking 40-60 seconds to load the genome browser. These are not long contigs (32KB) and have fairly few features as a result.

Do we have a missing index or somesuch? It seems this operation should be nearly instantaneous.

**Comment by mshukla1** [comment]
The genome browser gets data for all the contigs in the genome during the first load, not just the contig you selected. We did the performance tuning at the time of solarization. We should probably revisit it at some point in the light of 60,000 genomes now.

**Comment by mshukla1** [comment]
Just to add, the genome browser was slow earlier as well, taking ~20-30 seconds. This may have been exacerbated Today due to the on going data release and related batch query and indexing operations. 

We should try it again after the the genome loading is finished and see if it gets any better!

**Comment by hyoo** [comment]
No, genome browser loads features in a selected contig and within the range of your window.
however, request seems wrong
![image](https://user-images.githubusercontent.com/1236467/30387490-447a5df4-9872-11e7-9824-6451c538c3da.png)

it does not actually use right start & end.
@dmachi or @aswarren do you know why the second and third requests does not start 100000 and 140000 respectively?

**Comment by hyoo** [comment]
The changes in data api side has been deployed and UI side change is on alpha. Those changes will make GB faster. We still have some issues with solr cache, but that is beyond this topic.

**Comment by hyoo** [comment]
picked two similar sized genome.

production : 54s
https://patricbrc.org/view/Genome/287.1491#view_tab=browser&loc=CP011317%3A1..100000&tracks=refseqs%2CPATRICGenes%2CRefSeqGenes&highlight=

alpha: 37s
https://alpha.patricbrc.org/view/Genome/1407059.3#view_tab=browser&loc=HG530068%3A1..100000&tracks=refseqs%2CPATRICGenes%2CRefSeqGenes&highlight=
