### ISSUE TITLE
Can only select first 30 contigs

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#602]
![screen shot 2016-02-29 at 4 08 13 pm](https://cloud.githubusercontent.com/assets/2152226/13410676/a5fbebda-defe-11e5-907e-046498ced8ef.png)

How do I select a contig other than one of the first 30?

**Comment by hyoo** [comment]
this is fixed and available on beta.

**Comment by mshukla1** [comment]
Fixed, verified on public site.
