### ISSUE TITLE
Can't zoom out without zooming in

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#603]
In the genome browser if I want to zoom out to see the whole contig the "-" buttons don't do anything unless I zoom in first.

![screen shot 2016-02-29 at 4 09 37 pm](https://cloud.githubusercontent.com/assets/2152226/13410734/ec35f726-defe-11e5-91b4-423026f0c2cd.png)

**Comment by mshukla1** [comment]
Bob, I tried multiple times and can't reproduce the problem. I am able to zoom out after the initial page load, without zooming in first. 

Please show it to me / Harry when you get a chance. 

-Maulik

**Comment by hyoo** [comment]
cannot replicate the problem.
