### ISSUE TITLE
Long delay loading protein family table

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#604]
It takes 40 seconds to load the protein family list for my genome. Seems like this should be much faster. Where is the time going?

**Comment by mshukla1** [comment]
I am going to do some more performance testing Tonight and see if it is significantly slower because of ongoing data release. 

-Maulik

**Comment by hyoo** [comment]
Now, we have moved solr to a better performing machine and configured with gc-pause-less jvm.
In addition to that, I have implemented memory caching. As a result, we can run a PFS with 88 genomes and 50k families in 12 sec, which usually took more than 5min and timed out.

I will plug this version on alpha, as soon as @olsonanl and @danielolson5 resolve certificate issue for p3c.theseed.org

**Comment by hyoo** [comment]
now, www.alpha.patricbrc.org/ works with mem-cached pfs

![image](https://user-images.githubusercontent.com/1236467/30501890-c1ec2dfe-9a29-11e7-8ae0-3c310abff9c2.png)

**Comment by hyoo** [comment]
deployed on production at Oct 13 2017.
