### ISSUE TITLE
EC search fails

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#606]
Path way tools -> ec search gets a 404

HTTP Status 404 -

type Status report

message

description The requested resource () is not available.

JBossWeb/2.0.0.GA_CP

Maulik says it needs to be removed

**Comment by mshukla1** [comment]
Ron, 

Bob is referring to the the EC Search link present on the Pathways Data landing page below. 
We decided to get rid of the go and ec searches a while ago, now that it is covered under feature search. 
Do you know  how to remove it from DLPs? Or, I can take a look at it.  

https://www.patricbrc.org/portal/portal/patric/Pathways

-Maulik

**Comment by rkenyon** [comment]
I think I can access it.  I'll take a look.

**Comment by rkenyon** [comment]
Done
