### ISSUE TITLE
Being asked to log in again even though I'm logged in

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#607]
This is something I mentioned before but was closed as nobody else saw it happening.  Here it is again...and after I went to a lot of trouble to select my group, I might add!
![screen shot 2016-03-03 at 10 12 39 am](https://cloud.githubusercontent.com/assets/11475316/13498606/b21a3878-e128-11e5-89f8-e65682b144dc.png)

**Comment by mshukla1** [comment]
#531

**Comment by dmachi** [comment]
Closed as duplicate, though I don't think this problem exists any more.
