### ISSUE TITLE
error condition not caught

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#609]
In recovering from the failed uploads I tried a reupload which failed (the upload button appeared to do nothing). It turns out the problem was that the workspace was rejecting the upload attempt because the files already existed there (zero-length) and the overwrite flag was not set. The error should get caught and reported to the user; perhaps an option to overwrite would be useful.

**Comment by nconrad** [comment]
This was resolved sometime between feb and may.  #294
