### ISSUE TITLE
HTTP Status 404 on IE 11

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#61]
Error msg - The requested resource () is not available  JBossWeb/2.0.0.GA_CP  
(I forget how to check what version of Windows is running!)  

to reproduce
global search for PRJNA259658
Click on Genomes (24)
Show 24
Apply
Select all (24) displayed genomes
Add Genomes to Workspace
Login in modal
HTTP Status 404

**Comment by hyoo** [comment]
This is an issue on global search on IE11. If you look at url, the page name is missing; you will see www.beta.patricbrc.org/portal/portal/patric/ . So when you tries to login, it goes to login module and come back to empty page, which cause 404 error. login/logout works well other pages. I guess this is related some javascript code on the page, but I am not sure yet. Will work on this.
