### ISSUE TITLE
Data download tool does not work for private genomes

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#610]
Wah!  I am trying to build some trees!  It worked before, but now I can't get faa or fna files for my private genomes. :(
This is the error message I get: "Sorry. The requested file(s) are not available."

**Comment by mshukla1** [comment]
#573

**Comment by mshukla1** [comment]
Again, data download tool does not support private genomes. 

Duplicate: #573

**Comment by mshukla1** [comment]
Harry, please replace the instructions on the data download tools page as follows: 

"The Data Download Tool allows one to download data for one or more public genomes in standard file formats. Currently, **it does not support private genomes**. To use Data Download Tool, select one or more genomes of interest, then one or more annotation sources, followed by the file types. For further explanation, please see Download Data Tool User Guide."

**Comment by ARWattam** [comment]
Okay, okay...so I'm stupid!  Maybe I just keep expecting it to work and that's what I remember working before.  Putting the message would be quite helpful.

**Comment by mshukla1** [comment]
Note has been added on the download tool on the production site.
