### ISSUE TITLE
Check box on Differential Expression restricted makes difficult to upload

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#612]
The download is in a .gmz file, but file restrictions won't let you upload it as it is restricted to different file.  This was confusing to users...it took  awhile to figure out that they needed to unclick the restrictions.
![screen shot 2016-03-08 at 10 15 18 am](https://cloud.githubusercontent.com/assets/11475316/13607706/07b812e0-e517-11e5-8dcd-5eba3b86ad32.png)

**Comment by dawenx** [comment]
i just check on the production site, it looks like this checkbox has been removed (for a while). @ARWattam  can we close this ticket?
