### ISSUE TITLE
Check on what happens when contigs are uploaded as unspecified types

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#613]
A user ran into this, and was unable to start an annotation job.  We need to explore this

**Comment by dmachi** [comment]
Services only accept the correct type.  If you have uploaded something as unspecified and want to change it.  You select the file in the workspace then you can change it by clicking on the type in the item detail panel.  See attached image.

Dustin

**Comment by olsonanl** [comment]
What happened seems to have been that the .fa file appeared in the quick dropdown but then couldn't be selected. I want to try to repeat it since it was pretty confusing.

**Comment by nconrad** [comment]
Another old ticket.  I wasn't able to replicate the case of a file of unspecified type showing up in the dropdown.  Please reopen if you know of some issue like this.
