### ISSUE TITLE
Restrictions on upload continue to be confusing

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#615]
I had a gz file to upload, and the Restrictions button was turned on, but it still wouldn't allow me to select my .gz file until I turned if off.
![screen shot 2016-03-08 at 10 39 14 am](https://cloud.githubusercontent.com/assets/11475316/13608450/747cfa46-e51a-11e5-8c4f-dc924b247bd9.png)
Here's after I click the Restrictions off, and then I was able to upload:
![screen shot 2016-03-08 at 10 39 53 am](https://cloud.githubusercontent.com/assets/11475316/13608473/88776ac2-e51a-11e5-8807-341c67d1d0e5.png)

**Comment by nconrad** [comment]
@ARWattam, this is really old, there were probably a number of changes since then, and I'm not able to replicate the issue.  Please reopen if it's still an issue?

![image](https://user-images.githubusercontent.com/1194246/34503685-6af18452-efdf-11e7-8dfe-5dae41ac8451.png)
