### ISSUE TITLE
protein family sorter anomaly

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#616]
If we select a tax level from the protein family sorter, say Hydrogenthermaceae it shows there are 7 genomes

<img width="929" alt="screen shot 2016-03-08 at 4 19 05 pm" src="https://cloud.githubusercontent.com/assets/2152226/13618404/886fab82-e549-11e5-8417-d404e38af955.png">

But if we go there, we see there are only 4 genomes

<img width="1297" alt="screen shot 2016-03-08 at 4 20 15 pm" src="https://cloud.githubusercontent.com/assets/2152226/13618441/ba4374a4-e549-11e5-8c04-6ed97b5eb836.png">

We can drill down to a real anomaly in Sulfurihydrogenibium sp. YO3AOP1. It has families

<img width="1295" alt="screen shot 2016-03-08 at 4 10 47 pm" src="https://cloud.githubusercontent.com/assets/2152226/13618248/bac5e23c-e548-11e5-993c-c0db88e28e3e.png">

and if you try looking at just that in the sorter you get an error that makes it look like it's missing somewhere or something:

<img width="1285" alt="screen shot 2016-03-08 at 4 16 12 pm" src="https://cloud.githubusercontent.com/assets/2152226/13618535/42d15ffc-e54a-11e5-90cb-63cec813ea26.png">

**Comment by mshukla1** [comment]
Out of 65,000 genomes, why would you pick on 7 Hydrogenthermaceae genomes?

**Comment by mshukla1** [comment]
Harry, I checked and seeing similar problems with taxon selector. I don't think it is data problem. 
I think it is time to redesign or retire the taxon selector panel!!
