### ISSUE TITLE
Filter to add to genome dropdown

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#617]
It'd be useful to have a "Complete genomes" checkbox by the "Public genomes" and "My Genomes" options in the genome dropdown widget, especially for the places where reference genomes are being chosen.

**Comment by mshukla1** [comment]
Additional checkboxes have been added in the genome selector widget. 

<img width="392" alt="screen shot 2017-09-17 at 12 38 55 pm" src="https://user-images.githubusercontent.com/1236463/30523327-3e3e7994-9ba5-11e7-97ce-4bcabd3a2ded.png">
