### ISSUE TITLE
Proteome comparison should have native excel download

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#619]
We should have an xls download from the proteome comparison tool

**Comment by chmao1** [comment]
@levinas Could you make table in xls available from the server side?

**Comment by chmao1** [comment]
Implemented and made a pull request

**Comment by chmao1** [comment]
The implementation is now available in production.

**Comment by mshukla1** [comment]
@chmao1 again, a minor thing. Can you please add the link to the excel file to the Download button at the top right on the job result page? That will make it more accessible to the users. For example, the download above the genome table includes link to both csv and excel. 

If it is difficult to have two links, I would recommend replacing current link from csv to excel file. 

<img width="263" alt="Screen Shot 2019-04-26 at 1 59 13 PM" src="https://user-images.githubusercontent.com/1236463/56830511-24fe3500-682c-11e9-9027-fffe41aa3d7f.png">
<img width="150" alt="Screen Shot 2019-04-26 at 2 02 15 PM" src="https://user-images.githubusercontent.com/1236463/56830512-24fe3500-682c-11e9-9330-cce5f654f40b.png">

**Comment by ARWattam** [comment]
I was going to mention the same thing.

**Comment by chmao1** [comment]
Added an option in the download menu. This will be available in the next build.
![image](https://user-images.githubusercontent.com/6361802/57164588-9c027300-6dc2-11e9-88b0-9801bb93a1f5.png)

**Comment by chmao1** [comment]
Fixed and available in production
