### ISSUE TITLE
IE - new genome data problem w/ collection date -  or just problem when displayed in workspace

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#62]
you should know the drill by now :-)
to reproduce
global search for PRJNA259658
click on the 1st genome listed.   Looking at the metadata on the Genome Summary page, the Collection Date field looks OK.
Add Genome to Workspace
and when you look at it in the workspace  in IE the Collection Date says NaN/NaN/aN
looking at the exact same genome in my workspace on Mac Safari or Chrome, the date looks fine.

(but as a side comment .... I was so hoping that in the new tables that I was going to be able to select a field and copy it .... alas, that seems not to be the case)

**Comment by hyoo** [comment]
I confirmed this happens on IE only (checked chrome on Windows). I think this is a javascript date parsing issue.

**Comment by dmachi** [comment]
Harry changed this to use a string.  Can you retest in IE and close if this is resolved please?

**Comment by hyoo** [comment]
I verified that this works on IE 11 (Win7)
