### ISSUE TITLE
Proteome comparison xls addition: conditional formatting

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#621]
We should have conditional formatting that colors the bi/uni cells colored black when they are empty.

Optionally we could color based on pct identy / evalue to match the circos picture. Rebecca said doing this with rules was too expensive, but if we are generating the excel we can hardcode the cell colors and not use a rule..

**Comment by hyoo** [comment]
@levinas @maovt I guess this issue was lost for a year. Any of you can double check whether this is already addressed? or still doable?

**Comment by chmao1** [comment]
This requires server side to generate xls file.

**Comment by chmao1** [comment]
Implemented and made a pull request

**Comment by chmao1** [comment]
The implementation is now available in production.

**Comment by mshukla1** [comment]
@chmao1 , The new excel file and conditional formatting does look beautiful.

One minor suggestion, given that the coloring is done based on the percent identity,
I think it will be more intuitive if conditional coloring is done on percent identity column,
Instead of directionality column.

**Comment by mshukla1** [comment]
<img width="1223" alt="Screen Shot 2019-04-26 at 1 43 48 PM" src="https://user-images.githubusercontent.com/1236463/56830103-13685d80-682b-11e9-8bea-c46cd5c03e59.png">

**Comment by ARWattam** [comment]
I personally think that it works well with the coloring in the bi vs uni directional.  I like it, and I worry that if you move the colors into the percent identity, it will make the numbers harder to interpret.  I would also color the blank cells ONLY in the bi and uni, and not all the way across.  I have found that when I put to much formatting into an excel file, it becomes very sluggish and unresponsive.  And I prefer black to grey, as I really like the blank cells to stand out.

**Comment by chmao1** [comment]
@olsonanl 
I added the black color to the empty cells in the bi and uni columns and made a pull request in git.

**Comment by chmao1** [comment]
Fixed and available in production
