### ISSUE TITLE
proteome comparison xls addition: feature links

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#622]
The feature ids should be hotlinked back to the patric site.

**Comment by hyoo** [comment]
@levinas @maovt I guess this issue was lost for a year. Any of you can double check whether this is already addressed? or still doable?

**Comment by chmao1** [comment]
Also see #621

**Comment by chmao1** [comment]
Implemented and made a pull request

**Comment by chmao1** [comment]
The implementation is now available in production.
