### ISSUE TITLE
genome selector in differential exp import couldn't find genome

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#624]
Trying to select "Brucella melitensis biovar Abortus 2308" but typing that into the search didn't have it show up.

<img width="742" alt="screen shot 2016-03-09 at 10 50 02 am" src="https://cloud.githubusercontent.com/assets/2152226/13643136/fa9aae78-e5e4-11e5-987f-e98c37e8c433.png">

**Comment by rkenyon** [comment]
Appears to be working correctly now.  Closing ticket.
