### ISSUE TITLE
differential import should initialize the genome name from the original job

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#625]
If we've run an RNAseq job and are processing differential import, that dialog should autofill with the reference genome we used in the RNAseq job

**Comment by mshukla1** [comment]
The reference genome name is an optional parameter, user can leave it blank. If the uploaded file is output of the RNA-seq service, or for that matter, contains gene identifiers that can be unambiguously mapped to a genome, the service will map them automatically. 

-Maulik
