### ISSUE TITLE
heatmap sort order wrong

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#626]
Heatmap needs to sort by position on contig, not on id. The current ID sorting is strictly alphabetic which is wrong with the difference in digit count in the peg number.

**Comment by mshukla1** [comment]
I believe you are referring to transcriptomics here. I have updated the subject line for clarity.

**Comment by olsonanl** [comment]
Ah, yes, that's precisely it. See attached. There doesn't appear to be a field that can be used to sort them along the contig.

![screen shot 2016-03-10 at 12 41 22 pm](https://cloud.githubusercontent.com/assets/2152226/13680276/7b7d4194-e6bd-11e5-80f8-2705b6978446.png)

**Comment by hyoo** [comment]
fixed and available on beta.

for example, 

https://www.beta.patricbrc.org/portal/portal/patric/TranscriptomicsGene?cType=taxon&cId=1763&dm=result&pk=&expId=318920&sampleId=&colId=&log_ratio=0&zscore=0
