### ISSUE TITLE
Login on Chrome / Mac doesn't display WORKSPACE: HOME>

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#63]
Chrome / Mac - when I 1st login, there is no WORKSPACE: HOME> on the blue bar, even when it says Welcome rwill1.   If I do a reload, WORKSPACE: HOME> shows up.

I tested a few other browsers / systems (not exhaustive?) and it doesn't seem to be a problem

**Comment by hyoo** [comment]
I think this is not related to may browser. This happens maybe due to the synchronization issue with authentication server and JBoss session. If you logout, sometimes, I still see WORKSPACE: HOME after several refresh and it is gone at some point.

**Comment by hyoo** [comment]
this is fixed.
