### ISSUE TITLE
selecting filters in genome list shouldn't clear selection

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#630]
Say you are creating a genome group and pick a few genomes in the genome list, then click "complete" to shift to complete genomes only. If you had genomes selected that remain in the list after the filter is enabled, the genomes are deselected. They should remain selected after the filter is added.

**Comment by hyoo** [comment]
currently filtering triggers a new scoping, which means, all the numbers in the facets are updated and entire grid is also re-populated. So, we cannot keep the selections.

**Comment by mshukla1** [comment]
This may lead to confusion. When user changes selection / filters, we can not anticipate whether user wanted to keep the previous selection or not. If we keep it in memory, user has no way to unselect it, without first saving the group. 

You can incrementally add genomes to the same genome group using different filters. It may require few more clicks and saves, but I believe it is much cleaner and less confusing mechanism. 

Closing the ticket with won't fix as I don't think this is critical issue.
