### ISSUE TITLE
Ordering of genome groups in protein family sorter

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#631]
The list of genome groups in the protein family sorter appears in apparently random order. These should be able to be sorted by name, creation date, number of genomes, etc.

**Comment by mshukla1** [comment]
It seems this has been addressed as the genome group selector now supports selection from group listing. 

<img width="830" alt="screen shot 2017-09-17 at 12 01 31 pm" src="https://user-images.githubusercontent.com/1236463/30523058-fac1781a-9b9f-11e7-9591-8b82ea5bae61.png">
<img width="409" alt="screen shot 2017-09-17 at 12 00 39 pm" src="https://user-images.githubusercontent.com/1236463/30523057-faae37f0-9b9f-11e7-8461-c8d60f2d29d0.png">
