### ISSUE TITLE
Example: How to create task list in git issues

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#633]
Here is an example of creating check lists in tickets and marking them as they get completed. 
- [x] Task 1
- [x] Task 2
- [x] Task 3
- [ ] ~~Task 4~~
- [ ] Task 5

**Comment by rkenyon** [comment]
Pretty cool.

On 3/15/16 1:51 PM, mshukla1 wrote:
>
>   * Task 1
>   * Task 2
>   * Task 3
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/PATRIC3/patric3_website/issues/633>Web Bug from 
> https://github.com/notifications/beacon/ADCnWio4b1rtv1GWr5nUT8_A0GuwqIEiks5ptvG6gaJpZM4HxR-I.gif
>

-- 
Ron Kenyon
PATRIC Project Manager, patricbrc.org
Project Director, Virginia Bioinformatics Institute
Virginia Tech
rkenyon@vbi.vt.edu

**Comment by hyoo** [comment]
<img width="1080" alt="progress_bar" src="https://cloud.githubusercontent.com/assets/1236467/13997702/54a2fdcc-f101-11e5-816d-0868b33a3e7e.png">

another beauty of task list.
