### ISSUE TITLE
AMR Curation - enable user submission of metadata

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#636]
AMR Curation (Option 1) 
After establishing protocols for PATRIC-internal metadata standards, we will build tools that allow PATRIC users to submit their metadata using the same standards. This task will require manual curation of incoming data sets accompanied by the establishment of standards. Tools will be built that will replace the manual curation algorithms and feed the data in the appropriately formatted database.

**Comment by rkenyon** [comment]
3/16: For now, we will make a clean Excel template for AMR panel and genome metadata capture, with instructions, available for download from the website.  If filled in correctly, this will be able to be directly loaded (by us) into the PATRIC database.

**Comment by rkenyon** [comment]
3/28: Ron work on metadata submission form.

**Comment by rkenyon** [comment]
3/30: Chunhong and Ron reviewed the NCBI Antibiogram () and decided it was better to simply link to that page and information rather than create our own template, especially since most antibiogram data we will be getting will come from NCBI.

**Comment by mshukla1** [comment]
Closing this as an issue is fine. But we will need to allow users to upload 
genome metadata and amr data for their private genomes. 

This is something Neal will be working on next.
