### ISSUE TITLE
Proteome Comparison Service Enhancements

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#637]
These enhancements to the Proteomics Comparison Service include
- Enabling inclusion of reference genome
- Enabling inclusion of user-supplied genome
- Enabling generation of comparison based on user-selected feature set

**Comment by rkenyon** [comment]
3/28: Fangfang supposed to have worked on this past weekend (3/26-27)

**Comment by rkenyon** [comment]
3/30: Chunhong testing on Beta using her own build.  Noticed some issues - when using FASTA, the image is not rendered correctly.  When feature group is used as reference, the size of the circle seems wrong.  Link to PATRIC features needs to go to current PATRIC website.

**Comment by levinas** [comment]
It would be good if I could get the incorrect images from @maovt .

**Comment by maovt** [comment]
This is the image from fasta as reference

**Comment by levinas** [comment]
I'm not getting the image. Please send me a direct email.

**Comment by maovt** [comment]
This is the image I got from testing feature group as a reference.

**Comment by levinas** [comment]
@maovt  I can't see attachments sent via github.

**Comment by maovt** [comment]
I'll email you. 

Chunhong

**Comment by levinas** [comment]
3/30: Created pull request to update the backend after sync'ing with Chunhong:
https://github.com/olsonanl/app_service/pull/28

**Comment by olsonanl** [comment]
Merged & deployed.

**Comment by maovt** [comment]
The client side has been deployed on beta and is ready for testing at beta.patricbrc.org. 

Also, I fixed the genomes in reverse order problem.

**Comment by levinas** [comment]
Cool. Things look good in my tests.

**Comment by rkenyon** [comment]
Dustin has pushed to beta.  Can we verify and push to production for the 
release?

Ron

On 3/30/16 10:17 PM, Fangfang Xia wrote:
> Cool. Things look good in my tests.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/PATRIC3/patric3_website/issues/637#issuecomment-203718727>Web 
> Bug from 
> https://github.com/notifications/beacon/ADCnWvwrKrTZYLV60HF5t5943ljv8k3zks5pyy6-gaJpZM4HzGW_.gif
>

-- 
Ron Kenyon
PATRIC Project Manager, patricbrc.org
Project Director, Virginia Bioinformatics Institute
Virginia Tech
rkenyon@vbi.vt.edu

**Comment by levinas** [comment]
My tests on beta passed.

**Comment by maovt** [comment]
My tests look good as well.

**Comment by levinas** [comment]
This can be closed.
