### ISSUE TITLE
Metabolic Model for human macrophage cells

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#638]
Host-­‐Pathogen Response (Option 3) 
We will add a human cell metabolic model for macrophage cells to the metabolic modeling service (based on the Human Recon project). In this release, we will also provide global predictions at the cellular level on what the organism is doing metabolically in the context of antibiotic resistance (e.g., excreting ethanol and utilizing fructose).

**Comment by mshukla1** [comment]
Obsolete. closing the ticket.
