### ISSUE TITLE
Metabolic Modeling Service - visualizer and editing

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#639]
Metabolic Model Service 
Enhancements to the metabolic modeling service in this release include upgrades to visualizations. We will provide users visual representation of a metabolic model and the ability to edit the model by adding or deleting reactions on models that exist in a workspace where they have permissions to edit the model. We will also complete full integration of metabolic models into the underlying SOLR database and provide the user to view a model on KEGG maps and in standard PATRIC tabular displays.

**Comment by mshukla1** [comment]
Obsolete. Closing the ticket.
