### ISSUE TITLE
Metagenome Abundance Service

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#643]
Metagenomics Abundance Service 
We will create a more effective metagenomics capability in PATRIC that takes us beyond the current capabilities. Currently, a user can link out to the MG-RAST site for metagenome annotations in the form of functional and taxonomic abundance profiles. Going forward, we will enable users to upload a sample or a set of samples into a subdirectory in their workspace. We will internalize the computations of functional and taxonomic abundance profiles by creating a metagenomics abundance service. We will add the ability to compute a distance matrix summary from a set of samples. The service will compute a distance matrix summarizing the pairwise distances between samples using crAss. Similarly, given a set of samples, the service will compute a set of annotated clonal populations and provide an estimate of the community metabolic capacity from associated metabolic models.

**Comment by rkenyon** [comment]
01/26/16: No progress on this task.  De-prioritize for now and instead focus on Tn-seq data.

**Comment by mshukla1** [comment]
This is a major deliverable, should be tracked as part of release tasks and priorities and not as a github ticket. Hence, removing it from here. 

Metagenomics is scheduled for release in March 2018. 

-Maulik
