### ISSUE TITLE
Integrate Tn-seq data into PATRIC - Requirements / Use Cases / Plans

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#644]
Based on trends in research, data types coming from NIAD-funded centers, and input from NIAID program, we need to have a plan for dealing with Tn-seq data in PATRIC.  Below are some initial thoughts on what we could do:
- Deploy a Tn-­seq Upload Service that would take advantage of the PATRIC expression data infrastructure by supporting upload of tab-­delimited summary form of Tn-­seq data with metadata and counts and viewing the results of this tool in a heatmap view.
- In parallel, or perhaps downstream, we could support alignment/wig/bigwig forms of the data as we have seen with FLUTE using streaming to the genome browser, which is essentially what Tom Ioerger has suggested.

**Comment by mshukla1** [comment]
We have released Tn-seq service and data is streamed to genome browser. I believe this task is complete now. 

-Maulik
