### ISSUE TITLE
Integrate workspace (i) help into WordPress User Guides

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#645]
The pop-up help that appears when the <(i)> is clicked in the workspace is contained in simple html files.  There should be some way to render this information in WordPress on the fly or at least link to those pages from WordPress User Guides so that we don't have redundant help documentation.

Here are some examples of these files:

https://www.patricbrc.org/js/p3/widget/app/help/GenomeAssemblyHelp.html
https://www.patricbrc.org/js/p3/widget/app/help/GenomeAnnotationHelp.html
https://www.patricbrc.org/js/p3/widget/app/help/DifferentialExpressionHelp.html
https://www.patricbrc.org/js/p3/widget/app/help/GenomeAnnotationHelp.html
https://www.patricbrc.org/js/p3/widget/app/help/GenomeAssemblyHelp.html
https://www.patricbrc.org/js/p3/widget/app/help/GenomeComparisonHelp.html
https://www.patricbrc.org/js/p3/widget/app/help/ModelReconstructionHelp.html
https://www.patricbrc.org/js/p3/widget/app/help/RNASeqHelp.html

All available in Git from here: 
https://github.com/PATRIC3/p3_web/tree/master/public/js/p3/widget/app/help

**Comment by dawenx** [comment]
It looks like this issue is not relevant any more: help information is shown in the ItemDetailPanel (the rightest panel) now. Will close it if nobody objects.

**Comment by dawenx** [comment]
this is part of static content management now. all in-line help for services had been moved to p3_docs by harry and me and they are currently on alpha. suggest to close this ticket.

**Comment by mshukla1** [comment]
@hyoo can we close this?

**Comment by hyoo** [comment]
this is on production now.
