### ISSUE TITLE
Can't read full genome name in selector in variation

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#647]
The genome names overflow the dropdown so one cannot doublecheck the genome id. 
![screen shot 2016-03-30 at 12 46 11 pm](https://cloud.githubusercontent.com/assets/2152226/14151843/8ae0268e-f675-11e5-85f7-98733e77da08.png)

**Comment by dawenx** [comment]
![long_name_read_variation_service](https://user-images.githubusercontent.com/26723038/30453931-906a7dec-9968-11e7-978e-d9c4a0079df0.png)

**Comment by dawenx** [comment]
this drop down menu uses WorkspaceObjectSelector which was improved over the time. when i checked variation analysis service today (09/14/2017), i was able to see a long READ file name after i clicked on the triangle next to folder icon. i would say i cannot reproduce the issue. i suggest to close this issue (in a week) unless I hear objection from someone.

**Comment by mshukla1** [comment]
Agree. Seems it has been fixed. Closing the ticket.
<img width="644" alt="screen shot 2017-09-17 at 12 08 17 pm" src="https://user-images.githubusercontent.com/1236463/30523115-086e70f2-9ba1-11e7-97bc-56135d353226.png">
