### ISSUE TITLE
Yet another genome that has both RefSeq and PATRIC annotation, but the mapping does not appear on the RefSeq page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#649]
The RefSeq page:
![screen shot 2016-03-31 at 9 23 59 am](https://cloud.githubusercontent.com/assets/11475316/14177646/449f34f2-f725-11e5-8f7f-227d4f2e5e98.png)

The genome browser, showing the presence of the PATRIC gene:
![screen shot 2016-03-31 at 9 22 53 am](https://cloud.githubusercontent.com/assets/11475316/14177661/57191954-f725-11e5-9152-3da5ed67dbd4.png)

The PATRIC landing page, showing the RefSeq gene:
![screen shot 2016-03-31 at 9 46 22 am](https://cloud.githubusercontent.com/assets/11475316/14177698/809ee290-f725-11e5-8247-f4e52fc2d392.png)

Remember that 99.9% of users will come into PATRIC with different locus tags than the pegs.  We really need to get this right.

**Comment by mshukla1** [comment]
This issue seems to be resolved with the new website and the updated data. 

<img width="497" alt="screen shot 2019-02-20 at 12 56 05 pm" src="https://user-images.githubusercontent.com/1236463/53116748-fd7aab80-350e-11e9-9918-3649b44058a3.png">
