### ISSUE TITLE
Once logged in, website insists on my logging in again

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#65]
I am trying to create a genome group.  It asked me to log in, which I did successfully, and then when I tried to create the group again, it asked me to login again.

http://www.beta.patricbrc.org/portal/portal/patric/GenomeList?cType=taxon&cId=2&dataSource=&displayMode=&pk=&kw=#aP0=1&aP1=1&aT=0&key=1426863620043&cwG=false&tId=2&gName=&kW=Escherichia

**Comment by hyoo** [comment]
I think this is related #63. Time delay between Authentication server and JBoss session.

**Comment by hyoo** [comment]
fixed
