### ISSUE TITLE
Filter malfunctioning on genome list

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#650]
I was looking at Acinetobacter baumannii and saw that there were 134 total genomes:
![screen shot 2016-03-31 at 10 13 19 am](https://cloud.githubusercontent.com/assets/11475316/14178652/92ddaa0a-f729-11e5-80ac-816ff674c46b.png)
 Under Disease, there is a really weird top entry of (35):
![screen shot 2016-03-31 at 10 14 06 am](https://cloud.githubusercontent.com/assets/11475316/14178685/bbb726f4-f729-11e5-8d87-475064b31903.png)
When I click on it, nothing happens except that the page seems to reload.   Not sure what this is doing here, but the its unfortunate that it is at the top of the filter list for Disease.  When I click on anything else in Disease, the filtering seems to work.

**Comment by hyoo** [comment]
metadata problem.
