### ISSUE TITLE
job output window problem

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#651]
I was having trouble scrolling the job output window (safari in mac) and managed to slide it so that the title bar of the output window was out of view:

![screen shot 2016-04-01 at 8 50 01 am](https://cloud.githubusercontent.com/assets/2152226/14208798/c22386be-f7e6-11e5-9338-34d53f0813f2.png)

Hitting escape doesn't clear the window so I had to reload the page.

**Comment by hyoo** [comment]
This is specific to outdated website.

![image](https://cloud.githubusercontent.com/assets/1236467/25974290/de57c220-366d-11e7-879e-d018ff8d1d12.png)
