### ISSUE TITLE
Uh oh...I broke PATRIC

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#655]
I tried to do something new.  From Protein Family Sorter I selected FIGFams and then filtered on Imperfect families.  Then I tried to resize the table to see them all, and it killed every tab of PATRIC I had open.
![screen shot 2016-04-14 at 11 52 10 am](https://cloud.githubusercontent.com/assets/11475316/14534515/861e13d6-0237-11e6-900a-d7442ee44405.png)

**Comment by hyoo** [comment]
This means your browser is crashed. Maybe you opened too many tabs or opened tabs for long time (possible memory leak). This does no harm on site.

Harry

On Apr 14, 2016, at 10:53 AM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried to do something new. From Protein Family Sorter I selected FIGFams and then filtered on Imperfect families. Then I tried to resize the table to see them all, and it killed every tab of PATRIC I had open.
[screen shot 2016-04-14 at 11 52 10 am]<https://cloud.githubusercontent.com/assets/11475316/14534515/861e13d6-0237-11e6-900a-d7442ee44405.png>
