### ISSUE TITLE
Disconnect between experiments I can see at GEO and what appears on the PATRIC page.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#657]
I"m wondering why there is such a huge difference (or should I say "yuge" between what I see at GEO for Brucella, and what appears in PATRIC.  At GEO it says there are 547 datasets.  PATRIC says 45.
Here's GEO
![screen shot 2016-04-18 at 9 11 29 am](https://cloud.githubusercontent.com/assets/11475316/14605275/e66b3c4e-0545-11e6-97cf-1388f1fb0273.png)

And here's PATRIC
![screen shot 2016-04-18 at 9 11 44 am](https://cloud.githubusercontent.com/assets/11475316/14605285/f17fd55e-0545-11e6-9e05-404af7cf6382.png)

**Comment by mshukla1** [comment]
I just compared the records at NCBI and PATRIC for Brucella, and the numbers match as intended.

We summarize results from two different queries: 

1. By taxonomy, which gives experiments where Brucella is the sample organism. 
http://www.ncbi.nlm.nih.gov/gds/?term=txid234[Organism:exp]

2. By keyword, which will find all the experiments that match word Brucella, i.e. will also include all the Brucella host response datasets 

We add the number of platforms+series+datasets, which matches with what is at NCBI.

<img width="373" alt="screen shot 2016-04-27 at 10 44 45 am" src="https://cloud.githubusercontent.com/assets/1236463/14858479/de40898a-0c65-11e6-93f3-0650f39b4479.png">

<img width="535" alt="screen shot 2016-04-27 at 10 54 41 am" src="https://cloud.githubusercontent.com/assets/1236463/14858664/86ad9f9a-0c66-11e6-98ab-8fc7b931a67b.png">

<img width="525" alt="screen shot 2016-04-27 at 10 54 55 am" src="https://cloud.githubusercontent.com/assets/1236463/14858666/8a0689ae-0c66-11e6-9b48-5131e6e23d1b.png">
