### ISSUE TITLE
Comparative Pathway Viewer not loading genome groups

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#659]
Very frustrating.  Here is a screenshot of the error code I got:
![screen shot 2016-05-25 at 11 24 32 am](https://cloud.githubusercontent.com/assets/11475316/15545800/a26e47f0-226b-11e6-8716-df31a690bc18.png)

**Comment by hyoo** [comment]
#666 Duplicates?

**Comment by hyoo** [comment]
this works on beta now.
