### ISSUE TITLE
Have to re-enter keyword in filter when picking something else in metadata

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#66]
>All bacteria
>Genome List
>Filter on Resistant
>Enter Esherichia into key word filter and hit return
>Create group (after being asked to login twice)
>Change metadata filter to Susceptible

The table does not show Escherichia at this point, but all data even though its filtered on Escherichia.  As the word is still in the text box, I hit return, and it gives a list starting with Streptococcus.  To get Escherichia, I have to clear the text box, and then re-enter Escherichia, and then hit return.

http://www.beta.patricbrc.org/portal/portal/patric/GenomeList?cType=taxon&cId=2&dataSource=&displayMode=&pk=&kw=#aP0=1&aP1=1&aT=0&key=1426863923185&cwG=false&tId=2&gName=&kW=Escherichia

**Comment by hyoo** [comment]
In your example, Escherichia was misspelled. (missing c between Es and h). 

For some reason, (maybe related to your login situation), the keyword is stored in kW variable in url, but not in kw, which means, Escherichia keyword is typed in the keyword box, but not actually reflected in your search.

**Comment by mshukla1** [comment]
I tried to do this again and it seems to be working. I entered keyword, filtered on resistant, added to group, then filtered on susceptible and few other things, and it kept the keyword scope.

**Comment by ARWattam** [comment]
Tried on both Firefox and Chrome.  Problem appears to be resolved
