### ISSUE TITLE
"Isolation country" should be cleaned up.

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#660]
If you look under all bacteria at the isolation countries it is contaminated with geographic locations like "Canada: Eastern Canada", "Africa", "Louisiana", "Pacific Ocean", etc.

There are countries that are listed twice like Zimbabwe and Simbabwe
There is an empty field with 102 organisms, 
There is "Antarctica" and " Antarctica" etc.

**Comment by chmao1** [comment]
This is fixed and available in beta.

**Comment by chmao1** [comment]
@jimdavis1 please verify. Thanks.

**Comment by hyoo** [comment]
verified.
