### ISSUE TITLE
Not a big deal, but super annoying

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#661]
If you are on the organisms page and need to click "more" in order to select more than one of the not shown check boxes, it always reloads the page and closes the "more" list, so then you have to click "more" again, select the next check box, the list reloads and you have to click "more" and then select the next check box, wait for the list to reload and click more..... .... ....

![screen shot 2016-06-01 at 7 46 17 am](https://cloud.githubusercontent.com/assets/7661533/15709911/fa473ee4-27cc-11e6-9ada-b0359e2da6d9.png)

**Comment by hyoo** [comment]
no more issue on current production.
