### ISSUE TITLE
Can't download metadata

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#662]
I agree that you don't want to give somebody an excel file with 69K entries, but the flat text file should still be made available for download.

![screen shot 2016-06-01 at 7 53 26 am](https://cloud.githubusercontent.com/assets/7661533/15710102/195f7dfe-27ce-11e6-90fe-291ed0a2e345.png)

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/30171580-04646534-93b8-11e7-9703-029f0557bd32.png)

1. this is on old website
2. we support downloading metadata up to 25k genomes at a time.

@jimdavis1  please repoen or issue a new ticket if you think we need to increase this size or anything else you like related to this.
