### ISSUE TITLE
Clicking a checkbox in "Isolation country" artificially limits the number of possible checkboxes

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#663]
If you click on any isolation country, and then click "more", all of the countries with less than 17 genomes disappear.  For instance it is impossible to select the genomes from  Russia and Soviet Union.

![screen shot 2016-06-01 at 8 08 47 am](https://cloud.githubusercontent.com/assets/7661533/15710565/370e2f7e-27d0-11e6-949d-9c8cc5521b2b.png)

**Comment by hyoo** [comment]
This is specific to outdated website.
