### ISSUE TITLE
Why is the RefSeq locus tag missing from the annotation box?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#665]
Its in the accession summary box above....
![screen shot 2016-06-06 at 9 53 56 am](https://cloud.githubusercontent.com/assets/11475316/15824329/af56d30a-2bcc-11e6-8882-a3ba23f855f9.png)

**Comment by mshukla1** [comment]
This is very old ticket based on the old jboss website. The gene page has been redesigned the issue is no longer there. 

<img width="428" alt="screen shot 2017-09-14 at 9 02 09 pm" src="https://user-images.githubusercontent.com/1236463/30463243-1e18c050-9990-11e7-8247-c698523bd859.png">
