### ISSUE TITLE
New genome groups not showing up in Protein Family Sorter-need this to work before ASM workshop

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#666]
I have created some new groups, and can see them in my workspace, but when I look for them in the PFS, they are not there.  They aren't in the Comparative Pathway tool either.  I need this to be functional before the ASM Microbe workshop.

**Comment by hyoo** [comment]
I cannot reproduce this issue. I can see my test genome group (created to test save as genome group from pathway tab). it took some time though.

**Comment by hyoo** [comment]
I guess this issue no longer exists.
