### ISSUE TITLE
Typo in Comparative Pathway Tool results page

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#669]
To learn how to filer, sort, manipulate, refine, and save data within PATRIC feature tables,
"filer" should be "filter."

**Comment by hyoo** [comment]
Well, this is somewhat systematically spread. I have fixed four different places and will deploy soon.

https://github.com/PATRIC3/patric3_website/commit/c13a9e38b763fd1b004b5001ad7aeff08243a4e5

**Comment by hyoo** [comment]
available on production now.
