### ISSUE TITLE
Need to make MLST display like users are anticipating

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#670]
For example, "MLST.Escherichia_coli_1.457" should display like "ST-457", as users are used to seeing, instead of the long concatenated string.

https://www.patricbrc.org/portal/portal/patric/Genome?cType=genome&cId=562.10576

**Comment by mshukla1** [comment]
Our naming scheme is slight deviation from the simple naming, i.e. ST-XXXX, but it is necessary as it helps us address the following issues without having the need to have multiple fields to capture all MLST related information, which would be even more confusing for the users. 

All of the MLST databases used in PATRIC come from PubMLST. There are multiple MLST databases / typing schemes for some of the pathogens, each using different set of genes for typing as shown below. The database names we use come straight PubMLST, which includes pathogen name + typing scheme number. The prefix MLST was added intentionally to make it easier to search for genomes with MLST assignments. 

Acinetobacter_baumannii_1
Acinetobacter_baumannii_2
Escherichia_coli_1
Escherichia_coli_2
Leptospira_spp
Leptospira_spp_2
Leptospira_spp_3
Pasteurella_multocida_1
Pasteurella_multocida_2
Streptococcus_thermophilus
Streptococcus_thermophilus_2
Vibrio_cholerae
Vibrio_cholerae_2
