### ISSUE TITLE
Genome Overview: display SRA accession

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#672]
Display SRA accession on the genome overview page and link it to the SRA page at NCBI

Sample link: 

http://www.ncbi.nlm.nih.gov/sra/?term=ERR551435

**Comment by hyoo** [comment]
will be available on alpha soon.

**Comment by hyoo** [comment]
this is a way old ticket already addressed.

**Comment by mshukla1** [comment]
verified on beta.
