### ISSUE TITLE
Alpha PF clustering (Payload too large)

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#673]
When trying to cluster PF on the heatmap for https://www.alpha.patricbrc.org/view/Taxonomy/1485#view_tab=proteinFamilies

I get a: POST https://www.alpha.patricbrc.org/api/ 413 (Payload Too Large)

Dustin says the current limit is 10Mb for the POST. I suppose we've gone back and forth with making this clustering client side?

**Comment by aswarren** [comment]
I created a milestone p3_web-3.2.x since Dustin wanted to represent it as a tag. Not sure whether it should be a label OR milestone. We can edit the designation going forward.

**Comment by hyoo** [comment]
Dustin, can we change it to 30mb? 30mb will take care most of cases, since we set 500 as max.

**Comment by dmachi** [comment]
I've updated this on alpha.  Can you please test and see if it resolves the problem?

**Comment by hyoo** [comment]
well, it failed due to the timeout (10min) so I increased the limit to 20min in jsonrpc.js but failed again at 15.5 min. So somewhere in nginx config is limiting. Would you take a look?

**Comment by dmachi** [comment]
I’ve increased this to 30 mins in nginx, but it is still not long enough.  Cluster for this (487 Clostridium genomes), is currently still running after 40 minutes.  I am going to continue to let it run so I can see if I can catch how long it ends up taking, but we need to figure out some other way to do this.  Nobody is going to wait on that screen for 40 minutes and the p3_api server (machine)  isn’t really setup to handle long cpu intensive jobs like this.

**Comment by hyoo** [comment]
I have added a checking routine in order to inform users when the data size is too large. Clustering works approximately <100 genomes x <8,000 families in 10mins.

**Comment by mshukla1** [comment]
Fixed, verified on alpha.
