### ISSUE TITLE
Data API returns erroneous FNA

### ISSUE THREAD

**Issue by levinas** [PATRIC3/patric3_website#674]
The data API for FNA is missing one base every 60 characters. Please see the comparison example below. The bases on the red line are the delta between the two. This bug may be contributing to the "too distant" issue in the variation service. @dmachi 

`$ curl -s ftp://ftp.patricbrc.org/patric2/patric3/genomes/520466.3/520466.3.fna |grep NZ_EQ999587 -A 5`

<img width="625" alt="fna-bug" src="https://cloud.githubusercontent.com/assets/1056733/17073171/e260f902-5033-11e6-8345-59d3c79fa465.png">

`$ curl -s -H "Content-Type: multipart/form-data" "https://www.patricbrc.org/api/genome_sequence/?eq(genome_id,520466.3)&http_accept=application/dna+fasta&limit(1)" |head -n 6`

```
>accn|NZ_EQ999587   Brucella melitensis bv. 3 str. Ether genomic scaffold supercont1.2, whole genome shotgun sequence.   [Brucella melitensis bv. 3 str. Ether | 520466.3]
gaattcttccgggatggtgaggccgaagaagccaagctccttcatctgcgcaatgatatc
gccggaatggcgtttgtttcggcgacttcgttctccctggggatgagcgtttccgaaacg
actggttgacagtgtcgcgcagaatttcaagtgtttccgggtcgcggatcatgcattctc
tagcggccgttgccggccttttctgcaaggctccgctttccggcagattacgggacagcg
agctgatgttgtgaaccatctcgatcaggcgggggccgatatcgtcctccagcttctcgc
```

**Comment by dmachi** [comment]
I've fixed this and deployed to the alpha api instance.  Can you see if it works better for you there now.  If so, I'll push to production soon.
