### ISSUE TITLE
Clicking twice on genome group doesn't work consistently.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#68]
I double click on the group I want, and it reshuffles to alphabetize the group list.  I'm not sure how many clicks it takes to open the group, but there seems to be a lack in consistency.

http://www.beta.patricbrc.org/workspace/ARWattam@patricbrc.org/home/Genome%20Groups

**Comment by dmachi** [comment]
I'm still trying to understand the reshuffling portion (Rebecca demonstrated for me on friday).  However, I have made some changes to address the click vs dblclick issue that Rebecca and Chunhong demonstrated.  Now you can single click a row's type icon OR dbl click anywhere in a row to drill down.
