### ISSUE TITLE
Safari Heatmap not loading

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#680]
The heatmap isn't working in Safari

**Comment by hyoo** [comment]
This may be because Safari blocked flash player.

https://helpx.adobe.com/flash-player/kb/enabling-flash-player-safari.html

**Comment by hyoo** [comment]
It did not work for me initially, but after installing the most updated flash player and enabling flash player in the safari preferences, heatmap starts working.

**Comment by hyoo** [comment]
need to display message. will work on

**Comment by hyoo** [comment]
we're displaying a message how to enable flash player. This will be a temporary solution until we reimplement the heatmap viewer with standard technology.
