### ISSUE TITLE
The number of genomes retrieved from the pie charts on Genome Overview page shows different count on the pie chart

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#682]
For example, this pie chart shows 28 genomes for Diarrhea, but it retrieves 114 genome after clicking on the pie.
<img width="342" alt="screen shot 2016-07-26 at 10 11 22 am" src="https://cloud.githubusercontent.com/assets/6361802/17141887/f1390308-531b-11e6-9013-29b873e8b5b3.png">

**Comment by mshukla1** [comment]
Chunhong, can you please check if you still see this problem? If so, can you provide more details / url to reproduce it? 

-Maulik

**Comment by maovt** [comment]
This is still a problem. Here is the example: From organisms list, choose Bartonella, go to Genomes tab, select all genomes (83) from the list. Click on the "GENOMES" icon on the green bar. It'll show you the genome list view from the 83 genomes. Go to the Overview tab, choose Peru from the pie chart (13 genome on the pie chart). The resulting genome list shows 189 genomes.
![genome_view](https://cloud.githubusercontent.com/assets/6361802/17942732/a02b7ff2-6a06-11e6-9260-c028a700fed7.png)
![genome_lis](https://cloud.githubusercontent.com/assets/6361802/17942737/a37df8ba-6a06-11e6-9da4-93e6f55ddb6c.png)

**Comment by hyoo** [comment]
fixed and deployed on beta.
