### ISSUE TITLE
Taxon view: change tab names

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#683]
"Sequences" and "Features" are too generic and can be confusing to users. 

Change the tab names as follows: 

Sequences => Genome Sequences

Features => Genomic Features / Genome Features

-Maulik

**Comment by dmachi** [comment]
If I do this, the tabs won't fit in a 1024 width screen without wrapping.  I'd prefer not to do this.  Instead I propose using mouseovers on the tabs to avoid this.  We can discuss.

**Comment by hyoo** [comment]
I have copied mouseover contents from the current production, but it obviously requires revision because we are no longer limited to the taxon level.

**Comment by dmachi** [comment]
I updated the mouseovers with more generic content and added in the missing tabs.
