### ISSUE TITLE
From the table view  of Genome Metadata Top 5 of the Genome Overview page, the links to genomes don't work

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#684]
Nothing happens when clicking the links in the table.
<img width="1118" alt="screen shot 2016-07-26 at 10 19 14 am" src="https://cloud.githubusercontent.com/assets/6361802/17142143/0b57dc36-531d-11e6-98ed-381ac7276ee4.png">

**Comment by dmachi** [comment]
These seem to be working for me.  I'm not sure if they were fixed by someone else today or what.

**Comment by hyoo** [comment]
This works for me except the "See all genomes with xxx". Most of times, it works, but sometimes it adds a few more genomes, and I guess that is due to the empty string, which is counted in * query but omitted in the count.
