### ISSUE TITLE
MSA returns incomplete view when no alignment exists

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#685]
3.1.118alpha
Needs something more informative
![screen shot 2016-07-26 at 9 38 36 am](https://cloud.githubusercontent.com/assets/3188570/17142207/e140a6f6-5314-11e6-85be-d64258037116.png)

**Comment by aswarren** [comment]
This example https://www.alpha.patricbrc.org/view/MSA/?in(feature_id,(PATRIC.1313.4582.ERS022057.6972_2_3.1.CDS.28057.28578.fwd,PATRIC.1313.4582.ERS022057.6972_2_3.1.CDS.43375.44181.fwd,PATRIC.1313.4582.ERS022057.6972_2_3.1.CDS.35015.35974.rev,PATRIC.1313.4582.ERS022057.6972_2_3.1.CDS.47588.48595.rev))

Is coming up now in MSA. Trying to find an example that doesn't work.
