### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#686]
bullets in boxes at the top are not all linked, for example:

- Genomes
- Genomic Features
- Protein Families
- Transcriptomics Experiments

**Comment by mshukla1** [comment]
I am not sure this referred to the top navigation bar or the flow chart we had in the redesigned home page. 

Anyways
- the links from the data menu in the top navigation bar are working now
- we decided not to redesign the home page for now, so it is very similar to what we have on production site. 

I am closing the ticket. 

-Maulik
