### ISSUE TITLE
Genomic Features vs. Genome Features

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#702]
Click Genomic Features and get Genome Features

<img width="540" alt="screen shot 2016-07-26 at 9 52 01 am" src="https://cloud.githubusercontent.com/assets/8005288/17142730/d67a1e80-5316-11e6-89c1-9d12fa557978.png">

**Comment by hyoo** [comment]
I think we should go with features tab only or remove this page from the top menu. It doesn't make sense to display all genome features.

**Comment by hyoo** [comment]
```
$ grep -r "Genome Features" *
widget/templates/GlobalSearch.html:						<option value="genome_features">Genome Features</option>
widget/viewer/_FeatureList.js:			this.totalCountNode.innerHTML = " ( " + newVal + " Genome Features ) ";
```

fix two places.

**Comment by hyoo** [comment]
https://github.com/hyoo/p3_web/commit/a0bca24e9d2762230acb1bfe76a330b20aa7a931
