### ISSUE TITLE
Taxon overview: make the reference genome list little longer

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#703]
It seems we have more vertical space available in the left panel to make the reference genome list longer. Please make it long enough to display top 10 rows, to avoid scrolling in most cases. 

-Maulik

<img width="1430" alt="screen shot 2016-07-26 at 9 53 21 am" src="https://cloud.githubusercontent.com/assets/1236463/17142727/d2eb77c8-5316-11e6-9fc4-c3632fb444bc.png">

**Comment by hyoo** [comment]
fixed and will be available on alpha soon
