### ISSUE TITLE
Speciality Genes page blank

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#704]
Blank

<img width="515" alt="screen shot 2016-07-26 at 9 54 16 am" src="https://cloud.githubusercontent.com/assets/8005288/17142770/f6b9bd18-5316-11e6-9647-34e80f9506cd.png">

**Comment by dmachi** [comment]
I'm not sure if harry plans to have an overview here or whether we'll just have the list

**Comment by hyoo** [comment]
let's just go with the list as we do in transcriptomics experiments.
