### ISSUE TITLE
Campylobacter vs. Camplyobacter on menu bar

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#706]
<img width="515" alt="screen shot 2016-07-26 at 9 54 16 am" src="https://cloud.githubusercontent.com/assets/8005288/17142846/2fe2eae2-5317-11e6-896f-632fc31f2991.png">

**Comment by edietrich** [comment]
<img width="918" alt="screen shot 2016-07-26 at 9 55 39 am" src="https://cloud.githubusercontent.com/assets/8005288/17142902/535d4242-5317-11e6-9598-6843efb72f01.png">

**Comment by dmachi** [comment]
Fixed
