### ISSUE TITLE
Apply Filter issue: After removing filter selections, and clicking on the Apply filter button, the top query summary does not update

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#707]
See the example below, after removing "Human, Homo sapiens" AND  "Complete" and clicking APPLY button, the query in the green box did not change.

<img width="1214" alt="screen shot 2016-07-26 at 10 33 57 am" src="https://cloud.githubusercontent.com/assets/6361802/17142805/72836bc6-531f-11e6-9a8d-9678bd43f9c5.png">

**Comment by dmachi** [comment]
This is the correct behavior, except that the apply button should not be clickable.
