### ISSUE TITLE
All bacteria - graphic runs into right text

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#712]
<img width="1430" alt="screen shot 2016-07-26 at 9 58 43 am" src="https://cloud.githubusercontent.com/assets/8005288/17143045/c8b4d3ac-5317-11e6-8430-17b3f021f5d7.png">

**Comment by hyoo** [comment]
This is due to the fact that AMR bar chart does not resize when the browser does. will work on it.

**Comment by hyoo** [comment]
fixed and will be available on alpha soon.
