### ISSUE TITLE
The tabs are no longer clickable after clicking on the pie chart of the Overview page

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#716]
From the Genome Overview page, clicking on the pie chart to show genome list. The page stays on the genome list page, other tabs are not clickable. Also the number of the genomes is not correct for the Genome list.
<img width="1265" alt="screen shot 2016-07-26 at 10 45 35 am" src="https://cloud.githubusercontent.com/assets/6361802/17143236/b9534d54-5320-11e6-9ce9-c70749e482fa.png">

**Comment by chmao1** [comment]
This is fixed.
