### ISSUE TITLE
Genome metadata missing from workspace download

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#72]
Most of the traditional metadata fields are missing from the genome download from the workspace.

**Comment by hyoo** [comment]
need to match column order with feature/genome list defined in https://github.com/cidvbi/patric3_website/blob/master/portal/patric-libs/src/edu/vt/vbi/patric/common/DownloadHelper.java

**Comment by dmachi** [comment]
Updated Columns and Column order
