### ISSUE TITLE
Links vs. no links

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#722]
Very hard to distinguish that you can use "Explore" link but "Analyze" isn't a link

<img width="960" alt="screen shot 2016-07-26 at 10 12 39 am" src="https://cloud.githubusercontent.com/assets/8005288/17143634/91b5bd1a-5319-11e6-9495-0586ea6d1daf.png">

**Comment by hyoo** [comment]
This page is no longer exists.
