### ISSUE TITLE
Assembly service failed with auth header error

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#724]
I was logged in.

![image](https://cloud.githubusercontent.com/assets/991769/17143659/a6004088-5319-11e6-9525-0e32a4bf4e07.png)

**Comment by brettin** [comment]
also problem with annotation service

![image](https://cloud.githubusercontent.com/assets/991769/17144544/b4b22d8c-531c-11e6-94b0-54e103eb97dd.png)

**Comment by brettin** [comment]
Also a problem with workspace upload/download.

I uploaded a file called MANIFEST.txt. No error reported on upload. I then downloaded and opened the file. The contents of the file are wrong, see figure:

![image](https://cloud.githubusercontent.com/assets/991769/17144833/c74d8f26-531d-11e6-8e0f-dc2962988f4c.png)

**Comment by dmachi** [comment]
There was a certificate validation problem while we were at ANL, Bob fixed.
