### ISSUE TITLE
Link vs. no links - in boxes

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#725]
None of search and explore are links, but other boxes have live links

<img width="943" alt="screen shot 2016-07-26 at 10 13 49 am" src="https://cloud.githubusercontent.com/assets/8005288/17143673/b9e25ce4-5319-11e6-9ef1-c4ef9f1321c2.png">

**Comment by dmachi** [comment]
Styling hasn't been completed on this yet, closing as a duplicate of #722
