### ISSUE TITLE
Show which user is logged in on menu or header

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#726]
Right now you have to go to workspace to discover what user you are logged in as

**Comment by dmachi** [comment]
Do we need to show which user is logged or just that you ARE logged in.  I've put a new icon in the header now when you are logged in, but I would prefer to avoid putting the text.  It looks crappy.  If we need something more, I could probably add the user's id into the dropdown of this icon.

**Comment by dmachi** [comment]
Fixed and will be pushed to alpha soon
