### ISSUE TITLE
Taxon overview: AMR panel: add links

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#727]
Add links from the chart and tabular view to corresponding list of genomes. 

-Maulik

**Comment by hyoo** [comment]
Discussed with Maulik and we would like to push back to milestone p3_web-3.2.x, since we want to add extra view for this data type.

**Comment by hyoo** [comment]
fixed and available on beta.

**Comment by mshukla1** [comment]
Wicked awesome! I love it! ... verified on beta.
