### ISSUE TITLE
When clicking sort in an empty column in Workspace, all records disappear

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#73]
In my genome group, if I click the column header for which no records have information, all the rows in the table disappear.

**Comment by mshukla1** [comment]
I still see this behavior. In my genome group, when I sort by disease, all rows disappear. 

![screen shot 2015-06-10 at 11 12 29 pm](https://cloud.githubusercontent.com/assets/1236463/8099116/5c86c6f8-0fc6-11e5-944f-89987ec9c3c6.png)
![screen shot 2015-06-10 at 10 42 21 pm](https://cloud.githubusercontent.com/assets/1236463/8099118/618f0a16-0fc6-11e5-88eb-0fb47c9a5a04.png)

**Comment by mshukla1** [comment]
The problem was that disease field was multi-value, and solr doesn't allow sorting on multi value fields. Dustin has disabled sorting on disease.
