### ISSUE TITLE
Blast - placeholder for text

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#730]
<img width="692" alt="screen shot 2016-07-26 at 10 17 40 am" src="https://cloud.githubusercontent.com/assets/8005288/17143803/39a00c74-531a-11e6-90d8-80384439fee3.png">

**Comment by hyoo** [comment]
please provide short description about this service. I cannot retrieve useful info from the old production BLAST.

**Comment by mshukla1** [comment]
The BLAST Search allows you to search against public or private genomes in PATRIC or other reference databases using a DNA or protein sequence and find matching genomes, genes, RNAs, or proteins.
