### ISSUE TITLE
Genomics workflow - link or no link

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#739]
Difficult to tell which text is links vs. no links

<img width="1018" alt="screen shot 2016-07-26 at 10 23 49 am" src="https://cloud.githubusercontent.com/assets/8005288/17144059/205cf97e-531b-11e6-98d5-0ec4fef0c16c.png">

**Comment by hyoo** [comment]
this was a part of the homepage prototype and we are not using this.
