### ISSUE TITLE
BLAST option field

### ISSUE THREAD

**Issue by vvons** [PATRIC3/patric3_website#740]
Suggesting to add a field that allows entry of BLAST options:

 like for example "-F f" to remove the low complexity sequence filter build into the BLAST default settings

**Comment by hyoo** [comment]
This will require discussion about homology search interface.

**Comment by olsonanl** [comment]
We need to enumerate which options to expose to the user and how to make it not overwhelming.

**Comment by mshukla1** [comment]
Here are the algorithm parameters exposed in NCBI BLAST. Personally, I have hardly ever used anything other than max target sequences option.

@vvons, do you frequently use advance BLAST options for your work? 

<img width="599" alt="screen shot 2016-10-28 at 10 33 20 am" src="https://cloud.githubusercontent.com/assets/1236463/19812219/46e23054-9cfa-11e6-8738-85ccd107da5c.png">

**Comment by vvons** [comment]
Oh yes, I did. Especially in a system like PATRIC this might be very important. See, if you have a sequence that will hit 1000 MT sequences before it hits anything else that you might want to see - BLAST outside your species, but you don’t know who else might have it.
It certainly would make more sense to be able to exclude the same species from the start. You don’t really want 1000 sequences aligned in this case. You would rather save time and computation power and get the BLAST focused on the distant hits. If such parameter could be set, that would be really great.

Veronika

**Comment by mshukla1** [comment]
The current BLAST options allow you to restrict your search in multiple ways to get desired results as shown below. This would satisfy needs for most users. 

<img width="728" alt="screen shot 2017-09-14 at 9 06 16 pm" src="https://user-images.githubusercontent.com/1236463/30463335-b0eabd48-9990-11e7-80dc-2fd88b5c9987.png">

Regarding exposing advanced blast parameters, i.e. scoring parameters, word size, gap penalty, sequence filters / masks etc, I doubt most users would ever use it (I don't). Also, not showing unnecessary advanced options, is consistent with all other services / tools we have. 

I am closing the ticket, please reopen if you disagree.
