### ISSUE TITLE
When clicking on a pie chart on the Genome Overview page and apply that filter, the pie charts didn't charge

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#744]
For example, when a disease "Diarrhea" is clicked, on the genome list page, the filter added this disease. When clicking on APPLY filter button, it added to the top Query sentence, but if we go back to the Overview page, the filter didn't apply to it and the pie chart did not change.

<img width="1264" alt="screen shot 2016-07-26 at 11 01 01 am" src="https://cloud.githubusercontent.com/assets/6361802/17143913/ffc28bb8-5322-11e6-98f2-b82de6ac7208.png">

**Comment by hyoo** [comment]
#822
