### ISSUE TITLE
MSA not loading from workspace

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#75]
After many, many minutes, this is all I see....
![screen shot 2015-03-20 at 11 45 34 am]
![screen shot 2015-03-20 at 11 45 34 am](https://cloud.githubusercontent.com/assets/11475316/6755034/c67b443c-cef6-11e4-9820-ba3c2a7dcf38.png)

**Comment by hyoo** [comment]
fixed and available on beta.
