### ISSUE TITLE
PATRIC register brought up log-in instead of register page

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#752]
<img width="561" alt="screen shot 2016-07-26 at 10 31 49 am" src="https://cloud.githubusercontent.com/assets/8005288/17144390/32fabb9c-531c-11e6-8f6d-6f2b7c592f16.png">

Not this:

<img width="757" alt="screen shot 2016-07-26 at 10 31 27 am" src="https://cloud.githubusercontent.com/assets/8005288/17144395/3959b240-531c-11e6-96dc-11443338e671.png">

**Comment by dmachi** [comment]
Can't reproduce this right now, but will keep an eye and and reopen if necessary.
