### ISSUE TITLE
Bars indicating user information

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#758]
Many times, this icon is used for user information, private account summaries, etc.

It strikes me as different from the norm, that PATRIC information would be housed here. Why would a user believe they should go here to get information about upcoming workshops / PATRIC news? I would recommend changing.

<img width="281" alt="screen shot 2016-07-26 at 10 35 26 am" src="https://cloud.githubusercontent.com/assets/8005288/17144589/df080b2e-531c-11e6-869d-47a13a14b374.png">

**Comment by dmachi** [comment]
This icon is generally the "more" choice, which is why you often see it capturing the user related options.  In any case, i've separated out the user items now.
