### ISSUE TITLE
AMR Panel Summary - blank for both icons

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#760]
<img width="740" alt="screen shot 2016-07-26 at 10 45 08 am" src="https://cloud.githubusercontent.com/assets/8005288/17144923/155d4bac-531e-11e6-8e8d-13eb8faaecef.png">

**Comment by hyoo** [comment]
this may be due to the data inconsistency. cannot reproduce after Maulik's clean up.
