### ISSUE TITLE
Reference Genomes panel cut off - in full screen

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#761]
<img width="439" alt="screen shot 2016-07-26 at 10 46 14 am" src="https://cloud.githubusercontent.com/assets/8005288/17144977/422455cc-531e-11e6-9ae6-677b61fc8bce.png">

**Comment by hyoo** [comment]
![image](https://cloud.githubusercontent.com/assets/1236467/25009298/cf9c8890-202b-11e7-88e9-1e7e17e69f19.png)

fixed
