### ISSUE TITLE
Pathways action not working?

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#763]
3.1.118alpha
From a set of genomes selected the Pathways tab.  From there, selected a set of pathways and then clicked the Pathways action button.  Kept getting empty table and "1-1 of 0 Results." Has a very long URL string.
![screen shot 2016-07-26 at 10 44 42 am](https://cloud.githubusercontent.com/assets/3188570/17144898/00da54e0-531e-11e6-82a0-4cbdbbb81882.png)
![screen shot 2016-07-26 at 10 45 22 am](https://cloud.githubusercontent.com/assets/3188570/17144929/193d4786-531e-11e6-8b38-6c230a6ecd72.png)

**Comment by hyoo** [comment]
This might be related too long url issue. This will trigger pathway summary tab with  6249(=3934+331+1260+724) feature ids.

**Comment by dmachi** [comment]
Duplicate of #766
