### ISSUE TITLE
window does not refresh

### ISSUE THREAD

**Issue by vvons** [PATRIC3/patric3_website#764]
I'm in Firefox on https://www.alpha.patricbrc.org/app/Assembly
I'm choosing a different tool from the tool drop down window in the blue banner, the url changes 
https://www.alpha.patricbrc.org/app/BLAST 
but the window does not refresh and go to the chosen tool window. As I look at it it actually might be because there are no placeholder pages for those apps. That might be the reason.

**Comment by dmachi** [comment]
Were you logged in for this? There is a known bug here that when you are not logged in it should show you the login screen for all of the tools except BLAST.  I suspect that is what you are seeing here.

**Comment by vvons** [comment]
Thank you, I was not logged in. I will retry.

**Comment by dmachi** [comment]
Fixed
