### ISSUE TITLE
Right panel - readability problem

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#767]
<img width="327" alt="screen shot 2016-07-26 at 10 52 44 am" src="https://cloud.githubusercontent.com/assets/8005288/17145269/27ce1bf8-531f-11e6-95b1-8e5a3b0e8cac.png">

**Comment by dmachi** [comment]
There are some things that are hard to read, but most of the common overview stuff is easily read.  Furthermore, you can widen the panel if you want to read inline or you can drill down to that specific item to see in a more readable fashion.
