### ISSUE TITLE
Feature returned twice

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#768]
PATRIC 3.1.118-alpha
A human gene was returned twice in response to a search.   The system perceives  it as one (note a summary panel for fig|1006543.3.peg.2241 displayed on the right) 

<img width="1056" alt="bug1" src="https://cloud.githubusercontent.com/assets/20665963/17145199/f69de84c-531e-11e6-9d35-00aca4035cea.png">

**Comment by dmachi** [comment]
There were some issues in specialty genes viewer.  That has been resolved.
