### ISSUE TITLE
Pathway - blank

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#771]
<img width="1231" alt="screen shot 2016-07-26 at 10 55 34 am" src="https://cloud.githubusercontent.com/assets/8005288/17145389/89923608-531f-11e6-85be-a42daa8884ab.png">

**Comment by mshukla1** [comment]
This happens when I select a one or more features that do not have pathways, i.e. hypothetical proteins. 

Solution: need a summary sentence above the table, which says: 

Out of X genes selected, X genes found in X pathways

**Comment by hyoo** [comment]
#853
