### ISSUE TITLE
Genome list: keeps filters from last taxon view

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#772]
I was in mycobacterium taxon view and applied filters for disease and human. 

Later, I went to Brucella taxon view, I still see the filters from Mycobacterium applied, which are 
not relevant for Brucella genomes, hence the genome list is empty. Screenshot attached. 

The filters should be reset every time the scope for taxon view changes. 

-Maulik

**Comment by dmachi** [comment]
Fixed.
