### ISSUE TITLE
AMR Panel Summary - consistency in phenotype designation

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#774]
<img width="741" alt="screen shot 2016-07-26 at 11 03 02 am" src="https://cloud.githubusercontent.com/assets/8005288/17145637/9c716f5e-5320-11e6-9263-4deccd8beb43.png">

**Comment by hyoo** [comment]
Data cleanup will take care of this issue.

**Comment by mshukla1** [comment]
AMR data has been cleaned up.
