### ISSUE TITLE
Blue banner suggestion

### ISSUE THREAD

**Issue by vvons** [PATRIC3/patric3_website#775]
I feel that the blue banner (because it stays as one proceeds through other pages) should have exactly the same options as the 3 boxes on the entry page and not something different:

Search or Explore Data 
    Genomes
    Genomic Features
    Protein Families
    Transcriptomics Experiments

Analyze (and not Tools)
    Genome Assembly
    Genome Annotation
    BLAST
    Variation Analysis
    RNA-Seq Analysis
    Protein Families Comparison
    Proteome Comparison
    Comparative Pathways
    Metabolic Reconstruction
Workspace
    Upload Your Data
        Contigs
        Reads
        Differential Expression Data
        FASTA Files
    Create and Combine Data Groups
    Store and share analyses

& 
Help

**Comment by dmachi** [comment]
Noted and will try do this to the extent practical.
