### ISSUE TITLE
Genome Metadata tool link - error

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#778]
<img width="529" alt="screen shot 2016-07-26 at 11 23 35 am" src="https://cloud.githubusercontent.com/assets/8005288/17146287/7671fcda-5323-11e6-81e1-c3a73bf9cb35.png">

**Comment by dmachi** [comment]
I know that this is trying to load static content, but i'm not sure which static content.  Where did you link to to get this?  Can you add the url that you see for this?

**Comment by dmachi** [comment]
This was referring to part of the static placeholder content. Closing this ticket for now
