### ISSUE TITLE
Comparative Analyses page - make clean rows

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#779]
<img width="1007" alt="screen shot 2016-07-26 at 11 24 47 am" src="https://cloud.githubusercontent.com/assets/8005288/17146327/a33ba22a-5323-11e6-86a6-2a121b8272f7.png">

**Comment by dmachi** [comment]
This is just placeholder content currently.  We'll need to update this page with the rest of the static content when that happens.  I'm closing this for now.
