### ISSUE TITLE
Major issue with pathways

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#78]
Mapping to the wrong number of pathways in the beta site.  On production, the number of pathways for Salmonella enterica subsp. enterica serovar Typhimurium str. SL1344 is 133.  On beta, the number of pathways is 22.  See attached screenshots.
![screen shot 2015-03-20 at 11 59 04 am](https://cloud.githubusercontent.com/assets/11475316/6755315/986ff39c-cef8-11e4-9c7b-615c113953f3.png)
![screen shot 2015-03-20 at 11 58 56 am](https://cloud.githubusercontent.com/assets/11475316/6755314/986faa36-cef8-11e4-8abf-2491a7329aec.png)

**Comment by hyoo** [comment]
This is a bug and fixed on beta. http://www.beta.patricbrc.org/portal/portal/patric/CompPathwayTable?cType=genome&cId=216597.6&algorithm=PATRIC&ec_number=
