### ISSUE TITLE
Explore - clicking down error makes box disappear

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#780]
<img width="542" alt="screen shot 2016-07-26 at 11 26 27 am" src="https://cloud.githubusercontent.com/assets/8005288/17146378/d908f600-5323-11e6-9eb1-d5f5d7636122.png">

**Comment by dmachi** [comment]
This is the general behavior of popups.  When they are clicked, even if nothing in particular is clicked, they close.  The down arrow in this case doesn't do anything, so the popup closed.  I have adjusted the styling so that it doesn't change color and cursor on hover.
