### ISSUE TITLE
Protein family sorter

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#781]
Two issues are described in the attached file "Bug2.png" One of them is an optional suggestion, as we don't need to baby our users necessarily...

![bug2](https://cloud.githubusercontent.com/assets/20665963/17146362/c712002c-5323-11e6-863e-c0d141a0a737.png)

**Comment by hyoo** [comment]
1. pgfam is selected by default (see #864)
2. title has added on the top checkbox.
   These fixes will be available on alpha soon.

**Comment by mshukla1** [comment]
fixed, verified on alpha.
