### ISSUE TITLE
Filter returns unexpected result

### ISSUE THREAD

**Issue by disz** [PATRIC3/patric3_website#783]
https://www.alpha.patricbrc.org/view/Genome/83333.106#view_tab=features&filter=keyword(s1)

On this page I searched for s1 in the keyword box and it returned features with no apparent occurrence of s1.

**Comment by mshukla1** [comment]
@dmachi: Two thoughts: 
1. We should make the keyword search in feature and genome list behave the same way as those in global search. i.e. use the same optimizations for a given data type. 
2. Whenever keyword search is applied in genome/feature/spgene lists, sort the results by score to bring the best results at the top. 

-Maulik

**Comment by mshukla1** [comment]
I believe this is now addressed with the advanced search criteria in the global search.
