### ISSUE TITLE
Differential Expression link - brings you back to homepage

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#784]
<img width="886" alt="screen shot 2016-07-26 at 11 28 45 am" src="https://cloud.githubusercontent.com/assets/8005288/17146500/5a6440ce-5324-11e6-9bb4-cb51e3b81e78.png">

Brings you here:

<img width="948" alt="screen shot 2016-07-26 at 11 30 35 am" src="https://cloud.githubusercontent.com/assets/8005288/17146520/7334ff6c-5324-11e6-9202-e990f36d297e.png">

**Comment by edietrich** [comment]
Here is what the first picture should be:

<img width="927" alt="screen shot 2016-07-26 at 11 30 02 am" src="https://cloud.githubusercontent.com/assets/8005288/17146553/8c1dc8d8-5324-11e6-8f7d-01ad291f8f3f.png">

**Comment by hyoo** [comment]
this was a part of the homepage prototype and we are not using this.
