### ISSUE TITLE
Genome List: Antimicrobial Resistance_evidence

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#787]
Change the filter label to "Antimicrobial Resistance Evidence" to make it consistent with others. 

<img width="402" alt="screen shot 2016-07-26 at 2 01 16 pm" src="https://cloud.githubusercontent.com/assets/1236463/17152040/ba9d8074-533b-11e6-8f96-a428ab0670ac.png">

**Comment by dmachi** [comment]
Fixed
