### ISSUE TITLE
View Experiment Group Gene List does not work from the workspace Experiment Group

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#788]
<img width="973" alt="screen shot 2016-07-26 at 3 23 24 pm" src="https://cloud.githubusercontent.com/assets/6361802/17152223/f6e7728e-5344-11e6-9327-00410b1ead1b.png">

<img width="815" alt="screen shot 2016-07-26 at 3 23 36 pm" src="https://cloud.githubusercontent.com/assets/6361802/17152231/fcc0f87e-5344-11e6-810a-f060caa8fe26.png">

**Comment by hyoo** [comment]
Two things to do
- form a url to alpha site. currently it uses production url pattern.
- TranscriptomicsGene viewer is not ready to read from workspace yet. We need to implement this.

**Comment by hyoo** [comment]
fixed and available on alpha.
