### ISSUE TITLE
View Experiment Gene List does not work from the workspace Experiment

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#789]
<img width="982" alt="screen shot 2016-07-26 at 3 25 45 pm" src="https://cloud.githubusercontent.com/assets/6361802/17152343/586de402-5345-11e6-8414-063b469295ed.png">
<img width="801" alt="screen shot 2016-07-26 at 3 25 56 pm" src="https://cloud.githubusercontent.com/assets/6361802/17152350/5c631870-5345-11e6-8469-56267ffbdc9f.png">

**Comment by hyoo** [comment]
duplicate #788
