### ISSUE TITLE
From heatmap view, when I save proteins to group, the dialog box doesn't go away

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#79]
I successfully created the group, but the box remains
![screen shot 2015-03-20 at 12 03 40 pm](https://cloud.githubusercontent.com/assets/11475316/6755412/4de221dc-cef9-11e4-9f17-91eac83a2a84.png)

**Comment by hyoo** [comment]
I cannot reproduce this issue. When you click "Add Proteins To Group", that dialog should be closed and Workspace one should show up.

**Comment by mshukla1** [comment]
Can't reproduce, seems to be fixed now.
