### ISSUE TITLE
Taxonomy Overview Pie Chart: It's hard to read the labels when the label names are long

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#790]
I suggest to add an action: when the mouse point to the pie, the full name shows in the tip.
<img width="323" alt="screen shot 2016-07-26 at 3 38 19 pm" src="https://cloud.githubusercontent.com/assets/6361802/17152808/73ae4246-5347-11e6-8591-4afc552e6c5e.png">

**Comment by hyoo** [comment]
color them has changed
