### ISSUE TITLE
Blank page when going to genome list from search

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#793]
To reproduce:

go to alpha front page.
paste HKOPL1 into search box and search
click on Genomes (1)
and get a blank page

the link I get when I go there is 
https://www.alpha.patricbrc.org/view/GenomeList/?keyword(HKOPL1)#view_tab=genomes

This breaks in safari and works in chrome

3.1.118alpha

**Comment by dmachi** [comment]
Fixed with the es6 updates harry pushed earlier
