### ISSUE TITLE
Global Search: genome features searches only CDSs

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#797]
It seems that the global search is currently searching only for CDSs in genome features. 
So, if I search for Brucella rRNA, I don't actually get rRNAs. If I click on genome features, it takes me to a table matching CDSs with keyword rRNA. 

The global search should search for all features, except maybe source and assembly gaps. Or, better, boost the score for following matches in the global search results: 
- CDS and RNA genes
- PATRIC annotation
- Select attributes: Genome id, genome name, PATRIC id, refseq locus tag, gene name, product

**Comment by dmachi** [comment]
Fixed
