### ISSUE TITLE
Genome View: The breadcrumb for the genome page is missing the genome name

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#798]
See the example below: Staphylococcus argenteus strain H115100079 should be included in the breadcrumb
<img width="1014" alt="screen shot 2016-07-26 at 4 29 04 pm" src="https://cloud.githubusercontent.com/assets/6361802/17154240/1bc50cc0-534e-11e6-9214-8a3198999de7.png">

**Comment by dmachi** [comment]
Fixed
