### ISSUE TITLE
pathway heatmap problems

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#8]
WE still seem to have problem with the pathway heatmap. The heatmap 
loads correctly for small amount of data, say when there are less than
~10000 genes in the selected pathway. However, when there are more than 
~10000 genes in a pathway, heatmap never loads. For example, you can go 
to Brucellaceae level and try few pathways from there. 

http://patricbrc.org/portal/portal/patric/CompPathwayTable?cType=taxon&cId=118882&algorithm=PATRIC&ec_number=

TCA cycle loads fine: 

http://patricbrc.org/portal/portal/patric/CompPathwayMap?cType=taxon&cId=118882&dm=&feature_id=&ec_number=&map=00020&pk=&algorithm=PATRIC

However, if you sort the table by number unique genes in descending order and try 
first two/three pathways:

Purine metabolism
http://patricbrc.org/portal/portal/patric/CompPathwayMap?cType=taxon&cId=118882&dm=&feature_id=&ec_number=&map=00230&pk=&algorithm=PATRIC

or, Arginine and proline metabolism
http://patricbrc.org/portal/portal/patric/CompPathwayMap?cType=taxon&cId=118882&dm=&feature_id=&ec_number=&map=00330&pk=&algorithm=PATRIC

the heat map never load and give "500 internal server error". 
Please see the attached screen shots. 

  
I believe the problem most likely due to the ajax / solr call timeout set to 30 sec or so. 
I tried the pages multiple times, and the error message always appear at around 35 seconds.
All the pathways for which the heatmap loads correctly, it loads in less than 30 seconds. 

Please check it out and see if the problem is indeed related to request timeout. 
If so, please increase the timeout to 5 minutes and we can see if that solves the 
problem.

**Comment by mshukla1** [comment]
This is due to the out of memory issue on solr side.

The facet query retrieving the unique feature count cause out of memory error.

http://macleod.vbi.vt.edu:8080/solr/pathway/select?q=pathway_id:00230&fq=annotation:PATRIC&fq={!join%20from=genome_id%20to=genome_id%20fromIndex=genome}taxon_lineage_ids:118882%20AND%20genome_status:(complete%20OR%20wgs)&rows=0&facet=true&json.facet={stat:{field:{field:genome_ec,limit:-1,facet:{gene_count:%22unique(feature_id)%22}}}}


Dustin, would you take a look at? I guess we can increase the heap size and try this query again.

**Comment by dmachi** [comment]
We can increase the memory if you like, but I think we're going to have to rethink how we are doing this some.  A single instance of this query is trying to use more than 15-20gb (before it fails, so maybe more).  While we can probably increase the memory to support allowing this to run, it probably wont' be able to handle two or three people running it simultaneously.

How much would you like to increase it? Either harry or I can bump up the numbers and restart solr.

**Comment by hyoo** [comment]
I was able to simplify the facet query, which uses less memory. Actually, the entities in the pathway core were features, so we don't need to count unique feature_id, instead, we can just count the number of records. Please verify the result below,

http://dev.patricbrc.org/portal/portal/patric/CompPathwayTable?cType=taxon&cId=118882&algorithm=PATRIC&ec_number=
