### ISSUE TITLE
The case of 415 invisible cyano genomes

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#800]
See attached 

![bug3](https://cloud.githubusercontent.com/assets/20665963/17155075/44eb51cc-5349-11e6-913f-f01a5c373c69.png)

**Comment by dmachi** [comment]
I'm not exactly sure why, but in the database both terrabacteria group and cyanobacteria group both appear to be 'no rank' and I think that is messing this up.

**Comment by dmachi** [comment]
Confirmed that these groups are both classified as "no rank" at NCBI, http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=1798711&lvl=3&lin=f&keep=1&srchmode=1&unlock.

I'm not exactly sure how to resolve this problem, handing off to Maulik

**Comment by dmachi** [comment]
Fixed
