### ISSUE TITLE
Patric ID sort

### ISSUE THREAD

**Issue by vvons** [PATRIC3/patric3_website#801]
https://www.alpha.patricbrc.org/view/FeatureList/?keyword(*)#view_tab=features&filter=and(eq(annotation,%22PATRIC%22),eq(feature_type,%22CDS%22))
Sort needs to be fixed. The column PATRIC ID if sorted returns :
peg.1
peg.10
peg.100
peg.1000
peg.1001
peg.1002

**Comment by dmachi** [comment]
There isn't much that can be done about this currently.  You can work around the issue by sorting on the start parameter.  We'll see what we can do to address this in the future.
