### ISSUE TITLE
More on Taxonomy Tab

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#802]
There are many  phyla named "Candidatus smth ..."  displayed under the Taxonomy Tab. They crowd the view as they all appear early (high in the list),  starting with "C" 
I suggest to group them all under "unclassified Bacteria" OR "Bacteria candidate phyla" as the top phylum.  Patric already has the detail taxonomic descriptions in place --

     cellular organisms, Bacteria, **unclassified Bacteria,** **Bacteria candidate phyla,** Patescibacteria group, Microgenomates group, Candidatus Amesbacteria

**Comment by mshukla1** [comment]
@dmachi 

I think, currently, the problem is that you are trying to guess/specify the next taxonomy level explicitly (i.e. "phylum") which may not be try next level for a any given node as there may be "no rank" nodes that are direct children of a node. 

Solution: Maulik to add parent id in the solr core, which can be used to find direct descendants of any give taxonomy node. 

-Maulik

**Comment by dmachi** [comment]
I'm not sure I'm following this.  I don't quite understand what Sveta is getting at.   Additionally, I am NOT trying to guess/specify the next taxonomy level.  It walks down the the levels until it find something.  All that said, adding parent id would make the whole walk easier/unnecessary.

**Comment by dmachi** [comment]
Fixed

**Comment by Sveta-user** [comment]
Really like how Patric Taxonomy display looks now.   Great job, guys! 
However the "Phylogeny" tab is always empty, doesn't seem to work at all...  Don't want to open a new ticket - maybe this function is not yet supposed to work in alpha?

**Comment by mshukla1** [comment]
We do have phylogenetic trees for select bacterial orders. 

Can you please provide the URL for the page you were looking at? 
It will help us figure out whether it is a bug or whether we don’t have 
tree available for that taxon. 

-Maulik

**Comment by mshukla1** [comment]
In cat, create a new ticket for missing phylogeny, so that we can track the issue. 

-M
