### ISSUE TITLE
Set appropriate limits for tabs and tools

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#803]
Tabls: 

Protein families: 500 genomes
Pathways: 500 genomes
All other tabs: 10000 genomes OR max that can be supported by solr

Tools: 

MSA: 200 
ID Mapping: 1000

**Comment by dmachi** [comment]
I've implemented a version of the filtering to reference and representative genomes as we discussed last week.  I  have not yet updated the tool limits.   

Note that while 10k works as the default for most of the tabs, it is not clear to me if that number should end up being that high

**Comment by dmachi** [comment]
These updates have been commited.  They will be merged to alpha in a day or two.
