### ISSUE TITLE
Should be able to access genomes from Taxonomy view

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#808]
The only action bar item is Taxonomy, and that is only enabled if only one taxon level is selected.  Since the taxon levels represent sets of genomes, it seems like the Genomes action icon at least should be enabled.
![screen shot 2016-07-27 at 9 43 46 am](https://cloud.githubusercontent.com/assets/3188570/17179390/a97988bc-53de-11e6-8d97-67accf9a1697.png)

**Comment by dmachi** [comment]
To get to genomes from here, there are two options.  
   1.  Click on Taxonomy (to update the taxon ) then go to the genomes tab
   2.  Click and hold on Taxonomy, a popup will appear and then you can go straight to genomes from there.
