### ISSUE TITLE
Public workspaces are not available, and speciality workspaces are not workspaces

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#809]
How do i see the list of public workspaces and how do I get to them.

![image](https://cloud.githubusercontent.com/assets/991769/17179707/c1182590-53df-11e6-9abc-46c294dcedd9.png)

**Comment by mshukla1** [comment]
There is nothing in special collections or public workspace as of now, except:

- OMICS4TB data: https://www.patricbrc.org/workspace/PATRIC@patricbrc.org/home/Special%20Collections/NIAID%20Systems%20Biology%20Centers

My suggestions: 
- Special collections: links to the existing data landing pages for now
- Workspaces: given that we do not support multiple workspaces for users for now, it owuld be more useful to provide direct links to genome groups, feature groups, and perhaps other recently updated top level folders in my workspace

**Comment by dmachi** [comment]
Fixed
