### ISSUE TITLE
In my workspace Experiment Group folder, some groups were empty

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#81]
In my workspace Experiment Group folder, some groups were empty although they have items in the PATRIC production site. For example: cmao / home / Experiment Groups / iron uptake

**Comment by dmachi** [comment]
We're failing to return experiments for solr currently.

**Comment by dmachi** [comment]
This should be fixed after I push to beta in a few minutes.  Please verify and reopen if this is still an issue for you.
