### ISSUE TITLE
Workspace "created" files

### ISSUE THREAD

**Issue by vvons** [PATRIC3/patric3_website#810]
I would suggest to display rather the "date modified" then the date a file or folder was "created". It would help find recent  additions faster and this is usually what you are working on.

**Comment by dmachi** [comment]
Technically you can't modify files in your workspace, so the modification date and the creation date should always be the same.  We could update the label though.

**Comment by dmachi** [comment]
@vvons suggested that we at least update the folder's modification date as things are added.  I'm not sure if currently have a modification date field for any of this.  Passing to @olsonanl to evaluate.

**Comment by nconrad** [comment]
I agree this would be pretty useful.  Duplicate of #668
