### ISSUE TITLE
Concentric pulsating circles

### ISSUE THREAD

**Issue by vvons** [PATRIC3/patric3_website#811]
While waiting for a table to load, I'm seeing the conventional little spinning ball AND big concentric pulsating circles. If that is intended, have you considered what will happen to the user if the table is very big or the connection very slow? He/she might get hypnotized... :-)

**Comment by dmachi** [comment]
When you refer to the conventional little spinning ball, do you mean the normal apple 'beachball'?

**Comment by dmachi** [comment]
I don't see this as an actual problem, just a stylistic decision.  Joe and most others have been fine with it.  If anyone actually does get hyptnotized, I'll add some subliminal messages in there saying patric is great.
