### ISSUE TITLE
cant upload to the workspace

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#813]
I don't think I can upload to the workspace.  The upload button says 100% but I have 0bytes.

<img width="1224" alt="screen shot 2016-07-27 at 10 29 13 am" src="https://cloud.githubusercontent.com/assets/7661533/17181251/0a4b260e-53e5-11e6-8da7-400bb1006f28.png">

**Comment by dmachi** [comment]
This was a cert issue
