### ISSUE TITLE
Search in Taxonomies does not seem to work

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#814]
3.1.121alpha

![screen shot 2016-07-27 at 10 29 58 am](https://cloud.githubusercontent.com/assets/3188570/17181268/1fc48e26-53e5-11e6-9c21-571309865a63.png)

**Comment by maovt** [comment]
It works for me. You had a typo. Should be Escherichia

**Comment by rkenyon** [comment]
It works when "Everything" is selected, but not when "Taxonomies" is selected.

**Comment by maovt** [comment]
Fixed.

**Comment by dmachi** [comment]
deployed
