### ISSUE TITLE
Issue with FIGfam vs. PLfams vs. PGfams filters

### ISSUE THREAD

**Issue by vvons** [PATRIC3/patric3_website#815]
https://www.alpha.patricbrc.org/view/GenomeGroup/VeronikaV@patricbrc.org/home/Genome%20Groups/Complete%20E.colis#view_tab=proteinFamilies

I was trying to see differences between choosing different families for E.coli annotations. Here are several screen shots. Note the radio buttons checked and the feature numbers displayed. 
I don't think that the Filters work properly. Radio buttons stay clicked when clicking for another filter. The table does change, but at the end it is not clear what you are looking at, if the radio buttons stay marked.

_
<img width="885" alt="screen shot 2016-07-27 at 10 21 22 am" src="https://cloud.githubusercontent.com/assets/20665585/17181511/01e79140-53e6-11e6-9345-3e7917aa7681.png">
<img width="889" alt="screen shot 2016-07-27 at 10 02 14 am" src="https://cloud.githubusercontent.com/assets/20665585/17181510/01e3ccea-53e6-11e6-9757-caf8ded7eaf3.png">
<img width="891" alt="screen shot 2016-07-27 at 10 00 16 am" src="https://cloud.githubusercontent.com/assets/20665585/17181509/01e365f2-53e6-11e6-80c6-f59c001d0d81.png">

_

**Comment by hyoo** [comment]
I was able to reproduce it when I request another family type before it gets loaded. So I fixed that case. please reopen if you can reproduce with other route. will be deployed soon on alpha.
