### ISSUE TITLE
AMR data in the all bacteria genomes overview is wrong

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#816]
The number for isoniazid isn't correct, and would not have been correct even in July of last year.

<img width="729" alt="screen shot 2016-07-27 at 11 24 42 am" src="https://cloud.githubusercontent.com/assets/7661533/17183411/e723523e-53ec-11e6-8a8c-fcf77a0dfcfb.png">

**Comment by mshukla1** [comment]
This could be because the alpha site was connecting to the solr replica at Argonne at that point, which may not have all AMR data recently added. 

The production solr has correct AMR data as of now, after July release...and it looks like it is 
displayed correctly now on the alpha site. 

-Maulik
