### ISSUE TITLE
Popup window off screen

### ISSUE THREAD

**Issue by vvons** [PATRIC3/patric3_website#817]
Please see example where popup window is running off the screen
<img width="1195" alt="screen shot 2016-07-27 at 11 40 39 am" src="https://cloud.githubusercontent.com/assets/20665585/17183956/70685e20-53ef-11e6-9154-718f5ddeb2a0.png">

**Comment by dmachi** [comment]
I have made changes that fixes this issue for the most part, though its not perfect on this particular popup.
