### ISSUE TITLE
Genome Overview: Remove the empty spaces when the pie chart is empty

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#818]
If any of the pie charts has no data, we should remove the empty spaces.

<img width="1125" alt="screen shot 2016-07-27 at 1 03 31 pm" src="https://cloud.githubusercontent.com/assets/6361802/17184537/c8b4dc7e-53fa-11e6-8578-852b28f38cab.png">

**Comment by hyoo** [comment]
fixed and will be available on alpha soon
