### ISSUE TITLE
Genome Circular Viewer: "loading NON-CDS FEATURES" problem 

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#827]
"loading NON-CDS FEATURES" message does not disappear for some of the genomes.
![circular_view](https://cloud.githubusercontent.com/assets/6361802/17532542/13a50e26-5e4f-11e6-93b1-49180647f3df.png)

**Comment by dmachi** [comment]
There is something weird about that track.  When I load that Genome in the browser, it looks like there are two overlapping NON-CDS Feature tracks and I see some errors in the console. Looking in the Feature list for that genome, it looks like there aren’t any non-CDS features outside of some ‘source’ features, which I are explicitly excluded from that tracks’ query.

**Comment by maovt** [comment]
This happens to many small genomes which do not have NON-CDS features.

**Comment by maovt** [comment]
Fixed. Also fixed an issue that not all NON_CDS features were loaded.
