### ISSUE TITLE
Download for feature transcriptomics table not working

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#829]
The download buttons for feature transcriptomics table (whole table or selected items) do not work.

**Comment by chmao1** [comment]
Here is an example:

https://www.beta.patricbrc.org/view/Feature/PATRIC.83332.12.NC_000962.CDS.1002917.1003792.fwd#view_tab=transcriptomics

<img width="1081" alt="screen shot 2016-10-10 at 4 30 14 pm" src="https://cloud.githubusercontent.com/assets/6361802/19250172/f14539c6-8f06-11e6-8f78-8bdaeb0595b5.png">

**Comment by mshukla1** [comment]
The whole table download is working now. However, downloading selected items using action bar still doesn't work. 

-Maulik

**Comment by chmao1** [comment]
Here is an example page
https://www.alpha.patricbrc.org/view/Feature/PATRIC.83332.12.NC_000962.CDS.1015398.1016171.fwd#view_tab=transcriptomics
Go to the "Table" tab

**Comment by dmachi** [comment]
I believe this is failing because there is no unique key defined in the transcriptomics_gene core in solr.  The streaming download requires that queries be sorted on a unique key.  Currently the query is trying to use 'pid' as the unique key, but I dont see it defined as unique in the solr schema.

**Comment by dmachi** [comment]
@maovt  Harry will need to add a unique key into this table before the download can work, but he indicated that 'pid' isn't correct.  That was unique per sample, but not for the gene.  I think it is probably 'id' that this needs to be sorted by for downloads.

**Comment by hyoo** [comment]
we actually had the id field with values, so please use this. I reloaded production solr. so you should be able to see it now.

**Comment by dmachi** [comment]
I changed the pk to use 'id' instead of 'pid'.  With Harry's change, this works for both the table download and the selection download.

**Comment by mshukla1** [comment]
fixed. verified on beta.
