### ISSUE TITLE
RASTtk files that I get from PATRIC are corrupted

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#83]
I annotated my own genome and thenI opened up the feature table.  Instead of seeing protein or nucleotide sequence in column F, I see garbage.  See screenshot
![screen shot 2015-03-20 at 4 28 05 pm](https://cloud.githubusercontent.com/assets/11475316/6760373/428c6e30-cf1e-11e4-8084-c682775cabdb.png)

**Comment by olsonanl** [comment]
This isn't a matter of corruption, rather the lack of headings and the fact the data is checksums and not protein sequences. This is resolved by the addition of column headings and the new spreadsheet download.
