### ISSUE TITLE
can not perform batch search

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#832]
Using the genome finder page, I can create a genome group by pasting in a list of genome ids. I can do this in about three mouse clicks. 

I can't do this on alpha.

1408180.3
1088720.3
1318634.3
1236940.3
568704.3
1078018.5
525361.3
1381116.3
1286405.4
1408205.4

**Comment by mshukla1** [comment]
#896

**Comment by dmachi** [comment]
Spoke with Rebecca.  This is not needed for the Florida WS, bumping it to fix other bugs.

**Comment by hyoo** [comment]
Now you can do this by selecting search option "Any Term"

![image](https://cloud.githubusercontent.com/assets/1236467/25968874/8e4dc636-3658-11e7-9bcb-31d335634e83.png)
