### ISSUE TITLE
annotation service fails on alpha, works on production, with same inputs

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#834]
The same 2 sets of 2 were run on alpha and prod. The alpha annotation jobs fail.

![image](https://cloud.githubusercontent.com/assets/991769/17636484/f8289dc4-60a2-11e6-8704-b24f633035d5.png)

The error message for the failed task run from alpha:

![image](https://cloud.githubusercontent.com/assets/991769/17635552/a44cb2c6-609d-11e6-8785-a13dd24c5349.png)

**Comment by dmachi** [comment]
We were configured to use p3c which wasn't working or failing in some way.
