### ISSUE TITLE
proteome comparison not displaying genome name

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#837]
Not sure why, but the genome name didn't display.

![image](https://cloud.githubusercontent.com/assets/991769/17637228/cf4cb066-60a7-11e6-9e12-3f8d8c9ff4c5.png)

![image](https://cloud.githubusercontent.com/assets/991769/17637245/de14235e-60a7-11e6-8a4d-389332db4481.png)

**Comment by dmachi** [comment]
p3c protoeome comparison error.  Works when configured against p3 service.
