### ISSUE TITLE
gene links on proteome comparison maps not working

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#838]
![image](https://cloud.githubusercontent.com/assets/991769/17637347/a537808e-60a8-11e6-87fd-efa00bad87e1.png)

**Comment by brettin** [comment]
the links are in the output of the service, so all of the existing proteome comparison views are going to fail when jboss goes away

**Comment by mshukla1** [comment]
Below is the link URL I am getting for one of the jobs I submitted on production some time ago. 

https://www.alpha.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=fig|83332.12.peg.39

The URL is already pointing to alpha. Probably, we should just redirect it to the appropriate gene page on alpha. 

-Maulik

**Comment by hyoo** [comment]
we can set nginx rewrite rule for this. The rewritten url should be like 

https://www.alpha.patricbrc.org/view/Feature/fig|83332.12.peg.39

**Comment by dmachi** [comment]
Fixed on alpha and beta
