### ISSUE TITLE
Change About (hamburger) menu items

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#842]
I believe we need to avoid links to Production eNews. This is problematic for a number of reasons.  Pursuant to this, please make the following changes:

Make the following static pages in Alpha (copy the html to an alpha page)
 - Publications
 - Scientific Working Group
 - Personnel
 - Collaborators
 - Related Sites

Remove the following fromt the menu for now (we need to re-think how we do these and I will defend their removal to Rick or whoever)
 - Data Releases and Updates
 - Website Updates
 - Presentations

**Comment by dmachi** [comment]
I've made these changes to pull the static content out of enews with the exception of news items themselves which is more problematic and will need more work.  We probably need to update the style on some of these somewhat (or at least pull in the css classes that were in use into our site css).

All of the static content is located at https://github.com/PATRIC3/p3_api/tree/master/content and can be checked out and edited or edited inline in github.  After updates are made, a simple git pull is all that is required to deploy the updates to the site.

**Comment by dmachi** [comment]
Will need to move the content from Specialty data collections over too, so i'm reopening this ticket.

**Comment by mshukla1** [comment]
I am closing this ticket and opening another one specifically for special data collections, for better tracking.
