### ISSUE TITLE
Taxon/genome list view: default should be overview tab

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#843]
I am in borrelia, protein family tab. Next, I select mycobacterium from the top nav, and it jumps directly to mycobacterium protein family tab. 

Every time taxon level is changed, by default it should go to the oveview page, not the same tab 
for the last taxon. 

I think the same principle whould apply to other views as well, i.e. genome list, genome view, etc. 

-Maulik

**Comment by dmachi** [comment]
Fixed this for the tabs in the menu bar
