### ISSUE TITLE
Down scroll bar on Heat map in alpha.patricbrc.org not scrolling

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#850]
Its stuck at one level with the names are expanded, making it impossible to see the lower genomes.  The horizontal scroll bar works well, though

**Comment by hyoo** [comment]
I cannot reproduce this problem on chrome 52.0.2743.116 (64-bit), firefox 48.0.2, and safari  9.1.3 (11601.7.8).

Please specify your browser and url.

**Comment by hyoo** [comment]
duplicate #1102
