### ISSUE TITLE
Pathway list not appearing

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#852]
Made a second selection from the heatmap, got the genes, selected Pathway Summary in the green bar and got...a totally blank page (see screenshot).  Feeling even more sad 👎 
<img width="1211" alt="screen shot 2016-08-17 at 5 50 22 pm" src="https://cloud.githubusercontent.com/assets/11475316/17754580/2c9f0b20-64a3-11e6-809d-a8e281d87550.png">

**Comment by hyoo** [comment]
could be related to #853
