### ISSUE TITLE
Pathway Summary: add title and link to pathway map

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#853]
On the pathway summary page: 

- add bread crumb / page title, i..e "Pathway Summary"
- add a message saying, "Out of 20 genes selected, 6 genes found in 8 pathways"
- when a single pathway is selected from the table, provide link to pathway map

**Comment by hyoo** [comment]
fixed and will be available soon

**Comment by mshukla1** [comment]
Looks good!
