### ISSUE TITLE
Unable to upload xlsx file in Differential Expression Import on alpha

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#854]
Alas, my dreams of doing an analysis on the beautiful alpha site are thwarted.  I was unable to upload my excel file with my carefully crafted data.  It stayed stuck on the upload page (see screenshot).  Feeling slightly let down, but not overly depressed. :(
<img width="676" alt="screen shot 2016-08-17 at 6 11 09 pm" src="https://cloud.githubusercontent.com/assets/11475316/17755156/45bf166a-64a6-11e6-9a25-f66d78d756bc.png">

**Comment by aswarren** [comment]
Not sure what you were experiencing but this worked fine for me on alpha with the same file

![image](https://cloud.githubusercontent.com/assets/229173/18187053/73aa411a-7074-11e6-8d88-e72d9a5bcfba.png)
