### ISSUE TITLE
Can't upload text file using differential expression import on alpha site

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#855]
Alas, this didn't work either.  Now I feel very depressed, as I was sure this would work. 👎 
<img width="997" alt="screen shot 2016-08-17 at 6 13 51 pm" src="https://cloud.githubusercontent.com/assets/11475316/17755202/879a9258-64a6-11e6-894c-4877a7e76411.png">

**Comment by ARWattam** [comment]
I might add that the same file uploaded beautifully on the PRODUCTION website.  That made me feel happy 👍

**Comment by aswarren** [comment]
Works fine for me on alpha. Must be a blip.
![image](https://cloud.githubusercontent.com/assets/229173/18187612/0293b2ea-7079-11e6-9ba0-421f57310f59.png)
