### ISSUE TITLE
Found the experiment on alpha, but the genes don't load

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#857]
One step forward two steps back.  The experiment is there, and I click on it (its cute little flask icon is MISSING, btw), and then I click on "Genes" in the green bar, and....drum roll....nothing loads (see screenshot).  To quote Donald Trump, "Sad."
<img width="1262" alt="screen shot 2016-08-17 at 7 13 26 pm" src="https://cloud.githubusercontent.com/assets/11475316/17756624/10087a4e-64af-11e6-8e79-474d9db353db.png">

**Comment by mshukla1** [comment]
From where did you find the experiment? global search or experiment list? 

-Maulik

**Comment by mshukla1** [comment]
working now on beta.
