### ISSUE TITLE
Feature Group in workspace: Feature List View is missing

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#858]
Feature List View option in the green action bar is needed for feature group

**Comment by mshukla1** [comment]
This is critical oversite. 

From the workspoace feature group list, there is no link to the feature group overview page. It needs to be added in the toolbar. 

When I double click on a feature group, it takes to the list of members, the old page that was implemented in the production workspace. Instead it should go to feature list overview page! 

We need similar action when multiple feature groups are selected. 

-Maulik

**Comment by maovt** [comment]
Fixed and made a pull request
