### ISSUE TITLE
Genomes Tab: Sorting by Antimicrobial Resistance column gives an empty table

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#861]
![genomelist](https://cloud.githubusercontent.com/assets/6361802/17790912/a73b083e-6566-11e6-83e3-cc56d946681c.png)

**Comment by mshukla1** [comment]
Dustin, sorting is not working because antimicrobial_resistance is a multi value fields. 

We need to either disable sorting or handle it gracefully, instead of table not loading.

**Comment by dmachi** [comment]
Yes, that column just needs to set sortable to false.

https://github.com/PATRIC3/p3_web/blob/master/public/js/p3/widget/GenomeGrid.js#L269-L278 <https://github.com/PATRIC3/p3_web/blob/master/public/js/p3/widget/GenomeGrid.js#L269-L278>

need to have “sortable: false” added as is done at:

https://github.com/PATRIC3/p3_web/blob/master/public/js/p3/widget/GenomeGrid.js#L88 <https://github.com/PATRIC3/p3_web/blob/master/public/js/p3/widget/GenomeGrid.js#L88>

If there are other multivalve fields, the same treatment should be done on them.

**Comment by dmachi** [comment]
Fixed all multivalue fields in the GenomeGrid
