### ISSUE TITLE
Loading icon does not show on alpha when you change protein families

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#865]
I like it.  It should be there

**Comment by mshukla1** [comment]
Agree, we need to add wait icons throughout the site, for most of the tables/pages, if not all.  

-Maulik

**Comment by hyoo** [comment]
loading icon on family_type is already there. moving milestone to 3.2.x

**Comment by mshukla1** [comment]
Fixed, verified on alpha.
