### ISSUE TITLE
Map icon missing from green bar in gene selection-alpha

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#866]
We can't see the pathway map because the icon is missing
![screen shot 2016-08-19 at 11 47 41 am](https://cloud.githubusercontent.com/assets/11475316/17815557/d3fc63d0-6602-11e6-9f24-b5dfffe88ad6.png)
![screen shot 2016-08-19 at 11 47 25 am](https://cloud.githubusercontent.com/assets/11475316/17815559/d3fcaa02-6602-11e6-85c3-4698088fb81a.png)
![screen shot 2016-08-19 at 11 47 14 am](https://cloud.githubusercontent.com/assets/11475316/17815560/d3fca5a2-6602-11e6-82a4-05f2b7d379a3.png)
![screen shot 2016-08-19 at 11 47 16 am](https://cloud.githubusercontent.com/assets/11475316/17815556/d3fc17cc-6602-11e6-9566-83ca7b3a705a.png)
![screen shot 2016-08-19 at 11 47 05 am](https://cloud.githubusercontent.com/assets/11475316/17815558/d3fc729e-6602-11e6-83de-91d750a429b2.png)

**Comment by ARWattam** [comment]
Screenshots are reverse order in the process

**Comment by mshukla1** [comment]
Map icon is added from the pathway summary table. Verified on alpha. 

-Maulik
