### ISSUE TITLE
Comparing pathways with groups in alpha only shows one genome on map

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#867]
There should be 63 selected, but when you get down to the final pathway map it only shows the data for ONE. 👎 
![screen shot 2016-08-19 at 11 50 05 am](https://cloud.githubusercontent.com/assets/11475316/17815647/42e04be0-6603-11e6-85ae-c49dcb34711b.png)
![screen shot 2016-08-19 at 11 49 48 am](https://cloud.githubusercontent.com/assets/11475316/17815649/42e69874-6603-11e6-923f-0dfec31a2fbf.png)
![screen shot 2016-08-19 at 11 49 36 am](https://cloud.githubusercontent.com/assets/11475316/17815646/42dfaef6-6603-11e6-8371-55eb56c7d968.png)
![screen shot 2016-08-19 at 11 49 17 am](https://cloud.githubusercontent.com/assets/11475316/17815648/42e2c492-6603-11e6-9086-98bd2909eb03.png)

**Comment by mshukla1** [comment]
Verified. Problem is fixed.
