### ISSUE TITLE
Disconnect in names between feature group and overview-alpha

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#869]
In the table the gene names are different on the list vs the overview page.
![screen shot 2016-08-19 at 12 19 31 pm](https://cloud.githubusercontent.com/assets/11475316/17816480/504e521e-6607-11e6-9f71-298a7bb31682.png)
![screen shot 2016-08-19 at 12 19 22 pm](https://cloud.githubusercontent.com/assets/11475316/17816479/504ca7de-6607-11e6-8767-548a19bc702b.png)

**Comment by ARWattam** [comment]
the name is coming from the Figfam and not the plfam, but we had to go to production to see that.
![screen shot 2016-08-19 at 12 22 36 pm](https://cloud.githubusercontent.com/assets/11475316/17816559/b75f857c-6607-11e6-94c0-72e8425d968b.png)

**Comment by mshukla1** [comment]
Verified.
