### ISSUE TITLE
Red text in upload makes me thing I've already made an error

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#87]
The red comes up even if I haven't started uploading yet; typically you see the red when you've already tried some action and didn't do the right thing.

![screen shot 2015-03-23 at 11 47 11 am](https://cloud.githubusercontent.com/assets/2152226/6785246/71e9e528-d152-11e4-800c-5e55d350ff8e.png)

**Comment by dmachi** [comment]
I will change it to a different color.  This was added by request to make a large warning about this before people try to upload.
