### ISSUE TITLE
Protein Family Sorter Table: When a family selected, download and idmap buttons are not working

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#871]
The green bar actions for Download, ID MAP, Pathways are not working

![image](https://cloud.githubusercontent.com/assets/6361802/17819992/8d4eec3a-6618-11e6-888b-cfe72ecb502d.png)

**Comment by hyoo** [comment]
I would scope this to download and idmap button, since the fasta button is covered by other tickets(#872)

**Comment by maovt** [comment]
Download works now. ID Map doesn't work.

**Comment by mshukla1** [comment]
Verified the fix on alpha.
