### ISSUE TITLE
Protein Family Sorter Table: When a family selected, Green bar item "FASTA" not working 

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#872]
![image](https://cloud.githubusercontent.com/assets/6361802/17820064/e9df7a1e-6618-11e6-97d2-cb6c3eb4c0cb.png)

**Comment by mshukla1** [comment]
I just checked, both fasta and ID mapping are not working from the protein family table toolbar. 

-Maulik

**Comment by hyoo** [comment]
fixed and will be available on alpha soon.

**Comment by maovt** [comment]
Viewing fasta works now, but on the fasta page, the download button doesn't work.

**Comment by hyoo** [comment]
this is a problem of a FASTA viewer. not protein family sorter. I have created a new ticket (#936).

**Comment by hyoo** [comment]
per @maovt 's comment, I am closing this ticket.
