### ISSUE TITLE
Genome list with genome groups

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#874]
Select one or more genome groups from workspace, go to genome list view. 
The header shows the entire path for the genome groups. Given that all genome/feature
groups are in the same directory, I think we should display only group names, instead of 
the whole path. 

-Maulik

<img width="897" alt="screen shot 2016-08-19 at 1 53 44 pm" src="https://cloud.githubusercontent.com/assets/1236463/17820869/7726bac2-6614-11e6-97e9-553cab0c96bf.png">

**Comment by dmachi** [comment]
Fixed.
