### ISSUE TITLE
Visit TB@PATRIC button on Supporting TB community carousel item goes to blank page

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#876]
https://www.alpha.patricbrc.org/view/disease/TB

**Comment by mshukla1** [comment]
As a temporary fix, we are pointing the link from the carousal to the Mycobacterium taxon overview page. 

Not sure whether this is sufficient as a permanent  solution, or do we need the current TB@PATRIC page implemented on alpha. 

-Maulik

**Comment by rkenyon** [comment]
Appears to be completed.
