### ISSUE TITLE
Transcriptomics Comparison Tab: select a comparison, green bar items DOWNLOAD, FASTA not working

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#877]
![image](https://cloud.githubusercontent.com/assets/6361802/17822204/c14b99b0-6623-11e6-83cd-7a4907c2c0b6.png)

**Comment by mshukla1** [comment]
Trascriptomics experiments and comparison selection toolbar should not have fasta download. 

Please remove it. 

-Maulik

**Comment by maovt** [comment]
Removed FASTA button

**Comment by maovt** [comment]
Will be pushed to the new build

**Comment by mshukla1** [comment]
Verified on beta.
