### ISSUE TITLE
ALL Browse Data icons on home page below carousel give 404 error

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#878]
https://www.alpha.patricbrc.org/Genomes
https://www.alpha.patricbrc.org/GenomicFeatures
https://www.alpha.patricbrc.org/SpecialtyGenes
https://www.alpha.patricbrc.org/ProteinFamilies
https://www.alpha.patricbrc.org/Pathways
https://www.alpha.patricbrc.org/Transcriptomics

**Comment by dmachi** [comment]
URLs fixed.
