### ISSUE TITLE
Broken links on home page in "What Can I Do @ PATRIC" section of home page

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#879]
The following give 404 error
Protein Family Sorter:
https://www.alpha.patricbrc.org/FIGfam?cType=taxon&cId=131567&dm=&bm=tool
Genome Metadata:
https://www.alpha.patricbrc.org/GenomeList?cType=taxon&cId=2&dataSource=&displayMode=&pk=
Comparative Pathway Tool:
https://www.alpha.patricbrc.org/PathwayFinder?cType=taxon&cId=&dm=
Gene Page Transcriptomics:
https://www.alpha.patricbrc.org/TranscriptomicsGeneExp?cType=feature&cId=18154431&sampleId=&colId=&log_ratio=&zscore

**Comment by dmachi** [comment]
Links Fixed. Will be deployed to alpha soon.
