### ISSUE TITLE
Tabs: changes to mouseover / tooltips 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#881]
Taxonomy: 
The "Taxonomy" tab provides taxonomy subtree for the current taxon level. 

Phylogeny: 
The "Phylogeny" tab provides order or genus level phylogenetic tree, constructed using core protein families. 

Genomes:
The "Genomes" tab contains a list of all genomes associated with the current view and their metadata"

Sequence Tab: 
The "Sequences" tab contains a list of genomic sequences (e.g. chromosomes, plasmids, contigs) for genomes associated with the current view

Specialty Genes: 
The "Specialty Genes" tab contains a list of specialty genes (e.g., antimicrobial resistance genes, virulence factors, drug targets, and human homologs) for genomes associated with the current view

Browser:
The "Browser" tab shows genome sequence and genomic features using linear genome browser

Circular Viewer:
The "Circular Viewer" tab provides circular overview of the entire genome and its genomic features

Transcriptmics: [gene level]
The "Transcriptomics" tab shows gene expression data available for the current gene

Correlated Genes: 
The "Correlated Genes" tab shows list of genes from the same genome with correlated expression profiles

**Comment by dmachi** [comment]
Fixed.
