### ISSUE TITLE
Feature list: bugs in filter conditions

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#884]
I went to Borrelia feature list, by default it shows PATRIC CDS. 

Searched for keyword glycolysis, it shows ALL genes matching glycolysis, previous filters for PATRIC and CDS are not applied, even though they are still displayed on the page. 

Next, I clicked X next to keyword to remove it, it ended up removing other filters as well. 

Below are the series of screenshots. 

-Maulik

<img width="710" alt="screen shot 2016-08-19 at 5 07 25 pm" src="https://cloud.githubusercontent.com/assets/1236463/17825709/e682b95a-662f-11e6-92f5-f95e0e218712.png">

<img width="1040" alt="screen shot 2016-08-19 at 5 07 48 pm" src="https://cloud.githubusercontent.com/assets/1236463/17825710/eaa2d2cc-662f-11e6-92a7-b88ea6baab24.png">

<img width="1037" alt="screen shot 2016-08-19 at 5 08 08 pm" src="https://cloud.githubusercontent.com/assets/1236463/17825715/eea132c4-662f-11e6-9813-7af35b00d81d.png">

**Comment by dmachi** [comment]
Fixed, will be on alpha shortly.

**Comment by mshukla1** [comment]
Thanks. Verified the fix on alpha.
