### ISSUE TITLE
Global search: table default sorting 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#886]
Global search -> everything -> "MCR-1" -> Genomic Features: 125 -> result table

The default sorting for global search result should be based on the score, not by any other attributes....otherwise it is very hard to find the top hits! 

-Maulik

**Comment by dmachi** [comment]
Changed the default for FeatureGrid and GenomeGrid to sort by score.

**Comment by mshukla1** [comment]
Thanks, looks good from the global search. 

As we discussed, we still need the following, but can be done after beta release. 
- Default sort for the feature list should be based on genome+chromosome+start. 
- We need a button to switch to default sorting and filters. 

-Maulik
