### ISSUE TITLE
Feature list overview: graph labels

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#887]
In the functional and taxonomic profiles: 

- The fonts in the graph look weird and different than all other graphs on the site! Need to be changed. I think fonts can be smaller, like other graphs. 

- The functions are fully visible when too long. Need mouseover tooltip showing full function.

**Comment by hyoo** [comment]
1. no special font was configured.
2. mouseover tooltip is already implemented.
3. I have implemented resizing bar width when the bar is too tick. this will be available on alpha soon.

**Comment by mshukla1** [comment]
fixes verified on beta.
