### ISSUE TITLE
Feature group view: header / group summary

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#890]
- The header should be made consistent in terms of styling with other headers. 

- Remove directory path in the header. All the feature groups are in the same default directory right now, so path in uninformative. 

- Group summary: change it from grid to non grid view, like on the genome/gene overview pages. 

<img width="581" alt="screen shot 2016-08-20 at 6 35 47 am" src="https://cloud.githubusercontent.com/assets/1236463/17830907/5e575506-66a0-11e6-9486-ec21a374fa61.png">

**Comment by hyoo** [comment]
will be available on alpha soon.

**Comment by mshukla1** [comment]
fixed, verified on beta.
