### ISSUE TITLE
Pathway may appears downstream from gene selection, but with no data mapped to it-alpha

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#893]
Gene selection from heatmap...choose pathway summary tool.  Select pathway.  Select map, and while the map loads, none of the genes appear on it.
<img width="1177" alt="screen shot 2016-08-20 at 8 18 07 am" src="https://cloud.githubusercontent.com/assets/11475316/17831139/f4277706-66ae-11e6-9024-8f412a5eae03.png">

<img width="1177" alt="screen shot 2016-08-20 at 8 18 23 am" src="https://cloud.githubusercontent.com/assets/11475316/17831136/db2dba62-66ae-11e6-98b9-24e457ba72a1.png">

<img width="1440" alt="screen shot 2016-08-20 at 8 17 48 am" src="https://cloud.githubusercontent.com/assets/11475316/17831140/09e1de6a-66af-11e6-85b5-5cadac90a952.png">

**Comment by hyoo** [comment]
I cannot reproduce this problem. Would you please provide url or some more detail (what genomes/genes selected?)

**Comment by mshukla1** [comment]
checked from both PF and transcriptomics heatmaps. Seems to be working fine.
