### ISSUE TITLE
P3 API repeat parameter

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#894]
Repeat parameters don't seem to make it into the query. At least via URL.

e.g. the bq parameter here

https://www.alpha.patricbrc.org/api/genome/?defType=dismax&rows=100&q.alt=%28%28genome_name%3A%28MG1655%29%29%29&bq=reference_genome%3ARepresentative%5E2&bq=reference_genome%3AReference%5E3&fl=genome_name%2Cgenome_id%2Creference_genome&qf=genome_name&wt=json&http_content-type=application/solrquery+x-www-form-urlencoded&http_accept=application/solr+json

**Comment by dmachi** [comment]
Do you need this to work for something for the beta release?  This is because the Express parser doesn't handle that case the way you want (the way solr does).

**Comment by aswarren** [comment]
The dismax parser that is being used to get the ordered selection of taxonomy divisions in the TaxonNameSelector.js was assuming this.
Currently it kind of works because genus is the last one stuck in so that's the one it uses. Which is probably an 80/20 of most needed promotion cases.
boostQuery:["taxon_rank:superkingdom^7000000","taxon_rank:phylum^6000000","taxon_rank:class^5000000","taxon_rank:order^4000000","taxon_rank:family^3000000","taxon_rank:genus^2000000"],

Not strictly necessary for beta.

**Comment by aswarren** [comment]
Stopped using dismax. Now using regular leucene parser. Like this:
https://www.alpha.patricbrc.org/api///taxonomy/?q=((taxon_name:*Escherichia*)%20OR%20(taxon_name:Escherichia))%20AND%20(taxon_rank:(superkingdom)%5E7000000%20OR%20taxon_rank:(phylum)%5E6000000%20OR%20taxon_rank:(class)%5E5000000%20OR%20taxon_rank:(order)%5E4000000%20OR%20taxon_rank:(family)%5E3000000%20OR%20taxon_rank:(genus)%5E2000000%20OR%20taxon_rank:(species)%5E1000000%20OR%20taxon_rank:*)&fl=taxon_name,taxon_id,taxon_rank,lineage_names&qf=taxon_name

**Comment by hyoo** [comment]
@aswarren @dmachi Is this still a valid issue or not?

**Comment by aswarren** [comment]
I'm sure its still valid in that the API doesn't do it. But the need is no longer there since I figured out how to do it on the regular lucene parser. @hyoo closing this. reopen if you need.
