### ISSUE TITLE
Global Search: optimization and advanced search options

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#896]
We need to optimize the global search for getting the desired results at the top, i.e. Reference/representative genomes, PATRIC CDSs, exact id/locus tag matches, etc by selectively boosting weight for certain fields. 

We also need advance search capabilities to support exact match, search against select fields, batch query, etc. 

Follow the detail requirements available at: 
https://docs.google.com/document/d/1B1xB_xRB5OLJBj-KhVfdch0Ytp7yXPCfFrPEJkU93Xc/edit

-Maulik

**Comment by dmachi** [comment]
The more capable search inputs...or, and, (), not  are working now.  There is not yet an advanced form to help a user populate this.  Spoke with Rebecca.  This is not needed for the Florida WS, bumping it to fix other bugs.

**Comment by mshukla1** [comment]
#777 
#688

**Comment by hyoo** [comment]
@maovt Would you check whether any actionable item left out? I closed #832 since you have fixed this one.

**Comment by chmao1** [comment]
We now support exact match and batch query. However, searching against select fields is not yet implemented.  I'm not sure whether this enhancement is still required. @mshukla1  please comment on this.

**Comment by chmao1** [comment]
Close this issue for now. Please reopen when advanced searching against select fields are needed and well designed.
