### ISSUE TITLE
Genome Browser: Upload user data 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#897]
Allow users to upload their own data in standard file formats (BAM, BigWig, GFF, etc) and display them as custom tracks. 

Genome browser is an important tool for providing integrated view of the multi-omics data and using comparing experimental data to annotations. We need to preserve the basic functionality that allow users to upload their data directly to genome browser and later provide tighter integration with the data in user workspace. 

-Maulik

**Comment by dmachi** [comment]
Fixed.
