### ISSUE TITLE
Circular viewer: support user data upload

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#900]
Support user data upload in standard file formats (i.e. gene list or coordinate list, with/without numeric values) and display them as custom tracks (heatmap, histograms, etc). 

Again, try to support the minimum functionality that is already available on production or make it better. 

-Maulik

**Comment by chmao1** [comment]
Implemented and available on alpha.

**Comment by dmachi** [comment]
Fixed
