### ISSUE TITLE
HPI/PPI Search and Visualization 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#901]
Add HPI/PPI Search and visualization. 

If needed, reimplement using Cytoscape to make it more integrated, interactive and enhance it to support future use cases. 

Prerequisite: updated HPI/PPI data in solr. 

-Maulik

**Comment by hyoo** [comment]
punting to March 2017.

**Comment by hyoo** [comment]
this is deployed as a part of 2017 March release.
