### ISSUE TITLE
Add Experiment view page

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#902]
global search -> searched for "hypoxia" -> clicked on one of the experiments -> when to

https://www.alpha.patricbrc.org/view/Experiment/354496

The header says "loading..." but it actually never loads the results. 

We need Experiment view page, similar to that on production: 
https://www.patricbrc.org/portal/portal/patric/SingleExperiment?cType=taxon&cId=2&eid=315319

<img width="1434" alt="screen shot 2016-08-24 at 11 55 21 am" src="https://cloud.githubusercontent.com/assets/1236463/17939916/3b8d9cba-69f2-11e6-8991-d58fee2fd208.png">

**Comment by maovt** [comment]
This page was not implemented. I added the page and made a pull request. This will be included in the next build.

**Comment by mshukla1** [comment]
I reviewed the page and it looks good.
