### ISSUE TITLE
DLP: Add data landing pages on alpha

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#904]
...all the DLPs on production, with graphs and links to other pages/tools on alpha. 

-Maulik

**Comment by hyoo** [comment]
All DLPs are available on alpha and linked from top nav menu.

**Comment by mshukla1** [comment]
Pages look good. 

Found few problems: 

- Links from the genome and pathway DLPs to pathway pages are not working. For example it links to the following url for H37Rv: 
https://www.alpha.patricbrc.org/view/Genome/83332.12#view_tab=pathways
Looks like it should be
https://www.alpha.patricbrc.org/view/Genome/83332.12#view_tab=pathways&filter=eq(annotation,PATRIC)

- M

**Comment by mshukla1** [comment]
#1187

**Comment by mshukla1** [comment]
fixed. verified on alpha.
