### ISSUE TITLE
Set up help/Jira queue for the beta site

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#905]
We have few possible options: 
1. Set up a new help email address and send tickets to a new project in jira.
   We can work with Dan to set this up before the beta release. 
2. Create a light weight help/feedback submission from with just subject and body. 
   The feedback can be submitted to jira using server side mail or using jira API. 
   We can make submission available only after log in, if we want to void spams.
   Advantage is that we can capture additional information, such as add "(beta)" to subject, 
   page url, user id/email, etc behind the scene to help debugging. The tickets can go to the 
   same JIRA queue as production, but can easily be filtered out using "beta" tag in subject. 

Dustin, let me know your thoughts/preference. 

-Maulik

**Comment by dmachi** [comment]
Spoke to Dan about this.  I'm going to be sending an email from a no-reply address that has the following in the subject:
[vVERSION] [beta]  

The body of the message itself will contain information such as the url, the user if logged in, and other contextual details in addition to the users message.

**Comment by dmachi** [comment]
This is implemented and on Alpha.

**Comment by rkenyon** [comment]
How are we looking for the beta release today?  I meant to dial in on the sys dev call yesterday, but lost track of time.

Thanks,
Ron

**Comment by dmachi** [comment]
The first two items are easy to change and I can change them this morning before the release.  The email address will take a little bit more effort as the handler only has user ID at the time (it will need to do a lookup into the user api to get the email) and even when that is the case, I won't be able to set the cc/watcher as I am just sending an email in.   The thank you message should ultimately come from JIRA not from the website.

**Comment by dmachi** [comment]
I've modified the subject line and pushed that change into alpha.  Moving this ticket to 3.2.x to address the other two suggestions in the future.

**Comment by dmachi** [comment]
This has been completed now.  The from address is populated either from the users account if they are logged in or if they provide the email address in the form (option appears when they are not logged in to do so).  Can also attach images now.
