### ISSUE TITLE
Phylogeny: Wrong tree displayed for Acinetobacter

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#911]
On alpha, the phylogenetic tree for Acinetobacter does not have Acinetobacter...rather it shows 
Escherichia/Shigella etc. 

https://www.alpha.patricbrc.org/view/Taxonomy/469#view_tab=phylogeny

-Maulik

**Comment by aswarren** [comment]
This is fixed now. Though despite increasing from 14 to 91 trees there still isn't one for Pseudomonas.
