### ISSUE TITLE
DLPs: add links to relevant tools / services

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#917]

**Comment by mshukla1** [comment]
@hyoo Can you or Chris add links to relevant services / tools on the DLP pages? 

...just links, no need for fancy icons. 

-M

**Comment by chris-c-thomas** [comment]
Will do

Sent from my iPhone

On Jul 16, 2018, at 6:23 AM, hyoo <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #917<https://github.com/PATRIC3/patric3_website/issues/917> to @chris-c-thomas<https://github.com/chris-c-thomas>.

**Comment by hyoo** [comment]
I will delegate adding links to Chris, and I will create a list to add. @chris-c-thomas please wait until I complete the list.

- Antibiotic Resistance: NA

- Genomes:
      Genome Assembly, Genome Annotation, Comprehensive Genome Analysis, 
      Similar Genome Finder, Variation Analysis, Tn-Seq Analysis, Phylogenetic Tree Building,
      Proteome Comparison

- Genomic Features:
      BLAST, Proteome Comparison

- Pathways:
      Comparative Pathway Service

- Protein Families:
      Protein Family Sorter Service

- Specialty Genes: NA

- Transcriptomics:
      Expression Data Import, RNA-Seq Analysis

**Comment by chris-c-thomas** [comment]
Okay, no problem.

Sent from my iPhone

On Jul 16, 2018, at 6:34 AM, hyoo <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #917<https://github.com/PATRIC3/patric3_website/issues/917>.

**Comment by mshukla1** [comment]
@chris-c-thomas 

Now that we have moved all DLPs to the doc site, can you please add these links and send it back to me for review?

**Comment by mshukla1** [comment]
I have added 
1) Assessing data and 
2)Relevant Services and Tools sections to all DLPs.
