### ISSUE TITLE
Scrambled text above protein page context cartoon

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#918]
<img width="147" alt="screen shot 2016-09-07 at 2 07 18 pm" src="https://cloud.githubusercontent.com/assets/2152226/18324916/8119e190-7504-11e6-850f-6a9625803f8e.png">

https://www.beta.patricbrc.org/view/Feature/PATRIC.866909.3.AHHF01000082.CDS.58964.61276.rev

**Comment by mshukla1** [comment]
@olsonanl, I can not reproduce it.

**Comment by hyoo** [comment]
I think this is an old version before we implement multiple tracks to avoid overlap.

**Comment by mshukla1** [comment]
seems to be fixed.
