### ISSUE TITLE
PFS: heatmap out of sync with table

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#919]
Brucella PF tab, applied keyword filters to see membrane proteins. Filtered families are shown 
correctly in table and heatmap. 

Then, I reset the filters, to show all families. They are correctly displayed in the table. However, 
the heatmap still shows only membrane proteins. 

-Maulik

https://www.beta.patricbrc.org/view/Taxonomy/234?and(eq(collection_date,%222011%22),or(eq(host_name,%22Mouse%2C%20Mus%20musculus%22),eq(host_name,%22Cattle%2C%20Bos%20sp.%22),eq(host_name,%22American%20bison%2C%20Bison%20bison%22)))#view_tab=proteinFamilies

<img width="1131" alt="screen shot 2016-09-07 at 2 15 47 pm" src="https://cloud.githubusercontent.com/assets/1236463/18325133/a88355bc-7505-11e6-93d1-7abdcc7bdf42.png">

<img width="1255" alt="screen shot 2016-09-07 at 2 15 59 pm" src="https://cloud.githubusercontent.com/assets/1236463/18325135/ad615e44-7505-11e6-8cdd-169b0bebdd23.png">

**Comment by hyoo** [comment]
fixed and available on alpha.
