### ISSUE TITLE
Get error when trying to download Excel file of Transcriptomics Gene List

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#92]
Get the error below when clicking on Download/Table/Excel file from this URL:

http://www.beta.patricbrc.org/portal/portal/patric/TranscriptomicsGene?cType=taxon&cId=2&dm=result&pk=&expId=10846&sampleId=&colId=&log_ratio=&zscore=#gs_0=-4355984623048542570

HTTP Status 500 -
type Exception report
message

description The server encountered an internal error () that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: An exception occurred processing JSP page /jsp/GetMainTable.jsp at line 14

11: 	String fileType = request.getParameter("GeneFileType");
12: 	String data = request.getParameter("data");
13: 
14: 	if (fileType.equals("xls") || fileType.equals("xlsx")) {
15: 		List<String> _tbl_header = new ArrayList<String>();
16: 		List<String> _tbl_field = new ArrayList<String>();
17: 		List<ResultType> _tbl_source = new ArrayList<ResultType>();

Stacktrace:
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:518)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:429)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:320)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:266)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
root cause

java.lang.NullPointerException
	org.apache.jsp.jsp.GetMainTable_jsp._jspService(GetMainTable_jsp.java:67)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:387)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:320)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:266)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
note The full stack trace of the root cause is available in the JBossWeb/2.0.0.GA_CP logs.

**Comment by hyoo** [comment]
This is due to the acceptable size of POST, which is configured in nginx. Current production doesn't work with this experiment as well, and works well with smaller experiments. I need to figure out right config for this issue.

**Comment by mshukla1** [comment]
Harry, the file downloads work for other experiments, but still doesn't work for this one. 

https://www.beta.patricbrc.org/portal/portal/patric/TranscriptomicsGene?cType=taxon&cId=2&dm=result&pk=&expId=10846&sampleId=&colId=&log_ratio=&zscore=#gs_0=-4355984623048542570

![screen shot 2015-06-10 at 12 42 05 pm](https://cloud.githubusercontent.com/assets/1236463/8088293/38c437d0-0f6e-11e5-845a-1fd698408b66.png)

**Comment by hyoo** [comment]
as I described above, this occurs only when you download a large data set. Works for small data set (https://www.beta.patricbrc.org/portal/portal/patric/TranscriptomicsGene?cType=taxon&cId=1763&dm=result&pk=&expId=318920&sampleId=&colId=&log_ratio=0&zscore=0)

**Comment by dmachi** [comment]
I had tagged this as part of the DataAPI, but I don't think that is really the case and we'll need to track down specifically where this is failing.  There are no size limits in nginx that would prevent this and in any case the POST to request this information isn't too large, it is the response that is large so I'm not sure that makes sense as to the source of this failure.
