### ISSUE TITLE
Remove the old JBoss image on the PATRIC web page

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#920]
See the image at the browser tab:
<img width="729" alt="screen shot 2016-09-07 at 3 14 53 pm" src="https://cloud.githubusercontent.com/assets/6361802/18325192/2b86ac54-750e-11e6-9180-fff23fee4f53.png">

**Comment by hyoo** [comment]
this if favicon. Not sure whether we have an alternative.
