### ISSUE TITLE
Pathway Tab: genome filters are not applied to pathway map

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#921]
Selected 14 genomes in Brucella from genome list, applied filter to change scope, went to pathway tab. It shows pathway comparison for 14 genomes. Clicked on TCA, the map shows all >500 Brucella genomes. 

https://www.beta.patricbrc.org/view/Taxonomy/234?and(eq(collection_date,%222011%22),or(eq(host_name,%22Mouse%2C%20Mus%20musculus%22),eq(host_name,%22Cattle%2C%20Bos%20sp.%22),eq(host_name,%22American%20bison%2C%20Bison%20bison%22)))#view_tab=pathways

<img width="1119" alt="screen shot 2016-09-07 at 2 27 18 pm" src="https://cloud.githubusercontent.com/assets/1236463/18325540/3e553064-7507-11e6-81b3-418abedc8561.png">

<img width="1185" alt="screen shot 2016-09-07 at 2 27 28 pm" src="https://cloud.githubusercontent.com/assets/1236463/18325543/42572bfe-7507-11e6-89a6-91128f787c30.png">

**Comment by hyoo** [comment]
this will be available on alpha soon.

**Comment by mshukla1** [comment]
fixed on beta.
