### ISSUE TITLE
DLP for pathways: the links for "Summary of Top 10 Pathways" not working

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#922]
The links in the "Summary of Top 10 Pathways" table don't work
<img width="1228" alt="screen shot 2016-09-07 at 3 27 15 pm" src="https://cloud.githubusercontent.com/assets/6361802/18325566/cb01e77a-750f-11e6-8ea9-e045bfab6d1e.png">

**Comment by mshukla1** [comment]
#1187

**Comment by mshukla1** [comment]
fixed. verified on alpha.
