### ISSUE TITLE
Pathway Summary: TCA map not shown 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#923]
selected all genes from TCA pathway, ran pathway summary, then selected from TCA from pathway summary page, and clicked on view map. The TCA map is not displayed. However, the TCA map IS available from the main pathway tab. 

<img width="972" alt="screen shot 2016-09-07 at 2 28 26 pm" src="https://cloud.githubusercontent.com/assets/1236463/18325650/d1e7baea-7507-11e6-99f6-3e7110651519.png">

<img width="1072" alt="screen shot 2016-09-07 at 2 30 04 pm" src="https://cloud.githubusercontent.com/assets/1236463/18325653/d477e474-7507-11e6-8c52-0c24a3242d2a.png">

**Comment by hyoo** [comment]
I cannot reproduce it. please provide url

**Comment by mshukla1** [comment]
https://www.beta.patricbrc.org/view/Taxonomy/234#view_tab=pathways

select TCA -> run pathway summary -> select TCA -> select view map.

**Comment by hyoo** [comment]
fixed and deployed
