### ISSUE TITLE
Specialty genes: no add to group function

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#924]
Specialty genes tab. The table action bar doesn't have add to group function. 

-Maulik

<img width="1029" alt="screen shot 2016-09-07 at 2 33 01 pm" src="https://cloud.githubusercontent.com/assets/1236463/18325686/0071ed9a-7508-11e6-9b11-4a7ec63a2593.png">

**Comment by chmao1** [comment]
Fixed and is available to verify.

**Comment by mshukla1** [comment]
verified on alpha.
