### ISSUE TITLE
Broken / misdirected links on data landing pages 

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#925]
Antibiotic Resistance: https://www.beta.patricbrc.org/view/DataType/AntibioticResistance
 - links from "Specialty Gene FAQs" and "Antibiotic Resistance and Other Clinical Metadata" should either link to static page or to new tab if we are keeping it in Production eNews for now. 

Genomes: https://www.beta.patricbrc.org/view/DataType/Genomes
 - link from "Genome Finder FAQ" should either link to static page or new tab if we are keeping in Production eNews.  Do we even have Genome Finder in Beta?

Genome Features: https://www.beta.patricbrc.org/view/DataType/GenomicFeatures
 - broken links "Genome Feature Types" and "Feature Table FAQs" 

Pathways: https://www.beta.patricbrc.org/view/DataType/Pathways
 - link from "Comparative Pathway Tool" should either link to static page or to new tab if we are keeping it in Production eNews for now. 

Protein Families: https://www.beta.patricbrc.org/view/DataType/ProteinFamilies
 - link from "Protein Family Sorter" should either link to static page or to new tab if we are keeping it in Production eNews for now. 

Specialty Genes: https://www.beta.patricbrc.org/view/DataType/SpecialtyGenes
 - links from "Specialty Gene FAQs" and "Antibiotic Resistance and Other Clinical Metadata" should either link to static page or to new tab if we are keeping it in Production eNews for now. 
 - Link from PATRIC_VF goes to production: https://www.patricbrc.org/portal/portal/patric/SpecialtyGeneSource?source=PATRIC_VF&kw=

Transcriptomics: https://www.beta.patricbrc.org/view/DataType/Transcriptomics
 - broken link "Transcriptomics FAQ" broken

**Comment by hyoo** [comment]
1. enews page is opened in a new tab.

2. PATRIC_VF still goes to production since we're missing the page. #903 

3. transcriptomics faq is fixed.

**Comment by mshukla1** [comment]
fixed on beta.
