### ISSUE TITLE
Phylogeny: selection not summarized in details pan

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#926]
Selected few genomes from phylogenetic tree, the number of genomes selected is not summarized 
in the details pan on the right. 

-Maulik

<img width="1269" alt="screen shot 2016-09-07 at 2 36 46 pm" src="https://cloud.githubusercontent.com/assets/1236463/18325875/ef442ac8-7508-11e6-8cd0-01496d54a3ff.png">

**Comment by aswarren** [comment]
Fixed in https://github.com/PATRIC3/p3_web/pull/328
