### ISSUE TITLE
eNews items on front page need to spawn in new tab.

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#930]
Currently  they go to the news item in the current tab/window.

http://enews.patricbrc.org/5097/patric-july-2016-release-features-over-7600-new-genomes-and-amr-panel-data-for-approximately-5400-genomes/

http://enews.patricbrc.org/5073/patric-may-2016-release-features-over-700-new-genomes-and-amr-panel-data-for-approximately-1800-genomes/

http://enews.patricbrc.org/5071/first-u-s-case-of-e-coli-resistant-to-colistin/

"Read More" http://enews.patricbrc.org/

**Comment by hyoo** [comment]
fixed and deployed on alpha

**Comment by hyoo** [comment]
I cannot recall the prev comment. but I made change anyway. will be available on alpha by Oct 12 noon.
