### ISSUE TITLE
Transcriptomics Gene List: heat map out of sync with gene table

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#931]
Went to heat map, applied clustering. Looks fine. 

Then, went back to table, sorted genes by locus tag, went back to the heatmap to see the gene order, however, the genes are still sorted by clustering. 

There is no way to "undo" clustering effect. 

-Maulik

**Comment by mshukla1** [comment]
Also, note that the view after default clustering are different between production and beta.  

https://www.patricbrc.org/portal/portal/patric/TranscriptomicsGene?cType=taxon&cId=1763&dm=result&pk=&expId=233094&sampleId=&colId=&log_ratio=&zscore=#gs_0=3376543450474988015

<img width="912" alt="screen shot 2016-10-25 at 11 58 13 am" src="https://cloud.githubusercontent.com/assets/1236463/19695840/5c97b2fe-9aaa-11e6-93c3-30b567ec9d6d.png">

https://www.alpha.patricbrc.org/view/TranscriptomicsExperiment/?eq(eid,(233094))

<img width="912" alt="screen shot 2016-10-25 at 11 58 03 am" src="https://cloud.githubusercontent.com/assets/1236463/19695839/59c241c0-9aaa-11e6-9991-66d01876b99a.png">

**Comment by hyoo** [comment]
reopen for verification. changed heatmap based on expression values from the heatmap value.

**Comment by hyoo** [comment]
wait.. my fix (f654671) was regarding clustering values (read value vs. heatmap value/count). order-matching is not working yet.

**Comment by hyoo** [comment]
reopen for verification.

**Comment by mshukla1** [comment]
@hyoo , I am still finding problems with heatmap coloring and sorting by gene order. Hard to explain in an email. Need to show them to you in person.

**Comment by hyoo** [comment]
this is fixed and available to review on alpha or beta (3.2.59)

**Comment by mshukla1** [comment]
fixed. verified on beta.
