### ISSUE TITLE
PFS: make PLfam default for taxon level tab

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#932]
Currently Protein Families display (and possibly other pages in pATRIC, not sure) default to FIGfams.  Don't you think they should now  default to  PATRIC genus-specific families (PLfams)?

**Comment by hyoo** [comment]
#864

**Comment by mshukla1** [comment]
For now, PGFam is default. Later, we will make PLfam default, based on selected taxon and genomes. 

-Maulik
