### ISSUE TITLE
Flagging Representative genomes

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#933]
I suggest to add one more column to the "Genomes" table display to flag all  Reference and Representative genomes.  If implemented, a user would be able to sort by this column - to quickly bring those genomes to the top

**Comment by dmachi** [comment]
Added a column called "Reference" into the available columns in the genome list.  It is hidden by default.

**Comment by mshukla1** [comment]
fixed. verified on alpha.
