### ISSUE TITLE
Transcriptomics gene list: not displayed for private dataset

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#934]
You can try to reproduce it by uploading the attached data using differential expression app. 

[Sangurdekar Microarray data - 2.xlsx](https://github.com/PATRIC3/patric3_website/files/460242/Sangurdekar.Microarray.data.-.2.xlsx)

<img width="886" alt="screen shot 2016-09-07 at 3 15 30 pm" src="https://cloud.githubusercontent.com/assets/1236463/18327007/f02e922a-750d-11e6-9d08-7145f791f238.png">

<img width="1156" alt="screen shot 2016-09-07 at 3 15 07 pm" src="https://cloud.githubusercontent.com/assets/1236463/18327008/f585520e-750d-11e6-93d1-c224e65ca901.png">

**Comment by hyoo** [comment]
#857

**Comment by mshukla1** [comment]
working now on beta.
