### ISSUE TITLE
In FASTA viewer, download button is not working

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#936]
for example,

https://www.alpha.patricbrc.org/view/FASTA/dna/?and(in(genome_id,(470.1737,470.1738,470.1765,696749.3,470.773,470.772,470.775,480119.5,1413216.3,557600.4,405416.6,400667.7,509173.8,470.771,1096995.4,1096996.4,1096997.4,470.774,1455315.5,497978.4,1401639.4,509170.6,980514.3,1100841.3,1400867.3,470.2423,470.2122,470.1295,470.1294,470.1345,470.1288,470.1575,470.1576,470.2026,470.1574,470.1579,470.1311,470.1310,470.1405,470.1763,470.1375,470.1867,470.1866,470.1869,470.1865,470.1864,470.1822,871585.3,1242245.3,106654.21,436717.3,48296.83,48296.84,1324350.3,62977.6,1789224.3,1809055.3,1608473.3,1407071.3,1646498.3,1197884.5)),in(figfam_id,(FIG00000001)))

**Comment by dmachi** [comment]
Fixed. Up on alpha soon.

**Comment by hyoo** [comment]
verified
