### ISSUE TITLE
Assembly failure on PacBio reads (Salmonella bax reads from workshop downloads)

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#937]
Has anyone ever had the reads assemble successfully?  I am preparing for the workshop and this job failed...twice.  Could someone check out and see why it failed?

**Comment by ARWattam** [comment]
When I look at the error report for the job, its blank.
<img width="287" alt="screen shot 2016-09-21 at 7 22 34 am" src="https://cloud.githubusercontent.com/assets/11475316/18709090/4a40fd8e-7fcc-11e6-8a3e-eddef0dda8f0.png">

**Comment by olsonanl** [comment]
I'm putting the error output in another comment to make this easier to read. Given that very first error it sounds like the upload did not succeed; and workspace pokes concur:

gally-4:release-2016-0922 olson$ ws-cat -a '/ARWattam@patricbrc.org/home/salmonella_1.bax.h5'
https://p3.theseed.org/services/shock_api/node/806e6260-5407-4cb9-b65f-a74e98983dd6
gally-4:release-2016-0922 olson$ ws-cat --shock -a '/ARWattam@patricbrc.org/home/salmonella_1.bax.h5'
gally-4:release-2016-0922 olson$ 

Rebecca, do you remember if you had any issues during the upload of this file?

**Comment by olsonanl** [comment]
olson@beech:/disks/p3/task_status/7a9026f3-0683-449a-af9a-9f2a58731caa$ cat stderr
GET WS => /scratch/tmp/fDrr02t6v3 salmonella_1.bax.h5 /ARWattam@patricbrc.org/home/salmonella_1.bax.h5
Error retrieving https://p3.theseed.org/services/shock_api/node/806e6260-5407-4cb9-b65f-a74e98983dd6: {"status":400,"data":null,"error":["Node has no file"]}
\@submit_cmd = $VAR1 = [
          'ar-run',
          '-r',
          'smart',
          '--single',
          '/scratch/tmp/fDrr02t6v3/salmonella_1.bax.h5'
        ];
Running ar-run -r smart --single /scratch/tmp/fDrr02t6v3/salmonella_1.bax.h5
Submission returns
Job ID: 18

Submitted job 18, waiting for results
+--------+---------+----------------------------+----------+-------------+
| Job ID | Data ID |           Status           | Run time | Description |
+--------+---------+----------------------------+----------+-------------+
|   9    |    9    |          Complete          | 1:01:32  |     None    |
|   10   |    10   |          Complete          | 1:00:58  |     None    |
|   11   |    11   | [FAIL] Data does not exist |          |     None    |
|   12   |    12   |          Complete          | 1:30:58  |     None    |
|   13   |    13   | [FAIL] Data does not exist |          |     None    |
|   14   |    14   | [FAIL] Data does not exist |          |     None    |
|   15   |    15   |          Complete          | 0:08:45  |     None    |
|   16   |    16   |          Complete          | 2:05:43  |     None    |
|   17   |    17   |           Queued           |          |     None    |
|   18   |    18   |           Queued           |          |     None    |
+--------+---------+----------------------------+----------+-------------+

Running pull: ar-get -w -p -j 18 | ar-filter -l 300 -c 5
HTTP error: Forbidden (HTTP status code 403)

Error downloading results from 18

**Comment by dmachi** [comment]
Bob, this was the upload question I pinged you about a week or two ago.   I’m not sure why her uploads were falling.  When I tested it with Rebecca, I could see that the data was sent (the UI went to 100% complete), but the files never showed up with any size associated with them in the workspace itself.   I discussed this with you the day after I had tested with Rebecca and on that day I tested myself using the same data files but uploading into Andrew’s workspace from my computer.  These uploads succeeded (and showed file size in the workspace).  It is not clear to my why it was failing for Rebecca.  At the time I asked you about it, you said you didn’t see anything odd about failures in the shock or workspace logs.

**Comment by dmachi** [comment]
I do note that the shock error at the top here shows status 400, Node has no file.  Below that however, we see HTTP error: Forbidden (HTTP status code 403).   The 403 generally means that authentication headers existed (or we’d see a 401 error), but that the request was still forbidden.  I’m not sure why that would be the case here.  

Dustin

**Comment by dawenx** [comment]
this issue is more than 1 year old, do we still have similar issue? @olsonanl

**Comment by olsonanl** [comment]
I think it was probably an upload problem that we can close.
