### ISSUE TITLE
problem with import of experiments?

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#94]
see screenshots - I'm not sure why there are so many more experiments in my beta workspace than my production workspace.   I haven't uploaded any directly into beta.
![production workspace with 8 experiments](https://cloud.githubusercontent.com/assets/1243115/6789278/8a3841d8-d175-11e4-8529-ea190d19240c.png)
![new workspace with 17 experiments](https://cloud.githubusercontent.com/assets/1243115/6789277/8a36c7d6-d175-11e4-80ee-9abc663854ca.png)

**Comment by dmachi** [comment]
I'm seeing these files in the export.  The data that is in Experiment Groups does seem to match what is shown in the productin patricbrc.org image above.  However, in the rwill1 folder, there are a number of experiments.  I'm not sure what the source of these is.  Perhaps they are failed attempts that you simply don't see in patric normally?

_0de974dc-042a-4d45-9003-e95f8d4c3998.json.metadata:{"name":"foobar","type":"job_result"}
_1227acc1-4510-4773-a3e1-5f535b638399.json.metadata:{"name":"this is an alternate title","type":"job_result"}
_2250416a-be99-4525-bbf8-c322b6d6622e.json.metadata:{"name":"try loading mtb rnaseq data after december release","type":"job_result"}
_25218840-7280-4dd2-990d-aadcc471c17e.json.metadata:{"name":"TB SysBio Hypoxia transcriptomics","type":"job_result"}
_273b3377-7da4-4c99-8461-16a1c1253a80.json.metadata:{"name":"ioeger","type":"job_result"}
_2f56bbc5-f97e-41b8-bdb8-24cee1354fb4.json.metadata:{"name":"this shouldn't work","type":"job_result"}
_54c3a13f-ef92-4118-ad8d-2cde513f2d14.json.metadata:{"name":"foo","type":"job_result"}
_58c9ff60-748d-45e8-adca-af75b9db1bcd.json.metadata:{"name":"fffffoooo","type":"job_result"}
_59addc59-ea85-412c-a48d-412dacf035ba.json.metadata:{"name":"ioeger","type":"job_result"}
_71551525-8f21-42af-b77a-edfc902ce9e0.json.metadata:{"name":"TB SysBio microarray data","type":"job_result"}
_7f2814da-0bd3-47cb-b377-5f8e64241a0e.json.metadata:{"name":"ext","type":"job_result"}
_8187710d-84b3-4278-865f-8d34a808f611.json.metadata:{"name":"Gene expression of E. coli MG1655 wild type and rpoS knock-out strains","type":"job_result"}
_8352e600-9910-4305-8dd4-d73c8ac8ee2a.json.metadata:{"name":"foo1","type":"job_result"}
_96b31051-501a-4f7f-b211-6cc349777463.json.metadata:{"name":"tb sys bio hypoxia","type":"job_result"}
_a8ae29cf-1439-442c-9644-a0432d1ff65f.json.metadata:{"name":"foo","type":"job_result"}
_aaa6570c-32a9-4bca-ace8-b5059d156c46.json.metadata:{"name":"tbsysbio","type":"job_result"}
_d345a9b0-7c95-495b-a28d-a0262d18316e.json.metadata:{"name":"F","type":"job_result"}
_e455f306-152b-4958-8ddd-8fadafbf8816.json.metadata:{"name":"TB SysBio hypoxia data for SG2","type":"job_result"}
_f6ab7ab3-be7b-4f04-abd5-2a9584667073.json.metadata:{"name":"tb sffo","type":"job_result"}

Maulik.  Can you check on Becky's Experiment folder to see if you have an explanation?

**Comment by rwill1** [comment]
I'm more than willing to believe that the extras are failed attempts - that would mean I have a slightly less than 50% history of successfully accomplishing a task - that seems about my speed :-)

**Comment by mshukla1** [comment]
The workspace dump and collections we used for transformation and shown on the beta site 
are based on the snapshot taken on February 10. 

So, you may not have added any experiments in beta site, but you may have deleted few experiments on the production site after we took the snapshot on February 10. If so, those changed are not reflected yet on the beta site. However, they will be, when we reexport/import workspaces before the release. 

-Maulik

**Comment by rwill1** [comment]
There is no such thing as a "sure thing" - but I say w/ 99% confidence that I have NOT deleted any experiments on the production website, probably ever, and even more probably not since 10-Feb.

**Comment by mshukla1** [comment]
I checked both the workspace json file and the collections and they both have 19 experiments with user name rwill1. So, all I can say at this point is that it is not a bug in the script that transforms the workspace. Once I have fresh workspace dump this morning and run the transformation,  I will check the number of experiments again.

**Comment by dmachi** [comment]
After an updated export from Polyomic, these groups still existed.  Maulik and Harry investigated and found these to be experiments that had been marked deleted.  He is adjusting his export script to ignore the deleted experiments now.
