### ISSUE TITLE
Error message won't go away from job details list-beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#942]
I clicked on a failed job to see if I could get some details, and a error box popped up...and then never went away.
<img width="1431" alt="screen shot 2016-09-21 at 3 07 15 pm" src="https://cloud.githubusercontent.com/assets/11475316/18725195/43fd2b5a-800d-11e6-8dd1-70d68f14661a.png">

**Comment by ARWattam** [comment]
I had to reload the page to finally get rid of it, but at least that was successful

**Comment by dmachi** [comment]
The box is too small in this case, we need a minimum size set for this Dialog.  Note that you can hit escape to close most any of the dialogs like this.

**Comment by mshukla1** [comment]
verified on beta.
