### ISSUE TITLE
Sequences download FASTA DNA not working

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#945]
The Sequences tab download function in the green bar
It is missing a couple of things:
genome_sequence instead of sequence
and the sort based on sequence id.

https://www.beta.patricbrc.org/api/genome_sequence/?eq(genome_id,9606.33)&http_download=true&http_accept=application/dna+fasta&sort(sequence_id)

**Comment by hyoo** [comment]
I fixed and will be available on alpha soon

**Comment by mshukla1** [comment]
Fixed. Verified on beta.
