### ISSUE TITLE
IDBA appears to be missing from auto assembly 

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#946]
I did an assembly of the E. coli MRSN genome for the workshop (same reads) and I can see from the Quast report that velvet and spades run, but no IDBA.  This is supposed to be part of auto.  Where is it?  If it didn't run because of some criterion that the reads didn't meet, shouldn't it say that somewhere in the report?  Or is there a bug and that assembly method just isn't running?

**Comment by mshukla1** [comment]
Fangfang, can you please check the issue and comment/close as appropriate.

**Comment by hyoo** [comment]
@levinas would you check whether this is still issue? if not, please close this.

**Comment by mshukla1** [comment]
We updated the version of IDBA, verified it is showing up in the auto assembly results.
