### ISSUE TITLE
Best contigs should be labeled as BEST in the assembly job

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#947]
As I could not see the IDBA assembly, I thought that the contigs.fa on the assembly job report might be that.  Its not...its the best assembly.  I think the word "best" should be associated with it to avoid confusion...also to avoid users downloading the same contigs twice in their confusion.

**Comment by AllanDickerman** [comment]
We will address this in the new assembler system. Make it unambiguous which contigs are to be used.

**Comment by AllanDickerman** [comment]
Solve with next assembler system soon.
