### ISSUE TITLE
Gene neighborhood summary on top of gene summary page could be more helpful

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#948]
Are we planing on replacing that with something else?  If not...when you mouse over, it should show the RefSeq gene locus and the name.  Having the PATRIC id is not that helpful, and not having the name makes the whole thing more frustrating than useful.
<img width="885" alt="screen shot 2016-09-25 at 9 45 42 am" src="https://cloud.githubusercontent.com/assets/11475316/18815715/5bfec30c-8306-11e6-8aa3-04f10dc1f6ca.png">

**Comment by mshukla1** [comment]
I thing the gene neighborhood  cartoon will stay. Agree, that it needs to have RefSeq locus tags in the mouse over.

**Comment by hyoo** [comment]
fixed and will be available on alpha soon.

**Comment by mshukla1** [comment]
fixed, verified on beta.

**Comment by olsonanl** [comment]
It should also have the gene function, and clicking on a gene should recenter the display. Otherwise you can't walk all the way down the genome using it.

**Comment by hyoo** [comment]
now mouseover displays product and gene is clickable (move to the corresponding gene page)

**Comment by mshukla1** [comment]
all fixes verified on beta.
