### ISSUE TITLE
Why don't we link to the SEED viewer from the new gene page on beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#949]
The SEED viewer is one of the more valuable links on the public site.  Why have we lost this?
<img width="1353" alt="screen shot 2016-09-25 at 9 57 33 am" src="https://cloud.githubusercontent.com/assets/11475316/18815726/ca6486b0-8306-11e6-9a72-5fe13965364a.png">
<img width="1004" alt="screen shot 2016-09-25 at 9 58 32 am" src="https://cloud.githubusercontent.com/assets/11475316/18815727/ca69154a-8306-11e6-9cbf-e25208ac0735.png">

**Comment by mshukla1** [comment]
Because only about 25000/80000 genomes are in seed, which means majority of the links will lead to error. It was removed by popular demand! 

The goal is to get most of the functionality in seed to PATRIC, starting with the compare region view and literature references in The next release (Oct).

**Comment by ARWattam** [comment]
I still think its a mistake to remove this.  There is absolutely no way to get to subsystems now, and those users who like it are forced to annotate the same genome in RAST and PATRIC.

----- Original Message -----

**Comment by mshukla1** [comment]
I am fine with having the links, as long as people don't start complaining again about broken links. 

Also, keep in mind that, for the same pegs, the annotations in PATRIC are updated frequently, but they are not updated in pseed since we annotated the genomes. So, there will be discrepancies. 

-Maulik

**Comment by hyoo** [comment]
We are planning to work on subsystem view.

@ARWattam if we provide subsystem info, do we still need a link to SEED viewer? 
@mshukla1 
Do you think we can close this and make sure the subsystem deployed by May/June ?

**Comment by ARWattam** [comment]
I guess we can close it.  There isn't a one to one between the two anymore,
anyway.

Rebecca
