### ISSUE TITLE
Differential Expression App job failures using the provided data set

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#95]
When I use the Differential Expression data upload form, the job failed 2x when I clicked Submit.  Also had non-repeatable problems/delays during upload process.  I used the SampleGenes.xlsx file provided in the Help on the form.
![transcriptomics app fail](https://cloud.githubusercontent.com/assets/3188570/6789339/e7d4896e-d175-11e4-8c02-55f45da08f09.PNG)

**Comment by aswarren** [comment]
A change to the data API necessitated a change to the expression app. An update has been committed. Just waiting for a redeploy.

**Comment by aswarren** [comment]
This needs a redeploy in order to resolve.

**Comment by aswarren** [comment]
Redeploy fixed this. Closing.
