### ISSUE TITLE
Load files on page with genome annotation results-beta?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#950]
There's a load file row on my genome annotation results, and it is altering the image on the page.  What is this?
<img width="673" alt="screen shot 2016-09-28 at 1 45 43 pm" src="https://cloud.githubusercontent.com/assets/11475316/18925426/f50e30f0-8581-11e6-95c2-6275859eaf5d.png">

**Comment by mshukla1** [comment]
looks better now. verified on beta.
