### ISSUE TITLE
No indication of private or public genome in search

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#951]
I'm searching for a private genome doing global search.  We used to be able to filter on private or public in the genome results.  I get the following results...if I am a new PATRIC user (like somebody at the workshop), there is no indication for me to be able to find the genome I annotated that has the same name as the public genome.
<img width="1043" alt="screen shot 2016-09-28 at 1 50 24 pm" src="https://cloud.githubusercontent.com/assets/11475316/18925663/deeb0748-8582-11e6-815b-ce3e8b9e31b7.png">

**Comment by dmachi** [comment]
Need a column added to the tables that shows whether each row is public or private.  You can filter for this now, but it doesn't show in the table itself.  It should probably be represented by an icon so it doesn't have to take up much space if it is going to be shown by default.

**Comment by dmachi** [comment]
I've added the public column to the genome grid for now.  You can hide/show it like any of the other columns, but it is hidden by default.  Ultimately we should create a formatter that shows a public/private icon and displays the owner in a tooltip when mousing over the icon for private genomes.

**Comment by chmao1** [comment]
This was fixed.
