### ISSUE TITLE
jbrowse error on private genome

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#953]
I ran the genome Rebecca was having issues with (Lactococcus latis) as a private genome and tried to look at the peg in question. Here is the overview page for fig|1360.131.peg.649:

https://www.beta.patricbrc.org/view/Feature/PATRIC.1360.131.CP010050.CDS.644915.645088.fwd#view_tab=overview

when I go to genome browser I get the attached. 3.2.9beta.

![screen shot 2016-09-30 at 2 02 24 pm](https://cloud.githubusercontent.com/assets/2152226/19003464/87f807d4-8716-11e6-835c-7f52fae261aa.png)

**Comment by dmachi** [comment]
Fixed.  Will be on alpha soon.

**Comment by dmachi** [comment]
Fixed, wil be on alpha soon.

**Comment by hyoo** [comment]
verified.
