### ISSUE TITLE
I just submitted 3 proteome comparison jobs in beta and none of them ever showed up in the queue

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#955]
I submitted 3-and I got the message that the job was queued, but nothing ever showed up in the job list.  Just did it again, and the same thing happened.  Que pasa?
<img width="1048" alt="screen shot 2016-10-02 at 8 50 26 am" src="https://cloud.githubusercontent.com/assets/11475316/19020674/9232bef2-887d-11e6-8f5d-f5c49bda1e57.png">

**Comment by ARWattam** [comment]
Oh, and here's a minor point...The tool is listed as Proteome Comparison.  The In Progress message says "Genome Comparison"

**Comment by ARWattam** [comment]
Okay, so I checked later in the afternoon and it did complete...but why did it take so long to show up in the jobs list?  And why does it take the jobs list so long to load?

**Comment by dmachi** [comment]
Jobs list is represented by other active issues.
