### ISSUE TITLE
Pathway map not loading showing genes on private genome

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#958]
The pathway map loads, but the genes present in the genome never showed up.
<img width="1114" alt="screen shot 2016-10-02 at 5 06 42 pm" src="https://cloud.githubusercontent.com/assets/11475316/19023705/c7ee332e-88c2-11e6-872b-af8416773ae9.png">

**Comment by hyoo** [comment]
this works for me.

![958_works](https://cloud.githubusercontent.com/assets/1236467/19053922/9d353a72-8982-11e6-842a-37fab5fe5ae4.png)

**Comment by ARWattam** [comment]
Is it a private genome that you loaded?

----- Original Message -----

**Comment by hyoo** [comment]
yep

**Comment by hyoo** [comment]
Is this still occurring?

**Comment by ARWattam** [comment]
Just checked and it loaded for my private genome.

----- Original Message -----

**Comment by hyoo** [comment]
I am closing this ticket per Rebecca's comment.
