### ISSUE TITLE
Download button too small to notice when trying to download jobs

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#959]
First of all, people that have used PATRIC before will be looking for it on the right hand side.  Secondly, I KNOW where it is, and I still have to look for it!  Can't we make it bigger and more obvious?
<img width="667" alt="screen shot 2016-10-03 at 7 51 51 am" src="https://cloud.githubusercontent.com/assets/11475316/19036560/8b71e572-893e-11e6-9f2a-7aa014165b14.png">

**Comment by dmachi** [comment]
Neal has fixed the styling so it is on the right like it is supposed to be.  Will be up on beta soon.
