### ISSUE TITLE
searching with seed/taxonomy ids

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#96]
This might be my greatest pet peeve.  I search for a taxonomy id/seed genome ID (83334.1) in the genome browser and I basically get the right answer.  Then I search for (fig|83334.1.peg.4) and I get something totally off base.
![screen shot 2015-03-23 at 3 03 21 pm](https://cloud.githubusercontent.com/assets/7661533/6789413/1916c760-d16e-11e4-992e-3ccdbb5c2894.png)

![screen shot 2015-03-23 at 3 03 31 pm](https://cloud.githubusercontent.com/assets/7661533/6789417/206337a6-d16e-11e4-8c59-122046aeca97.png)

**Comment by hyoo** [comment]
Although this ticket is for current production, new website takes care of it and we're planning to have beta soon. So, I am closing this ticket.
 
https://www.alpha.patricbrc.org/search/?keyword(%22fig%7C1673609.3.peg.2413%22)
