### ISSUE TITLE
workspace scrolling/selection weirdness 

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#961]
1) in WS viewer, scroll down
2) select something
3) automatically brought back to top of view

![8u5nfioh1d](https://cloud.githubusercontent.com/assets/1194246/19048033/2a71d56c-896a-11e6-9979-2a8944c45811.gif)

**Comment by dmachi** [comment]
This happens because the table is current rendered from an array.  The workspace manager is polling for changes to the workspace folder you are in and so it is re-rendering it.  We’ll need to do this a different way to avoid that.

Dustin

**Comment by nconrad** [comment]
@dmachi this turned out to be that update_meta was being called whenever a row was selected, which in turn would refresh the list afterwards.  It's fixed, but will look into more general approach like using models in future.

**Comment by mshukla1** [comment]
yeah, that jumping was really annoying. thanks for fixing it. verified on beta.
