### ISSUE TITLE
fix model page styling on beta

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#962]
![image](https://cloud.githubusercontent.com/assets/1194246/19048363/9c08b9f6-896b-11e6-9c12-8b98fce2b5e2.png)

vs

![image](https://cloud.githubusercontent.com/assets/1194246/19048368/a3dacb60-896b-11e6-8dfb-152d5b3bf8b2.png)

**Comment by dmachi** [comment]
That page uses some old styling from p2.css that we don’t include any more that uses some (IMHO) weird relative/absolute position stuff.  It could be much cleaner and not require fancy css to do what we need here.

**Comment by mshukla1** [comment]
fixed. verified on beta.
