### ISSUE TITLE
Pathway map on private genome loads on chrome but not on firefox

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#963]
And yes, I cleared my cache on firefox!

Here's the same private genome pathway map on chrome:
<img width="1431" alt="screen shot 2016-10-03 at 6 42 09 pm" src="https://cloud.githubusercontent.com/assets/11475316/19056783/5a6fb11a-8999-11e6-9601-4351a834373d.png">

And here's the same pathway on firefox (after clearing the cache!):
<img width="1436" alt="screen shot 2016-10-03 at 6 44 25 pm" src="https://cloud.githubusercontent.com/assets/11475316/19056802/72012d18-8999-11e6-84b8-65f0c237e957.png">

**Comment by ARWattam** [comment]
I will test in both chrome and firefox from now on, unless you tell me we are abandoning one over the other.

**Comment by hyoo** [comment]
oh, that's useful info. I will test on firefox from now on. I will check this issue as well.

**Comment by hyoo** [comment]
My private genome works on firefox. Which version of firefox are you using? Mine is 49.0.1

<img width="1217" alt="963_works" src="https://cloud.githubusercontent.com/assets/1236467/19080508/ee6ffe78-8a1c-11e6-8076-7c348b2d165a.png">

**Comment by ARWattam** [comment]
And my Firefox is 43.0.4

Maybe that is the issue.

Rebecca

----- Original Message -----

**Comment by ARWattam** [comment]
I updated Firefox and then the pathway map was painted with the genes.  Hooray!

**Comment by mshukla1** [comment]
It works for private genomes in firefox. verified on beta.
