### ISSUE TITLE
Search doesn't work for terms with quotes

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#964]
If you search for

   RNA-2',3'-PO4:RNA-5'-OH ligase

you don't get a result back.  Explicitly adding quotes doesn't seem to help.

Underlying solr search works properly:

http://localhost:8983/solr/genome_feature/select?q=product%3A%22RNA-2'%2C3'-PO4%3ARNA-5'-OH+ligase%22&fl=patric_id%2Cproduct&wt=json&indent=true

{
  "responseHeader":{
    "status":0,
    "QTime":0,
    "params":{
      "q":"product:\"RNA-2',3'-PO4:RNA-5'-OH ligase\"",
      "indent":"true",
      "fl":"patric_id,product",
      "wt":"json"}},
  "response":{"numFound":35910,"start":0,"docs":[
      {
        "patric_id":"fig|991.19.peg.706",
        "product":"RNA-2',3'-PO4:RNA-5'-OH ligase"},
      {
        "patric_id":"fig|991.16.peg.706",
        "product":"RNA-2',3'-PO4:RNA-5'-OH ligase"},
      {
        "patric_id":"fig|991.18.peg.706",
        "product":"RNA-2',3'-PO4:RNA-5'-OH ligase"},
      {
        "patric_id":"fig|991.23.peg.706",
        "product":"RNA-2',3'-PO4:RNA-5'-OH ligase"},
      {
        "patric_id":"fig|991.24.peg.706",
        "product":"RNA-2',3'-PO4:RNA-5'-OH ligase"},
      {
        "patric_id":"fig|991.21.peg.706",
        "product":"RNA-2',3'-PO4:RNA-5'-OH ligase"},
      {
        "patric_id":"fig|991.17.peg.706",
        "product":"RNA-2',3'-PO4:RNA-5'-OH ligase"},
      {
        "patric_id":"fig|991.22.peg.706",
        "product":"RNA-2',3'-PO4:RNA-5'-OH ligase"},
      {
        "patric_id":"fig|991.12.peg.706",
        "product":"RNA-2',3'-PO4:RNA-5'-OH ligase"},
      {
        "patric_id":"fig|991.14.peg.706",
        "product":"RNA-2',3'-PO4:RNA-5'-OH ligase"}]
  }}

**Comment by dmachi** [comment]
Working on the API side fix to this, but don't want to change right before the workshop.  I've put a temporary fix into the ui that simply strips out these characters when users search for them, which solves the problem as well.  When the API fix is in, will remove this hack.

**Comment by dmachi** [comment]
This will be up on alpha soon.  This fix will take care of the WS milestone, bumping this ticket to a future milestone.

**Comment by hyoo** [comment]
verified this is working on production.
