### ISSUE TITLE
Search: finding a set of genomes from a list of ids

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#965]
## PATRIC created PATRIC-559:

```
        Summary: [beta] finding a set of genomes from a list of ids.
            Key: PATRIC-559
            URL: https://jira.cels.anl.gov/browse/PATRIC-559
        Project: PATRIC
     Issue Type: Bug
       Reporter: PATRIC
       Assignee: Rebecca Wattam
```

Version: 3.2.12 beta
URL: https://www.beta.patricbrc.org/
User ID: brettin

Can I do a search for a set of genomes? It appears the default is AND. I 
don't see how to do OR.

GENOMES that match all of the keywords "1403933.3", "562.5211", "562.5155", 
"935296.3", "685445.4", "548.35", "548.34", "1439323.3", "1439322.3", 
"1439321.3", "1439320.3", "1400145.3", "1400144.3", "1400143.3", 
"1400142.3", "1400141.3", "1400140.3", "1400139.3", "1400138.3", AND 
"1028307.3" ( 0 Genomes )

**Comment by dmachi** [comment]
Already represented by other tickets
