### ISSUE TITLE
Searching for a gene on beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#966]
Walking through the old tutorial and looking trying to find the protein family for the mcr-1 genes.  It has not been a pleasant experience.  First I did it without filtering on the global search, which returned 11279 genomic features:
<img width="1434" alt="screen shot 2016-10-05 at 4 44 15 pm" src="https://cloud.githubusercontent.com/assets/11475316/19130906/4d05b0d2-8b1b-11e6-879d-019c3e3e4465.png">

Then I filtered on genomic features (why oh why can't we just call them genes???) and it returned the most confusing page I have ever seen, as well as 11460 hits.  Why the discrepancy?
<img width="961" alt="screen shot 2016-10-05 at 4 42 34 pm" src="https://cloud.githubusercontent.com/assets/11475316/19130945/6fabda6c-8b1b-11e6-990d-f129c994a6e7.png">

I understand what you're trying to do, but forcing the user to look at these graphs (which are somewhat confusing) and making them first FIND the tab to get them to the features and then CLICK on that is like making somebody watch an add on YouTube before letting them see their video.  Its more frustrating than rewarding.

**Comment by dmachi** [comment]
The count portion of this ticket is referencing #972

**Comment by hyoo** [comment]
from the global search result, linking to features tab may make more sense. Especially these two profiles are summary of top 10 function/taxon.  Dustin, would you change that? I guess you're working the global search.

**Comment by dmachi** [comment]
Yep, I already changed it where it says Genome Features in the top N results…I forgot to change it in the summary at the top, but have fixed it locally already.

**Comment by mshukla1** [comment]
fixed on beta.
