### ISSUE TITLE
Feature table: column width

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#967]
```
        Summary: [beta] feature table.
            Key: PATRIC-556
            URL: https://jira.cels.anl.gov/browse/PATRIC-556
        Project: PATRIC
     Issue Type: Bug
       Reporter: PATRIC
       Assignee: Rebecca Wattam
```

Version: 3.2.9 beta
URL: 
https://www.beta.patricbrc.org/view/Taxonomy/1491#view_tab=features&filter=and(eq(feature_type,%22CDS%22),eq(annotation,%22PATRIC%22))
User ID: KPNs_4_Houston

If you search for say, "clostridium botulinum" and click on the feature 
table, it renders a huge column for the check boxes and small columns for 
everything else.  Unfortunately I can't send a screenshot.

**Comment by dmachi** [comment]
I haven't been able to reproduce this.

**Comment by mshukla1** [comment]
I can't either!
