### ISSUE TITLE
Feature list view not even clickable on beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#969]
Okay...the frustration continues.  I at least hoped that I could click on either the name or the bar in the graph to get to a list of the genes that I was searching for, but I could only click and click in vain.  A dead end graphic doesn't do anybody any good, especially on this page when all the user wants is to get to the actual gene!
<img width="872" alt="screen shot 2016-10-05 at 4 52 16 pm" src="https://cloud.githubusercontent.com/assets/11475316/19131172/6203aede-8b1c-11e6-92e1-de00101c4270.png">

**Comment by ARWattam** [comment]
Sorry, wrong screenshot.  I meant to use this one:

<img width="977" alt="screen shot 2016-10-05 at 4 44 40 pm" src="https://cloud.githubusercontent.com/assets/11475316/19131181/6d6cf122-8b1c-11e6-8d2d-7e8db035a3eb.png">

**Comment by ARWattam** [comment]
This looks great.  This should be the default view:
<img width="1053" alt="screen shot 2016-10-05 at 4 55 37 pm" src="https://cloud.githubusercontent.com/assets/11475316/19131294/e9e6b828-8b1c-11e6-81f2-bc35b87d2404.png">

**Comment by dmachi** [comment]
I think we could make the list view the default, but what this ticket really says is that the Feature overview page is not useful.  As with the rest of the site, the intent is always default to the overview page not the list.  So we either need to make it useful or get rid of it.

**Comment by hyoo** [comment]
I think we already changed to feature list.

**Comment by mshukla1** [comment]
default is now table view. verified on beta.
