### ISSUE TITLE
How do you download a whole genome?

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#97]
I selected this E. coli genome from the genome table, and I clicked on "Download Genome Data" in the top left, but it had no memory of the genome I had selected.  On the download page it looks like their used to be a way to search and download, but I can't find it.

![screen shot 2015-03-23 at 3 07 59 pm](https://cloud.githubusercontent.com/assets/7661533/6789504/cebacbd4-d16e-11e4-8a04-1b81abcf52cc.png)

![screen shot 2015-03-23 at 3 09 57 pm](https://cloud.githubusercontent.com/assets/7661533/6789508/d7b36854-d16e-11e4-8c93-e2e3837b01a7.png)

**Comment by jimdavis1** [comment]
As a post script, I went back and clicked on the link for that first E. coli genome and got this:
![screen shot 2015-03-23 at 3 12 05 pm](https://cloud.githubusercontent.com/assets/7661533/6789545/0c44a358-d16f-11e4-8ae3-207c2b6b94c1.png)

**Comment by hyoo** [comment]
1. You can browse genome by taxonomy tree or a-z list, and you can also search by name, after you click Taxonomy Tree or A-Z List tab in the organism selector (right below, 1. Select organism(s)). 

2. this link was out-dated. I have fixed it and will be deployed in next release.
