### ISSUE TITLE
Numbers at top and bottom of the page do not line up following beta search

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#971]
At the top of the page it says there are 11460 genes, and at the bottom of the table it says there are only 5545.  Why the disconnect?
<img width="520" alt="screen shot 2016-10-05 at 5 02 10 pm" src="https://cloud.githubusercontent.com/assets/11475316/19131501/a083ac62-8b1d-11e6-9fc0-5f2dfa27b2f5.png">

**Comment by dmachi** [comment]
This is because there are filters (CDS and PATRIC annotation) filters applied (the yellow boxes) by default.
