### ISSUE TITLE
Another way that numbers don't add up on gene search in beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#972]
Here's the search I did without using the filter:
<img width="249" alt="screen shot 2016-10-05 at 5 10 53 pm" src="https://cloud.githubusercontent.com/assets/11475316/19131782/d3385e04-8b1e-11e6-97a4-98e3adf8afa0.png">
It returned 11,279 genome features (also called GENES by almost everybody in the world):
<img width="530" alt="screen shot 2016-10-05 at 5 11 00 pm" src="https://cloud.githubusercontent.com/assets/11475316/19131814/f35563d0-8b1e-11e6-8c4b-3d7b6348e116.png">
When I clicked on that 11,279 genome features (aka GENES) it takes me to a table that says there are 11,460 genome features (i.e. GENES):
<img width="530" alt="screen shot 2016-10-05 at 5 11 00 pm" src="https://cloud.githubusercontent.com/assets/11475316/19131867/296e7114-8b1f-11e6-8470-bb9398c0f576.png">

So I ask you...which number is correct?

**Comment by ARWattam** [comment]
Rats!  This one was supposed to be the final salvo!  Sorry...Its like when the percussion guy drops the cymbals 30 seconds before he's supposed to play them.
<img width="717" alt="screen shot 2016-10-05 at 5 11 14 pm" src="https://cloud.githubusercontent.com/assets/11475316/19131891/44a9cb04-8b1f-11e6-8297-1edc250af628.png">

**Comment by dmachi** [comment]
I'm not sure why the numbers don't match yet, but you also seem to be of the opinion that we should not be calling things Genomic Features.  I'm fine if we want to change that, but I thought that was discussed and debated years ago and I have no opinion on that other than what we call them should be consistent throughout the site.

**Comment by hyoo** [comment]
Maybe, the number discrepancy came from the query "feature_type:!source" in the global search. I am more leaning toward removing source features. @mshukla1 what do you think?

**Comment by dmachi** [comment]
I think you are probably correct about global search excluding source features and feature list including them.

**Comment by mshukla1** [comment]
fixed on beta.
