### ISSUE TITLE
Table showing taxonomy profile on Gene search results has messed up x axis numbers

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#973]
Probably because there are too many genes?
<img width="707" alt="screen shot 2016-10-05 at 5 17 30 pm" src="https://cloud.githubusercontent.com/assets/11475316/19131991/a811c322-8b1f-11e6-893e-4ce240f80bd0.png">

**Comment by hyoo** [comment]
Labels were just overlapped each other.

**Comment by hyoo** [comment]
Better limit up to a certain number of features for both performance and display perspective.

**Comment by ARWattam** [comment]
I agree
