### ISSUE TITLE
The table view is also unclickable in the graphic design of the Genome Features (aka genes) search on beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#975]
I really wanted to see why those repeat regions matched an mcr-1 search.  But alas, I was not able to click on them from the table.  I wonder if I will ever find out....The table, at least, should have clickable rows I think.
<img width="688" alt="screen shot 2016-10-05 at 5 20 22 pm" src="https://cloud.githubusercontent.com/assets/11475316/19132144/3e61abee-8b20-11e6-9dea-8911c8cbfb76.png">

**Comment by hyoo** [comment]
this is fixed and will be available on alpha soon.

**Comment by mshukla1** [comment]
fixed on beta.
