### ISSUE TITLE
Search: keep query string in he search box

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#978]
Version: 3.2.9 beta
URL: 
https://www.beta.patricbrc.org/view/GenomeList/?keyword(%22Lactobacillus%20casei%22)
User ID: KPNs_4_Houston

Whenever you search for something in the main search bar your query 
disappears, so if you need to edit it, you have to retype it again.

**Comment by dmachi** [comment]
This is intentional and to me is the common behavior, though I suppose we could change it.  This is a single page app, so if we didn’t clear it when you initially did the search, what would a user do that would end up clearing it?

**Comment by dmachi** [comment]
Fixed, though i'm not sure I agree with it.  Will be up on alpha soon.
