### ISSUE TITLE
figfam id.

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#98]
![screen shot 2015-03-23 at 3 25 48 pm](https://cloud.githubusercontent.com/assets/7661533/6789792/020f2fbe-d171-11e4-9c1a-e373e38ceca9.png)

![screen shot 2015-03-23 at 3 25 59 pm](https://cloud.githubusercontent.com/assets/7661533/6789786/fc027fe0-d170-11e4-8657-fc397a1dcb15.png)

**Comment by hyoo** [comment]
Can you explain a little bit more? What do you think is wrong? What is expected in your mind?

**Comment by mshukla1** [comment]
Not sure what is the problem here, not enough details. closing the ticket.
