### ISSUE TITLE
MSA either not scrolling to see full alignment, or two genes have no sequence

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#981]
I couldn't scroll to the right.
<img width="1376" alt="screen shot 2016-10-05 at 5 38 05 pm" src="https://cloud.githubusercontent.com/assets/11475316/19132654/aa11b99a-8b22-11e6-900f-a63a154b7684.png">

**Comment by ARWattam** [comment]
The gene is 562 aa long, so it should scroll.  
<img width="519" alt="screen shot 2016-10-05 at 5 48 04 pm" src="https://cloud.githubusercontent.com/assets/11475316/19132953/fdcd94fe-8b23-11e6-8df2-c0ca40cc0bcc.png">

**Comment by ARWattam** [comment]
Sorry, 516 aa in length.  I mistyped.

**Comment by aswarren** [comment]
Works.
