### ISSUE TITLE
Data download for private genomes not working

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#989]
Version: 3.2.9 beta
URL: https://www.beta.patricbrc.org/view/Genome/573.2806
User ID: KPNs_4_Houston

I clicked on the blue download icon in the top right of the screen for the 
genome landing page of a private genome and I got an error window that said 
"550 failed to change directory"

**Comment by dmachi** [comment]
This is because this icon incorrectly links to the FTP site and there are no downloads of private genomes there.  This should be using the Download Dialog that the green bar triggers when you click download -> more options.

**Comment by hyoo** [comment]
I have replaced with Advanced Download dialog, but still having a problem with private genome.

**Comment by hyoo** [comment]
will remove download button for private genomes
