### ISSUE TITLE
Source ID in drug target database table

### ISSUE THREAD

**Issue by cshenry** [PATRIC3/patric3_website#99]
Click on the source IDs in this table:
http://www.beta.patricbrc.org/portal/portal/patric/SpecialtyGeneList?cType=genome&cId=198215.6&kw=source:DrugBank#aP0=1&aT=0&key=1427142600513&kW=source:DrugBank&tId=

Looks like the link is out of date. I can't figure out where this number comes from.

**Comment by maovt** [comment]
Apparently, the URL links to DrugBank are no longer valid due to the site update. Maulik, could you make the corresponding changes?
