### ISSUE TITLE
Job Submission: file selector 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#991]
Version: 3.2.9 beta
URL: https://www.beta.patricbrc.org/app/SeqComparison
User ID: KPNs_4_Houston

I have two fasta files called KPN1530ec.  One a fasta of the contigs and 
the other is a fasta of the plasmid proteins.  Since the proteome 
comparison tool abbreviates the path in the genome selection, I can't tell 
the difference.

**Comment by mshukla1** [comment]
One file is in:  "home/KPN_Annotations”, and the other is in "home/KPN_Plasmid_Spades”.  My main complaint is that "home/../something” is almost entirely useless since (until we can share) everything will be in your home directory.  My genomes should have shown up as "../KPN_Plasmid_Spades/KPN1530ec", and "../KPN_Annotations/KPN1530ec”.  

Looking them up with the folder icon works by the way, but it is likely that I didn’t even try because of how many genomes I had.  I am attaching a screen shot, because I just discovered that you can sort them by clicking the column headers (which makes it easier) but the little arrow icon doesn’t appear unless you click on the column header, so you wouldn’t know that it sorts. 

PastedGraphic-15.png
![image](https://cloud.githubusercontent.com/assets/1236463/19161354/1694e7a4-8bb9-11e6-9197-74226880064e.png)

**Comment by chmao1** [comment]
@mshukla1 Could you clarify the requirement for this issue? The name label in the drop down list is implemented the same way for all app services. Do you want the label display to include more text (characters) in the drop down list or you want the selection table to show bigger arrow for sorting? The label display has limited space. Currently, only partial path is displayed.  I see that using the same sub-folder and file names can result in the same text display and can be very confusing. What's your suggested change?

**Comment by mshukla1** [comment]
@chmao1 I just checked, it seems this issue has been addressed by providing mouseover tooltip on the dropdown items, which show complete file path, instead of abbreviated one.  

I am closing the issue.
