### ISSUE TITLE
Search / feature list: download results

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#992]
Version: 3.2.9 beta
URL: https://www.beta.patricbrc.org/
User ID: KPNs_4_Houston

I am trying to download a table for "PGF_00059805". I can't do it on 
production or beta.

**Comment by mshukla1** [comment]
Here is some more information: 

Global search: "PGF_00059805" -> go to feature list -> download all results as text/csv/excel

text and csv came up blank....excel results in crash.

**Comment by dmachi** [comment]
I'm not seeing this problem at all.  All three work for me with this same search.  Need some more information.

**Comment by dmachi** [comment]
[patric3_genome_feature_query.txt](https://github.com/PATRIC3/patric3_website/files/514401/patric3_genome_feature_query.txt)

**Comment by dmachi** [comment]
Attached an example of what the text download downloaded for me.

**Comment by mshukla1** [comment]
ok, this seems to be working now!
