### ISSUE TITLE
Feature list: column selection resets when filters applied

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#993]
Version: 3.2.9 beta
URL: 
https://www.beta.patricbrc.org/view/GenomeList/?keyword(%22KPN573ec-combo%22)#view_tab=features&filter=and(eq(feature_type,%22CDS%22),eq(annotation,%22PATRIC%22),keyword(con.0031))
User ID: KPNs_4_Houston

I searched with a keyword on the filter table, but after the page refreshed 
with the search, it went back to the original list of columns, and blew 
away the columns that I needed.

**Comment by mshukla1** [comment]
Dustin, 

I was able to reproduce the problem. Go to feature list, add/remove few columns, apply keyword search...and the columns reset to default. 

-Maulik

**Comment by dmachi** [comment]
I'm not able to reproduce this.   The page should not be reloading when you add in keyword searches, it just redoes the query.  So I don't understand where this is happening.  Was this the keyword search by the filters or the global search?

**Comment by mshukla1** [comment]
Go to borrelia, feature tab, add / remove few columns. Now, search for transport and hit enter. Below are the screenshots. 

<img width="1128" alt="screen shot 2016-10-07 at 11 43 00 am" src="https://cloud.githubusercontent.com/assets/1236463/19198190/62b0b33c-8c83-11e6-8740-d8078f5ab680.png">

<img width="1123" alt="screen shot 2016-10-07 at 11 43 24 am" src="https://cloud.githubusercontent.com/assets/1236463/19198197/68833dc0-8c83-11e6-986a-cefdd5b3b4bc.png">

<img width="1127" alt="screen shot 2016-10-07 at 11 43 53 am" src="https://cloud.githubusercontent.com/assets/1236463/19198200/6c85b1b4-8c83-11e6-85fd-d7ddd2d6f380.png">

**Comment by dmachi** [comment]
Fixed. Will be on alpha soon.
