### ISSUE TITLE
Inconsistency in the term "Genomic Features"

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#994]
We use it in the global search, at the top of the search results, but further down in the page at the header for the genes, it says "Genome Features".
<img width="1431" alt="screen shot 2016-10-06 at 2 57 06 pm" src="https://cloud.githubusercontent.com/assets/11475316/19166398/52c8a604-8bd5-11e6-8c52-88e0c858bc7c.png">

Also, once you click on the number following the name, it says "Genome Features" at the top of the page.  
<img width="351" alt="screen shot 2016-10-06 at 2 58 41 pm" src="https://cloud.githubusercontent.com/assets/11475316/19166447/8352de8e-8bd5-11e6-9561-e9a19c62131d.png">

It is time for someone to make a choice....a brave, brave choice  Will it be "Genomic Features" or "Genome Features"?  Take care with your decision, as you will have to live with yourself after making it...

**Comment by mshukla1** [comment]
Decision: call it **Genomic features** throughout the site, instead of genome features. 

Action: change the global search dropdown and  search result labels to "Genomic Features". 

-Maulik

**Comment by dmachi** [comment]
Fixed.  Will be available in alpha soon.

**Comment by mshukla1** [comment]
@dmachi, I don't see it in alpha yet!

**Comment by mshukla1** [comment]
fixed. verified on alpha.
