### ISSUE TITLE
PFS: If I'm looking at genomes in the same genus, why are the cross-genus protein families the default?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#995]
It should be genus-specific families.
<img width="682" alt="screen shot 2016-10-06 at 3 26 08 pm" src="https://cloud.githubusercontent.com/assets/11475316/19167362/5894c230-8bd9-11e6-8419-875e56201ea5.png">

**Comment by hyoo** [comment]
what if user selected genomes across genre? I think pgfam is the safest option.

But I know Maulik once liked to check the taxon level and change to plfam in taxon view. I guess we can do something similar: check the common lineage of the selected genomes and see whether they share genus then change to plfam. But I think this is beyond the scope of BETA release. marking it feature enhancement.

**Comment by mshukla1** [comment]
Harry, can we at least check for the taxon level pages to decide if it is genus or below or higher taxon levels? 

If we are passing genome ids, we can counts the facet by genus and decide before loading data. 

-Maulik

**Comment by mshukla1** [comment]
Given taxonomy may change and users often choose incorrect taxonomy labels, I think it is safe to always show PGFam as default and let user choose PLfam, if they wish.
