### ISSUE TITLE
update node version

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#998]
https://nodejs.org/en/blog/vulnerability/september-2016-security-releases/

alpha: 4.4.3
beta: 4.1.0

Both are way behind. Please update to 4.6.0 LTS.

**Comment by dmachi** [comment]
Way behind is a bit of an overstatment, 4.4.3 is from April.  I will take care of these, but probably not before the FloridaWS.

**Comment by hyoo** [comment]
I have updated to 4.6.1 on alpha and beta.

used
curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -

as instructed in https://nodejs.org/en/download/package-manager/
