### ISSUE TITLE
Feedback: can't attach image

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#999]
Version: 3.2.8 beta
URL: 
https://www.beta.patricbrc.org/view/Genome/511145.12#view_tab=features&filter=and(eq(feature_type,%22CDS%22),eq(annotation,%22PATRIC%22),keyword(mdh))
User ID: undefined

This is sort of a meta-bug, but if you want us to use this, you have to 
enable the attachment of a screenshot.

**Comment by hyoo** [comment]
attaching file is available on production
